### ISSUE TITLE
Rancher Desktop Fails with - 4294967295

### ISSUE THREAD

**Issue by unixdaddy** [rancher-sandbox/rancher-desktop#1001]
Rancher fails with the screenshot futher down immediately on starting it.

**Windows Version**
Edition	Windows 10 Pro
Version	20H2
OS build	19042.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Rancher Version**
Rancher desktop 0.6.1 (0.6.0 also failed)

**See the logs for the errors**
[wsl-1.log](https://github.com/rancher-sandbox/rancher-desktop/files/7602773/wsl-1.log)
[background-1.log](https://github.com/rancher-sandbox/rancher-desktop/files/7602774/background-1.log)
[update-1.log](https://github.com/rancher-sandbox/rancher-desktop/files/7602776/update-1.log)

**Error Message**
<img width="416" alt="rancher-error" src="https://user-images.githubusercontent.com/8880529/143439332-5cf58d61-443c-459e-bedc-4f3af49c3534.png">

it then just sits there forever like this

![image](https://user-images.githubusercontent.com/8880529/143440134-b10a57c0-fe91-4ebe-8361-ac13de00335f.png)

**WSL information**
I see nothing in wsl --list output so it looks like it never downloads the kubernetes

wsl --status
Default Version: 2
Windows Subsystem for Linux was last updated on 03/11/2021
WSL automatic updates are on.
Kernel version: 5.10.60.1

**Comment by ericpromislow** [comment]
Hi, the only substantive error message in the three log files you sent is that in the command 

`wsl.exe --terminate rancher-desktop`

it's complaining that there's no such distribution (I really wish every error message would give specific names, because not all commands are run manually at a command-line prompt), but I think it's safe to assume that it can't find a distro called `rancher-desktop`. This would happen if it was getting deleted twice in a row. I'm not sure why we would be deleting it even the first time, especially when there's no info on migrating from an older version of Rancher Desktop.  By any chance, is this what's happening?

Before I suggest anything, it would be helpful to see the `k3s.log` file as well from that session, or another one that fails.

**Comment by gsimpson1130** [comment]
I have the same issue on the Window's build and Windows Home and Windows 11

[wsl.log](https://github.com/rancher-sandbox/rancher-desktop/files/7615443/wsl.log)
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/7615444/background.log)
[update.log](https://github.com/rancher-sandbox/rancher-desktop/files/7615445/update.log)

There are no K3 logs.
.

**Comment by dosgo** [comment]
So is mine.

**Comment by dosgo** [comment]
I have no problem using 0.6.1, it should be related to the kernel mirroring.

**Comment by mook-as** [comment]
For [these logs](https://github.com/rancher-sandbox/rancher-desktop/issues/1001#issuecomment-981272967), we're getting `There is no distribution with the supplied name.` when running [`printenv EXE_PATH`](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.6.1/src/k8s-engine/wsl.ts#L1007).  The [equivalent command on 0.7.1](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.7.1/src/k8s-engine/wsl.ts#L1226) still [spawns the distribution](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.7.1/src/k8s-engine/wsl.ts#L551).

The [original logs](https://github.com/rancher-sandbox/rancher-desktop/issues/1001#issue-1063520659) contain the same.

Looking at the callers closer, there _can_ be an issue, I think, if you switch to the _WSL Integration_ tab before startup finishes.  However, that should be generally harmless (that page won't load correctly, but it should continue starting).

@dosgo: could you explain which _kernel mirroring_ you're referring to?

**Comment by dosgo** [comment]
[wsl-exec.log](https://github.com/rancher-sandbox/rancher-desktop/files/7759460/wsl-exec.log)
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/7759463/background.log)
[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/7759464/k8s.log)
[update.log](https://github.com/rancher-sandbox/rancher-desktop/files/7759465/update.log)
[wsl.log](https://github.com/rancher-sandbox/rancher-desktop/files/7759466/wsl.log)

**Comment by dosgo** [comment]
C:\Users\DosGo\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.10.tar

**Comment by dosgo** [comment]
I have two pcs, one can be normal when replaced with 0.6.1, and the other is not normal with 0.6.1

**Comment by mook-as** [comment]
dosgo: Odd, the installer didn't seem to install WSL2 correctly for you.  It's reporting that it needs a kernel update.

> WSL 2 需要更新其内核组件。有关信息，请访问 https://aka.ms/wsl2kernel

Judging by the URL, it says:

> WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel

Please run `wsl --update` from an elevated command prompt, and then run `wsl --shutdown` from a normal one.

(This is completely unrelated to the previous comments in this issue.)

**Comment by dosgo** [comment]
0.6.1 is fine! Thank you very much, I installed wsl_update_x64.msi, but did not execute wsl --update, because it is not in the Microsoft documentation.

**Comment by dosgo** [comment]
Windows 11 runs "wsl --update" and you can use 0.7.1 in the future.

**Comment by jandubois** [comment]
I'm going to close this issue, as the original report relates to 0.6.1, and at least @dosgo reports that everything is fine with 0.7.1.

If any of the other participants on this issue still experience problems, please open a new issue and provide details!

**Comment by davidwuibaille** [comment]
wsl need Bios CPU virtualization Enable
