### ISSUE TITLE
Add debug logging in main process

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#1004]
_Originally posted by @adamkpickering in https://github.com/rancher-sandbox/rancher-desktop/issues/538#issuecomment-978113532_

**Comment by dpmerrill** [comment]
Questions:
- What is the "main" process?  Does this refer to the "main" directory in "src"?
- Do we want a new "main.log", or should messages go into an existing log?
- Should I just do a best-effort at debug logging interesting events and we can add more later if needed?
