### ISSUE TITLE
Enable debug level logging on WSL if possible

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#1006]
_Originally posted by @adamkpickering in https://github.com/rancher-sandbox/rancher-desktop/issues/538#issuecomment-978113532_

**Comment by adamkpickering** [comment]
Things to explore:
- Enable wpr logging as shown at https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually
- Something in wsl.conf?

**Comment by adamkpickering** [comment]
I explored a number of options - I've listed them below.

At https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configuration-setting-for-wslconfig, it discusses the `debugConsole` option in `.wslconfig`. This could come in handy if it were possible to capture the output to a file, but as far as I can tell it just prints the output to a console window. Additionally it only works on WSL 2 and Windows 11.

Another possibility is Windows Performance Recorder, for which there is a wsl.wprp file available (see https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually). This is tempting because it would give us WSL logs (even if they are in the binary `.etl` format). The way I would implement this is to run the command to start logging from the above link at RD startup, and then run the command to stop logging and write the log file upon RD shutdown, if debug mode is enabled. Unfortunately, the use of the `wpr` command requires that [Windows ADK](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install) is installed, which could be a headache. This might be worth it, but it is hard to tell.

There appears to be no `--debug`, `--verbose` or other such command in the `wsl` command. There is a `--verbose` option for the `--list` option (used to list distributions), but this is of little value to us.

Another thing I briefly looked at is command line auditing, which is mentioned [here](https://github.com/Microsoft/WSL/issues/3868#issuecomment-467129990). There are a lot of steps to set this up, and I'm not sure if they can be automated. To be honest I didn't look too hard at this one because of the setup complexity, and also because we can see which `wsl` commands we are running simply by adding log statements to our code in `WSLBackend.execWSL`.

So where does that leave us? I'd say WPR logging is tempting. But, I do not have a machine running windows at the moment so I would either have to get one, or someone else would have to implement it. @mook-as also raised the idea of logging the `wsl` commands that we call. We have a similar issue for this for `limactl`, so I definitely think this is something we should do. I am going to begin work on this.

**Comment by jandubois** [comment]
I agree that we definitely want to capture the `wsl` and `limactl` commands with all their arguments.

Ideally we want to also capture stdout/stderr, and include that in the log as well when the commands exit with a non-zero status code. Not sure if this is easily doable, but maybe we can create some wrapper that takes care of it "transparently"?

**Comment by adamkpickering** [comment]
Closing - logging of which `wsl.exe` commands are executed was added in commit `f4094d3`.
