### ISSUE TITLE
Enable debug level logging on everything else

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#1007]
Other things may include k3s, nerdctl, docker, and other things that run inside the VM. And possibly things that run outside of the VM. This one is open-ended.

_Originally posted by @adamkpickering in https://github.com/rancher-sandbox/rancher-desktop/issues/538#issuecomment-978113532_

**Comment by jandubois** [comment]
> This one is open-ended.

This is not really actionable; we should file specific logging requests when we cannot figure out problems without additional information.
