### ISSUE TITLE
Error starting VM due to missing `vde` on Linux

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#1031]
### Rancher Desktop Version

Commit dc578f9 (on main branch)

### Rancher Desktop K8s Version

N/A

### What operating system are you using?

Other Linux

### Operating System / Build Version

Pop OS

### What CPU architecture are you using?

x64

### Actual Behavior

Running `npm run dev` on the `main` branch results in a failure to start the VM.

### Steps to Reproduce

1. Start Rancher Desktop with `npm run dev`
2. Application should fail when starting VM

### Result

The VM fails to start with the message as shown in the screenshot below.

### Expected Behavior

Normal startup.

### Additional Information

![image](https://user-images.githubusercontent.com/19395776/144089172-54ed943f-7ab4-4d60-b847-5950e9fe5d35.png)

`vde` is associated with MacOS; we should not be getting references to it on Linux.

**Comment by evertonlperes** [comment]
Also detected on `openSUSE Leap 15.3`
![Screen Shot 2021-11-30 at 4 13 44 PM](https://user-images.githubusercontent.com/37411123/144136613-28e238f7-cf67-4191-8629-8e309f668501.png)

Steps to reproduce:
1. `sudo zypper ar --refresh https://download.opensuse.org/repositories/isv:/Rancher:/dev/rpm/isv:Rancher:dev.repo`
2. `sudo zypper install rancher-desktop`
3.  Should see the error message popping up after download k8s.

RD Dev version: `0.6.0-493-ge2e74ad` - [commit](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/1522947247)
K8s: `1.21.5(stable)`
