### ISSUE TITLE
Figure out notarization and signing for the M1 builds

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1051]
Using the same procedure as with the Intel builds removes the hypervisor entitlement from qemu.

**Comment by mattfarina** [comment]
@jandubois can we remove this now that the entitlement PR has landed?

**Comment by jandubois** [comment]
> @jandubois can we remove this now that the entitlement PR has landed?

I guess we can. I don't like that the current signing mechanism makes us add the hypervisor entitlement to all bundled binaries, and not just to qemu, but I don't think it really matters.
