### ISSUE TITLE
nerdctl with --file option fails on Windows

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1060]
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

forgot :)

### What operating system are you using?

Windows

### Operating System / Build Version

Home

### What CPU architecture are you using?

x64

### Actual Behavior

This is running inside an Ubuntu distro:

```
jan@DESKTOP-4992680:/mnt/c/Users/Jan/flask$ nerdctl image build -f foo/Dockerfile .
2021/12/02 11:52:32 Error unmounting /mnt/wsl/rancher-desktop/run/nerdctl-tmp.3021226780/input.4254969962: invalid argument
2021/12/02 11:52:32 Error parsing arguments: no such file or directory
[+] Building 0.0s (0/0)
error: could not find foo/: stat foo/: no such file or directory
FATA[0000] unrecognized image format
```

This happened the first time only for me (but a Slack user reports this happens to them every time). On subsequent runs the command seems to work, but still emits the unmounting error message.

The problem does not happen on macOS; it is most likely related to the `nerdctl-stub` mechanism.

### Steps to Reproduce

Try the `nerdctl image build` command with the `-f` or `--file` option and the `Dockerfile` in a non-default location.

### Result

see above

### Expected Behavior

I don't expect to see the error message, and I expect the command to work.

### Additional Information

https://rancher-users.slack.com/archives/C0200L1N1MM/p1638468605305200

**Comment by fernando-j-almeida** [comment]
I am the "Slack user". I get always the same error. If i run the build without "-f" options it works fine.
I can pull and run containers without a problem.
