### ISSUE TITLE
Error during app launch after 1st time installation

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1078]
### Rancher Desktop Version

0.7.0.beta.1

### Rancher Desktop K8s Version

1.21.0

### What operating system are you using?

Ubuntu

### Operating System / Build Version

21.10

### What CPU architecture are you using?

x64

### Actual Behavior

On 1st installation, I see below error during app launch. 

![image](https://user-images.githubusercontent.com/59538726/145066747-6df7126d-a00a-40b4-857e-2b638d966ee6.png)

I see below message in  `update.log`. All other log files are empty.

`2021-12-07T05:26:16.415Z: autoUpdater.hasUpdateConfiguration check failed: Error: ENOENT: no such file or directory, open '/opt/rancher-desktop/resources/app-update.yml'
`

### Steps to Reproduce

Install Rancher Desktop on ubuntu for the 1st time.

### Result

See `Actual Behavior` section.

### Expected Behavior

App should launch without errors.

**Comment by mook-as** [comment]
Is Virtualization supported on your machine? If you're on a VM, please ensure you have nested virtualization working.

Note that, as I understand it, VirtualBox does not currently support nesting Hyper-V.

**Comment by gunamata** [comment]
It looks like the hardware (very old) I am using is not compatible to enable virtualization.. 

i will close the issue.
