### ISSUE TITLE
Beta release doesn't start k3s 

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#1082]
### Rancher Desktop Version

0.7.0-beta.1

### Rancher Desktop K8s Version

1.21.6 (changing does not affect issue)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Beta Ring -- Build 22000.348 

### What CPU architecture are you using?

x64

### Actual Behavior

The UI comes up cleanly (and shows first use prompts after factory reset and reboot), Then I get an alert:

![image](https://user-images.githubusercontent.com/442274/145268788-7d301cf6-573c-482e-925c-e5f169a665b1.png)

K3s is not running after this.

### Steps to Reproduce

This seems to happen regardless of configuration (containerd/moby, k8s version). 

Based on initial debugging, might be an issue with my user name including a space. 

### Result

Some useful logs (will upload full directory in comment): 

```* /etc/fstab does not exist
Service `hwdrivers' needs non existent service `dev'
 * Caching service dependencies ... [ ok ]
 * /mnt/c/Users/Andrew Gracey/AppData/Local/rancher-desktop/logs/k3s.log: creating file
 * /mnt/c/Users/Andrew Gracey/AppData/Local/rancher-desktop/logs/k3s.log: correcting mode
 * /mnt/c/Users/Andrew Gracey/AppData/Local/rancher-desktop/logs/k3s.log: correcting mode
 * Starting k3s ...
 * supervise-daemon: Gracey/AppData/Local/rancher-desktop/logs/k3s.log does not exist

 * failed to start k3s
                                                   [ !! ]
 * ERROR: k3s failed to start```

### Expected Behavior

K3s should start up on boot or after reset.

### Additional Information

_No response_

**Comment by agracey** [comment]
[RD-gracey-0-7-0-beta1-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/7678334/RD-gracey-0-7-0-beta1-logs.zip)
Here's the logs folder if it's useful

**Comment by agracey** [comment]
Let me know if you need to get on a call and poke at things.

**Comment by mook-as** [comment]
From `wsl.exec.log`:
```
 * /mnt/c/Users/Andrew Gracey/AppData/Local/rancher-desktop/logs/k3s.log: creating file
 * /mnt/c/Users/Andrew Gracey/AppData/Local/rancher-desktop/logs/k3s.log: correcting mode
 * /mnt/c/Users/Andrew Gracey/AppData/Local/rancher-desktop/logs/k3s.log: correcting mode
 * Starting k3s ...
 * supervise-daemon: Gracey/AppData/Local/rancher-desktop/logs/k3s.log does not exist
```
So it's the space in the file name, probably.

**Comment by agracey** [comment]
Just tested that #1086 does fix this issue
