### ISSUE TITLE
Got an error, app is partly shut down but I need to use `kill (1)` to kill it.

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1087]
### Rancher Desktop Version

dev->0.7.0

### Rancher Desktop K8s Version

1.22.4

### What operating system are you using?

macOS

### Operating System / Build Version

Monterey 12.0.1

### What CPU architecture are you using?

x64

### Actual Behavior

Woke the machine up after 17 hours, and got this dialog box message:
`A JavaScript error occurred in the main process`:
```
Uncaught Exception:
Error: spawn /Users/ericp/workspace/rancher/desktop/resources/darwin/bin/docker EMFILE
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### Steps to Reproduce

Not sure how. Maybe let it sleep overnight.

### Result

I pressed OK, and can continue to use the app.

### Expected Behavior

No error messages, ever.

**Comment by jandubois** [comment]
@ericpromislow Not sure what we can do here. Do you want to try to repro with the 1.0.0-beta release, or should we close this?

**Comment by ericpromislow** [comment]
I haven't seen this problem since then, and it's more likely something we do on the dev side, so let's close it.
