### ISSUE TITLE
Rancher Desktop install blew away large portions of kube config (contexts and clusters)

### ISSUE THREAD

**Issue by dennisme** [rancher-sandbox/rancher-desktop#1093]
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

1.18.16

### What operating system are you using?

macOS

### Operating System / Build Version

10.15.7

### What CPU architecture are you using?

x64

### Actual Behavior

Post mac install, my ~/.kube/config was edited to add the rancher desktop context and server. In the process it also blow away all other servers and contexts that I had. I had a local backup so it wasn't a huge deal, but still this doesn't seem like the correct behavior. 

### Steps to Reproduce

Install and diff local kubeconfig 

### Result

servers and context sections fully replaced with rancher settings. 

### Expected Behavior

It appends to sections of the config file doesn't replace contexts or servers.

**Comment by mook-as** [comment]
Sorry to hear that — that _definitely_ isn't the intention; we do parse the kubeconfig (as YAML) and append our settings.  It would help a lot (since you have a backup) if you could attach a sanitized copy (replace all server addresses, user names, certs, etc. with short strings) so we can take a harder look.

**Comment by dennisme** [comment]
Yes I can, having local git repos for important things is helpful sometimes. Ill post a better comment later this evening if time allows, if not this weekend. Thanks @mook-as.

**Comment by jandubois** [comment]
@dennisme Did you manage to save a copy of the kubeconfig that got destroyed by RD?

I don't see any other reports of this happening, so I suspect it is somehow due to a partially malformed config file. Getting a copy to be able to repro would really help to investigate this further.

**Comment by dennisme** [comment]
Hey @jandubois apologies for the delay I was also unable to reproduce this. Sorry for the noise! 👍
