### ISSUE TITLE
limactl exited with code 1 (m1)

### ISSUE THREAD

**Issue by nbari** [rancher-sandbox/rancher-desktop#1095]
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

macOS

### Operating System / Build Version

12.0.1 (21A559)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

There was an unknown error starting Kubernetes: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

### Steps to Reproduce

`brew install --cask rancher` and open Rancher desktop

### Result

There was an unknown error starting Kubernetes: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

### Expected Behavior

No error

**Comment by jandubois** [comment]
The homebrew cask version does not support the M1; it is Intel-only.

The first version supporting the M1 is going to be 0.7.0. I assume the cask formula will be updated to install separate Intel and ARM versions, but it is outside our control, as the formula is maintained directly by the homebrew cask project.
