### ISSUE TITLE
Support configuration of default registry and mirrors for the CLI

### ISSUE THREAD

**Issue by janeczku** [rancher-sandbox/rancher-desktop#1100]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

With the `docker`/`nerdctl` CLI included in Rancher Desktop the default registry used for partially qualified image names is hardcoded to be `docker.io`. This makes working with the CLI inconvenient for users that are primarily using images stored on a private registry as they have to specify the full registry location as part of the image name in all commands.

### Proposed Solution

Rancher Desktop should allow users to configure the default registry for partially qualified images as well as defining registry mirrors. That configuration should apply to both k3s and the Docker/nerdctl CLI.

### Additional Information

Ref:
-  https://github.com/containerd/containerd/blob/main/docs/cri/registry.md
- https://rancher.com/docs/k3s/latest/en/installation/private-registry/

**Comment by mattfarina** [comment]
> Rancher Desktop should allow users to configure the default registry for partially qualified images

Looking into this, it's not possible without carrying a patch on Moby/dockerd. dockerd does not provide a means to accomplish this.

Moby has an issue for this feature (https://github.com/moby/moby/issues/33069) where they have said no. Commenters have noted the possible security issues.

I don't expect we will provide a means to alter the default location right now.

> defining registry mirrors

This is something we are talking about.

**Comment by janeczku** [comment]
Closing in favor of https://github.com/rancher-sandbox/rancher-desktop/issues/719
