### ISSUE TITLE
SUSE: k3s runs, but reports kubectl failed and says k3s is shutting down

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1104]
### Rancher Desktop Version

0.7.0-beta.1-74-g413ab5c

### Rancher Desktop K8s Version

1.21.6

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Actual Behavior

Startup is interrupted with a dialog reporting that kubernetes failed to start. Looking at the logs shows that one of the calls to `kubectl` failed.
But I can run `limactl shell 0`, and `k3s` is still running.

### Steps to Reproduce

See the SUSE installation instructions, and follow them. Start up Rancher Desktop from the command-line.

### Result

Two error messages:

### Expected Behavior

```
 * Starting k3s ... [ ok ]
2021-12-14T22:21:57.823Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/bin/kubectl exited with code 255
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
2021-12-14T22:23:24.684Z: + limactl shell --workdir=. 0 sudo /sbin/rc-service k3s stop
2021-12-14T22:23:24.684Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
```
I also saw this message:
```
2021-12-14T22:27:09.828Z: Kubernetes was unable to start: Error: Virtualization does not appear to be supported on your machine.
    at Bt.ensureVirtualizationSupported (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:1:28682)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

But I messed with the BIOS to enable virtualization....

Another error message complained that `rename /tmp/rancher-desktop-... /home/ericp/.local/share/rancher-desktop/...` was a cross-link operation, but both directories are on device `/dev/sda4`

### Additional Information

Going to set up a dev environment so I can debug this better.

**Comment by mook-as** [comment]
Can you check that:
1. `/proc/cpuinfo` shows either `vmx` or `svm` under `flags`
2. There is a `/dev/kvm` (and that your user has read/write access to it)

(We should keep this open to improve messaging in either case)

**Comment by ericpromislow** [comment]
Yes to both -- all 12 CPUs have vmx​ in flags, and /dev/kvm is crw-rw-rw-​ owned by root:kvm​
________________________________

**Comment by mook-as** [comment]
Odd; `/proc/cpuinfo` is literally the [only thing we test for](https://github.com/rancher-sandbox/rancher-desktop/blob/6b8227459fbcf79ccf70f6e5c310060a9c60be12/src/k8s-engine/lima.ts#L264-L272). (We should probably add a thing to test the ability to write to `/dev/kvm`.)

… I'm not sure why we're using `cat` instead of just reading the file, though.

**Comment by jandubois** [comment]
These check still don't tell you if virtualization has been disabled in the bios. [kvm-ok](https://bazaar.launchpad.net/~cpu-checker-dev/cpu-checker/trunk/view/head:/kvm-ok) has a check, but it must be run as `root`. There may be a way to scan `dmesg` for the information, but of course it may have been discarded by the time the check is running.

**Comment by mook-as** [comment]
Right; my confuse is rather that the info in this report shouldn't be possible in one single run of RD (regardless of whether it's possible to start VMs on that machine).

**Comment by ericpromislow** [comment]
Can't reproduce this. Will close this issue after discussion.

**Comment by ericpromislow** [comment]
Close for now, since I don't have access to the linux machine while WFH
