### ISSUE TITLE
k3s can't start on SUSE: network config issue involving 'global unicast ip'

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1106]
### Rancher Desktop Version

v0.7.0-beta.1-101-ga1caf74

### Rancher Desktop K8s Version

1.21.6

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Actual Behavior

The UI is stuck at `Waiting for Kubernetes...`
ssh'ing to the VM shell shows that `/var/log/k3s.log` is full of these two lines repeating:
```
time="2021-12-14T23:44:13.578625237Z" level=warning msg="unable to get global unicast ip from interface name: route ip+net: no such network interface"
time="2021-12-14T23:44:13.578657298Z" level=fatal msg="invalid node-ip "
```
Related `ps` output:
```
2855 ericp     0:00 sshfs :/home/ericp/.cache/rancher-desktop/k3s /home/ericp/.cache/rancher-desktop/k3s -o slave -o ro -o allow_other
 3131 root      0:00 supervise-daemon k3s --start --stdout /var/log/k3s.log --stderr /var/log/k3s.log --pidfile /var/run/k3s.pid --respawn-delay 5 --respawn-max 0 /usr/local/bin/k3s -- server --https-listen-port 6443 --flannel-iface rd0
```

### Steps to Reproduce

Set up a new openSUSE machine, install nvm, node v16, go v1.17, git and run `npm i ; npm run dev`

### Result

Kubernetes is not starting

### Expected Behavior

It should start

**Comment by gaktive** [comment]
Should be addressed by #1108

**Comment by ericpromislow** [comment]
Probably due to a failure to include the `rd0` network.

**Comment by jandubois** [comment]
> Probably due to a failure to include the `rd0` network.

Unlikely, given that there is no `rd0` network in the Linux version. Any code dealing with `rd0` should be inside a "darwin" branch.

**Comment by ericpromislow** [comment]
Drop this for now. I'm not using Linux right now. Let's see if other users run into it.
