### ISSUE TITLE
We need to retry getting /var/log/k3s.log from the lima shell

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1109]
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

1.21.6

### What operating system are you using?

macOS

### Operating System / Build Version

macOS - happens with linux as well

### What CPU architecture are you using?

x64

### Actual Behavior

Contents of `k3s.log` are often just:
```
tail: can't open '/var/log/k3s': No such file or directory
```

### Steps to Reproduce

Doesn't always happen, but start a dev (or packaged) build and check `k3s.log`

### Result

See above

### Expected Behavior

Other messages should appear

### Additional Information

The code in `followLogs` needs to recover when `/var/log/k3s` doesn't yet exist.

**Comment by jandubois** [comment]
The simplest solution is probably to make sure it exists by running `touch /var/log/k3s` first...

**Comment by mook-as** [comment]
It should already be [attempting to restart](https://github.com/rancher-sandbox/rancher-desktop/blob/29dd7f2581497edd15cfd584c81c056c2e248078/src/k8s-engine/lima.ts#L1038) on exit.
