### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#1114]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We have a PR from a user to configure Dependabot.

### Proposed Solution

Dependabot PR: #1179

**Comment by rishvantsingh** [comment]
I would like to work on the dependabot.

**Comment by jandubois** [comment]
> I would like to work on the dependabot.

We already have PR #1179, which will be merged next week once the 1.0.0-beta release is out.

Is there anything else left to do?
