### ISSUE TITLE
Error saving credentials: error storing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``

### ISSUE THREAD

**Issue by dee-kryvenko** [rancher-sandbox/rancher-desktop#1124]
### Rancher Desktop Version

0.7.0

### Rancher Desktop K8s Version

1.21.6

### What operating system are you using?

macOS

### Operating System / Build Version

11.6.1

### What CPU architecture are you using?

x64

### Actual Behavior

```sh
> docker login registry.local
Username: user
Password: 
Error saving credentials: error storing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

### Steps to Reproduce

Delete any other Docker installs, install RD with DockerD option, activate `/usr/local/bin/docker` symlink option. Try `docker login`.

### Result

Not able to login.

### Expected Behavior

Should be able to use private registries.

**Comment by mattfarina** [comment]
@dee-kryvenko Thanks for filing this issue. Did you previously connect to this registry with a Docker Desktop setup? If so, can you look in the file at `~/.docker/config.json` and see if `credsStore` or `credStore` is set. If one of those is set can you please share which one and the value you have.

As a work around, you may be able to get the helper from https://github.com/docker/docker-credential-helpers. The value of credsStore/credStore is the suffix for the option to use.

**Comment by dee-kryvenko** [comment]
Yes, I did had Docker Desktop. I just removed my `~/.docker` folder to avoid any leftovers from it. Now I seem to be able to login:

```sh
> docker login registry.local
Username: user
Password:
WARNING! Your password will be stored unencrypted in /Users/user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

So it doesn't seem to use any helper which isn't very secure...

But even after doing so, my K8d cluster doesn't seem to be able to fetch images:

```
Failed to pull image "registry.local/image": rpc error: code = Unknown desc = Error response from daemon: Head "https://registry.local/v2/image/manifests/latest": no basic auth credentials
```

**Comment by evertonlperes** [comment]
Adding a bit more info in this thread:

On macOS, after uninstalling Docker Desktop and removing the folder `~/Library/Application\ Support/Docker\ Desktop/`, I can also replicate the same issue (using docker-compose):
```bash
❯ docker-compose build && docker-compose up
2 errors occurred:
	* error listing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
	* error listing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```
Ref project: https://github.com/evertonlperes/sample-test-app
Rancher Desktop `1.0.0-beta1`
macOS Monterey 12.1

**Comment by jandubois** [comment]
`docker-credential-desktop` is part of Docker Desktop and obviously no longer available when you uninstall it.

It is configured in `~/.docker/config.json`:

```json
{
    "auths": {
		"ghcr.io": {},
    },
    "credsStore": "desktop",
}
```

When you delete the `credsStore` entry, the credentials will be stored directly inside this config file.

Or you could install the docker credential helper with e.g. `brew`:

```console
# brew install docker-credential-helper
```

and then change `desktop` to `osxkeychain` (the `desktop` helper is not available outside Docker Desktop).

Note that this is purely about encrypting credentials at rest (when you are not already logged into the system). If you already use drive encryption, it doesn't really make much difference.

**Comment by jandubois** [comment]
When running with the `dockerd` runtime we need to check if `~/.docker/config.json` exists, and if it doesn't, we need to create an empty file containing just `{}`.

If the file exists, we need to check the `credsStore` setting. It is fine to be missing, but if it exists, then `docker-credential-$CREDSSTORE` must exist on the `PATH`.

If it doesn't, we look for the native credentials helper, e.g. `osxkeychain` instead of `desktop` on macOS. If the native helper exist, we switch `credsStore` to that value. If it doesn't, we delete the entry.

Once #1699 is implemented, we should always have the native helper available, but it may not be on the `PATH`.

**Comment by jandubois** [comment]
Superseded by #1699 and #2013

**Comment by ayusmand** [comment]
> osx

Worked well for me.
