### ISSUE TITLE
docker-compose not working out-of-the-box

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1131]
From [Rancher Users Slack](https://rancher-users.slack.com/archives/C0200L1N1MM/p1639764360431600):

I'm trying to get a simple docker compose app running and have had a few issues:

1. It seems that removing Docker Desktop did not remove the symlinks from /usr/local/bin/docker and /usr/local/bin/kubectl, so Rancher was displaying that they were "already linked" even though the links were not valid.   It would be a good idea to try and follow the symlinks, and if they are not valid, point them into Rancher's binaries.

2. After sorting this out docker compose did not work.  I installed docker-compose using homebrew and added it manually to ~/.docker/cli-plugins, and now docker compose is lit up.

3. When trying to pull images using docker compose up (I presume docker pull would have done the same), I got an error about the credential store not being found. Docker Desktop had left ~/.docker/config.json with an entry like "credsStore" : "desktop" .  I changed that to "osxkeychain" but then had to download the docker-credential-osxkeychain from github and install it manually in /usr/local/bin.  Once that was all in place, my compose application seems to start up.

**Comment by VoX** [comment]
These issues appear unique to macos. I didn't see them on a Windows install of Rancher Desktop.

**Comment by jslew** [comment]
It seems like deleting the `credsStore` setting entirely also works, and doesn't require manually installing the osxkeychain component.

**Comment by n0rig** [comment]
@jandubois / @jslew What if we "need" to have the CredStore value defined?

For example, AWS ECR's '[ecr-login](https://github.com/awslabs/amazon-ecr-credential-helper#docker)':
```json
"credsStore" : "ecr-login"
```

**Comment by jandubois** [comment]
@n0rig Did you install the helper?

```console
$ brew install docker-credential-helper-ecr
```

**Comment by n0rig** [comment]
yes
```shell
Warning: docker-credential-helper-ecr 0.5.0 is already installed and up-to-date.
```

**Comment by Kronos11** [comment]
> It seems like deleting the `credsStore` setting entirely also works, and doesn't require manually installing the osxkeychain component.

This fixed it for me

**Comment by jandubois** [comment]
> What if we "need" to have the CredStore value defined?
> 
> For example, AWS ECR's '[ecr-login](https://github.com/awslabs/amazon-ecr-credential-helper#docker)':
> 
> ```json
> "credsStore" : "ecr-login"
> ```

@n0rig I have successfully pulled an image from a private ECR repository using ecr helper. Can you provide more details on how it fails for you? Are you sure you have setup your credentials correctly? Are you using environment variables, `~/.aws/config`, or something else?

Did you check the output in `~/.ecr/log/ecr-login.log`?
