### ISSUE TITLE
[E2E] nerdctl integration on RD

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1134]
Implement automated test for nerdctl integration on RD.

Test case:
* Pull a sample image (e.g. nginx or alpine).
* Build a sample image (custom Dockerfile).
* Pull or push a custom image from a cloud registry.
* List containers.

Note: This test scenario seems to be resource and time eager. A further analysis/research will be required, perhaps it will be required a specific runner for this test.

**Comment by jandubois** [comment]
`nerdctl` is being tested by BATS
