### ISSUE TITLE
[E2E] dockerd integration on RD

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1135]
Implement automated test for moby/dockerd integration on RD.

Test case:
* Pull a sample image (e.g. nginx or alpine).
* Build a sample image (custom Dockerfile).
* Pull or push a custom image from a cloud registry.
* List containers.

Note1: This test scenario seems to be resource and time eager. A further analysis/research will be required, perhaps it will be required a specific runner for this test.
Note2: There's a possible blocker for this test that might need some changes on the source code, running on TEST or CI environment. The step `Installing networking requirements` will pop up a dialog box and then the OS will request the user password - not sure if playwright has access to the user/password dialog box, it seems to be controlled by OS.

**Comment by jandubois** [comment]
`docker` CLI testing is done by BATS
