### ISSUE TITLE
unable to get global unicast ip from interface name: can't find ip for interface rd0

### ISSUE THREAD

**Issue by 12101111** [rancher-sandbox/rancher-desktop#1141]
### Rancher Desktop Version

0.7.0-35-g7c0ad62

### Rancher Desktop K8s Version

1.22.4

### What operating system are you using?

macOS

### Operating System / Build Version

12.0.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

k3s.log:
```
time="2021-12-19T14:10:55Z" level=fatal msg="invalid node-ip "
time="2021-12-19T14:11:00Z" level=warning msg="unable to get global unicast ip from interface name: can't find ip for interface rd0"
```

### Steps to Reproduce

lima vm:
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:55:55:cb:09:29 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.15/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fec0::5055:55ff:fecb:929/64 scope site dynamic flags 100
       valid_lft 86237sec preferred_lft 14237sec
    inet6 fe80::5055:55ff:fecb:929/64 scope link
       valid_lft forever preferred_lft forever
3: rd0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:55:55:78:f5:be brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5055:55ff:fe78:f5be/64 scope link
       valid_lft forever preferred_lft forever
```

```
$ sudo /sbin/udhcpc -b -R -p /var/run/udhcpc.rd0.pid -i rd0 -x hostname:lima-0
udhcpc: started, v1.33.1
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc failed to get a DHCP lease
udhcpc: no lease, forking to background
```

### Result

k3s won't start

### Expected Behavior

k3s will start

### Additional Information

I use the version from https://github.com/rancher-sandbox/rancher-desktop/pull/1136

**Comment by 12101111** [comment]
It seems it don't work in an open WiFi with portal authentication, but works in a normal WiFi with WPA2/3

**Comment by jandubois** [comment]
> It seems it don't work in an open WiFi with portal authentication

Ah yes, that is an excellent observation: the bridged networking cannot work if the local network requires manual authentication.

In that situation you should change the `rd0` interface to "shared" mode by creating an `override.yaml` file like this:

```console
$ cat "$HOME/Library/Application Support/rancher-desktop/lima/_config/override.yaml"
networks:
- lima: shared
  interface: rd0
```

The IP address will then be local to your host, so not accessible from other machines on the local network.

**Comment by 4uganesh** [comment]
Hi Jan,

After adding the override.yaml also, I am having the same issue

time="2021-12-29T23:20:52Z" level=fatal msg="invalid node-ip: invalid ip format ''"
time="2021-12-29T23:20:57Z" level=warning msg="unable to get global unicast ip from interface name: can't find ip for interface rd0"

**Comment by learnerEvermore** [comment]
Same here. Fresh/first rancher-desktop install, 0.7.1. Reduced memory ("Kubernetes Settings") to t2GB and "Reset Kubernetes". Did not recover. Override file did not help, the log continued to issue the same message. My WiFi was disabled, used a wired (dongle) Ethernet. Tried disconnecting from my VPN - no change.

**Comment by 4uganesh** [comment]
After making the adjustment `character` and replace it with a regular space in override.yaml file, the application is up and running. Thanks @jandubois for helping out. Much appreciated 

00000000  6e 65 74 77 6f 72 6b 73  3a 0a 2d 20 6c 69 6d 61  |networks:.- lima|
00000010  3a 20 73 68 61 72 65 64  0a 20 20 69 6e 74 65 72  |: shared.  inter|
00000020  66 61 63 65 3a 20 72 64  30 0a                    |face: rd0.|
0000002a

**Comment by jandubois** [comment]
> Restarting the rancher desktop GUI (with the override file in place) did help.

Yes, the `override.yaml` is only processed when the VM is started. The problem @4uganesh ran into was that they had a non-breaking space instead of a regular space in the YAML file, which cause that line to be ignored.

So it looks like switching to a "shared" network solved the problem for everyone.

I would still be grateful for any information why the bridged network doesn't work in your setup. Ideas so far:

* Wifi doesn't really allow multiple IP addresses on one connection; it only works sometimes by accident.
* Corporate network management detects an "illegal switch" on the network isolates it.

**Comment by learnerEvermore** [comment]
@jandubois I don't quite know why. I don't think it has anything to do with corporate network management. More likely it is confused by the sheer number of interfaces I have, as created by other VMs, for example. Some get confused by the VPN one, which is why I tried disabling it. 

I am trying Rancher Desktop as an alternative to Docker Desktop. Whether it is this setting or another, image building now fails when it tries to reach out to get some GPG keys (a FrankenVersion of PostgreSQL Dockerfile) so I replaced those with local versions temporarily + `COPY`.

**Comment by jandubois** [comment]
> More likely it is confused by the sheer number of interfaces I have, as created by other VMs, for example.

Yes, there is a limit on the number of networks vmnet can support, but if it can create another shared network, then it should be able to create a bridged network as well.

> image building now fails when it tries to reach out to get some GPG keys (a FrankenVersion of PostgreSQL Dockerfile) so I replaced those with local versions temporarily + `COPY`.

Please file a separate issue if those problems persist.

**Comment by learnerEvermore** [comment]
> Please file a separate issue if those problems persist.

I don't think I need to (yet). That was more of an indication that about the limits of this workaround.
