### ISSUE TITLE
WSL: Allow overriding k3s command line

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#1142]
# Problem Description

Currently, there is no supported way of overriding k3s command line arguments on Windows.

On Lima, the user can set `K3S_EXEC` in `…/lima/_config/override.yaml`.

# Proposed Solution

Let the user drop a file in `\\wsl$\rancher-desktop-data`, and we'll source that file in `/etc/conf.d/k3s` _after_ any of our existing lines. (If the user put in configuration that breaks the run, they can discover and fix it.)

**Comment by mook-as** [comment]
Upon further discussion with @jandubois, since both Windows & Lima are using OpenRC, we could perhaps get something that would be mounted in `/etc/local.d`, and enable that service at the `sysinit` runlevel (where `machine-id` is).

Note that (at least on Windows) we never properly stop the service, so `*.stop` would never get run.

**Comment by jandubois** [comment]
> enable that service at the `sysinit` runlevel

Any reason not to run at the `default` runlevel? I can't remember right now if e.g. networking is available when you run as part of `sysinit`, and you may want to make networks calls as part of the custom setup script.

Anyways, I haven't thought this through; just wanted to know why you picked `sysinit`?

**Comment by mook-as** [comment]
I was thinking `sysinit` because this is the equivalent of a provisioning script, and should run before other things.  Given that we manually trigger the primary services (`k3s`, `docker`, etc.), that probably doesn't matter, though, so we can pick whatever we want.

On Windows, at least, networking is up before `/sbin/init` starts, so that isn't an issue.  Though there's `dnsmasq`; perhaps it's better to be in `default` with a dependency on `dnsmasq` instead?
