### ISSUE TITLE
[BUG] Two versions of Kubernetes are listed as latest

### ISSUE THREAD

**Issue by simonflood** [rancher-sandbox/rancher-desktop#1143]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

N/A

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Actual Behavior

Having upgraded from 0.7.0 to 0.7.1 (both installed from the RPM update repository) I noticed that when listing the available Kubernetes versions to select, two latest versions are listed, v1.22.4 and v1.22.5.

### Steps to Reproduce

Launch Rancher Desktop, go to Kubernetes Settings, and select drop-down box of Kubernetes versions.

### Result

![Uploading Screenshot from 2021-12-20 17-50-26.png…]()

### Expected Behavior

There can only be one latest version (v1.22.5) - v1.22.4 should now not be flagged as latest.

**Comment by simonflood** [comment]
Hmm seems my RD setup was screwy as reset it and now 1.22.4 has disappeared leaving only one latest version listed (v1.22.5)

**Comment by mcekovic** [comment]
This happened to me after updating to 1.0.1 version, seems there is a bug that manifests either when upgrading Rancher Desktop or after Kubernetes versions list is refreshed. Seems that when new latest version is available, the previously latest one keeps to be marked as latest in `k3s-versions.json`.

**Comment by mcekovic** [comment]
I can confirm this is not fixed. In Rancher Desktop 1.0.1, new Kubernetes version 1.23.4 has arrived and 'latest' tag is present to both 1.23.4 and 1.23.3 versions.

**Comment by simonflood** [comment]
I can confirm it's not fixed in 1.1.0 - I'm loath to reset as I'd lose something I've got setup
![Screenshot from 2022-03-09 15-44-47](https://user-images.githubusercontent.com/8300801/157477054-15e81d0e-e3b9-4098-8647-841f7ffb5949.png)

**Comment by jandubois** [comment]
@simonflood This is fixed in #1584, which will be in the next release.

I believe you can still use all the versions from the list; you just have additional redundant entries (and incorrect stable/latest labels).
