### ISSUE TITLE
Linux Release Have Wrong Version

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#1144]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

N/A

### What operating system are you using?

Other Linux

### Operating System / Build Version

pop OS 20.04, openSUSE 15.3

### What CPU architecture are you using?

x64

### Actual Behavior

The version string for 0.7.1 on Linux (in the packaging of deb/rpm) is wrong. The version is listed as 0.7.0.

### Steps to Reproduce

After the release of a version off a release branch (other than main) look at the version (you can see it in the file name). For example, you can see it [here](https://download.opensuse.org/repositories/isv:/Rancher:/stable/rpm/x86_64/). The 0.7.1 release was versioned as 0.7.0.

### Result

N/A

### Expected Behavior

The version should be 0.7.1

### Additional Information

This appears to be happening because [OBS is configured](https://build.opensuse.org/package/show/isv:Rancher:stable/rancher-desktop) to [look at the main branch](https://build.opensuse.org/package/view_file/isv:Rancher:stable/rancher-desktop/_service?expand=1).  The 0.7.1 tab was on a release branch. 

OBS is triggered with a [webhook called through a GitHub Action](https://github.com/rancher-sandbox/rancher-desktop/blob/7c0ad62de6db286982f30c2902935f85c29a48cc/.github/workflows/linux-release.yaml#L29-L34). No context about the release is passed so the version information (or how to get it) needs to already be available to OBS.

As we move forward to regular patch releases this setup isn't going to work.

**Comment by adamkpickering** [comment]
I'm going to close this issue and create separate ones for the steps it is going to take to resolve it. I will link to this issue in those ones.
