### ISSUE TITLE
sudoers file doesn't work if the user is not a member of the `staff` group

### ISSUE THREAD

**Issue by andreroggeri** [rancher-sandbox/rancher-desktop#1152]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

0.22.5

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.1

### What CPU architecture are you using?

x64

### Actual Behavior

Cannot start rancher desktop (Tried factory reset, fresh install)

### Steps to Reproduce

Open Rancher Desktop

### Result

Error occurs

### Expected Behavior

It should start normally

### Additional Information

```
time="2021-12-22T09:24:13-03:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2021-12-22T12:24:13.011Z: + limactl start --tty=false 0
2021-12-22T12:24:13.011Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2021-12-22T12:24:13.011Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

```

**Comment by andreroggeri** [comment]
Adding the following line to the sudoers fixes this erros but then fails on another one 😢 

```
ALL ALL=NOPASSWD: /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima
```

**Comment by andreroggeri** [comment]
Next error:

```
"/private/etc/sudoers.d/rancher-desktop-lima" is up-to-date (or sudo doesn't require a password)
time="2021-12-22T09:41:32-03:00" level=info msg="Using the existing instance \"0\""
time="2021-12-22T09:41:32-03:00" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2021-12-22T09:41:32-03:00" level=info msg="Starting vmnet daemon for \"bridged_en0\" network"
time="2021-12-22T09:41:32-03:00" level=info msg="Attempting to download the image from \"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/alpine-lima-v0.2.3-rd-3.14.3.iso\"" digest=
time="2021-12-22T09:41:32-03:00" level=info msg="Downloaded image from \"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/alpine-lima-v0.2.3-rd-3.14.3.iso\""
time="2021-12-22T09:41:33-03:00" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/[user]/Library/Application Support/rancher-desktop/lima/0/serial.log\")"
time="2021-12-22T09:41:33-03:00" level=info msg="SSH Local Port: 55397"
time="2021-12-22T09:41:33-03:00" level=info msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
time="2021-12-22T09:41:33-03:00" level=info msg="[hostagent] QEMU has exited"
time="2021-12-22T09:41:33-03:00" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/Users/[user]/Library/Application Support/rancher-desktop/lima/0/ha.stderr.log\")"
2021-12-22T12:41:33.802Z: + limactl start --tty=false 0
2021-12-22T12:41:33.802Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2021-12-22T12:41:33.802Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

**Comment by rogerfernandes** [comment]
I have a similar case in `macOS Big Sur 11.6.1` with this error:

```
"/private/etc/sudoers.d/rancher-desktop-lima" is up-to-date (or sudo doesn't require a password)
time="2021-12-22T15:10:11-03:00" level=info msg="Using the existing instance \"0\""
time="2021-12-22T15:10:11-03:00" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2021-12-22T15:10:11-03:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2021-12-22T18:10:11.213Z: + limactl start --tty=false 0
2021-12-22T18:10:11.213Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2021-12-22T18:10:11.214Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

```

**Comment by mattfarina** [comment]
When you started Rancher Desktop up, did it prompt you for your password? If so, did you cancel that or go through with it?

**Comment by andreroggeri** [comment]
I'm not 100% sure, but I think it did not.


But I deleted the sudoers file (/private/etc/sudoers.d/rancher-desktop-lima) and it triggered the prompt and I went through (And saw that the sudoers file was created again)

**Comment by DaunerM** [comment]
Hi,

i can confirm this problem. 
Tried also a clean reinstall of rancher-desktop. Definitely processed the prompt with the correct password. sudoers file was also created.

Same log:
```time="2021-12-23T08:39:45+01:00" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2021-12-23T08:39:45+01:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2021-12-23T07:39:45.536Z: + limactl start --tty=false 
2021-12-23T07:39:45.536Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2021-12-23T07:39:45.536Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)```

**Comment by dparada8817** [comment]
> When you started Rancher Desktop up, did it prompt you for your password? If so, did you cancel that or go through with it?

i have the same issue, the first time he ask me for the password but the still happend
MacOs Monterey 12.1
Version: 0.7.1

**Comment by AdilusPrimus** [comment]
Same issue here

**Comment by rogerfernandes** [comment]
> When you started Rancher Desktop up, did it prompt you for your password? If so, did you cancel that or go through with it?

Yes, it asked me for the password. I entered my password correctly, but the problem still happens.

**Comment by 589290** [comment]
If I already have lima/limactl installed on my Mac via `brew install lima` couldn't RD check for the presence of this installation before trying to install lima/limactl on it's own?

**Comment by scrudge** [comment]
Is there a workaround?

**Comment by jandubois** [comment]
> If I already have lima/limactl installed on my Mac via `brew install lima` couldn't RD check for the presence of this installation before trying to install lima/limactl on it's own?

@589290 RD bundles it's own version to be sure it is exactly the right version it requires. This also makes sure that you don't break RD if you uninstall your lima formula.

RD sets a different `LIMA_HOME` and keeps all settings separate from the normal lima install, so both version should co-exist and not even be aware of each other.

**Comment by cristobal** [comment]
Same error here, seems only option is to use an older version of Rancher Desktop until this is resolved…

**Comment by scrudge** [comment]
6.1 seems to work.

**Comment by cristobal** [comment]
> 6.1 seems to work.

Yup that’s the one i’m currently using.

**Comment by mlewe** [comment]
The problem here seems to be that the sudoers file installed by Rancher Desktop assumes that the current user is a member of the group 'staff'.
This was not the case for my user.
After adding my user to the staff group, i.e.
```
sudo dscl . append /groups/staff GroupMembership $(whoami)
```
Rancher Desktop seems to start up normally in 0.7.1

**Comment by jandubois** [comment]
> assumes that the current user is a member of the group 'staff'.
> This was not the case for my user.

That is very interesting. Do you know why?

Normally **all** users are part of the `staff` group. Administrators are **also** members of the `admin` group, while `root` is included in `wheel`, whereas other admin accounts are not.

Well, at least that's what I thought how the default groups on macOS are set up.

**Comment by mlewe** [comment]
> That is very interesting. Do you know why?

I think it very likely has something to do with my mac being a corporate laptop and the user account being connected to Active Directory.
But I don't know anything more apart from that.

**Comment by cristobal** [comment]
> > That is very interesting. Do you know why?
> 
> I think it very likely has something to do with my mac being a corporate laptop and the user account being connected to Active Directory. But I don't know anything more apart from that.

I can confirm here also, that my Mac is a corporate laptop where my user is an admin user and not does not include `staff` in groups it belongs too listed here:

```
wheel
everyone
netaccounts
_appserverusr
admin
_appserveradm
_lpadmin
com.apple.sharepoint.group.3
com.apple.sharepoint.group.4
com.apple.sharepoint.group.2
_appstore
_lpoperator
_developer
_analyticsusers
com.apple.access_ftp
com.apple.access_screensharing
com.apple.access_remote_ae
com.apple.sharepoint.group.1
```

If the `staff` group should be one that should be included in the groups for a user, i am happy to notify our helpdesk and suggest it for them to include. But i think the best would be to circumvent and defaulting on the`staff` group if its possible?

**Comment by jandubois** [comment]
Thanks @mlewe and @cristobal, looks like we should include the uid in the sudoers file as well, e.g.

```
%staff, #501  ALL=(root:wheel) NOPASSWD:NOSETENV: ...
```

(or whatever the UID is for the current user). Not ideal for a multi-user machine, as it will need to update the sudoers file every time the user changes, so maybe only do that when the current user is not a member of the `staff` group.

BTW, the actual group name should be configurable by editing 

```
~//Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml
```

However, it will only work for unix groups; you won't be able to set it to e.g. an AD group.

**Comment by scrudge** [comment]
I added myself to the staff group and restarted my computer.  Did a "factory reset" on RD as well as :
LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" limactl rm 0
rm -rf ~/Library/State/rancher-desktop
rm -rf /Users/larry//Library/Caches/rancher-desktop

Still no luck.  Here's the contents of the lima.log

"/private/etc/sudoers.d/rancher-desktop-lima" is up-to-date (or sudo doesn't require a password)
time="2022-01-03T09:54:37-06:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-01-03T09:54:37-06:00" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2022-01-03T09:54:37-06:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2022-01-03T15:54:37.484Z: + limactl start --tty=false /Users/larry/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-01-03T15:54:37.485Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-01-03T15:54:37.485Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

**Comment by jandubois** [comment]
> `time="2022-01-03T09:54:37-06:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"`

@scrudge You should not get this error when you are a member of the `staff` group. Can you please verify:

```console
$ head -1 /etc/sudoers.d/rancher-desktop-lima
%staff ALL=(root:wheel) NOPASSWD:NOSETENV: /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima
$ id
uid=501(jan) gid=20(staff) groups=20(staff), [...]
```

**Comment by scrudge** [comment]
```
$ head -1 /etc/sudoers.d/rancher-desktop-lima
%staff ALL=(root:wheel) NOPASSWD:NOSETENV: /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima
$ id
uid=502(larry) gid=20(staff) groups=20(staff),...
```

**Comment by jandubois** [comment]
@scrudge That is really curious. What happens when you run this manually:

```
sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima
```

Do you get the same error? Can you also verify the permissions on the sudoers file to make sure it is only `root` writable:

```console
$ ls -ld /etc /etc/sudoers.d /etc/sudoers.d/rancher-desktop-lima
lrwxr-xr-x@ 1 root  admin    11 14 Dec  2019 /etc -> private/etc
drwxr-xr-x  5 root  wheel   160 28 Dec 21:44 /etc/sudoers.d
-rw-r--r--  1 root  wheel  5334 17 Dec 15:33 /etc/sudoers.d/rancher-desktop-lima
```

**Comment by scrudge** [comment]
yes:
```
$ sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima
sudo: a password is required
```
```
$ ls -ld /etc /etc/sudoers.d /etc/sudoers.d/rancher-desktop-lima
lrwxr-xr-x@ 1 root  wheel    11 Jan  1  2020 /etc -> private/etc
drwxr-xr-x  3 root  wheel    96 Jan  3 10:45 /etc/sudoers.d
-rw-r--r--  1 root  wheel  8562 Dec 30 13:46 /etc/sudoers.d/rancher-desktop-lima
```

**Comment by jandubois** [comment]
@scrudge Weirder and weirder.

Is the `sudoers.d` directory included in the `sudoers` file?

```console
$ sudo grep sudoers.d /etc/sudoers
## Read drop-in files from /private/etc/sudoers.d
#includedir /private/etc/sudoers.d
```

**Comment by scrudge** [comment]
```
$  sudo grep sudoers.d /etc/sudoers
## Read drop-in files from /private/etc/sudoers.d
#includedir /private/etc/sudoers.d
```

**Comment by scrudge** [comment]
I wonder if there is a rule in my sudoers file that's causing it to require a password.

**Comment by jandubois** [comment]
@scrudge I'm almost out of ideas now.

> I wonder if there is a rule in my sudoers file that's causing it to require a password.

Yes, I was just about to write this: if there is another rule in your `sudoers` file, or in any of the `sudoers.d` files, then it might override the rule from rancher-desktop.

I could try to help you, but I would need the complete set of files. In that case you must verify first that there is no proprietary information in your sudoers files, that you would not be allowed to share.

**Comment by jandubois** [comment]
@mlewe and @cristobal Could you verify if your AD users are members of the `everyone` group (12)? It looks like `staff` is indeed only for local accounts, but `everyone` should include also external accounts.

And if you are a member of that group, could you check if changing the group in `~/Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml` from `staff` to `everyone` fixes the problem for you (after you regenerate the sudoers file)?

If this works, it would be a much simpler fix than adding the #uid to the sudoers file.

**Comment by cristobal** [comment]
> And if you are a member of that group, could you check if changing the group in `~/Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml` from `staff` to `everyone` fixes the problem for you (after you regenerate the sudoers file)?
> 
> If this works, it would be a much simpler fix than adding the #uid to the sudoers file.

Hmm so should i do the following then?

1. Factory reset and quit Rancher Desktop
2. Edit `~/Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml` and change from `stagff` to `everyone`
3. Remove `/private/etc/sudoers.d/rancher-desktop-lima`
4. Restart Ranched Desktop?

**Comment by jandubois** [comment]
> Hmm so should i do the following then?

First you should verify that you are indeed a member of the `everyone` group:

```console
$ id
uid=501(jan) gid=20(staff) groups=20(staff),701(com.apple.sharepoint.group.1),12(everyone),[...]
```

> 1. Factory reset and quit Rancher Desktop

Factory reset is not necessary, but won't hurt. But you have to stop RD.

> 2. Edit `~/Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml` and change from `staff` to `everyone`

Yes

> 3. Remove `/private/etc/sudoers.d/rancher-desktop-lima`

Should not be necessary because it will be overwritten in the next step.

> 4. Restart Ranched Desktop?

This should again ask you for your password, so it can regenerate the sudoers file with the new content, and then I hope it will all work.

**Comment by cristobal** [comment]
> This should again ask you for your password, so it can regenerate the sudoers file with the new content, and then I hope it will all work.

Yes i am a member for `everyone` with group id `12`, i did as you said:

1. Quit Rancher Desktop
2. Modified `~/Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml` and changed from `staff` to `everyone`
3. Restarted Rancher Desktop

I was asked for password and the sudoers file was recreated, and everything seems to be running fine now 👌🏽 

![Screenshot 2022-01-03 at 23 01 47](https://user-images.githubusercontent.com/155505/147985395-698b014d-d15b-466c-a3b3-7df5565294b1.png)

I can confirm that this works for me, thanks for the help @jandubois 🙂

**Comment by Freydal** [comment]
I ran into this issue also and it was really helpful.  I had been triggering retries with 'Reset Kubernetes' so I attempted a shortened fix.

Using `sed -i "" s/staff/everyone/ ~/Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml` and clicking 'Reset Kubernetes' should be sufficient.  I got another password prompt after making this change.

**Comment by AdilusPrimus** [comment]
Applied the recommendation setting for everyone instead of staff and still get these errors in Lima.log

time="2022-01-04T11:59:17-05:00" level=debug msg="Running: [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]"
time="2022-01-04T11:59:17-05:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2022-01-04T16:59:17.398Z: + limactl --debug start --tty=false 0
2022-01-04T16:59:17.398Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

It must be how our company set the sudoers config

**Comment by jandubois** [comment]
@AdilusPrimus Did you verify that your user is part of the `everybody` group first?

```console
$ id
uid=501(jan) gid=20(staff) groups=20(staff),701(com.apple.sharepoint.group.1),12(everyone),[...]
```

The next thing would be to verify that the `/private/etc/sudoers.d` is actually included in your sudoers file:

```console
$ sudo tail -3 /etc/sudoers
## Read drop-in files from /private/etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /private/etc/sudoers.d
```

For good measure you could double-check that `/etc` is indeed a symlink to `/private/etc`:

```console
$ ls -ld /etc
lrwxr-xr-x@ 1 root  admin  11 14 Dec  2019 /etc -> private/etc
```

If that all checks out, then I would check the content of `/etc/sudoers` and all files under `/etc/sudoers.d` to see if they include a rule that might override the rancher-desktop rules.

I can offer to help you with this review, but you must check with your company first if you are allowed to share these files, or if they might include confidential information. If you want me to take a look, and got approval, you can send them to me e.g. in a ZIP file to jan.dubois@suse.com.

**Comment by scrudge** [comment]
> @scrudge I'm almost out of ideas now.
> 
> > I wonder if there is a rule in my sudoers file that's causing it to require a password.
> 
> Yes, I was just about to write this: if there is another rule in your `sudoers` file, or in any of the `sudoers.d` files, then it might override the rule from rancher-desktop.
> 
> I could try to help you, but I would need the complete set of files. In that case you must verify first that there is no proprietary information in your sudoers files, that you would not be allowed to share.

That was the issue. I found a line that was requiring a password for another group that I am in.  I changed the order so that the RD sudoers was loaded after and it's working now.

Thanks for all the help, really appreciate it.

**Comment by jandubois** [comment]
I know this is already closed, but we were still seeing reports of people where the sudoers file wasn't working.

It is still not clear to me where it comes from (e.g. from some JamF policy), but it seems like several people have a `/etc/sudoers.d/sudoers` file that looks like this:

```console
$ sudo cat /etc/sudoers.d/sudoers
username ALL=(ALL) ALL
```

Sudoers files are processed alphabetically, and the last rule matching a command will be used, this rule will override **all** rules from the `/etc/sudoers.d/rancher-desktop-lima` file: it says that `username` can run ALL commands, but does have to provide a password.

In the 1.0.1 release we have changed our filename to `/etc/sudoers.d/zzzzz-rancher-desktop-lima` to have a better chance of being "the last rule". It is a bit silly, but the way `sudo` works, the generic rules need to be processed before the more specialized ones.

I hope this resolves the issue for those who still had problems with `sudo`. If things still don't work for you with the 1.0.1 release, then please open a new Github issue!
