### ISSUE TITLE
[Playwright] Bump PW 1.17.0 to 1.19.0

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1153]
`To-Do` after playwright releases v1.19.0 version.
Due couple (intermittent) issues found on playwright test framework that is affecting our tests, we need to bump the playwright version on `v1.19.0` release.

1. On CI, RD app takes more than 30 seconds to gracefully close the application and in some cases, all the tests will pass (test cases), but eventually it will fail due the hard-coded 30s from playwright `Electron.close()` function.
2. Timeout fixtures on `playwright-config.ts` does not apply the specified custom timeout and cannot set the correct timeout based on environments.

Playwright addressed issues:
* Electron.close() timeout after 30s -  https://github.com/microsoft/playwright/issues/11068
* Timeout fixtures does not apply to Electron application - https://github.com/microsoft/playwright/issues/10840

**Comment by mook-as** [comment]
Their current release is  v1.17.0, so I assume this means we can't actually do this yet?

**Comment by evertonlperes** [comment]
> Their current release is v1.17.0, so I assume this means we can't actually do this yet?

We're on v1.17.0 already and yes, we can't bump to 1.19 because it wasn't released yet.

**Comment by evertonlperes** [comment]
Main card: https://github.com/rancher-sandbox/rancher-desktop/issues/1577
