### ISSUE TITLE
Executing an interactive terminal needs keystroke after exiting

### ISSUE THREAD

**Issue by TheOnlyJho** [rancher-sandbox/rancher-desktop#1171]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Home 21H1

### What CPU architecture are you using?

x64

### Actual Behavior

When you exit an interactive terminal (you can either "docker run" a shell with a container or "docker exec" a shell in an already running one) it waits for a keystroke before you get back to your command shell and it displays its prompt again.

I have been trying to use testcontainers with Rancher Desktop (that's why I used dockerd). Testcontainers executes commands in running containers for example to test for some docker requirements on startup or to see if a container has opened its exposed port.
All this hangs on execution and runs in a Timeout (or just grinds to a halt) and it might be that this is due to the "not really exiting" problem I described here.

Also I think this could break scripts that just execute a single command (like trivy checking etc.).

### Steps to Reproduce

Run Rancher Desktop with dockerd container runtime.
In a cmd shell execute "docker run -it --rm alpine sh".
Exit the container shell by executing "exit".

### Result

The cmd shell does not display its prompt but you have to press any key to get back into the cmd shell.

### Expected Behavior

The command should completely exit and should not wait for a keystroke.

**Comment by evertonlperes** [comment]
Issue replicated on Windows 10 PRO, using both `cmd` and `powershell` console.
Linux and macOS are working as expected.

**Comment by dblanchette** [comment]
Same here. This break scripts calling docker command since it never knows when the command exited which is a pretty major blocker for us.

**Comment by jhollmannk** [comment]
This is the last issue for the 1.0.0-beta milestone. Any chance that this will be fixed soon?
This is the only thing that really prevents us from using RancherDektop because we use testcontainers in our Java-JUnit-Tests and this behaviour breaks almost all the JUnit-Tests.
So a major blocker for us too. Would be great if this was fixed!

**Comment by gaktive** [comment]
@jhollmannk This will take a bit longer, alas, so we'll target this for right after 1.0.

**Comment by mook-as** [comment]
To give more details:
I suspect our proxy process is buffering too much, which means the `/containers/{id}/wait` connection is not closing properly (so the client couldn't tell when it should detach).

Oddly, watching `/wait` and force-closing the `/attach` connection fixes the issue, but that seems… very suspect?

**Comment by mook-as** [comment]
Making API calls directly, it appears that `/wait` actually _is_ working correctly; that returns when the container is closed.  So we'll have to forcefully terminate the `/attach` connection instead (which seems wrong).
