### ISSUE TITLE
Error starting the app/Kubernetes

### ISSUE THREAD

**Issue by pythoninthegrass** [rancher-sandbox/rancher-desktop#1172]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Version 21H2 (OS Build 22000.348)

### What CPU architecture are you using?

x64

### Windows User Only

Tailscale is installed, but not running when the permissions act up.

### Actual Behavior

Get two separate issues:

1. Startup read permissions error
2. kubeconfig copy permissions error

### Steps to Reproduce

- Start Rancher Desktop
- Triggers first read error message
- Wait for k8s install (default)
- Second copyfile permission error happens after install
- Fresh install/upgrade produces the same results
- Running as admin has no effect
- Turns out a previous k3s/kubeconfig directory was present at `$home\.kube`
- Removed that and the install and launch was successful
- `.kube` and `.kubelr` directories were generated
- Kept previous directory if needed to repro (may need to scrub keys/creds first)

### Result

![2022-01-02 23_38_48-Error](https://user-images.githubusercontent.com/4097471/147902419-c98c9420-c952-4635-99eb-84077b036b52.png)
![2022-01-02 23_40_25-Error](https://user-images.githubusercontent.com/4097471/147902430-5ad61865-45e8-4721-9a24-6dbf1cda67a7.png)
Appears similar to this: https://github.com/facebook/metro/issues/658

### Expected Behavior

- Start fresh Rancher Desktop
- Mount WSL2
- Installs stable k8s
- Copies kubeconfig and kubectl to dotfile directories in home directory
- Complete setup

### Additional Information

`background log`
```
2022-01-03T05:51:40.518Z: Kubernetes was unable to start: [Error: EPERM: operation not permitted, copyfile 'C:\Users\l-ste\AppData\Local\Temp\rancher-desktop-kubeconfig-5hmROj\kubeconfig' -> 'C:\Users\l-ste\.kube\config'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'copyfile',
  path: 'C:\\Users\\l-ste\\AppData\\Local\\Temp\\rancher-desktop-kubeconfig-5hmROj\\kubeconfig',
  dest: 'C:\\Users\\l-ste\\.kube\\config'
}
```
`k8s.log`
```
2022-01-03T05:51:40.505Z: Error trying to load kubernetes config file C:\Users\l-ste\.kube\config: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at KubeConfig.loadFromFile (C:\Users\l-ste\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\@kubernetes\client-node\dist\config.js:75:32)
    at Tt.updateKubeconfig (C:\Users\l-ste\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:1:24246) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
```
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/7800588/logs.zip)

**Comment by mook-as** [comment]
The relevant line seems to be:
> C:\Users\l-ste\.kube\config: Error: EISDIR: illegal operation on a directory

That's… unusual; we can work around it, but we wouldn't be able to update your Kubernetes configuration in that case (so it would be difficult for you to access your cluster).

**Comment by pythoninthegrass** [comment]
Missed your comment @mook-as! Something changed in the last few releases -- 1.1.1 fixed it 🤷‍♂️

**Comment by yahyanouali** [comment]
I have the same problem on recent version 1.11.1
