### ISSUE TITLE
VS Code Remote Container issue "mount path must be absolute"

### ISSUE THREAD

**Issue by ckihm** [rancher-sandbox/rancher-desktop#1173]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10, Version 1909 (Build 18363.1977)

### What CPU architecture are you using?

x64

### Windows User Only

Work behind a company proxy. Work from the home office with a ZScaler VPN connection. SSL certificates are broken. Nexus is used as a pass through registry for Docker images.

### Actual Behavior

As 0.7.1 has docker support, I am trying to get the VS Code extension [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) with Rancher Desktop.

When I try to open a copy of this [repo](https://github.com/microsoft/vscode-remote-try-node) **under Windows with VS Code**, which I have **cloned into my WSL distribution file system[ as recommendet by MS](https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_store-your-source-code-in-the-wsl-2-filesystem-on-windows)**, I encounter the following error:

```
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '1ddff10d-b7f5-4248-87dc-c16fa415c643' mount path must be absolute.
```

The command that fails is the following:

```
Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ckihm/workspace/vscode-remote-try-node,target=/workspaces/vscode-remote-try-node --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\Ubuntu-DevEnv\home\ckihm\workspace\vscode-remote-try-node -l vsch.quality=stable -l vsch.remote.devPort=0 --entrypoint /bin/sh vsc-vscode-remote-try-node-135bee0ef1abe7e04d86d4d2eb4f9d17-uid -c echo Container started
trap "exit 0" 15

while sleep 1 & wait $!; do :; done
```

Interesting is that it behaves differently when I check out the repository in **the windows filesystem** which is not recommended. If I then use the function "Reopen in Container", a container is successfully created. The console output says:

```
Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Entwicklung\workspace\vscode-remote-try-node-main,target=/workspaces/vscode-remote-try-node-main,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=c:\Entwicklung\workspace\vscode-remote-try-node-main -l vsch.quality=stable -l vsch.remote.devPort=0 --entrypoint /bin/sh vsc-vscode-remote-try-node-main-e491ec68c95f7d66f4c22de542969066 -c echo Container started
Container started
```

### Steps to Reproduce

1. Check out the repository in WSL's filesystem with git
2. Start VS Code under Windows and open the folder
3. Next start the remote container with "Reopen in Container"

It makes no difference in the result whether I start VS Code under Windows or work with the [Remote - WSL Extention](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl). The error messages are identical.

### Result

The Remote Container Extention only works if the repository is located in the Windows file system.

### Expected Behavior

The remote container extention should work regardless of whether the repository is in the Windows or WSL file system.

**Comment by jandubois** [comment]
Looks like the fix still made it into 1.0.0-beta.1, so please test, and let us know if the fix works for you!
