### ISSUE TITLE
wslhost.exe listen only on localhost (0.7.1 with dockerd)

### ISSUE THREAD

**Issue by zerikv** [rancher-sandbox/rancher-desktop#1180]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.2.1.7

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 1909

### What CPU architecture are you using?

x64

### Actual Behavior

The behaviour of Docker in the WSL distro used by rancher-desktop is different from Docker on Ubuntu, concerning the addresses in listen when a container is run with a bound port.

### Steps to Reproduce

Just start a `nginx` container with the external port `38080` bound on the internal http port :
```
$ docker run -d --name test-nginx -p 38080:80 nginx
cc9620d916c8147f3d3b0b2903b53cf13fcacc9006e13bc90fd6790f761c77b8
```
The container is started and the external port should be listen on all interfaces for IP v4 and v6 :
```
$ docker container ls | egrep '(nginx|CONTAINER)'
CONTAINER ID   IMAGE  COMMAND                  CREATED             STATUS          PORTS                                    NAMES
cc9620d916c8   nginx  "/docker-entrypoint.…"   3 minutes ago       Up 40 seconds   0.0.0.0:38080->80/tcp, :::38080->80/tcp  test-nginx
```

### Result

But actually `netstat` shows that only the local addresses are bound by the listener.
```
$ netstat -anto | egrep -a '(38080|Proto)'
  Proto  Adresse locale         Adresse distante       état            PID      état de déchargement
  TCP    127.0.0.1:38080        0.0.0.0:0              LISTENING       10020    InHost
  TCP    [::1]:38080            [::]:0                 LISTENING       10020    InHost
```
So the container is not reachable with the external IP of the host.

### Expected Behavior

In a Docker installed on Ubuntu the external port is reachable with any available IP on the host (locals and externals).
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

# docker version
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

# docker run -d --name test-nginx -p 38080:80 nginx
977bb07890323434549aee02bfd0be4ab13644d0f02cfcc348c6ea91e2895147

# docker container ls | egrep '(nginx|CONTAINER)'
CONTAINER ID   IMAGE   COMMAND                  CREATED          STATUS          PORTS        
977bb0789032   nginx   "/docker-entrypoint.…"   6 seconds ago   Up 5 seconds   0.0.0.0:38080->80/tcp, :::38080->80/tcp   test-nginx

# ss -antp | egrep '(38080|State)'
State    Recv-Q    Send-Q       Local Address:Port         Peer Address:Port    Process                                                          
LISTEN   0         4096               0.0.0.0:38080             0.0.0.0:*        users:(("docker-proxy",pid=166659,fd=4))                        
LISTEN   0         4096                  [::]:38080                [::]:*        users:(("docker-proxy",pid=166667,fd=4))                        
```
One expected the same behaviour with the Docker managed by rancher-desktop.

**Comment by zerikv** [comment]
In the nginx container : nginx listen on all interfaces
```
$ wsl -d rancher-desktop -- docker exec test-nginx netstat -anp | grep ':80'
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1/nginx: master pro
tcp6       0      0 :::80                   :::*                    LISTEN      1/nginx: master pro
```

In the rancher-desktop VM : docker-proxy listen on all interfaces
```
$ wsl -d rancher-desktop  -- netstat -anp | grep 38080
tcp        0      0 0.0.0.0:38080           0.0.0.0:*               LISTEN      4003/docker-proxy
tcp        0      0 :::38080                :::*                    LISTEN      4011/docker-proxy
```

On the Windows host: wslhost.exe listen only on local interfaces 
```
$ netstat -ano | grep 38080
  TCP    127.0.0.1:38080        0.0.0.0:0              LISTENING       15452
  TCP    [::1]:38080            [::]:0                 LISTENING       15452

$ tasklist | grep 15452
wslhost.exe                  15452 Console                    2     5 088 Ko
```
I have tried to use a proxy port as explained in this Microsoft documentation : 
[Accessing a WSL 2 distribution from your local area network (LAN)](https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan) 
```
PS C:\WINDOWS\system32> netsh interface portproxy add v4tov4 listenport=38081 listenaddress=0.0.0.0 connectport=38080 connectaddress=127.0.0.1

PS C:\WINDOWS\system32> netsh interface portproxy show all

Écouter sur ipv4 :             Connecter à ipv4 :

Adresse         Port        Adresse         Port
--------------- ----------  --------------- ----------
0.0.0.0         38081       127.0.0.1       38080

PS C:\WINDOWS\system32> netstat -ano | grep ':3808'
  TCP    0.0.0.0:38081          0.0.0.0:0              LISTENING       3816
  TCP    127.0.0.1:38080        0.0.0.0:0              LISTENING       15452
  TCP    [::1]:38080            [::]:0                 LISTENING       15452
```
But that doesn't work for me :
```
$ curl -sv http://<HOST_IP>:38081
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 38081 (#0)
> GET / HTTP/1.1
> Host: localhost:38081
> User-Agent: curl/7.63.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
```

**Comment by philippe-granet** [comment]
Have toi tried https://github.com/CzBiX/WSLHostPatcher

**Comment by zerikv** [comment]
@philippe-granet : thanks for your suggestion, but in my environment I can't apply this kind of unofficial patch.

**Comment by zerikv** [comment]
Sorry but here the version 1.1.0 doesn't fix the problem.

With the Rancher-Desktop 1.1.0
``` 
$ powershell "(Get-Item -path 'C:\Users\xxxxx\AppData\Local\Programs\Rancher Desktop\Rancher Desktop.exe').VersionInfo.ProductVersion"
1.1.0.0
```
installed on Windows 10
```
$ cmd /C ver
Microsoft Windows [version 10.0.19043.1526]
```
when I run a Nginx container :
``` 
$ docker run -d --name test-nginx -p 38080:80 nginx
3d9ada605d3563f598775636fc8fdb3655e53b314037ad4e0418829345d1183c
```
the external port should be listening on all interfaces :
```
$ docker container ls --format='{{.Names}}\t{{.Ports}}'
test-nginx      0.0.0.0:38080->80/tcp, :::38080->80/tcp
```
but in fact the external port is bound only on the localhost interface :
```
$ netstat -anto | grep 38080
  TCP    127.0.0.1:38080        0.0.0.0:0              LISTENING       16436    InHost
  TCP    [::1]:38080            [::]:0                 LISTENING       16436    InHost
```
It's the opposite behaviour described in the issue #1626 (the user want bind the port only on the localhost but it is actually bound on all interfaces). But in this case the problem occurs on macOS.

**Comment by dominikhuembeli** [comment]
Same here. I use Windows 11 with dockerd.

**Comment by alsolh** [comment]
I am having this issue intermittently in windows 10, seems like it works only on the initial network where you were connected before starting rancher desktop even sometimes not always and had to do a workaround of nginx on host to be able to reach some services

to reproduce this issue, try switching networks after running the container, the host ip will not be reachable only localhost

![image](https://user-images.githubusercontent.com/22778662/158533704-647e43ba-52cd-4366-a22d-1238011826dc.png)

![image](https://user-images.githubusercontent.com/22778662/158533774-e484fb7b-4446-4856-8eac-8c6123f2719b.png)

![image](https://user-images.githubusercontent.com/22778662/158533745-fe409c26-2f60-42ca-8aaa-7f714a5ce53d.png)

![image](https://user-images.githubusercontent.com/22778662/158533833-e11ac535-87c2-4faf-a7a0-541759a341ed.png)

**Comment by dominikhuembeli** [comment]
@jandubois can you please reopen this issue? Does not seem to be resolved.

**Comment by jandubois** [comment]
> @jandubois can you please reopen this issue? Does not seem to be resolved.

Sure! @Nino-K can you take a look?

**Comment by dominikhuembeli** [comment]
Hey @Nino-K, there are some similar issue: 
* https://github.com/rancher-sandbox/rancher-desktop/issues/1724
* https://github.com/rancher-sandbox/rancher-desktop/issues/1420

Can you link them?

**Comment by dominikhuembeli** [comment]
@Nino-K  Any news when this is going to be fixed?

**Comment by Nino-K** [comment]
@dominikhuembeli This work is certainly on our roadmap and it should get picked up soon for our next release. Unfortunately, until then you would have to use `netsh portproxy` utility as a workaround.

**Comment by gaktive** [comment]
https://github.com/rancher-sandbox/rancher-desktop/issues/2677 should address this. Once that's in, then we should simply validate this.

**Comment by jandubois** [comment]
@Nino-K #2677 is fully merged; please validate this bug and close if successful!

**Comment by danilagalimov** [comment]
You can also use `v4tov6` forwarding for the same address, I used this command to make testcontainers work:
`netsh interface portproxy add v4tov6 listenaddress=localhost listenport=2375 connectaddress=::1 connectport=2375`
