### ISSUE TITLE
Bump Trivy to version 0.22

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#1188]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Trivy 0.22 comes with the ability to scan images that use rpm-ndb (including openSUSE and SLE). This helps us better inform users about the security of their built images.

### Proposed Solution

Upgrade the deployed version of trivy to 0.22

**Comment by mattfarina** [comment]
When one runs `npm ci` (as it happens in CI to build RD) the latest version of Trivy is automatically pulled in. We are not pinning to a version which is a separate issue.

The latest version is being pulled in and used. I tested this.
