### ISSUE TITLE
Spike: Component Testing

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1200]
### Description
Expanding our test automation suite, component testing will be very welcomed to be part of Rancher Desktop test automation.
It can be straight-forward to implement using Cypress (component testing - Vue package) or Playwright using golden images (image comparison) 

Ref: https://github.com/cypress-io/cypress

### How it works?
Cypress will provide a blank canvas where we can `mount` components in isolation, not being necessary to load the backend! The component will be render in a real browser (our case chromium) instead inside of the terminal.

### Objective
As our application will grow, our component will come grow along. Implementing an automated visual testing for component will assist us to improve the quality, reduce the component bugs and also free up our time (manually verifying each single component rendered).

**Comment by jandubois** [comment]
This is not being planned.
