### ISSUE TITLE
Factory Reset does not restart app

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1201]
### Rancher Desktop Version

0.7.0-95-g3d15186

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

macOS

### Operating System / Build Version

Monterey 12.0.1

### What CPU architecture are you using?

x64

### Windows User Only

N/A

### Actual Behavior

Performing `factory-reset` does not restart the app and it keeps the app in a "broken-state".

### Steps to Reproduce

1. Install dev package version: 0.7.0-95-g3d15186
2. Wait until app be ready to use
3. Navigate to `Troubleshooting` tab and click `Factory Reset`
4. Should see the warning modal and the app won't restart.

### Result

* Application does not restart after factory reset.
* Other buttons are disabled, such as `Reset Kubernetes`

### Expected Behavior

Application should close/open after performing Factory Reset.

### Additional Information

No logs were found, after Factory Reset is performed.
You need to manually close Rancher Desktop application through system tray or force quit through activity monitor app.

**Comment by rak-phillip** [comment]
Is build 0.7.0-95-g3d15186 from before or after #1199 was merged? I just tested with 0.7.0-98-g417abb3 and factory reset appeared to be behaving as expected.

**Comment by evertonlperes** [comment]
> Is build 0.7.0-95-g3d15186 from before or after #1199 was merged? I just tested with 0.7.0-98-g417abb3 (the build for #1199) and factory reset appeared to be behaving as expected.

@rak-phillip 
Performed some tests on `0.7.0-100-g553fe59` - after your `rmdir` changes and it seems all good. I've noticed the issue before your changes though.

Closing this.
