### ISSUE TITLE
Support donations / payments / funding

### ISSUE THREAD

**Issue by CameronNemo** [rancher-sandbox/rancher-desktop#1207]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to support the development of this application financially.

### Proposed Solution

Set up a Liberapay, open collective, and/or GitHub sponsors. Link to the donation/payment page from the app itself, the project homepage, and this GitHub repo.

**Comment by jandubois** [comment]
Thank you for your enthusiasm!

Right now all the major contributors to this project are employed by SUSE and already paid for their work, so there is no need to support the project financially.

We are however always interested in getting additional contributors. Especially as the project matures, it should become easier to work on/contribute specific features. So if you know anybody capable of contributing, and want to support them directly, that would be fine.

I'm going to close this issue, but thank you again for your support!
