### ISSUE TITLE
Verify that password-less sudo works

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1219]
It is possible that the rules added to `/etc/sudoers.d/rancher-desktop-lima` do not work:

If multiple rules match a particular command, the last matching rule will be executed, even if it is less specific than an earlier rule.

This can happen if there are additional rules in `/etc/sudoers` after the `#includedir /private/etc/sudoers.d` line, or if there is another file in `/etc/sudoers.d` that sorts alphabetically lower than `rancher-desktop-lima` (the files are read in alpha order), see e.g. https://github.com/rancher-sandbox/rancher-desktop/issues/1152#issuecomment-1006254779

We should detect this situation and display a proper dialog instead of having failing `limactl` commands with the reason hiding in the log file.

One way to detect this would be to include a no-op probe command in our sudoers file, e.g.

```
%everyone ALL=(root:wheel) NOPASSWD:NOSETENV: /bin/ls /
```

and then check:

```console
$ sudo --user root --group wheel --non-interactive /bin/ls /
sudo: a password is required
```

If the command fails like this, then something else is taking precedence over our sudoers file.

**Comment by asantos2000** [comment]
My company (financial) does not allow me to change /etc/sudoers. I have admin permission, but I need to type the password every time. And since version 0.6.0 rancher-desktop does not work anymore. In the last version 1.0.1, the error is:

```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

time="2022-02-17T11:31:30-03:00" level=info msg="Using the existing instance \"0\""
time="2022-02-17T11:31:30-03:00" level=info msg="Starting switch daemon for \"shared\" network"
time="2022-02-17T11:31:32-03:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2022-02-17T14:31:32.214Z: + limactl start --tty=false 0
2022-02-17T14:31:32.214Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-02-17T14:31:32.215Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Is there any workaround? We're using rancher-desktop as a replacement of docker-desktop on mac and windows.

**Comment by jandubois** [comment]
We are moving away from using the `sudoers` mechanism to allow password-less operations.

In a first step we will allow operation as an unprivileged user (with reduced functionality, as we can't use vmnet interfaces without being `root`).

In a later release we will switch to a privileged helper process model, where the admin password will only be required during installation.
