### ISSUE TITLE
Enabling dockerd mode breaks Docker Desktop

### ISSUE THREAD

**Issue by milas** [rancher-sandbox/rancher-desktop#1221]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

N/A

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.1

### What CPU architecture are you using?

x64

### Actual Behavior

Docker Desktop gets into a broken state requiring a full uninstall + reinstall

### Steps to Reproduce

1. Install Docker Desktop (if not already installed - I'm using 4.3.2, which is latest as of 2022-01-11)
2. Install Rancher Desktop
3. In Rancher Desktop preferences, switch to `dockerd` mode
4. Quit Rancher Desktop
5. Launch Docker Desktop + attempt to `docker run --rm hello-world`

### Result

Docker Desktop gets into an extremely broken state where it thinks it's working but isn't. Even resetting it via preferences doesn't seem to fix things, needed to do a full fresh install.

### Expected Behavior

Rancher Desktop does not break Docker Desktop

### Additional Information

I think that Rancher Desktop is overwriting `/var/run/docker.sock` and causing trouble.

I wonder if Rancher Desktop could create `/var/run/rancher.sock` and suggest setting `DOCKER_HOST=unix:///var/run/rancher.sock` in  your shell profile, e.g. `~/.zshrc`.

**Comment by jandubois** [comment]
> I think that Rancher Desktop is overwriting /var/run/docker.sock and causing trouble.

This is indeed correct. You cannot run Rancher Desktop and Docker Desktop at the same time, for this reason. However, you should be able to switch back and forth between them as long as you always stop one before you start the other.

Both Rancher Desktop and Docker Desktop will replace `/var/run/docker.sock` if it doesn't point to its own socket.

**Comment by milas** [comment]
That makes sense - a warning would definitely be nice (from Rancher Desktop) if `/var/run/docker.sock` exists and/or Docker Desktop is installed.

At least anecdotally, myself and a coworker both did the same thing in our eagerness to try out Rancher Desktop in `dockerd` mode of launching it w/ Docker Desktop still running, and had to do a full reinstall of Docker Desktop to restore it (restarting Docker Desktop after exiting Rancher Desktop didn't help, nor did "Clean / purge data" in Docker Desktop; possible another option would have, but I went for the full reinstall at that point).

**Comment by evertonlperes** [comment]
@milas 
Here's the issue for this: https://github.com/rancher-sandbox/rancher-desktop/issues/1081

**Comment by milas** [comment]
Thanks! Closing this as #1081 covers a solution and links to this now.
