### ISSUE TITLE
Add support for commandline arguments

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1222]
Any value in `settings.json` should be configurable from the commandline:

```console
# on MacOS
open -a "Rancher Desktop" --args --debug --kubernetes-version 1.21.8

# on  Windows
start "%LOCALAPPDATA%\Programs\Rancher Desktop\Rancher Desktop.exe" --debug --kubernetes-version 1.21.8
```

This can be implemented by simply changing the `settings.yaml` file before initializing the app. It would be more robust than the user editing the JSON file manually.

I think the easiest way to map settings properties to argument names would be to take them verbatim, and separate levels with a `-`, as I've done above: `--kubernetes-version`.

Aesthetically it looks weird to me to keep the uppercase (e.g. `--portForwarding-includeKubernetesServices`), but it would be the easiest to explain/document.

For boolean options I would like to see us use the Go convention that `--debug` is equivalent to `--debug=true`.

**Comment by jandubois** [comment]
I've added this to the Next milestone because I want it to be considered in conjunction with #816 to have a consistent UX. Actual implementation may not happen for this milestone.

**Comment by ericpromislow** [comment]
Regarding the weird case:

If an option is all lower-case, we do case-insensitive matching on the existing prefs set.
If the option is in mixed case, we do case-sensitive matching, assuming the user knows exactly what they're doing.

And of course +1 on the go-ish implicit `true`.

**Comment by ericpromislow** [comment]
Closed in https://github.com/rancher-sandbox/rancher-desktop/pull/2025#event-6437475796
