### ISSUE TITLE
Memory and CPU in the settings file are VM settings and not kubernetes

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1223]
While writing #1222 I noticed that `memoryInGB` and `numberCPUs` are misplaced:

```json
$ jq < ~/Library/Preferences/rancher-desktop/settings.json
{
  "version": 3,
  "kubernetes": {
    "version": "1.21.8",
    "memoryInGB": 6,
    "numberCPUs": 2,
    "port": 6443,
    "containerEngine": "containerd"
  },
  "portForwarding": {
    "includeKubernetesServices": false
  },
  "images": {
    "showAll": true,
    "namespace": "k8s.io"
  },
  "telemetry": false,
  "updater": false,
  "debug": false
}
```

Not sure if it is worth fixing, but now that I know about it, it bothers me. 😄 

But also, if #1222 is implemented, I would want the arguments to be `--memoryInGB` or `--memory-in-gb`, and not `--kubernetes-memory-in-gb`...

**Comment by jandubois** [comment]
Please consider the upgrade use-case: the existing `settings.json` may still have the settings under the old name, and they need to be migrated.

**Comment by ericpromislow** [comment]
Bump the settings version number on this so we know whether these two properties belong (currently: inside k8s, after: not inside it).

**Comment by jandubois** [comment]
`containerEngine` also does not belong inside `kubernetes` anymore.
