### ISSUE TITLE
Make `sudo` usage configurable

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1225]
We should have a global `sudo` setting persisted in `settings.yaml`.

The "Rancher Desktop needs root access to ..." explainer dialog currently has only a single button: "Ok":

<img width="532" alt="Screen Shot 2022-01-11 at 4 07 25 PM" src="https://user-images.githubusercontent.com/78947/149040988-5ec989f9-e183-4454-a0c3-5e6aa3532535.png">

We need to add a "Cancel" button and an explanation: "When you cancel this dialog, any features requiring `sudo` will not be available."

When the user clicks ok, the next prompt asks for the password:

<img width="555" alt="Screen Shot 2022-01-11 at 4 07 42 PM" src="https://user-images.githubusercontent.com/78947/149040993-7b3da415-a979-410a-9373-82aa4856ee4c.png">

When the user cancels the sudo password prompt we display this dialog, and then quit the app:

<img width="532" alt="Screen Shot 2022-01-11 at 4 07 58 PM" src="https://user-images.githubusercontent.com/78947/149041000-093f3b31-2978-4283-94a0-acdfd941586b.png">

Instead we should go back to the explainer dialog, giving the user another chance to run RD without `sudo`.

There needs to be another checkbox somewhere in the UI to show the current status, and to allow to re-enable sudo mode.

**Comment by jsoref** [comment]
Fwiw, there's text nearby, but this Electron path is only used for macOS and on macOS this field isn't used, so, it apparently needs to be moved into the main section:
https://github.com/rancher-sandbox/rancher-desktop/blob/3048d150f8fb1aadcb66891b41777dddd691f1d2/src/k8s-engine/lima.ts#L702

(Note to future self)
