### ISSUE TITLE
Don't configure `vmnet` networks when `sudo` is unavailable

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1226]
Prerequisite: #1225 

Without sudo we need to make the following changes:

* no vmnet binaries will be installed into `/opt/rancher-desktop`
* `/etc/sudoers.d/rancher-desktop-lima` file will not be created
* `lima.yaml` will not include a `networks` section
* docker socket will not be overwritten when `dockerd` is the runtime

We need to add some text how the user can set either `DOCKER_HOST` or create a docker context (we should have support to create the context, but that can come later).

**Comment by mook-as** [comment]
I believe this is actually done already (we don't create the vmnet stuff; and _separately_, we don't create a docker socket, but that shouldn't be covered under the given issue summary).
