### ISSUE TITLE
Issue when installing on some networks.

### ISSUE THREAD

**Issue by robertsirc** [rancher-sandbox/rancher-desktop#1231]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monteray 12.3

### What CPU architecture are you using?

x64

### Actual Behavior

When on conference networks (tried two different networks here) I can download the dmg install and start up the app. The app hangs at "Starting Kubernetes API".

### Steps to Reproduce

Download and Install RD and attempt to start it cleanly from a public or conference network.

### Result

The logs show this:

Fetching releases from https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 -> rate limit exceeded

### Expected Behavior

Either start the cluster up or have this bomb out and let me know it will never start up due to rate limit.

**Comment by jandubois** [comment]
Possible solutions:

1. Bundle a cached list of all available versions to fall back on
2. Show only the latest versions from the channel server (#988)
3. Show only the already cached versions (which means it won't work on a fresh install)
4. Provide a way to use a GITHUB token

I think (4) is clunky and requires too much effort. Solutions (1), (2), (3) can be combined to provide a best effort result.

**Comment by robertsirc** [comment]
I would be just happy with a timeout that it cannot full what it can.

**Comment by mook-as** [comment]
We should already be doing (3) [here](https://github.com/rancher-sandbox/rancher-desktop/blob/33dd5880bdc4d12c33975b506e9baa1152cee83a/src/k8s-engine/k3sHelper.ts#L306).  However, there was a cache [layout change](https://github.com/rancher-sandbox/rancher-desktop/pull/988) going from 0.6 to 0.7, so the cache may haven been dropped if it's a fresh run right after an upgrade.

(We should still fix it so it works on first run too, of course.)

**Comment by jandubois** [comment]
I thought this was a fresh install. Since #988 has already been merged, RD should have the channel-server versions. It should just not fail/hang when the Github api doesn't return anything because it is throttled.

**Comment by robertsirc** [comment]
I installed 0.7.1 over 0.6.

**Comment by gunamata** [comment]
As per my discussion with @robertsirc, Rancher Desktop installation has been working fine in the recent demos.  Closing this now.
