### ISSUE TITLE
Cannot resolve a host from a local hosts entry

### ISSUE THREAD

**Issue by jhollmannk** [rancher-sandbox/rancher-desktop#1245]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2

### What CPU architecture are you using?

x64

### Actual Behavior

An entry in the local hosts file cannot be resolved inside a running container depending on the resolve method of the linux running inside the container.

### Steps to Reproduce

Start RancherDesktop with **dockerd** as the container runtime.
Make an entry in your local c:\Windows\system32\drivers\etc\hosts like
`10.3.6.25 host.docker.internal`
start a basic alpine:
`docker run -it --rm alpine sh`
In the started container shell call
`ping host.docker.internal`

### Result

The ping fails with the message
`ping: bad address 'host.docker.internal'`

### Expected Behavior

The ping should succeed.

### Additional Information

To make things more complicated:

The command
`getent hosts host.docker.internal`
in the alpine container returns the expected address
`10.3.6.25         host.docker.internal  host.docker.internal`

Additionally if you start a basic ubuntu
`docker run -it --rm ubuntu sh`
and install ping in the running shell
`apt update`
`apt install iputils-ping`
The ping comand described above works out of the box.

So this is an issue with how a hostname is resolved in the running linux. I raise this issue because DockerDesktop does not have this problem with the alpine container.

**Comment by gaktive** [comment]
@mook-as, does https://github.com/rancher-sandbox/rancher-desktop/pull/1302 address this?

**Comment by mook-as** [comment]
I believe that #1302 does address this:
- We run a `dnsmasq`, which _does_ read `/etc/hosts` (that was generated from the Windows one at `C:\Windows\system32\drivers\etc\hosts`).
- That means it picks up the entries and _responds as a DNS server_ to them.

(Tested by adding a host on the Windows side, and running an `alpine` container — even though that host name isn't listed in `/etc/hosts` in the container, it works fine.)

**Comment by jandubois** [comment]
Sounds like this should be fixed then. Please open a new issue if you still have problems resolving DNS with the next release!

**Comment by AKhilesh-D** [comment]
@jandubois This issue reopens in 1.17  (I upgraded from 1.16 to 1.17 , in 1.16 it was working ok)

**Environment details** 
OS: Windows 11 23H2
WSL version: 2.4.8.0
Kernel version: 5.15.167.4-1

**.wslconfig**

[experimental]
bestEffortDnsParsing=true

=============
I have added following line in c:\Windows\System32\drivers\etc\hosts

172.26.80.1 rd-local

--Steps to reproduce --

**start a basic alpine:**
docker run -it --rm alpine sh
**In the started container shell call**
ping rd-local
