### ISSUE TITLE
Cannot connect to a port mapped from another container from inside a running container

### ISSUE THREAD

**Issue by jhollmannk** [rancher-sandbox/rancher-desktop#1246]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2

### What CPU architecture are you using?

x64

### Actual Behavior

I want to run a postgresql database as a container on my PC with its port 5432 mapped to my host. So any locally running application can use this database with localhost:5432. That works just fine.

Now I want to run other containers via docker-compose and use the same postgresql database. And this does not work and boils down to the problem that the port itself is somehow not reachable from the running containers.

### Steps to Reproduce

Start RancherDesktop with dockerd as the container runtime.
Start a simple hello service with a mapped port 50001:
`docker run -e PORT=50001 -p 50001:50001 gcr.io/google-samples/hello-app:2.0`
You can verify that the service is running by calling `curl http://localhost:50001` in a command prompt on your PC.

Now start a basic alpine container:
`docker run -it --rm alpine sh`
and install curl inside
`apk add curl`
Let's say the IP of your PC is 10.3.6.25, so call
`curl http://10.3.6.25:50001`

### Result

The curl command fails with the message
`curl: (28) Failed to connect to 10.3.6.25 port 50001 after 133682 ms: Operation timed out`

### Expected Behavior

The output of the hello service should be displayed.

### Additional Information

I verified that curl with my local IP address works by starting an application locally (not as a docker container with a mapped port).

So a local application that opens a port 50001 can be reached on my PC and from inside a running container using my IP address as expected

But a running container with an exposed and mapped port 50001 can only be reached on my PC but not from inside a running container.

**Comment by gunamata** [comment]
@jhollmannk ,

As the case you are trying here is that of cross container communication and hence directly using the host ip address doesn't work at the moment. Can you please use the ip given by this command `docker inspect bridge --format="{{(index .IPAM.Config 0).Gateway}}"` instead to curl from your second container. 

We also have a issue #1767 to map the ip address from command provided above to  `gateway.docker.internal` in one of the upcoming releases. Hope this helps.

**Comment by gunamata** [comment]
Closing this as there's a workaround as mentioned above. https://github.com/rancher-sandbox/rancher-desktop/issues/1767 is being tracked in planning sessions.
