### ISSUE TITLE
[Apple Silicon] Error dialing backend after suspending

### ISSUE THREAD

**Issue by yuchanns** [rancher-sandbox/rancher-desktop#1253]
### Rancher Desktop Version

1.0.0-beta.1

### Rancher Desktop K8s Version

v1.23.1

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

After my M1Max wake up from a suspension, I couldn't get a shell to running containers, only got an error which is `Error from server: error dialing backend: dial tcp: lookup lima-rancher-desktop: no such host`. I confirm that those containers are still working because I can visit the app inside.

### Steps to Reproduce

Suspend mbp for a while, then execute a command like `kubectl exec -it pod_name -n namespace -- /bin/bash`

### Result

Error from server: error dialing backend: dial tcp: lookup lima-rancher-desktop: no such host

### Expected Behavior

Start a shell session inside running containers.

**Comment by gaktive** [comment]
We should verify if this is fixed by #1440
