### ISSUE TITLE
Add Rancher Desktop to startup apps so that the app auto starts after machine boots

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1254]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Users need to manually start Rancher Desktop every time. 

### Proposed Solution

It would be nice to add Rancher Desktop to the list of "startup" apps/programs so that the app automatically starts after machine boots.

**Comment by jandubois** [comment]
This should be a configuration option and not something that is done by default.

I also think this is Windows-only. On macOS you can simply right-click on the app in the dock and toggle the "Open at login" option, so there is no need to duplicate that functionality inside the app. And I think on Linux it depends on the desktop manager how you accomplish this, so not sure if we want to implement all the different mechanisms...

**Comment by gunamata** [comment]
I agree, it should be a configurable option. And, to be consistent, it would be better to provide this configuration within RD for all 3 OSs even though those OSs themselves provide ways to add apps to "startup".

**Comment by oemergenc** [comment]
I am using the _system way_ on mac os x by adding Rancher Desktop to my startup apps. The problem with this approach is on every system boot i need to enter my password when Rancher Desktop starts since it somehow need admin rights and forgot that i already granted access on the last boot.

**Comment by rafaribe** [comment]
> I am using the _system way_ on mac os x by adding Rancher Desktop to my startup apps. The problem with this approach is on every system boot i need to enter my password when Rancher Desktop starts since it needs admin rights to initialize and it somehow seems to forget that i already granted the access on the last boot.

The same is happening to me. It's a bit annoying. Does it create a new VM each time or just boots the same VM? Because I wouldn't expect this to happen with the same VM.

**Comment by jandubois** [comment]
> Does it create a new VM each time or just boots the same VM?

It is the same VM each time. I also feel like RD prompts for sudo too often. It only should do that when the configuration has changed, e.g. the `/var/run/docker.sock` symlink has changed, or you have installed a new RD version.

Could you record what RD wants to do when it is asking for the password? It should show an explainer dialog before, that lists the expected actions.

**Comment by oemergenc** [comment]
Sure, basically it is like this:

* System boots
* Rancher Desktop starts up
* A popup occurs telling that RD needs admin privileges
* After entering the password, it takes about 1,5 min to completely startup

See here:
![rd](https://user-images.githubusercontent.com/10146674/151430685-e8ab134e-dda0-4bf3-835a-b1a2c1bc0732.gif)

**Comment by oemergenc** [comment]
One more thing to note which is somehow annoying, is that RD seems to switch the kubernetes context (e.g. `kubectl config current-context`) to **rander-desktop**, although another one was active during shutdown.

**Comment by a1031** [comment]
> Could you record what RD wants to do when it is asking for the password? It should show an explainer dialog before, that lists the expected actions.

@jandubois I've installed RD for the first time today, version 1.2.1. I'm on an M1 Mac running macOS 12.3. After going through the initial setup and providing my password when requested each time, RD starts successfully.

Then after restarting my machine and launching RD, it requires my password to start the VM, but only for `* /var/run/docker.sock`:

![Screen Shot 2022-03-24 at 5 51 50 PM](https://user-images.githubusercontent.com/5606114/160017037-c879f1a7-0c1f-476c-82ec-6b009464291d.png)

**Comment by robbiemu** [comment]
> I also think this is Windows-only. On macOS you can simply right-click on the app in the dock and toggle the "Open at login" option, so there is no need to duplicate that functionality inside the app. And I think on Linux it depends on the desktop manager how you accomplish this, so not sure if we want to implement all the different mechanisms...

This is incorrect though. The solution proposed here says "after machine boots" which is before login (so multiple users on the same machine can all benefit from the same k8s from rancher) -- that would require writing a plist for /Library/LaunchDaemons on the mac.

**Comment by quigamdev** [comment]
Hi, is this feature planned to be delivered any time soon?

**Comment by ljohnston** [comment]
@jandubois 

> I also think this is Windows-only. On macOS you can simply right-click on the app in the dock and toggle the "Open at login" option, so there is no need to duplicate that functionality inside the app. And I think on Linux it depends on the desktop manager how you accomplish this, so not sure if we want to implement all the different mechanisms...

Sure, you can add this to your login items, but that's not the same as having an option within the application to "start on login". With Rancher Desktop added to the user's login items, it will _always_ show the Rancher Desktop UI on login, which is not the desired behavior (and, of course, there's the annoying prompt to allow administrative access, but that's a different issue). 

What the app should do with a "start on login" behavior is nothing more than add the icon to the menu bar and start itself up in the background. Rancher Desktop already shows its status (starting vs started) in its menu bar icon, so it's nearly there. It just needs to avoid throwing up any UIs or prompts. For a perfect example of how this should work, look no further than Docker Desktop.

**Comment by guice** [comment]
In short: I have an expectation Rancher Desktop handles startup same as Docker Desktop. Rancher Desktop should add an option to add the docker demon upon start, like Docker Desktop. I don't want to launch the whole Rancher Desktop UI upon starting up - just start the backend demon.

**Comment by rak-phillip** [comment]
@jandubois closing this issue as completed in #3144
