### ISSUE TITLE
Epic: Configure private registries

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#1277]
This epic is about using private registries.

Out of scope: insecure registries, registry mirrors.

Tasks:

- [X] CA certs installed on the host are automatically installed inside the guest
- [x] #1699
- [x] #2013

Related, but not part of this epic: Credential forwarder from VM to host #2014

For a later milestone:
- [x] #2264
- [ ] configure /var/lib/kubelet/config.json

See also #721

**Comment by jandubois** [comment]
Closing because the required features have been delivered in 1.4.1. Followup epic in #2401
