### ISSUE TITLE
Rancher Desktop does not work on Windows 10 LTSC 1809

### ISSUE THREAD

**Issue by ksondere** [rancher-sandbox/rancher-desktop#1283]
### Rancher Desktop Version

1.0.0-beta.1

### Rancher Desktop K8s Version

1.23

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Actual Behavior

Install the beta version of Rancher Desktop and start.

The dialog for nrdctl vs moby shows up...I've tried both.  

I can see Rancher Desktop as a background process in the tasks list but it never shows up in the Windows tray.

### Steps to Reproduce

Install the beta version of Rancher Desktop and start.

The dialog for nrdctl vs moby shows up.  I've installed twice using each option and get the same failure.

### Result

If I look at the background.log file here is what I see

2022-01-19T22:48:52.262Z: Expected error moving config: Error: ENOENT: no such file or directory, rename 'C:\Users\kelly.sonderegger\AppData\Roaming\xdg.config\rancher-desktop\settings.json' -> 'C:\Users\kelly.sonderegger\AppData\Roaming\rancher-desktop\settings.json'
2022-01-19T22:48:52.265Z: Expected error moving cache: Error: ENOENT: no such file or directory, rename 'C:\Users\kelly.sonderegger\AppData\Local\xdg.cache\rancher-desktop' -> 'C:\Users\kelly.sonderegger\AppData\Local\rancher-desktop\cache'
2022-01-19T22:49:06.963Z: Error starting up: Error: wsl.exe exited with code 4294967295
    at ChildProcess.<anonymous> (C:\Users\kelly.sonderegger\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:1:8014)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: 'Invalid command line option: --list\r\r\n' +
    'Usage: wsl.exe [option] ...\r\r\n' +
    'Options:\r\r\n' +
    '    -d, --distribution <DistributionName>\r\r\n' +
    '        Launch the specified distribition.\r\r\n' +
    '\r\r\n' +
    '    -e, --exec <CommandLine>\r\r\n' +
    '        Execute the specified Linux command. The remainder of the arguments are\r\r\n' +
    '        used as the command line to execute.\r\r\n' +
    '\r\r\n' +
    '    -u, --user <UserName>\r\r\n' +
    '        Run as the specified user.\r\r\n' +
    '\r\r\n' +
    '    --help\r\r\n' +
    '        Display this usage information.\r\r\n' +
    '\r\r\n' +
    '    --\r\r\n' +
    '        Stop parsing arguments and pass the remainder to the Linux process.\r\r\n'
}

### Expected Behavior

I expect to see the rancher desktop icon in the Windows trey

**Comment by mook-as** [comment]
Which version of Windows 10 Enterprise do you have? (Ideally, please provide the second line of the output when you start `winver.exe`; something like `Version 21H2 (OS Build 19044.1466`.)

I suspect (but am not yet certain) that you're something like Windows Enterprise LTSC 2019, and I'm not sure we have proper environments to test those.

**Comment by ksondere** [comment]
Version 1809 (OS Build 17763.1879)

**Comment by mook-as** [comment]
Right; I don't think we'd be able to support that (we're [listed as 1909+](https://github.com/rancher-sandbox/rancher-desktop/blob/main/README.md#system-requirements), though I'm not sure how much we managed to test with 1909).

Looking at their release history, they made [significant changes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18305) to the `wsl.exe` command line sometime around Windows 10 1903.

**Comment by gaktive** [comment]
We only work on 1909 and higher, so please try on a newer version of Windows.

**Comment by ksondere** [comment]
This is version 19043.1469
