### ISSUE TITLE
WSL screen keeps on top aftec activation

### ISSUE THREAD

**Issue by eirisdg** [rancher-sandbox/rancher-desktop#1290]
### Rancher Desktop Version

1.0.0-beta1

### Rancher Desktop K8s Version

1.23.1

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise / 21H1 19043.1110

### What CPU architecture are you using?

x64

### Actual Behavior

I've chosen the option to reinstall Rancher Desktop with Containerd (moby) because all the vscode plugins works on it.
After the reinstall, I choose the WSL integration, and a screen keeps on top and doesn't close. 
If I try to close, it keeps opening everytime.

I think is not a if issue, but the screen doesn't show anything, and the logs doesn't say anything too.

![image](https://user-images.githubusercontent.com/5367659/150403985-f39aa864-f347-43f9-b822-05be9ee6c7fa.png)

### Steps to Reproduce

Install Rancher Desktop with DockerD and WSL Integration with Ubuntu

### Result

Window with wsl (without interaction) keeps opened.

### Expected Behavior

Don't know exactly...

**Comment by evertonlperes** [comment]
Thanks for reporting @eirisdg .
Closing this. Duplicated https://github.com/rancher-sandbox/rancher-desktop/issues/1248
