### ISSUE TITLE
Show an error popup when running on an unsupported setup

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1294]
Right now we do not support Windows older than Windows 10 1909, or macOS older than macOS 10.15 Catalina, and know that it won't work.

In that case we should display a dialog upfront and exit instead of running into the known issue later.

Not sure if we have something easy to check for on Linux. Maybe support for nested virtualization?

**Comment by gaktive** [comment]
Need to add Manuele once he has access to this repo.

**Comment by gaktive** [comment]
Current plan: we'll circle back to this after one other feature for the next milestone is taken care of.

**Comment by gaktive** [comment]
Could be part of the overall efforts tied to the Diagnostics page: #2319
