### ISSUE TITLE
Only use trusted certificates

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1295]
Right now we are using the [mac-ca](https://github.com/jfromaniello/mac-ca/blob/master/index.js) module to retrieve a list of system certs. It essentially just parses the output of

```console
$ /usr/bin/security find-certificate -a -p
-----BEGIN CERTIFICATE-----
MIIEFzCCAv+gAwIBAgIBGzANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzET
MBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlv
biBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMTAwNTI2MTkx
```

The problem is that this does not take account of the actual trust settings on each certificate. E.g. it will include this CA cert:

<img width="466" alt="Screen Shot 2022-01-19 at 7 12 27 PM" src="https://user-images.githubusercontent.com/78947/150266101-f52ce264-43a4-47ab-afc7-58dd3d062dc1.png">

We only want to use certificates that are trusted for basic X.509 operations and not yet expired. For this the certs have to be split into separate files and checked individually:

```console
$ /usr/bin/security find-certificate -c mkcert -p > /tmp/mkcert

$ /usr/bin/security verify-cert -l -L -R offline -c /tmp/mkcert; echo $?
Cert Verify Result: CSSMERR_TP_NOT_TRUSTED
1

$ /usr/bin/security find-certificate -c SUSE -p > /tmp/suse

$ /usr/bin/security verify-cert -l -L -R offline -c /tmp/suse; echo $?
...certificate verification successful.
0
```

We could try to update the upstream module, but the whole logic is so trivial that we could also just implement it ourselves.

I also found a Ruby implementation in [osx-ca-certs.rb](https://github.com/raggi/openssl-osx-ca/blob/master/osx-ca-certs.rb) for comparison.

<hr>

I've only checked the macOS version; we should look into the other platforms too to make sure we only use trusted CAs.

**Comment by mook-as** [comment]
Note to self: *don't* try to use FFI for this; trying to do FFI with ObjectiveC is… not fun. (The relevant documentation is [`SecItemCopyMatching(query:result:)`](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/certificates/storing_a_certificate_in_the_keychain).)
