### ISSUE TITLE
Reset Kubernetes and Images doesn't delete images

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1296]
### Rancher Desktop Version

1.0.0.beta.1

### Rancher Desktop K8s Version

1.21.0

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

No

### Actual Behavior

`Reset Kubernetes and Images` doesn't delete images.

### Steps to Reproduce

With docker (moby) as the run time, I do below steps..

- `docker pull alpine`

- Check images list in the UI. The newly pulled alpine does appear in the list.

- Click `Reset Kubernetes and Container Images`

- After kubernetes is reset, Check images list in the UI. The alpine image still in the list.

### Result

alpine image still shows up in the Images list in the UI. So does the `docker images` command output.

### Expected Behavior

`Reset Kubernetes and Images` should delete images.

**Comment by evertonlperes** [comment]
Hi @gunamata 
On macOS, I cannot replicate the issue. All non-rancher images, are deleted after `Reset Kubernetes and Container Images`.

`docker pull alpine`:

```bash
❯ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Image is up to date for alpine:latest
docker.io/library/alpine:latest
❯ docker image ls
REPOSITORY                       TAG       IMAGE ID       CREATED         SIZE
alpine                           latest    c059bfaa849c   8 weeks ago     5.59MB --> pulled non-rancher image
rancher/library-traefik          2.4.8     deaf4b1027ed   9 months ago    91.3MB
rancher/coredns-coredns          1.8.3     3885a5b7f138   11 months ago   43.5MB
rancher/klipper-helm             v0.4.3    3b0b04aa3473   12 months ago   145MB
rancher/local-path-provisioner   v0.0.19   148c19256271   13 months ago   42.4MB
rancher/metrics-server           v0.3.6    9dd718864ce6   2 years ago     39.9MB
rancher/klipper-lb               v0.1.2    897ce3c5fc8f   2 years ago     6.1MB
rancher/pause                    3.1       da86e6ba6ca1   4 years ago     742kB
```

<img width="957" alt="Screen Shot 2022-01-20 at 6 58 05 PM" src="https://user-images.githubusercontent.com/37411123/150429304-43c94ca6-e918-4d5a-a215-6d02ad845473.png">


After `Reset Kubernetes and Container Images`:

```bash
❯ docker image ls
REPOSITORY                       TAG       IMAGE ID       CREATED         SIZE
rancher/library-traefik          2.4.8     deaf4b1027ed   9 months ago    91.3MB
rancher/coredns-coredns          1.8.3     3885a5b7f138   11 months ago   43.5MB
rancher/klipper-helm             v0.4.3    3b0b04aa3473   12 months ago   145MB
rancher/local-path-provisioner   v0.0.19   148c19256271   13 months ago   42.4MB
rancher/metrics-server           v0.3.6    9dd718864ce6   2 years ago     39.9MB
rancher/klipper-lb               v0.1.2    897ce3c5fc8f   2 years ago     6.1MB
rancher/pause                    3.1       da86e6ba6ca1   4 years ago     742kB
```
<img width="936" alt="Screen Shot 2022-01-20 at 7 20 29 PM" src="https://user-images.githubusercontent.com/37411123/150431487-42eff03c-641a-46ac-a55a-ca1e1a571995.png">


Also did a double check on my Windows VM, and it seems to be working fine:
`docker pull alpine && docker image ls`:
<img width="1792" alt="Screen Shot 2022-01-20 at 7 12 11 PM" src="https://user-images.githubusercontent.com/37411123/150430768-c18418d6-2f80-4a4f-9741-396cbde7b598.png">

`docker image ls` after reset k8s and images:
<img width="1579" alt="Screen Shot 2022-01-20 at 7 13 54 PM" src="https://user-images.githubusercontent.com/37411123/150430778-143a4af0-952a-4ee4-aee8-e1716d723272.png">


Tested on `1.0.0-beta1` on macOS Monterey and Windows 10 PRO 2H02

**Comment by gunamata** [comment]
my bad. I had Docker Desktop running in the background and it caused the confusion. Not a issue, Closing it.
