### ISSUE TITLE
There was an unknown error starting kubernetes...exited with code 1

### ISSUE THREAD

**Issue by zbabac** [rancher-sandbox/rancher-desktop#1298]
### Rancher Desktop Version

1.0.0-beta1

### Rancher Desktop K8s Version

1.23.1 (latest)

### What operating system are you using?

Other Linux

### Operating System / Build Version

KDE Neon: Linux 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

### Actual Behavior

Tried installations with linux zip from releases page, appimage (v0.7.1) and apt deb installation (shown here). The result is the same. After first run, rancher-desktop asks to select k8s image and containerd, then downloads image, tries to start and throws an error (logs show it can't find alpine image). Then I reboot laptop, start again, k8s image is checked, displays "starting virtual machine", after 10 minutes timeout, it displays the error message (screenshot). 
![rancher-desktop-error](https://user-images.githubusercontent.com/10812743/150498201-3c63a33b-31d7-4b6e-afb0-464b76f12f9c.png)

No kubernetes started, the same error happens with every run, including after reboot. 
v0.7.1 exhibits the same behavior. Also with zip release and appimage release.

Steps taken to troubleshoot, correct:
- firewall switched off,
- stopped libvirt and virbr0 NIC,
- removed dnsmasq conf for libvirt

The ps shows that qemu image is started and that vm is at 192.168.5.15. ssh to that IP on port 37943 timeouts (just like in logs).
Logs from ~/.local.share/rancher-desktop/logs/ are attached.
[os-release.txt](https://github.com/rancher-sandbox/rancher-desktop/files/7911808/os-release.txt)
[rancher-desktop-ps.txt](https://github.com/rancher-sandbox/rancher-desktop/files/7911809/rancher-desktop-ps.txt)
[rancher-desktop-logs.tar.gz](https://github.com/rancher-sandbox/rancher-desktop/files/7911810/rancher-desktop-logs.tar.gz)
.

### Steps to Reproduce

removed rancher-desktop:
sudo apt remove rancher-desktop
- removed all folders from home dir referencing rancher and k3s
- reinstalled: apt install rancher-desktop
- restarted laptop

### Result

![rancher-desktop-error](https://user-images.githubusercontent.com/10812743/150498703-00cd4516-71f8-4c62-81be-abdc0d49c8be.png)

### Expected Behavior

started virtual machine and k3s, able to use it

**Comment by zbabac** [comment]
Also tried with different k8s image 1.22.5, the result is the same.

**Comment by zbabac** [comment]
Tried with dual boot with Windows 10 1909 (exe installer v1.0.0-beta1). It installs, installs WSL, reboot, GUI just flashes on run and then closes. Task manager show that rancher-desktop is running, taking 25% cpu, but no gui is displayed. Didn't have time to troubleshoot in detail. Could it be specific hw, cpu? Laptop is Lenovo X1 Carbon, gen 9.

**Comment by zbabac** [comment]
The same issue with v0.6.1 (kubernetes v1.21.8)

**Comment by adamkpickering** [comment]
Have you checked that your processor has VT-X or AMD-V? And that it is enabled? I suspect something like this.

**Comment by zbabac** [comment]
Thanks mate, but that was the first thing to check.
Actually, after yesterdays GA release, I updated and now it works!
I don't know what they changed, but they changed it well.
