### ISSUE TITLE
WSL shell opens when WLS integration is enabled

### ISSUE THREAD

**Issue by schoeppi5** [rancher-sandbox/rancher-desktop#1299]
### Rancher Desktop Version

1.0.0-beta1

### Rancher Desktop K8s Version

1.20.7

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 21H2 19044.1469 

### What CPU architecture are you using?

x64

### Actual Behavior

When I select Ubuntu-20.04 WSL Integration in the UI it creates the symlink and a Ubuntu shell opens with no content. I can't write in it or anything. If I close it, it opens up again. When I deselect the WSL integration in the UI, the shell closes again. If I manually create the symlink, the UI shows the integration as enabled and no window opens. When I restart my machine in this state and open Rancher Desktop again after bootup, the window opens up again and closes, once the integration is deselected again

### Steps to Reproduce

Install Rancher Desktop 1.0.0-beta1 with WSL 2 already installed and Ubuntu-20.04 installed, enabled the WSL Integration for Ubuntu-20.04

### Result

A shell opens with no content shown

### Expected Behavior

No random shell should open if the integration is enabled

**Comment by evertonlperes** [comment]
Hi @schoeppi5 
Thanks for filling the issue.
Could you verify if the error that you're describing is similar to https://github.com/rancher-sandbox/rancher-desktop/issues/1248 ?

**Comment by schoeppi5** [comment]
Yes, however, I don't have the window falshing in the images tab, just the behaviour [documented here](https://github.com/rancher-sandbox/rancher-desktop/issues/1248#issuecomment-1014781744). Thanks, for pointing that out, I missed that when looking through the issues already opened on that

**Comment by evertonlperes** [comment]
> Yes, however, I don't have the window falshing in the images tab, just the behaviour [documented here](https://github.com/rancher-sandbox/rancher-desktop/issues/1248#issuecomment-1014781744). Thanks, for pointing that out, I missed that when looking through the issues already opened on that

No problem.
I'll close this issue and we can track it at #1248
