### ISSUE TITLE
RD unable to overwrite binaries symlinks

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1300]
### Rancher Desktop Version

1.0.0-beta1

### Rancher Desktop K8s Version

all

### What operating system are you using?

macOS

### Operating System / Build Version

Monterey 12.1

### What CPU architecture are you using?

x64

### Windows User Only

N/A

### Actual Behavior

RD does not overwrite binaries symlinks during Factory Reset.

### Steps to Reproduce

1. Install DD and open the DD app
2. Wait until app be ready to use
3. Close DD app and install RD `1.0.0-beta1`
4. Open RD app
5. Navigate to `Supporting Utilities`
6. Should see one or multiple binaries being already linked to DD app.

### Result

Binary being linked to another container management application:

<img width="1017" alt="Screen Shot 2022-01-21 at 9 56 06 AM" src="https://user-images.githubusercontent.com/37411123/150530783-2b6ac75d-52b1-404c-b00c-1d11335a3c3b.png">

### Expected Behavior

RD should overwrite DD symlinks if DD application is closed.

### Additional Information

Even uninstalling DD application, the binary still linked:
```bash
lrwxr-xr-x    1 root          admin        54 20 Jan 15:26 docker -> /Applications/DD.app/Contents/Resources/bin/docker
lrwxr-xr-x    1 root          admin        62 21 Sep 13:56 docker-compose -> /Applications/DD.app/Contents/Resources/bin/docker-compose
```

An workaround is:
* Delete docker binary (`usr/local/bin/docker`) or manually unlink the binary
* Restart RD app and check the binary on the `Supporting Utilities` tab.

```bash
 ls -la /usr/local/bin/docker
lrwxr-xr-x  1 evertonperes  admin  80 21 Jan 09:39 /usr/local/bin/docker -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker
```

Might be related to this: https://github.com/rancher-sandbox/rancher-desktop/issues/1081

**Comment by jandubois** [comment]
> RD should overwrite DD symlinks if DD application is closed.

I thought we had logic to overwrite a dangling symlink (where the existing symlink points to a file that no longer exists).

I disagree that overwriting a symlink is acceptable just because the other app is not currently running.

**Comment by gaktive** [comment]
Need to hold on this until we come up with consensus from https://github.com/rancher-sandbox/rancher-desktop/discussions/1512

**Comment by jandubois** [comment]
We will no longer create symlinks in `/usr/local/bin`, so dropping this issue.
