### ISSUE TITLE
Getting Rancher Desktop running on Apple m1

### ISSUE THREAD

**Issue by stephanwesten** [rancher-sandbox/rancher-desktop#1309]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In my quest for replacing Docker Desktop with Rancher Desktop on my macOS Monterey / m1 pro, i ran into the following problem:

Installing Rancher Desktop went fine, except for the known, documented problem with "Insufficient permission to manipulate /usr/local/bin: Error: EACCES: permission denied, access '/usr/local/bin'"
This leaves nerdctl unchecked 
The other tools docker and kubectl were already installed by me and apparently recognised by RD.
Installing an image into RD using kubectl went fine and smooth less.

The problem is nerdctl. I thought that m1 was supported by RD, however installing nerdctl on macOS requires lima. (only very high level I've an idea what this is about)
I even went into the source code of nerdctl and see that it only support Linux and Windows.

The video demo on the RD website shows nerdctl. But I now get the impression that this is not working on m1.

### Proposed Solution

Document clearly what the limitations are for m1.

**Comment by jandubois** [comment]
`nerdctl` should work just fine on M1. We just have to provide alternative means to install utilities for users who don't have write access to `/usr/local/bin`.

`nerdctl` is just a shell wrapper; the actual binary has to run inside the VM:

```console
$ cat /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/nerdctl
#!/bin/bash
set -eu -o pipefail

scriptname="${BASH_SOURCE[0]}"
while [ -L "${scriptname}" ]; do
    scriptname="$(readlink "${scriptname}")"
done
scriptdir="$(cd "$(dirname "${scriptname}")" && pwd)"

if ! LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "${scriptdir}/../lima/bin/limactl" ls --json | grep '"name":"0"' | grep -q '"status":"Running"'; then
  echo "Rancher Desktop is not running. Please start Rancher Desktop to use nerdctl";
  exit 1
else
  LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "${scriptdir}/../lima/bin/limactl" shell 0 sudo --preserve-env=CONTAINERD_ADDRESS nerdctl "$@"
fi
```

You just have to create a symlink to it somewhere on your `PATH` to get it working.

Or you could put ` /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin` on your `PATH` directly to get all the bundles utilities:

```console
$ ls /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin
docker  helm    kubectl kuberlr nerdctl
```

**Comment by stephanwesten** [comment]
Thanks! Will try this out and update

**Comment by stephanwesten** [comment]
All seems to be working. I realized it is just missing documentation on what is installed and how it works. For example, looking at the bin folder I noticed that Docker cli was also installed.

This looks very promising.

**Comment by jandubois** [comment]
> For example, looking at the bin folder I noticed that Docker cli was also installed.

Note that you configure RD with either `containerd` or `moby/dockerd` as the container runtime. You use `nerdctl` with `containerd` or the `docker` cli with `moby`. Even though `moby` internally also uses `containerd`, you cannot use `nerdctl` in that configuration. `kubectl` works with both, of course.

**Comment by jandubois** [comment]
> All seems to be working.

Thanks, closing.
