### ISSUE TITLE
WSL Integration UI caption doesn't indicate docker-proxy coupling

### ISSUE THREAD

**Issue by schoeppi5** [rancher-sandbox/rancher-desktop#1311]
### Rancher Desktop Version

1.0.0-beta.1

### Rancher Desktop K8s Version

1.20.7

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 21H2 19044.1469

### What CPU architecture are you using?

x64

### Actual Behavior

WSL Integration UI tab caption:
> Expose Rancher Desktop's Kubernetes configuration to Windows Subsystem for Linux (WSL) distros

### Steps to Reproduce

Open WSL Integration tab

### Result

see above

### Expected Behavior

Something like:
> Expose Rancher Desktop's Kubernetes configuration **and Docker socket** to Windows Subsystem for Linux (WSL) distros

### Additional Information

Requested by @mook-as in issue #1248

**Comment by jandubois** [comment]
See also #1208 which seems closely related.
