### ISSUE TITLE
Terminal window always visible

### ISSUE THREAD

**Issue by sascha-andres** [rancher-sandbox/rancher-desktop#1314]
### Rancher Desktop Version

1.0.0-beta.1

### Rancher Desktop K8s Version

1.20.14

### What operating system are you using?

Windows

### Operating System / Build Version

11 latest stable

### What CPU architecture are you using?

x64

### Windows User Only

No specific software installed

### Actual Behavior

A Windows terminal window pops up with just a cursor blinking:

![image](https://user-images.githubusercontent.com/3052075/150789381-4f680c21-8e90-4497-8ed5-4740f4c2ee71.png)

When closing, the window re-appears. Is closes only when quitting Rancher Desktop.

### Steps to Reproduce

Start Rancher Desktop

### Result

A terminal windows open on my desktop

### Expected Behavior

No visible terminal window

**Comment by sascha-andres** [comment]
When quitting Rancher Desktop the wsl process seems to be terminated, but the window stays open:

![image](https://user-images.githubusercontent.com/3052075/150790079-95a49e74-f42f-43e2-b7a4-3e4599cb4a99.png)

**Comment by evertonlperes** [comment]
Hi @sascha-andres , thanks for filling the issue.

Just to double check, Is the issue that you describing similar as https://github.com/rancher-sandbox/rancher-desktop/issues/1248#issuecomment-1014781744?

**Comment by sascha-andres** [comment]
Is a duplication of https://github.com/rancher-sandbox/rancher-desktop/issues/1248
@evertonlperes Thanks for pointing thi sout
