### ISSUE TITLE
Unable to build - Image Fetch Error - service/builder is not available/installed on Windows 10 & WSL2 for v1.0.0-beta-1 and v1.0.0

### ISSUE THREAD

**Issue by lincoln42** [rancher-sandbox/rancher-desktop#1325]
### Rancher Desktop Version

1.0.0-beta-1 and 1.0.0

### Rancher Desktop K8s Version

1.23.1

### What operating system are you using?

Windows

### Operating System / Build Version

19043.1466

### What CPU architecture are you using?

x64

### Windows User Only

VPN is ZScaler

### Actual Behavior

After installing the above version, when I run a `kubectl get all -A -o name` command I do not see a listing for the builder service. 
Additionally I also cannot build any docker files. When I attempt to do so, I get the error 'Unrecognized Image Format'. Additional text of the error is:
     
`  error: failed to solve: node:lts-alpine; failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/lts-alpine": dial tcp: lookup registry-1.docker.io on .... : i/o timeout`

### Steps to Reproduce

Install beta version as above with ZScaler running and attempt to build any docker file.

### Result

```
[+] Building 10.4s (3/3) FINISHED
=> [internal] load build definition from Dockerfile                                                               0.3s
=> => transferring dockerfile: 953B                                                                               0.1s
=> [internal] load .dockerignore                                                                                  0.3s
=> => transferring context: 2B                                                                                    0.1s
=> ERROR [internal] load metadata for docker.io/library/node:lts-alpine                                          10.0s
------
> [internal] load metadata for docker.io/library/node:lts-alpine:
------
Dockerfile:1
--------------------
   1 | >>> FROM node:lts-alpine
   2 |
   3 |     # Install chromium manually
--------------------
error: failed to solve: node:lts-alpine: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/lts-alpine": dial tcp: lookup registry-1.docker.io on 192.168.0.1:53: read udp 192.168.3.43:55223->192.168.0.1:53: i/o timeout
FATA[0011] unrecognized image format
```

### Expected Behavior

Rancher Desktop should be able to build the docker file.

**Comment by gaderGarcia** [comment]
when I installed Rancher desktop I got a similar error getting timeout and unable to pull or create an image, after some time spent, I found in my case the issue was related to the WSL access to the internet, and I followed the steps mentioned on this page https://stackoverflow.com/a/67756837, using vi commands I was able to update and apply the changes.

```
cmd > wsl
# vi /etc/resolv.conf
```
maybe your issue is similar to this.

**Comment by lincoln42** [comment]
@gaderGarcia  RD uses its own wsl distro, do you know how to go about updating the DNS on the RD distro? this seems like it is related to past issues #702 and #770 observed on the Mac but this is happening on Windows WSL2

**Comment by gaderGarcia** [comment]
@lincoln42 I'm not an expert, but when I type in my command line `wsl --list --verbose` I got a list and the only one that it was referenced is rancher-desktop, seeing that I assumed that any command that I type it will make reference to that distro, then I type in my command line `wsl` to enter in that mode and then I type the vi commands to apply the changes for the nameserver and so on.

![image](https://user-images.githubusercontent.com/7773945/151407183-c24a8918-f3eb-49a9-b1c1-e2632e8d947f.png)

![image](https://user-images.githubusercontent.com/7773945/151407245-02d1cccc-393d-490c-8076-7296ae49979f.png)

**Comment by lincoln42** [comment]
@gaderGarcia you are right, the issue is a DNS issue wherein when the rancher-desktop WSL distro starts up, it seems to put itself as the DNS server instead of properly picking up the DNS servers configured for the currently active (VPN or not) connection of the host. I came across this issue on the WSL board (https://github.com/microsoft/WSL/issues/5336) which again seems to be the same thing but people are running scripts to make the update manually. 

   I also came across this really good article (https://unix.stackexchange.com/questions/589683/wsl-dns-not-working-when-connected-to-vpn) on the issue and there 'Rubin Simons' has provided a PowerShell script that you can run via the task scheduler or just manually targeting your WSL distro to fix the DNS by picking up the connect DNS servers from the currently connected network adapter. I have tried this script and it works, I am able to build images now and the changes stick even after a reboot and going on and off the VPN as well.
   
    @jandubois can the Rancher Desktop team take a look at making this DNS fix, provided by 'Rubin Simons', part of the product? It will save all of us having to make hacky script fixes for this issue. I have already burnt many productive hours finding a fix for this and it would save everyone else the hassle as well.

**Comment by Nino-K** [comment]
We have implemented a [process](https://github.com/rancher-sandbox/rancher-desktop/pull/1592) that defines the most suitable DNS servers in `/etc/resolve.conf` while on a dedicated VPN tunnel. These changes should be available in our next release.
