### ISSUE TITLE
Rancher Desktop will not run if Time Machine is not allowed to execute

### ISSUE THREAD

**Issue by r0b2g1t** [rancher-sandbox/rancher-desktop#1337]
### Rancher Desktop Version

0.71

### Rancher Desktop K8s Version

1.21.6

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.1

### What CPU architecture are you using?

x64

### Actual Behavior

When I try to start Rancher Desktop I get an error that execution of tmutil ends with a SIGKILL error. The reason is that Rancher will exclude lima from Time Machine backups ([link](https://github.com/rancher-sandbox/rancher-desktop/blob/e5c825241e83d90c4536d91f1cfa54590b54ab39/src/k8s-engine/lima.ts#L578)) but Time machine is not allowed to run on my Mac. The lima.ts file has no exception handling and the function ``childProcess.spawnFile`` handles errors only with a ```reject``` ([link](https://github.com/rancher-sandbox/rancher-desktop/blob/e5c825241e83d90c4536d91f1cfa54590b54ab39/src/utils/childProcess.ts#L236)).
<img width="291" alt="Bildschirmfoto 2022-01-26 um 14 11 20" src="https://user-images.githubusercontent.com/5357541/151171174-8b25c4d3-344c-49a0-931c-002b0e883ef7.png">

### Steps to Reproduce

Disallow to start any ```tmuitl``` process. And try to start rancher desktop

### Result

Rancher Desktop wont work and the cluster will not start. With the error.
<img width="291" alt="Bildschirmfoto 2022-01-26 um 14 11 20" src="https://user-images.githubusercontent.com/5357541/151171135-8d32222d-8acd-4e61-b009-b68c5ad2bfec.png">

### Expected Behavior

Rancher Desktop should recognize the error and continue the execution.

**Comment by jansalapatek** [comment]
tmutil is blocked in our case due to company policies. The reason, why tmutil is invoked by Rancher in the first place, imho is related to the effort to exclude Rancher VMs from timemachine backups (https://github.com/rancher-sandbox/rancher-desktop/issues/354).
