### ISSUE TITLE
Project Status still listed as beta

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#1339]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

N/A

### What operating system are you using?

macOS

### Operating System / Build Version

N/A

### What CPU architecture are you using?

x64

### Actual Behavior

In the General settings it says "Project Status: beta"

### Steps to Reproduce

Start RD

### Result

You "Project Status: beta" on the General settings

### Expected Behavior

The project status should either say stable or be removed.

**Comment by somersuo** [comment]
Perhaps the project status line can be completely removed?

https://github.com/rancher-sandbox/rancher-desktop/blob/fcf762c4cdd88aa481a94e8c28c5c543d9ebb1bb/src/pages/General.vue#L8
