### ISSUE TITLE
Document how Rancher Desktop is different from Rancher

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#1342]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We get many questions about Rancher Desktop with the assumption it's Rancher itself. 

### Proposed Solution

Document how Rancher Desktop is different from Rancher.

**Comment by gunamata** [comment]
Added some information to the current faq question about `Rancher vs Rancher Desktop`. 

https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/19

**Comment by gunamata** [comment]
We added some information clarifying the difference between Rancher and Rancher Desktop with below PRs. So, closing this issue for now. We will reopen if we need to clarify further.

https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/19
https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/20
