### ISSUE TITLE
Rancher Desktop fails to start on Ubuntu 18.04

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#1344]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.2

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 18.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

### Actual Behavior

Rancher Desktop starts, downloads Kubernetes, and then errors out with the following error:

```
Error Starting Kubernetes
Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
Last command run:
limactl start --tty=false /home/adam/.local/share/rancher-desktop/lima/_config/0.yaml

Context:
Starting virtual machine

Some recent logfile lines:
time="2022-01-26T14:14:59-07:00" level=info msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
time="2022-01-26T14:14:59-07:00" level=info msg="[hostagent] QEMU has exited"
time="2022-01-26T14:14:59-07:00" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/home/adam/.local/share/rancher-desktop/lima/0/ha.stderr.log\")"
2022-01-26T21:14:59.339Z: + limactl start --tty=false /home/adam/.local/share/rancher-desktop/lima/_config/0.yaml
2022-01-26T21:14:59.339Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
2022-01-26T21:14:59.339Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

The error occurs both when RD is installed via deb package, and when it is run from an AppImage.

### Steps to Reproduce

Install RD via deb or AppImage, and run it.

### Result

RD fails to start. See above for error message.

### Expected Behavior

RD should start Kubernetes successfully.

### Additional Information

![image](https://user-images.githubusercontent.com/19395776/151248599-de0c181b-8187-4853-95e8-b048dbec6ea0.png)

**Comment by jw-websensa** [comment]
In my case, when I checked lima logs as it is advised in this message, it was problem with permissions to kvm device (it can be accessed only by root or kvm group members). I could not really find out what user rancher desktop uses, so I just lightened permissions to kvm:
```bash
sudo chmod +666 /dev/kvm
```
and it worked
However it would be probably recommended to add required user to kvm group.

**Comment by pulberg** [comment]
Same issue on Ubuntu 21.10, I tried changing perms as @jw-websensa suggested, but that did not work.

**Comment by adamkpickering** [comment]
@jw-websensa's advice should work. Another way of working around this is to add your user to the `kvm` group:

```
sudo adduser $USER kvm
```

You'll need to log out and log back in to make this work.

Of course, the user shouldn't have to do this. I'm looking for a better solution at the moment.

**Comment by pulberg** [comment]
@adamkpickering Same error after adding myself to the `kvm` group

**Comment by adamkpickering** [comment]
Darn. Can you please make a separate bug report for it? I suspect that it is a different problem.

Closing this issue as it has been addressed by a merged PR in the docs.rancherdesktop.io repo.
