### ISSUE TITLE
fails to startup on windows because space in folder name isn't escaped

### ISSUE THREAD

**Issue by szantopeter** [rancher-sandbox/rancher-desktop#1350]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

v1.23.2

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

We have a corporate proxy server

### Actual Behavior

Rancher desktop fails to start with message 

Error: No active cluster!

Running command wsl --distribution rancher-desktop --exec /mnt/c/Users/pszanto/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig

### Steps to Reproduce

start rancher desktop

### Result

Running command wsl --distribution rancher-desktop --exec /mnt/c/Users/pszanto/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig

### Expected Behavior

The error happens because rancher desktop by default installs itself with a space in the directory name then it forgets to escape it when it calls. This command fails

`wsl --distribution rancher-desktop --exec /mnt/c/Users/pszanto/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig`

(note the space between Rancher Desktop)

The easiest would be to install rancher into a directory name without space, but I can't customize the installation folder name

**Comment by ikogan** [comment]
Is there any workaround for this right now?

**Comment by szantopeter** [comment]
I think I was wrong with this. I copied rancher to a folder without space, started rancher from there but the application still fails. so the problem is something else. I will open a separate ticket about that

**Comment by gaktive** [comment]
@szantopeter When do you open the other ticket, feel free to link back here for context.
