### ISSUE TITLE
Change bottom left text to wrap instead of truncate in main window

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1353]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Long blobs of text are hard to read, they're even harder to read when elipisized or otherwise truncated:
![image](https://user-images.githubusercontent.com/2119212/151269982-fd8d5077-1c71-4f1e-bcda-c348a9c09199.png)
![image](https://user-images.githubusercontent.com/2119212/151269989-f4ba3195-5ef3-49ff-a9c4-247a419b7311.png)

A tooltip is not a solution, as it tends to use an even smaller font, and the text in the bottom left changes rapidly

### Proposed Solution

1. Instead of a single line, the text should wrap and be willing to grow up if necessary.
2. There should be an *easy* way to see a log of all of the messages (the fact that there's a `Troubleshooting` view with a `Show Logs` button isn't quite sufficient as there are at least 11 items there and it isn't remotely obvious which file would have the logs for that area) shown in this area.

### Additional Information

The picture is from 0.7.1, but the same general behavior is present in 1.0.0.

**Comment by evertonlperes** [comment]
Thanks for your feature request!
I'm closing this issue due duplication.
We're tracking an enhancement on this matter on https://github.com/rancher-sandbox/rancher-desktop/issues/1217
