### ISSUE TITLE
Documentation on how RD can be used on airgap environment

### ISSUE THREAD

**Issue by bwgjoseph** [rancher-sandbox/rancher-desktop#1358]
### Problem Description

I would like to know how RD can be configured and used in an airgap environment. I've raised this in the [slack](https://rancher-users.slack.com/archives/C0200L1N1MM/p1643254904826419) channel and was asked to create an issue here

Currently, it is unclear if RD can be used, and if able to what are the criteria, and what to note

Some of the unknown are:

- setting up with self-hosted repository (e.g jfrog artifactory)
- configuring authentication process
- setting up with custom CA cert
- how to bring the caches into airgap environment for installation
- ...and possibly more

Quoted from the slack @jandubois 

```
The container runtime will need the CA cert to validate the registry (assuming that you are using a self-signed cert inside the airlock). Then you may need to provide credentials, unless you don't have authentication configured

But there are registries that require auth tokens that expire and need to be refreshed periodically, and this is when things become interesting...

It will not work automatically; it will download k3s and the k3s-airgap images on first run, so you would have to bring those as well and put them into the cache.

I suspect that RD will always try to download the list of available k3s versions on startup, so it may not actually work airgapped yet. It is definitely a goal, but it may not be working right now
```

### Proposed Solution

To have the process of bringing RD to airgap environment, and the how-tos

### Additional Information

Related to #888

**Comment by jtravee** [comment]
Understood issue is blocked currently, but would need details once it's able to be documented.

**Comment by ericpromislow** [comment]
More notes:

* Prerequisite for Windows: Requires WSL 2 and a version of the WSL kernel (see the installer) -- this requires a network connection

For other components, they should be installable from removable media populated on a network-connected machine. We need to document what these are, and where they need to be deployed. For example:

* the kubernetes cache
* the `kuberlr` cache (with appropriate version of `kubectl`)

**Comment by ericpromislow** [comment]
Errors on startup:

macos on uninitialized air-gapped system :

1. 
```
Error Starting Kubernetes
Error: No version available
```

Populate `~/Library/Cache/rancher-desktop/`:
```
$ mkdir -p ~/Library/Caches/rancher-desktop/k3s
$ cp k3s-versions.json ~/Library/Caches/rancher-desktop/
$ cp -r k3s/v1.23.8+k3s2 ~/Library/Caches/rancher-desktop/k3s/
```

2. After cache is populated with a minimum (`k3s-versions.json` and `k3s/vN.N.N+k3sN`):

```
Error Starting Kubernetes
Error: /Users/ericp/workspace/rancher/desktop/resources/darwin/bin/kubectl exited with code 255
Last command run:
/Users/ericp/workspace/rancher/desktop/resources/darwin/bin/kubectl --context rancher-desktop cluster-info
```

When run from the command-line:
```
$ time kubectl --context rancher-desktop cluster-info
I0711 15:03:41.651538    9709 versioner.go:84] Right kubectl missing, downloading version 1.23.8+k3s2
F0711 15:04:11.654550    9709 main.go:69] Error while trying to get contents of https://storage.googleapis.com/kubernetes-release/release/v1.23.8/bin/darwin/amd64/kubectl.sha256: Get https://storage.googleapis.com/kubernetes-release/release/v1.23.8/bin/darwin/amd64/kubectl.sha256: dial tcp: i/o timeout

real	0m30.081s
user	0m0.038s
sys	0m0.042s
```

`~/.kuberlr/PLATFORM-ARCH` needs to be manually populated with an acceptable version of `kubectl`. For example, we have one file in k3s cache: `v1.23.8+k3s2/` -- So any of `kubectl1.22.*` through `kubectl1.24.*` should be acceptable.

Other notes on macos:

3. Rebuilding `~/.docker` can be done without a network connection.
4. The data in `~/Library/Application Support/rancher-desktop` gets rebuilt without a network connection.

**Comment by ericpromislow** [comment]
Written up at https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/95

**Comment by gaktive** [comment]
@btat we'll move this over to the docs repo.

**Comment by bwgjoseph** [comment]
I just saw the latest release, a step closer to running on airgap environment a possibility. Thanks for the work!

> During initial setup a network connection is required 

I saw the following in the change log, and wish to clarify if that is going to be the long term, or would be the long term goal to be able to run without initial network connection as long as we can provide the necessary files/binaries separately?

**Comment by jandubois** [comment]
> would be the long term goal to be able to run without initial network connection as long as we can provide the necessary files/binaries separately?

"Providing the necessary files/binaries" is what requires the initial network connection. You should be able to put everything into a tarball or whatever and transport it to an offline machine, and then have it all work there. This should already work with this release; we are just missing the documentation on how to create the required tarball.

It is not clear if we will eventually create a packager that will do this for you automatically, but you should be able to already do this manually.

I don't know if there are still more issues with the installer. The macOS and Linux installers should work offline, but the Windows install may try to fetch WSL2 and updated WSL2 kernels from Microsoft. Assuming all the prerequisites are in place, I would hope that the installer works offline, but I don't think we have tested it yet.

**Comment by taleodor** [comment]
Tested on MacOS and Windows. If Windows has WSL2 pre-installed, offline installation works. So overall, yes, it's more of documentation issue at this point + certainly, a native support for some sort of self-contained installer would be nice.

**Comment by bwgjoseph** [comment]
> > would be the long term goal to be able to run without initial network connection as long as we can provide the necessary files/binaries separately?
> 
> "Providing the necessary files/binaries" is what requires the initial network connection. You should be able to put everything into a tarball or whatever and transport it to an offline machine, and then have it all work there. This should already work with this release; we are just missing the documentation on how to create the required tarball.
> 
> It is not clear if we will eventually create a packager that will do this for you automatically, but you should be able to already do this manually.
> 
> I don't know if there are still more issues with the installer. The macOS and Linux installers should work offline, but the Windows install may try to fetch WSL2 and updated WSL2 kernels from Microsoft. Assuming all the prerequisites are in place, I would hope that the installer works offline, but I don't think we have tested it yet.

I see, thanks for the explanation. I probably misunderstood from the release notes, thinking that I have to first be connected to the internet, grab all necessary packages/binaries, before going offline. If it's not too complicated, you may list out the steps involved in creating the tarball, and extracting to where.

I have a machine that is without WSL2, so is able to test if that works for non WSL2 machine.

**Comment by bwgjoseph** [comment]
> Tested on MacOS and Windows. If Windows has WSL2 pre-installed, offline installation works. So overall, yes, it's more of documentation issue at this point + certainly, a native support for some sort of self-contained installer would be nice.

Do you mean if WSL2 is not pre-installed, it does not work?

**Comment by taleodor** [comment]
> Do you mean if WSL2 is not installed, it does not work? Would it be for machine that is with Hyper-V?

WSL2 is a requirement for Rancher Desktop overall. Hyper-V is not relevant here.

In a situation where you are doing an offline setup of Rancher Desktop, you need to have WSL2 pre-installed on the machine already - because it wouldn't be able to go online and set it up.

**Comment by ericpromislow** [comment]
Closed in https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/95 -- better to continue discussion on this area in [the rancher-desktop slack channel](https://rancher-users.slack.com/archives/C0200L1N1MM) and from there we can either resolve it right away or decide whether to open a new issue in the rancher-desktop or docs repo.
