### ISSUE TITLE
Cannot start Kubernetes on macOS 10.14

### ISSUE THREAD

**Issue by saghul** [rancher-sandbox/rancher-desktop#1360]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.3

### What operating system are you using?

macOS

### Operating System / Build Version

10.14.6

### What CPU architecture are you using?

x64

### Actual Behavior

The following error is displayed on a dialog:

~~~
Error Starting Kubernetes
Error: /usr/sbin/system_profiler exited with code 1
~~~

~~~
system_profiler -xml >MySystem.spx
     Creates a XML file which can be opened by System Profiler.app

2022-01-27T08:28:34.579Z: Error starting lima: Error: /usr/sbin/system_profiler exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: ''
}
~~~

### Steps to Reproduce

Start the app.

### Result

![Uploading Screen Shot 2022-01-27 at 09.30.00.png…]()

### Expected Behavior

App your start successfully.

**Comment by saghul** [comment]
Looks like https://github.com/rancher-sandbox/rancher-desktop/issues/920 is badk.

**Comment by evertonlperes** [comment]
Thanks for reporting @saghul 
Could you share the entire `background.log` and `lima.log` files? 
Also, it seems your image haven't been uploaded and it will be nice to have a image of the failure.

**Comment by saghul** [comment]
<img width="1052" alt="Screen Shot 2022-01-27 at 15 24 23" src="https://user-images.githubusercontent.com/317464/151377878-67e478cd-a925-4065-8f7f-f8d7ccffc526.png">

Here is the image it failed to be uploaded.

background.log:

<details>
<pre>
2022-01-27T14:24:19.006Z: Expected error moving Lima state: Error: ENOENT: no such file or directory, rename '/Users/saghul/Library/State/rancher-desktop/lima' -> '/Users/saghul/Library/Application Support/rancher-desktop/lima'
2022-01-27T14:24:19.561Z: Kubernetes was unable to start: Error: /usr/sbin/system_profiler exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: ''
}
</pre>
</details>

lima.log

<details>
<pre>
2022-01-27T14:24:19.451Z: Running command limactl list --json...
time="2022-01-27T15:24:19+01:00" level=fatal msg="open /Users/saghul/Library/Application Support/rancher-desktop/lima: no such file or directory"
2022-01-27T14:24:19.528Z: Could not parse lima status, assuming machine is unavailable.
Usage: system_profiler [-listDataTypes]
       system_profiler [-xml] [-timeout n] [-detailLevel n]
       system_profiler [-xml] [-timeout n] [dataType1 ... dataTypeN]

  -detailLevel n    specifies the level of detail for the report
                      mini = short report (contains no identifying or personal information)
                      basic = basic hardware and network information
                      full = all available information

  -listDataTypes    lists all the available datatypes

  -xml              generates xml output instead of plain text
                    if redirected to a file with the extension ".spx"
                    the file can be opened in System Profiler.app

  -timeout          specifies the maximum time to spend gathering information
                    the default is 180 seconds, 0 means no timeout

  Redirect stderr to /dev/null to suppress progress and error messages.

Examples:

  system_profiler
     Generates a text report with the standard detail level.

  system_profiler -detailLevel mini
     Generates a short report without identifying/personal information.

  system_profiler -listDataTypes
     Shows a list of the available data types.

  system_profiler SPSoftwareDataType SPNetworkDataType
     Generates a text report containing only software and network data.

  system_profiler -xml >MySystem.spx
     Creates a XML file which can be opened by System Profiler.app

2022-01-27T14:24:19.557Z: Error starting lima: Error: /usr/sbin/system_profiler exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: ''
}
</pre>
</details>

**Comment by saghul** [comment]
I was not running any previous version of Rancher Desktop, if that helps with anything.

**Comment by evertonlperes** [comment]
Thanks for sharing @saghul 
Currently, RD supports macOS Catalina or later only. As Mojave EOL was finished on Sept 2021, not sure if lima will support that.
Currently we're on `lima v1.17` on RD `1.0.0`.
Ref: https://github.com/rancher-sandbox/rancher-desktop/issues/859#issuecomment-951081055

@jandubois I'll mark this issue as a regression and your thoughts on this issue will be very appreciated.

**Comment by jandubois** [comment]
We tried before to support Mojave with reduced functionality, but have now additional dependencies on changes in Catalina. We've discussed that and decided not to spend any more engineering resources on supporting versions older than Catalina.

You will have to upgrade the OS if you want to run Rancher Desktop, sorry!

**Comment by jandubois** [comment]
> not sure if lima will support that.

Lima will actually still work on Mojave (with limited functionality; doesn't auto-detect DNS and proxy settings). It is code in Rancher Desktop itself now that requires Catalina and doesn't have a fallback.

**Comment by saghul** [comment]
Sounds fair. TBH this machine is not the main one I use so I simply neglected to update.

That said, IMHO, the app should just fail to start with a descriptive message if run in an unsupported environment.

Thanks for the prompt response!

**Comment by jandubois** [comment]
> That said, IMHO, the app should just fail to start with a descriptive message if run in an unsupported environment.

I completely agree, which is why I filed #1294 last week. 😄
