### ISSUE TITLE
wsl other machine integration fail due to invalid mount point

### ISSUE THREAD

**Issue by ghdiska** [rancher-sandbox/rancher-desktop#1377]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.20.15

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows 10 Enterprise Build 19044

### What CPU architecture are you using?

x64

### Actual Behavior

WSL failed to execute wsl.exe --distribution Ubuntu-18.04 --exec /mnt/c/Users/.../AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper kubeconfig --show: Error: wsl.exe exited with code 1.

my wsl setup has :
[automount]
root = /
options = "metadata"

so C: is mounted in /c and not in /mnt/c

### Steps to Reproduce

add in /etc/wsl.conf

[automount]
root = /
options = "metadata"

### Result

WSL failed to execute wsl.exe --distribution Ubuntu-18.04 --exec /mnt/c/Users/.../AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper kubeconfig --show: Error: wsl.exe exited with code 1.

### Expected Behavior

integration works with mount in /c as it works when mount is in /mnt/c?

**Comment by psclhk** [comment]
I have the same issue.

**Comment by DorianGreen** [comment]
I solved this by adding a link to the expected mount folder:
ln -s /c /mnt

**Comment by mook-as** [comment]
This should be fixed in the next version (planned to be 1.1.0); please let us know if it wasn't once that's released. (Of if you want to try it early, grab a build from CI.)
