### ISSUE TITLE
`Wiping` doesn't follow from `Reset`

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1385]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.3

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur 11.6.3

### What CPU architecture are you using?

x64

### Actual Behavior

Dialog introduced a new term `Wiping` that doesn't fit the `Reset` family of terms

### Steps to Reproduce

1. Open Rancher
2. Select Kubernetes Settings
3. Click the strange drop down arrow next to `Reset Kubernetes`
4. See a single menu item `Reset Kubernetes and Container Images`
5. Click that (?)
6. See message

        Wiping Kubernetes will delete all workloads, configuration, and images.

        Do you want to proceed?

### Result

![image](https://user-images.githubusercontent.com/2119212/151570157-bc0a5a6f-8b47-47e7-b3db-80e3bc43da5b.png)

### Expected Behavior

Verbs should be used consistently. Any change in verbiage should be supported by prose to explain the newly introduced term.

Also, order should be consistent.

As the default order is presumably _base_ (`workloads`) + _configuration_, and I'm changing _base_ to _extended base_, I'd expect to see _extended base_ + _configuration_, i.e. `delete all workloads, images and configuration`.

Really, I'd expect to be able to know what a button does before I click it. I can understand what `Reset Kubernetes` does because there's explanatory text next to it that I can read before I click it.

I'd probably also expect the explanatory text to end with a `.`, as it sure feels like a sentence and there are sentences below the `containerd` and `dockerd` items.

### Additional Information

There is no context that explains what a `wipe` or `wiping` might be and how that would differ from a `reset`.

For comparison, here's what happens when I click `Reset Kubernetes`:
![image](https://user-images.githubusercontent.com/2119212/151571556-299573d4-f7e4-4f2e-ba45-da8f919d8baf.png)

**Comment by gunamata** [comment]
@jsoref , With the recent releases, we made some improvement to the `Reset Kubernetes` button, and the related messaging. Do you think the `Reset Kubernetes` UI in the current version 1.5.1 addresses the concerns you reported in this issue?

**Comment by jsoref** [comment]
You're now consistently using exactly the same text in two places:

---
![image](https://user-images.githubusercontent.com/2119212/186480180-3341e8de-514d-4b19-8f5c-b8c24d683044.png)
---
![image](https://user-images.githubusercontent.com/2119212/186480205-b6ef2263-7a04-40c6-a83d-f82f83d4d610.png)
---
I suppose, that's better than being inconsistent. I'm not sure it's particularly valuable. In general, I think people will be able to remember what they saw before they clicked `Reset Kubernetes` while looking at the displayed dialog (and if not, they can click `Cancel`).

Here's a simple checklist based on the initial report:

- [x] Verbs should be used consistently.
   - [x] ~Any change in verbiage should be supported by prose to explain the newly introduced term.~ N/A 
- [x] Order should be consistent.
- [x] ~As the default order is presumably base (workloads) + configuration, and I'm changing base to extended base, I'd expect to see extended base + configuration, i.e. delete all workloads, images and configuration.~ N/A
- [x] I'd expect to be able to know what a button does before I click it. I can understand what Reset Kubernetes does because there's explanatory text next to it that I can read before I click it.
- [x] I'd probably also expect the explanatory text to end with a `.`
