### ISSUE TITLE
Clarify that `k3d` isn't included

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1392]
https://github.com/rancher-sandbox/rancher-desktop/blob/1df436eab3b0e6d15e9bf426ff09f81f43675bc3/src/assets/translations/en-us.yaml#L259

With the exception of `k3d`, all of the commands mentioned on this screen:
![image](https://user-images.githubusercontent.com/2119212/151585939-71654ecd-f784-45b2-9236-b82e133da091.png)
Are available in `Supporting Utilities`
![image](https://user-images.githubusercontent.com/2119212/151586264-c55e213f-b511-4bbb-8903-54a6e95ffff8.png)

**Comment by jandubois** [comment]
Let's just remove the "and k3d" part from the UI and be done with it.

Bundling `k3d` with Rancher Desktop would be a separate issue.
