### ISSUE TITLE
Cannot start nerdctl on wsl2/ubuntu limactl missing

### ISSUE THREAD

**Issue by deexem** [rancher-sandbox/rancher-desktop#1408]
nerdctl on wsl2 (Ubuntu) complains on Rancher not running/limactl missing

Rancher-Desktop Version 1.0.0

jdoe@DESKTOP-942B7IH:~$ nerdctl
/mnt/c/Users/J. Doe/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/bin/nerdctl: 13: /mnt/c/Users/J. Doe/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/bin/nerdctl: /mnt/c/Users/J. Doe/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/bin/../lima/bin/limactl: not found
Rancher Desktop is not running. Please start Rancher Desktop to use nerdctl

jdoe@DESKTOP-942B7IH:~$ ls  "/mnt/c/Users/J. Doe/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/bin/../"

Result:

bin  rancher-desktop.appdata.xml  wsl-helper

And Rancher Desktop is running with the runtime set to containerd

**Comment by jjohnson1024** [comment]
Rancher-Desktop Version: 1.0.0 runtime set to containerd
OS Version and build: Windows 10 Pro 21H2 build 19044.1466
WSL Distro: Debian 1.12.1.0
Logs are all empty (not in debug mode)

Same symptoms as @deexem when using `nerdctl` from WSL (missing resources/linux/lima directory and contents). However, `nerdctl` does work from Powershell. `kubectl` works from both Powershell and WSL.

**Comment by deexem** [comment]
Rancher Desktop Version 1.0.1
OS: Windows 10 Pro 21H2 (19044.1466)
WSL Distro: Ubuntu 16.04.7 LTS
I attached the only non 0K log

[wsl-exec.log](https://github.com/rancher-sandbox/rancher-desktop/files/8004279/wsl-exec.log)

**Comment by mook-as** [comment]
> jdoe@DESKTOP-942B7IH:~$ nerdctl
…/linux/bin/nerdctl: 13: …/linux/bin/nerdctl: …/linux/bin/../lima/bin/limactl: not found
Rancher Desktop is not running. Please start Rancher Desktop to use nerdctl

It's trying to run the code path where it _isn't_ on Windows / WSL.  Do you have a custom kernel in WSL? I ask because [we check for it](https://github.com/rancher-sandbox/rancher-desktop/blob/4d46104753eb00dfb645a77c8344f549e3d3cd57/resources/linux/bin/nerdctl#L3).  We may need a better check here.

**Comment by deexem** [comment]
No, I don't think so. My distro is vanilla.

**Comment by mook-as** [comment]
Odd. What does `/proc/version` look like in your WSL distribution?
Can you try running `/bin/sh -x $(which nerdctl)` (or equivalent), to see what it's doing?

Thanks!

**Comment by deexem** [comment]
I just checked the name wsl gave my distro

wsl -l
It is called "Legacy" that didn't sound healthy. Installed a new one via the store and now it works.
Apparently blowing the spiders off the equipment helps even purely digitally :)

**Comment by mook-as** [comment]
Ah! That sounds like it's a WSL1 distribution. Spawned #1513 to have a better error message.
