### ISSUE TITLE
Create the rancher-desktop config under $HOME/

### ISSUE THREAD

**Issue by cmoulliard** [rancher-sandbox/rancher-desktop#1415]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

That should be great that the rancher-desktop config is installed under `$HOME/.rancher-desktop` and not using the Mac path pointing to the` $HOME/Library/Application Support/rancher-desktop/` which very long, includes a space that we must `\` 

### Proposed Solution

Create the rancher config including also lima under `$HOME/.rancher-desktop`

**Comment by himslm01** [comment]
I'm not sure this is a wise change to make.
Isn't it better to stick with the Mac standard?
Even Linux apps are starting to use a standard location for config (as Rancher Desktop does on Linux) and not just poop random named folders in the users home.

**Comment by jandubois** [comment]
> Isn't it better to stick with the Mac standard?

Yes.

You can create a symlink yourself if you want to:

```console
$ ln -s ~/Library/Application\ Support/rancher-desktop ~/.rancher-desktop
```

**Comment by cmoulliard** [comment]
Many thanks for the trick. That should be if this is documented under a section "How to ssh the Rancher VM" -->
```
ln -s ~/Library/Application\ Support/rancher-desktop ~/.rancher-desktop
LIMA_HOME=~/.rancher-desktop/lima limactl show-ssh 0
LIMA_HOME=~/.rancher-desktop/lima limactl shell 0
```
