### ISSUE TITLE
Switch to arm64/aarch64 electron on macOS M1

### ISSUE THREAD

**Issue by brodock** [rancher-sandbox/rancher-desktop#1416]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

?

### What operating system are you using?

macOS

### Operating System / Build Version

macos Monterey 12.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

When opening rancher-desktop it still requires to install Rosetta 2

### Steps to Reproduce

1. Download rancher desktop from: https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.0.0/Rancher.Desktop-1.0.0.aarch64.dmg
1. Copy the app to the Applications folder
1. Double click to run the app without having Rosetta 2 installed

### Result

You get the Rosetta 2 installation dialog

### Expected Behavior

Should work without requiring Rosetta 2

### Additional Information

Related to https://github.com/rancher-sandbox/rancher-desktop/issues/16

**Comment by thomasdpage** [comment]
Same issue experienced here.

**Comment by gaba-mlindner** [comment]
Looks like the `1.0.0.aarch64` build actually contains a mix of `x86_64` and `arm64` binaries ..

<img width="1019" alt="rancher-desktop-binaries-20220202" src="https://user-images.githubusercontent.com/61541565/152121758-4f54fd9a-c84b-4df3-a9b8-76a30fd9b40d.png">

**Comment by mook-as** [comment]
Correct; currently, the qemu process is native, but the UI (electron) is running under Rosetta.  This should not be an issue in the general case (the workloads are running natively), though of course we plan to fix that later.

Additionally, we're running various command line tools (kubectl, etc.) under Rosetta, since aarch64 binaries are not available for older versions.

Thought we had an issue for this already, but I couldn't spot it in a quick search, so I'm just going to use this one.

**Comment by fulldecent** [comment]
Here is the latest hit list as of 1.8.1:

```
find . -perm +111 -type f -exec file {} + | egrep 'x86'   
./MacOS/Rancher Desktop:                                                                               Mach-O 64-bit executable x86_64
./Resources/resources/darwin/bin/kuberlr:                                                              Mach-O 64-bit executable x86_64
./Resources/resources/darwin/bin/rdctl:                                                                Mach-O 64-bit executable x86_64
./Resources/resources/darwin/bin/docker-credential-none:                                               Mach-O 64-bit executable x86_64
./Resources/app.asar.unpacked/node_modules/ffi-napi/build/Release/ffi_bindings.node:                   Mach-O 64-bit bundle x86_64
./Resources/app.asar.unpacked/node_modules/ffi-napi/build/node_gyp_bins/python3:                       Mach-O 64-bit executable x86_64
./Resources/app.asar.unpacked/node_modules/ffi-napi/prebuilds/darwin-x64/node.napi.uv1.node:           Mach-O 64-bit bundle x86_64
./Resources/app.asar.unpacked/node_modules/clipboardy/fallbacks/linux/xsel:                            ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=9aa143c8c26a99d2be429b5d1495b108e4824306, with debug_info, not stripped
./Frameworks/Rancher Desktop Helper (Plugin).app/Contents/MacOS/Rancher Desktop Helper (Plugin):       Mach-O 64-bit executable x86_64
./Frameworks/Electron Framework.framework/Versions/A/Electron Framework:                               Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib:                           Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Electron Framework.framework/Versions/A/Libraries/libvk_swiftshader.dylib:                Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib:                        Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib:                        Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler:                  Mach-O 64-bit executable x86_64
./Frameworks/ReactiveObjC.framework/Versions/A/ReactiveObjC:                                           Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt:                                           Mach-O 64-bit executable x86_64
./Frameworks/Squirrel.framework/Versions/A/Squirrel:                                                   Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Rancher Desktop Helper.app/Contents/MacOS/Rancher Desktop Helper:                         Mach-O 64-bit executable x86_64
./Frameworks/Mantle.framework/Versions/A/Mantle:                                                       Mach-O 64-bit dynamically linked shared library x86_64
./Frameworks/Rancher Desktop Helper (GPU).app/Contents/MacOS/Rancher Desktop Helper (GPU):             Mach-O 64-bit executable x86_64
./Frameworks/Rancher Desktop Helper (Renderer).app/Contents/MacOS/Rancher Desktop Helper (Renderer):   Mach-O 64-bit executable x86_64
```

**Comment by Stargator** [comment]
I have a MacOS 13.3.1 MacBook Pro M2 laptop and I'm seeing this issue. Though the Rosetta prompt is not appearing, instead I Rancher Desktop is just displaying an error about Rancher Desktop not being compatible with the architecture.

I had to manually install Rosetta with this `softwareupdate --install-rosetta`.

I intentionally downloaded the aarch64 build, but it's listed as `Application (Intel)` when inspecting the Get Info display.

**Comment by da4ftso** [comment]
As of version 1.9.0, the aarch64 download still delivers an `Intel` version.

```
~ % file /Volumes/Rancher\ Desktop\ 1.9.0/Rancher\ Desktop.app/Contents/MacOS/Rancher\ Desktop 
/Volumes/Rancher Desktop 1.9.0/Rancher Desktop.app/Contents/MacOS/Rancher Desktop: Mach-O 64-bit executable x86_64
```

**Comment by gustaff-weldon** [comment]
Is there any progress on that, I purposefully avoid installing Rosetta and running any emulation to keep my apps fast and my battery long lasting

**Comment by da4ftso** [comment]
As of version 1.10, the aarch64 download still delivers an `Intel` version.

```
$ file /Volumes/Rancher\ Desktop\ 1.10.0/Rancher\ Desktop.app/Contents/MacOS/Rancher\ Desktop 
/Volumes/Rancher Desktop 1.10.0/Rancher Desktop.app/Contents/MacOS/Rancher Desktop: Mach-O 64-bit executable x86_64
```

**Comment by jandubois** [comment]
@douglas has volunteered to work on this in https://github.com/rancher-sandbox/rancher-desktop/pull/2387#issuecomment-1789691567

**Comment by jandubois** [comment]
Hi @douglas, you said [3 weeks ago](https://github.com/rancher-sandbox/rancher-desktop/pull/2387#issuecomment-1789691567) that you were planning to look into this.

Did you have a chance to familiarize yourself with the code, and the required changes? Do you need help with anything? Or did life interfere and you won't have time to work on this?

**Comment by douglas** [comment]
Hello @jandubois! I got super busy the last weeks due to changing jobs but I'll try to work on these changes this week.

**Comment by jandubois** [comment]
Yes, there is nothing left to do in this issue. The `kuberlr` problem is tracked in #980.
