### ISSUE TITLE
'localhost' does not work

### ISSUE THREAD

**Issue by wiruzman** [rancher-sandbox/rancher-desktop#1420]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.21.9

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 19044.1466

### What CPU architecture are you using?

x64

### Actual Behavior

I want to connect localhost in i.e., Azure Data Studio/Sql Server Management Studio, but I get an error.

### Steps to Reproduce

1. Install Rancher Desktop
2. Run `docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest`
3. Install Azure Data Studio/Sql Server Management Studio
4. Open 3. and connect using `localhost` and credentials from 2.

### Result

Timeout

### Expected Behavior

Database will connect fast.

### Additional Information

I did the same with Docker Desktop I get following listening ports,
![image](https://user-images.githubusercontent.com/7511734/151852563-51611a24-646a-4f0c-87c1-ee7ba2de2be0.png)
With Rancher Desktop I get following listening ports,
![image](https://user-images.githubusercontent.com/7511734/151852612-a428c8d1-7629-4492-9acf-d3c6e6e15c6f.png)
I believe port mapping is not done properly. You can argue that spinning up a simple nginxdemos container do work in the browser. Every browser based lookup works but not outside a browser.

Workaround: Disabling IPv6 on all net adapters works, but it takes some time to connect as it was doing a round trip of lookups and falls back on 127.0.0.1. If I use 127.0.0.1 directly it connects very fast.

**Comment by cpstevens** [comment]
I am also seeing a similar issue when trying to run a Microsoft Orleans Silo Project against a dockerized local AWS cluster running DynamoDB. If I try and connect to the cluster using `localhost` as the host it gives me the below error, but when I switch the settings to use `127.0.0.1` as the host it works almost immediately.

Error
`[16:50:43 ERR] Failed to refresh membership table, will retry shortly: System.IO.IOException: The response ended prematurely.`
   
For context, I am running on Rancher Desktop v1.0.0, not using Kubernetes, and a Mac user using macOS 11.6

**Comment by wiruzman** [comment]
Kubernetes is not used in my case as well as the problem is more on the port forwarded docker containers outside kubernetes.

**Comment by megakid** [comment]
Also seeing this with a vanilla nginx pod:

`docker run -it --rm -p 8085:80 nginx`

**Comment by falcorocks** [comment]
Same here on macos, version `1.0.0`.
Both with containerd and dockerd

**Comment by wertone-gh** [comment]
Any updates regarding fix for this?

**Comment by blueboxes** [comment]
> 1.0.0

Still an issue under 1.1.1

**Comment by wiruzman** [comment]
I created a dotnet project that can detect ports created by docker with RD in WSL and bind ANY ip. localhost will work after the bind.

https://github.com/wiruzman/wsl-port-forwarder

**Comment by wertone-gh** [comment]
Could make it part of Rancher Desktop?

**Comment by wiruzman** [comment]
Writing it in nodejs would do it I think. I did it in dotnet which is my main competence.

**Comment by Nino-K** [comment]
This should no longer be an issue anymore, feel free to upgrade to 1.13.1 or even our 1.14 release that will be out shortly. I also recommend turning on the option for network tunnel. I'm going to close this issue, feel free to re-open it if needed.

**Comment by mitchabaza** [comment]
I'm still running into this issue on 1.13.1.  

- OS: Windows 10 Enterprise 22H2
- Kubernetes: 1.29.4
