### ISSUE TITLE
nerdctl login fails with Azure Container Registry

### ISSUE THREAD

**Issue by Fmstrat** [rancher-sandbox/rancher-desktop#1421]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.3

### What operating system are you using?

macOS

### Operating System / Build Version

12.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

Can't use Azure Container Registry with Rancher Desktop:
```
$ nerdctl login -u <user> <registry>.azurecr.io
Enter Password: 
ERRO[0001] failed to call tryLoginWithRegHost            error="failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 400 Bad Request" i=0
FATA[0001] failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 400 Bad Request 
```
This is related to: https://github.com/containerd/nerdctl/issues/737

### Steps to Reproduce

See above command.

### Result

See above error

### Expected Behavior

A successful login.

**Comment by AkihiroSuda** [comment]
Should have been already fixed in the current `master` branch of nerdctl. I'll release v0.16.1 today.

**Comment by murphy85** [comment]
I got it working with Rancher Desktop 0.7 and 1.0, if I'm using dockerd instead of containerd. Then there will be a docker daemon and you can use azure cli to login.

**Comment by Fmstrat** [comment]
@AkihiroSuda Is there a binary release for M1 macs?

**Comment by Fmstrat** [comment]
My workaround:
```
# Download: https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-amd64.tar.gz
tar xvfz nerdctl-0.16.1-linux-amd64.tar.gz
alias limactl="LIMA_HOME='$HOME/Library/Application Support/rancher-desktop/lima' '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl' shell 0"
limactl
sudo cp nerdctl /usr/local/bin/nerdctl
```
Now Rancher Desktop is using the new version of `nerdctl`.

**Comment by jandubois** [comment]
We will have a new RD 1.0.1 release later today, or early tomorrow, which will include lima 0.8.2 and nerdctl 0.16.1.
