### ISSUE TITLE
Update nerdctl-stub for 0.16.1

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1430]
I don't think there are any parameter changes, so this should be a no-op, but it feels better to recreate the stub whenever we bump nerdctl itself.

**Comment by dschunack** [comment]
Hi,

The new nerdctl fixed a BUG and It's needed to update it asap to solve login issues on registries.

https://github.com/containerd/nerdctl/issues/750

**Comment by mook-as** [comment]
There's nothing to do here — running `npm run generate:nerdctl-stub` on the branch for #1429 makes no changes.  That means we can't make a PR here (with no commits).

(Note that this is bumping the _stub_, and not nerdctl itself; that's handled in #1429.  That's where the nerdctl bug fix is being applied.)
