### ISSUE TITLE
Do not override the active Kubernetes context on startup (or make it configurable)

### ISSUE THREAD

**Issue by alxndr42** [rancher-sandbox/rancher-desktop#1438]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Rancher Desktop overrides the active Kubernetes context on startup, which can cause problems if you're already working on a Kubernetes cluster at the same time.

### Proposed Solution

Rancher Desktop should not override the active Kubernetes context on startup, or should offer a configuration option to turn this behaviour off.

**Comment by Gerrit-K** [comment]
Duplicate of #622 ?

**Comment by alxndr42** [comment]
Yes, thank you!
