### ISSUE TITLE
sudo: unable to resolve host lima-rancher-desktop: Name or service not known

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1439]
https://github.com/rancher-sandbox/rancher-desktop/blob/1c4c40c3610ce0f448057e4d16330448ae33b967/src/assets/lima-config.yaml#L41-L46

`hostname` sets the `hostname`, but because it isn't added to `/etc/hosts`, programs, such as `sudo` will scream.

**Comment by jandubois** [comment]
> `hostname` sets the `hostname`, but because it isn't added to `/etc/hosts`, programs, such as `sudo` will scream.

Can you provide a situation where `sudo` fails because of this; I haven't observed this myself, so I'm curious how to repro.

**Comment by jsoref** [comment]
Using [nectos/act](https://github.com/nektos/act) with my check spelling action with a certain base image.
I suspect the base image is the important part:

`~/.actrc`:
```
 -P ubuntu-latest=catthehacker/ubuntu:act-latest
 -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
 -P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:full-18.04
 ```

**Comment by jsoref** [comment]
Here's a simpler test case, git init a directory and add a single file with this path (creating the necessary intermediate directories):
`.github/workflows/sudo.yml`:
```
name: test
on:
  push:

jobs:
  test:
    name: sudo
    runs-on: ubuntu-latest
    steps:
    - name: set up
      run: |
        set -x
        hostname
        cat /etc/hosts
        whoami
        id
        sudo true
```

Then run `act -P ubuntu-latest=catthehacker/ubuntu:act-latest`, and you should get output very similar to this (the M1 warning is only Applicable if you're using an M1 -- I can't use my x86-64 computer because it's patched, and I like it that way...):
```
WARN  ⚠ You are using Apple M1 chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
[test/sudo] 🚀  Start image=catthehacker/ubuntu:act-latest
[test/sudo]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[test/sudo]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[test/sudo] ⭐  Run set up
[test/sudo]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/jsoref/code/spelling-org/meh/workflow/0] user=
| + hostname
| lima-rancher-desktop
| + cat /etc/hosts
| 127.0.0.1	localhost localhost.localdomain
| ::1		localhost localhost.localdomain
| 192.168.5.2	host.lima.internal host.rancher-desktop.internal host.docker.internal
| + whoami
| root
| + id
| uid=0(root) gid=0(root) groups=0(root)
| + sudo true
| sudo: unable to resolve host lima-rancher-desktop: Name or service not known
[test/sudo]   ✅  Success - set up
```

Note: this isn't _fatal_ it's just annoying.

**Comment by jandubois** [comment]
I don't understand why `lima-rancher-desktop` gets the IP address of the host gateway!

Since the only use for it is for the host to talk to itself, shouldn't it have been set to `127.0.0.1` instead?

Also, shouldn't there be a corresponding change for the Windows version? We should try to keep fixing issues for the various platforms at the same time, whenever possible. It will be impossible to keep track of the differences otherwise.

**Comment by jandubois** [comment]
> Since the only use for it is for the host to talk to itself, shouldn't it have been set to `127.0.0.1` instead?

The current definitions probably works most of the time because guest ports are forwarded to the host. But e.g. port 22 isn't, so using `scp` or `rsync` with the `lima-rancher-desktop` name would now talk to the host instead of the VM.

Since this is already merged, please create a followup PR to fix this!

**Comment by jandubois** [comment]
Taking a look at WSL, it uses `127.0.1.1` for the local hostname:

```
127.0.0.1       localhost
127.0.1.1       DESKTOP-12345.localdomain     DESKTOP-12345
```

Debian is doing the same thing: https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

Maybe we should follow. And I think it should go into Lima and not Rancher Desktop, but we can implement it here for now, and drop it once Lima has support for it.

**Comment by gaktive** [comment]
We need a follow-up PR to correct the forward so that it points to `localhost`
