### ISSUE TITLE
Please use a different certificate format

### ISSUE THREAD

**Issue by metacosm** [rancher-sandbox/rancher-desktop#1456]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It seems that the current certificate that gets added to `.kube/config` uses the elliptical encryption format which is not supported by default when working with Java application. Using a different, supported by default on Java, format would lower the barrier of entry for Java developers and improve the user experience.

### Proposed Solution

Use a different format, one of JKS, PCKS12 or PEM (PCKS1), which are supported by default on the community versions of the Java VM.

**Comment by mook-as** [comment]
I believe we're just using [k3s](https://github.com/k3s-io/k3s) defaults here (copying the generated `/etc/rancher/k3s/k3s.yaml`); that would need to be able to generate the kind of certs you want first.

**Comment by brandond** [comment]
The K3s-generated kubeconfig uses the standard schema supported by all the Kubernetes clients, including the Kubernetes client at https://github.com/kubernetes-client/java.

As per upstream, the kubeconfig can either contain paths to files on disk, or inline base64-encoded PEM data. The inline formats are more self-contained so that's the format generally preferred for distribution.

```console
root@ubuntu01:~# awk '/client-certificate-data/ {print $2}' /etc/rancher/k3s/k3s.yaml  | base64 -d
-----BEGIN CERTIFICATE-----
...
```

I suspect that the actual issue you may be running into is related to the crypto libraries on your node. We use ECDSA keys instead of RSA; if you're on an older OS or Java version, you may be lacking support for these key types. I have personally run into this issue when trying to use curl on older versions of CentOS/RHEL where the system version of OpenSSL does not support ECDSA.

```console
root@ubuntu01:~# awk '/client-certificate-data/ {print $2}' /etc/rancher/k3s/k3s.yaml  | base64 -d | openssl x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 7276083908080311461 (0x64f9d7c399101ca5)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = k3s-client-ca@1643836920
        Validity
            Not Before: Feb  2 21:22:00 2022 GMT
            Not After : Feb  2 21:22:00 2023 GMT
        Subject: O = system:masters, CN = system:admin
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:9d:af:08:a7:eb:00:72:32:96:a6:18:a3:75:04:
                    86:62:bc:47:66:2f:4d:d4:c9:7c:64:71:99:2a:06:
                    ba:6b:86:70:a4:91:f2:2a:9a:c2:1e:25:73:2a:10:
                    9c:dd:32:89:8f:1b:5a:9a:80:c1:04:22:13:7f:7d:
                    ed:22:26:e4:e8
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Authority Key Identifier:
                keyid:27:BD:C7:CD:B8:00:AE:7E:21:E0:8D:0E:8F:3F:6F:26:7D:21:C7:CD
```

**Comment by jandubois** [comment]
@brandond So is there a workaround to get an RSA key instead, or is the only option to update the client software?

**Comment by brandond** [comment]
No, we do not support creating RSA keys instead of ECDSA. At the moment, all of our automatically generated keys are ECDSA.

**Comment by jandubois** [comment]
Closing the issue as there doesn't seem to be a way to do this.

**Comment by brandond** [comment]
I hate to link to SO but it appears that EC keys have been supported since Java 7; Java 8 will let you load them from base64 as part of the standard library:
https://stackoverflow.com/questions/30445997/loading-raw-64-byte-long-ecdsa-public-key-in-java

**Comment by metacosm** [comment]
I know that you can process these keys in Java… the point of the issue, though, is that support is not available out of the box, i.e. you need your client to do some extra processing, which is fine, but a source of frustration for users because they don't get a nice out-of-the-box experience if their client doesn't do that extra step.

Thank you for your explanations and taking the time to investigate the issue, though! ☺️

**Comment by brandond** [comment]
The Kubernetes client for Java should process these out of the box, without any additional processing. Are you experiencing otherwise?

**Comment by metacosm** [comment]
I'm using the Fabric8 Kubernetes Client. Supporting the key is not complex: it's just a matter of adding a single dependency to the project (which, if I'm not mistaken, is specified by default by the official client). The Fabric8 client doesn't bundle the dependency to keep things lighter.

**Comment by brandond** [comment]
Yeah, it appears this is intentional on their part: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L160

**Comment by metacosm** [comment]
Yep!
