### ISSUE TITLE
`Bad Gateway` from `docker ps` in WSL

### ISSUE THREAD

**Issue by ikogan** [rancher-sandbox/rancher-desktop#1457]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

v1.20.15

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 1909

### What CPU architecture are you using?

x64

### Windows User Only

Nothing that I'm aware of.

### Actual Behavior

1. Open new WSL terminal in Ubuntu.
2. Run `docker ps`

```
user@WindowsVM:/mnt/c/Users/user$ docker ps
request returned Bad Gateway for API route and version http://%2Fvar%2F/docker.sock/v1.24/containers/json, check if the server supports the requested API version
user@WindowsVM:/mnt/c/Users/user$ ls -lah /var/run/docker.sock
srwxrwxr-x 1 root docker 0 Feb   2 08:38 /var/run/docker.sock
user@WindowsVM:/mnt/c/Users/user$ id user
uid=1000(user) gid=1000(user) groups=1000(user),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),108(lxd),999(docker)
user@WindowsVM:/mnt/c/Users/user$ curl -I --unix-socket /var/run/docker.sock http://info
HTTP/1.1 502 Bad Gateway
Date: Wed,  02 Feb 2022 14:09:05 GMT
```

### Steps to Reproduce

1. Install Rancher Desktop
2. Open new WSL terminal in Ubuntu.
3. Run `docker ps`

Note that previously I had incorrect permissions on the docker socket. This error occurs after fixing them.

### Result

```
request returned Bad Gateway for API route and version http://%2Fvar%2F/docker.sock/v1.24/containers/json, check if the server supports the requested API version
```

### Expected Behavior

When run from PowerShell:

```
PS C:\Users\user> docker ps
CONTAINER ID    IMAGE                     COMMAND        CREATED     STATUS     PORTS    NAMES
<Various containers>
```

### Additional Information

In the `wsl-helper.Ubuntu.log` file I see a a stream of `http: proxy error: dial unix /mnt/wsl/rancher-desktop/run/docker.sock: connect: no such file or directory` errors right after it begins listening.

In `docker.log` I see a that it does begin listening:

```
time="2022-02-02T13:38:26.432998000Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2022-02-02T13:38:27.728508900Z" level=info msg="Loading containers: done."
time="2022-02-02T13:38:30.071811500Z" level=info msg="Docker daemon" commit=847da184ad5048b27f5bdf9d53d070f731b43180 graphdriver(s)=overlay2 version=20.10.11
time="2022-02-02T13:38:30.116764000Z" level=info msg="Daemon has completed initialization"
time="2022-02-02T13:38:30.486725100Z" level=info msg="API listen on /mnt/wsl/rancher-desktop/run/docker.sock"
time="2022-02-02T13:38:30.487252200Z" level=info msg="API listen on /var/run/docker.sock"
```

**Comment by mook-as** [comment]
Could you check if `curl --unix-socket=/mnt/wsl/rancher-desktop/run/docker.sock http://host/v2/info` works as expected (from your Ubuntu distribution)? If not, does `/mnt/wsl/rancher-desktop/run/docker.sock` exist?

The stream of errors in `wsl-helper.Ubuntu.log` would seem to indicate that it's having issues there.  Do you have a `/etc/wsl.conf` in your Ubuntu distribution? What does it look like?

Thanks for the help!

**Comment by ikogan** [comment]
`http://host/v2/info` still returns bad gateway. There is no `/etc/wsl.conf` in my Ubuntu installation and `/mnt/wsl` doesn't exist. 

However, in the `rancher-desktop` WSL instance, everything seems to work. The mount exists, and while `http://host/v2/info` claims that `v2` is too new, `host/info` does work fine.

However, I had a thought. This Ubuntu installation is _very old_. It was still on 18.04. I deleted it, deleted the store app, redownloaded it, re-created it, and re-checked the "Ubuntu" box in the "WSL Integration" section in Rancher Desktop and it now works.

A possibly important note that in the middle of all of this the 1.0.1 version was released and I updated before final testing. If this is good enough, feel free to close but I don't know if this _should_ have been working on the old install.

**Comment by mook-as** [comment]
I do not believe anything in 1.0.1 would have fixed this.

If your Ubuntu installation is very old, then it might be using WSL v1; we do not support integration with those (it doesn't run a real Linux kernel).  However, we _should_ also not attempt to integrate it at all (so you shouldn't have had the logs).

Unfortunately, at this point we're uncertain what's going on, and there probably isn't much we can do without further troubleshooting (which we can no longer do).

Closing this, but please post any information you think may be useful.  Thanks!

**Comment by ikogan** [comment]
Thanks for the quick responses! Just in case anyone comes here from Google, it was indeed WSL 2, I made sure of that. I'm not sure what was going on with it but who knows what I did in the past...
