### ISSUE TITLE
Proactively detect and suggest tool conflict resolution

### ISSUE THREAD

**Issue by krumware** [rancher-sandbox/rancher-desktop#1467]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There are a number of tools which may already be installed on the user's machine, which will be replaced or updated by RD. Those include Helm, kubectl + others.  Currently, a user can uninstall Docker Desktop and install Rancher Desktop, and run into conflicts post-installation. (admittedly made more difficult in Windows+WSL)

### Proposed Solution

Detect/flag these at installation time to suggest actions to take.
Or at minimum provide a pre-installation "checklist" for users for pre-installation preparation or cleanup.

**Comment by ericpromislow** [comment]
You mentioned Windows/WSL. Currently on macOS and linux the UI actually tells you exactly which tools are shadowed in the path, and where. But it's true on the WSL side there's no such information. So is this Windows only? Or do you want this information before you actually install Rancher Desktop?

**Comment by ericpromislow** [comment]
Hi, we're discussing this at https://github.com/rancher-sandbox/rancher-desktop/discussions/1512 . I'll close this issue now, and when we're ready to implement something we'll create a new issue. But please feel free to jump in.
