### ISSUE TITLE
Could not read message is misleading

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1471]
The text says `could not read`:
https://github.com/rancher-sandbox/rancher-desktop/blob/6c34341ffe5fb56b59c940c7db639ad99e08116d/src/k8s-engine/lima.ts#L1391

But the error is **could not _list_**:
https://github.com/rancher-sandbox/rancher-desktop/blob/6c34341ffe5fb56b59c940c7db639ad99e08116d/src/k8s-engine/lima.ts#L1383-L1384

The user who will run this command doesn't have permission to read the file (it's owned by `root` and has permissions `0600`).

(Spotted while debugging a problem relating to `~/.kube` configuration on the host that resulted in an error involving `kubectl` with this being one of the last outputs before the error. Using versions 1.0.0 and 1.0.1 on macOS Intel.)

**Comment by ericpromislow** [comment]
Normally this error message appears before `k3s.yaml` has been created. So you're asking for a more specific message, correct?

**Comment by jsoref** [comment]
Yes. I was planning to hang a PR off this ticket
