### ISSUE TITLE
Milestone link in app should include "closed=1"

### ISSUE THREAD

**Issue by ghost** [rancher-sandbox/rancher-desktop#1479]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.1

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

Link out from "Update Available" -> Changelog link goes to 'https://github.com/rancher-sandbox/rancher-desktop/milestone/15' which is *OK*

BUT 

that means there are no issues listed unless the user knows to click on "closed" in the web GUI.

Adding "closed=1" to the link out will show the list of closed issues and provide an immediate view of what was addressed for the milestone.

### Steps to Reproduce

Navigate to "Release Notes" [click on side arrow/which turns to down arrow]
Click on "v1.0.1 milestone" link in drop-down info box

<img width="938" alt="Screen Shot 2022-02-03 at 9 17 55 AM" src="https://user-images.githubusercontent.com/97919797/152360570-5b14ac99-197f-4896-b6d5-8fbfc7888c0b.png">

### Result

Empty list in GitHub Milestone web GUI

### Expected Behavior

Fully populated list of closed issues for the Milestone

### Additional Information

I know it's a nit. :smile:

**Comment by jandubois** [comment]
Thanks, fixed!

**Comment by gunamata** [comment]
As @jandubois noted above, this is fixed. The release notes uses the suggested `closed=1` flag.
