### ISSUE TITLE
Have a single location to store the Alpine ISO and WSL distro release versions

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1498]
Right now these version numbers need to be bumped in 2 places: the download scripts, and the k8s-engine modules. See e.g. https://github.com/rancher-sandbox/rancher-desktop/commit/140e2b25cc90207b26ed382192485f187f4988df

This is error-prone and can get out of sync; there should be a single location that records versions/commits/whatever to pin external dependencies.

**Comment by gaktive** [comment]
@adamkpickering close this once the work in https://github.com/rancher-sandbox/rancher-desktop/issues/2307 reaches this stage
