### ISSUE TITLE
Uninstall leaves data directory behind

### ISSUE THREAD

**Issue by giggio** [rancher-sandbox/rancher-desktop#1505]
### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows [Version 10.0.22000.469]

### What CPU architecture are you using?

x64

### Windows User Only

No.

### Actual Behavior

Uninstalling Rancher desktop leaves behind the `%localappdata%\rancher-desktop` and `%localappdata%\rancher-desktop-updater` directories.

### Steps to Reproduce

1. Install Rancher Desktop
2. Uninstall Rancher Desktop

### Result

These directories are still there after uninstall, with hundreds of megabytes on disk each.

### Expected Behavior

The directory is removed.

### Additional Information

I might want to keep the data, so you should ask. For problems during upgrade (or any other app problem) it would be a nuisance if an uninstall/reinstall deleted all my data.

**Comment by ericpromislow** [comment]
Same comments as for issue #1504

**Comment by ericpromislow** [comment]
We're going to revisit this along with #1504

**Comment by jandubois** [comment]
Should be handled by #1504 as well.
