### ISSUE TITLE
Time Synchronization issue between host machine and Rancher Desktop

### ISSUE THREAD

**Issue by todurnatesh** [rancher-sandbox/rancher-desktop#1517]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.1

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Big Sur 11.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

Reported time difference between host machine and Rancher Desktop is more than expected. Ideally the time Rancher desktop uses should be in sync with the host machine. It happens sometimes but not often (weekly thrice approx.).

Case info - 
Host machine time - 7:25 pm IST (India Standard Time) on 3 Feb 2022
IST is 5 hours and 30 minutes ahead of UTC (Coordinated Universal Time).
Rancher Desktop time as observed in log files - 22:58 on 2 Feb 2022.

The time difference here is enormous. The log file should have timestamps of around 13:55 UTC on 3 Feb 2022

### Steps to Reproduce

No specific steps to reproduce this issue. I have tried to keep Rancher Desktop running for 2-3 days and checked at regular time intervals but works most of the time.

### Result

<img width="646" alt="rancher-desktop-time-difference" src="https://user-images.githubusercontent.com/32215872/152668485-58954a33-b305-48d9-a429-549d2e151530.png">

Please observe the machine timestamp and the log file timestamp. Its way out of sync.

### Expected Behavior

The only visual time difference between host machine and rancher desktop must be that of the UTC time difference. It should be in sync.

### Additional Information

A restart of Rancher Desktop can be considered as an immediate workaround. It works right after RD restart.

It has been reported in other macOS machines :
- MacOS 11.4 Big Sur
- MacOS 10.5 Catalina

This was never an issue with Docker desktop.

This error was observed when trying to connect to AWS S3 (or local machine hosted serverless S3) from the container. The specific error thrown by sdk client - <b> RequestTimeTooSkewed</b>

**Comment by ericpromislow** [comment]
When Rancher Desktop starts up, are there discrepancies in the log files?

I'm wondering if the VM clock stops when the machine goes to sleep.

**Comment by jandubois** [comment]
This used to be a known issue, but should have been fixed by https://github.com/lima-vm/lima/pull/490.

But this was supposed to be fixed in RD 1.0.0: there is now a check every 10s, and if the time difference between guest and host is more than 2s, the guest time is set to the host time.

Can you please confirm that you are running 1.0.0 and not an earlier version?

**Comment by todurnatesh** [comment]
No errors reported in RD 1.0.0 and above. Closing this.

The confusion arose due to the auto-update feature in RD. By the time I had received the logs, the version was updated and thus I mistakenly stated here that the error was in RD 1.0.0. Whereas the issue should have been for 0.7.*

**Comment by jandubois** [comment]
Thank you for confirming this!
