### ISSUE TITLE
After reinstalling Rancher Desktop, it's not possible to re-setup Rancher Desktop -> choose another container engine (eg. from containerd to docker/moby).

### ISSUE THREAD

**Issue by BartekZm** [rancher-sandbox/rancher-desktop#1525]
### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

11.6 BigSur

### What CPU architecture are you using?

x64

### Actual Behavior

After reinstalling Rancher Desktop, it's not possible to re-setup Rancher Desktop -> choose another container engine (eg. from containerd to docker/moby).

### Steps to Reproduce

Installed rancher desktop with containerd.

Uninstall -> move the app to trash and then empty the trash
https://docs.rancherdesktop.io/installation#uninstalling-rancher-desktop-on-macos

Reinstall.

### Result

Then, Rancher is re-installed with the engine that was chosen previously.

### Expected Behavior

A user should be able to re-setup rancher after uninstall, including the image engine.

### Additional Information

Unfortunately, I need to use docker/moby for one project which automation was not rewritten to containerd yet.

**Comment by BartekZm** [comment]
Ok I admit I'm a little dumb I didn't check it at first - factory reset did the job I wanted to perform.
Allow me to rephrase it a bit - should RDesktop reinstall trigger Factory Reset (for better UX ;) )?

**Comment by jandubois** [comment]
Note that you don't need to reinstall/factory reset RD to change container runtimes. There is a radio button to select it on the "Kubernetes Settings" page. It will still restart the VM, and images will not carry over between the runtimes, but otherwise you can switch back and forth without reinstalling.
