### ISSUE TITLE
Spike: Code Metrics

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1530]
### Objective
* Provide code coverage data to the devs
* Measure the overall code coverage on the project
* Find out coverage gaps and take actions

### Tools
* [Coveralls](https://coveralls.io/)
* [Sonarqube](https://docs.sonarqube.org/latest/)

### Nice to have
* GHA integration
* Pull request detailed summary
* Report dashboard

**Comment by jandubois** [comment]
There are currently no plans to introduce code coverage metrics.
