### ISSUE TITLE
Split Waiting for human from `Installing networking requirements`

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1532]
Steps:
1. Start Rancher Desktop
2. Go home for the weekend
3. Come back and see:

![image](https://user-images.githubusercontent.com/2119212/152858478-1dd77901-6316-4f4d-a374-32fe546b7ade.png)

https://github.com/rancher-sandbox/rancher-desktop/blob/2800792b0619912396d585dbfbb2bc32a18b6904/src/k8s-engine/lima.ts#L1253-L1258

4. There was a dialog saying it would ask me for credentials, and I dismissed it
5. Time passed and the counter ticked, and no credentials dialog arrived, and I asked about this on Slack
6. As I was filing this ticket, the permission dialog finally arrived.

Expected results:
If the phase in question is `Waiting for user permission`, then it should say so. It didn't take 3 2/3 days to not install networking. It took that time _Waiting for the human to return to the chair to enter credentials_.

**Comment by evertonlperes** [comment]
Tagging the main feature request to deal with all statuses verification: https://github.com/rancher-sandbox/rancher-desktop/issues/1217
