### ISSUE TITLE
Show Running Images on the UI (runtime dockerd)

### ISSUE THREAD

**Issue by 1bberto** [rancher-sandbox/rancher-desktop#1539]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I wanted to see all the current images running, the same as exists today for docker desktop: a list of current images running and also if there is a stack of images as well 

### Proposed Solution

create a menu option to see the current running images

**Comment by evertonlperes** [comment]
Thanks for filing the feature request.
Closing this one due duplicity, issue: https://github.com/rancher-sandbox/rancher-desktop/issues/1185
Feel free to add more info on #1185
