### ISSUE TITLE
Consider wrapping the Windows EXEs in an MSI

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1547]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

See https://www.exemsi.com/ and test it out.

Some locked down systems will only install from MSI files.

### Proposed Solution

Wrap the EXE in an MSI.

**Comment by jandubois** [comment]
The MSI should also be able to configure the initial setup of RD, like container runtime and k3s version. Not sure where to draw the line, but probably everything that is configured by the first-run dialog, so this that dialog will not show if things are configured via the installer.

This should be implemented by creating the `settings.json` file, so it can be done without starting RD.

As long as WSL2 and the required kernel are already installed, it should be possible to do an automated "quiet" install of the MSI without any user interaction.

**Comment by mook-as** [comment]
That depends on which user the MSI is being installed as; settings are per-user, so if it's an unassociated adminstrator running the MSI installer, the first-run dialog would still appear.  We might need to look at if there's a way to de-elevate (in effect, the difference between `getuid` and `geteuid`).

**Comment by mook-as** [comment]
This appears to be obsolete — our installers are currently msi-only.
