### ISSUE TITLE
[E2E] Rancher Deployment

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1548]
Implement automated test Rancher Deployment

Test case:
- Deploy Rancher Dashboard using helm
- Deploy Rancher Dashboard using dockerd and containerd
- Verify if the deployment went through without errors/warnings

Goal: Validate the complete installation and hit the Rancher Dashboard application, after the deployment.

This test case will require some changes after the Rancher Dashboard integration on RD.
Ref: https://github.com/rancher-sandbox/rancher-desktop/issues/1192

**Comment by jandubois** [comment]
Rancher Manager installation, both in a container, and on top of k8s is being tested by BATS
