### ISSUE TITLE
Spike: Disable k3s

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1559]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Some people don't want the overhead of running kubernetes

### Proposed Solution

Don't launch it.

### Additional Information

Determine the surface area of this change in a one-day spike.

**Comment by jandubois** [comment]
I just tried to run just plain `containerd` without `k3s`, and this was all that is required (on macOS with Lima, but should be similar on Linux/Windows):

```console
$ rdlima
lima-rancher-desktop:~$ echo "export CONTAINERD_ADDRESS=/var/run/containerd/containerd.sock" > ~/.profile
lima-rancher-desktop:~$ sudo rc-service k3s stop
 * Stopping k3s ...
lima-rancher-desktop:~$ sudo rc-service containerd start
 * /var/log/containerd.log: creating file
 * Starting Container Daemon ...
lima-rancher-desktop:~$ ^D
$ nerdctl pull nginx
docker.io/library/nginx:latest:                                                   resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:bb129a712c2431ecce4af8dde831e980373b26368233ef0f3b2bae9e9ec515ee: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:c316d5a335a5cf324b0dc83b3da82d7608724769f6454f6d9a621f3ec2534a5a:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b559bad762bec166fd028483dd2a03f086d363ee827d8c98b7268112c508665a:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:78091884b7bea0fa918527207924e9993bcc21bf7f1c9687da40042ceca31ac9:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:5eb5b503b37671af16371272f9c5313a3e82f1d0756e14506704489ad9900803:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:091c283c6a66ad0edd2ab84cb10edacc00a1a7bc5277f5365c0d5c5457a75aff:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:1ae07ab881bd848493ad54c2ba32017f94d1d8dbfd0ba41b618f17e80f834a0f:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:55de5851019b8f65ed6e28120c6300e35e556689d021e4b3411c7f4e90a9704b:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 5.1 s                                                                    total:  54.1 M (10.6 MiB/s)
$ nerdctl images
REPOSITORY    TAG       IMAGE ID        CREATED          PLATFORM       SIZE
nginx         latest    2834dc507516    3 seconds ago    linux/amd64    149.1 MiB
```

So for `containerd` start the `containerd` service instead of `k3s` and change the socket address.

For `dockerd` it just means don't start `k3s`. Everything else is already there.

**Comment by ericpromislow** [comment]
Seems doable in a week:

Tasks:
- [x] add a setting and checkbox for `settings.kubernetes.disabled`
- [x] don't start up k3s when `disabled`
- [x] disable Port Forwarding of k8s services when `disabled`
- [  ] avoid loading k8s versions in non-k8s mode
- [x] support dockerd in non-k8s mode
- [ ] support containerd in non-k8s mode
- [ ] verify image operations work for dockerd
- [ ] verify image operations work for containerd

**Comment by ericpromislow** [comment]
Closing the spike -- determined what we need to do, and that everything is straightforward
