### ISSUE TITLE
Allow users to decide whether to run k3s or not

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1562]
Seems doable in a week:

Tasks:
- [x] add a setting and checkbox for `settings.kubernetes.enabled` (default: on)
- [x] add `enabled` setting to startup screen (default: on)
- [x] lima: don't start up k3s when `disabled`
- [x] windows: don't start up k3s when `disabled`
- [x] disable Port Forwarding of k8s services when `disabled`
- [x] support dockerd in non-k8s mode
- [x] support containerd in non-k8s mode
- [x] verify image operations work for lima (lima)
- [x] verify image operations work for lima (WSL)
- [x] verify image operations work for containerd (lima)
- [x] verify image operations work for containerd (WSL)
- [x] verify rancher images show up for containerd going from k8s-on to -off (lima)
- [x] verify rancher images show up for containerd going from k8s-on to -off  (WSL)
- [x] verify rancher images show up for docker going from k8s-on to -off (lima)
- [x] verify rancher images show up for docker going from k8s-on to -off  (WSL)
- [x] Moved to #1587
- [x] Moved to #1589

_Originally posted by @ericpromislow in https://github.com/rancher-sandbox/rancher-desktop/issues/1559#issuecomment-1034315595_

Related issues, to appear with 'Fixes ...' in the PR:
#985 
#1166

**Comment by ericpromislow** [comment]
From Jan:
I just tried to run plain `containerd` without `k3s`, and this was all that is required (on macOS with Lima, but should be similar on Linux/Windows):

```console
$ rdlima
lima-rancher-desktop:~$ echo "export CONTAINERD_ADDRESS=/var/run/containerd/containerd.sock" > ~/.profile
lima-rancher-desktop:~$ sudo rc-service k3s stop
 * Stopping k3s ...
lima-rancher-desktop:~$ sudo rc-service containerd start
 * /var/log/containerd.log: creating file
 * Starting Container Daemon ...
lima-rancher-desktop:~$ ^D
$ nerdctl pull nginx
docker.io/library/nginx:latest:                                                   resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:bb129a712c2431ecce4af8dde831e980373b26368233ef0f3b2bae9e9ec515ee: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:c316d5a335a5cf324b0dc83b3da82d7608724769f6454f6d9a621f3ec2534a5a:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b559bad762bec166fd028483dd2a03f086d363ee827d8c98b7268112c508665a:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:78091884b7bea0fa918527207924e9993bcc21bf7f1c9687da40042ceca31ac9:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:5eb5b503b37671af16371272f9c5313a3e82f1d0756e14506704489ad9900803:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:091c283c6a66ad0edd2ab84cb10edacc00a1a7bc5277f5365c0d5c5457a75aff:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:1ae07ab881bd848493ad54c2ba32017f94d1d8dbfd0ba41b618f17e80f834a0f:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:55de5851019b8f65ed6e28120c6300e35e556689d021e4b3411c7f4e90a9704b:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 5.1 s                                                                    total:  54.1 M (10.6 MiB/s)
$ nerdctl images
REPOSITORY    TAG       IMAGE ID        CREATED          PLATFORM       SIZE
nginx         latest    2834dc507516    3 seconds ago    linux/amd64    149.1 MiB
```

So for `containerd` start the `containerd` service instead of `k3s` and change the socket address.

Similar for `dockerd`

**Comment by ericpromislow** [comment]
Current work in branch `1562-disable-k3s`

**Comment by flyinprogrammer** [comment]
This is likely out of scope, but it might be nice to have a chunk of helper functions that we offer folks.

Hopefully something less horrendous than this:


```shell
func rancher_k3s_status() {
  LIMA_HOME="${HOME}/Library/Application Support/rancher-desktop/lima" limactl shell 0 sudo /etc/init.d/k3s status
}

func rancher_k3s_start() {
  LIMA_HOME="${HOME}/Library/Application Support/rancher-desktop/lima" limactl shell 0 sudo /etc/init.d/k3s start
}

func rancher_k3s_stop() {
  LIMA_HOME="${HOME}/Library/Application Support/rancher-desktop/lima" limactl shell 0 sudo /etc/init.d/k3s stop
  docker rm -f $(docker ps -aq)
}

# I also do custom lima stuff with a lima home that doesn't reside here, so it's nice to make this opt-in.
func rancher_lima() {
  export LIMA_HOME="${HOME}/Library/Application Support/rancher-desktop/lima"
}

# It's nice to grab a shell into the rancher instance
func rancher_shell() {
  LIMA_HOME="${HOME}/Library/Application Support/rancher-desktop/lima" limactl shell 0 /bin/sh
}

# One-shot commands are fun, but the lack of autocomplete is 😢 
func rancher_cmd() {
  LIMA_HOME="${HOME}/Library/Application Support/rancher-desktop/lima" limactl shell 0 ${@}
}
```

Idk if this helps at all 🤷  just 2 cents of someone who's using this daily to get work done.

Here's a picture of a baby kookaburra for your troubles:

![kookaburra](https://user-images.githubusercontent.com/1844847/153620575-65fdf79f-5706-42aa-a591-49d3c799b8ae.jpeg)

**Comment by sumanthkumarc** [comment]
+1 for feature. Adding this feature will make rancher desktop, best alternative to docker desktop given the terms change in the docker desktop.
