### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by sanyarnd** [rancher-sandbox/rancher-desktop#1569]
### Actual Behavior

Hi, Rancher Desktop is unable to start. After 5 minutes it says `Error: unable to verify the first certificate`.

Querying kubectl during this period of time outputs `Unable to connect to the server: x509: certificate signed by unknown authority`.

### Steps to Reproduce

Just installed the software, no additional steps

### Result

Program doesn't start

### Expected Behavior

Working software :)

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Windows User Only

VPN, Cisco AnyConnect + company root certificates

**Comment by Nino-K** [comment]
Please upgrade to 1.9 release and enable our new https://github.com/rancher-sandbox/rancher-desktop/issues/3810network which should address this issue. You can simply enable the new network using:
```
rdctl set --experimental.virtual-machine.networking-tunnel=true
```
