### ISSUE TITLE
Images list not coming up

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1575]
### Actual Behavior

On app launch with dockerd (moby), I do not see any images in the `Images` screen. 

### Steps to Reproduce

Launch RD App
Switch to Images menu

### Result

The screen shows `Waiting for image manager to be ready` message.

Running `docker images` from command terminal shows..

```
C:\2022\rd_test>docker images
request returned Bad Gateway for API route and version http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/json, check if the server supports the requested API version
```

### Expected Behavior

Should display a list of images.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.21.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Windows User Only

N/A

**Comment by gunamata** [comment]
Adding logs..

[no-images-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/8050244/no-images-logs.zip)

**Comment by gunamata** [comment]
Another observation is that, with the `Enable Debug mode` selected, the `Factory reset` didn't work. After unchecking `Enable Debug mode` Factory reset worked, and docker commands worked too.

**Comment by gaktive** [comment]
@gunamata to retry this and file a new item if this happens again.
