### ISSUE TITLE
Rancher Desktop 1.0.1 setup not working

### ISSUE THREAD

**Issue by heroku-miraheze** [rancher-sandbox/rancher-desktop#1579]
### Actual Behavior

I restarted my computer, and does not nothing.

### Steps to Reproduce

Start setup, does not anything, restart my computer, and rerun setup and does not anything.

### Result

Not working setup.

### Expected Behavior

Not working setup.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

none

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

**Comment by evertonlperes** [comment]
@heroku-miraheze 
Could share some logs and images related to your issue?
You can check the logs, following this steps: https://docs.rancherdesktop.io/preferences#show-logs

The behaviour that you're describing cannot be duplicated on Windows 11.

**Comment by willkwan** [comment]
I'm having the same issue, same system set up, apart from "Which container runtime are you using?" which for me is "none".

**Comment by mook-as** [comment]
Hmm, when you say "Start setup, does not anything, restart my computer, and rerun setup and does not anything.", are you saying you can't see the setup window at all? It should have a verifying stage:
![image](https://user-images.githubusercontent.com/3977982/154140176-1d6f7a64-5825-4f98-acfe-17d1f5068655.png)
Follow by the installer welcome screen, which could take some time to show up:
![image](https://user-images.githubusercontent.com/3977982/154140319-1df0c47f-04e8-4b23-bc72-ca88952ad348.png)
(This is all just standard NSIS installer, which is pretty wide spread.)

**Comment by SamuelColacchia** [comment]
I experienced a similar issue.

The window for "Please wait while Setup is loading" was not displaying, I noticed that the amount of ram the process was using was changing so i watied a few minutes and then the "Rancher Desktop Setup" window appeared.

Maybe this is a issue with newer versions of windows?

### Operating System / Build Version / OS build
Windows 10 / 21H1 / 19044.1526

**Comment by tobiasoort** [comment]
Same on my Win11 box. Only after impatiently starting the installer EXE a few times, the installer finally popped up.

**Comment by gunamata** [comment]
This one looks like a problem due to the lack of a proper messaging between the time a user double clicks on the installer and the time the first installation setup screen appears. We have this issue https://github.com/rancher-sandbox/rancher-desktop/issues/2153 related to adding a splash screen.

Closing this issue for now. @tobiasoort , Please feel free to reopen if it's still a problem installing Rancher Desktop.
