### ISSUE TITLE
Add the variable DOCKER_HOST=npipe:////./pipe/docker_engine on windows installation.

### ISSUE THREAD

**Issue by alexgracianoarj** [rancher-sandbox/rancher-desktop#1580]
### Actual Behavior

Hi, firstly, thanks for Rancher Desktop development.

I installed RD on my windows and it worked fine but after reboot the docker cli would no longer connect to the docker host (#1575),

I verified that the DOCKER_HOST=npipe:////./pipe/docker_engine variable was not created, so I created it manually and now it works without any more problems.

### Steps to Reproduce

windows installation and reboot windows.

### Result

docker cli would no longer connect to the docker host.

### Expected Behavior

docker cli connect to docker host.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
On Windows, `DOCKER_HOST` should already default to `npipe:////./pipe/docker_engine` — so you shouldn't need to set it separately.  Note that (of course) Rancher Desktop would need to be started manually in the default configuration — we do not attempt to start automatically on Windows startup.

Am I understanding correctly that manually setting `DOCKER_HOST` (from the previous, undefined, value) fixes things for you?

**Comment by mook-as** [comment]
That's even weirder then…
The variable should _not_ be created at install, because that's the default value; not having it at all should work fine.

**Comment by jandubois** [comment]
> The variable should _not_ be created at install, because that's the default value; not having it at all should work fine.

This can happen when the user has been using a `docker context` with a non-default setting. `DOCKER_HOST` will then override the value from the context.
