### ISSUE TITLE
Outdated k8s versions

### ISSUE THREAD

**Issue by dougbreaux** [rancher-sandbox/rancher-desktop#1584]
### Actual Behavior

My k8s list shows an outdated set of versions, compared both to a colleague and to @jandubois.

Mine:
![image](https://user-images.githubusercontent.com/25640850/153914654-b5d835a4-10cf-4c3d-a35c-8c1d441b9178.png)

Colleague:
![image](https://user-images.githubusercontent.com/25640850/153914715-6f05fa83-818f-4c55-85ee-5ca7a3207d36.png)

Jan:
![image](https://user-images.githubusercontent.com/25640850/153914787-ca0853e0-5285-483b-b76f-74d8305fc23a.png)

### Steps to Reproduce

Start RD, view Preferences > Kubernetes Settings

### Result

Different available versions from others

### Expected Behavior

Same available versions

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.21.7

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise, Version 21H2 (OS Build 19044.1526)

### What CPU architecture are you using?

x64

### Windows User Only

Nothing relevant

**Comment by jandubois** [comment]
My screenshot shows 2 stable versions simultaneously. Not sure if this is a separate issue, but I saw this when I tried to verify the "latest" problem. Running 1.0.1 on M1, fwiw.

**Comment by mcekovic** [comment]
This issue manifests when new Kubernetes versions become available and are downloaded. Previous latest version tags are not cleared, but new versions with latest tag are added.
