### ISSUE TITLE
Rancher Desktop 1.0.1 does not install Supporting Utilities on M1 Mac due to lack of write privileges to /usr/local/bin

### ISSUE THREAD

**Issue by littlejackal** [rancher-sandbox/rancher-desktop#1604]
### Actual Behavior

Installation of Rancher Desktop prompted for superuser password, however it does not appear to have the elevated privileges required to subsequently create symlinks for supporting utilities in /usr/local/bin

Clicking on "Supporting Utilities" tab in Rancher Desktop shows red error text:

Insufficient permission to manipulate /usr/local/bin: Error: EACCES: permission denied, access '/usr/local/bin'

All supporting utilities listed in this panel are therefore greyed out.

### Steps to Reproduce

Install Rancher Desktop 1.0.1 on MacOS Monterey 12.1 (21C52)

### Result

Insufficient permission to manipulate /usr/local/bin: Error: EACCES: permission denied, access '/usr/local/bin'

### Expected Behavior

Rancher Desktop has or acquires proper permissions to install supporting utilities

### Additional Information

Factory Reset in Rancher Desktop troubleshooting section does not resolve this issue. Request for elevated privileges is never asked after initial installation.

Kubernetes does not appear to be affected and Desktop reports everything working as expected.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

v1.22.6 (stable)

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.1 (21C52)

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by godlove10** [comment]
b cncngfgn

**Comment by painhardcore** [comment]
same with macos 12.2.1 and rancher-desktop 1.2.1

**Comment by ggustafsson** [comment]
This has been fixed in a new release so this issue can be closed.

See:
https://github.com/rancher-sandbox/rancher-desktop/issues/1732
https://github.com/rancher-sandbox/rancher-desktop/issues/1155
