### ISSUE TITLE
"docker login" to access private registry fails

### ISSUE THREAD

**Issue by mehran63** [rancher-sandbox/rancher-desktop#1607]
### Actual Behavior

After a fresh installation on Mac with Apple M1 chip, I try to run `docker login` but it fails with the following error:
> Error saving credentials: error storing credentials - err: signal: segmentation fault, out: 

It seems that Rancher Desktop didn't create `~/.docker` directory as part of the installation, I create one myself but still getting the same error.

### Steps to Reproduce

1. Run `docker login`
2. Provide username
3. Provide password
4. It prompts with the following error:
> Error saving credentials: error storing credentials - err: signal: segmentation fault, out: ``

If the credential were not right , the error would have been as follow:
> Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or passwor

### Result

Error saving credentials: error storing credentials - err: signal: segmentation fault, out: ``

### Expected Behavior

Successful login and credential/token stored in `.docker/config.json`.

### Additional Information

Apple M1 chip could be the culprit.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

v1.22.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey Version 12.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by jandubois** [comment]
Can you create an empty `config.json` file and see if that makes a difference? Something like

```console
$ mkdir -p ~/.docker
$ echo "{}" > ~/.docker/config.json
```

**Comment by mehran63** [comment]
> Can you create an empty config.json file and see if that makes a difference? Something like

Still getting the same error.

**Comment by goober** [comment]
> Can you create an empty `config.json` file and see if that makes a difference? Something like

I had the same issue but the suggested solution worked for me.

**Comment by mehran63** [comment]
> I had the same issue but the suggested solution worked for me.
@goober I removed and recreated the config file and still the same error. Do you have the same silicon, Apple M1? By any chance, did you install Docker Desktop before or after?

**Comment by edy** [comment]
I also have a M1 with a freshly installed rancher desktop (Container Runtime set to `dockerd` in Kubernetes Settings). Login works for me.

```
$ docker login <my own registry>
Username: edy
Password:
WARNING! Your password will be stored unencrypted in /Users/edy/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

also logging in to docker hub did work:

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: edy
Password:
WARNING! Your password will be stored unencrypted in /Users/edy/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

**Comment by jandubois** [comment]
Creating `~/.docker/config.json` and configuring credential helpers is covered by #2013
