### ISSUE TITLE
ca.pem cannot be found

### ISSUE THREAD

**Issue by abialas** [rancher-sandbox/rancher-desktop#1608]
### Actual Behavior

I installed Rancher on my MacOS (with Intel). When I start it and try to run any docker command I get:

> unable to resolve docker endpoint: open /Users/adabia/.docker/machine/machines/default/ca.pem: no such file or directory

I have no even .docker directory under my user home folder. I verified with the others and Rancher created this folder for them. What could be the reason?

### Steps to Reproduce

- install Rancher Desktop on MacOS (with Intel)
- try to run docker ps

### Result

unable to resolve docker endpoint: open /Users/adabia/.docker/machine/machines/default/ca.pem: no such file or directory

### Expected Behavior

I should get docker response with empty list.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

v1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS BigSur 11.6.2

### What CPU architecture are you using?

x64

**Comment by ryanmt** [comment]
I've run into the same problem on an Apple silicon Mac.  I've attached my zipped folder here in case it is helpful.  I don't see any specific logged errors but my `~/.docker` folder is very empty:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/299377/167918321-4f1c4b22-d9fc-4b81-a501-93205c119e1d.png">

[rancher-desktop.zip](https://github.com/rancher-sandbox/rancher-desktop/files/8672419/rancher-desktop.zip)

**Comment by Deviad** [comment]
Same here, is there any news on this one? 
It's 2024.

**Comment by mook-as** [comment]
We're not using docker-machine (but we used to, way back); so if you're getting this with a non-obsolete version of Rancher Desktop, please check `docker context ls` and make sure you're using the `rancher-desktop` one (or, if you have [administrative access](https://docs.rancherdesktop.io/ui/preferences/application/general#administrative-access) enabled, that you're using the default one and it doesn't have any weird settings in `docker context inspect`).
