### ISSUE TITLE
How to install Rancher Desktop in Fedora Kinoite or Fedora Silverblue?

### ISSUE THREAD

**Issue by hermesalvesbr** [rancher-sandbox/rancher-desktop#1610]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/1603

<div type='discussions-op-text'>

<sup>Originally posted by **hermesalvesbr** February 16, 2022</sup>
I tried rpm-ostree, but it didn't find rancher-desktop. I also tried through zypper, but it is not possible to modify read-only files.

I need to use appimage? 

https://docs.rancherdesktop.io/installation/#linux </div>

### AppImage didn´t work

2022-02-17T12:55:51.713Z: Trying to determine version, can't get output from /tmp/.mount_ranchetDYcoj/opt/rancher-desktop/resources/resources/linux/bin/kubectl version Error: /tmp/.mount_ranchetDYcoj/opt/rancher-desktop/resources/resources/linux/bin/kubectl exited with code 1
    at ChildProcess.<anonymous> (/tmp/.mount_ranchetDYcoj/opt/rancher-desktop/resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: 'Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}\n'
}
2022-02-17T12:55:51.714Z: Can't get version for kubectl in /tmp/.mount_ranchetDYcoj/opt/rancher-desktop/resources/resources/linux/bin/kubectl
2022-02-17T12:56:11.856Z: event settings-read in main: [object Object]

**Comment by hermesalvesbr** [comment]
I have tried from toolbox container too.

![Screenshot_20220217_105705](https://user-images.githubusercontent.com/379850/154496414-11f549e6-9595-40fd-87ee-d9664654431d.png)

**Comment by evertonlperes** [comment]
Installing via AppImage is smoothly (same as installing RPM and Deb packages).
I was wondering if there's any restrictions on the user permissions that could affect the installation.

Could you share all logs (zip/tar preferable) from your last attempt? You can find it navigating to Troubleshooting tab and clicking on `Show Logs`.

**Comment by hermesalvesbr** [comment]
Thanks for responding. I will send the log files. 

No, it's not corporate network. It's a simple connection with my ISP provider. 

I'm using Fedora Kinoite 35. 

With windows, or fedora workstation 34. Works fine, in the same network.

**Comment by hermesalvesbr** [comment]
I can´t access the log files. The window didn´t open.

rancher-desktop
bash: rancher-desktop: comando não encontrado
[hermes@fedora hermes]$ toolbox enter k8s
⬢[hermes@toolbox hermes]$ rancher-desktop
Gtk-Message: 15:49:13.510: Failed to load module "colorreload-gtk-module"
Gtk-Message: 15:49:13.510: Failed to load module "appmenu-gtk-module"
Config file has no clusters, will retry later
[5720:0217/154913.572022:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
**LaunchProcess: failed to execvp:
xdg-open**

**Comment by evertonlperes** [comment]
I tried to replicate the issue, but on both Fedora 35 and Fedora Silverblue, getting the following error:

AppImage execution:
```bash
[test@fedora ~]$ sudo chmod a+x ~/Downloads/rancher-desktop-1.0.1-Build7.1.glibc2.27-x86_64.AppImage 
[test@fedora ~]$ ~/Downloads/rancher-desktop-1.0.1-Build7.1.glibc2.27-x86_64.AppImage 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[8927:0217/135751.865105:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[8987:0217/135752.176558:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
creating dir /var/home/test/.kube
creating file /var/home/test/.kube/config
Config file has no clusters, will retry later
```

![Screen Shot 2022-02-17 at 12 57 46 PM](https://user-images.githubusercontent.com/37411123/154562371-7c5538cc-ecab-4e84-8db5-e4d5f9901e09.png)

[fedora-silverblue-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/8091953/fedora-silverblue-logs.zip)

As I'm trying to replicate it through a virtual box instance, a bunch of variables comes up. We might need some @adamkpickering thoughts on this issue though.

**Comment by hermesalvesbr** [comment]
[logs.tar.gz](https://github.com/rancher-sandbox/rancher-desktop/files/8092682/logs.tar.gz)

**Comment by tepene** [comment]
![image](https://user-images.githubusercontent.com/54766327/162904987-6077c7a0-5640-421a-89e7-15437beb8407.png)

I have a Fedora Silverblue test installation (in a Gnome Box VM). Rancher-Desktop can be started from the AppImage. On the first launch I can see that docker gets installed and all symbolic links were created. On the second launch the App starts but the symbolic links point to the old directory under **/tmp**.

Screenshot details:
- Terminal shows actual mount in **/tmp** folder
- Rancher-Desktop screen shows symbolic links to old **/tmp** folder

Has anyone got this working on Silverblue?

**Comment by tepene** [comment]
After fiddling around with a test installation in a distrobox i returned to the latest appimage version 1.4.1. No I was able to start it successfully and integration with vscode does also work.

**Comment by jandubois** [comment]
Thanks for confirming @tepene !

Closing this issue; please re-open if somebody else still experiences any problems on Fedora!
