### ISSUE TITLE
Port forwarding not working as expected

### ISSUE THREAD

**Issue by eviscares** [rancher-sandbox/rancher-desktop#1611]
### Actual Behavior

Self built images don't open ports when run with `nerdctl run -p 127.0.0.1:8081:80 f2d889a1bc4c`.
Prebuilt nginx container opens up port 8080 as expected when run with `nerdctl run -d -p 127.0.0.1:8080:80 nginx:alpine`.

lima.ha.stderr.log shows no error, but also shows no success unlike for nginx image which results in: 
`"level":"debug","msg":"guest agent event: {Time:2022-02-17 15:20:26.158725448 +0000 UTC LocalPortsAdded:[{IP:127.0.0.1 Port:8080}] LocalPortsRemoved:[] Errors:[]}","time":"2022-02-17T16:20:26+01:00"`

### Steps to Reproduce

Run `nerdctl run -p 127.0.0.1:8081:80 f2d889a1bc4c` with an image that should react on port 80.
Try to telnet into port

### Result

Connection not possible on chosen port

### Expected Behavior

Connection pssible on exposed port

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.01

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by evertonlperes** [comment]
Thanks for filing the issue @eviscares 

I did a couple validations and something looks odd on your command. 
AFAIK, the hash `f2d889a1bc4c` is the container ID, which is random and it will change if you stop/start the container instance.

telnet output:
```bash
❯ telnet 127.0.0.1 8081
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

nerdctl run output:
```bash
nerdctl run -p 127.0.0.1:8081:80 nginx:latest
docker.io/library/nginx:latest:                                                   resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:bb129a712c2431ecce4af8dde831e980373b26368233ef0f3b2bae9e9ec515ee: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:c316d5a335a5cf324b0dc83b3da82d7608724769f6454f6d9a621f3ec2534a5a:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:5eb5b503b37671af16371272f9c5313a3e82f1d0756e14506704489ad9900803:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b559bad762bec166fd028483dd2a03f086d363ee827d8c98b7268112c508665a:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:1ae07ab881bd848493ad54c2ba32017f94d1d8dbfd0ba41b618f17e80f834a0f:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:091c283c6a66ad0edd2ab84cb10edacc00a1a7bc5277f5365c0d5c5457a75aff:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:55de5851019b8f65ed6e28120c6300e35e556689d021e4b3411c7f4e90a9704b:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:78091884b7bea0fa918527207924e9993bcc21bf7f1c9687da40042ceca31ac9:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 7.7 s                                                                    total:  54.1 M (7.0 MiB/s)
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/02/17 21:26:27 [notice] 1#1: using the "epoll" event method
2022/02/17 21:26:27 [notice] 1#1: nginx/1.21.6
2022/02/17 21:26:27 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
2022/02/17 21:26:27 [notice] 1#1: OS: Linux 5.10.93-0-virt
2022/02/17 21:26:27 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:1024
2022/02/17 21:26:27 [notice] 1#1: start worker processes
2022/02/17 21:26:27 [notice] 1#1: start worker process 32
2022/02/17 21:26:27 [notice] 1#1: start worker process 33

# Got nginx server running at http://localhost:8081
```

Have you faced the same issue using `moby/dockerd`?

**Comment by eviscares** [comment]
Hey, thanks for taking a look at this.
Something is definitely off. I checked and `f2d889a1bc4c` which should be fine to use in a run command, right?
Even weirder, after a restart of my mac I reran the command, this time with port 8080 as local port and for a short time I could reach nginx under `127.0.0.1` which is really weird, because the container I was starting was a node container.
I'm wondering if there is something weird happening inside the vm, is there a good way to inspect it from the inside to see what's going on?

The problem also seems to be there when running `moby/dockerd`, and using a tag instead of the image id also makes no difference.

**Comment by eviscares** [comment]
I seem to have fixed it. My best guess is that it came from an old lima instance still being available on the machine.
Sorry for wasting your time.

**Comment by evertonlperes** [comment]
> I seem to have fixed it. My best guess is that it came from an old lima instance still being available on the machine. Sorry for wasting your time.

No problem, glad that you sorted it out.

Regarding accessing lima VM, you can access it through:
```bash
LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0
```

**Comment by danieldonoghue** [comment]
I the same issue; I am using Mac m1, moby/dockerd and have exposed the relevant ports in my Dockerfile and oublised when running but if I attempt to send anything to those ports, I get connection refused..

on the host:
```
% docker ps|grep cont
ef25e8e3f392   dd-image                "/entrypoint.sh"         36 minutes ago   Up 36 minutes (healthy)   0.0.0.0:16384->16384/udp, :::16384->16384/udp   dd-container
```

on the container:
```
bash-5.1# nc -l -u -p 16384 -s 0.0.0.0 -v
listening on 0.0.0.0:16384 ...
```

on the host:
```
% cat /tmp/test|nc -u 127.0.0.1 16384
read(net): Connection refused
```

**Comment by bgagnon** [comment]
Lima does not support UDP port forwarding -- it uses SSH tunnels under the hood.
See lima-vm/lima#366.

**Comment by danieldonoghue** [comment]
you can get round this issue by adding a network route on your host for the docker network in question, pointing at the lima vm and then using the IP address directly.

I.E.,
```
route -n add -net 172.17.0.0/16 lima-ip
cat /tmp/test|nc -u 172.17.0.2 16384
```

**Comment by gunamata** [comment]
The problem reported in the issue description seems to have been sorted out. Closing the issue. Please free to reopen if it's still a problem.

**Comment by sumanthkumarc** [comment]
Any idea how can we get the lima-ip mentioned in this comment - https://github.com/rancher-sandbox/rancher-desktop/issues/1611#issuecomment-1176491158 ?
