### ISSUE TITLE
MacOS: Change the DNS Resolution 

### ISSUE THREAD

**Issue by DidierHoarau** [rancher-sandbox/rancher-desktop#1633]
### Problem Description

In the environment that we are working in, it seems that for some reason, it is the DNS resolution doesn't work out of the box with Rancher Desktop. 
Images can't be pull

I have already fixed the issue on Windows. We have a procedure to connect to the Rancher Desktop WSL and update the resolv.conf (there is a few more steps to do that but that's the basics). This works very well.
```
> wsl -d rancher-desktop
# cat /etc/resolv.conf
nameserver 1.1.1.1

```

Now the problem is with MacOS.... I assume that Rancher Desktop also runs some kind of VM (Lima?). We need a way to change this on MacOS's Rancher Desktop? Doing it at the MacOS system level doesn't work. 

### Proposed Solution

I would suggest the following

Either: There should be a way to configure this for MacOS and this way should be documented (ideally can be documented for Windows as well)

Either: Rancher Desktop should be able to use the host name resolution (unsure what the problem is to be honest)

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by Nino-K** [comment]
@DidierHoarau thanks for reaching out. 

> I have already fixed the issue on Windows. We have a procedure to connect to the Rancher Desktop WSL and update the resolv.conf (there is a few more steps to do that but that's the basics). This works very well.

We just did some work in our upcoming release that addresses the issue on the Windows platform so you may no longer need a process to update the `/etc/resolve.conf`. 

However, as for the MacOS the [lima host agent](https://github.com/lima-vm/lima/blob/01ce318b113b88196ad4862278fdb9876cb03cc8/pkg/hostagent/dns/dns.go#L51) looks up in `/etc/resolve.conf` of the host machine for DNS resolutions. If that does not work for whatever reason it falls back on some predefined DNS server addresses such as `8.8.8.8` and `1.1.1.1`. 

Are you able to share with us a bit more information on the errors you are seeing? Perhaps some logs from RD and content of the `/etc/resolve.conf`

Feel free to redact any confidential or corporate-specific information.

**Comment by mackankowski** [comment]
I've also experienced a DNS resolution issue so I couldn't pull any image or login to docker hub, but finally, I've worked out the solution, and maybe it will turn out useful: 

[# Docker network issues when using Rancher Desktop on Mac with Apple Silicon ARM-based processor (M1 chip) - readme.md](https://gist.github.com/mackankowski/be575ec0b81fd8ba3a948d3e84410adc)

Best regards,
Maciej

**Comment by Nino-K** [comment]
@mackankowski thanks for providing additional info, are you able to share with us some logs when the DNS issue is taking place? 

You can get them under the Troubleshooting tab -> Show Logs.

That would help us to pinpoint the issue.

**Comment by mackankowski** [comment]
@Nino-K, My only issue was about incorrect DNS value after Rancher Desktop installation and I thought it could be kind of a similar one. I could imagine that the DNS address (nameserver value) in lima VM was set as default with the DNS of my VPN but I can't verify it now. I think the default DNS address should be 8.8.8.8 so docker (and the Linux virtual machine in general) would have access to public domains like docker hub/registry (also, I couldn't ping any other public www from the inside of the VM). As I provided in my gist link, this is a solution that helped me to fix the wrong server name (DNS) and docker has started working again.

**Comment by Nino-K** [comment]
@DidierHoarau We have provisioning scripts that can be placed in the following path `~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml` the syntax is similar to [lima-config.yaml](https://github.com/rancher-sandbox/rancher-desktop/blob/main/src/assets/lima-config.yaml)

Can you please see if this could help you?

**Comment by pboushy** [comment]
@Nino-K - when do the provisioning scripts run?

With ZSH you can run this to get the primary IPv4 DNS Server from `scutil`:
`[[ $(scutil --dns) =~ 'nameserver\[0\] : ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})' ]] && dnsServer="$match[1]"`

I'm interested in making it work as a provisioning script until DNS and proxy are more figured out.

**Comment by DidierHoarau** [comment]
Hi,

Sorry for the late reply. Actually took us some time to be able to test this.

I confirm that this part works in our environment:

```
hostResolver:
  enabled: false
dns:
- 8.8.8.8
```

Thanks you for the help!

**Comment by Nino-K** [comment]
@DidierHoarau going to close this issue, feel free to re-open if needed.
