### ISSUE TITLE
[Fix] Intercept traefik startup in CI

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1634]
K3s is responsible to startup the traefik services and in order to get the traefik load balancer IP Address, we need to intercept it, wait and then get the IP address.
This handling seems a bit flaky in CI (Linux) and it need a deeper analysis.

Ref: #885 (Ci Only - Linux runner)

**Comment by jandubois** [comment]
Traefik testing is done by BATS
