### ISSUE TITLE
Debugging in docker container via VSCode docker extension does not work

### ISSUE THREAD

**Issue by timirnich** [rancher-sandbox/rancher-desktop#1638]
### Actual Behavior

Using RD with dockerd runtime, version 1.0.1. The VSCode docker extension provides a way to run and debug code within a docker container, via a special, automatically generated, run config. I'm using this with a Python/Flask based example app (see https://github.com/SUSE-Rancher-Community/example-flask-sqlite). Generating the run config via the command `Docker: Initialize for Docker debugging` works fine, but when I start the resulting `Docker: Python - Flask` run config, it times out after building and launching the container with the error message `Timed out waiting for the launcher to connect`.
![Screenshot 2022-02-23 at 08 30 37](https://user-images.githubusercontent.com/16071350/155277243-c8c6e567-9ca4-48de-b990-8f9727944926.png)
 

### Steps to Reproduce

- Clone repo https://github.com/SUSE-Rancher-Community/example-flask-sqlite 
- Start VSCode in the root directory
- cmd+shift P -> Docker: Initialize for Docker debugging. Select `Python Flask` and `app.py` in the following dialogs. 
- Switch to Run and Debug Tab, select the `Docker: Python - Flask` run config and start it
- Wait for the timeout error message to appear
- Hit cancel

### Result

Output of the `docker-run: debug` task:

```
> Executing task: docker-build <

> docker build --rm --pull -f "/Users/tim/Documents/src/example-flask-sqlite-tim/Dockerfile" --label "com.microsoft.created-by=visual-studio-code" -t "exampleflasksqlitetim:latest" "/Users/tim/Documents/src/example-flask-sqlite-tim" <

Sending build context to Docker daemon  256.5kB
Step 1/15 : FROM python:3
3: Pulling from library/python
Digest: sha256:f06f47e4bfbda3ba69c4e1ea304f5a3c2a48ee6399ab28c82369fc59eb89410e
Status: Image is up to date for python:3
 ---> dfce7257b7ba
Step 2/15 : RUN apt-get clean     && apt-get -y update
 ---> Using cache
 ---> 2b2cbde40140
Step 3/15 : RUN apt-get -y install     python3-pip
 ---> Using cache
 ---> 976e862476d4
Step 4/15 : WORKDIR /app
 ---> Using cache
 ---> f8b31c9a385f
Step 5/15 : COPY requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 923b0fa4ab6d
Step 6/15 : RUN pip3 install -r requirements.txt
 ---> Using cache
 ---> 5fb48fc7d72c
Step 7/15 : COPY database /app/database
 ---> Using cache
 ---> 359f8e4a41a9
Step 8/15 : COPY handlers /app/handlers
 ---> Using cache
 ---> 20d765c948c5
Step 9/15 : COPY templates /app/templates
 ---> Using cache
 ---> ba7ceda43d45
Step 10/15 : COPY app.py /app/app.py
 ---> Using cache
 ---> c2c7cbc354aa
Step 11/15 : COPY schema.sql /app/schema.sql
 ---> Using cache
 ---> e9899fdd8e02
Step 12/15 : RUN flask init-db
 ---> Using cache
 ---> b6eaf2d19e1d
Step 13/15 : EXPOSE 5000
 ---> Using cache
 ---> 676a9849a4e6
Step 14/15 : CMD [ "python3", "app.py" ]
 ---> Using cache
 ---> f13378e68ec2
Step 15/15 : LABEL com.microsoft.created-by=visual-studio-code
 ---> Using cache
 ---> cea444abb1d9
Successfully built cea444abb1d9
Successfully tagged exampleflasksqlitetim:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

Terminal will be reused by tasks, press any key to close it.

> Executing task: docker-run: debug <

> docker run -dt -P --name "exampleflasksqlitetim-dev" -e "FLASK_APP=app.py" --label "com.microsoft.created-by=visual-studio-code" -v "/Users/tim/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy:/debugpy:ro,z" --entrypoint "python3" "exampleflasksqlitetim:latest" <

55f5a686c2997fa9bf9fc23b20c9f04f55fadb803838845e3ad8e76e5c79edba

Terminal will be reused by tasks, press any key to close it.
```

Output on the Python Debug Console:

```
/>  /usr/bin/env /usr/local/bin/python3 /Users/tim/.vscode/extensions/ms-azuretools.vscode-docker-1.20.0/resources/python/launcher.py 65281 -- -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002 docker exampleflasksqlitetim-dev 
docker exec -d exampleflasksqlitetim-dev python3 /debugpy/launcher host.docker.internal:65281 -- -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002
 /> 
```

### Expected Behavior

The local VSCode should be able to connect to the debugger running in the container and show a clickable link in the console output that takes me to the frontend of the app. I should hit the breakpoints set in the code once sending a request to the frontend default route. From there I should be able to step through the code and debug it as if it was running locally. 

### Additional Information

Similar behavior is observed when attempting to debug a Kubernetes application with Google Cloud Code, which used to work with previous versions of RD (0.6.1 I believe). I'll open a separate issue for that. 

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur 11.6

### What CPU architecture are you using?

x64

**Comment by sanyer** [comment]
1. DNS name `host.docker.internal` is not available in Rancher docker containers by default.
2. Even if `host.docker.internal` is added to hosts file it results in `ConnectionRefusedError: [Errno 111] Connection refused`.

For context, these are the commands VSCode runs:

```sh
docker build --rm --pull -f "/Users/<USERNAME>/workspace/other/example-flask-sqlite/Dockerfile" --label "com.microsoft.created-by=visual-studio-code" -t "exampleflasksqlite:latest" "/Users/<USERNAME>/workspace/other/example-flask-sqlite"

# host.docker.internal could be added to container by adding --add-host:
# docker run --add-host=host.docker.internal:172.17.0.1 -dt -P --name "exampleflasksqlite-dev" ...
docker run -dt -P --name "exampleflasksqlite-dev" -e "FLASK_APP=app.py" --label "com.microsoft.created-by=visual-studio-code" -v "/Users/<USERNAME>/.vscode/extensions/ms-python.python-2022.0.1814523869/pythonFiles/lib/python/debugpy:/debugpy:ro,z" --entrypoint "python3" "exampleflasksqlite:latest"

docker exec -d exampleflasksqlite-dev python3 /debugpy/launcher host.docker.internal:52952 -- -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002
```

Docker for Desktop sets up `host.docker.internal` automagically: https://docs.docker.com/desktop/mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
And Rancher Desktop (dockerd) doesn't do that.

On a side note @timirnich:
You have `apt-get update` in a separate layer from `apt-get install` here: https://github.com/SUSE-Rancher-Community/example-flask-sqlite/blob/main/Dockerfile#L3-L4
Always combine `RUN apt-get update` with `apt-get install` in the same RUN statement: https://docs.docker.com/develop/develop-images/dockerfile_best-practices#apt-get

**Comment by sanyer** [comment]
Seems like this was resolved, but not yet released: https://github.com/rancher-sandbox/rancher-desktop/pull/1625

**Comment by jandubois** [comment]
> Seems like this was resolved, but not yet released: #1625

Thanks for the reminder; closing now. Please re-open if the problem still happens with the 1.1.0 release (should be out in a few days).

**Comment by timirnich** [comment]
Thanks folks - will test with 1.1.0 once available. Also big thanks to @sanyer for the tip with the run statements for apt-get, wasn't aware.

**Comment by timirnich** [comment]
Thanks folks - will test with 1.1.0 once available. Also big thanks to @sanyer for the tip with the run statements for apt-get, wasn't aware.

**Comment by timirnich** [comment]
Thanks folks - will test with 1.1.0 once available. Also big thanks to @sanyer for the tip with the run statements for apt-get, wasn't aware.

**Comment by gunamata** [comment]
@timirnich , I ran into some issues with your [sample](https://github.com/SUSE-Rancher-Community/example-flask-sqlite) , I am not sure if there are any steps I need to follow other than the ones you showed in your video.

But, I could get the debugging working with the samples provided [here](https://github.com/bwateratmsft/samples) with the 1.1.0 release candidate (not yet released as of today, Feb 25th). 

Yes, Please give the upcoming 1.1.0 a try with your own samples and let us know if you see any problems.

**Comment by timirnich** [comment]
@gunamata was the issue related to not finding tables in the SQLite database? You need to run `flask init-db` to set up the db structure. Don't remember if that's in the video. 

Will a corresponding firewall rul be required on MacOs as well?

**Comment by gunamata** [comment]
@timirnich , I did not run `flask init-db`. I guess this command needs to be run on the host.  I will try your sample with this step again.

I did not get a chance to try on MacOs yet. Also, the firewall requirement might be my machine specific.. So, I suggest you try debugging use case with out the firewall rule and if doesn't work then set the rule.

**Comment by timirnich** [comment]
I have re-tested with 1.1.1. It goes further but still does not work. On the debug console I see 
```
Serving Flask app 'app.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on [http://172.17.0.2:5002/]() (Press CTRL+C to quit)
 ```
But when I hit the frontend URL in the browser it just times out and no breakpoints get hit. 

It's entirely likely that I'm hitting the MacOS counterpart of the missing firewall rule Guna was encountering. Is anyone able  to tell me what the right rule to set on MacOS would be? I assume it's not directly congruent to what needs to be done on Windows since it's not WSL.

**Comment by sanyer** [comment]
Hey @timirnich , I've also tested samples provided [here](https://github.com/bwateratmsft/samples) with the 1.1.1 and Docker Desktop.
It works flawlessly.

Seems like something might be wrong with the VSCode Docker extension or with the way we use it. I wasn't able to use this extension to run several samples even the one they provide [here](https://code.visualstudio.com/docs/containers/quickstart-python)
This is the cmd for this samples:
`python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002`
and VSCode Docker is running this command:
`python3 /debugpy/launcher host.docker.internal:52952 -- -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002`

**Comment by sanyer** [comment]
Actually, I was able to make it work by changing app (in `Dockerfile` and `app.py`) port to 5002 from 5000.

**Comment by sanyer** [comment]
@timirnich Actually, I was able to make it work by changing app (in Dockerfile and app.py) port to 5002 from 5000.

**Comment by timirnich** [comment]
With this tip I was able to get it working as well. For some reason VSCode auto-generates the python run command in tasks.json with port 5002. When I change it to 5000, it works. 

Side note: in my case the frontend is reachable under `http://localhost:49153/`, which I assume is an automatic port forward created by RD? The VSCode output says it's reachable under `http://172.17.0.2:5000/`, which is probably the IP of the lima VM. Probably worth documenting...

**Comment by sanyer** [comment]
Oh, I've found out even more.

When you use VSCode Docker extension to generate config, it creates file `.vscode/tasks.json`.
This file includes task `docker-run: debug` and this task holds the commandline to be used for the `docker run` command. The last item in the list `python.args` is the port which will be used and which should be exposed and bound by your Flask app.

**Comment by sanyer** [comment]
Nice, you found this while I was typing my comment :-D

**Comment by sanyer** [comment]
Yeah, `172.17.0.2` is the lima gateway and in 1.1.0 it was made available by alias `host.docker.internal`
And VSCode opens the appropriate `localhost` address automatically. Would be nice to have it stated somewhere indeed.
