### ISSUE TITLE
Kubernetes Settings - Visual Regressions

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#1641]
### Actual Behavior

Two aspects of the Kubernetes Settings page have visually regressed:

1. Information text next to reset kubernetes button is top aligned
2. Kubernetes version and port do not reflow at smaller widths

### Steps to Reproduce

1. Open Preferences
2. Navigate to Kubernetes Settings page
3. Resize window width

### Button Description

![image](https://user-images.githubusercontent.com/835961/155381892-032c0e7c-e7e6-4567-bdc7-d498348d1e4c.png)

### Kubernetes Version & Port

![image](https://user-images.githubusercontent.com/835961/155381956-65b91bd7-6a15-4369-af3f-5ae0311e4017.png)

### Button Description

![image](https://user-images.githubusercontent.com/835961/155382108-4058f641-30c6-43bf-a3b6-2de56551fe4e.png)

### Kubernetes Version & Port

![image](https://user-images.githubusercontent.com/835961/155382172-02b60dbe-14b7-4e0d-8c9a-e223961ac67b.png)

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

NA

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

NA

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
This bug is obsolete because the settings will move to a dialog.
