### ISSUE TITLE
Rancher Desktop Hangs on Installing CA Certificates

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#1642]
### Actual Behavior

* Rancher Desktop gets stuck on the Installing CA certificates step

* Image manager never gets to a ready state

### Steps to Reproduce

Still trying to identify the offending cert to produce an example, but it looks like we need an invalid CA Cert to trigger the exception

### Result

* Rancher Desktop gets stuck on the Installing CA certificates step

* Image manager never gets to a ready state

![image](https://user-images.githubusercontent.com/835961/155384645-5e34e718-59c1-475f-a20e-cdc5944792d8.png)

### Expected Behavior

Rancher Desktop will handle the cert error and continue without blocking function.

### Additional Information

Identified while working off of `main` branch

Looks to be an issue function `checkCertValidity()` in `src/main/networking/cert-parse.ts`. Introducing a `try...catch` block and handling the uncaught exception should suffice. 

```
Checking certificate for expiry...
Error: Invalid PEM formatted message.
    at Object.pem.decode (/home/phillip/Development/rancher-desktop-pr/node_modules/node-forge/lib/pem.js:192:11)
    at checkCertValidity (/home/phillip/Development/rancher-desktop-pr/dist/app/background.js:41047:75)
    at Array.filter (<anonymous>)
    at getSystemCertificates (/home/phillip/Development/rancher-desktop-pr/dist/app/background.js:41207:97)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MainEventsImpl.<anonymous> (/home/phillip/Development/rancher-desktop-pr/dist/app/background.js:41181:26)
```

### Rancher Desktop Version

1.0.1-d18f7d77

### Rancher Desktop K8s Version

NA

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Tumbleweed 20222016

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by pdalfarr** [comment]
Using Rancher 1.12.0 on Windows 11, I sometimes encounter this issue: 
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/1537201/15724dae-9f62-4e1c-98f8-fdbd8227895f)

Am I the only one?

**Comment by jandubois** [comment]
@pdalfarr Please upgrade to 1.12.1, which fixes the issue you are replying to.

If you still have problems after upgrading, please file a new issue (and attach logs), as it will have a different root cause.

**Comment by jandubois** [comment]
> @pdalfarr Please upgrade to 1.12.1, which fixes the issue you are replying to.

Oops, I mixed up the issues; this is a really old one and not the one I thought it was.

But anyways, 1.12.0 has a known problem installing CA certs on Windows, which is fixed in 1.12.1. So my advice remains the same.

**Comment by pdalfarr** [comment]
I upgraded to 1.12.1  two weeks ago and the problem didn't show up since then, so I guess it's fixed.
(I am using Ranchr on daily basis)

Thanks

**Comment by coxchen** [comment]
Hi I'm having issue upgrading to **v1.12.3 - darwin(x64)**.

I got Error starting Kubernetes:
`Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1`

**Context**:
Installing CA certificates

```
'WARNING: Skipping duplicate certificate in file ca-cert-rd-83.pem\n' +
    'WARNING: Skipping duplicate certificate in file ca-cert-rd-64.pem\n' +
    'WARNING: Skipping duplicate certificate in file ca-cert-rd-29.pem\n' +
    'WARNING: Skipping duplicate certificate in file ca-cert-rd-136.pem\n' +
    'WARNING: Skipping duplicate certificate in file ca-cert-Starfield_Services_Root_Certificate_Authority_-_G2.pem\n' +
    'run-parts: /etc/ca-certificates/update.d/certhash: exit status 132\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl shell --workdir=. 0 sudo update-ca-certificates'
}
```

Not sure why it failed with duplicate certificates.
Can anyone suggest how to make it work?

Thank you.

**Comment by mook-as** [comment]
@coxchen Please file a [new issue](https://github.com/rancher-sandbox/rancher-desktop/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml) or [discussion](https://github.com/rancher-sandbox/rancher-desktop/discussions/new?category=q-a) rather than resurrecting an older unrelated issue (since the relevant code might have changed), thanks!
