### ISSUE TITLE
Use compressed airgap tarballs, when available

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1680]
k3s only used to have uncompressed tarballs until recently. The size difference is enormous though: 160MB vs. 475MB for the latest release.

We should use the compressed tarballs whenever available. Right now it would probably be faster to let the runtime pull the (compressed) layers from Dockerhub than fetching the uncompressed tarballs from Github.

Random link to a recent-ish release without compressed tarballs: https://github.com/k3s-io/k3s/releases/tag/v1.18.17%2Bk3s1

### Acceptance criteria

Note: **all** acceptance tests have to be performed with both the `containerd` and the `moby` container engine.

* Start with RD 1.6.1, Factory Reset, Run k8s 1.23.13
* Verify the cache version is using .tar
* Upgrade to RD 1.7.0 RC
* Start 1.23.13 again and make sure the cache directory is unchanged
* Switch to 1.25.3 and verify that the cache uses the .tar.zst file
* Switch to 1.18.17 and verify that the cache uses the .tar file
* If you can find a k3s release that has a .tar.gz file, but not a .tar.zst, check that as well, and verify that it downloads the .tar and not the .tar.gz file

* For each kubernetes version, check that it started properly by running e.g. `kubectl get po -A`

**Comment by gaktive** [comment]
New PR: https://github.com/rancher-sandbox/rancher-desktop/pull/3378 (can't link to it from the PR, maybe because of the hash in the title?)
