### ISSUE TITLE
VM should include xz

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#1688]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/1685

<div type='discussions-op-text'>

<sup>Originally posted by **Zerpet** March  1, 2022</sup>
<p>Hey there 👋 I have a Dockerfile with `ADD some.tar.xz` and it is not extracting the archive. I suspect the issue is a missing `xz` binary/package inside the VM.</p>

<p>The issue can be reproduced using a sample Dockerfile provided in this other issue https://github.com/moby/buildkit/issues/1172.</p>

<blockquote>&lt;snipped output&gt;</blockquote>

<p>Is there a way to install `xz` inside the VM manually, as an attempt to resolve the problem?</p></div>

That sounds like we just need to include [xz](https://pkgs.alpinelinux.org/package/v3.14/main/x86_64/xz) in our distros (Windows & Lima).

**Comment by jandubois** [comment]
> That sounds like we just need to include [xz](https://pkgs.alpinelinux.org/package/v3.14/main/x86_64/xz) in our distros (Windows & Lima).

Is there an exhaustive list of all compression formats we should support? E.g. do we need to bundle lzma as well (just an example; I haven't checked if we already include it or not).

**Comment by jandubois** [comment]
> do we need to bundle lzma as well

I just noticed that `xz` includes `lzma` support. :)

**Comment by jandubois** [comment]
Fixed by

* [ ] https://github.com/lima-vm/alpine-lima/pull/51
* [ ] https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/31

**Comment by jandubois** [comment]
Distros bumped by #1766
