### ISSUE TITLE
Option to use a specific (available) port for Port forwarding instead of a randomly picked port.

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1695]
### Problem Description

The current Port forwarding feature picks a random available port. It would be helpful to developers to pick a specific port.

### Proposed Solution

Add a text field to allow users to input the port number, and use that for port forwarding.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jandubois** [comment]
I'm not sure this is easily possible; I think the port is chosen by kubernetes. If you want to forward to a specific port, you probably have to create a service for it.

**Comment by gunamata** [comment]
The ask here is to support what `kubectl port-forward ...` does, via the GUI where we can specify the host port to forward to.

**Comment by blankensteiner** [comment]
Where I work we are 50-60 people that would love to switch from Docker Desktop to Rancher Desktop, but we would need this feature.
We have created a helm chart for setting up a developer environment and would require that a number of custom ports can be opened and will remain open when Rancher Desktop is restarted.

**Comment by gunamata** [comment]
Duplicate of https://github.com/rancher-sandbox/rancher-desktop/issues/791, which is addressed in the release https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.5.0
