### ISSUE TITLE
Cannot Connect to Docker Daemon on WSL with kubernetes disabled

### ISSUE THREAD

**Issue by devNaresh** [rancher-sandbox/rancher-desktop#1703]
### Actual Behavior

After upgrading rancher desktop to `v1.1.0`, I am not able to use docker when kubernetes is disabled. I am using ubuntu 20.04 with WSL2.

### Steps to Reproduce

- run rancher desktop v1.1.0
- disable kubernetes
- execute `docker ps` in wsl machine

### Result

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

### Expected Behavior

docker should work with kubernetes disabled

### Rancher Desktop Version

1.1.0

### Rancher Desktop K8s Version

1.22

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
@evertonlperes Can you check if you can repro?

**Comment by evertonlperes** [comment]
> @evertonlperes Can you check if you can repro?

On it.

**Windows 11 Pro (21H2) + Ubuntu 20.04 WSL**
The socket seems alive after disabling k8s, but after selecting `moby` and disabling `k8s`, the `docker ps` does not list any RD running containers:

```bash
# Making sure k8s is disabled
test@Win10RD:~$ kubectl get pods -A
I0303 18:34:08.034722     412 versioner.go:58] Get https://192.168.9.111:6443/version?timeout=5s: dial tcp 192.168.9.111:6443: connect: connection refused
The connection to the server 192.168.9.111:6443 was refused - did you specify the right host or port?

# First docker ps attempt --> empty response
test@Win10RD:~$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
# Second docker ps attempt --> empty response
test@Win10RD:~$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Logs**

**Comment by jandubois** [comment]
> but after selecting `moby` and disabling `k8s`, the `docker ps` does not list any RD running containers

That seems correct; why would you expect any containers to be running? The fact that `docker ps` shows output and not an error means that the socket is actually working, so you cannot reproduce the issue.

@devNaresh Is the problem for you reproducible after stopping Rancher Desktop and restarting it? Make sure you really exit the application (e.g. via "File | Exit") and not just close the window.

**Comment by devNaresh** [comment]
@jandubois it's seem i needed a windows restart. Now docker is working as expected with kubernetes disable. Thanks for your time. Really appreciate the efforts you guys has put on this project.
