### ISSUE TITLE
Rancher Desktop broken after 1.1.0 automatic update

### ISSUE THREAD

**Issue by johanwestling** [rancher-sandbox/rancher-desktop#1704]
### Actual Behavior

Used Rancher Desktop (v1.0.1) in Windows 10 (21H2 19044.1566) and got the automatic update downloaded. After update got applied Rancher Desktop launched but application window was white and closed after a while.

After this I downloaded the 1.1.0 installer exe from Github release page, installation went through but when finishing with the checkbox to launch Rancher Desktop checked I'm getting the following:

<img width="679" alt="Screenshot 2022-03-03 101702" src="https://user-images.githubusercontent.com/2246952/156547614-e1ea3968-b6f9-4926-ad1b-bf98d0d1c852.png">

When trying to uninstall Rancher Desktop from Apps & features I get the following:

<img width="498" alt="Screenshot 2022-03-03 123251" src="https://user-images.githubusercontent.com/2246952/156547744-9579e425-1e12-4eb8-9e2c-945de2fe43fc.png">

When checking the permissions all seems fine, and running the Uninstall Rancher Desktop.exe as administrator gives similar results.

Seems like I'm also unable to install a previous version after this, any ideas? :)

### Steps to Reproduce

1. Let Rancher Desktop v1.0.1 auto update or have Rancher Desktop v1.0.1 installed and install v1.1.0 on top of it.
2. Rancher Desktop will now work after upgrade or installation is complete.

### Result

See Actual Behavior.

### Expected Behavior

Rancher Desktop launches after upgrade/installation is completed in Windows.

### Rancher Desktop Version

1.1.0

### Rancher Desktop K8s Version

?

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2 19044.1566

### What CPU architecture are you using?

x64

**Comment by evertonlperes** [comment]
@johanwestling Thanks for filing the issue.
That's an odd behaviour and we would like to get more information from your env.
Are you behind a corporate network (during the upgrade process)? If yes, could you try the same steps outside of the company network?

**Comment by johanwestling** [comment]
Unfortunately I am, and as unfortunate I'm not able/allowed to disable the company network (Global Protect). Do you suspect some part of the installation not being properly downloaded? 

Based on the error messages I'm getting it sounds like some file association issue. And while doing some testing this morning Rancher Desktop sometimes start (windowless) and sometimes with just a blank window.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/2246952/156713746-31972717-13db-43f9-bd61-b441a65ca2ab.png">

Did however notice a windows notification this time around, seems to be Windows Defender related.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/2246952/156713897-e94ee594-7289-4b86-9c0e-c3ac874bee98.png">

I'll check with the IT department if there are some specific rules applied for our organization, but I suspect it's default for Windows Defender.

But I guess we can rule out Rancher Desktop having a bug, not sure if you can do anything for your side on this one? Feel free to close this issue in that case.

**Comment by johanwestling** [comment]
Closing this issue as I suspect there is very little that can be done from Rancher Desktop side of things. 🙂

**Comment by evertonlperes** [comment]
Thanks for sharing those information @johanwestling 
I'll bring it along with the team. This Windows Defender message is quite scary... we'll investigate it.

**Comment by mook-as** [comment]
For the initial dialog (during setup), would it be possible to hit `Ctrl+C` and copy the dialog? It'll beep as if it didn't accept the input, but (at least it used to) it will copy the title + tax to the clipboard, so that we can see the full, uncropped title text.

Thanks!

**Comment by johanwestling** [comment]
It's a Global Protect setup @evertonlperes. Other than that it's Windows/Microsoft Defender Endpoint that I know of.

Sadly I did not get around to copy the full message of that dialog before IT corrected the false positive in the Microsoft Defender rules. Do you know if it could be found out from e.g. Event Viewer or something?

**Comment by johanwestling** [comment]
Hey @mook-as after installing the update of Rancher Desktop right now I got a second chance at copying the full output of that error dialog. Funny enough it seems to be related to the fact that my machine had Internet Explorer 11 unchecked (hence uninstalled) in the Windows Features. 😄

```
[Window Title]
C:\Users\jwestlin\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Rancher Desktop.lnk

[Content]
Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item.

[OK]
```

Restarting now to see what happens with Internet Explorer 11 re-enabled in Windows Features.

**Comment by mook-as** [comment]
Well, we certainly didn't _intentionally_ add a shortcut in Quick Launch…

It probably came as part of electron-builder? I see that NSIS has a `FOLDERID_UserPinned` define (`WinCore.nsh`); however, I don't see it used by electron-builder.  This needs more investigation, I guess.

**Comment by johanwestling** [comment]
Yeah the Internet Explorer 11 being enabled didn't change anything. Seems to be Microsoft Defender blocking the app from running being the root case. 

Having the joy of contacting the organisations IT-department to add the new hash/signature for Rancher Desktop every update, and I guess that's how it will have to be until they (IT) figure out a better solution. 😞
