### ISSUE TITLE
Ability to use CIFS plugin for Kubernetes

### ISSUE THREAD

**Issue by wstr-ncrum** [rancher-sandbox/rancher-desktop#1706]
### Problem Description

Our team makes use of services that connect to network shares via the [fstab/cifs](https://github.com/fstab/cifs) plugin for kubernetes. In order to use this the nodes running kubernetes need to have JQ installed for parsing json. We can make the folders and copy in the plugin but are unable to complete the setup without a way to install JQ. Are there any package management tools in the Rancher Desktop image that could be used to manually install JQ?

### Proposed Solution

Either add JQ to Rancher Desktop or provide a tool that enables installation of a package. At worst a person messes up their install and needs to reinstall Rancher Desktop

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jandubois** [comment]
You didn't specify your OS. On Linux and macOS you can install `jq` with `apk add jq` in a provisioning script.

On Windows we don't include `apk`, but you can just download the binary directly from [Github](https://stedolan.github.io/jq/download/):

```console
/mnt/c/Users/Jan # curl -Lso jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
/mnt/c/Users/Jan # chmod +x jq
/mnt/c/Users/Jan # echo "[1,2,3]" | ./jq
[
  1,
  2,
  3
]
```

I've created #1711 to make `apk` available on Windows as well.

Provisioning script support was added for Windows in 1.1.0 via #1576
