### ISSUE TITLE
Requires a restart is scary and confusing

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1710]
### Actual Behavior

`a restart` is wrong/misleading. Normally on macOS `a restart` would mean `restarting the computer`, and on Windows it certainly would mean that. It should be `restarting the virtual machine` or _something_.

### Steps to Reproduce

1. Start Rancher Desktop 1.1.0
2. Give it sudo credentials
3. Select `Kubernetes Settings`
4. Click the checkbox to disable kubernetes

### Result

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/2119212/156627168-3627d22a-70bf-4cfb-a289-2b8bf31b7bf2.png">

### Expected Behavior

`Requires restarting the virtual machine`

### Rancher Desktop Version

1.1.0

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur 11.6.4

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment]
Noted. Thanks. Similar to the symlink topic in a recent issue you brought up on 1.1.0, we're also revisiting this aspect of the UI. For one thing, if changing one or more settings is going to require a restart (for lack of a better name), we probably need a more modal element to present to the user.

**Comment by mattfarina** [comment]
@jsoref Thank you for pointing this out. Sometime we can end up focusing on our own thing and forgetting the higher level y'all who use Rancher Desktop experience. We'll clean up this messaging.

**Comment by jsoref** [comment]
I personally range quite up and down the stack, but, I try to be aware of my internal clients who are not necessarily technical. (Just got off a plain old phone call with one such person.) It's definitely important to keep end users in mind.
