### ISSUE TITLE
Investigate XDG to manage paths to symlinks

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#1717]
### Problem Description

Based on https://github.com/rancher-sandbox/rancher-desktop/discussions/1512, we should see if XDG allows us a clear way to amend paths to a user's profile. This could help with Rancher Desktop tool usage since we're looking at symlinks and allowing our CLIs and tools to work.

@colstrom to dig into this based on his experience/knowledge.

### Proposed Solution

TBD

**Comment by mook-as** [comment]
Presumably this is about the [XDG Base Directory spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and _not_ the [xdg-app-paths npm package](https://www.npmjs.com/package/xdg-app-paths) that we no longer use (because it gives values that don't match what people use)?

**Comment by colstrom** [comment]
Correct. According to the spec...

> User-specific executable files may be stored in `$HOME/.local/bin`. Distributions should ensure this directory shows up in the UNIX `$PATH` environment variable, at an appropriate place.

Whether they **do** or not is a whole different question. I'll run some checks across the popular distros to confirm.

**Comment by jandubois** [comment]
@colstrom See #881 for more info regarding `~/.local/bin` and the recent-ish update to make it work on openSUSE.

**Comment by jandubois** [comment]
We have decided to create `~/.rd/bin` and put that on the `PATH`. We want a directory that we own completely, so we can delete and recreate it at will.

No further research required.
