### ISSUE TITLE
Write code to manage `PATH` by changing it in users' rc files

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#1719]
### Problem Description

Based on https://github.com/rancher-sandbox/rancher-desktop/discussions/1512, we should look at post-flight scripts to help set profiles to manage our paths for our tools, which are a mix of symlinks.

Python has an example we can leverage for the various shells available: https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Mac/BuildScript/scripts/postflight.patch-profile

### Proposed Solution

A similar script for Rancher Desktop

**Comment by adamkpickering** [comment]
Edited to more accurately represent a piece of the work related to integration management.
