### ISSUE TITLE
Write code to edit `PATH` by adding a file to `/etc/paths.d/`

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#1720]
### Problem Description

Based on discussion on https://github.com/rancher-sandbox/rancher-desktop/discussions/1512, we may run into a scenario whereby we edit a shell profile for some users so that the path points to a directory with symlinks.

We should figure out a way of fencing lines, whereby a factory reset removes what we edit. This could tie into logic whereby we must backup any file we edit first so we can easily revert back. 

### Proposed Solution

TBD

**Comment by adamkpickering** [comment]
Edited to more accurately reflect an item of work pertaining to integration management.

**Comment by jandubois** [comment]
I believe the problem description above does not match the issue subject.

Either way, we currently have no plans to create `/etc/path.d` files, so I'm closing this issue for now.
