### ISSUE TITLE
SQL server connection possible only using 127.0.0.1.

### ISSUE THREAD

**Issue by wertone-gh** [rancher-sandbox/rancher-desktop#1724]
### Actual Behavior

Hello,
I recently switched from Docker Desktop to Rancher Desktop.
However, when I'm trying to run SQL Server 2019 in container I have issues regarding connection.
When I was using Docker Desktop I was able to connect to database using 
localhost, 1433
., 1433,
(mypchostname), 1433

Right now after switching to Rancher Desktop I can only access sql server using 127.0.0.1, 1433.
Moreover, my applications cannot connect to db anymore (they are using host.docker.internal,1433 in connection string).
It worked in Docker Desktop, but right now it cannot connect. 

### Steps to Reproduce

- Install Rancher Desktop 1.1.0
- Use any SQL Server Client
- Run container using mcr.microsoft.com/mssql/server:2019-latest image and expose 1433 port
- Try to connect from SQL Management Studio using localhost, 1433
- Try to connect from any containerized application using host.docker.internal,1433 connection string.

### Result

Cannot connect to db. Only works using 127.0.0.1 from host machine, cannot find a way to connect from containerized application. 

### Expected Behavior

Everything works similar to Docker Desktop

### Rancher Desktop Version

1.1.0

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
The root issue here is probably the same as #1702, which will be fixed in the 1.1.1 patch release (hopefully still later today).

**Comment by jandubois** [comment]
Please test with https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.1.1 and re-open if you still have problems!

**Comment by wertone-gh** [comment]
Hello, I just tested with 1.1.1 version. Sadly issue still occurs.
Here is my docker compose file used to start SQL server
`version: "3.9"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: admin123@
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

I tried to connect to the database that I started using this compose file, but it failed. Still, the database is only reachable using 127.0.0.1.
I'm using SQL management studio to connect to database and when I try to connect using server: localhost (1433 is default port for SQL server), user: sa, pw: admin123@ I see following error:
![sql_bug](https://user-images.githubusercontent.com/57866326/156881344-e88a005b-b505-47d9-ac98-bade391cd5d4.png)

Same scenario if I use .  or my hostmachinename as server.

Moreover, the issue with communication from container still exists. I have .net core application that tries to connect to the database using the following connection string:
`server=host.docker.internal,1433;database=test;Persist Security Info=False;User ID=test;Password=test;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;`

The result is the same a with SQL management studio. 
Everything works fine when I switch to Docker Desktop (exactly the same docker compose file etc)

**Comment by wiruzman** [comment]
Already reported here #1420 .

**Comment by wertone-gh** [comment]
> Already reported here #1420.
> 
> Docker Desktop has a windows service running in the background, com.docker.backend.exe, which listens to 0.0.0.0 and the port which application runs on. Wsl as default only binds on 127.0.0.1 and [::1] where Docker Desktop in addition also binds on 0.0.0.0 and [::].
> 
> I am working on a similar solution as Docker Desktop, I tested out with a C# application where the bindings where set and immediately localhost worked.
> 
> There are other solutions from wsl repo issue using netsh, but I do not like to use admin elevation to fix this kind of problem.

So what do you recommend to use in order to connect to the database from an application running in container? host.docker.internal not working? 127.0.0.1 works only on host machine, but what about connection to db from container?

**Comment by templafymek** [comment]
For kubernetes I used to set up IPAMConfig ip address on host.docker.internal in the config map for coredns. In that way I could connect my application running in kubernetes to db hosted by docker/containerd. I did not try to connect to containers together.
