### ISSUE TITLE
trayMenu contextMenuItems should reflect actual configuration 

### ISSUE THREAD

**Issue by 4x0v7** [rancher-sandbox/rancher-desktop#1734]
### Problem Description

With #985 now implemented, the trayMenu [updateMenu](https://github.com/rancher-sandbox/rancher-desktop/blob/main/src/main/tray.ts#L179) is no longer reflective of the users choice.

If the user disables k8s, the tray status will still show ['Kubernetes is running'](https://github.com/rancher-sandbox/rancher-desktop/blob/aaa54eced53a1d9c84b460a6e7df5cfdad4a540f/src/main/tray.ts#L183)

This may confuse users into thinking Kubernetes was _not_ disabled

### Proposed Solution

Reflect the status of the _Container Runtime_ when Kubernetes has been disabled:

For example:

- Containerd is running
- Dockerd is running

Optionally the status of _both_ the runtime, and the Kubernetes cluster could be shown.

---
Examples of potential tray messages:

- Containerd is running (Kubernetes disabled)
- Dockerd is running (Kubernetes disabled)

- Kubernetes is running (container runtime: containerd)
- Kubernetes is running (container runtime: dockerd)

---
Or perhaps put the runtime first in the message:

- Containerd is running (with Kubernetes enabled)
- Dockerd is running (with Kubernetes enabled)

- Containerd is running (with Kubernetes disabled)
- Dockerd is running (with Kubernetes disabled)

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jsoref** [comment]
#1270 changed the behavior here.

**Comment by jsoref** [comment]
So, I've puzzled this out a bit.

The item could say:
* `Lima/WSL2 is starting` (as appropriate)
* `containerd/dockerd is starting` (as appropriate)

* `VM is starting`
*  `Starting` (not mentioning any implementation details)

---

* Lima doesn't have an icon atm.
* Amusingly, afaict, WSL2 doesn't have an icon either.

---

* containerd has an icon, I'm not entirely certain we'd be able to use the icon (presumably the `d`)
* While Docker has icons, I believe they're explicitly precluded under https://www.docker.com/legal/trademark-guidelines -- see the bits that say that some software may be available under Apache license the icons are not included.

---

* If we use VM, we'd probably want a generic VM icon (this might be relatively easy).
* Similarly if we don't specify `VM`
