### ISSUE TITLE
Can´t install in Manjaro Linux (via PAMAC)

### ISSUE THREAD

**Issue by hermesalvesbr** [rancher-sandbox/rancher-desktop#1737]
### Actual Behavior

```
2907 verbose stack     at ChildProcess.<anonymous> (/var/tmp/pamac-build-manjaro/rancher-desktop/src/.nvm/versions/node/v17.6.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
2907 verbose stack     at ChildProcess.emit (node:events:527:28)
2907 verbose stack     at maybeClose (node:internal/child_process:1090:16)
2907 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2908 verbose pkgid rancher-desktop@1.1.0
2909 verbose cwd /var/tmp/pamac-build-manjaro/rancher-desktop/src/rancher-desktop-1.1.0
2910 verbose Linux 5.15.25-1-MANJARO
2911 verbose argv "/var/tmp/pamac-build-manjaro/rancher-desktop/src/.nvm/versions/node/v17.6.0/bin/node" "/var/tmp/pamac-build-manjaro/rancher-desktop/src/.nvm/versions/node/v17.6.0/bin/npm" "install"
2912 verbose node v17.6.0
2913 verbose npm  v8.5.1
2914 error code 1
2915 error path /var/tmp/pamac-build-manjaro/rancher-desktop/src/rancher-desktop-1.1.0
2916 error command failed
2917 error command sh -c node ./scripts/postinstall.mjs
2918 verbose exit 1
```

### Steps to Reproduce

PAMAC INSTALL: http://aur.archlinux.org/packages/rancher-desktop

### Result

![Screenshot_20220305_161724](https://user-images.githubusercontent.com/379850/156897124-9a60988f-9554-4588-b79e-d9f52b418379.png)

### Expected Behavior

I had already installed it, but when updating via PAMAC in Manjaro it crashed the error reported above.

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Linux myagon 5.15.25-1-MANJARO #1 SMP PREEMPT Wed Feb 23 14:44:03 UTC 2022 x86_64 GNU/Linux

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
@adamkpickering Please take a look!

**Comment by dgiebert** [comment]
Seems you are using nodejs in version `v17.6.0`

As specified here: https://github.com/rancher-sandbox/rancher-desktop#macos-and-linux you should use v16.
You can see it here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rancher-desktop#n29

Will bump the version now, after a test build in about 30 minutes

**Comment by dgiebert** [comment]
@hermesalvesbr can you try building it manual and report if it works:

```bash
git clone https://aur.archlinux.org/rancher-desktop.git
cd rancher-desktop
makepkg -si
```

**Comment by hermesalvesbr** [comment]
Thanks , works now.
