### ISSUE TITLE
Rancher Desktop Fails to Start

### ISSUE THREAD

**Issue by Technophobe01** [rancher-sandbox/rancher-desktop#1741]
### Actual Behavior

Kubernetes Error
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

Last command run:
limactl --debug start --tty=false 0

Context:
Starting virtual machine

Some recent logfile lines:
```
time="2022-03-06T17:28:35-08:00" level=info msg="Starting switch daemon for \"bridged_en1\" network"
time="2022-03-06T17:28:35-08:00" level=debug msg="Running: [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]"
time="2022-03-06T17:28:35-08:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-07T01:28:35.250Z: + limactl --debug start --tty=false 0
2022-03-07T01:28:35.250Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-07T01:28:35.250Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

### Steps to Reproduce

Machine config:

- macOS Monterey
- Version 12.3 Beta
- Processor 2.7 Ghz 24 Core Intel Xeon W
- Memory 384 Gb

Rancher Desktop Version 1.1.1

### Log Data:

**Background.log**

`2022-03-07T01:44:19.580Z: event settings-read in main: [object Object]`

**update.log**

2022-03-07T01:27:58.950Z: Staged version 1.1.1 not greater than current version 1.1.1, skipping.
2022-03-07T01:27:58.951Z: Checking for update
2022-03-07T01:27:58.951Z: update: checking for update
2022-03-07T01:27:59.736Z: Update for version 1.1.1 is not available (latest version: v1.1.1, downgrade is disallowed).
2022-03-07T01:27:59.736Z: update: not available: {
  files: [
    {
      url: 'https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.1.1/Rancher.Desktop-1.1.1-mac.x86_64.zip',
      size: 407722097,
      sha512: 'cUXx61cgoOvxOUa5FAtfxs8CSDgCXhc4o1kH3OwncOMCXlGvqiZZ3O4tb6uck/j8ct8NyjZ6pZ2ANvhSs55HFQ==',
      isAdminRightsRequired: false
    }
  ],
  version: 'v1.1.1',
  path: '',
  sha512: '',
  releaseName: 'Rancher Desktop 1.1.1',
  releaseNotes: 'This is the 1.1.1 release of Rancher Desktop, an open source desktop application to bring Kubernetes and container management to Mac, Windows, and Linux. The release contains 2 bug fixes:\r\n' +
    '\r\n' +
    '- DNS not working correctly in some Windows environments\r\n' +
    '- The docker-buildx symlink was incorrect\r\n' +
    '\r\n' +
    'You can connect with the developers via:\r\n' +
    '\r\n' +
    '- The [issue queue](https://github.com/rancher-sandbox/rancher-desktop/issues)\r\n' +
    '- [Rancher Users Slack](https://slack.rancher.io/) in the #rancher-desktop channel\r\n' +
    '\r\n' +
    '## Changelog\r\n' +
    '\r\n' +
    'The [full version changelog, from v1.1.0, can be found using GitHub compare](https://github.com/rancher-sandbox/rancher-desktop/compare/v1.1.0...v1.1.1) and the details of the release can be found in the [v1.1.1 milestone](https://github.com/rancher-sandbox/rancher-desktop/milestone/17?closed=1).',
  releaseDate: '2022-03-04T20:25:49Z',
  nextUpdateTime: 1646617432410
}
2022-03-07T01:43:52.526Z: Checking for update
2022-03-07T01:43:52.526Z: update: checking for update
2022-03-07T01:43:53.791Z: Update for version 1.1.1 is not available (latest version: v1.1.1, downgrade is disallowed).
2022-03-07T01:43:53.791Z: update: not available: {
  files: [
    {
      url: 'https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.1.1/Rancher.Desktop-1.1.1-mac.x86_64.zip',
      size: 407722097,
      sha512: 'cUXx61cgoOvxOUa5FAtfxs8CSDgCXhc4o1kH3OwncOMCXlGvqiZZ3O4tb6uck/j8ct8NyjZ6pZ2ANvhSs55HFQ==',
      isAdminRightsRequired: false
    }
  ],
  version: 'v1.1.1',
  path: '',
  sha512: '',
  releaseName: 'Rancher Desktop 1.1.1',
  releaseNotes: 'This is the 1.1.1 release of Rancher Desktop, an open source desktop application to bring Kubernetes and container management to Mac, Windows, and Linux. The release contains 2 bug fixes:\r\n' +
    '\r\n' +
    '- DNS not working correctly in some Windows environments\r\n' +
    '- The docker-buildx symlink was incorrect\r\n' +
    '\r\n' +
    'You can connect with the developers via:\r\n' +
    '\r\n' +
    '- The [issue queue](https://github.com/rancher-sandbox/rancher-desktop/issues)\r\n' +
    '- [Rancher Users Slack](https://slack.rancher.io/) in the #rancher-desktop channel\r\n' +
    '\r\n' +
    '## Changelog\r\n' +
    '\r\n' +
    'The [full version changelog, from v1.1.0, can be found using GitHub compare](https://github.com/rancher-sandbox/rancher-desktop/compare/v1.1.0...v1.1.1) and the details of the release can be found in the [v1.1.1 milestone](https://github.com/rancher-sandbox/rancher-desktop/milestone/17?closed=1).',
  releaseDate: '2022-03-04T20:25:49Z',
  nextUpdateTime: 1646621032807
}

### Result

Rancher Desktop fails to start

Presenting the following Error Message as a popup:

Kubernetes Error

Error Starting Kubernetes

Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

Last command run:
limactl --debug start --tty=false 0

Context:
Starting virtual machine

Some recent logfile lines:
time="2022-03-06T17:48:18-08:00" level=info msg="Starting switch daemon for \"shared\" network"
time="2022-03-06T17:48:18-08:00" level=debug msg="Running: [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]"
time="2022-03-06T17:48:18-08:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-07T01:48:18.168Z: + limactl --debug start --tty=false 0
2022-03-07T01:48:18.169Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-07T01:48:18.169Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

### Expected Behavior

Rancher Desktop install and runs

### Additional Information

I'd expect /private/var/run/rancher-desktop-lima to contain:

ls -hal /private/var/run/rancher-desktop-lima
total 32
drwxrwxr-x   8 root    daemon     256B Mar  3 13:10 .
drwxrwxr-x  35 root    daemon     1.1K Mar  5 12:34 ..
drwxrwx---  13 daemon  everyone   416B Mar  3 13:10 bridged_en0.ctl
-rw-r--r--   1 daemon  daemon       5B Mar  3 13:10 bridged_en0_switch.pid
-rw-r--r--   1 root    daemon       4B Mar  3 13:10 bridged_en0_vmnet.pid
drwxrwx---  13 daemon  everyone   416B Mar  3 13:10 shared.ctl
-rw-r--r--   1 daemon  daemon       5B Mar  3 13:10 shared_switch.pid
-rw-r--r--   1 root    daemon       4B Mar  3 13:10 shared_vmnet.pid

however on the machine in question I get this:

ls -hal /private/var/run/rancher-desktop-lima
total 0
dr-xr-xr-x   2 root  daemon    64B Mar  5 16:49 .
drwxrwxr-x  48 root  daemon   1.5K Mar  6 02:03 ..

if I update the permissions manually

sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima

and then run:

/Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl --debug start --tty=false /Users/$USER/Library/Application\ Support/rancher-desktop/lima/_config/0.yaml

I get the following error:

DEBU[0000] interpreting argument "/Users/$USER/Library/Application Support/rancher-desktop/lima/_config/0.yaml" as a file path for instance "0"
INFO[0000] Terminal is not available, proceeding without opening an editor
FATA[0000] field `networks[1].lima` references network "bridged_en2" which is not defined in networks.yaml

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

v1.21.10

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

 Version 12.3 Beta

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment]
Could you reset the ownership and perms on `/private/var/run/rancher-desktop-lima/` to `root:daemon` and 0775 respectively and then rerun (possibly with a factory reset)?

**Comment by Technophobe01** [comment]
> sudo chown root:daemon /private/var/run/rancher-desktop-lima
> sudo chmod 0755 /private/var/run/rancher-desktop-lima
> ls -la /private/var/run/rancher-desktop-lima/
total 0
drwxr-xr-x   2 root  daemon    64B Mar  6 17:27 .
drwxrwxr-x  49 root  daemon   1.5K Mar  7 12:01 ..

----
Factory Reset through Rancher / restart application

----

Welcome to Rancher Prompt

Kubernetes Version v1.22.7 (Stable)
Container Runtime: containerd
Selected: Enable Kuberetes 

----

Result: Error

Kubernetes Error

Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

Last command run:
limactl start --tty=false /Users/pkjar/Library/Application Support/rancher-desktop/lima/_config/0.yaml

Context:
Starting Virtual machine

Recent Logfiles lines
time="2022-03-07T13:43:42-08:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-03-07T13:43:42-08:00" level=info msg="Starting switch daemon for \"shared\" network"
time="2022-03-07T13:43:42-08:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-07T21:43:42.755Z: + limactl start --tty=false /Users/<$USER>/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-03-07T21:43:42.755Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-07T21:43:42.755Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

----

Ok, so at this point, I tried switching to Docker, from Containerd... (Invert test)

Factory Reset 
Select Docker (Moby)

Result:

Kubernetes Error

Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

Last Command Run:
limactl start --tty=false /Users/pkjar/Library/Application Support/rancher-desktop/lima/_config/0.yaml

Context:
Starting Virtual machine

Recent Logfiles lines
time="2022-03-07T13:51:01-08:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-03-07T13:51:01-08:00" level=info msg="Starting switch daemon for \"bridged_en2\" network"
time="2022-03-07T13:51:01-08:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-07T21:51:02.000Z: + limactl start --tty=false /Users/<$USER>/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-03-07T21:51:02.000Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-07T21:51:02.001Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)


----

![2022-03-05_18-42-59](https://user-images.githubusercontent.com/749230/157123521-5a604f22-6fb9-4041-9a17-76fc2737fa3a.png)
![2022-03-07_13-51-26](https://user-images.githubusercontent.com/749230/157123873-c020e1a4-ecf9-4272-9ca1-35397c773760.png)

**Comment by ericpromislow** [comment]
Could you attach the `lima.log` file that contains these messages?

**Comment by Technophobe01** [comment]
Eric,

I was able to resolve the issue by manually removing Rancher Desktop, deleting the directories, rebooting the machine and then reinstalling Rancher desktop. So everything is now working. I want to just say thank you for your help. You are appreciated.

**Comment by planetf1** [comment]
I've got, what appears to be, the same error.

MacOS, Monterey/12.3

I tried uninstalling (removing the rancher desktop app) and reinstalling - made no difference.
I also removed /private/var/run/rancher-desktop - no help

ie error was:
```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
```

command was:
```
limactl start --tty=false 0
```

My logfile summary ends:
```
time="2022-03-11T18:27:47Z" level=info msg="Using the existing instance \"0\""
time="2022-03-11T18:27:47Z" level=info msg="Starting switch daemon for \"shared\" network"
time="2022-03-11T18:27:47Z" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-11T18:27:47.818Z: + limactl start --tty=false 0
2022-03-11T18:27:47.818Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-11T18:27:47.818Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```
My lima.log is empty .

**Comment by planetf1** [comment]
(can't reopen - seemed to make sense to post here rather than new issue)

**Comment by planetf1** [comment]
Occurs after a 'factory reset' in Rancher desktop also

**Comment by planetf1** [comment]
Trying this at the cli:
```
$ ./limactl start --tty=false /Users/jonesn/Library/Application\ Support/rancher-desktop/lima/_config/0.yaml
INFO[0000] Terminal is not available, proceeding without opening an editor
FATA[0000] field `networks[1].lima` references network "bridged_en0" which is not defined in networks.yaml
```

**Comment by planetf1** [comment]
I removed again, and this time cleared out all rancher config under Application Support -- same error

**Comment by planetf1** [comment]
Re: https://github.com/rancher-sandbox/rancher-desktop/issues/1441 

```
sudo chmod 775 /private/var/run/rancher-desktop-lima
```

Seems to have fixed it...
