### ISSUE TITLE
Dnsmasq based DNS is malfunctioning

### ISSUE THREAD

**Issue by byjrack** [rancher-sandbox/rancher-desktop#1747]
### Actual Behavior

DNS settings that function with corporate VPN are lost in the latest 1.1.x releases with the move to dnsmasq.

WSL (via autoconfig) attempts to send traffic out the physical adapter and not the VPN tunnel.  This won't work in our case and workaround has been to disable auto-generate and set a static in resolv.conf.  With the move to dnsmasq though I didn't want to pull that out without understanding the implications.  And the data-resolv-conf is wiped on each recycle so I don't know where to hard code a DNS server permanently.

### Steps to Reproduce

1. Install 1.1.0 or 1.1.1 
2. Try and pull an image from internal or external registries
3. Will generate a tcp: lookup error as DNS is malfunctioning

### Result

Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.68.6:53: read udp 192.168.68.6:47222->192.168.68.6:53: i/o timeout.

### Expected Behavior

dockerd or containerd can pull images

### Additional Information

Looked at #1722 but that is the resolv.conf for dnsmasq being lost.  This is more about the .1 endpoint provided by Hyper-V doesn't send traffic up the correct pipe so DNS is broken.  Workaround for statically configuring resolv.conf may conflict with the move to dnsmasq.

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

W10 1909 18363.2037

### What CPU architecture are you using?

x64

### Windows User Only

VPN and Proxy in Play

VPN conflict w Microsoft's WSL init is at fault, but workaround is trivial if the hard code isn't wiped.

**Comment by Nino-K** [comment]
@byjrack currently dnsmaq uses wsl DNS as an upstream so the reliability of cascading name resolution really comes down to how reliable wsl DNS is, and it is clear that it is not very reliable. This issue is being discussed as we speak, we may have to do some fundamental changes in the way DNS is being handled to tackle this issue. One potential option could be running the DNS server on the Host and setup an additional interface on the guest, that way we can eliminate the dnsmasq and bypass the wsl DNS altogether.

**Comment by byjrack** [comment]
Yeah in my case the auto-detection of DNS is always going to be a mess as the VPN does confuse the routing.  I bucket this one in with proxies where just allowing the user to update some host level config to set envs and settings like dns.  Looking at wsl.ts it seems to indicate that the resolv is sourced from data-distro so just toying with how to mount that and hard code it there.

**Comment by Nino-K** [comment]
@byjrack thanks for the additional context. 

> _Yeah in my case the auto-detection of DNS is always going to be a mess as the VPN does confuse the routing._

As for the detection of the DNS while on VPN we have done some [work](https://github.com/rancher-sandbox/rancher-desktop/pull/1592) in our previous release. We added a process that detects the most suitable interface that handles DNS resolutions while on VPN. Although this work is not fully wired in yet, it should handle the DNS resolutions in a full VPN tunnel scenario. For a split VPN tunnel, we would still need to do some work.

**Comment by byjrack** [comment]
Yeah we use a split to avoid realtime traffic from needing to hairpin through our private network to reach the UC and other latency sensitive systems.  So just scoping to the default gw can be a bit hit or miss.

If the logic is available I can try to poke at it and see how it functions with some pointers to how to hook it.  I will say that however Lima is handling it on the Mac seems to be playing nice with the route table shenanigans.  

To unblock Windows my understanding is that resolv is sourced from the busybox based data distribution as data-resolv-conf in dnsmasq.d.  Is there a process to edit that persisted data so I could get back to the hard coded DNS that isn't reset?

**Comment by jandubois** [comment]
> however Lima is handling it on the Mac seems to be playing nice with the route table shenanigans

That's good to hear! We are planning to move the lima host resolver code to a standalone daemon and run it on Windows, so all names would be looked up in the host context, and not inside the VM. Hopefully this will work out; then it will be in the following release...

**Comment by bvanhorick** [comment]
On my side (Corporate computer on Windows), I was also facing the DNS issue preventing my from pulling images both in docker and k8s.
I found a single step to work around this issue: I disable the Windows Firewall on Public Profile for WSL Interface.
In an admin Powershell: Set-NetFirewallProfile -Name Public -DisabledInterfaceAliases "vEthernet (WSL)"
It seems the DNS resolution is blocked when it tries to it the Windows Host DNS as the firewall prevent it.
After this change, I can pull images from WSL via Docker or in K8S.
Hope this helps...

**Comment by byjrack** [comment]
Hadn't thought of that as I had been heard coding for so long, but it makes sense.  I did give it a shot in my case and it wasn't able to resolve the issue, but we have layers of security software running so who knows if the traffic is just hitting another gate.

It also started flagging as insecure by Windows Security so I am sure someone from my security team would have tracked me down at some point.  I wonder if just adding an Allow on All:53 would have the same result without setting off the alarms.

**Comment by bvanhorick** [comment]
Sorry to hear it doesn't work for you, it seems this issue may encounter various gates indeed. I had to diagnose a lot with nslookup to discover at which level it blocked on my side.

You're right, Windows Security flag this as insecure and I've seen requests to make it possible to add the WSL Interface private instead of Public which could probably solve the issue at some point too. But, in my case, this was the "easiest" way to make things work. 
I previously tried with various rules in Windows Firewall without success.

**Comment by rtroch** [comment]
To add on top of this issue i am experiencing similar problems. I have RD 1.1.1 on Mac M1 and cannot build my app because of random network-loss during image build time. Sometimes it fails to resolve `github.com` sometimes it times out downloading libraries because it cannot resolve `rubygems.org`. There seem to be similar issues on the `lima-vm` repository as well. Is there any workaround or am i forced to downgrade to 1.0.1?

**Comment by Nino-K** [comment]
@byjrack There is a [PR](https://github.com/rancher-sandbox/rancher-desktop/pull/1576) that got merged in a while ago which allows you to add provisioning scripts. I believe the script should persist after the restart, can you please see if this could help you out.

**Comment by byjrack** [comment]
Missed that feature.  Let me read up on it to think through how best to hook that, but agree that looks like a great way to handle the environmental nuances much like override.yml in lima.

Do you want me to leave this Issue open for the larger area/dns refinement work if I can track down a script that ticks the boxes (which I will post back here)?

**Comment by Nino-K** [comment]
Sure, let's leave it open for now.  Also, your feedback/workaround would be great if you could kindly share it here.

**Comment by byjrack** [comment]
So using provisioning scripts worked great for DNS.

%APPDATA%\rancher-desktop\provisioning\dns.start
```
#!/bin/ash
echo "nameserver <private dns ip>" >> /etc/dnsmasq.d/data-resolv-conf
```

- I leave the "autoConfig" resolver in there as it fails quick so it's minimal cost
- Watch out for Windows Notepad for authoring as its carriage returns seemed to throw things off when run 
   - Use an editor that can handle that case or you can jump into WSL and follow the symlink at /etc/local.d and use vi
- Tried to tack on some exports for Proxy stuff, but that didn't fly
  - #1770 is probably part of the issue, but going to look at creating /etc/environment and rc_env_allow though again feels like timing might be an issue

**Comment by Nino-K** [comment]
@byjrack thanks for the update and glad that worked for you. I will go ahead and close the issue, however, feel free to re-open at any point.

**Comment by Nino-K** [comment]
@rtroch there is an issue for Mac specific to M1 [here](https://github.com/rancher-sandbox/rancher-desktop/issues/1633), please take a look. Thanks.

**Comment by byjrack** [comment]
Only ask @Nino-K would be if the team has used provisioning scripts to handle proxy env for containerd and dockerd.  I have not been able to get the timing right even using rc-service restarts and /etc/profile just yet.  The startup flow and env handling is still a bit fuzzy for me.

**Comment by byjrack** [comment]
For those who find this issue I also have been working with our Cybersecurity team as I was seeing DROPs in the client firewall logs when not using a hard coded DNS server.  Note our rules are policy based so local rules in the client firewall won't be effective (eg Rancher can't fix it by adding rules itself) so check with your own cybersecurity team.  WSL does create a set of rules following the naming "HNS Container Networking - DNS (UDP-In) - UUID" in the local rules table which should work, but unless you are merging local rules those will not effect the DROPs most likely.

- Local Port: UDP/53 and Remote: Any
  - The DROPs were on the Hyper-V switch gateway IP to the WSL instance IP's ephemeral port on the reply from DNS
- Local IPs: RFC1918 addresses
  - WSL2 does not allow for configuring private IPs (like the old 10.0.75.0/28 Docker subnet) so it will test and allocate based on what doesn't create a route collision meaning the rule scope is large, but not internet routed.
- Remote IPs: Local subnets
  - This aggregate allows for scoping destinations based on the the network adapter gateways on the client
- Program: Internet Connection Sharing (ICS) [aka SharedAccess]
  - Firewall allows for scoping to processes so whether it is svchost.exe SharedAccess or the Service registration you can scope it to only that Process which is handling the NAT traffic for Hyper-V
- Users: SYSTEM
  - ICS is run from the SYSTEM process so you can target that User though combined with the svchost control you are overlapping the efficacy heavily at this point.

**Comment by Nino-K** [comment]
@byjrack this is great information. Thanks for sharing this.
