### ISSUE TITLE
Build an HTTP server listening on port 6107, bound to 0.0.0.0.

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1753]
The server will listen on a fixed TCP port (e.g. 6107) and bind to 0.0.0.0, so automation can connect to a Rancher Desktop instance running on a remote server, e.g. in a cloud service. It will use basic auth with a fixed username (e.g. user) and a randomly generated password. The port and password will become configurable at a later point.

The app will create an rd-engine.json file with 0600 filemode that contains: port, user, password, pid. The CLI will read this file to be able to connect to the API.

**Comment by AkihiroSuda** [comment]
I'd expect this to be opt-in, or at least it should default to use a local UNIX socket.

> It will use basic auth with a fixed username (e.g. user) and a randomly generated password. The port and password will become configurable at a later point.

With TLS, right?
I'd also suggest use mTLS rather than password.

**Comment by jandubois** [comment]
> I'd expect this to be opt-in, or at least it should default to use a local UNIX socket.

Why does this need to be opt-in, as long you need authorization? UNIX sockets are not available on Windows, so you would need to create some named pipe mechanism. Sounds like a lot of work for little gain.

> > It will use basic auth with a fixed username (e.g. user) and a randomly generated password. The port and password will become configurable at a later point.
> 
> With TLS, right? I'd also suggest to use mTLS rather than password.

That is a good point. I think we should rather only bind to `127.0.0.1` at first, both to get a prototype into the next release, and for ease-of-use from the commandline.

**Comment by AkihiroSuda** [comment]
> UNIX sockets are not available on Windows

Available since 2017
https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

**Comment by jandubois** [comment]
> Available since 2017

Yeah, but don't work with WSL2 afaict: https://github.com/microsoft/WSL/issues/5961
