### ISSUE TITLE
Incorporate Dashboard rebrand when it becomes available

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#176]
And also incorporate the new logo and colours.

**Comment by mook-as** [comment]
Abbreviated steps to test the new dashboard:
- Run RD
- Install following the [docs](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/) (use latest, default self-signed cert)
- Edit the service (`cattle-system:rancher`) to be NodePort
- Run dashboard in [development mode](https://github.com/rancher/dashboard#running-for-development), using `API=https://<development VM IP>:<service http port>`
