### ISSUE TITLE
Rancher Desktop gets stuck on "Waiting for Kubernetes API" on Windows since Rancher Desktop v1.1.1

### ISSUE THREAD

**Issue by MaxStroh** [rancher-sandbox/rancher-desktop#1762]
### Actual Behavior

Since the update of Rancher Desktop to v1.1.1, Rancher Desktop gets stuck on "Waiting for Kubernetes API" on start-up. I tried different Kubernetes Versions (each down to v.1.20.15), restarted Rancher Desktop completely and restarted it, but gets stuck everytime.

### Steps to Reproduce

1. Start Rancher Desktop (v1.1.1) on Windows (10)
2. Wait for Rancher Desktop to start-up
3. It gets stuck on "Waiting for Kubernetes API"

Rancher Desktop FAQs told me to open an issue (https://docs.rancherdesktop.io/faq/#q-rancher-desktop-is-stuck-on-waiting-for-kubernetes-api-what-do-i-do) ;)

### Result

Just the loading bar in the lower left corner, saying "Waiting for Kubernetes API". No Error, no warning.

### Expected Behavior

Rancher Desktop is able to start-up.

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

I tried every version between 1.23.4 and 1.20.15

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Business 21H2

### What CPU architecture are you using?

x64

### Windows User Only

No VPN, no proxy, firewall rules are managed over the organization, ESET as security software - but nothing of this changed since last week, where I used Rancher Desktop successfully in v1.1.0 on the same device with the same settings.

**Comment by ericpromislow** [comment]
I didn't see anything unusual in the supplied log files. Where it gives warnings and error messages, I see the same in my working Windows deployment. Before taking the last resort of a factory reset, I would disable Kubernetes (in the Kubernetes Settings panel), restart, and then re-enable it and restart again. Does that help at all?

**Comment by MaxStroh** [comment]
Unfortunately I cannot edit the checkbox of "Enable Kubernetes" in the Kubernetes Settings while Rachner Desktop is starting (which it automatically does on opening and at which it gets stuck) - so I can not disable or reset Kubernetes over the Kubernetes Settings.

**Comment by MaxStroh** [comment]
But a factory reset should help? I would try that out before uninstalling v1.1.1 and reinstalling v1.1.0 again to see whether the older version works.

**Comment by ericpromislow** [comment]
Here's a workaround to disable Kubernetes:

* Shut down Rancher Desktop.
* Edit the preferences file. I don't have a Windows machine at hand right now, but it should be at `%HOME%/AppData/Roaming/rancher-desktop/settings.json`.
* Set `kubernetes.enabled` to `false`
* Save changes and restart Rancher Desktop.

**Comment by GRathnaMadhuri** [comment]
Can you Elaborate how you solved the issue , I am also facing same issue as your

**Comment by RaiArxlan** [comment]
I am also facing this issue on v1.19.1 on Windows 11 Enterprise. I waited 3+ hours for it was still stuck there.
