### ISSUE TITLE
Support cross-arch containers

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1764]
### Problem Description

This command worked fine (macOS / M1) when I used Docker Desktop before migrating to Rancher Desktop:
```
docker run --platform amd64 busybox
```

w/ Rancher Desktop (1.1.1), I get:
```
% docker run --platform amd64 busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
Digest: sha256:34c3559bbdedefd67195e766e38cfbb0fcabff4241dbee3f390fd6e3310f5ebc
Status: Image is up to date for busybox:latest
docker: Error response from daemon: image with reference busybox was found but does not match the specified platform: wanted darwin/amd64, actual: linux/amd64.
See 'docker run --help'.
```

For perspective, I've been told `colima` supports this feature:
https://github.com/abiosoft/colima/issues/165#issuecomment-1030707418

### Proposed Solution

Apparently, Docker Desktop and colima implement this using qemu. This seems like the natural approach.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jandubois** [comment]
> This command worked fine (macOS / M1) when I used Docker Desktop before migrating to Rancher Desktop:
> 
> ```
> docker run --platform amd64 busybox
> ```

Are you sure? I don't have a setup to test, but I suspect it will have the same issue as Rancher Desktop:
 
> w/ Rancher Desktop (1.1.1), I get:
> 
> ```console
> % docker run --platform amd64 busybox
> Unable to find image 'busybox:latest' locally
> latest: Pulling from library/busybox
> Digest: sha256:34c3559bbdedefd67195e766e38cfbb0fcabff4241dbee3f390fd6e3310f5ebc
> Status: Image is up to date for busybox:latest
> docker: Error response from daemon: image with reference busybox was found but does not match the specified platform: wanted darwin/amd64, actual: linux/amd64.
> See 'docker run --help'.
> ```

As the error message shows, you are requesting a `darwin/amd64` image (which doesn't exist). You should ask for `linux/amd64`, which works fine:

```console
jan@zilicon ~ % uname -a
Darwin zilicon.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:45 PST 2022; root:xnu-7195.141.19~2/RELEASE_ARM64_T8101 arm64

jan@zilicon ~ % docker run --platform linux/amd64 busybox uname -a
Linux 65d7277a23c5 5.10.93-0-virt #1-Alpine SMP Thu, 27 Jan 2022 09:34:38 +0000 x86_64 GNU/Linux

jan@zilicon ~ % docker run --platform linux/arm64 busybox uname -a
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
f4731b18983e: Pull complete
Digest: sha256:34c3559bbdedefd67195e766e38cfbb0fcabff4241dbee3f390fd6e3310f5ebc
Status: Downloaded newer image for busybox:latest
Linux 08947390ed7c 5.10.93-0-virt #1-Alpine SMP Thu, 27 Jan 2022 09:34:38 +0000 aarch64 GNU/Linux
```
 
> For perspective, I've been told `colima` supports this feature: [abiosoft/colima#165 (comment)](https://github.com/abiosoft/colima/issues/165#issuecomment-1030707418)

Yes, it does, because it uses a fork of the Alpine Lima image for Rancher Desktop, that implements this...

> ### Proposed Solution
> Apparently, Docker Desktop and colima implement this using qemu. This seems like the natural approach.

We are all using same code from Docker developer Tõnis Tiigi: https://github.com/tonistiigi/binfmt. All glory belongs to him! 😄

**Comment by jsoref** [comment]
Oops. 🤦
