### ISSUE TITLE
Traefik Dashboard does not load

### ISSUE THREAD

**Issue by nunix** [rancher-sandbox/rancher-desktop#1779]
### Actual Behavior

The Traefik dashboard is not reachable and the page displays an error `404 page not found`

### Steps to Reproduce

After a fresh install of Rancher Desktop, try opening http://localhost/dashboard/
It will display the `404` error message

### Result

Page displays `404 page not found`

### Expected Behavior

The Traefik dashboard is loaded and displayed via the URL http://localhost/dashboard/

### Additional Information

This issue has been reported on Slack (https://rancher-users.slack.com/archives/C0200L1N1MM/p1646832761734359) and after some testing, I could find a workaround for this issue:

1. The issue seems to be due to a misconfiguration of the default `IngressRoute` created by Traefik helm chart
2. When I change the `entryPoints` from `traefik` to `web`, the dashboard could be loaded without issues.
3. here is the YAML portion I changed:
```yaml
...
spec:
  entryPoints:
  - web
...
```
4. The URL used during the tests was `http://localhost/dashboard/`

I tried this workaround on the three OS and it worked fine. Please note that for Linux, I used the AppImage and due to the limitation of the ports opening (rootless mode), I used the port exposed by the Traefik service.

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

v1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Windows User Only

Nothing extra used. Personal laptop without VPN or domain set (workgroup).

**Comment by nunix** [comment]
@gunamata this will work "too" indeed. I actually asked the user in Slack to do it first. However the point here is that there's a configuration already done out of the box, where we do have an `IngressRoute` and should be able to use it.

It seems as a misconfiguration, but if it's installed "as it should", then it's all good to close this issue as the solution is already mentioned in the FAQ.

**Comment by gunamata** [comment]
yeah. As traefik comes bundled with k3s, it would make more sense to update the configuration upstream to enable the dashboard.  Closing this issue as we have one possible configuration steps covered in [FAQ]( https://docs.rancherdesktop.io/faq#q-how-can-i-enable-the-dashboard-for-the-traefik-ingress-controller)
