### ISSUE TITLE
Support hitting the Windows server with `rdctl` from a WSL partition

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1780]

**Comment by ericpromislow** [comment]
from slack:
indeed, there's no "reverse port mapping" form Windows to WSL > as discussed before, you'll need to use netsh portproxy ...

**Comment by jandubois** [comment]
Idea: Let the server listen on `0.0.0.0`, but check the source IP address. If it is neither `127.0.0.1` nor the VM IP, then return 403 Forbidden.

We do something similar in Lima to bind to privileged ports on localhost: for some reason macOS allows you to bind to `0.0.0.0:80` as a regular user, but you must be `root` to bind to `127.0.0.1:80`. So we bind to all interfaces, but reject connections from anything but localhost.

@mook-as What do you think?

**Comment by jandubois** [comment]
> We should check the _destination_ address, but that should work, I think. (Do it that way because an attacker might be able to convince the network to accidentally route to an internal address on an external interface. But that would still have a _destination_ of the external address.)

I don't understand how this would work. We do want to accept connections on the external address, but only if they come from localhost or the IP of our VM. If we check the destination address and reject connections from the external address, then we are in the same place as just binding to localhost, because we are now rejecting connections from the VM, no?

I don't understand your "attacker" scenario at all. Can you spell it out with the different interfaces involved?

Note that an external attacker would still need to be able to authorize, even if they could connect. But since authorized connections can no longer go over an external network, there should be no way to snoop on the token.

**Comment by mook-as** [comment]
I thought we wanted to listen on `0.0.0.0` (i.e. everywhere), but only accept the connection if it was made on either the loopback interface (`127.0.0.1`) or the WSL interface (`172.?.?.1`).

In the past, I've somehow managed to run `traceroute` to a `192.168.x` address and managed to get a response over the internet before (while troubleshooting other network issues), so while that _shouldn't_ happen, I would prefer to not trust the routing table to not have shenanigans.  Looking at the destination address (that is, the local address) doesn't involve any routing, so it's less likely to have issues.

Maybe it's fine? I don't know :)

**Comment by jandubois** [comment]
> I thought we wanted to listen on `0.0.0.0` (i.e. everywhere), but only accept the connection if it was made on either the loopback interface (`127.0.0.1`) or the WSL interface (`172.?.?.1`).

Yes, that is my understanding.
 
> In the past, I've somehow managed to run `traceroute` to a `192.168.x` address and managed to get a response over the internet before (while troubleshooting other network issues), so while that _shouldn't_ happen, I would prefer to not trust the routing table to not have shenanigans. Looking at the destination address (that is, the local address) doesn't involve any routing, so it's less likely to have issues.

I don't understand how the destination address is helping us. When the connection comes from the WSL interface, the destination address will be the host external address. So what do we do now?

If we block, then connections from the WSL interface will not work, so we could have just listened on `127.0.0.1` instead.

If we don't block, how do we know this connections doesn't come from the outside without looking at the source address.

If we make the decision to block or not based on the source, then why do we look at the destination?

So I still don't understand how this would work.

**Comment by mook-as** [comment]
> I don't understand how the destination address is helping us. When the connection comes from the WSL interface, the destination address will be the host external address. So what do we do now?

Umm, wouldn't it be the WSL vEthernet address (typically 172.something.1)? That would be distinct from the external network address (what eth0/wl0 would be, had this been Linux).

**Comment by jandubois** [comment]
> wouldn't it be the WSL vEthernet address (typically 172.something.1)?

If that is the case, then it would indeed work, and I was confused in that I expected it to go through the external interface.

**Comment by jandubois** [comment]
This issue has been superseded by #2327 (create rdctl vtunnel)
