### ISSUE TITLE
"no required module provides package github.com/.../pkg/dockerproxy/models"

### ISSUE THREAD

**Issue by saliej** [rancher-sandbox/rancher-desktop#1799]
### Actual Behavior

When I try to build in Windows 10 (Powershell), the build fails with the following error:

> Client-side fallback created: 200.html                                                    12:03:10
pkg\dockerproxy\serve.go:38:2: no required module provides package github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models; to add it:
        go get github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models
pkg\dockerproxy\serve.go:38:2: no required module provides package github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models; to add it:
        go get github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models
Error: Process exited with code 1
    at ChildProcess.<anonymous> (file:///C:/dev/rancher-desktop/scripts/lib/build-utils.mjs:97:18)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

It seems that the **wsl-helper** package was moved to the **go** subfolder, but even under there there is no **models** package.

### Steps to Reproduce

In Powershell on Windows 10, run in the repo root:
`npm run build`

### Result

Observe the following error:

> √ Client-side fallback created: 200.html                                                    12:03:10
pkg\dockerproxy\serve.go:38:2: no required module provides package github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models; to add it:
        go get github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models
pkg\dockerproxy\serve.go:38:2: no required module provides package github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models; to add it:
        go get github.com/rancher-sandbox/rancher-desktop/src/wsl-helper/pkg/dockerproxy/models
Error: Process exited with code 1
    at ChildProcess.<anonymous> (file:///C:/dev/rancher-desktop/scripts/lib/build-utils.mjs:97:18)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

### Expected Behavior

The build should succeed.

### Additional Information

`go version go1.18rc1 windows/amd64`

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

None

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise, 10.0.19043

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
Hmm, did you run `npm install` first? That triggers `go generate` under `wsl-helper`, which builds the `models` package via `go-swagger`.

**Comment by saliej** [comment]
> Hmm, did you run `npm install` first? That triggers `go generate` under `wsl-helper`, which builds the `models` package via `go-swagger`.

I managed to trace the issue to a restrictive corporate group policy. It seems I can only build successfully on a specific user account. There are still a few superficial issues when it tries to download and copy `kuberlr.exe` but I can just bypass that manually.
