### ISSUE TITLE
Kubernetes Error after Mac OS upgrade to 12.3

### ISSUE THREAD

**Issue by erniekim** [rancher-sandbox/rancher-desktop#1812]
### Actual Behavior

An error occurred after installing the package and initializing the system.

### Steps to Reproduce

Precondition: MacOS 12.3
Install the rancher desktop with options
- Kubernetes: 1.22.7(stable)
- containerd

### Result

An error occurred after installing the package and initializing the system.

### Expected Behavior

Complete to initialize the rancher desktop normally.

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.3

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by erniekim** [comment]
<img width="935" alt="스크린샷 2022-03-15 오후 3 41 36" src="https://user-images.githubusercontent.com/25345608/158322221-dac7f61c-9f97-4874-aabb-fed6cedf5b6b.png">

Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

Last command run:
limactl start --tty=false 0

Context:
Starting virtual machine

Some recent logfile lines:
time="2022-03-15T15:48:06+09:00" level=info msg="Using the existing instance \"0\""
time="2022-03-15T15:48:06+09:00" level=info msg="Starting switch daemon for \"bridged_en0\" network"
time="2022-03-15T15:48:06+09:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-15T06:48:06.269Z: + limactl start --tty=false 0
2022-03-15T06:48:06.270Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-15T06:48:06.272Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

**Comment by erniekim** [comment]
<lima.log>
2022-03-15T06:51:20.434Z: Running command limactl list --json...
2022-03-15T06:51:20.582Z: Running command limactl stop --force 0...
time="2022-03-15T15:51:20+09:00" level=info msg="The QEMU process seems already stopped"
time="2022-03-15T15:51:20+09:00" level=info msg="The host agent process seems already stopped"
time="2022-03-15T15:51:20+09:00" level=info msg="Removing *.pid *.sock under \"/Users/younghokim/Library/Application Support/rancher-desktop/lima/0\""

**Comment by pawelpogorzelski** [comment]
Same here. Intel arch. Right after macOS upgrade to 12.3 the same errors, not allowing cluster to come online

**Comment by rbrtmrln** [comment]
had the same problem after macos 12.3 update (intel arch).

could make it work again by giving group write permissions (not sure if this is correct though):

```sh
sudo chmod g+w /private/var/run/rancher-desktop-lima
```

**Comment by erniekim** [comment]
@rbrtmrln 
Thanks. After giving group write permissions, it doing well.

**Comment by pawelpogorzelski** [comment]
IMHO this bug should remain open as the "fix" is temporary (at least in my situation) - till the next reboot, and you have to do  the process again.

**Comment by NPuhlmann** [comment]
same error ARM on Mac OS after update to 12.3

**Comment by jandubois** [comment]
> IMHO this bug should remain open as the "fix" is temporary

@pawelpogorzelski You are right, that is not a fix, it is a workaround. #1815 is a duplicate of this issue and is still open (and includes a root cause analysis). This issue should not affect our next release, as we'll no longer even create the directory (to avoid the `sudo` prompt after each reboot). Once this has been verified we'll close #1815 as well.

We are planning to have a new release next week that will include these changes.
