### ISSUE TITLE
Store passwords in Keychain

### ISSUE THREAD

**Issue by pboushy** [rancher-sandbox/rancher-desktop#1819]
### Problem Description

When running `docker login` it outputs:

```
WARNING! Your password will be stored unencrypted in /Users/<username>/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

This is insecure. It would be better if the data was stored in the macOS keychain.

### Proposed Solution

Please store passwords in the keychain and pass the password through to docker.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jandubois** [comment]
#1699 exist for bundling the helpers; not sure if/where we would configure it, or leave it to the user.

You can easily set this up right now by installing the helpers with e.g. `brew install docker-credential-helper` and configuring them in `~/.docker/config.json`.

Also note that this is mostly about encryption at rest. While you are logged in, the credentials are still available to an unprivileged attacker:

```console
$ docker-credential-osxkeychain list
{"https://registry.home":"user"}
$ echo "https://registry.home" | docker-credential-osxkeychain get
{"ServerURL":"https://registry.home","Username":"user","Secret":"password"}
```

**Comment by jandubois** [comment]
#2013 covers configuration of the credential helpers
