### ISSUE TITLE
Kubernetes error downgrading Rancher Desktop from CI build to most recent release version

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1824]
### Actual Behavior

If you are testing CI build and if auto upgrade option is selected in your session, the UI prompts you that an upgrade is available, which is expected behavior. 

If you accept the upgrade, the app goes back to the latest release version and during the relaunch runs into a kubernetes error.

### Steps to Reproduce

- Ensure `Check for updated automatically`
- Download, Install and launch latest CI build from Github
- On launch, the UI asks you to upgrade. Follow the UI prompts to upgrade.

You will land into the kubernetes error.

### Result

Kubernetes error.

![image](https://user-images.githubusercontent.com/59538726/158645032-e80684fd-85e4-4aa5-88d1-7cb0423e3541.png)

### Expected Behavior

We should be able to downgrade to the latest release version from a CI build install.

### Additional Information

Workaround: Doing `Factory Reset` lets you continue with the latest release version.

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.21.0

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Windows User Only

No

**Comment by mook-as** [comment]
This is expected (due to a change in the k3s version caching), and there's nothing much we can do unless we decide to ship a point release.  This should not be an issue going forward (we added a version field to the cache).

I don't believe we pretend to support downgrades?

**Comment by gunamata** [comment]
Thanks @mook-as 
Yes, we don't support downgrades and expect our users to be on the latest version. This is just an annoyance for those of us who switch between CI builds and release versions while testing things.  I will close this when the next release comes out with the cache handling change.

**Comment by gunamata** [comment]
This one seems to have got fixed in the recent 1.2.1 release. I could downgrade from CI build (1.2.0-137-geb635209) to 1.2.1 with out any issue. So, Closing this.
