### ISSUE TITLE
Put the docker socket into ~/.rd/docker.sock

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1841]
Right now the docker socket is created at `$HOME/Library/Application Support/rancher-desktop/lima/0/sock/docker`.

Using `sudo` we create a symlink to `/var/run/docker.sock`.

Since we are already planning to create `~/.rd/bin/` for supporting utilities and `~/.rd/lima` for the `LIMA_HOME` directory (to have more space for socket names when the user name is long), it makes sense to place the docker socket into the same location: `~/.rd/docker.sock`.

**If** we have `sudo`, we should create a symlink at `/var/run/docker.sock`.

---
Edited by @mook-as: removed docker context stuff, that's covered by #910.

**Comment by jandubois** [comment]
Just wanted to record that https://github.com/rancher-sandbox/rancher-desktop/blob/11cf6308e758f854e8d67c830a38b5de5c62101f/src/k8s-engine/lima.ts#L611 can be changed to

```go
    hostSocket: '{{.Home}}/.rd/docker.sock',
```

Lima will do the template expansion, but the directory must exist.

**Comment by mook-as** [comment]
Hmm, if `LIMA_HOME` is already going to be `~/.rd/lima`, is there a point in moving the docker socket from `~/.rd/lima/0/sock/docker` to `~/.rd/docker.sock`?

**Comment by jandubois** [comment]
> is there a point in moving the docker socket from `~/.rd/lima/0/sock/docker` to `~/.rd/docker.sock`?

We will still need to make the location of the data volume configurable, for users who are out of space on their boot volume and want to move it to a mounted disk. But I guess we could just move the `~/.rd/lima/0/diffdisk` file and replace it with a symlink instead of moving `LIMA_HOME` (and dealing with max socket path length again).

So, not sure yet. I kind of prefer `DOCKER_HOST=unix://$HOME/.rd/docker.sock` over including implementation details in our docs.

I was also thinking that we would only create `~/.rd/lima` for new installations and not try to move an existing directory. E.g. some people already replaced the directory with a symlink to deal with the socket name length issue, and it seems like just keeping existing installs as-is is the safer option. But I would still want to move the docker socket.

**Comment by mook-as** [comment]
> I was also thinking that we would only create ~/.rd/lima for new installations and not try to move an existing directory. 

Please definitely not this; this adds a lot of complexity, makes troubleshooting harder, and we should solve it differently. Given that we shouldn't have access to user systems, the less moving parts the better.

> We will still need to make the location of the data volume configurable, for users who are out of space on their boot volume and want to move it to a mounted disk. But I guess we could just move the `~/.rd/lima/0/diffdisk` file and replace it with a symlink instead of moving `LIMA_HOME` (and dealing with max socket path length again).

How do you feel about:
- Don't move the docker socket at all;
- Go straight to #910 and add a `rancher-desktop` docker context;
- If we have permissions, _also_ make `/var/run/docker.sock` a symlink to our socket as current

This way, the documentation would just be "use the docker context; if your application doesn't support docker contexts, set `DOCKER_HOST` to the value in the context".

(That said, I already have local changes that are almost PR-able for this, but I wanted to confirm that's what we _actually_ want long term before PRing…)

**Comment by jandubois** [comment]
> Please definitely not this; this adds a lot of complexity, makes troubleshooting harder, and we should solve it differently. Given that we shouldn't have access to user systems, the less moving parts the better.

We have postponed a decision on this pending further discussion.

@mook-as and I agreed on using `~/.rd/docker.sock` as the socket name.
