### ISSUE TITLE
rdctl command reference docs

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1870]
### Problem Description

Command reference docs for the newly added rdctl

### Proposed Solution

Add `rdctl command reference`  doc to Rancher Desktop docs

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by ericpromislow** [comment]
Currently supported commands (shipping with version 1.2.0):

```
list-settings   - Lists the current settings.
set OPTIONS - Update selected fields in the Rancher Desktop UI and restart the backend.
OPTIONS include at least one of:
      --container-engine string     Set engine to containerd or moby (aka docker).
      --kubernetes-enabled          Control whether kubernetes runs in the backend.
      --kubernetes-version string   Choose which version of kubernetes to run.
shutdown      - Shuts down the running Rancher Desktop application
```

Also code-completion can be generated for a few shells by running
`rdctl completion SHELL > FILE`.

For example:
```
rdctl completion bash > rdctl.sh
source rdctl.sh
rdctl <TAB>
```

Run `rdctl completion -h` for a list of supported shells.

**Comment by gunamata** [comment]
https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/53 adds a doc with the commands added in last release (1.2.1). Closing this issue.  We will add new issues to update the https://docs.rancherdesktop.io/references/rdctl-command-reference, as and when we add/modify `rdctl` commands.
