### ISSUE TITLE
First Time Run, Kubernetes Error

### ISSUE THREAD

**Issue by davaba86** [rancher-sandbox/rancher-desktop#1875]
### Actual Behavior

After just removing Docker and successfully installing Rancher Desktop through brew I fails immediately once I type the correct user password.

```
❯ brew install rancher
==> Downloading https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.1.1/Ranc
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65b
######################################################################## 100.0%
==> Installing Cask rancher
==> Moving App 'Rancher Desktop.app' to '/Applications/Rancher Desktop.app'
🍺  rancher was successfully installed!
```

### Steps to Reproduce

Start the application, first time.

### Result

<img width="800" alt="image" src="https://user-images.githubusercontent.com/72309434/159680686-7bc720fd-a5e5-480c-9d44-fc68e78a0119.png">

Code lines below:
```
time="2022-03-23T11:33:40+01:00" level=info msg="Using the existing instance \"0\""
time="2022-03-23T11:33:40+01:00" level=info msg="Starting switch daemon for \"shared\" network"
time="2022-03-23T11:33:40+01:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-23T10:33:40.791Z: + limactl start --tty=false 0
2022-03-23T10:33:40.791Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-23T10:33:40.792Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

### Expected Behavior

I wish to be able to run the application on a first try.

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.22.7(stable)

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

12.3

### What CPU architecture are you using?

x64

**Comment by davaba86** [comment]
Closing it down, saw another duplicate.

https://github.com/rancher-sandbox/rancher-desktop/issues/1815

**Comment by vaibhavkumar049** [comment]
@davaba86 worked for you?
