### ISSUE TITLE
Epic: CLI Part 2

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1896]
This continues the CLI Ecosystem Epic from #1748.

This second epic focuses on providing commands that are required to use `rdctl` for testing Rancher Desktop itself.

The API version should remain at `v0` and we will still consider the CLI experimental until we have redesigned the `list-settings` command to provide human-readable output that matches settings to the options that can be specified in the `set` command.

- [x] #1897
- [x] #1903
- [x] #1944
- [x] #1945
- [x] #1222
- [x] #2006
- [x] #1904
- [x] #1870

These tasks are probably not going to make it into the next release:

- [ ] #1974
- [ ] Add `rdctl wait` command
- [ ] #2063

The `start` and `shell` command don't use the REST API, but native host features, to perform their tasks.

**Comment by jandubois** [comment]
Will create a new Epic for the remaining tasks.
