### ISSUE TITLE
Can't connect to localhost using host.docker.internal

### ISSUE THREAD

**Issue by sousarmb** [rancher-sandbox/rancher-desktop#1909]
### Actual Behavior

Trying to connect to azure mssql within docker container. Bitvise client is running on windows host, bound to all interfaces (0.0.0.0) on port 1435. Trying to access it using `tsql` with host parameter `host.docker.internal` port 1435 but times out after +/- 2 minutes, bitvise logs show no communication attempts. If i try to connect directly to the database IP address the connection is established but access is denied as per server access rules (IP address not allowed to connect).

### Steps to Reproduce

Install Rancher Desktop, updated to 1.2.1.

Built container with `net=host` or `net=bridge` or not setting it at all

Run:
- `tsql -H host.docker.internal -p 1435 -U [user] -P [password] -D [database]`
- `tsql -H host.rancher-desktop.internal -p 1435 -U [user] -P [password] -D [database]`
- `tsql -H host.rancher-desktop.internal -p 1435 -U [user] -P [password] -D [database]`
- `tsql -H 127.0.1.1 -p 1435 -U [user] -P [password] -D [database]`

WSL2 is used

### Result

`tsql` times out or refuses to connect.

### Expected Behavior

Login to the database server and query databases

### Additional Information

![Untitled](https://user-images.githubusercontent.com/13436535/160370826-b1b77877-0ca3-4c36-9967-17147bd0ae02.png)

Routing info inside Rancher Desktop host

![Untitled](https://user-images.githubusercontent.com/13436535/160408236-8edebb34-f295-4b6b-943b-0c14359441af.png)

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise, build 19044

### What CPU architecture are you using?

x64

### Windows User Only

Custom defined VPN

**Comment by mook-as** [comment]
Hi there!

The `host.docker.internal` / `host.rancher-desktop.internal` addresses currently map to the host machine's `vEthernet (WSL)` interface; if your application is listening on that interface things should work (barring firewalls and conflicting subnets).

In your first screenshot, though, it shows that (if I'm reading this correctly) port 1435 (the censored row) is bound to `127.0.0.1` instead; that interface would not be visible inside Rancher Desktop (as there's a VM involved, as managed by WSL).

**Comment by ebenitez1** [comment]
Hello,
I am having the same issue as well but for port 34441 via IIS Express and Visual Studio. In Docker Desktop, I set the url to be http://host.docker.internal:34441/ and it's able to connect fine. If I do this same thing in Rancher Desktop, regardless of if using docker or k8s, it is unable to connect.

**Comment by tarrinho** [comment]
Hello,
Same error here: host.docker.internal
![image](https://user-images.githubusercontent.com/1039120/161274848-c2a5dfa7-b866-4bd8-bc83-89ace6492b1b.png)
host.rancher-desktop.internal
![image](https://user-images.githubusercontent.com/1039120/161274968-d1fda257-b2fb-40d9-84ac-20fefc2cd09d.png)

However, if I use either the internal IP (between the host and docker):
![image](https://user-images.githubusercontent.com/1039120/161275185-4540cb5f-061c-4f44-a063-92cf26144243.png)
or the internal IP of the Host: 
![image](https://user-images.githubusercontent.com/1039120/161275358-85a4f487-e67f-4668-bf6f-2d0a144e53ea.png)
It works!

An idea is to ensure that in the docker file we add an entry stating:
RUN echo <HOST IP> host.docker.internal >> /etc/hosts

**Comment by dougbreaux** [comment]
I've had to do multiple things on my Windows 10 here to get this kind of connection back to the host working. And neither has to do with RD per se, but with WSL2 itself. You can test this out with any WSL instance. Whatever DD does to handle this would be great to see added here, but in the mean time...
1. I had to add firewall rules to Windows Defender to allow the desired ports in. Obviously, your particular firewall and configuration might or might not have the same need
2. I had to run Windows `netsh interface portproxy add ...` commands for each port

e.g.
```console
netsh interface portproxy add v4tov4 listenport=9080 listenaddress=<ip-address-of-wsl-adapter> connectport=9080 connectaddress=localhost
```

`netsh` commands have to be run with Administrator privileges. `portproxy` has to be set each time your WSL adapter IP address changes, and, as far as I know, have to run this for each port you want to reach.

**Comment by Nino-K** [comment]
Can you try defining a new inbound firewall rule associated with the wsl interface to see if that rectifies the issue?

```
New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow
```
Many thanks.

**Comment by dougbreaux** [comment]
@Nino-K instead of the above two things I described? Or only instead of the port-specific firewall rules I added? That is, should the `netsh ... portproxy ...` still be required?

**Comment by Nino-K** [comment]
@dougbreaux just the firewall rule alone that I mentioned above, no additional steps, thanks.

**Comment by dougbreaux** [comment]
@Nino-K not only is that rule not working by itself for me, now even adding back the original steps is no longer working. Not sure what I broke

**Comment by Nino-K** [comment]
@dougbreaux the above line just adds a firewall rule that can be easily removed. All it does is add a rule associated with `wsl` under inbound rules. You can simply go to "Windows Defender Firewall with Advanced Security" and remove the rule. Please take a look at the screenshot attached. 

When I add that rule to my firewall I can easily connect to a service that is running on the host without it I get the behavior mentioned above. 

![Screen Shot 2022-05-02 at 3 45 01 PM](https://user-images.githubusercontent.com/10409174/166339183-8cf2e84d-c897-48fc-91af-f0948ff4952b.png)

**Comment by dougbreaux** [comment]
I realize that's all it's doing, but with or without that rule added, my WSL instances are no longer able to reach the host, with or without my port rules added, and with or without the netsh proxying added.

I've even rebooted, thinking maybe something was holding a port, but that made no difference either.

**Comment by dougbreaux** [comment]
Well, I found some DROPs in the firewall log, despite having both or one-or-the-other set of firewall rules defined. Turns out my JDK (IBM Semuru) that is running my app had a "Public Network" Block rule. Despite me being on a Private network, and not having created such a rule myself, and the failures happening even when that JDK app wasn't running at all, disabling that rule has me able to connect from RD to the host again. 

Even without using the `netsh ... portproxy ...` rules.

The firewall also has rules for the JDK to explicitly Allow Private Network connections, which is what my Windows Network Status confirms is active, so I guess I don't understand why the Public Block would be preventing this.

**Comment by dougbreaux** [comment]
Also, BTW, I find that sometimes when I stop and start a container, the `host.docker.internal` hostname is gone from hosts. If I instead delete the container and re-run it from scratch, the hostname is working again.

**Comment by jandubois** [comment]
> disabling that rule has me able to connect from RD to the host again

@dougbreaux Thanks for confirming that this was a local config issue. The new firewall rule proposed by @Nino-K seems to fix the problem for everyone who has responded so far.

I'm going to hide your earlier messages as "outdated" to prevent confusing users who find this issue via a Google search.

> BTW, I find that sometimes when I stop and start a container, the `host.docker.internal` hostname is gone from hosts.

Please file a separate issue for unrelated problems!

<hr>

I'll leave this bug open for now until we have figured out if we want to add the firewall rule to the installer or some other way to make it easier for users to enable it.

**Comment by Nino-K** [comment]
> Can you try defining a new inbound firewall rule associated with the wsl interface to see if that rectifies the issue?
> 
> ```
> New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow
> ```
> 
> Many thanks.

Can we please add this to our documentation?

**Comment by sregdorr** [comment]
Please let me know if this isn't directly related, but I've started experiencing issues with host.docker.internal. 
with a localhost service running on port 3500: 

![image](https://user-images.githubusercontent.com/32646119/172694158-286c6326-b79b-4de8-bbb7-bb42bd008094.png)

I'm not able to call the service from a docker container. I've started the container with `--add-host=host.docker.internal:host-gateway` 

![image](https://user-images.githubusercontent.com/32646119/172694627-3a8384e7-9086-4dc0-bb8d-ed5baef975ea.png)

And I can ping the host

![image](https://user-images.githubusercontent.com/32646119/172694865-a254b407-6d9c-4dbb-a28c-b602c7641561.png)

But anytime I try to call the service (curl or telnet) on port 3500, I receive a connection refused error

![image](https://user-images.githubusercontent.com/32646119/172695037-d0d04cca-5b52-4288-a52a-e1245c465e57.png)

This happens in spite of the aforementioned firewall rule being applied to allow traffic from WSL

Thanks in advance!

rancher-desktop: v1.3.0
docker: v20.10.9

**Comment by Nino-K** [comment]
> Please let me know if this isn't directly related, but I've started experiencing issues with host.docker.internal.
> Given a localhost service running on port 3500:

@sregdorr You would need to make sure the service that is running on the host is bound to either `vEthernet (WSL)` which is mapped to `host.docker.internal` or is bound to `0.0.0.0`. I think you might have your service port `3500` bound to `127.0.0.1` which is not going to work, even if you run the firewall rule. 

Here are the steps I took to verify this:

Run a nginx and bind the port to all interfaces:

```
docker run -d -p 87:80 --restart=always nginx
```
Then from inside of the container: 

```
docker run -it wbitt/network-multitool /bin/bash
```
Run:
```
curl host.docker.internal:86
```
You will notice that curl is being blocked. 

Now run the firewall rule: 

```
New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow
```
Run curl again and you will see it returns 200 OK status

```
bash-5.1# curl -I host.docker.internal:86
HTTP/1.1 200 OK
Server: nginx/1.23.1
Date: Fri, 30 Sep 2022 20:45:54 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 19 Jul 2022 14:05:27 GMT
Connection: keep-alive
ETag: "62d6ba27-267"
Accept-Ranges: bytes
```
Run another nginx container and bind it to `127.0.0.1` this time

```
docker run -d -p 127.0.0.1:87:80 --restart=always nginx
```

run the curl again:
```
bash-5.1# curl -I host.docker.internal:87
```
You will notice that our curl never succeeds and it timesout. 

This is because docker proxy has no knowledge of how to route to `127.0.0.1:SERVICE_PORT` on the host.
