### ISSUE TITLE
/usr/sbin/system_profiler: -json option not supported on older versions of macOS

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#1931]
When running on `mojave` or older, starting up gives this error:
```
Error starting lima: Error: /usr/sbin/system_profiler exited with code 1
```

The cause is that we're calling it with the `-json` flag, but this isn't available on older systems.

### Rancher Desktop Version

1.2.1

### What operating system are you using?

macOS

### Operating System / Build Version

10.12.6 Mojave

**Comment by jandubois** [comment]
Minimum requirement is macOS Catalina or newer.

**Comment by yangliuyu** [comment]
@ericpromislow I use pre-compiled clang+llvm (14.0.0), lima, colima and compile qemu 5.2.0 on High Sierra
