### ISSUE TITLE
Epic: Rancher Desktop should be usable on macOS without sudo

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1938]
This is a subset of #1224 that should make it into the next release.

* [ ] Run in reduced functionality mode when `sudo` is unavailable
  * [x] #1226
  * [x] #1937
  * [x] #1841
    * [x] #910
* [x] #1225
* [x] Verify that RD works when installed into `$HOME/Applications`

**Comment by mook-as** [comment]
> Verify that RD works when installed into `$HOME/Applications`

Seems to work fine; I didn't allow sudo access, though.
