### ISSUE TITLE
Docs: How to setup Multi node / Multi cluster in Rancher Desktop

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1954]

**Comment by mook-as** [comment]
I do not believe this is supported, or on the short term roadmap.

I do not believe multi-cluster is even anywhere near the roadmap.

**Comment by gunamata** [comment]
I was referring this this thread (https://github.com/rancher-sandbox/rancher-desktop/issues/588) and thought Multi Node / Multi Cluster is now feasible via k3d. No?

**Comment by jandubois** [comment]
> thought Multi Node / Multi Cluster is now feasible via k3d. No?

Yes, it is possible to use `k3d` with Rancher Desktop and the docker runtime (you can disable k3s, it will not be used).

E.g. you can create a 3-node cluster with:

```console
$ k3d cluster create --agents 3
INFO[0000] Prep: Network
INFO[0000] Created network 'k3d-k3s-default'
INFO[0000] Created image volume k3d-k3s-default-images
INFO[0000] Starting new tools node...
INFO[0000] Starting Node 'k3d-k3s-default-tools'
INFO[0001] Creating node 'k3d-k3s-default-server-0'
INFO[0001] Creating node 'k3d-k3s-default-agent-0'
INFO[0001] Creating node 'k3d-k3s-default-agent-1'
INFO[0001] Creating node 'k3d-k3s-default-agent-2'
INFO[0001] Creating LoadBalancer 'k3d-k3s-default-serverlb'
INFO[0001] Using the k3d-tools node to gather environment information
INFO[0001] HostIP: using network gateway 172.19.0.1 address
INFO[0001] Starting cluster 'k3s-default'
INFO[0001] Starting servers...
INFO[0001] Starting Node 'k3d-k3s-default-server-0'
INFO[0006] Starting agents...
INFO[0006] Starting Node 'k3d-k3s-default-agent-0'
INFO[0006] Starting Node 'k3d-k3s-default-agent-2'
INFO[0006] Starting Node 'k3d-k3s-default-agent-1'
INFO[0017] Starting helpers...
INFO[0017] Starting Node 'k3d-k3s-default-serverlb'
INFO[0024] Injecting records for hostAliases (incl. host.k3d.internal) and for 5 network members into CoreDNS configmap...
INFO[0026] Cluster 'k3s-default' created successfully!
INFO[0027] You can now use it like this:
kubectl cluster-info
$ kubectl get no
NAME                       STATUS   ROLES                  AGE   VERSION
k3d-k3s-default-agent-2    Ready    <none>                 18s   v1.22.6+k3s1
k3d-k3s-default-agent-0    Ready    <none>                 17s   v1.22.6+k3s1
k3d-k3s-default-agent-1    Ready    <none>                 16s   v1.22.6+k3s1
k3d-k3s-default-server-0   Ready    control-plane,master   25s   v1.22.6+k3s1
```

Note that the cluster will not be managed by RD, so you can't upgrade the k3s vesion using the UI and the dashboard will also not work. But it is a way to run a multi-node cluster with RD.

**Comment by mook-as** [comment]
Wouldn't that be a k3d thing, and totally outside our scope? We can say "k3d works, but please turn off RD's built in Kubernetes", but I don't see why we'd have detailed documentation on using k3d?

**Comment by jandubois** [comment]
> We can say "k3d works, but please turn off RD's built in Kubernetes",

Yes, but we should also mention the limitations I noted above: versions not managed by RD, so no upgrade/downgrade support, no support dashboard.

There may be more, but needs research: are the images exposed to the docker daemon? If not, then the images tab also doesn't apply. Port forwarding through the UI will not work, and in general host mounts and port forwarding may be different.

**Comment by gunamata** [comment]
Added a doc by https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/56
