### ISSUE TITLE
Cannot pull when using Rancher Desktop and wsl-vpnkit

### ISSUE THREAD

**Issue by abcarcol** [rancher-sandbox/rancher-desktop#1966]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/1962

<div type='discussions-op-text'>

<sup>Originally posted by **abcarcol** April  4, 2022</sup>
I am using wsl-vpnkit to provide network connectivity to the WSL 2 VM while connected to VPNs on the Windows host. However, when I try to pull any image with Rancher Desktop I get the following:

> nerdctl pull nginx
INFO[0000] trying next host                              error="failed to do request: Head \"https://registry-1.docker.io/v2/library/nginx/manifests/latest\": dial tcp: lookup registry-1.docker.io on 172.29.215.96:53: read udp 172.29.215.96:34076->172.29.215.96:53: read: connection refused" host=registry-1.docker.io
FATA[0000] failed to resolve reference "docker.io/library/nginx:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/nginx/manifests/latest": dial tcp: lookup registry-1.docker.io on 172.29.215.96:53: read udp 172.29.215.96:34076->172.29.215.96:53: read: connection refused

> nslookup registry-1.docker.io
Server:  anycastdns.corp.xxx.com
Address:  10.5.5.5

Non-authoritative answer:
Name:    registry-1.docker.io
Addresses:  44.196.236.180
          54.85.133.123
          52.21.28.242
          52.72.252.48
          52.205.127.201
          54.86.228.181
          54.197.112.205
          34.203.135.183</div>

**Comment by Nino-K** [comment]
@abcarcol please upgrade to 1.9 release and enable our new [gvisor-based ](https://github.com/rancher-sandbox/rancher-desktop/issues/3810)network which should address this issue. Please note that you will not need wsl-vpnkit, you can simply enable the new network using 
```
rdctl set --experimental.virtual-machine.networking-tunnel=true
```
