### ISSUE TITLE
Run vde_vmnet with launchd to remove sudoers file.

### ISSUE THREAD

**Issue by CMBulthuis** [rancher-sandbox/rancher-desktop#1968]
### Problem Description

I am working at a company where security is im portant and we monitor root/admin usage on MacBooks using CyberArk EPM. Using a sudoers files is not possible with CyberArk EPM. 
With the current setup of Rancher Desktop and Lima /private/etc/sudoers.d/zzzzz-rancher-desktop-lima is required to run the vde switch and vmnet processes.
To overcome this I created a setup to run vde switch / vmnet using launchd.

### Proposed Solution

Use launchd to run vde switch / vmnet.

I created a proposal for this setup which is tested on an Intel Mac without CyberArk EPM and a M1 Mac with CyberArk EPM.
I am interested in your feedback, see draft pull request in my forked repository https://github.com/CMBulthuis/rancher-desktop/pull/2.

Note:
The pull request is on current version of the rancher-sandbox/rancher-desktop main branch. I can also create a pull request against rancher-sandbox/rancher-desktop repo from my forked repo if that is the preferred methode.

### Additional Information

I tried removing sudoers file zzzzz-rancher-desktop-lima only run into integration issue with Lima.
During stop/start of Rancher Desktop Lima will pkill the vde vmnet and switch processes:
- sudoers file is required
- pid files for the vmnet processes are required. 
- pid file names for launchd processes need to be different as default used by lima, otherwise lima will try to kill them

If the idea to use launchd is excepted I am thinking about the following additional improvements:

- During ‘Factory reset’ also remove configuration created using sudo permissions.
- For additional stability check during startup if the vde processes (under control of launchd) are running correct and if needed launchctl unload and load them.
Note: during development I noticed when Lima pkilled the switch process while vmnet kept running just starting the switch process was not enough. In this situation the vmnet process lost the connection with the switch process. 
- Remove the sudoers file zzzzz-rancher-desktop-lima.
To be able to remove the sudoers file changes are required in Lima. In the current network setup Lima is executing code requiring the sudoers file also when it is not required when launchd is used.
A flag/switch or other option should be added to disable this behaviour.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by CMBulthuis** [comment]
Hello @jandubois when checking the contributions I noticed you worked a lot on the network integration between Rancher Desktopo and Lima. I am interested in your opinion for my proposal to use launchd for vde_vmet.
Kind regards, Chris

**Comment by AdnanHodzic** [comment]
This issue seems to be related to: #1615

**Comment by Krijger** [comment]
@jandubois do you have any idea when you will be able to have a look at this issue?

**Comment by jandubois** [comment]
If everything goes well, we'll have a release later this week that should allow you to run Rancher Desktop without `sudo` (but also without vde_vmnet).

Starting/stopping the vmnet daemons via a privileged helper process will come later.

**Comment by CMBulthuis** [comment]
@jandubois do you plan to implement vmnet using launchd like my proposal or are there other plans?
Depending on the ideas I can maybe help with the solution.

**Comment by CMBulthuis** [comment]
@jandubois I understand your decision to create a privileged helper process. It gives more freedom to use it in other situations were elevated access is required. I will keep track of the overall Epic about sudo handling and if I see something I can help with I will get in touch.

Thanks for the advice together with version 1.3.0. Will have a look if it can help us in the meantime.

**Comment by CMBulthuis** [comment]
Hi @jandubois, 
Just a checkup.
Is their progress on the privileged helper process?
If I can help either by testing or developing let me know.
Kind regards, Chris

**Comment by jandubois** [comment]
Hi @CMBulthuis,

This work is currently on hold for the current release cycle, as we are doing major internal refactoring of the the engine, and the GUI priority is a new modal preferences dialog that allow you to make all the settings changes you want, and apply them all at once. Since some people also take time off over the summer, we don't have the capacity to work on the privileged helper stuff simultaneously.

Note that there is also new development on the Lima side, with https://github.com/lima-vm/socket_vmnet hopefully replacing vde_vmnet soon, but not yet ready yet, as it only supports a single interface per VM right now. So there are additional considerations for how the helper process needs to work, to accommodate this.

Sorry for the not-so-great news, but those are the constraints. We still very much plan to do this; it is just taking a little longer than we hoped for!

**Comment by CMBulthuis** [comment]
> @CMBulthuis I work for the same organisation and I don't seem to have (as much) issues anymore running sudoless 1.4.1 rancher desktop on my m1 mac w. Cyberark EPM, give it a try :)

That sound good, will try it. 
What is your experience with networking from docker and kubernetes to your local system?

**Comment by CMBulthuis** [comment]
For retrieving elevated/root access on MAC books we moved away from CyberArk EPM to another tool which also provides functionality to deal with sudoers files. I will Close this issue.

**Comment by fethiarras** [comment]
Hi,

I made an Enhancement Request to CyberARK for supporting --non-interactive on EPM. Since agent 24.7, you need to open a case to CyberARK, if you want activate the support of --non-interactive and it's work :)
