### ISSUE TITLE
Rancher Dashboard (Deskboard) - Does not render

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#1969]
### Actual Behavior

Dashboard integration renders a blank page.

### Steps to Reproduce

1. Start Rancher Desktop
2. Select Dashboard from Tray

### Result

Dashboard integration renders a blank page.

### Expected Behavior

Rancher Dashboard renders successfully. 

### Additional Information

* both Debian and Xubuntu 20.04. Both reports are running XFCE DE, which I don't expect to contribute to the problem, but it's interesting enough to note

* `/bin/sh: 1: p11tool: not found`. After installing `p11tool`, Dashboard appeared to momentarily work, but it shortly stopped afterward

* dashboard is accessible from firefox/chrome, just not the embed webkit.  Potentially relevant logs

   ```
   [177638:177644:0404/144059.375977:ERROR:ssl_client_socket_impl.cc(997)] handshake failed; returned -1, SSL error code 1, net_error -202
   [249581:0404/144113.644796:ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -202
   [249581:0404/144113.732723:ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -202
   [249581:0404/144119.129914:ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -202
   [249581:0404/144119.216757:ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -202
   ```

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

N/A

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Xubuntu 20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by ibuildthecloud** [comment]
I wonder if the simplest solution is just no run TLS.  Steve can be started with `--https-listen-port=0` do disable TLS and the redirect.  I'm trying this out now but the dashboard build is all hardcoded to https://127.0.0.1:9443.  I'm trying to figure out how to rebuild the dashboard with http://127.0.0.1:8080

**Comment by rak-phillip** [comment]
We have a custom build of Dashboard for the Rancher Desktop integration for the time being. Taking a look at the github action might fast track you into into rebuilding dashboard:

https://github.com/rancher-sandbox/dashboard/blob/master/.github/workflows/release-rancher-desktop.yml

**Comment by rak-phillip** [comment]
I've been attempting to reproduce this one in Xubuntu 20.04.4 without success.. I might circle back later in the week to attempt in Debian to see if I can repro.

@jandubois

**Comment by rak-phillip** [comment]
Able to reproduce, from what I can see this a problem with electron and rendering/resizing a `browserView`. Based on what I'm seeing, this doesn't look to be an issue with Dashboard or Steve. Collecting more info to see if we can get this to behave more consistently in xfce.
