### ISSUE TITLE
Cannot access LoadBalancer service from the Pod itself when using dockerd

### ISSUE THREAD

**Issue by Maxinho96** [rancher-sandbox/rancher-desktop#1978]
### Actual Behavior

I have a LoadBalancer that exposes one of my Pods to the outside via an external IP. The external IP is accessible from the outside and from all the Pods, except from the Pod itself that is attached to the LoadBalancer service.

### Steps to Reproduce

1. Define a LoadBalancer service and attach it to a Deployment via selectorLabels
2. Open the shell of a Pod in the deployment and launch a curl to the LoadBalancer external IP

### Result

The curl returns `curl: (7) Failed connect to <external_ip>; Connection timed out`, where <external_ip> is the IP of the LoadBalancer.

### Expected Behavior

The external IP should be accessible from the Pod itself.

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.21.10

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 1909

### What CPU architecture are you using?

x64

**Comment by Maxinho96** [comment]
UPDATE: this bug only affects dockerd (moby/docker cli), it works fine in containerd (nerdctl cli)

**Comment by gaktive** [comment]
@gunamata to repro this and determine what the next steps are.

**Comment by gunamata** [comment]
Hi, Apologies for the delay in getting to this..

I tried to reproduce the issue described in the description. I have tried the example on [this page](https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-D1451EA0-C39F-44F6-A9A9-68AA89328003.html), with `dockerd (moby)` as the selected container runtime. I run Windows 10 Enterprise as well on my machine.

Once the pods, service are up and running I could successfully `curl` to the LoadBalancer external IP from the Deployment pods, from the host machine as well as from a different container. @Maxinho96, Can you please try with the latest version of Rancher Desktop and let us know if you still this problem. If you still see the problem, please also try creating a firewall rule as described in this [FAQ](https://docs.rancherdesktop.io/faq#q-can-containers-reach-back-to-host-services-via-hostdockerinternal) to see if it helps.

**Comment by gaktive** [comment]
Will retest as part of the next RC.

**Comment by gunamata** [comment]
I have tried the steps mentioned in the issue description with the latest release 1.6.0, and could successfully curl the load balancer external ip. 

Closing the issue. @Maxinho96 , Please feel free to reopen if you run in to this issue again with the latest Rancher Desktop release.
