### ISSUE TITLE
How  to add a node?

### ISSUE THREAD

**Issue by jack-liew** [rancher-sandbox/rancher-desktop#1988]
### Problem Description

RD has only one node by default, but I need multiple nodes, how can I add more than one node?
Is it possible to add nodes with K3S and manage them with RD?

Thanks.

### Proposed Solution

I hope to be able to handle all the things about containerd with RD.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jandubois** [comment]
This not currently supported. See https://github.com/rancher-sandbox/rancher-desktop/issues/1954#issuecomment-1086166664 how you can run a multi-node cluster with k3d on RD, but it will not be managed through the UI.

I'm closing this issue as a duplicate of #588

**Comment by jack-liew** [comment]
> 

 just a lit disappointed, I hope to add this feature soon
