### ISSUE TITLE
VSCode devcontainer "Clone Repository in a named Container Volume" hangs forever while cloning

### ISSUE THREAD

**Issue by kamalrayaguru** [rancher-sandbox/rancher-desktop#2003]
### Actual Behavior

Tried out with Rancher Desktop 1.2.1 & Kubernetes 1.22.7(stable) on my Windows 10 laptop and tried opening the git repository in VS Code in a named container volume. Cloning hangs forever.

### Steps to Reproduce

1. Keep Rancher Desktop running.
2. Open VS Code and do **ctrl+shift+p** and select **Remote-Containers: Clone Repository in a named Container Volume.**
3. Provide the name for git repository and the container volume
4. The VS Code window (instance) will reload and begin to clone the source code.

### Result

1. The clone never completes. It hangs after getting the remote branches:
![image](https://user-images.githubusercontent.com/94606107/162456872-5f0b14af-280d-4484-892a-b6b60675a75a.png)
2. Close VS Code and re-open. Try to open the above one from Recent section on VS Code. Here, it hangs at the step:
![image](https://user-images.githubusercontent.com/94606107/162457528-65b01aa0-6c60-40d9-aef0-a1464273bccf.png)

### Expected Behavior

The clone should complete. The devcontainer should start building.

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.22.7(stable).. Tried with other versions too such as 1.23.5(latest)

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2 OS Build 19044.1586

### What CPU architecture are you using?

x64

### Windows User Only

No

**Comment by gunamata** [comment]
Looks like the same problem reported in https://github.com/rancher-sandbox/rancher-desktop/issues/1895
I could reproduce the issue on my windows machine with https://github.com/microsoft/vscode-remote-try-node.git.. Btn, In #1895, it's mentioned that this repo works though.. 

Going through the logs.. I will post here, if I find something..

**Comment by gunamata** [comment]
As mentioned [here](https://github.com/microsoft/vscode-remote-release/issues/6590), the cloning in named container volumes  works with an earlier version (0.224.3) of the VS Code extension.. For reference, I followed below steps to downgrade the extension.

- Uninstall the current version of `Remote Containers` 
- Turn off  Auto Upgrade of extensions by running `Extensions: Disable Auto Update for all extensions` from the command palette (Ctr + Shift + P on Windows)
- Download the vsix file of 0.224.3 version with this url (https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-containers/0.224.3/vspackage)
- Install the extension via vsix file using the command `Extensions: Install from VSIX`
- Reload VS Code window `Developer: Reload Window`.

**Comment by kamalrayaguru** [comment]
> As mentioned [here](https://github.com/microsoft/vscode-remote-release/issues/6590), the cloning in named container volumes works with an earlier version (0.224.3) of the VS Code extension.. For reference, I followed below steps to downgrade the extension.
> 
> * Uninstall the current version of `Remote Containers`
> * Turn off  Auto Upgrade of extensions by running `Extensions: Disable Auto Update for all extensions` from the command palette (Ctr + Shift + P on Windows)
> * Download the vsix file of 0.224.3 version with this url (https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-containers/0.224.3/vspackage)
> * Install the extension via vsix file using the command `Extensions: Install from VSIX`
> * Reload VS Code window `Developer: Reload Window`.

Thanks @gunamata, this fixes my issue !

**Comment by kamalrayaguru** [comment]
Closing the issue as I got a fix suggested by @gunamata.
