### ISSUE TITLE
Startup and boot on Linux Fedora 35 using AppImage Install

### ISSUE THREAD

**Issue by thawkins** [rancher-sandbox/rancher-desktop#2043]
I'm not sure if this working as expected

If I start up RD it will create a set of utility links in ~/.local/bin

So I can type ">$docker ps" and I can see the loaded containers, all good

If I exit RD it will remove the links in ~/.local/bin

If I startup RD again it won't create the utility links again because it has effectively "Unchecked" the options on the "Supporting Utilities", so I cant use the utilities, so checking them again will recreate them, and everything is hunky-dory again. 

But: 

If i reboot the machine without exiting RD, it leaves a set of symlinks in my ~/.local/bin that now point to a temp directory in /tmp that is not the real directory for RD, its the old one used by the previous boot. And if I start up RD again the links are unchecked, but now I cant check them because it says they already exist. 

So I have to manually delete the contents of ~/.local/bin and then recheck the checkboxes to recreate the links. 

So here is what I expected to happen. 

1. If I stop and then start RD I expect it to remove and then recreate the links, it should not remove the checks on the "supporting Utilities" 
2. If I startup RD and there are already links in ~/.local/bin, and those links point at a missing directory because RD removed it and replaced it with a new one in /tmp on startup, then i expect it to also remove and replace the links so that the links work. 
3. And this is a bit of a stretch, but it resolves an issue if I set RD to be a startup application that should do all of the above so I don't have to remember to restart it each time I want to use the container system. 

SystemOS: Linux Fedora 35
RD Version: 1.2.1

**Comment by thawkins** [comment]
Some more information, this behavior seems to be mainly related to the "Appimage" version of the tool, that is what I initially installed as that was the advice given on the downloads page for fedora users. 

If however, I install RD "natively" on Fedora 35 using this procedure ( https://techviewleo.com/run-kubernetes-on-fedora-rocky-centos-using-rancher-desktop/ ), then certainly issues 1 and 3 seem to work fine now, I will try and confirm 2, but given that 3 works it is highly likely that 2 is working as well. Given this then it would seem that the use of "AppImages" is problematic and will cause new users to experience issues. 

Updating the description to reflect this.

**Comment by adamkpickering** [comment]
Thanks for the feedback! We're aware of this issue and working on it. While we can't make any promises, we are planning a release that will fix this in the next few weeks.

For more information, see the discussion at #1512, and the epic at #1732.

Closing since this issue is already tracked in other ones.
