### ISSUE TITLE
README missing information on dependencies

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#2058]
### Problem Description

Trying to develop Rancher Desktop from a fresh Linux environment currently fails due to missing pre-requisites that are not mentioned in the readme

`build-essential`
`go`

### Proposed Solution

Detail missing pre-requisites for developing Rancher Desktop in Linux.

### Additional Information

We should verify that nothing has changed for other environments as well

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by mook-as** [comment]
Testing on an openSUSE Leap 15.3 container:
- Installed `git-core` + `npm16` (which pulls in `nodejs16`)
- Needed to install additional dependencies:
  - `nodejs16-devel`
  - `python3` (for `node-gyp`)
  - `pattern:devel_C_C++` & `gcc-c++` (g++ is separate, see [bug 1154052](https://bugzilla.opensuse.org/show_bug.cgi?id=1154052))
  - `go1.18`

**Comment by mook-as** [comment]
Testing on Ubuntu 22.04 container:
- `nodejs` 16 via [NodeSource](https://github.com/nodesource/distributions/blob/master/README.md#deb) (which means getting `curl` too)
- `git`
- `golang` (pulling in g++)
- `build-essential`
