### ISSUE TITLE
Fresh install of Rancher Desktop 1.2.1 on Windows 10 does not start

### ISSUE THREAD

**Issue by steinar-flatland** [rancher-sandbox/rancher-desktop#2076]
### Actual Behavior

A new install of Rancher Desktop 1.2.1 on a Windows 10 machine does not start.  Attempting to run it results in errors in both background.log and k8s.log (attached)

* [background.log](https://github.com/rancher-sandbox/rancher-desktop/files/8542632/background.log)
* [k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/8542634/k8s.log)

### Steps to Reproduce

* First, ensure Rancher Desktop is not installed.  To do this I:
  * Run C:\Users\my.user\AppData\Local\Programs\Rancher Desktop\Uninstall Rancher Desktop.exe
    * _Observe that this deletes all files in C:\Users\my.user\AppData\Local\Programs\Rancher Desktop_
  * Delete the C:\Users\my.user\AppData\Local\Programs\Rancher Desktop directory
  * Delete the C:\Users\my.user\AppData\Local\rancher-desktop directory
  * Delete the C:\Users\my.user\AppData\Local\rancher-desktop-updater directory
* Run Rancher.Desktop.Setup.1.2.1.exe, click I Agree, uncheck Run Rancher Desktop, click Finish.
  * _It seems to have installed fine.  C:\Users\my.user\AppData\Local\Programs\Rancher Desktop is populated with a fresh install._
* In a Command Prompt, cd to C:\Users\my.user\AppData\Local\Programs\Rancher Desktop and run "Rancher Desktop.exe"
  * _The program runs for only about 1 second or less.  There are no error messages on the console.  Rancher Desktop is not running._
  * _There are error messages in background.log and k8s.log (see attachments to Actual Behavior)_

### Result

After the install, Rancher Desktop.exe will not start.  On attempt to run it, it runs for only a short time (a second or so) and there are error messages in both background.log and k8s.log.  These files are attached to the Actual Behavior.

### Expected Behavior

The expectation is that Rancher Desktop should start and run normally, without error messages in the logs.

### Additional Information

It is perhaps noteworthy that I have similar issues with Rancher Desktop 1.2.1, 1.2.0, 1.1.1, and 1.1.0.  However, if I install 1.0.1 it works fine.  So the highest version number of Rancher Desktop I can run on this machine is 1.0.1.

I was curious if it would make a difference running both the installer and Rancher Desktop as administrator.  I tried this.  Same results.

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

unsure

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 version 20H2 (build 19042.1586)

### What CPU architecture are you using?

x64

### Windows User Only

My company uses GlobalProtect, Version 5.1.6-16 from Palo Alto Networks, Inc.  I have duplicated this problem while disconnected from the VPN.

**Comment by panktrip** [comment]
I am also seeing this issue.. Tried to install rancher-desktop first time on windows-10-enterprise. but it failed.

**Comment by steinar-flatland** [comment]
I have determined that "Rancher Desktop.exe" is failing before it has a chance to register the WSL distributions for rancher-desktop and rancher-desktop-data.  I determined this by uninstalling as stated in the Steps to Reproduce above and, in addition, running the following commands at a Command Prompt:

```wsl --unregister rancher-desktop```
```wsl --unregister rancher-desktop-data```

Having done this, I can do

```wsl --list```

And these distributions definitely do not exist.

Then, I install Rancher Desktop 1.2.1 and run it for the first time as stated in the Steps to Reproduce.  Afterwards I once again run 

```wsl --list```

And still, the distributions for rancher-desktop and rancher-desktop-data do not exist.

If I run through this same procedure on a different Windows 10 laptop, Rancher Desktop installs and launches fine, and afterwards the distributions **do** exist.  There seems to be some state on this laptop (which otherwise works fine) that is keeping Rancher Desktop from working.

**Comment by nwrkbiz** [comment]
The issue seems to be linked to the win-ca node extension. roots.exe returns an "endless" string.

**Comment by steinar-flatland** [comment]
Interesting.  Just noticed this issue seems related to or same as this one: [Issues with root certificates seems to keep Rancher Desktop from even starting](https://github.com/rancher-sandbox/rancher-desktop/issues/1072).

**Comment by steinar-flatland** [comment]
I deleted expired certificates as follows:  In a CommandPrompt run mmc.  Then:  File/Add or Remove Snap-in.../Certificates/Add >/Computer account/Next >/Local computer/Finish/OK.  Browse certificates in the left panel. Delete ones that are expired, being careful not to delete anything critical.

Now I have fewer certificates.  I repeated the procedure in Steps to Reproduce, and now it works.

So it _appears_ that the presence or absence of expired certificates is the difference between getting or not getting the following exception on startup (for full error see attachements to Actual Behavior above).

```
2022-04-22T16:40:54.300Z: Error starting up: <ref *1> Error: spawnSync C:\Users\steinar.flatland\AppData\Local\Programs\Rancher Desktop\resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    ...
```

My immediate problem is solved.  I'll leave it to the folks running this github project to decide what you want to do with this issue.  Thanks!

**Comment by nwrkbiz** [comment]
Nah, I guess its the amount of certs avaiable on the system. We have quite some copany certs on our devices...

Seems to me like rancher should use some node ffi functions, instead he uses roots.exe.

**Comment by mook-as** [comment]
Luckily, we switched over to using FFI for getting certs in #1072 so it should be different in the next release (aiming for this week, but we'll see).

If you could grab a CI build off `main` to check that it fixes things, it'd be much appreciated too. (Note that, of course, it's not signed because CI shouldn't have access to the certs)

**Comment by nwrkbiz** [comment]
> Luckily, we switched over to using FFI for getting certs in #1072 so it should be different in the next release (aiming for this week, but we'll see).
> 
> If you could grab a CI build off `main` to check that it fixes things, it'd be much appreciated too. (Note that, of course, it's not signed because CI shouldn't have access to the certs)

Would be happy to try, can you guide me to the ci artifact?

**Comment by jandubois** [comment]
> Would be happy to try, can you guide me to the ci artifact?

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2224861532

**Comment by nwrkbiz** [comment]
****

> > Would be happy to try, can you guide me to the ci artifact?
> 
> https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2224861532

Jep works fine (: (Takes a while to start up)

**Comment by nwrkbiz** [comment]
The new release fixed this problem for me, I think this issue can be closed?

**Comment by jandubois** [comment]
Thanks for confirming!
