### ISSUE TITLE
Necessary config/utils not applied to WSL instance after install

### ISSUE THREAD

**Issue by justinrush** [rancher-sandbox/rancher-desktop#2093]
### Actual Behavior

I installed rancher desktop on my windows 10 desktop. After that succeeded, I went to the WSL Integration tab and checked the box next to my preferred WSL instance. I did a `wsl --shutdown` and started it back up, but none of the expected tools (e.g. `nerdctl`) appear to have been installed. I fetched the binaries manually from their releases page, but I get the following error when trying to run it:

```
➜  ~ nerdctl ps
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/

```

Running `nerdctl ps` from the Windows command prompt works as expected.

### Steps to Reproduce

Install and apply the WSL integration

### Result

```
➜  ~ nerdctl ps
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/

```

### Expected Behavior

it should work

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.23.5

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 20H2 19042.1645

### What CPU architecture are you using?

x64

### Windows User Only

Carbon Black is installed but did not generate any warnings or errors during the install or configuration of the software. No VPN, but we do use OpenDNS

**Comment by mook-as** [comment]
Hi!

On Windows, rather than installing files, we set your `PATH` to include the directory holding all the tools.  Using upstream binaries (especially for `nerdctl`) would not work correctly, as we do not use Windows containers (everything runs in the WSL VM).

On some IT-managed machines, some PowerShell features might be disabled; this would break our installer (see #828).

Additionally, if you set your WSL distribution to _not_ pick up your Windows `PATH`, this would also not be found within that distribution. This would be in [`/etc/wsl.conf`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings), under `[interop] appendWindowsPath`.

Please check the `PATH` in your environment to see if either of the two cases apply to you.

**Comment by justinrush** [comment]
This should probably be documented somewhere - I can manually add that path to my profile, but I have no override `/etc/wsl.conf` file, so I'm guessing the behavior you are counting on isn't default... or was I supposed to reboot after installing in my env?

**Comment by mook-as** [comment]
The path is normally automatically added; when it isn't it's considered a bug.

I believe normally Explorer picks up the change automatically and therefore the reboot is normally unnecessary.

**Comment by justinrush** [comment]
must be something special to how i have things then - thanks
