### ISSUE TITLE
Don't notify that bridged/shared network has no IP address when running without sudo

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2099]
When I select "never ask for administrative access" then I should not get a popup that bridged network didn't get an IP address, and shared network didn't get one either: that is expected because we don't configure bridged/shared networks in that case.

**Comment by mook-as** [comment]
We should probably only do this after we have some status showing that sudo access is disabled; as it is, the user would not have any indication that it is permanently off (other than the checkbox in the prefs), so it is likely they'll just be confused when things don't work.

**Comment by jandubois** [comment]
> We should probably only do this after we have some status showing that sudo access is disabled;

What/where should this be?

I've been running without administrative access for a day now, and the notification sound on each startup of RD is really annoying. And there is no way to turn it off if you cannot enable `sudo` mode.
