### ISSUE TITLE
Kubernetes version is not reset back to original value when change is made and popup is cancelled

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#2124]
### Actual Behavior

See title.

### Steps to Reproduce

1. Go to "Kubernetes Settings" tab.
2. Select an earlier version of Kubernetes.
3. Cancel the popup that says that a reset is required.
4. Note how the `Kubernetes version` field stays at what you selected, not what it originally was.

### Result

The kubernetes version stays the same after deciding not to change it.

### Expected Behavior

I expected the kubernetes version field to go back to what it was originally.

### Rancher Desktop Version

b65193d0

### Rancher Desktop K8s Version

1.23.5

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Rocky Linux 8.5

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by jandubois** [comment]
This will be obsolete with the new modal preferences dialog in #2373
