### ISSUE TITLE
Epic: Make sure Rancher Desktop works properly without a network connection

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2130]
This is also the first step towards airgap operation, but for this epic the scenario is:

First:
* [x] #1701
* [x] #2408

Rancher Desktop has been installed on a laptop while connected to the network. **It has been run at least once**, so k3s and images have been downloaded to the local cache.

* [x] #2409
* [x] #2548
* [ ] #1358

Bonus features to allow "Reset Kubernetes and Images" and "Factory Reset" while offline:
* [ ] #1808

For later:
* [ ] #2645

**Comment by johnthagen** [comment]
Related to

- #888

**Comment by gaktive** [comment]
Closing. All open items are in the Next milestone for continued work.
