### ISSUE TITLE
Epic: CLI Part 3

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2131]
This continues the CLI Ecosystem Epic from #1896 

This third epic continues to focus on providing commands that are required to use `rdctl` for testing Rancher Desktop itself.

The API version should remain at `v0` and we will still consider the CLI experimental until we have redesigned the `list-settings` command to provide human-readable output that matches settings to the options that can be specified in the `set` command.

Bug fixes:
- [x] #2143 
- [x] #2159
- [x] #2327 (assigned to @Nino-K)

Features (details not yet worked out):
- [ ] #1974
- [ ] Add `rdctl wait` command

**Comment by ericpromislow** [comment]
Acceptance criteria for `rdctl factory-reset`:

## Cleaning up after itself:

After running a factory-reset operation, whether from the UI or from `rdctl`, the following files should be deleted or cleaned up afterwards.

On macOS:
* All of `~/.rd` 
* All of ~/Library/Applications/rancher-desktop
* All of ~/Library/Caches/rancher-desktop unless told not to (see below)
* All of ~/Library/Preferences/rancher-desktop
* The lima VM should be deleted (run `limactl ls` to verify afterwards).
* The docker-X symbolic links should be removed from `~/.docker/cli-plugins`.
* The docker context `~/.docker/contexts/meta/b547d66a5de60e5f0843aba28283a8875c2ad72e99ba076060ef9ec7c09917c8` should be deleted.
* The settings adding `~/.rd/bin` to the `.*rc` files from the following list should be deleted:
```
	        ".bashrc",
		".bash_profile",
		".bash_login",
		".profile",
		".zshrc",
		".cshrc",
		".tshrc"
```

On linux:
* All of `~/.rd` 
* All of ~/.local/share/rancher-desktop
* All of ~/.local/cache/rancher-desktop unless told not to (see below)
* All of ~/.config/rancher-desktop
* The lima VM should be deleted (run `limactl ls` to verify afterwards).
* The docker-X symbolic links should be removed from `~/.docker/cli-plugins`.
* The docker context `~/.docker/contexts/meta/b547d66a5de60e5f0843aba28283a8875c2ad72e99ba076060ef9ec7c09917c8` should be deleted.
* The settings adding `~/.rd/bin` to the `.*rc` files from the following list should be deleted:
```
	        ".bashrc",
		".bash_profile",
		".bash_login",
		".profile",
		".zshrc",
		".cshrc",
		".tshrc"
```

On Windows:
* The `rancher-desktop` and `rancher-desktop-data` WSLs should be gone (run `wsl --list` to verify)
* All of `%HOME%/AppData/Local/rancher-desktop` should be gone. This includes `distro`, `distro-data`, `logs`, and `cache`, unless we specify to keep existing k8s caches
* All of `%HOME%/AppData/Roaming/rancher-desktop` should be gone. This includs the `privisioning`, the `lockfile` , and (currently) four `yaml` and `json` configuration files.

## Invocation

* From the UI: Troubleshooting > Factory Reset: check or don't check "Keep cached K8s images" .  If they're kept, verify that on the next startup you don't see a prompt stating that k8s images are being downloaded.

* From the CLI: `rdctl factory-reset {FLAGS}`
- flags include `--verbose`, `--wait` (default true), and `--remove-kubernetes-cache` (default false)

If `... --wait=false --verbose=true` is specified, verify you don't see a prompt every 2 seconds where `rdctl` reports on progress waiting for key parts of Rancher Desktop to have shut down.

* Verify specifying `--remove-kubernetes-cache=false` and not specifying it have the same behavior 
* Verify specifying `--remove-kubernetes-cache=true` deletes the k8s cache files.

* Verify `rdctl factory-reset` works when Rancher Desktop is not running. If there are some of the files listed above, this should delete them.
