### ISSUE TITLE
WSL Integration - distro select option disabled

### ISSUE THREAD

**Issue by micheleietri** [rancher-sandbox/rancher-desktop#2137]
### Actual Behavior

Fresh Install (v1.3.0) kubectl 
docker correctly exposed on windows
Under WSL Integration it shows my Ubuntu-20.04 distro but select option is disabled
![image](https://user-images.githubusercontent.com/12233542/165908122-4f253172-bbb6-409e-881c-ba74dca744d8.png)

### Steps to Reproduce

Install rancher desktop v1.3.0
Move to wsl integration tab
try select distro to expose socket

### Result

unable to select distro

### Expected Behavior

Able to select distro and use docker/kube comand on wsl

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

v1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Enterprise 22H2 build 22598.200

### What CPU architecture are you using?

x64

**Comment by micheleietri** [comment]
Deleting default config under $HOME/.kube fixes the issue.
Just backup it, enable integration then merge the newly created one with the old one (or just set $KUBECONFIG to use many config files)

**Comment by divetta** [comment]
> Deleting default config under $HOME/.kube fixes the issue. Just backup it, enable integration then merge the newly created one with the old one (or just set $KUBECONFIG to use many config files)

I've tried this workaround and didn't work properly. I've tried to uninstall rancher desktop, reboot and install again, but the WSL Integrations still disable for both versions:

![image](https://user-images.githubusercontent.com/19962827/167745432-62bf56eb-175f-49a6-ae0d-6d777f8c169a.png)

I'm using the version 1.3.0 too.

**Comment by wozjac** [comment]
+1, same behavior observed with version 1.3.0

**Comment by Pikabanga** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/22037089/168996310-5c56b3f2-b853-4234-8c26-60b89dc33f43.png)

![image](https://user-images.githubusercontent.com/22037089/168996436-95aa283c-953f-4ce1-acc6-e56e8cb8995b.png)

![image](https://user-images.githubusercontent.com/22037089/168996390-601c8dc2-349b-47cf-8dd5-743425a3f993.png)

Please let me know if more information is required.

**Comment by mickem** [comment]
I also encountered this and deleting `.kube` solved it for me. 

Maybe a hint in the UI as to why it is disabled would be useful as I spent some time on google before I found this page.

**Comment by mickem** [comment]
For me all my WSL are version 2 so for sure not #2214 instead what was mentioned above about removing .kube fixed it. And there is no "hint" at all as to why the checkbox is disabled nor (that I could find) any error message anywhere. So adding some hint to the UI would make it much simpler to understand and fix.

**Comment by adamkpickering** [comment]
Another note: if you upgrade to 1.4, you will probably get better feedback even without #2360 being merged. There were some changes that went into 1.4 that I was unaware of that improve feedback regarding WSL integrations.

**Comment by jandubois** [comment]
#2360 has been merged in 1.5.0, so I'm closing this for now.

If anybody still has this issue with 1.5.1 or later, please re-open!
