### ISSUE TITLE
Capture missing steps for Linux dev environment setup

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#2142]
When we follow the steps to get a Linux dev environment setup, `npm install` fails. This is because RD, specifically the `ffi-napi` package, requires that certain utilities are on the system. We need to update this.

**Comment by rak-phillip** [comment]
This looks like a duplicate of #2058

**Comment by adamkpickering** [comment]
Closing, since this is a duplicate.
