### ISSUE TITLE
rdctl start fails after factory reset

### ISSUE THREAD

**Issue by chancez** [rancher-sandbox/rancher-desktop#2143]
### Actual Behavior

```
(⎈ |rancher-desktop:default) ~/p/w/hubble-timescape ❯❯❯ rdctl start --flannel-enabled=false                                                                                                                  pr/chancez/helm-custom-ca ⬆ ⬇ ✭ ◼
2022/04/29 10:24:27 Error trying to read file /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: open /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: no such file or directory
```

### Steps to Reproduce

- Start rancher desktop
- Perform factory reset
- use `rdctl start`

### Result

```
2022/04/29 10:24:27 Error trying to read file /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: open /Users/chancezibolski/Library/Application Support/rancher-desktop/rd-engine.json: no such file or directory
```

### Expected Behavior

Rdctl starts rancher-desktop, using default values for unspecified options, and does not error.

### Additional Information

```
(⎈ |rancher-desktop:default) ~/p/w/hubble-timescape ❯❯❯ rdctl version                                                                                                                                        pr/chancez/helm-custom-ca ⬆ ⬇ ✭ ◼
rdctl client version: 1.1.0, targeting server version: v0
(⎈ |rancher-desktop:default) ~/p/w/hubble-timescape ❯❯❯ which rdctl                                                                                                                                          pr/chancez/helm-custom-ca ⬆ ⬇ ✭ ◼
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/rdctl
```

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

n/a

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Darwin dune.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by chancez** [comment]
Also, when I started rancher-desktop manually, but did not select any of the options for Kubernetes version/containerd/dockerd and then ran `rdctl start --flannel-enabled=false`, the rdctl start worked, but then rancher-desktop restarted without a Kubernetes version set, and failed to start k3s.

**Comment by gunamata** [comment]
Looks like a macOS specific behavior.. Below steps worked for me on Windows.

- Start Rancher Desktop (1.3.0)
- Perform Factory Reset
- Accept defaults at the app relaunch screen
- Once the app is up, File -> Exit to close the app
- Run `rdctl start` from terminal
