### ISSUE TITLE
Kubernetes version is not filled in for a short while upon factory reset

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#2145]
### Actual Behavior

When starting RD after a fresh install or factory reset, the drop-down under "Please select a Kubernetes version:" is blank. If you click "Accept" and navigate to the "Kubernetes Settings" tab quickly, you'll see that the problem is there as well.

Everything starts fine though. Also, if you wait long enough on the first run modal, the k8s version gets filled in. And if you get to the "Kubernetes Settings" tab and see a blank version field, you can go to another tab and then come back to the "Kubernetes Settings" tab and it will be filled.

### Steps to Reproduce

1. Do a factory reset.
2. Start RD. Notice how the k8s version is blank, and then gets filled in.

### Result

The k8s version field is blank.

### Expected Behavior

The k8s version field should be filled in, in both the first run modal and on the "Kubernetes Settings" tab.

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Pop OS 20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by rak-phillip** [comment]
I can definitely reproduce and I'm finding that it takes about 8+ seconds to fetch the list of available k8s versions.. We seem to be waiting on `src/k8s-engine/k3sHelper.ts` for some reason

https://github.com/rancher-sandbox/rancher-desktop/blob/299efdbb0a5c6b891c3a2f9776d09cb21bc7eeff/src/k8s-engine/k3sHelper.ts#L440-L447

**Comment by rak-phillip** [comment]
This 8+ second delay definitely isn't present in v1.2.1.. 

I can see now that we were originally attempting to hide the delay with fetching by not rendering the first run window until we receive the list of k8s versions

https://github.com/rancher-sandbox/rancher-desktop/blob/7f55234ed26045597977089ef0ae3f84f1a0cd41/src/pages/FirstRun.vue#L110-L116

I don't think this is the right pattern, as we're just hiding that we're waiting for data by delaying when the window is shown. This behavior is probably what contributes to the long wait times that I've experienced during first run in the past. Ideally we'd display some indicator that we're waiting to get things ready before the first run..

**Comment by rak-phillip** [comment]
I created #2153 so that we can address the problem of better communicating that we're waiting before rendering the first run dialog.
