### ISSUE TITLE
DNF install fails on fedora 35 with 1.3.0

### ISSUE THREAD

**Issue by thawkins** [rancher-sandbox/rancher-desktop#2154]
### Actual Behavior

When updating or performing a clean install to 1.3.0 the following errors are displayed by DNF and no update is done, on a clean install, 1.2.1 is installed instead.

[thawkins@fedora ~]$ sudo dnf install rancher-desktop
[sudo] password for thawkins: 
Sorry, try again.
[sudo] password for thawkins: 
Last metadata expiration check: 0:01:56 ago on Sun 01 May 2022 01:01:48 PM PST.
Dependencies resolved.

 Problem: cannot install the best candidate for the job
  - nothing provides libX11-6 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libXcomposite1 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libXdamage1 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libXext6 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libXfixes3 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libXrandr2 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libasound2 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libatk-1_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libatk-bridge-2_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libatspi0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libcairo2 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libcups2 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libdbus-1-3 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libdrm2 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libexpat1 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libgbm1 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libgcc_s1 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libgdk_pixbuf-2_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libgio-2_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libglib-2_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libgmodule-2_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libgobject-2_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libgtk-3-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libpango-1_0-0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libxcb1 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides libxkbcommon0 needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides mozilla-nspr needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
  - nothing provides mozilla-nss needed by rancher-desktop-1.3.0-lp153.2.1.x86_64
==============================================================================================================================================================================================================================================
 Package                                                         Architecture                               Version                                                              Repository                                              Size
==============================================================================================================================================================================================================================================
Installing:
 rancher-desktop                                                 x86_64                                     1.2.1-lp153.4.8                                                      isv_Rancher_stable                                     355 M
Installing dependencies:
 SLOF                                                            noarch                                     20210217-2.git33a7322d.fc35                                          fedora                                                 217 k
 edk2-aarch64                                                    noarch                                     20211126gitbb1bba3d7767-1.fc35                                       updates                                                5.3 M
 openbios                                                        noarch                                     1:20200725-3.git7f28286.fc35                                         fedora                                                 307 k
 qemu                                                            x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-pr-helper                                                  x86_64                                     2:6.1.0-14.fc35                                                      updates                                                316 k
 qemu-system-aarch64                                             x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-aarch64-core                                        x86_64                                     2:6.1.0-14.fc35                                                      updates                                                4.5 M
 qemu-system-alpha                                               x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-alpha-core                                          x86_64                                     2:6.1.0-14.fc35                                                      updates                                                3.0 M
 qemu-system-arm                                                 x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-arm-core                                            x86_64                                     2:6.1.0-14.fc35                                                      updates                                                4.1 M
 qemu-system-avr                                                 x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-avr-core                                            x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.1 M
 qemu-system-cris                                                x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-cris-core                                           x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.1 M
 qemu-system-m68k                                                x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-m68k-core                                           x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.4 M
 qemu-system-microblaze                                          x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-microblaze-core                                     x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.5 M
 qemu-system-mips                                                x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-mips-core                                           x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 13 M
 qemu-system-nios2                                               x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-nios2-core                                          x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.1 M
 qemu-system-or1k                                                x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-or1k-core                                           x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.1 M
 qemu-system-ppc                                                 x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-ppc-core                                            x86_64                                     2:6.1.0-14.fc35                                                      updates                                                7.9 M
 qemu-system-riscv                                               x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-riscv-core                                          x86_64                                     2:6.1.0-14.fc35                                                      updates                                                6.5 M
 qemu-system-rx                                                  x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-rx-core                                             x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.1 M
 qemu-system-s390x                                               x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-s390x-core                                          x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.7 M
 qemu-system-sh4                                                 x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-sh4-core                                            x86_64                                     2:6.1.0-14.fc35                                                      updates                                                5.7 M
 qemu-system-sparc                                               x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-sparc-core                                          x86_64                                     2:6.1.0-14.fc35                                                      updates                                                4.7 M
 qemu-system-tricore                                             x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-tricore-core                                        x86_64                                     2:6.1.0-14.fc35                                                      updates                                                2.1 M
 qemu-system-xtensa                                              x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 15 k
 qemu-system-xtensa-core                                         x86_64                                     2:6.1.0-14.fc35                                                      updates                                                6.6 M
 qemu-tools                                                      x86_64                                     2:6.1.0-14.fc35                                                      updates                                                210 k
 qemu-user                                                       x86_64                                     2:6.1.0-14.fc35                                                      updates                                                 17 M
Skipping packages with broken dependencies:
 rancher-desktop                                                 x86_64                                     1.3.0-lp153.2.1                                                      isv_Rancher_stable                                     341 M

Transaction Summary
==============================================================================================================================================================================================================================================
Install  44 Packages
Skip      1 Package

Total download size: 454 M
Installed size: 1.6 G
Is this ok [y/N]: y
Downloading Packages:

### Steps to Reproduce

Using the following /etc/yum.repos.d file on fully up to date fedora 35 

[thawkins@fedora ~]$ more /etc/yum.repos.d/rancher-desktop.repo 
[isv_Rancher_stable]
name=Rancher stable packages (rpm)
type=rpm-md
baseurl=https://download.opensuse.org/repositories/isv:/Rancher:/stable/rpm/
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/isv:/Rancher:/stable/rpm/repodata/repomd.xml.key
enabled=1
[thawkins@fedora ~]$ 

perform a:

sudo dnf install rancher-desktop

### Result

On update, no version 1.3.0 is installed 

Remove version 1.2.1 and do a fresh install, version 1.2.1 is reinstalled after the error messages shown above are displayed. 

### Expected Behavior

Version 1.3.0 should be installed

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Fedora 35

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by adamkpickering** [comment]
Hello! As the docs say:
> Installing via .rpm Package
>
> Note: RHEL, Fedora, and related distributions package QEMU, which Rancher Desktop uses on Linux, differently than other distributions. To use Rancher Desktop on these distributions, please use the AppImage.
>
> To add the repository and install on openSUSE:
> ```
> sudo zypper addrepo https://download.opensuse.org/repositories/isv:/Rancher:/stable/rpm/isv:Rancher:stable.repo
> sudo zypper install rancher-desktop
> ```

Please use the AppImage on Fedora 35.

**Comment by thawkins** [comment]
Application AppImage not work, It fails to install the links to the cmdline tools in the users path.
