### ISSUE TITLE
Incorrect error message when `rdctl start` is run while a session is already running

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2159]
If you run `rdctl start` (may be by mistake), when you have a session running already, the command prints below message which is not correct.

```
rdctl start
Error: set command: no settings to change were given
Usage:
  rdctl start [flags]

Flags:
      --container-engine string     Set engine to containerd or moby (aka docker).
      --flannel-enabled             Control whether flannel is enabled. Use to disable flannel so you can install your own CNI. (default true)
  -h, --help                        help for start
      --kubernetes-enabled          Control whether kubernetes runs in the backend.
      --kubernetes-version string   Choose which version of kubernetes to run.
  -p, --path string                 Path to main executable.

Global Flags:
      --config-path string   config file (default C:\Users\GunasekharMatamalam\AppData\Roaming\rancher-desktop\rd-engine.json)
      --host string          default is localhost; most useful for WSL
      --password string      overrides the password setting in the config file
      --port string          overrides the port setting in the config file
      --user string          overrides the user setting in the config file
```

**Comment by ericpromislow** [comment]
The reason for this is by design -- if the user runs `rdctl start` when Rancher Desktop is running, it should be treated as if they typed `rdctl set...`. The problem is that `rdctl set` requires at least one argument. But in this case, they should get a warning message that it's already running. So: a legitimate bug.

**Comment by jandubois** [comment]
> if the user runs `rdctl start` when Rancher Desktop is running, it should be treated as if they typed `rdctl set...`

This is true, but if the command then detects any kind of errors, the error message should still say `rdctl start` and not `rdctl set`. The fact that both commands share the code when RD is already running is an implementation detail that should not be exposed, as it may be confusing to the user.

**Comment by Nino-K** [comment]
Just curious why can't we do this [check](https://github.com/rancher-sandbox/rancher-desktop/blob/dfd7771d468b9165051aef115858a2828a6634af/src/go/rdctl/cmd/start.go#L64) before we do [this](https://github.com/rancher-sandbox/rancher-desktop/blob/dfd7771d468b9165051aef115858a2828a6634af/src/go/rdctl/cmd/set.go#L55).

**Comment by ericpromislow** [comment]
I don't follow -- could you elaborate?
________________________________

**Comment by Nino-K** [comment]
Basically, what I'm referring to is if RD is already running and I do `rdctl start` I should get a more appropriate message `e.g RD is already running` as for the `rdctl set` would it make sense to make sure if RD is already running like how we do in the start before we call `doSetCommand`?
