### ISSUE TITLE
Epic: release automation

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#2161]
### Problem Description

Though the release process is mostly manageable by those who pull the levers, when it comes to building, signing, tagging and announcing, we should look at automating what we can so that others can do the release.

This may be complicated based on the platforms we have to target and having systems to do that but this ticket should have subtasks tied to what we can do to make this process available via push button.

#### Possible tasks
- [ ] #3434
- [x] Final smoke test: download binaries from draft release, make sure they are signed, do install, and start up a cluster. Could publish the release if everything passes. — #6691

**Comment by gaktive** [comment]
@mattfarina may have input based on his experiences, as with @gunamata.

**Comment by gaktive** [comment]
We will a script from @jandubois that should do this. Then we'll try with @mook-as so he can do a release (but not 1.9)

**Comment by mook-as** [comment]
We've done the release automation we intend to do for now; there isn't any manual steps that doesn't involve checking the output before proceeding.  Closing.
