### ISSUE TITLE
rancher-desktop leftovers after uninstalling

### ISSUE THREAD

**Issue by kockok** [rancher-sandbox/rancher-desktop#2167]
### Actual Behavior

docker cli not updating on MacOS.

### Steps to Reproduce

1. remove rancher-desktop from the application folder of my mac
2. type `docker info` in the terminal

### Result

```
docker info
Client:
 Context:    rancher-desktop
 Debug Mode: false
 Plugins:
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)
WARNING: Plugin "/Users/jason/.docker/cli-plugins/docker-buildx" is not valid: failed to fetch metadata: fork/exec /Users/jason/.docker/cli-plugins/docker-buildx: no such file or directory
WARNING: Plugin "/Users/jason/.docker/cli-plugins/docker-compose" is not valid: failed to fetch metadata: fork/exec /Users/jason/.docker/cli-plugins/docker-compose: no such file or directory

Server:
ERROR: Cannot connect to the Docker daemon at unix:///Users/jason/.rd/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Expected Behavior

Client:
 Context:    rancher-desktop <-- should not be rancher-desktop

### Additional Information

I removed rd and reinstalled docker desktop afterwards.

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

never use k8s 

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

the latest

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by mook-as** [comment]
On mac, there's no uninstaller; if you want to automatically remove things, please run a factory reset before deleting the application (though, in this case, that wouldn't _really_ help, as I believe #2128 didn't make it into v1.3.0).

As a workaround, please run `docker context use default` + `docker context rm rancher-desktop`.
