### ISSUE TITLE
umask doesn't take effect when docker creates volumes

### ISSUE THREAD

**Issue by schoeppi5** [rancher-sandbox/rancher-desktop#2180]
### Actual Behavior

With Docker and Docker-compose: When creating a new container which mounts a local directory, which doesn't exist yet, Docker creates the directory.
The directory gets created, as you would expect with the default permissions (0777) - umask (0022).
However, I can't change that.

If I go into the rancher-desktop WSL Distribution and run `umask`, it tells me

```bash
$ 0022
```

and I can change it here:

```bash
$ umask 0000
$ umask
0000
```

This does work. New files and directories will be created (in either Linux FS or the mounted Windows FS) with the default (777 for dirs or 666 for files).

But I can't get Docker to do the same, or persist this change. I've tried using the automount options in wsl.conf, adding

```text
[boot]
command = "umask 0000"
```

to the wsl.conf, adding

```bash
umask 0000
```

to the `profile` script in `%localappdata%\Programs\Rancher Desktop\resources\resources\scripts`. Nothing worked.

### Steps to Reproduce

In Powershell, run:

```powershell
$ docker run -d --rm -v $pwd/test:/test ubuntu:latest
$ wsl -d rancher-desktop --cd $pwd ls -l
```

### Result

The created *test* directory should have *0755* permissions.

### Expected Behavior

I should be able to change the umask used to create this directory

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.21.10

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows 11 Pro 10.0.22000 Build 22000

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
I believe `dockerd` manually sets the umask:

https://github.com/moby/moby/blob/2c7c092e279062b93d638edd4c88f21643f0c4ef/cmd/dockerd/daemon_unix.go#L48-L52

As such, an override is not possible.

As this is what upstream `dockerd` intended, we can't really do anything on our end to change this (unless I've mixed something up, of course).  As such, you'll probably discuss with them to change it.

**Comment by schoeppi5** [comment]
Thank you for the insight. Seems like I have to find some other option.
