### ISSUE TITLE
Rancher Desktop Application Crashes (Windows 10 VM)

### ISSUE THREAD

**Issue by amomin8646** [rancher-sandbox/rancher-desktop#2184]
Hello,

i am in process of setting up Rancher Desktop to conduct a tutorial on a VM (windows 10). I have concluded installation of Rancher Desktop on the machine with 8 GM of ram and 4 cpu allocated to the vm. 

Issue: When i attempt to run the Rancher Desktop, it simply crashes. The window opens for a brief moment and disappears almost instantly. 

Ask: Can someone guide me on how to overcome this behavior?

Regards,
Ayaz

**Comment by gunamata** [comment]
Do you have virtualization enabled on the VM?

![image](https://user-images.githubusercontent.com/59538726/167041738-4d7d6489-3ea9-42cf-8083-603ea7b7df20.png)

**Comment by amomin8646** [comment]
Hi,

Yes, both items highlighted above were/are enabled. However, the issue was with the VM i had downloaded. I reinstalled VM from msft developer page (https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) and now i am able to conduct the installation of Rancher Desktop (its on-going as i type).

Thank you for your prompt response.

Regards,
Ayaz

**Comment by gunamata** [comment]
Closing the issue. Feel free to re-open incase you run into any other problems with installation. 
Good luck with your tutorial!

**Comment by gunamata** [comment]
Can you please do **Troubleshooting -> Factory Reset** and try launching the app again. If you still see issues, then please share the application logs here. You can find logs at `%USERPROFILE%\AppData\Local\rancher-desktop\logs`

**Comment by amomin8646** [comment]
Hi,

After factory reset, the launch failure reports following log

2022-05-06T13:46:58.461Z: Registered distributions: Ubuntu
2022-05-06T13:46:58.575Z: Registered distributions: Ubuntu
2022-05-06T13:46:58.666Z: Registered distributions: Ubuntu
2022-05-06T13:46:58.873Z: WSL failed to execute wsl.exe --import rancher-desktop C:\Users\User\AppData\Local\rancher-desktop\distro C:\Users\User\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.21.tar --version 2: Error: wsl.exe exited with code 4294967295


Additionally, there is no log folder/file on the AppData path.
![image](https://user-images.githubusercontent.com/105017328/167147375-6dda3be1-cf85-488f-a959-0ec411fe3d60.png)


H

**Comment by amomin8646** [comment]
Actually - found it. See attached log folder
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/8641218/logs.zip)

**Comment by gunamata** [comment]
From the error code in your logs, it might be related to this https://github.com/microsoft/WSL/issues/5092 ? Please try the fixes suggested in the thread and see if it helps. Plus, as someone suggested on Slack, sometimes uninstalling the app, restarting the machine and then reinstalling might help too..

**Comment by gunamata** [comment]
Plus, Are you running on Win32 machine? If yes, then Rancher Desktop is not supported on 32 bit machines.

**Comment by amomin8646** [comment]
Its 64 bit system.

**Comment by amomin8646** [comment]
I tried most of the direction on the case #5092. Nothing works. However, i continuously see following. I verified under task manager that Virtualization is enabled. Not sure where to go next from here. 

Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install

**Comment by amomin8646** [comment]
Hi,

got it to work. It was having issues on VM. I ended up installing locally on my machine. 

Thank you for your assistance
