### ISSUE TITLE
How to mount a specific folder from my laptop into a kubernetes container

### ISSUE THREAD

**Issue by andreidiaconescu** [rancher-sandbox/rancher-desktop#2189]
Hello,
I would like an example of how to map a specific folder from my laptop into a kubernetes container, in Linux.

I have looked through the documentation and the faq and only found a mention of only 2 folder being shared by default: /home/$USER on Linux, and /tmp/rancher-desktop , but no example on how to use other folders and how to do this.

Thank you,
Andrei

**Comment by gunamata** [comment]
You can use provisioning scripts to accomplish this..

Create an `~/Library/Application Support/rancher-desktop/lima/_config/override.yaml` file with a provisioning script

**Example:**

```
provision:
  - mode: system
    script: |
      #!/bin/sh
      set -e

      # sample additional mounts
      mount bpffs -t bpf /sys/fs/bpf
      mount --make-shared /sys/fs/bpf
      mount --make-shared /sys/fs/cgroup
```

@jandubois , Please correct me if something is wrong in the above example.

**Comment by jandubois** [comment]
> Please correct me if something is wrong in the above example.

The edited version on Github is correct.

@andreidiaconescu the original message that you may have received as email notification is not, so please check back on Github!

**Comment by andreidiaconescu** [comment]
thank you,
it works
