### ISSUE TITLE
Install and configure credential helper inside the VM

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2202]

**Comment by ericpromislow** [comment]
Notes on what to do:
1. On the guest, cat '{"credsStore":"rancher-desktop"}' > /root/.docker/config.json
2. Test it with `nerdctl login`

**Comment by ericpromislow** [comment]
I assume you're only talking about the testing instructions. The `/root` partition doesn't seem to survive restarts of rancher-desktop, at least for lima.

**Comment by jandubois** [comment]
> The `/root` partition doesn't seem to survive restarts of rancher-desktop, at least for lima.

Oh, this is a bug; it should because it is like `/home`, but for `root`.

This should be done by `lima`, but I'll see if I can add this to RD for now.

**Comment by jandubois** [comment]
> I assume you're only talking about the testing instructions.

I'm sorry, I was confused. It is ok for the testing code to simply override the file. It is the installation part that should do proper changes because we want to persist the directory between restarts (see https://github.com/rancher-sandbox/rancher-desktop/pull/2250/files).

**Comment by ericpromislow** [comment]
Fixed by #2252
