### ISSUE TITLE
Clean up cache directory on version change

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#221]
I noticed that we include [desiredVersion](https://github.com/rancher-sandbox/rd/blob/0a45d87/src/k8s-engine/hyperkit.ts#L362) in the name of the cache directory inside the machine, just like on the host. However, we are not going to use it as a cache; even when you switch between 2 versions, we will always copy the currently required version in again.

The cached versions take up quite a bit of space:

```
$ du -h .tinyk3s/
406M	.tinyk3s//v1.20.2+k3s1
395M	.tinyk3s//v1.20.4+k3s1
408M	.tinyk3s//v1.20.0+k3s2
406M	.tinyk3s//v1.19.4+k3s2
406M	.tinyk3s//v1.19.5-rc1+k3s2
2.0G	.tinyk3s/
```

We have no mechanism for the user to clean them. So I would suggest we either use an unversioned cache directory name, or we delete and re-create it every time we change versions.

**Comment by mook-as** [comment]
👍 though we'll need to coordinate fixes from tinyk3s, since we're using `run-k3s` from there (and that's why we needed the extra directory). Though perhaps we can use a fork of the `run-k3s` script instead…

**Comment by mook-as** [comment]
Actually, now that I think about it, we don't _need_ to use `run-k3s` on mac; we could just copy the files into the correct place in the first place? Will need root, though.

**Comment by mook-as** [comment]
This is no longer relevant: on Lima, we just mount the host's cache directory into the VM directly, so there's nothing to delete.
