### ISSUE TITLE
Volume mount won't remount across docker restart in WSL2

### ISSUE THREAD

**Issue by wpwoodjr** [rancher-sandbox/rancher-desktop#2231]
**EDIT May 25, 2022**

Further testing shows that this bug occurs with any volume mount from a native WSL2 directory, not just ones that have soft links to a Windows directory, as described below.  If you mount a WSL2 directory as a volume in a Docker container, it stops working once Rancher is restarted.  If you mount a Windows directory as a volume in a Docker container, it will still work after Rancher is restarted.

### Actual Behavior

A volume mount which uses a soft link to mount a directory in Windows works OK when container is first run, but does not remount when the container is stopped then restarted.

Mounting a Windows volume in a Docker container doesn't work when specifying the volume's path as `/mnt/c/Users/...` but does work if you soft link from the WSL2 home directory.  Unfortunately the container cannot remount the volume after stopping and restarting it.

### Steps to Reproduce

```
$ pwd
/home/xxx

$ ls -lat win
lrwxrwxrwx 1 xxx xxx 46 Apr 21 19:55 win -> '/mnt/c/Users/xxx/projects/'

$ sudo -E /usr/local/bin/docker run -itd --restart=always -v /home/xxx/win:/home/xxx/work -v /var/run/docker.sock:/var/run/docker.sock linux-dev --hostname linux-dev --name linux-dev 
93dc4d62eae20d5de72e8cab1b0db51c1fc188c6c4577db8a4b876cff9a7dc97

$ docker stop linux-dev
linux-dev

$ docker start linux-dev
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/mnt/wsl/rancher-desktop/run/docker-mounts/aaad516c-8005-484e-be16-b6a867acf089" to rootfs at "/var/run/docker.sock" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: linux-dev
```

### Result

$ docker start linux-dev
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/mnt/wsl/rancher-desktop/run/docker-mounts/aaad516c-8005-484e-be16-b6a867acf089" to rootfs at "/var/run/docker.sock" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: linux-dev

### Expected Behavior

Container starts with volume mount intact.

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

n/a

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

OS Name	Microsoft Windows 10 Enterprise Version 10.0.19042 Build 19042

### What CPU architecture are you using?

x64

### Windows User Only

No

**Comment by wpwoodjr** [comment]
Thanks for the quick response!  I use the container as a quick 'n dirty way to get my environment up and running across different PCs, and also to experiment with installs and stuff that I might not want in my regular WSL environment.

I'm actually going to try starting it from Windows and see if that works.

**Comment by wpwoodjr** [comment]
Aha!  Starting the container from the Windows side of things using the Windows path for the volume (instead of starting it from WSL2) allows the container to be stopped and restarted with the volume re-mounting successfully.

**Comment by Maxinho96** [comment]
I am experiencing the same bug using bind mounts in docker-compose through WSL2.

**Comment by wpwoodjr** [comment]
Actually I tested and this same issue occurs when mounting a native WSL2 directory, not only when accessing a Windows directory.  After a Rancher restart, the mount fails and the container won't start:
```
$ docker start linux-dev
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/mnt/wsl/rancher-desktop/run/docker-mounts/8654144d-5f48-4fec-a60a-3ddd28f9b7af" to rootfs at "/var/run/docker.sock" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: linux-dev
```

**Comment by wolfymaster** [comment]
Has anyone heard of an update on this one or found a work-around? I notice that when I am in wsl and bind mount any directory into a container, if that container is restarted then it is missing all the files from the bind mount. Specifically, it looks like the bind mount is created at: `/mnt/wsl/rancher-desktop/run/docker-mounts/XXXXXXXXXXXX`. It does not use the wsl path I provided.

**Comment by Maxinho96** [comment]
> Has anyone heard of an update on this one or found a work-around? I notice that when I am in wsl and bind mount any directory into a container, if that container is restarted then it is missing all the files from the bind mount. Specifically, it looks like the bind mount is created at: `/mnt/wsl/rancher-desktop/run/docker-mounts/XXXXXXXXXXXX`. It does not use the wsl path I provided.

As a workaround you need to start the container from Poweshell, then you can use all the other commands from WSL, also restart, and it works.

**Comment by wolfymaster** [comment]
Upon further review - I think everything is working correctly - but the issue we are running into is due to [mungeContainersStartRequest](https://github.com/rancher-sandbox/rancher-desktop/blob/main/src/go/wsl-helper/pkg/dockerproxy/mungers/containers_create_linux.go#L303-L364) doing a[ look-up against the full container id](https://github.com/rancher-sandbox/rancher-desktop/blob/main/src/go/wsl-helper/pkg/dockerproxy/mungers/containers_create_linux.go#L308) which is stored in `docker-binds.json`
```
{
  "159bddfc-dfa4-4938-898c-1c0246e077e7": {
    "ContainerId": "e14f944aedfebf7ce2dfba98ae13450767a2a58dc50d8a87f5e02ac1b5fb7429",
    "HostPath": "/home/wolfy/code/test/"
  },
  ...
} 
```


If I perform a `docker start e14f944aedfebf7ce2dfba98ae13450767a2a58dc50d8a87f5e02ac1b5fb7429` the container comes up with the correct bind mounts - however using any other alias (ie the name or short id) is not found in the map and therefore the binds are not re-created.

**Comment by lystor** [comment]
The same problem is in 1.9.1 and 1.10.0.

**Comment by malylemireflo** [comment]
Same problem with 1.11.1 please re-open. Binding a WSL2 directory won't re-mount.

**Comment by jandubois** [comment]
PR #3496 fixed `docker start` with a container name. The other half of this report, mounts from a WSL directory breaking after Rancher Desktop restarts, is still open as #4286, and [this comment](https://github.com/rancher-sandbox/rancher-desktop/issues/4286#issuecomment-5629759542) there explains the cause and the workarounds.
