### ISSUE TITLE
Unable to run any container on windows

### ISSUE THREAD

**Issue by Luxvao** [rancher-sandbox/rancher-desktop#2243]
### Actual Behavior

Every time I try to run a container it downloads the image and then it outputs an error (I'm not sure if I'm doing the command wrong)

### Steps to Reproduce

nerdctl run -it debian

### Result

FATA[0052] no such file or directory

### Expected Behavior

I'd like it to download and run a image that I can use as a "linux environment"

### Additional Information

![image](https://user-images.githubusercontent.com/95533447/169560346-c4c1cf21-106c-4bd0-ada6-072580665d8f.png)

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home Version 21H2 Build 22000.675

### What CPU architecture are you using?

x64

### Windows User Only

No VPN, proxy, Special Firewall rules, Security Software or custom Activity directory features. I have nothing

**Comment by rak-phillip** [comment]
@Luxvao thanks for raising this issue 🙂

Are you running PowerShell/cmd as an administrator? It looks like you might run into issues when attempting to do so:

#1379
#819

**Comment by Luxvao** [comment]
> 

I am using administrator and doing it without it solved the issue! Thanks!

**Comment by Luxvao** [comment]
I was running as administrator, but running it as non administrator solved the issue! Thanks
