### ISSUE TITLE
`~/.rd/bin` management

### ISSUE THREAD

**Issue by dee-kryvenko** [rancher-sandbox/rancher-desktop#2246]
### Actual Behavior

The new `~/.rd/bin` way of managing binaries is a regression comparing to how it was previously (that's why I am creating it as a bug). It forces me to do all-in or all-out. That's obviously is never the case.  I would want to use my own `kubectl` and `helm` binaries, as local cluster is not the only cluster I am interacting with daily, and I need specific versions and I need to switch in between the versions. But I would want `nerdctl` and `rdctl` to be there for me. Also, as a side note, the `kubectl` version you ship with RD - probably is not compiled correctly, it does not work with the split-DNS properly like the version I get from `brew`.

Adding `~/.rd/bin` to `PATH` does not let you pick which from these binaries you do want to use, and which - you don't. That makes me do `rm -f ~/.rd/bin/{helm,kubectl}` every time I restart RD and it is getting annoying.

### Steps to Reproduce

1. `brew install kubectl`
2. Start RD
3. Enable automatic `PATH`

### Result

Observe `which kubectl` is not pointing to my `brew` version of `kubectl`.

### Expected Behavior

I want to be able to choose which `~/.rd/bin` binaries I want to use, like I was able to before.

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.20.15

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur 11.6.5

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
> Adding `~/.rd/bin` to `PATH` does not let you pick which from these binaries you do want to use, and which - you don't. That makes me do `rm -f ~/.rd/bin/{helm,kubectl}` every time I restart RD and it is getting annoying.

The "Automatic" setting is for users who don't know/care about the details. You can always select "Manual" and add the directory to the **end** of your `PATH` yourself. That way any versions you have installed locally take precedence over the ones shipped with RD.

The `kubectl` included in RD is actually a symlink to [kuberlr](https://github.com/flavio/kuberlr), which will automatically download and use a version of `kubectl` that is compatible with your cluster.

Could you please file a bug against `kuberlr` that shows how it doesn't work with split-DNS?

I'm going to close this bug report, as the new `PATH` mechanism works "as-designed", and allows the flexibility you are seeking by adding the directory manually.
