### ISSUE TITLE
Document Rancher Desktop

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#227]
We need some documentation on using Rancher Desktop.

This should include:

- How to set your k8s version
- Upgrading and downgrading k8s
- Building, pushing, and pulling images
- Using the port forwarding

For the time being these should be markdown files a docs directory. These can be skipped for building.

**Comment by sirredbeard** [comment]
@btat is working on this.

**Comment by gaktive** [comment]
A good portion of this is already live in https://docs.rancherdesktop.io/ (repo: https://github.com/rancher-sandbox/docs.rancherdesktop.io)

If other specific items are needed, we can file separate tickets for docs in https://github.com/rancher/docs unless we write material ourselves.

@btat -- let us know if any of the above is missing and requires new issues filed.

**Comment by btat** [comment]
> A good portion of this is already live in https://docs.rancherdesktop.io/ (repo: https://github.com/rancher-sandbox/docs.rancherdesktop.io)
> 
> If other specific items are needed, we can file separate tickets for docs in https://github.com/rancher/docs unless we write material ourselves.
> 
> @btat -- let us know if any of the above is missing and requires new issues filed.

@gaktive maybe we can keep the doc tickets on https://github.com/rancher-sandbox/docs.rancherdesktop.io?
