### ISSUE TITLE
Image scanning failed with the release candidate (1.3.0-298-gc1ed19db)

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2274]
I see below error message when I try scanning an image. I am on Windows 10 Enterprise. 

Logs from my machine.
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/8781422/logs.zip)

![image](https://user-images.githubusercontent.com/59538726/170558303-c136d3e1-a75a-48de-9545-690cea5400eb.png)

**Comment by gunamata** [comment]
Image scanning works for me in the same session. Not sure why didn't work when i tried few hours ago.

**Comment by mook-as** [comment]
I can see the error, from `images.log`:
```
2022-05-26T22:27:32.825Z: /usr/local/bin/docker-credential-rancher-desktop: source: line 5: can't open '/etc/rancher/desktop/credfwd': No such file or directory
2022-05-26T22:27:32.812Z        FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
        * unable to inspect the image (nginx:latest): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
        * unable to initialize Podman client: no podman socket found: stat /mnt/wslg/runtime-dir/podman/podman.sock: no such file or directory
        * error getting credentials - err: exit status 2, out: ``
```

I'm using containerd backend — is it failing to use our existing containerd?

**Comment by jandubois** [comment]
> `2022-05-26T22:27:32.825Z: /usr/local/bin/docker-credential-rancher-desktop: source: line 5: can't open '/etc/rancher/desktop/credfwd': No such file or directory`

How is this possible? This file should always be written as the VM is started.

**Comment by gunamata** [comment]
I see the error again.. It happens only with `containerd`.. But when i posted ~ 30 min back that it's working, I checked both `containerd` and `dockerd` images and scanning worked. 

After seeing Mark's message, I did switched to `nerdctl`, did `Reset Kubernetes & Images`, pulled an image, scanned and ran into the error again.

**Comment by gunamata** [comment]
Finally, after many many iterations, I figured out steps to reproduce the behavior in a consistent way. Here are the steps.

- Switch to `containerd`
- Click `Reset Kubernetes & Container Images`
- Pull a couple of images. I did `nerdctl pull alpine`, `nerdctl pull nginx`
- Try scanning the images and I see an error
- Click `Reset Kubernetes`
- Try scanning the images and it works now

I hope these steps help someone investigate the problem and find out the cause.

**Comment by gunamata** [comment]
With https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2397934188 I don't see the image scanning issue anymore.

**Comment by rak-phillip** [comment]
@gunamata I think this should be reopened 

I can still reproduce this issue in Window 10 Pro for both our RC 1.4.0 build and the build you mentioned above. I'm unable to scan images using `containerd` while I can scan without issue using `moby`

**Comment by gunamata** [comment]
Image scanning failed again on today's build (https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2411965629) .
With this version, `nerdctl pull alpine`  took a very long time to complete, and I see the 2 warning messages at the beginning of the pull command.

```
WARN[0132] cannot get auth config for authConfigHostname="index.docker.io" (refHostname="docker.io")  error="error getting credentials - err: exit status 28, out: ``"
WARN[0265] cannot get auth config for authConfigHostname="docker.io" (refHostname="docker.io")  error="error getting credentials - err: exit status 28, out: ``"
```

Logs from this session.
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/8809650/logs.zip)


I then tried the Eirc's PR from Friday (https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2397934188) and I don't see the image scanning error, the `nerdctl pull` was quick as usual, and I don't see the error message at the beginning of the pull command. 

Logs from this session.
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/8809729/logs.zip)



Btn, I am testing on an Azure VM (Win 10 Pro)

**Comment by gunamata** [comment]
Tested `image scanning`, `nerdctl login/logout`, `Multiple images delete` features with the latest main (https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2418491873) on Win 10 Pro. All these features work with this build.
