### ISSUE TITLE
OpenSUSE: 1.4 RC test build never comes up as front window

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2277]
### Actual Behavior

Start `rancher-desktop` from the terminal window, typing `./rancher-desktop &`

The window always comes up behind other existing windows for other applications.

### Steps to Reproduce

See above.

### Result

See above.

### Expected Behavior

The window should appear in the front (position 0 in z-order)

### Rancher Desktop Version

1.3.0-298-gc1ed19db

### Rancher Desktop K8s Version

n/a

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE 15.3

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment]
```
Operating System: openSUSE Leap 15.3
KDE Plasma Version: 5.18.6
KDE Frameworks Version: 5.76.0
Qt Version: 5.12.7
Kernel Version: 5.3.18-59.37-default
OS Type: 64-bit
Processors: 12 × Intel® Xeon® CPU E5-2620 v3 @ 2.40GHz
Memory: 15.5 GiB of RAM
```

**Comment by thehejik** [comment]
It's working for me on opensuse 15.3 with Gnome and on Plasma as well. Maybe take a look on KDE System Settings `Workspaces/Window Management/Focus` - I have selected `Click to focus` there.

**Comment by ericpromislow** [comment]
Thanks -- "Click to Focus" is my current setting (which is the default).

I've only noticed this with Rancher Desktop, but I'm not running many other apps on the SUSE box: Terminal, Firefox, emacs. Other randomly selected apps come up at the top of the z-order. It's just Rancher Desktop (and a separate first-time-only modal dialog it creates).

— Eric
________________________________

**Comment by ericpromislow** [comment]
I no longer see this.
