### ISSUE TITLE
Test Plan 1.4: Windows 10 Pro: Test #42 - Default credential helper is not configured

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#2279]
### Problem Description

1. Ensure RD is closed (completely, not just the window) and DD is closed and uninstalled.
2. Ensure that ~/.docker/config.json has the following contents:

 `{"credsStore": "desktop"}`

3. Start RD. Wait for all steps to complete.

**Expected Result**

~/.docker/config.json should have the credsStore key configured as follows:

Windows: "wincred"

### Additional Information

FAIL

After starting RD, credstore is not set to `wincred`

{"credsStore":"desktop"}

**Comment by jandubois** [comment]
This can happen if for whatever reason you still have `docker-credential-desktop.exe` installed (and on your `PATH`).

I would assume that uninstalling DD would uninstall the `desktop` helper as well, but maybe double-check?

**Comment by ericpromislow** [comment]
Could be a dup of #2280

**Comment by ericpromislow** [comment]
This is a non-issue. Rancher desktop manages the contents of `/root/.docker/config.json` on the VM, but not the user's own version of this file.
