### ISSUE TITLE
Display warning if CLI tools are shadowed in the PATH

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#228]
On macOS we install symlinks for `helm`, `kim`, and `kubectl` into `/usr/local/bin`.

However, it is possible that the user has other instances of the tool in directories earlier in the `PATH`, so they would not run the version we install/link. We don't want to push our versions to the front of the `PATH`, but ideally we would like to display a warning.

Not sure if this is possible though, as the `PATH` setting will be determined by `launchd` and not by the user's shell if the app is lauched via e.g. `Finder.app`.

Just for reference I want to mention again that there is also another mechanism to get bundled tools onto the PATH on macOS:

```
$ ls -l /etc/paths.d/
total 24
-rw-r--r--  1 root  wheel  23 24 Jan  2020 MacGPG2
-rw-r--r--@ 1 root  wheel  51 26 Apr 14:59 at.obdev.littlesnitch
-r--r--r--  1 root  wheel  47 19 Oct  2020 com.vmware.fusion.public

$ cat /etc/paths.d/com.vmware.fusion.public
/Applications/VMware Fusion.app/Contents/Public

$ ls -l "/Applications/VMware Fusion.app/Contents/Public"
total 1912
lrwxr-xr-x  1 root  wheel      29 29 Apr 22:17 containerd -> ../Library/vkd/bin/containerd
lrwxr-xr-x  1 root  wheel      41 29 Apr 22:17 containerd-shim-crx-v2 -> ../Library/vkd/bin/containerd-shim-crx-v2
lrwxr-xr-x  1 root  wheel      47 29 Apr 22:17 docker-machine-driver-vmware -> ../Library/vkd/bin/docker-machine-driver-vmware
drwxr-xr-x  5 root  wheel     160 25 Mar 05:55 include
-rw-r--r--  1 root  wheel  823376 25 Mar 06:17 libvixAllProducts.dylib
-rw-r--r--  1 root  wheel  149333 25 Mar 05:55 open_source_licenses.txt
lrwxr-xr-x  1 root  wheel      22 29 Apr 22:17 swagger.zip -> ../Library/swagger.zip
lrwxr-xr-x  1 root  wheel      23 29 Apr 22:17 vctl -> ../Library/vkd/bin/vctl
lrwxr-xr-x  1 root  wheel      17 29 Apr 22:17 vmrest -> ../Library/vmrest
lrwxr-xr-x  1 root  wheel      16 29 Apr 22:17 vmrun -> ../Library/vmrun
```

This mechanism relies on the `path_helper` tool that is invoked via the system-wide `.profile` files (so only affects shells created after the software has been installed):

```
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

We'll have a similar issue (`PATH` shadowing) on Windows, once we actually install the CLI utilities; I don't know what the proper way to detect this would be there.

**Comment by mook-as** [comment]
On Windows, the environment variables are just user-wide (that is, the same environment is used across graphical apps and command-line ones), so just checking out own environment is enough.  We add entries to the `PATH` in the installer, so we don't have to worry about dynamic configuration, I believe.
