### ISSUE TITLE
Deleting multiple images does not finish

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2289]
### Actual Behavior

When deleting multiple images at once, the image output pane never appears to finish.

![image](https://user-images.githubusercontent.com/3977982/170781218-77cd261a-6afb-4e0b-a941-0054e0fcbac2.png)

### Steps to Reproduce

- Running containerd
- `nerdctl -n k8s.io pull alpine`
- `nerdctl -n k8s.io pull python`
- Go to image management screen
- Switch to the `k8s.io` namespace
- Check `alpine:latest`, `python:latest`, `rancher/klipper-helm:v0.6.4-build…`, and `rancher/klipper-helm:v0.7.1-build…`
- Click `Delete` (button at the top)
- Accept deletion of two images (`alpine:latest` and `python:latest`)

### Result

- Output appears in the Image Output pane (as expected)
- The button to close the output never appears
- It is no longer possible to switch to a different page (`WSL Integration`, `Kubernetes Settings`, etc.)

### Expected Behavior

- Output appears in the Image Output pane
- Eventually, the button to close the output appears.

### Additional Information

- The images are deleted successfully; `nerdctl -n k8s.io images` no longer shows them.
- Closing the window, and then opening it again (via the tray icon) shows that the images are removed.

### Rancher Desktop Version

1.3.0-298-gc1ed19db

### Rancher Desktop K8s Version

1.21.5

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home 21H2 (Build 22000.708)

### What CPU architecture are you using?

x64

### Windows User Only

Hyper-V virtual machine.

**Comment by mook-as** [comment]
I cannot reproduce the issue using the moby backend.

**Comment by mook-as** [comment]
For the focus issue: @ericpromislow says there's an issue calling things like `alert` from the renderer process; presumably that's what we're doing in the confirmation dialog?

**Comment by rak-phillip** [comment]
My concern is that this issue is related to problems that we're having with `containerd` in Windows.. while I can't repro this issue in Windows 10 Pro, the difference between `containerd` and `moby` raises a flag.

I'm also seeing issues with scanning images via `containerd` in #2274

**Comment by mook-as** [comment]
I could not longer reproduce this issue (using build for aeb6c119). :(
