### ISSUE TITLE
Test Plan 1.4: Windows 10 Pro: Tests 6, 8, 9, 10, 12, & 13 - Cannot Install Helm Charts

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#2290]
### Problem Description

I cannot install charts with Helm in the 1.4 RC for Rancher Desktop. For example, when I try to run test plan 8:

```
helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" already exists with the same configuration, skipping

helm install --wait --timeout=20m wordpress bitnami/wordpress --set=service.type=NodePort --set=volumePermissions.enabled=true --set=mariadb.volumePermissions.enabled=true
Error: INSTALLATION FAILED: failed to download "bitnami/wordpress"
```

I get the same behavior for Helm commands across all tests

### Proposed Solution

TBA

### Additional Information

I've attempted Factory Reset, Reset Kubernetes & Container Images, and Uninstalling/Reinstalling with no change in behavior.

**Comment by gaktive** [comment]
Not seen with @mook-as on Windows 11 Home. @gunamata saw a similar issue when adding a helm repo but one of @ericpromislow's PRs appears to resolve this.

**Comment by gaktive** [comment]
@rak-phillip to try `helm repo up` to see if that updates the Bitnami charts.

**Comment by rak-phillip** [comment]
`helm repo up` resolves this issue, closing
