### ISSUE TITLE
vtunnel: pick dynamic vsock ports

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2296]
### Problem Description

As  a follow up to #2281, we should pick af_vsock ports dynamically.

### Proposed Solution

- Pick a random `af_vsock` port on the host
- Spawn the vsock peer (`vtunnel`) from the vsock host (`vtunnel.exe`) with the random host ports
- Have the peer print the picked port on stdout

(This is just a sketch; other solutions are just fine too.)

**Comment by Nino-K** [comment]
I'm going to close this as we are in the process of retiring vtunnel process soon.
