### ISSUE TITLE
Dynamically select first run ram

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#232]
There's a big difference between someone having 8gb or 32gb of memory. If someone has little memory on their system we want to take only a little. If a user has more memory we can take more as the default. Suggestion, 25% of available ram up to a maximum of 6gb.

**Comment by jandubois** [comment]
> Suggestion, 25% of available ram up to a maximum of 6gb.

Feels on the low side for me; I would pick larger defaults and tell users to tune them down if they are running other resource-intensive apps, or keep 100s of browser tabs open. 😄 

Maybe we need do to some actual testing with both 8GB and 16GB Macs to check remaining system resources with various allocations.

For comparison, this is the memory Windows reserves for WSL by default:

>50% of total memory on Windows or 8GB, whichever is less; on builds before 20175: 80% of your total memory on Windows

**Comment by jandubois** [comment]
I've added the "macos" label because on Windows we don't offer CPU and memory settings; they can only be configured for all of WSL2 together and not on a per-distro basis.

**Comment by ericpromislow** [comment]
Merged in https://github.com/rancher-sandbox/rancher-desktop/pull/323#event-4838845650
