### ISSUE TITLE
Create rdctl vtunnel

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2327]
Same thing as #2301, but for the rdctl service endpoint. This is required to run `rdctl` from inside a WSL distro instead of `rdctl.exe` from the Windows side.

**Comment by mook-as** [comment]
Presumably, we'll need to keep the HTTP REST server (for API users)?

**Comment by jandubois** [comment]
> Presumably, we'll need to keep the HTTP REST server (for API users)?

Yes. I assumed the tunnel would just connect to the TCP endpoint on localhost, so this would continue to work automatically. Doesn't it?
