### ISSUE TITLE
Failed to start on opensuse tumbleweed

### ISSUE THREAD

**Issue by markusgod** [rancher-sandbox/rancher-desktop#2330]
### Actual Behavior

![image](https://user-images.githubusercontent.com/20001291/171961223-a0d60801-0020-4cec-9955-f614d8619622.png)

❯ cat /home/mark/.local/share/rancher-desktop/lima/0/ha.stderr.log
```
{"level":"debug","msg":"OpenSSH version 8.9.1 detected","time":"2022-06-04T01:10:07+03:00"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2022-06-04T01:10:07+03:00"}
{"level":"info","msg":"Starting QEMU (hint: to watch the boot progress, see \"/home/mark/.local/share/rancher-desktop/lima/0/serial.log\")","time":"2022-06-04T01:10:07+03:00"}
{"level":"debug","msg":"qCmd.Args: [/usr/bin/qemu-system-x86_64 -m 6144 -cpu host -machine q35,accel=kvm -smp 2,sockets=1,cores=2,threads=1 -boot order=d,splash-time=0,menu=on -drive file=/home/mark/.local/share/rancher-desktop/lima/0/basedisk,media=cdrom,readonly=on -drive file=/home/mark/.local/share/rancher-desktop/lima/0/diffdisk,if=virtio -cdrom /home/mark/.local/share/rancher-desktop/lima/0/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:34575-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:a8:b5:36 -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -parallel none -chardev socket,id=char-serial,path=/home/mark/.local/share/rancher-desktop/lima/0/serial.sock,server=on,wait=off,logfile=/home/mark/.local/share/rancher-desktop/lima/0/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/home/mark/.local/share/rancher-desktop/lima/0/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-0 -pidfile /home/mark/.local/share/rancher-desktop/lima/0/qemu.pid]","time":"2022-06-04T01:10:07+03:00"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2022-06-04T01:10:07+03:00"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2022-06-04T01:10:07+03:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/mark/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=mark -o ControlMaster=auto -o ControlPath=\"/home/mark/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=5m -p 34575 127.0.0.1 -- /bin/bash]","time":"2022-06-04T01:10:07+03:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 34575: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 34575: Connection refused\\r\\n\": exit status 255","time":"2022-06-04T01:10:07+03:00"}
{"level":"debug","msg":"qemu[stderr]: qemu-system-x86_64: -device virtio-vga: 'virtio-vga' is not a valid device model name","time":"2022-06-04T01:10:07+03:00"}
{"error":"exit status 1","level":"info","msg":"QEMU has exited","time":"2022-06-04T01:10:07+03:00"}
```

### Steps to Reproduce

Install rancher-desktop  via rpm on opensuse tumbleweed 20220602
```
sudo zypper addrepo https://download.opensuse.org/repositories/isv:/Rancher:/stable/rpm/isv:Rancher:stable.repo
sudo zypper install rancher-desktop
```

### Result

rancher-desktop fails to start

### Expected Behavior

successfully initialize

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSuse Tumbleweed 20220602

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by markusgod** [comment]
I've set zypper solver to zypp.onlyRequires = true, reinstalling qemu with all recommended packages fixed problem, there probably should be dependencies on qemu vga and other packages.

**Comment by jandubois** [comment]
@adamkpickering Please take a look!

**Comment by aitorpazos** [comment]
Same here, reinstalling qemu with `onlyRequires = true` didn't help, lima `serial.log` always hung in this log:
```
...
[   27.993678] Key type dns_resolver registered
[   27.993678] IPI shorthand broadcast: enabled
[   27.993678] sched_clock: Marking stable (27776986827, 206691717)->(28371455858, -387777314)
[   28.019499] registered taskstats version 1
[   28.020600] Loading compiled-in X.509 certificates
[   28.022107] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
[   28.026938] Loaded X.509 cert 'Build time autogenerated kernel key: 84461956e1584de539104e8b0204fbb09dcbd8b0'
[   28.029834] Key type ._fscrypt registered
[   28.030980] Key type .fscrypt registered
[   28.032055] Key type fscrypt-provisioning registered
```
and `ha.stderr.log` stays waiting for an available SSH connection until it times out:
```
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2022-07-23T13:44:23+02:00"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2022-07-23T13:44:23+02:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/<redacted>/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=<redacted> -o ControlMaster=auto -o ControlPath=\"/home/<redacted>/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=5m -p 33471 127.0.0.1 -- /bin/bash]","time":"2022-07-23T13:44:23+02:00"}
```
same results with Appimage or rpm from isv_Rancher_stable. Same result in version `1.3.0` and `1.4.1` as well.

**Comment by markusgod** [comment]
> Same here, reinstalling qemu with `onlyRequires = true` didn't help, lima `serial.log` always hung in this log:
> 
> ```
> ...
> [   27.993678] Key type dns_resolver registered
> [   27.993678] IPI shorthand broadcast: enabled
> [   27.993678] sched_clock: Marking stable (27776986827, 206691717)->(28371455858, -387777314)
> [   28.019499] registered taskstats version 1
> [   28.020600] Loading compiled-in X.509 certificates
> [   28.022107] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
> [   28.026938] Loaded X.509 cert 'Build time autogenerated kernel key: 84461956e1584de539104e8b0204fbb09dcbd8b0'
> [   28.029834] Key type ._fscrypt registered
> [   28.030980] Key type .fscrypt registered
> [   28.032055] Key type fscrypt-provisioning registered
> ```
> 
> and `ha.stderr.log` stays waiting for an available SSH connection until it times out:
> 
> ```
> {"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2022-07-23T13:44:23+02:00"}
> {"level":"debug","msg":"executing script \"ssh\"","time":"2022-07-23T13:44:23+02:00"}
> {"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/<redacted>/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=<redacted> -o ControlMaster=auto -o ControlPath=\"/home/<redacted>/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=5m -p 33471 127.0.0.1 -- /bin/bash]","time":"2022-07-23T13:44:23+02:00"}
> ```
> 
> same results with Appimage or rpm from isv_Rancher_stable. Same result in version `1.3.0` and `1.4.1` as well.

My phrasing in english is bad. onlyRequires should be set to false. 
You can also try run `zypper in --recommends  qemu  qemu-audio-pa qemu-extra`

**Comment by aitorpazos** [comment]
Same result :disappointed: , quicker to get to that line after installing `qemu-extra`(which I had never installed before), but still hanging in:
```
[    1.153430] Loading compiled-in X.509 certificates
[    1.155843] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input0
[    1.162644] Loaded X.509 cert 'Build time autogenerated kernel key: 84461956e1584de539104e8b0204fbb09dcbd8b0'
[    1.165502] Key type ._fscrypt registered
[    1.166634] Key type .fscrypt registered
[    1.167706] Key type fscrypt-provisioning registered
```

**Comment by adamkpickering** [comment]
@markusgod is this no longer an issue? If not, we should leave it open - we will get to it eventually.

**Comment by markusgod** [comment]
Well, at least it "works on my machine". Can't say for the others.

**Comment by aitorpazos** [comment]
Just given it another try using `rancher-desktop 1.6.0` installed from [OpenSUSE rpm package](https://docs.rancherdesktop.io/getting-started/installation/#installing-via-rpm-package) and it is working fine now 👍. [Logs hanging before](https://github.com/rancher-sandbox/rancher-desktop/issues/2330#issuecomment-1193114957) now outputs the following:
```
[    0.652978] Loading compiled-in X.509 certificates
[    0.655131] Freeing initrd memory: 6648K
[    0.660829] Loaded X.509 cert 'Build time autogenerated kernel key: 55fbf911099fc17887381a4f976f35e1dc3485f1'
[    0.664278] zswap: loaded using pool lzo/zbud
[    0.665605] Key type ._fscrypt registered
[    0.666736] Key type .fscrypt registered
[    0.668425] Key type fscrypt-provisioning registered
[    0.960618] ata1: SATA link up 1.5 Gbps (SStatus 113 SControl 300)
[    0.966628] ata1.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    0.971908] ata1.00: applying bridge limits
[    0.976508] ata1.00: configured for UDMA/100
[    0.979698] ata2: SATA link down (SStatus 0 SControl 300)
[    0.983020] ata5: SATA link down (SStatus 0 SControl 300)
```
