### ISSUE TITLE
Unable to connect to exposed ports using Windows host IP with Rancher Desktop

### ISSUE THREAD

**Issue by veleek** [rancher-sandbox/rancher-desktop#2334]
# Problem

I'm running a number of containers using Rancher desktop on Windows with a compose file.  From the same Windows machine I'm able to connect to `http://localhost:16686`, but it fails to connect to `http://192.168.0.100:16686`.  I've tried a bunch of different IP addresses from the Windows machine such as the `172...` addresses assigned by the docker host and the IP from the rancher WSL instance with no luck.  

Is there some configuration I can set to tell rancher to listen on all IPs instead of just localhost?

# Expected Result
I should be able to connect to exposed ports using any IP address associated with the host machine.

# Details

The containers expose a few different ports and I want to be able to connect to those containers from other machines on my network.  

Example:
* Windows machine
  * IP: `192.168.0.100`
  * Running Rancher Desktop using WSL exposing port `XXX`
* RaspberryPi
  * IP: `192.168.0.200`
  * Attempt to connect to `192.168.0.100:XXX` 

I'm using a docker compose that looks something like this.

```yaml
version: '3.7'
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1
    ports:
      - '16686:16686'  # <--- In this case, this is a web server
```
*Some details trimmed like extra ports*

Running `netstat -abno` shows that it's listening on that port but only on `127.0.0.1`.

```
TCP    127.0.0.1:16686          0.0.0.0:0              LISTENING
```

This does not appear to be a WSL limitation as running the same compose file using Docker Desktop allows me to connect to the host ip with no problems and `netstat` shows it's listening on all IPs as expected.

```
TCP    0.0.0.0:16686          0.0.0.0:0              LISTENING
```

Lastly, I tried switching the Container Runtime rancher was using from `containerd` to `dockerd (moby)` with no luck.  Using `dockerd` it didn't seem to expose the ports at ALL even though `nerdctl port <name>` showed them all as expected.

**Comment by veleek** [comment]
Okay, now after messing around with switching the container runitem, when running with `nerdctl` it doesn't seem to be listening externally at all.  `netstat` shows no listeners on any of the expected ports and I can't connect even to localhost.

**Comment by adamkpickering** [comment]
I believe that exposing ports externally is not supported at the moment. For more info please see https://github.com/rancher-sandbox/rancher-desktop/issues/1180.

Closing this for now. If the above isn't your issue, please comment here and we will reopen this.

**Comment by veleek** [comment]
@adamkpickering - Yup, that sounds exactly like this!  I searched a bunch but couldn't find any relevant issues, so thanks for pointing it out!  I guess my searching for host, localhost, ip, and expose didn't really limit my results down to anything helpful. 😂

**Comment by nicanorj** [comment]
It's a bit old topic but i've recentelly came accross the same issue. Once i've known that it's a Rancher limitation, i've decided try another approach. So the following solution worked for me.

Creating a port forwarding made my api running in container available through the network:

netsh interface portproxy add v4tov4 listenport=5000 listenaddress=0.0.0.0 connectport=5000 connectaddress=127.0.0.1

to check if the rule was created: netsh interface portproxy show all

Hope it helps someone!
