### ISSUE TITLE
Create a docker-credential-none

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2335]
### Problem Description

On Linux (where there isn't a good system credential store), we currently default to using `docker-credential-pass`; however, that requires user setup (including installing `pass` and possibly `p11tool`).

### Proposed Solution

We should create a `docker-credential-none` (and use it by default on Linux) that emulates using no credential helpers (i.e. writing to `~/.docker/config.json`), so that the user doesn't need to set up any credential helpers unless they wish to.

If they wish to, non-Linux users can use this too, of course, but it doesn't need to be configured by us.

### Additional Information

This is spun out from #2329 / #2332

**Comment by adamkpickering** [comment]
Unless I'm missing something, `secretservice` suits this purpose just fine. @jandubois you seem to want to understand it better before making it something we configure `docker` and `nerdctl` to use, and we should. But assuming that it is secure, and that we can't find any distros that we want to support that don't work with it, I don't see why we wouldn't make it a default when `pass` doesn't work, or isn't present. As I wrote in https://github.com/rancher-sandbox/rancher-desktop/pull/2210:

> I should add that I tested docker-credential-secretservice on 4 different distros: Ubuntu 18.04, Ubuntu 22.04, Fedora 35 and Rocky 8.5. It worked without any further config on all of them. This is what I based my decision to use secretservice by default off of. I didn't think it was worth it to take the time to understand how it worked in depth, even though I'm interested to find out. But this covers most of our Linux users.

Is there a reason we aren't considering `secretservice` for this?

**Comment by mook-as** [comment]
`secretservice` wouldn't work on machines without secret-service; IIRC, KWallet doesn't support it yet. (I might be wrong there, though.)

**Comment by adamkpickering** [comment]
[Here](https://specifications.freedesktop.org/secret-service/latest/ch01.html) it says that the Secret Service API is the successor to GNOME Keyring and KWallet - how would KWallet support it? I think we need to dig into it more. I did some research on it earlier, but I didn't achieve the level of depth that Jan wanted. I think that we should be able to get the information we need from https://specifications.freedesktop.org/secret-service/latest/.

**Comment by jandubois** [comment]
> We should create a `docker-credential-none` (and use it by default on Linux)

#2372 builds the `none` helper, but doesn't configure it unless it is running in CI.

@ericpromislow  I can't find another issue that would "use it by default on Linux". Shouldn't there be one? Or should this be at least added to #2401?

BTW, I think it should only be configured by default after testing `pass` and determining that it isn't functional. If it has been configured, we should be using `pass`.

Re-opening just to create the followup issue (or entry in the epic), then it can be closed again.

**Comment by ericpromislow** [comment]
The part about using `none` if `pass` isn't available has been written up in #2624
