### ISSUE TITLE
M1 - Rosetta for x86 vms/containers

### ISSUE THREAD

**Issue by clemenko** [rancher-sandbox/rancher-desktop#2339]
### Problem Description

Having to deploy x86 containers requires a flag `--platform linux/amd64` on a M1 mac. It would be nice to set a global flag for this.

### Proposed Solution

Add a global flag for  https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta?language=objc  or for `--platform linux/amd64` for every command?

**Comment by reppners** [comment]
Will support for automatic x86 translation via rosetta be added? This would be quite huge for my daily work.

**Comment by jandubois** [comment]
> Will support for automatic x86 translation via rosetta be added? This would be quite huge for my daily work.

@reppners This requires macOS 13 (Ventura), which has not been released yet. You should create a separate Github issue for this, as it is unrelated to this request.

**Comment by jandubois** [comment]
> Having to deploy x86 containers requires a flag `--platform linux/amd64` on a M1 mac. It would be nice to set a global flag for this.

Assuming you are using the moby engine, this should be possible with

```shell
export DOCKER_DEFAULT_PLATFORM=linux/amd64
```

For `nerdctl` there is a PR for similar functionality, but it hasn't been merged yet: https://github.com/containerd/nerdctl/issues/1154
