### ISSUE TITLE
Menu bar entry "Kubernetes is starting" should be not selectable

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#235]
Normally this entry would be greyed out and could not be clicked on (because selecting it does not trigger any action):

<img width="230" alt="Screen Shot 2021-04-30 at 2 58 55 PM" src="https://user-images.githubusercontent.com/78947/116758947-06f0df80-a9c6-11eb-965b-4001c0b2bd7c.png">

**Comment by ericpromislow** [comment]
Merged in https://github.com/rancher-sandbox/rancher-desktop/pull/344#event-4867072089
