### ISSUE TITLE
Buffer size for credential forwarder is too small

### ISSUE THREAD

**Issue by darianjd** [rancher-sandbox/rancher-desktop#2359]
### Actual Behavior

After the 1.4.1 release, I can no longer authenticate against more than one AWS ECR repo.

The first repo authenticated against, works fine, but authenticating into a subsequent ECR repo using the following command, produces the following error:

```
➜ aws ecr get-login-password --region us-east-1 --profile PROFILENAME | nerdctl --namespace k8s.io login --username AWS --password-stdin ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com
time="2022-06-09T13:23:20Z" level=fatal msg="error saving credentials: error storing credentials - err: exit status 52, out: ``"
```

### Steps to Reproduce

Authenticate against two distinct ECR repos like so:
```
➜ aws ecr get-login-password --region us-east-1 --profile PROFILENAME | nerdctl --namespace k8s.io login --username AWS --password-stdin ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com
```

### Result

```time="2022-06-09T13:23:20Z" level=fatal msg="error saving credentials: error storing credentials - err: exit status 52, out: ``"
```

### Expected Behavior

```Login Succeeded```

### Additional Information

_No response_

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.19.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

12.3.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

_No response_

**Comment by jandubois** [comment]
> Authenticate against two distinct ECR repos like so:

Can you clarify what this means? You normally authenticate against a registry, not a repo.

Did you mean you authenticate against 2 different ECR registries (with different account ids), that are both accessible with the same AWS profile? Or are these 2 different repos inside the same registry?

**Comment by jandubois** [comment]
Also could you check the `.docker/config.json` files on the host and inside the VM. It should look something like this:

```console
$ rdctl shell sudo cat /root/.docker/config.json
{
	"auths": {
		"123456789.dkr.ecr.us-west-2.amazonaws.com": {},
	},
	"credsStore": "rancher-desktop"
}
$ cat ~/.docker/config.json
{
	"auths": {
		"123456789.dkr.ecr.us-west-2.amazonaws.com": {
			"auth": "..."
		}
	},
	"credsStore": "osxkeychain"
}
```

If you have any other contents in there, could you share a redacted copy of it here?

**Comment by amanfredi** [comment]
@jandubois I'm a coworker of @darianjd  and also helping investigate this issue. I hadn't yet updated to 1.4.1 and so I've compared the results prior to upgrading and afterward.

Prior to upgrading to 1.3, the contents looked like this:
`cat ~/.docker/config.json`
```
{
  "credsStore" : "desktop"
}
```
`rdctl shell sudo cat /root/.docker/config.json`
```
{
	"auths": {
		"204518742547.dkr.ecr.us-east-1.amazonaws.com": {
			"auth": "an-auth-token"
		},
		"306760545897.dkr.ecr.us-east-1.amazonaws.com": {
			"auth": "another-auth-token"
		}
	}
}%
```

Immediately after updating to 1.4.1, the contents are this:
`cat ~/.docker/config.json`
```
{
  "credsStore": "osxkeychain"
}
```
`rdctl shell sudo cat /root/.docker/config.json`
```
{
  "credsStore": "rancher-desktop"
}
```

Running an aws auth command (on the host) such as the following prints the following error, and ~/.docker/config.json as well as lima's /root/.docker/config.json are unchanged:
`aws ecr get-login-password --region us-east-1 --profile marketplace | nerdctl --namespace k8s.io login --username AWS --password-stdin 306760545897.dkr.ecr.us-east-1.amazonaws.com`
```
time="2022-06-09T22:20:33Z" level=fatal msg="error saving credentials: error storing credentials - err: exit status 52, out: ``"`
```

If I use keychain access to manually create an osx keychain entry with a valid ECR auth token, I'm able to pull images from that repo with nerdctl.

**Comment by jandubois** [comment]
This is really curious, as it works for me (using just a single registry):

```console
$ AWS_ACCESS_KEY_ID=$(kc-env get AWS_ACCESS_KEY) AWS_SECRET_ACCESS_KEY=$(kc-env get AWS_SECRET_KEY) aws ecr get-login-password --region us-west-2 | nerdctl --namespace k8s.io login --username AWS --password-stdin 123456789.dkr.ecr.us-west-2.amazonaws.com
Login Succeeded
```

and it results in the `config.json` files I've shown above.

Given that you have no `auths` entries in your `/root/.docker/config.json` file at all, I take it this fails for you for the first `login` already.

For debugging purposes, can you try to add some bogus credentials to the keychain, e.g.

```console
$ echo '{"ServerURL":"https://registry.com","Username":"user","Secret":"password"}' | rdctl shell docker-credential-rancher-desktop store
$ echo https://registry.com | docker-credential-osxkeychain get
{"ServerURL":"https://registry.com","Username":"user","Secret":"password"}
```

Do both commands work for you, or do they throw any errors? The first command runs inside the VM and uses the `rancher-desktop` helper, which will use the forwarder to run the `osxkeychain` helper on the host and store the credentials.

The second command runs on the host and uses the `osxkeychain` helper to retrieve them again.

**Comment by amanfredi** [comment]
Ok @jandubois I think I have some more useful info on this.

The example commands you provided work fine.
However, I noticed that the error was citing a peculiar exit status (52) and also that the ECR password is quite long
```
aws ecr get-login-password --region us-east-1 --profile marketplace | wc -c
2293
```
In our case we're using AWS SSO assumed roles - I'm not sure if that or the region might impact the length of the token, but I realized I can force docker-credential-rancher-desktop to exit with status 52 by passing any json over 2049 characters long:

```
echo '{"ServerURL":"306760545897.dkr.ecr.us-east-1.amazonaws.com","Username":"AWS","Secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}' | rdctl shell docker-credential-rancher-desktop store
Error: exit status 52
```

**Comment by amanfredi** [comment]
A workaround for this seems to be interacting directly with docker-credential-osxkeychain.

```
echo "{\"ServerURL\":\"306760545897.dkr.ecr.us-east-1.amazonaws.com\",\"Username\":\"AWS\",\"Secret\":\"$(aws ecr get-login-password --region us-east-1 --profile marketplace)\"}" | docker-credential-osxkeychain store
```

**Comment by jandubois** [comment]
> I realized I can force docker-credential-rancher-desktop to exit with status 52 by passing any json over 2049 characters long

Thank you for digging into this! It is a bug in the credential forwarder: https://github.com/rancher-sandbox/rancher-desktop/blob/05872a8d37e0b5d53e5145fa391d9656e2e63dd9/src/main/credentialServer/httpCredentialHelperServer.ts#L27

I'm glad you found a workaround!

**Comment by ericpromislow** [comment]
I added two e2e tests -- one with a 5,242,880-char secret of that exceeds the 4MiB limit and returns a 413 code, and a second with a 5000-char key that succeeds, and we can read it back to verify that it was successfully stored.
