### ISSUE TITLE
Menu bar icon should be gray-scale only and not use color

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#236]
Follow the [human interface guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/). The icon could be dimmed (like the Wifi icon in the screenshot) when Kubernetes is not running, and be fully white (or black) when it is.

Right now it turns blue, which looks out-of-place among monochromatic icons:

<img width="103" alt="Screen Shot 2021-04-30 at 2 59 33 PM" src="https://user-images.githubusercontent.com/78947/116759082-559e7980-a9c6-11eb-9a35-f3051f2747c0.png">

**Comment by jandubois** [comment]
The same issue is also true for Windows. Although I see the Windows bluetooth icon is in colour, which looks somewhat weird. And the Windows Security icon isn't transparent but has a fixed white background, so everything looks a bit jarring.

<img width="120" alt="Screen Shot 2021-05-03 at 10 02 45 AM" src="https://user-images.githubusercontent.com/78947/116912009-7a7c3200-abfc-11eb-91c7-aeb664343cee.png">

Random observation: The "VMware Fusion" task bar icon on macOS is also in colour...
Also "Fantastical" (macOS) can *optionally* display a coloured icon, but defaults to a b&w one...

**Comment by jandubois** [comment]
Just noticed that in dark mode the greyed out icon is barely visible:

<img width="111" alt="Screen Shot 2021-05-12 at 5 39 11 PM" src="https://user-images.githubusercontent.com/78947/118061119-2a624580-b349-11eb-94f5-aed6a4551450.png">

**Comment by mook-as** [comment]
Looking at the docs, on mac we should be using a [template image](https://www.electronjs.org/docs/api/native-image#template-image).

Everything is inconsistent on Windows, as usual: I happen to have 3 Microsoft icons, and… well…
![Dark mode icons: Windows Defender, Bluetooth, OneDrive](https://user-images.githubusercontent.com/3977982/127696036-c3374281-36ba-4f59-9055-f40d48b521c6.png) ![Light mode icons: Windows Defender, Bluetooth, OneDrive](https://user-images.githubusercontent.com/3977982/127696092-e32bf548-0c0d-4a8b-82e1-1e53bcea132a.png)
