### ISSUE TITLE
Introduce a tool like Python's `bumpversion` to automate bumping versions and possible creating version tags

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#2361]
As discussed in the retro, it may be beneficial to use a tool like Python's `bumpversion` to automate incrementing various copies of RD's version when making a release. We have had a number of releases where incrementing the release was missed somewhere, resulting in confusion.

It may or may not be worth it:

**Comment by jandubois** [comment]
This is currently not planned. The only place where the version needs to be bumped is `package.json`, and this is mentioned in the "Release Steps" document.
