### ISSUE TITLE
Aspect ratio of the Rancher Desktop icon feels off

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#237]
The icon in the task switcher (with the blue box around it) looks too wide. If it ends up next to another big icon, then there is no spacer in between, akin to over-kerning in typography:
<img width="677" alt="Screen Shot 2021-04-30 at 3 23 24 PM" src="https://user-images.githubusercontent.com/78947/116760728-95fff680-a9ca-11eb-81ff-64a0c284c91c.png">

The icon in the menu bar (which is lacking the surround background box) is not too wide, but should be taller; it looks squashed and seems to be floating. Ideally it should use the full height, but if not, it should at least be vertically centered (maybe it is, but it doesn't look like it, compared to other icons next to it):

<img width="103" alt="Screen Shot 2021-04-30 at 2 59 33 PM" src="https://user-images.githubusercontent.com/78947/116760886-0b6bc700-a9cb-11eb-9ff9-e4db0687a102.png">

**Comment by mook-as** [comment]
The PR fixed the app icon, but didn't change the tray icon. Reopening so that if we decided the existing tray icon is okay, we get an explicit message saying so.

**Comment by jandubois** [comment]
Note that #236 is another issue about the tray icon (I think they are called notification icons on Windows, and menu bar icons on macOS, but not sure).

**Comment by mook-as** [comment]
Closing this, and handling the tray stuff in #236.
