### ISSUE TITLE
AppImage Crashing Version 1.4.1

### ISSUE THREAD

**Issue by edmooney** [rancher-sandbox/rancher-desktop#2377]
### Actual Behavior

When booting Rancher Desktop - I get the following error:

at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  command: [
    '/tmp/.mount_rancheEC6TC1/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl',
    'start',
    '--tty=false',
    '0'
  ]
}

last command run
/tmp/.mount_rancheEC6TC1/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl start --tty=false 0

======

Error: /tmp/.mount_rancheEC6TC1/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1-

### Steps to Reproduce

Open AppImage : AppImageLauncher rancher-desktop-1.3.0-Build2.1.glibc2.27-x86_64_8bd1a07f1ba8133ce71d8ebc0fe67ef3.AppImage

### Result

at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  command: [
    '/tmp/.mount_rancheEC6TC1/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl',
    'start',
    '--tty=false',
    '0'
  ]
}

last command run
/tmp/.mount_rancheEC6TC1/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl start --tty=false 0

======

Error: /tmp/.mount_rancheEC6TC1/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1-

### Expected Behavior

Expected the full application to load - Interface does load however Images, Port forwarding and kubernetes is not running

### Additional Information

[settings.log](https://github.com/rancher-sandbox/rancher-desktop/files/8884009/settings.log)
[lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/8884011/lima.log)
[lima.ha.stderr.log](https://github.com/rancher-sandbox/rancher-desktop/files/8884012/lima.ha.stderr.log)

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other (specify below)

### Operating System / Build Version

Manjaro Linux / 21.2.6 - KDE Plasma 

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by adamkpickering** [comment]
Hi @edmooney, is this still happening with 1.6.0?

**Comment by edmooneysh** [comment]
This looks to be corrected in v. 1.6.1 - Tested on Manjaro/KDE Plasma.
