### ISSUE TITLE
vtunnel: suppress usage message on error

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2384]
### Actual Behavior

On Rancher Desktop startup, I see in the logs:
```
Error: vsockListen, could not determine VM GUID: could not find vsock-peer process on any hyper-v VM(s)
time="2022-06-13T11:50:34-07:00" level=info msg="attempt to handshake with [bd9d92be-9ee1-495b-8693-4540a655c43e], goroutine is terminated"
Usage:
  vtunnel host [flags]
…
```

### Steps to Reproduce

Start Rancher Desktop

### Result

`vtunnel` usage message is dumped into the logs on error.

### Expected Behavior

On `vtunnel` error, only print the usage message if the parameters are incorrect.

### Rancher Desktop Version

`05872a8d37e0b5d53e5145fa391d9656e2e63dd9` (main)

### Rancher Desktop K8s Version

N/A

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 21H2 (Build 19044.1706)

### What CPU architecture are you using?

x64

### Windows User Only

N/A.

**Comment by jandubois** [comment]
@Nino-K We do want to remove the noise from the user's log file.
