### ISSUE TITLE
vtunnel.exe is marked as malicious by several antivirus apps

### ISSUE THREAD

**Issue by scauwe** [rancher-sandbox/rancher-desktop#2404]
Hi all,

after the latest update of rancher desktop (v1.4.1), Carbon Black Cloud detected a thread in vtunnel.exe (%appdata%\local\programs\rancher desktop\resources\resources\win32\internal\vtunnel.exe).
Access to this file was blocked. It seems that this file is:
 * not signed
 * marked as malicious by several antivirus apps 
![image](https://user-images.githubusercontent.com/5180743/174014483-3add021b-e17e-4d5d-a367-a015d0f32fda.png)

**Comment by jandubois** [comment]
I don't think the additional signatures will change anything, but we should sign the parts that we build ourselves.

We have reported the false positives from the VT report to the respective vendors, and at least one of them said they would update their signatures. The count on VT (for vtunnel.exe) is down to 1 now.

Thanks for also reporting to McAfee; hope this is resolved soon!

**Comment by whgibbo** [comment]
Just curious, did this resolve the issue with malware detection ?

**Comment by gunamata** [comment]
We have filed false-positive reports with the anti virus vendors wherever possible. Some of them updated their databases and, no longer flag the components as malicious. 

Have you tried the latest version of Rancher Desktop 1.5.1 and do you still see your anti virus program flagging Rancher Desktop malicious? May I know the antivirus that you are using?

**Comment by whgibbo** [comment]
> We have filed false-positive reports with the anti virus vendors wherever possible. Some of them updated their databases and, no longer flag the components as malicious.
> 
> Have you tried the latest version of Rancher Desktop 1.5.1 and do you still see your anti virus program flagging Rancher Desktop malicious? May I know the antivirus that you are using?

Was just checking before installing.. No issues so far 👍
