### ISSUE TITLE
Registries.yaml not working for private repositories

### ISSUE THREAD

**Issue by prom3theu5** [rancher-sandbox/rancher-desktop#2405]
### Actual Behavior

Can't pull from a http private registry, http response to https client error

### Steps to Reproduce

No matter what I do I can't get this to work (WSL2, Windows 10 - v1.4.1)
I have a vagrant machine, that has k3s running on it, with registries.yaml configured and working fine with the custom registry (Nexus3)

I've taken the same config, and dropped it in /etc/rancher/k3s on the rancher-desktop wsl instance. (containerd)

Next up i've tried

unticking kubernetes, and reticking
restarting rancher desktop
shutting rancher desktop down, and running wsl --shutdown
full restarting machine
yet I get the infamous https client to http server call error

I've even created a add-mirror.start file within the provisioning folder which creates the contents of the file, and that succeeds - the file is there, but still same error, cant pull the image

`add-mirror.start`

```bash
mkdir -p /etc/rancher/k3s
rm /etc/rancher/k3s/registries.yaml
cat <<EOF >/etc/rancher/k3s/registries.yaml
mirrors:
  "10.200.17.94:5001":
    endpoint:
      - "http://10.200.17.94:5001"
  "10.200.17.94":
    endpoint:
      - "http://10.200.17.94:5001"
EOF
```

### Result

http response to https client error with backoff due to image pull error

### Expected Behavior

Image is pulled and container starts

### Additional Information

Repository Nexus3 - Same mirror config works in k3s under Vagrant / a standard Ubuntu VM running under Hyper-V.

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

tried 1.23.3 all the way to 1.24.1

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise: 21H2

### What CPU architecture are you using?

x64

### Windows User Only

VPN Global Protect, using with experimentalHostResolver set to true, only way I could get internet access in my containers.

**Comment by prom3theu5** [comment]
I can manually pull images using `nerdctl <image> --insecure-registry --namespace k8s.io` and that works, but I can't do this in my dev workflow really - hundreds of microservices lol

**Comment by prom3theu5** [comment]
Worked around for now by adding a self signed cert to nexus, and using a provisioning `start` script to copy that into ca certs, and call update-ca-certificates before k3s starts ^^

**Comment by drriguz** [comment]
Same here, registry.yaml not working.

**Comment by chengleqi** [comment]
same here
