### ISSUE TITLE
Generate screenshots as part of the CI for docs

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2430]
As we rapidly develop Rancher Desktop, some screens change from time to time. It would be nice to generate screenshots automatically as part of the CI to keep the docs up to date always.

We would like to generate native screenshots for Linux, macOS, and Windows. If possible both light and dark themed ones.

Note that different platforms have different Preferences pages/tabs, so not every screenshot applies to all platforms.

* [x] Create screenshots of all preference pages
* [x] Create screenshots of all application pages
* [ ] Create screenshots of additional dialogs (first-run, asking for sudo, ...)
* [ ] Create screenshots of the installer pages
* [x] Add dark theme screenshots

**Comment by rak-phillip** [comment]
For automating screenshot collection with playwright, we might be able to look into the following apis:

* https://playwright.dev/docs/screenshots#full-page-screenshots
* https://playwright.dev/docs/test-snapshots

**Comment by torchiaf** [comment]
I am taking, thanks

**Comment by jandubois** [comment]
The screen shots are missing the window title and borders. Maybe this needs an OS-specific solution for each platform.

I've been able to do a full window capture on macOS with:

```console
screencapture -l $(GetWindowID  "Rancher Desktop" "Rancher Desktop - Preferences") prefs.png
```

`screencapture` is bundled with macOS, and `GetWindowID` is from https://github.com/smokris/GetWindowID.

<img width="836" alt="prefs" src="https://user-images.githubusercontent.com/78947/202002471-afe8cf31-1d62-4dce-9bbb-a64175299361.png">

Rancher Desktop needs to be activated before taking the screen shot, so the window controls and title bar are not greyed out/dimmed.

**Comment by torchiaf** [comment]
Example of screenshots (Main and Preferences windows):[screenshots.tar.gz](https://github.com/rancher-sandbox/rancher-desktop/files/10015552/screenshots.tar.gz)

**Comment by torchiaf** [comment]
How to take screenshots:  `npm run screenshots` on your dev environment.

**Comment by jandubois** [comment]
> The screen shots are missing the window title and borders. Maybe this needs an OS-specific solution for each platform.

I have some ideas on how to do this on Windows, just need some time to try it out in the next few days.

I won't look for a solution on Linux; somebody else needs to do the research!

**Comment by jandubois** [comment]
The screenshots need to pretend to come from the release version, not a dev build. We should fake this by setting environment variables, e.g.

```
RD_VERSION_STRING=1.7.0 RD_DEV_MODE=false npm run dev
```

So that the version on the General page doesn't show as `1.6.0-456-g12345678`.

Similarly, we don't want the badge on the Diagnostics page to show up, except on the screenshot of that page itself. And there we should not show the "Testing" diagnostic, but a regular one, e.g. by setting PATH management to manual, and then showing that `~/.rd/bin` is not on the `PATH`.

Longer term we also want to be able to fake a pending update on the General screen, but that doesn't have to be done right now.

**Comment by torchiaf** [comment]
Created a new Issue for remaining points: #3434
