### ISSUE TITLE
Design: Display when changing a preference will require Kubernetes restart

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#2441]
We need to alert the user when changing a preference will trigger a restart/reset. The differences between the actions can be summarized as:

- Restart (Restarts the VM to apply preferences)
- Reset (Destructive - will delete all workloads and configuration in addition to applying preferences)

Areas in preferences where this will need to be communicated:

- Changing Container Runtime (Restart)
- Kubernetes
  - Enable/Disable Kubernetes (Restart)
  - Change Kubernetes Version (Upgrade Restart/Downgrade Reset)
  - Change Kubernetes Port (Restart)
  - Enable/Disable Traefik (Restart)
- Virtual Machine
  - Changing CPU/RAM (Restart)

### Acceptance Criteria

- [x] User needs to explicitly confirm when that the VM will be `Reset` when applying settings

### Nice to have

- [ ] A visual indicator that warns the user when a `Restart` will occur

**Comment by mook-as** [comment]
More things that require a restart:
- WSL integration changes (not sure if we need a full restart here)
- Flannel configuration (if we intend to expose this)
- Host resolver (though we will probably never expose this, just enable it permanently later)
- Sudo enabled / disabled (though it's only really going from disabled to enabeld, to re-prompt)

**Comment by jandubois** [comment]
Just brainstorming (I may change my mind again):

We need a confirmation prompt when there is a loss of workloads (downgrade). This prompt should come when you press the "Apply" button.

For restarting the VM or just kubernetes it would be nice (but not required) to have an indication of what will happen (just so the user has an idea how long it will take). So maybe there can be a short status field to the side of the Apply button that will tell you "Requires VM restart" or "Requires kubernetes restart" (actual details up to Phil and UI team).

Ideally we should have an API in the engine that tells the UI what kind of activity is required (something like `apply-setting --dry-run`. That way the prerequisite knowledge isn't duplicated in two places.

**Comment by rak-phillip** [comment]
Closing this issue. We can wrap up remaining work in #2631
