### ISSUE TITLE
Design: Location of Reset Kubernetes action

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#2442]
The "Reset Kubernetes" and "Reset Kubernetes & Container Images" actions do not fit with the Apply/Revert model for preferences. 

We need to identify where this actions belongs (maybe under Troubleshooting or General... somewhere else?) and produce a design so that we have a clear understanding of how we expect users to interact with these actions.

### Acceptance Criteria
- [x] Move to troubleshooting
- [x] Decide if the split button is the best way to display Reset Kubernetes options or if splitting into two discrete buttons makes more sense
- [ ] Mockups are provided for Reset Kubernetes under troubleshooting

### Notes

- We might need something in the future where we could list all the containers and delete all the containers easily (see also #2115)
- We can move this button to a better location later on when we have supporting features

**Comment by rak-phillip** [comment]
@jandubois regarding your question if we would be the only app using a "hambburger" menu, this is very similar to how VSCode handles settings via the cog in the panel

![vscode-settings](https://user-images.githubusercontent.com/835961/175393748-9d456ea5-caa4-48a2-a80b-f73034006667.png)

![vscode-settings-expanded](https://user-images.githubusercontent.com/835961/175393763-a86d30f2-002d-41bf-92d7-e08165762378.png)

Of course, these options are accessible through the menu bar as well. If we do adopt this pattern, I think it makes sense to details all the required menu items like we did with preferences.

**Comment by jandubois** [comment]
> regarding your question if we would be the only app using a "hamburger" menu, this is very similar to how VSCode handles settings via the cog in the panel

I was mostly thinking about other Rancher Labs applications here, but you are right, we should also look at other popular desktop applications.

I think VS Code is mis-using the gear icon, which is pretty universally used for settings. The icon used to invoke a context menu of loosely related menu entries is typically the "hamburger icon" (3 horizonal lines).

I liked that the gear icon would invoke the settings dialog with a single click; now it turns into a click, a search for the string "Preferences" (or "Settings"), moving the cursor over there, and clicking again. So not much of a shortcut compared to using the app menu or the keyboard shortcut anymore. I also wonder if this would increase problems with accessibility.

I acknowledge that this is just a personal preference (hah), but I prefer using the single-click gear icon to bring up the setting dialog.

Unrelated: I would expect the menu to use `⌘,` and not `Command+Comma` on macOS:

<img width="197" alt="Screen Shot 2022-06-23 at 2 59 32 PM" src="https://user-images.githubusercontent.com/78947/175422751-c18cb61b-7245-4656-b58b-b420ac80bdc3.png">

**Comment by rak-phillip** [comment]
In interest of keeping things simple for #2373, how do we feel about approaching this by taking on the proposed actions:

> 1. In the main app context
> a) Put "Reset Kubernetes" and "Reset Kubernetes and all container images" functionality under the menu item "Troubleshooting"
> b) Clicking on Reset Kubernetes would open a pop-up warning/info with a checkbox to also restart all container images

I think doing this will give us something that's minimal and approachable while keeping the discussion open for further refactoring of Factory Reset. 

What do you think @kwwii @jandubois ?
