### ISSUE TITLE
Integration symlinks are not updated properly

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2456]
I cannot find any code that is handling the upgrade case. For normal installations we are not replacing existing symlinks unless they point to `~/.rd/bin` already, which they won't if you upgrade from an earlier version. For example:

```console
jan@zilicon ~ % ls -l ~/.docker/cli-plugins
total 0
lrwxr-xr-x  1 jan  staff  83  1 Mar 15:08 docker-buildx -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/docker-buildx
lrwxr-xr-x  1 jan  staff  88  1 Mar 15:08 docker-compose -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-compose
```

Neither of these are updated. Which is fine for `docker-compose` because it still points to the right place, but the `docker-buildx` symlink is broken (it is missing the `/bin` part of the directory.

So at the very least we should delete/replace dangling symlinks instead of leaving them in a non-working state.

**Comment by adamkpickering** [comment]
Unless something has changed recently, `docker-buildx` and `docker-compose` should not be symlinked to `~/.docker/cli-plugins/` directly from the resources directory. They should be symlinked to `~/.rd/bin/` first, and then from `~/.rd/bin/` to `~/.docker/cli-plugins/`. How did this happen? Is it possible that you were manually symlinking things? I can't think of any time where we symlinked docker CLI plugins directly from the resources directly to `~/.docker/cli-plugins/`.

**Comment by krumware** [comment]
On Windows installations, buildx is available in Powershell, but not WSL terminals.
Would that be related to this, or does it deserve its own issue?

**Comment by adamkpickering** [comment]
That deserves its own issue.

**Comment by jandubois** [comment]
> How did this happen? Is it possible that you were manually symlinking things?

I did not symlink them manually, but I have verified that at least 1.4.1 has already symlinked them to `~/.rd/bin`, so it must have been inherited from an even older release.

There should be very few (if any) upgrading from such an old version in the future, and we should catch this situation with our new diagnostics features, so I'm closing this issue now.
