### ISSUE TITLE
Utilizing -v instead of --mount with .devcontainers in VSCode for Workspace

### ISSUE THREAD

**Issue by ksummersill2** [rancher-sandbox/rancher-desktop#2465]
### Actual Behavior

Current Version: 1.4.1 .deb installation. 
Issue: Currently utilizing VSCode and .devcontainers. When trying to run inside of a container the workspace mapping throws an error of:
```
docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/development/proxmox/proxmox-k8s,target=/workspaces/proxmox-k8s --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/development/proxmox/proxmox-k8s --entrypoint /bin/sh docker.io/hashicorp/packer -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /development/proxmox/proxmox-k8s.
```
I was however able to run this same command successfully by utilizing -v instead of --mount. 

I am currently stuck at the moment and am not sure what else I can do to move forward. Please help. a

### Steps to Reproduce

Install 1.4.1 .deb rancher-desktop. Install development-containers extension on VSCode. Run within a container and see if the workspace mounts correct. 

### Result

docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/development/proxmox/proxmox-k8s,target=/workspaces/proxmox-k8s --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/development/proxmox/proxmox-k8s --entrypoint /bin/sh docker.io/hashicorp/packer -c echo Container started
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /development/proxmox/proxmox-k8s.

### Expected Behavior

A mounted workspace. 

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.26

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Pop!_OS 22.04 LTS

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by dpmerrill** [comment]
Unable to reproduce.  The --mount option works fine in my testing.
The error reported makes it seem like the source directory doesn't exist or has an access problem.  I would try this with the latest version of Rancher Desktop, and if you still have problems try setting the Docker log level to Debug and see if you get more information.
