### ISSUE TITLE
Allow RD to configure the port

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#248]
The user may already have minikube, kind, k3d, Docker Desktop, VMware fusion, etc. version of kubernetes installed, which might conflict with our default port `6443`.

We should both test that the port is still available before starting `k3s`, and also provide a preference setting to select a user-provided port.

**Comment by ericpromislow** [comment]
Closed in https://github.com/rancher-sandbox/rancher-desktop/pull/385#event-4942331627
