### ISSUE TITLE
buildctl` needs to be installed and `buildkitd` needs to be running - buildkitd OSX Big Sur

### ISSUE THREAD

**Issue by Naoero** [rancher-sandbox/rancher-desktop#2481]
### Actual Behavior

$ nerdctl build
ERRO[0000] `buildctl` needs to be installed and `buildkitd` needs to be running, see https://github.com/moby/buildkit  error="2 errors occurred:\n\t* failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exit status 1\n\t* failed to ping to host unix:///run/buildkit/buildkitd.sock: exit status 1\n\n"
FATA[0000] no buildkit host is available, tried 2 candidates: 2 errors occurred:
	* failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exit status 1
	* failed to ping to host unix:///run/buildkit/buildkitd.sock: exit status 1

Rancher Desktop: 1.4.1
on freshly installed OSX Big Sur.

### Steps to Reproduce

Install Big Sur
Install Rancher Desktop
Choose Moby
Run nerdctl build

### Result

 % nerdctl build            
ERRO[0000] `buildctl` needs to be installed and `buildkitd` needs to be running, see https://github.com/moby/buildkit  error="2 errors occurred:\n\t* failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exit status 1\n\t* failed to ping to host unix:///run/buildkit/buildkitd.sock: exit status 1\n\n"
FATA[0000] no buildkit host is available, tried 2 candidates: 2 errors occurred:
	* failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exit status 1
	* failed to ping to host unix:///run/buildkit/buildkitd.sock: exit status 1

### Expected Behavior

the build process should start and not throw errors

### Additional Information

 % nerdctl build            
ERRO[0000] `buildctl` needs to be installed and `buildkitd` needs to be running, see https://github.com/moby/buildkit  error="2 errors occurred:\n\t* failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exit status 1\n\t* failed to ping to host unix:///run/buildkit/buildkitd.sock: exit status 1\n\n"
FATA[0000] no buildkit host is available, tried 2 candidates: 2 errors occurred:
	* failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exit status 1
	* failed to ping to host unix:///run/buildkit/buildkitd.sock: exit status 1

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.23.8

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Big Sur 11.5.2 (20G95)

### What CPU architecture are you using?

x64

**Comment by AkihiroSuda** [comment]
> Choose Moby

You have to choose `containerd` to use nerdctl

**Comment by jandubois** [comment]
> > Choose Moby
> 
> You have to choose `containerd` to use nerdctl

Or use `docker build` if for whatever reason you must use Moby.
