### ISSUE TITLE
Improve the Factory-Reset button

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2494]
### Problem

In PR #2457 I had to left-align the `Factory Reset` button, because leaving it in the standard location cut off the drop-down text.

We need to either find a way to right-align this button, or explore an alternative, such as an Electron dialog box with a checkbox.

**Comment by gaktive** [comment]
<img width="1052" alt="Screen Shot 2022-07-19 at 1 46 37 PM" src="https://user-images.githubusercontent.com/11466788/179845515-3f85caff-0154-4fb6-ab3e-6671d7a49d7e.png">

Screenshot for reference (from @jandubois). He will file another PR for better wording around "Keep Container System Images"
