### ISSUE TITLE
Network routing problem to intranet servers on VPN

### ISSUE THREAD

**Issue by rcsilva83** [rancher-sandbox/rancher-desktop#2505]
### Actual Behavior

After starting Rancher Desktop, my WSL distros get `Destination Host Unreachable` error when pinging to intranet servers. As a result, I also can't use my corporate Docker registry with Rancher Desktop.

### Steps to Reproduce

1. Close Rancher Desktop and run `wsl --shutdown` to ensure a clean environment
2. Enter Ubuntu WSL distribution and run `ping corporate.docker.repo` with success:
```
ping docker.corporate.docker.repo
PING server.name (172.17.204.106) 56(84) bytes of data.
64 bytes from server.name (172.17.204.106): icmp_seq=1 ttl=61 time=34.7 ms
```
3. Start Rancher Desktop
4. Run again `ping corporate.docker.repo` inside Ubuntu WSL distribution with error.

### Result

```
ping corporate.docker.repo
PING server.name (172.17.204.106) 56(84) bytes of data.
From 172.17.0.1 (172.17.0.1) icmp_seq=1 Destination Host Unreachable
```

### Expected Behavior

```
ping docker.corporate.docker.repo
PING server.name (172.17.204.106) 56(84) bytes of data.
64 bytes from server.name (172.17.204.106): icmp_seq=1 ttl=61 time=34.7 ms
```

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

Disabled

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2

### What CPU architecture are you using?

x64

### Windows User Only

Microsoft Always On VPN.

**Comment by Nino-K** [comment]
@rcsilva83 can you please try enabling [experimental host resolver](https://github.com/rancher-sandbox/rancher-desktop/issues/1899#issuecomment-1109128277) and let us know if it fixes the issue.

Thanks

**Comment by rcsilva83** [comment]
@Nino-K it didn't work.

**Comment by rcsilva83** [comment]
Yes, @ripun . Indeed it seems to be a similar issue with different VPN software.

**Comment by Nino-K** [comment]
@rcsilva83 a few questions: 
1) Did you fully restart the rancher desktop after setting the `"experimentalHostResolver":true`?
2) What kind of VPN software are you using?

Thanks,

**Comment by rcsilva83** [comment]
@Nino-K 

> * Did you fully restart the rancher desktop after setting the `"experimentalHostResolver":true`?

Yes, I did

> * What kind of VPN software are you using?

Microsoft Always On VPN

**Comment by rcsilva83** [comment]
Just a hint: Podman with `podman machine` works well. Maybe you can see how it's done there.

**Comment by Nino-K** [comment]
@rcsilva83 please use our latest release 1.9 which includes a https://github.com/rancher-sandbox/rancher-desktop/issues/3810 for when using Rancher Desktop behind a VPN. You can enable it using:

```
rdctl set --experimental.virtual-machine.networking-tunnel=true
```

I'm going to close this issue, feel free to re-open it if the issue still persists.
