### ISSUE TITLE
WSL environment fails to start

### ISSUE THREAD

**Issue by alexgurman** [rancher-sandbox/rancher-desktop#2519]
Installed latest RD from scratch. version 1.4.1, in Windows 10 Enterprise. in WSL Integrations tab no distribution is present. Screenshots and logs attached

Running  wsl -l -v in Powershell shows:
  NAME                    STATE           VERSION
* rancher-desktop-data    Stopped         2
  rancher-desktop         Running         2

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/9087937/logs.zip)
![Capture - RD settings - 2](https://user-images.githubusercontent.com/3374431/178369521-e0f8609c-38ac-48e8-8928-5e4087cfd637.JPG)
![Capture - RD settings](https://user-images.githubusercontent.com/3374431/178369523-d6544a90-e133-4603-b052-406da7103b6e.JPG)
![Capture - wsl](https://user-images.githubusercontent.com/3374431/178369524-71c5813d-8044-4cc6-a279-83473e9c0663.JPG)
.

**Comment by jandubois** [comment]
The `wsl -l -v` command must be run from a Windows command prompt (or Powershell), not from a Linux shell. Or you have to explicitly call it `wsl.exe` to run the Win32 binary:

```console
$ wsl.exe -l -v
  NAME                    STATE           VERSION
* Ubuntu-20.04            Running         2
  rancher-desktop-data    Stopped         2
  openSUSE-Leap-15.2      Stopped         2
  rancher-desktop         Stopped         2
```

Note that Rancher Desktop only supports WSL2; if your distros are still using version 1, you have to version 2 (using `wsl --set-version ...`.

Please let us know if this fixes your issue!

**Comment by alexgurman** [comment]
Ubuntu distro is present in WSL integration, but not RD distros. I guess they don't have to?

**Comment by jandubois** [comment]
> Ubuntu distro is present in WSL integration, but not RD distros. I guess they don't have to?

No, they are not supposed to be used directly.

**Comment by alexgurman** [comment]
then there is no issue, thank you
