### ISSUE TITLE
Enable the HostResolver by default

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#2530]
### Problem Description

We would like to turn on the host resolver by default. This will allow our current users who are behind VPN to continue using Rancher Desktop. 

We have introduced this feature as an experimental feature in [v1.3.0](https://github.com/rancher-sandbox/rancher-desktop/issues/1899#issuecomment-1109128277) We would like to have it on at all times.

There are 3 groups of users who may be impacted by this change. 

1) New users who have never used Rancher Desktop, are not impacted by this at all. 
2) Existing users who used Rancher Desktop, however, never turned on the Host Resolver; this change will set their DNS workflow within Rancher Desktop to Host Resolver instead of `dnsmasq`. 
3) Existing users who used Rancher Desktop and enabled the `experimentalHostResolver`. They will no longer have to interact with this property in the config since it will be enabled by default. 

### Proposed Solution

Change the `experimentalHostResolver: false` to `hostResolver: true` in `%APPDATA%\Roaming\rancher-desktop\settings.json`.

### Additional Information

Note: Although the existence of the previous flag in the config (`experimentalHostResolver`) is harmless for groups 2 and 3 of our users mentioned above a factory reset should remove the old flag completely if they wish to remove it.

**Comment by jandubois** [comment]
> Note: Although the existence of the previous flag in the config (`experimentalHostResolver`) is harmless for groups 2 and 3 of our users

You need to double-check this with @mook-as to make sure we don't do `settings.json` validation that will throw an error on unrecognized settings.

**Comment by mook-as** [comment]
There should be no issues with extra settings (they just get ignored).  I believe it will even round-trip correctly.

**Comment by gaktive** [comment]
Done in the project board hopefully means closed here :)

**Comment by Nino-K** [comment]
It's done, the second PR was optional.
