### ISSUE TITLE
Prototype for Dashboard as a Plugin in the App (UX/UI)

### ISSUE THREAD

**Issue by manuelecarlini** [rancher-sandbox/rancher-desktop#2562]
Version 1.6.0 

The release goal of 1.6.0 includes the possibility to have dashboard/s incorporated in the main window of the Rancher Desktop App.
I am designing a prototype to discuss the best way to develop this feature and eventually have a final version of the visual outcome.

**Comment by gaktive** [comment]
This ticket is redundant based on other work to integrate with a dashboard.
