### ISSUE TITLE
CI Build Test: Warning message with `pull image` within a WSL distro

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2567]
I noticed a warning message while pulling an image within WSL distro. 
```
$ docker pull nginx
Using default tag: latest
docker-credential-secretservice: error while loading shared libraries: libsecret-1.so.0: cannot open shared object file: No such file or directory
latest: Pulling from library/nginx
461246efe0a7: Pull complete
a96aaf9a9ec3: Pull complete
650d8b758441: Pull complete
b138da793ac8: Pull complete
bb1705539683: Pull complete
b9ed43dcc388: Pull complete
Digest: sha256:db345982a2f2a4257c6f699a499feb1d79451a1305e8022f16456ddc3ad6b94c
Status: Downloaded newer image for nginx:latest
docker.io/library/nginx:latest
```
I am testing below CI build at the moment.
https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2679412106

My session configuration from `rdctl list-settings`

```
>rdctl list-settings
{
  "version": 4,
  "kubernetes": {
    "version": "1.21.0",
    "memoryInGB": 2,
    "numberCPUs": 2,
    "port": 6443,
    "containerEngine": "moby",
    "checkForExistingKimBuilder": false,
    "enabled": true,
    "WSLIntegrations": {
      "Ubuntu": true
    },
    "options": {
      "traefik": true,
      "flannel": true
    },
    "suppressSudo": false,
    "experimentalHostResolver": false,
    "hostResolver": true
  },
  "portForwarding": {
    "includeKubernetesServices": false
  },
  "images": {
    "showAll": true,
    "namespace": "default"
  },
  "telemetry": true,
  "updater": false,
  "debug": false,
  "pathManagementStrategy": "notset"
}

```

**Comment by jandubois** [comment]
What is the OS and OS version of the WSL distro?

There is not much we can do about this problem, except via documentation. The library is required by the upstream credential helper.

See the answers to https://stackoverflow.com/questions/55309743/docker-docker-credential-secretservice-on-rhel for ways to install the missing library on RHEL or Ubuntu.

**Comment by mook-as** [comment]
Using `docker-credential-secretservice` inside of WSL sounds unusual; secret service runs on top of D-Bus, so it's usually in places where a full desktop environment is available.

(Unless you're using the Windows 11 support for graphical interfaces; in that case I'd expect things to work.)

**Comment by gunamata** [comment]
I am using `Ubuntu 20.04.4 LTS`

Ok, It makes sense to document this. I created a PR https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/93 to add an item under `Troubleshooting Tips`

**Comment by jandubois** [comment]
I could reproduce this, and it also makes sense to me now:

When you run `docker` inside a WSL distro, it will use the credential helper configured in `~/.docker/config.json` inside this distro. When this isn't set, it defaults to `secretservice`, which doesn't work because some supporting library is missing.

I had a chat with @mook-as about this, and we will attempt to build a customer Linux `docker` binary especially for WSL, which will default the credential helper to `docker-credential-wincred.exe`, which should then run the local Win32 helper instead, which is exactly what we do with the credential forwarder.

There are some unknowns, but it seems likely that this would solve this issue to use a single trust store from all locations.

**Comment by jandubois** [comment]
The change solves the problem with pulling images while not being logged in, but it does not support logging into docker hub or a registry:

```console
jan@DESKTOP-4992680:~$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: jandubois
Password:
Error saving credentials: error storing credentials - err: exec: "docker-credential-wincred": executable file not found in $PATH, out: ``
jan@DESKTOP-4992680:~$ docker-credential-wincred.exe
Usage: docker-credential-wincred.exe <store|get|erase|list|version>
```

**Comment by jandubois** [comment]
Confirmed that it is working as expected!

**Comment by nathanweeks** [comment]
Still seems to be an issue in Rancher Desktop v1.6.0 on Windows 10 / WSL2 (Ubuntu 20.04) when the image is pulled as a result of `docker compose up`?

```
$ cat compose.yml 
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
$ docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
$ docker compose up
docker-credential-secretservice: error while loading shared libraries: libsecret-1.so.0: cannot open shared object file: No such file or directory
[+] Running 0/0
 ⠋ nginx Pulling                                                          0.0s
error getting credentials - err: exit status 127, out: ``
```

A workaround in this case is to use `docker pull` to obtain the image before `docker compose up`:
```
$ docker pull nginx:stable-alpine
stable-alpine: Pulling from library/nginx
... 
Digest: sha256:addd3bf05ec3c69ef3e8f0021ce1ca98e0eb21117b97ab8b64127e3ff6e444ec
Status: Downloaded newer image for nginx:stable-alpine
docker.io/library/nginx:stable-alpine
$ docker compose up
[+] Running 2/0
 ⠿ Network test_default    Created                                        0.0s
 ⠿ Container test-nginx-1  Created                                        0.0s
Attaching to test-nginx-1
...
```

**Comment by skomma** [comment]
I hit the same issue on Rancher Desktop 1.7.0 on Windows 11 / WSL2 (Ubuntu 20.04).

```
$ docker compose up -d                                                                                                                                 docker-credential-secretservice: error while loading shared libraries: libsecret-1.so.0: cannot open shared object file: No such file or directory                                                            [+] Running 0/0                                                                                                                                                                                                ⠋ ngrok Pulling                                                                                                                                                                                         0.0s
error getting credentials - err: exit status 127, out: ``
```

I installed `libsecret-1-0`, but got the following error:

```
$ docker compose up -d                                                                                                                                 [+] Running 0/1                                                                                                                                                                                                ⠙ ngrok Pulling                                                                                                                                                                                         0.1s error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`  
```

So my workaround is overriding `credsStore` config in `~/.docker/config.json`.

```
$ cat ~/.docker/config.json
{
 "credsStore": "pass"
}
```

And everything works fine.

The checksum of the installed docker binary matches with `docker-wsl-amd64` in https://github.com/rancher-sandbox/rancher-desktop-docker-cli/releases/tag/v20.10.21.

```
$ sha256sum /mnt/c/Program\ Files/Rancher\ Desktop/resources/resources/linux/bin/docker
040c7a46a6c451c37a0659282e19b657f3ef333b153f9debd602005bdae239fe  /mnt/c/Program Files/Rancher Desktop/resources/resources/linux/bin/docker
```

Does the docker binary still depend on `secretservice`? (refs: #2612)
