### ISSUE TITLE
Integrate with existing Rancher telemetry system

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#26]
Github Rancher Telemetry, tied into Grafana. Similar to a welcome ping.

Default is opt-in, but you can opt-out.

**Comment by gaktive** [comment]
Would need a UI component that before enabling, users could opt-out. Ties into a need for something new in Dashboard.

**Comment by mattfarina** [comment]
@jandubois will do the back end work and then mark/eric will perform the integration. Jan is assigned for the time being.

**Comment by jandubois** [comment]
> @jandubois will do the back end work and then mark/eric will perform the integration. Jan is assigned for the time being.

@mattfarina I'm confused; I thought I was only assigned to #305 for the backend parts; I have no idea what I'm supposed to do for this issue.

**Comment by jandubois** [comment]
Unassigned myself because without further instructions I wouldn't know what to do.

**Comment by gaktive** [comment]
Goal here for 0.4.0 is to come up with a domain name in anticipation of having a server to send data to. For the next version, we would then do #404 to have the backend to collect the telemetry.

**Comment by ripun** [comment]
@gaktive @jandubois  can we have default opt-out , please review https://github.com/rancher-sandbox/rancher-desktop/issues/2393
