### ISSUE TITLE
No option to select k8s version during fresh install, like we get after factory reset

### ISSUE THREAD

**Issue by prabalsharma** [rancher-sandbox/rancher-desktop#2601]
### Actual Behavior

For fresh installs, I am seeing option to just to set PATH (to automatic or manual) but no option to select Kubernetes version.
I get both option after a Factory Reset. 

### Steps to Reproduce

1. Factory reset to remove `cat ~/Library/Preferences/rancher-desktop/settings.json`
2. Install latest RD package from main
3. Replace the old RD with new one in applications 
4. start the app
5. wait for settings pop up to show up (it will not have an option to select k8s version)

### Result

Settings pop up just gives option to select PATH

### Expected Behavior

Settings pop up should give option to select PATH, Kubernetes  version, Enable Kubernetes and container engine

### Additional Information

Fresh install:

<img width="978" alt="Screen Shot 2022-07-21 at 12 48 03 PM" src="https://user-images.githubusercontent.com/3749546/180302770-f273afdc-0806-4fdd-af31-85a04e1f8f4e.png">

vs

Factory Reset:

<img width="973" alt="Screen Shot 2022-07-21 at 12 56 47 PM" src="https://user-images.githubusercontent.com/3749546/180304112-b8f2593f-40fe-4238-9038-095b4a36ce7c.png">

### Rancher Desktop Version

1.4.1-523-g0d7a816d

### Rancher Desktop K8s Version

1.24.3

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
I cannot reproduce this behaviour using 1.4.1-562-g8d799160 on macOS Intel.

 I run this script to "factory reset" without deleting cached images:

```console
$ catw rd-factory-reset
#!/bin/sh
osascript -e 'tell application "Rancher Desktop" to quit'
while osascript -e 'if application "Rancher Desktop" is not running then error 1' 2>/dev/null; do
    sleep 3
done
LIMA_HOME=$HOME/Library/Application\ Support/rancher-desktop/lima \
    /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl \
    delete -f 0
rm ~/Library/Preferences/rancher-desktop/settings.json
```

When I restart Rancher Desktop I get the expected dialog:

<img width="448" alt="Screen Shot 2022-07-25 at 11 55 02 AM" src="https://user-images.githubusercontent.com/78947/180853555-7e810d1b-365f-4adb-9401-643319dcdd23.png">

**Comment by prabalsharma** [comment]
ToDo: Show Phil how to reproduce this. 
There should only be a modal window and we should remove the pop up window. We will have to add more fields to modal window, as indicated in Expected Behaviour

**Comment by prabalsharma** [comment]
Acceptance criteria: User should not be able to close first run options window

**Comment by rak-phillip** [comment]
@prabalsharma We made some changes to address the first run dialog behavior in #4420 & #4411. Additionally, we now default to rcfiles with #4928, so the the Configure Path dialog should never be displayed. 

Can you review this issue and confirm whether or not it's still relevant?

**Comment by jandubois** [comment]
The Configure Path dialog no longer exists; we show the full first-run dialog if there are no settings (and no deployment profile).

I think this issue no longer applies.
