### ISSUE TITLE
Nerdctl build gives "FATA[0000] unrecognized image format"

### ISSUE THREAD

**Issue by GaryHebert** [rancher-sandbox/rancher-desktop#2610]
### Actual Behavior

When running `nerdctl build -t dev-node-aspose -f ./Dockerfile.dev .`, the build fails at:

```
[+] Building 0.5s (2/3)
 => [internal] load build definition from Dockerfile.dev                                                           0.0s
[+] Building 0.5s (3/3) FINISHED
 => [internal] load build definition from Dockerfile.dev                                                           0.0s
 => => transferring dockerfile: 274B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 245B                                                                                  0.0sl
 => ERROR [internal] load metadata for docker.io/library/node:16-bullseye-slim                                     0.5s
```

### Steps to Reproduce

Run the command `nerdctl build -t dev-node-aspose -f ./Dockerfile.dev .` with a Dockerfile.dev containing `FROM node:16-bullseye-slim`.

### Result

```
[+] Building 0.5s (2/3)
 => [internal] load build definition from Dockerfile.dev                                                           0.0s
[+] Building 0.5s (3/3) FINISHED
 => [internal] load build definition from Dockerfile.dev                                                           0.0s
 => => transferring dockerfile: 274B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 245B                                                                                  0.0sl
 => ERROR [internal] load metadata for docker.io/library/node:16-bullseye-slim                                     0.5s
------
 > [internal] load metadata for docker.io/library/node:16-bullseye-slim:
------
Dockerfile.dev:1
--------------------
   1 | >>> FROM node:16-bullseye-slim
   2 |
   3 |     WORKDIR /app
--------------------
error: failed to solve: error getting credentials - err: exit status 2, out: ``
FATA[0000] unrecognized image format
```

### Expected Behavior

Should build the image

### Additional Information

It used to work, before I switched the runtime to `dockerd (moby)` and switched back to `containerd`. I rebooted the PC after each switch.

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.23.8

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2 build 19044.1806

### What CPU architecture are you using?

x64

**Comment by adamkpickering** [comment]
I can reproduce this on Linux (Pop OS 20.04). I wasn't able to get the error to go away by switching back and forth between dockerd and containerd, or by doing a factory reset. However, it does work fine when using dockerd.

**Comment by jandubois** [comment]
This worked fine for me with on both macOS and Windows.

However, I was testing with the latest development version. I suspect that the error may be related to the `nerdctl` version; there are some known issues with the version 0.20.0 we shipped with Rancher Desktop 1.4.1.

Here is a way to manually update `nerdctl` to see if that fixes the issue:

First start a shell inside the Rancher Desktop VM by running `rdctl shell sudo -i` from the host command prompt (on Windows the `sudo -i` part is optional).

Inside the shell, run these commands:

```shell
wget https://github.com/containerd/nerdctl/releases/download/v0.22.0/nerdctl-0.22.0-linux-amd64.tar.gz
tar xvfz nerdctl-0.22.0-linux-amd64.tar.gz -C /usr/local/bin nerdctl
```

Verify by running `nerdctl version` (on the host again) that you have successfully upgrade to nerdctl 0.22.0, and then run your original `nerdctl build ...` command again.

@adamkpickering maybe you can verify if this fixes the issue for you on Linux as well?

**Comment by adamkpickering** [comment]
I'm terribly sorry, my above comment was intended for #2584. I cannot reproduce this issue on Linux or on Windows. @GaryHebert does Jan's suggestion help?

**Comment by GaryHebert** [comment]
Hello,

Thank you for your patience and for the support, you're very reactive.

After updating nerdctl to 0.22 it still give me the same message:

```
 D:\SourceCode\EvoOn\evo-excel-generator> nerdctl build -t dev-node-aspose -f Dockerfile.dev .
[+] Building 0.5s (2/3)
[+] Building 0.5s (3/3) FINISHED
 => [internal] load build definition from Dockerfile.dev                                                                                                                                                                     0.0s
 => => transferring dockerfile: 274B                                                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                                                            0.0s
 => => transferring context: 245B                                                                                                                                                                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/node:16-bullseye-slim                                                                                                                                               0.4s
------
 > [internal] load metadata for docker.io/library/node:16-bullseye-slim:
------
Dockerfile.dev:1
--------------------
   1 | >>> FROM node:16-bullseye-slim
   2 |
   3 |     WORKDIR /app
--------------------
error: failed to solve: error getting credentials - err: exit status 2, out: ``
FATA[0000] unrecognized image format
PS D:\SourceCode\EvoOn\evo-excel-generator> nerdctl version
Client:
 Version:       v0.22.0
 OS/Arch:       linux/amd64
 Git commit:    8e278e2aa61a89d4e50d1a534217f264bd1a5ddf
 buildctl:
  Version:      v0.10.3
  GitCommit:    c8d25d9a103b70dc300a4fd55e7e576472284e31

Server:
 containerd:
  Version:      v1.6.4
  GitCommit:    212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:      1.1.2
  GitCommit:    a916309fff0f838eb94e928713dbc3c0d0ac7aa4
```

**Comment by adamkpickering** [comment]
Ok, let us know how that goes. From what you posted, I'm wondering if you have a problem with your credential store. What is the value of the `credsStore` key in your `.docker/config.json` file?

**Comment by adamkpickering** [comment]
I'm running out of ideas on this one. Here are some other things you could try:
- verifying that wincred works by itself
- setting the `credsStore` key in `.docker/config.json` to "" (or deleting it), and then trying again
- running the `nerdctl build` command as `nerdctl --debug-full build ...`, you might get more helpful info that you can put here

**Comment by GaryHebert** [comment]
> I'm running out of ideas on this one. Here are some other things you could try:
> 
>     * verifying that wincred works by itself
> 
>     * setting the `credsStore` key in `.docker/config.json` to `""` (or deleting it), and then trying again
> 
>     * running the `nerdctl build` command as `nerdctl --debug-full build ...`, you might get more helpful info that you can put here

Thank you for your help. I changed nothing and the command now works. I suspect a network related issue but I really don't know.
