### ISSUE TITLE
Windows is showing CPU/memory change

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#262]
On Windows, when we switch to the Kubernetes Settings page, I get dialog boxes about CPU changing from 2 to 1, and memory from 2 to 1.9…something.

Since we don't actually do memory and CPU on Windows (we don't attempt to adjust them for the WSL VM), that seems non-scenical.

**Comment by ericpromislow** [comment]
Fixed at https://github.com/rancher-sandbox/rd/blob/3bde68037611df5cc166a30d67bb75bb5336d443/src/pages/K8s.vue#L20 as part of 1a0941d4eae8c3a97aa3c4fb1b389c61d1407006 ("disable system preferences on Windows")

**Comment by mook-as** [comment]
Actually, no, that's the problem: there's no actual VM stuff visible at all, but I do get `alert()`s about the change.

**Comment by ericpromislow** [comment]
OK, I've never seen this. Is there a repro?

**Comment by ericpromislow** [comment]
This could be useful information - it's letting us know the maximum available memory and CPUs, and that the previous or default requested value was too large. The reported memory size should be reduced to either 3 decimal values (nearest MiB) or just 1. But I don't see this being a serious problem.

**Comment by ericpromislow** [comment]
Closed and merged to main in 6db2d6c
