### ISSUE TITLE
1.5.0 Release: Virus Scanners

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2625]
### Actual Behavior

Virus Total (or rather, the scanners it uses) is flagging our build again.

Specifically, it's flagging:
- The zip build (Cylance, Ikarus)
- 

### Steps to Reproduce

1. Go to https://www.virustotal.com/
2. Upload the Windows setup exe.
3. Upload the Windows zip build (as a shortcut to uploading all the bundled executables).

### Result

Setup executable: https://www.virustotal.com/gui/file/c11c4c07ac136af52580f3c40a932e61401b655a9d208e0be9b764479e42e513/detection

Zip build: https://www.virustotal.com/gui/file/f4e3569c069f578ef2d06df90b6e195f5e54253f95004ab236b1713171fa725c/detection

### Expected Behavior

No (false) positives in any scanner.

### Additional Information

Table of flagged files:

Hash | File
--- | ---
[`f4e3569c`](https://www.virustotal.com/gui/file/f4e3569c069f578ef2d06df90b6e195f5e54253f95004ab236b1713171fa725c/detection) | Rancher Desktop-1.4.1-589-g171c29e1-win.zip
[`4d3a7cd4`](https://www.virustotal.com/gui/file/4d3a7cd4cdc0a33b91bcf394af9d8096d3657deab86b5354aae2c5c699894bb5) | `resources\resources\win32\bin\nerdctl.exe`
[`09ed84de`](https://www.virustotal.com/gui/file/09ed84de7b771cd31b8a40ba7823d6d6db4839bc19a254fb314ef418c93c6387) | `resources\resources\win32\internal\vtunnel.exe`
[`026404a7`](https://www.virustotal.com/gui/file/026404a77bd6a2db1025cc3ce1180820dbbb694aca955802b0ebd59c62a5b210) | `resources\resources\win32\internal\host-resolver.exe`
[`abd54d5a`](https://www.virustotal.com/gui/file/abd54d5a589c7745b67990b4fdbd489c922864e3725353faf6859ceed835dd4a) | `resources\resources\win32\bin\docker-buildx.exe`
[`68c7353e`](https://www.virustotal.com/gui/file/68c7353e0ffd40e53795d4ddbbb5f3e6ade4fcce00ca0161c5f46fc72aec7634) | `Rancher Desktop.exe` (The electron stub executable)

### Rancher Desktop Version

1.4.1-589-g171c29e1

### Rancher Desktop K8s Version

N/A

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 21H2 (Build 19044.1826)

### What CPU architecture are you using?

x64

### Windows User Only

N/A

**Comment by gaktive** [comment]
Need to do this with the release images. @gunamata has the list of who to contact.

**Comment by gunamata** [comment]
Scanned the Rancher Desktop 1.5.0 release bits using virustotal. Sent rescan request e-mails to vendors that flag RD bits as malicious.

**Comment by ganapathi004** [comment]
Hello, thank you for building this. The Windows exe files corresponding to releases 1.5.1, 1.5.0, 1.4.1, 1.3.0, and 1.2.1 are all flagged on VirusTotal by Trapmine. Is there anything we can try to make sure the binaries aren't flagged?

- 1.2.1 - https://www.virustotal.com/gui/file/3711e91ae84140a429d012b3a9bba19e87fab3e1929eb4faca2620dc7ec11d71
- 1.3.0 - https://www.virustotal.com/gui/file/92108cbbd8c98f99b00a608d8f7d21e12faeca76f16890585ef212cc5bf1c779
- 1.4.1 - https://www.virustotal.com/gui/file/39d79e4287998e483e387166b1447a7df78e441d6cb939166dcf9cd9436adc31
- 1.5.0 - https://www.virustotal.com/gui/file/c63edb28d68a96e1929625b16516c304c1b8acfe7380097e9a0cb5ef235b8ebf
- 1.5.1 - https://www.virustotal.com/gui/file/620e1fc8f671ef6d4a320010815195f2343fa84d51e28b7a1a0b9bd6fae00e4e

**Comment by jandubois** [comment]
> Is there anything we can try to make sure the binaries aren't flagged?

Yes, contact Trapmine and ask them to fix their models. It sounds like they just use machine learning models to detect issues, and it seems like they are getting it wrong.

It is quite annoying that they put the burden of training their models on the users and software developers to report false positives to them.

An alternative would be to simply ignore them.
