### ISSUE TITLE
Can't scan or delete anonymous images

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2626]
When you select a `<none>:<none>` image you get a popup with "Error trying to scan <none>:latest".

Clicking "Ok" on the modal dialog then wipes out the "FATAL image scan error: ..." from the app window, so I can't copy & paste it.

You also can't delete them.

**Comment by rak-phillip** [comment]
Related issues:

#2623
#2608

**Comment by rak-phillip** [comment]
We attempt to construct an image name out of `repository` and `tag` to use with trivy. Seeing as how these images have neither available, our only option might be to disable scanning altogether.

https://aquasecurity.github.io/trivy/v0.30.3/docs/references/cli/image/

**Comment by evertonlperes** [comment]
Sharing a "workaround" command that can help to manually remove all `<none>` dangling images from local env:
```
docker images | grep "<none>" | awk '{print $3}' | xargs docker rmi
```
I've stressed out this procedure and so far it seems reliable, removing only the images tagged as `<none>`.

**Comment by himslm01** [comment]
Attempting to delete <none>:<none> images is still an issue in 1.6.0

![image](https://user-images.githubusercontent.com/1175979/194536821-8e76f2ef-e686-481d-a1e7-4f81876c65d8.png)

![image](https://user-images.githubusercontent.com/1175979/194536924-ddd4d56c-6627-4774-a2f9-edc17082d39f.png)

![image](https://user-images.githubusercontent.com/1175979/194536975-40126f1e-f190-42d2-9cf9-d044092904bb.png)

![image](https://user-images.githubusercontent.com/1175979/194537072-833668c1-df27-4218-889a-2bc776c9c2de.png)

**Comment by jandubois** [comment]
For the time being we want to filter out any images with `<none>` or empty name because none of the actions (scan/delete) can be applied to them.

**Comment by rak-phillip** [comment]
I think filtering out the images is a fine approach for now but I still have this slight concern that there might be some underlying issue that we'll end up glossing over. For what reason could these images that are none or empty be dangling? Why does it seem to occur only for rancher images? Why does this only appear to be an issue with containerd?
