### ISSUE TITLE
Test case 8 is very flaky on Ubuntu 22.04 (deploy wordpress via helm)

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#2635]
### Actual Behavior

Test case 8 passed one time, and failed all of the rest.

### Steps to Reproduce

```
helm repo add bitnami https://charts.bitnami.com/bitnami
 
helm install --wait --timeout=20m wordpress bitnami/wordpress --set=service.type=NodePort --set=volumePermissions.enabled=true --set=mariadb.volumePermissions.enabled=true

kubectl get service/wordpress

```

Get portnumber from above command output. Then attempt to access it via `https://localhost:<port>` in browser. The application should be accessible.

### Result

There are a couple ways this can go:
- It succeeds.
- Both the mariadb pod and the wordpress pod come up, but when one attempts to access the app in the browser it is not reachable.
- Either the mariadb or the wordpress pod fail to come up.

### Expected Behavior

The pods should come up and the UI should be accessible.

### Rancher Desktop Version

171c29e1

### Rancher Desktop K8s Version

1.24.3

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by gaktive** [comment]
Will hold until #2593 is done and see if that helps.

**Comment by gaktive** [comment]
With #2593 done, @adamkpickering can you check if this is still happening in 1.5.1? We can close if so.

**Comment by adamkpickering** [comment]
I gave it a run and it appears to work fine.
