### ISSUE TITLE
Tab used to switch between containerd and moby is called "Container Runtime", but containerd and moby are container engines

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#2642]
### Actual Behavior

Containerd and moby are container engines. An example of a container runtime would be runc. There is a lot of confusion between the two terms, but the following link explains it: https://developers.redhat.com/blog/2018/02/22/container-terminology-practical-introduction#registry_server

We should rename the "Container Runtime" tab to "Container Engine".

### Steps to Reproduce

Open the preferences dialog.

### Result

N/A

### Expected Behavior

N/A

### Rancher Desktop Version

171c29e1

### Rancher Desktop K8s Version

1.24.3

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Pop OS 20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by jandubois** [comment]
Just a note that `rdctl` already uses the correct terminology:

```console
$ rdctl start --help
Starts up Rancher Desktop with the specified settings.
If it's running, behaves the same as 'rdctl set ...'.

Usage:
  rdctl start [flags]

Flags:
      --container-engine string     Set engine to containerd or moby (aka docker).
```

We should make sure that internal function and variable names are all consistent with this usage, and not just the user visible parts. Otherwise we will continue to mix up the terms.

**Comment by rak-phillip** [comment]
We define a collection of potential properties to change #1924. Does "Container Engine" work as the preferences menu item for all these properties or do we need something broader here?

**Comment by jandubois** [comment]
I think it works well for those (and I've just edited that list to use "Container engine configuration" for consistency.
