### ISSUE TITLE
Create initial UI to display the diagnostics

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2656]
We already have some designs from Manuele; just adding my old notes here:

## General

* Diagnostics are displayed in their own tab. The tab label gets a batch with the number of failed checks.

* The tab displays only failed checks that have not been muted. Each failed test has a checkbox that can be used to mute this check in the future.

* A checkbox to display "all" checked (including passed and muted ones).

* A button to "Refresh" all checks (in case the user fixed a configuration problem manually outside the app). It should show approximately when  the diagnostics were last refreshed (e.g. 1 minutes ago, 5 minutes ago, 2 days ago).

* A button to "Unmute" all muted checks.

* An indicator of the number of muted failed checks.

## List of checks

* Checks are grouped by category

* Each check has a pass/fail indicator and a mute checkbox.

* Each check has 0 or more "fix actions" below it; fix actions _may_ have a button to invoke a callback. The callback may update the diagnostics object in arbitrary ways (add more checks, change pass/fail of existing checks).

- [ ] [diagnostics] Remove @ts-ignore for BadgeState import

## Designs

https://xd.adobe.com/view/5a2be601-740a-41bc-8908-ec4da5208ffd-0f78/

**Comment by gaktive** [comment]
@rak-phillip to work with Manuele based on his proposed wireframes and add screenshots.

**Comment by gaktive** [comment]
Proposed wireframe: https://xd.adobe.com/view/7e428229-357f-4b58-8761-badb84e4a107-2b11/
Need to incorporate categorizations for checks but it should be a minor revision.

**Comment by gaktive** [comment]
@manuelecarlini now added to the repo.

**Comment by rak-phillip** [comment]
Updated wireframe: https://xd.adobe.com/view/5a2be601-740a-41bc-8908-ec4da5208ffd-0f78/
