### ISSUE TITLE
Create a Github Action to notify about new releases of external dependencies

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2658]
We want to automatically check periodically (e.g. once a day) if new versions of any of our external dependencies are available, and then either create a pull request to update `dependencies.yaml`, or an issue that explains the steps required.

First task is to collect all the different ways new releases may be specified for any of our dependencies. Probably incomplete list:

* releases on the Github repo (e.g. `helm`)
* releases on a different repo (e.g. new `nerdctl` or `cri-dockerd` release means we should update `alpine-lima` and `wsl-distro`)
* new tag on a different repo (e.g. new tag on `docker-cli` means we should update our fork and trigger a release by creating a tag)
* merges to `main` , more than X days ago, that have not yet been released (in `rancher-sandbox` repos) could mean we forgot to make a release

Once we have a complete list, we can figure out how to codify the rules in `dependencies.yaml`.

For some dependencies (e.g. `nerdctl` and `cri-dockerd`) it would be better if we bundle them with Rancher Desktop instead of baking them into the `alpine-lima` and `wsl-distro` images.

**Comment by mook-as** [comment]
From testing, it doesn't look like GitHub actions pick up workflows in subdirectories. (I was hoping we could do `.github/workflows/dependencies/helm.yaml`, etc. but it doesn't seem to get invoked.)

**Comment by jandubois** [comment]
Re-opening because I don't think all the special cases are covered in #2493 

> * releases on a different repo (e.g. new `nerdctl` or `cri-dockerd` release means we should update `alpine-lima` and `wsl-distro`.
> * new tag on a different repo (e.g. new tag on `docker-cli` means we should update our fork and trigger a release by creating a tag)
> * merges to `main` , more than X days ago, that have not yet been released (in `rancher-sandbox` repos) could mean we forgot to make a release

We should create a new Epic from these (or just a new story) and then close this issue again.

**Comment by adamkpickering** [comment]
The new epic is #3117.
