### ISSUE TITLE
`nerdctl` sometimes breaks failing to get a non-empty ServerAddress field

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2689]
### Actual Behavior

The nerdctl version bump in PR #2673 to v 0.22.2 broke `nerdctl run`:
```
$ nerdctl version
Client:
 Version:	v0.22.2
 OS/Arch:	linux/amd64
 Git commit:	2899222cb0715f1e5ffe356d10c3439ee8ee3ba4
 buildctl:
  Version:	v0.10.3
  GitCommit:	c8d25d9a103b70dc300a4fd55e7e576472284e31
$ nerdctl run --rm busybox ls -ld /bin
FATA[0000] expected ac.ServerAddress ("") to be "https://index.docker.io/v1/"
```

### Expected Behavior

This is what happens with version 1.4.1

```
$ nerdctl version
Client:
 Version:	v0.20.0
 OS/Arch:	linux/amd64
 Git commit:	e77e05b5fd252274e3727e0439e9a2d45622ccb9

Server:
 containerd:
  Version:	v1.5.11
  GitCommit:	3df54a852345ae127d1fa3092b95168e4a88e2f8

$ nerdctl run --rm busybox ls -ld /bin
drwxr-xr-x    2 root     root         12288 Jul 29 01:32 /bin
```

and

```
$ nerdctl run --rm --platform linux/amd64 --entrypoint ls busybox -ld /bin
drwxr-xr-x    2 root     root         12288 Jul 29 01:32 /bin
```

### Steps to reproduce
1. Select moby/docker, if needed
2. `docker login`
3. Select containerd
4. nerdctl run IMAGE

It's possible that `IMAGE` needs to be an unloaded image.

### Rancher Desktop Version

1.5.0

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS (happens with Windows as well)

## Workaround

`nerdctl login ... SAME CREDENTIALS`

**Comment by ericpromislow** [comment]
Upstream bug: https://github.com/containerd/nerdctl/issues/1300

**Comment by ericpromislow** [comment]
And now it's working again. Looks like it has something to do with the credentials helper.

**Comment by rak-phillip** [comment]
Encountered this one while developing in on openSUSE Tumbleweed. Difficult to say how I got into this state, but can confirm that `nerdctl logout` coupled with `nerdctl login` resolves the issue.

### Before

```
$ nerdctl pull busybox
FATA[0000] expected ac.ServerAddress ("") to be "https://index.docker.io/v1/"
```

![image](https://user-images.githubusercontent.com/835961/184032203-5839e1ac-8dfe-4d97-8091-24cbf5808b13.png)

### After

```
$ nerdctl pull busybox
docker.io/library/busybox:latest:                                                 resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:ef320ff10026a50cf5f0213d35537ce0041ac1d96e9b7800bafd8bc9eff6c693:    exists         |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:98de1ad411c6d08e50f26f392f3bc6cd65f686469b7c22a85c7b5fb1b820c154: exists         |++++++++++++++++++++++++++++++++++++++|
config-sha256:7a80323521ccd4c2b4b423fa6e38e5cea156600f40cd855e464cc52a321a24dd:   exists         |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.1 s   
```

![image](https://user-images.githubusercontent.com/835961/184032326-9fa2c028-b99a-4c73-a925-ced3915b8fa4.png)

**Comment by dawilliams** [comment]
I found the fix.
https://github.com/rancher-sandbox/rancher-desktop/issues/1633#issuecomment-1063315909

**Comment by ericpromislow** [comment]
@dawilliams I don't understand how that link points to a fix for this problem, but the manual fix is the following:
```
$ rdctl shell
$ sudo su -
# vi /root/.docker/config.json
```
Ensure the JSON contains the line `auths: { 'https://index.docker.io/v1/': {} }`

Might be worth doing the following to ensure the config is valid JSON:
```
# Still in the VM as root:
# apk add jq
# jq . /root/.docker/config.json
```

**Comment by jwsy** [comment]
@ericpromislow's fix worked for me!
I ran into this problem while switching between Docker Desktop and Rancher Desktop. 

Here's my `~/.docker/config.json` for reference
```json
{
  "credsStore": "none",
  "auths": { "https://index.docker.io/v1/": {} }
}
```
