### ISSUE TITLE
Offer silent autostart checkbox on Windows

### ISSUE THREAD

**Issue by worldofgeese** [rancher-sandbox/rancher-desktop#2693]
### Problem Description

Rancher Desktop currently requires copying a shortcut into the Startup folder of Windows if start-on-boot is desired. If a user follows these directions Rancher Desktop will start on boot with GUI pop-up. Most users won't need to interact with the GUI on reboot if autostart is desired.

### Proposed Solution

Offer a GUI checkbox to silently (into tray) start Rancher Desktop on boot.

**Comment by gaktive** [comment]
Hi! Thanks for filing this request.

We have an existing feature request for this in #1254 so I'll close this as a duplicate. For now, as a workaround, follow the steps in https://docs.rancherdesktop.io/faq/#q-how-can-i-add-rancher-desktop-to-the-startup-programs-list-on-windows:
> - Press Windows+R to open the Run dialog box.
> - Type `shell:startup` and then hit Enter to open the Startup folder.
> - Copy "Rancher Desktop" shortcut from Desktop and paste in Startup folder.
> - Restart your machine.

Let me know if that's sufficient for now until we can get this into the product.
