### ISSUE TITLE
No message when I cannot link kubectl

### ISSUE THREAD

**Issue by vestival** [rancher-sandbox/rancher-desktop#273]
In macOS

I cannot link kubectl 

<img width="941" alt="image" src="https://user-images.githubusercontent.com/6848398/117481113-c9aac580-af62-11eb-98bf-d6eaad803a29.png">

The reason is that kubectl is already installed (I did installed it with brew) but there is no message explaining that. If you could update the message with this info it would be great.

**Comment by mattfarina** [comment]
The UI is confusing for this. We need to clean this up.

When greyed out it means there is something else with that name in the location. You already have kubectl installed.

**Comment by ericpromislow** [comment]
Closed in https://github.com/rancher-sandbox/rancher-desktop/pull/320#event-4860861332
