### ISSUE TITLE
Rename WSL instance to 'rancher-desktop'

### ISSUE THREAD

**Issue by jonstelly** [rancher-sandbox/rancher-desktop#274]
It would make it more obvious if the WSL instance that gets created was called 'rancher-desktop' instead of 'k3s' to match the kubernetes config file entry.

Also, the Kubernetes Settings page has a progress bar but it would be really nice if it had some status text too, `Creating WSL instance '...'`, `Initializing ...`, or even just a static message while things are initializing would help, it seemed to spin for quite a while for me and I didn't know what it was working on.

**Comment by jandubois** [comment]
I reluctantly agree with renaming the distro. The short name has advantages when you are manually debugging, but this only applies to the RD developers, and not the users, who actually shouldn't poke inside the distro...

For better status / progress reporting we already have #225, so this issue should just cover the distro renaming.

**Comment by jonstelly** [comment]
FWIW, I'd prefer the full name but `rd` would also be fine by me.  Same for the kube config entry, I'd have no problem with `rd` showing up there.  It's a bit less descriptive but given the repository name here (and that rancher seems to love short-named products) I think less is more.

For a compromise on kube config you could name the context `rd` and leave the cluster and auth info as `rancher-desktop`, so a `kubectl config get-contexts` would make it clear that it's rancher desktop, and the name being short would make it easier to switch kubernetes contexts.

**Comment by jandubois** [comment]
I actually prefer `rancher-desktop` because we also use it as the directory name in a bunch of locations under `AppData`. I don't have Windows machine running right now, but here are things on my Mac:

```console
$ fd rancher-desktop
Library/Caches/rancher-desktop
Library/State/rancher-desktop
Library/Preferences/rancher-desktop
Library/Preferences/io.rancher.rancher-desktop.plist
Library/Application Support/KeyCue/Key Counts/rancher-desktop.plist
Library/Application Support/KeyCue/Application Icons/rancher-desktop.tif
Library/Application Support/rancher-desktop
Library/Application Support/CrashReporter/rancher-desktop_BB91A231-8B81-5794-8293-FC46153BEB40.plist
Library/Saved Application State/io.rancher.rancher-desktop.savedState
```

**Comment by ericpromislow** [comment]
Merged https://github.com/rancher-sandbox/rancher-desktop/pull/316#event-4821617482
