### ISSUE TITLE
rancher-desktop-guestagent fails to restart when using custom lima env variables that contain spaces

### ISSUE THREAD

**Issue by nalxnet** [rancher-sandbox/rancher-desktop#2760]
### Actual Behavior

When starting Rancher Desktop, starting kubernetes fails while restarting rancher-desktop-guestagent service.

The service fails to properly source custom lima env variables that contain spaces, since it uses `source /etc/environment` for env sourcing in [src/assets/scripts/rancher-desktop-guestagent.initd](https://github.com/rancher-sandbox/rancher-desktop/blob/v1.5.1/src/assets/scripts/rancher-desktop-guestagent.initd#L35) instead of pam_env logic as in other places like [src/assets/scripts/service-k3s.initd](https://github.com/rancher-sandbox/rancher-desktop/blob/v1.5.1/src/assets/scripts/service-k3s.initd#L18) or lima's [boot.sh](https://github.com/lima-vm/lima/blob/master/pkg/cidata/cidata.TEMPLATE.d/boot.sh#L25)

### Steps to Reproduce

1. Add custom lima env variables in your lima/_config/override.yaml file, e.g.
```
env:
  K3S_EXEC: --flannel-iface rd1 --disable traefik --disable-network-policy
```

2. Start Rancher Desktop

### Result

Rancher Desktop fails to start kubernetes and shows the following error:
![Bildschirmfoto 2022-08-16 um 17 02 49](https://user-images.githubusercontent.com/29315921/184915842-eb731079-80c5-4158-855a-4acfdc045432.png)

When issuing the command manually, the output is:
```
/lib/rc/sh/openrc-run.sh: /etc/environment: line 7: rd1: not found
 * rancher-desktop-guestagent: error loading /etc/init.d/rancher-desktop-guestagent
 * ERROR: rancher-desktop-guestagent failed to start
```

### Expected Behavior

Rancher Desktop fully starts without errors when using custom lima env variables that contain spaces.

### Additional Information

Contents of /etc/environment inside lima VM when using the override.yaml as above:
```
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#
#LIMA-START
K3S_EXEC=--flannel-iface rd1 --disable traefik --disable-network-policy
#LIMA-END
```

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.23.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.5

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by gaktive** [comment]
Ties into work we need to look at in our docs around lima overrides: #1343
