### ISSUE TITLE
clicking on app icon during first run, opens main window

### ISSUE THREAD

**Issue by prabalsharma** [rancher-sandbox/rancher-desktop#2772]
### Actual Behavior

clicking on RD  icon during first run, opens main window along with first run settings pop up window

### Steps to Reproduce

1. Factory reset
2. Open app
3. click on App Icon 

### Result

<img width="998" alt="Screen Shot 2022-08-17 at 3 42 03 PM" src="https://user-images.githubusercontent.com/3749546/185256304-2b1e5a98-3825-4ec0-b1f6-fe50e35daa27.png">

### Expected Behavior

1.  Only first run options window should open up
2. Main window should not open up until a selection has been made by the user

### Rancher Desktop Version

1.5.0-13-g3072e87d

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment]
I can't reproduce this on macOS on trunk.

**Comment by ericpromislow** [comment]
Just to make sure we're on the same page, here's what I did in response to ^:

* Run /Apps/RD
* Keep icon in dock
* Run Factory Reset
* Double-click on the RD icon in the dock

I only saw the startup-dialog, not the main window.

**Comment by jandubois** [comment]
No, the sequence is:

* Do a factory reset, so the next run will display the first-run dialog.
* Start RD again and wait until the first run dialog appears
* Now click on the dock icon of the running app. The main window appears as well
* If you now click on the gear icon, you also get the regular preferences dialog.
