### ISSUE TITLE
Port 8000 cannot be used

### ISSUE THREAD

**Issue by subigre** [rancher-sandbox/rancher-desktop#2779]
### Actual Behavior

Port 8000 (and 8080) cannot be used anymore.

### Steps to Reproduce

```
$ docker run -d -p 8000:80 nginx
```

### Result

```
$ curl -I http://localhost:8000
curl: (52) Empty reply from server
```

### Expected Behavior

```
curl -I http://localhost:8000
HTTP/1.1 200 OK
Server: nginx/1.23.1
Date: Fri, 19 Aug 2022 11:00:27 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 19 Jul 2022 14:05:27 GMT
Connection: keep-alive
ETag: "62d6ba27-267"
Accept-Ranges: bytes
```

or the example in the [documentation](https://docs.rancherdesktop.io/tutorials/working-with-containers#exposing-a-port) should be updated.

### Additional Information

It works fine using port like 8001, 9000, etc. and I am pretty sure that it worked in the past.

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Professionnel 21H2 (22000.856)

### What CPU architecture are you using?

x64

**Comment by adamkpickering** [comment]
I checked with a fresh install of 1.5.1 on Windows 10 and didn't see anything listening on those ports. I also tried running `docker run -d -p 8000:80 nginx` and was able to access it on `http://localhost:8000`. This is Windows 10 and not 11, but I don't think there would be that kind of difference... @subigre is it possible that you had something running on those ports? @Nino-K do you know if we have anything that might run on those ports?

**Comment by subigre** [comment]
Thanks for the response @adamkpickering. I do not understand because just tried again and it works fine today... I am pretty sure that I double-checked that nothing else was running during the first try but I probably missed something 😢 
Sorry for wasting time.
