### ISSUE TITLE
Add lima examples directory and contents

### ISSUE THREAD

**Issue by alansill** [rancher-sandbox/rancher-desktop#2786]
### Problem Description

The example configuration files from the lima-vm project area apparently not available from within Rancher Desktop. These include definitions for many different containers that would be helpful to have available from within the dashboard. What would be required to add these in?

[https://github.com/lima-vm/lima/tree/master/examples](https://github.com/lima-vm/lima/tree/master/examples)

I'd be willing to put this in as a pull request if someone can point me to where these should be added to be discovered and used from within the lima environment in the Rancher Desktop app.

### Proposed Solution

Add the contents of the lima-vm examples directory or pull them in at the time of installation.

### Additional Information

Looking for an easy way to pull in containers containing other distributions and container images.

**Comment by adamkpickering** [comment]
I can see this being useful, but I'm going to defer to @jandubois, @gunamata and @gaktive on this one.

**Comment by jandubois** [comment]
> Looking for an easy way to pull in containers containing other distributions and container images.

I'm confused about what you are looking for. You should be able to run containers using different distributions on top of Rancher Desktop.

What you can't do is switching the distro used by the RD VM itself; it is a purpose-built distro derived from Alpine-virt.

The actual distro of the VM is an implementation details. We provide access to it, so users can change the configuration as it pertains to running the container engine etc, but not as a general purpose Linux VM.

Maybe the documentation needs to be updated about the scope of RD: It is about running containers, either directly, or via compose, or Kubernetes. It is **not** about running VMs.

**Comment by alansill** [comment]
There is not good reason to exclude the lima examples that already exist. Decisions about which ones to deploy should be left to users.

**Comment by jandubois** [comment]
> There is no good reason to exclude the lima examples that already exist. Decisions about which ones to deploy should be left to users.

There is actually a very good reason: the rest of Rancher Desktop will not work if you use any other base image.

As I wrote above, Rancher Desktop is not a generic virtualization tool for operating systems, but a specialized tool for container workloads, where the host OS is mostly irrelevant.

If you want a GUI app to start other lima examples you may want to take a look at https://github.com/afbjorklund/lima-gui instead.
