### ISSUE TITLE
Can't Install Rancher Desktop 1.5.1 on Mac Os 12.5.1 with chip Apple M1 Pro

### ISSUE THREAD

**Issue by lucacerone** [rancher-sandbox/rancher-desktop#2793]
### Actual Behavior

I download the [installer file](https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.5.1/Rancher.Desktop-1.5.1.aarch64.dmg).

I click it, and when I move the Rancher Desktop to the Applications folder the Rancher Desktop icon is available,
but when I open the app a message saying "Rancher Desktop is damaged and can't be opened" appears.

### Steps to Reproduce

Download the installer.
Install the app.
Try to open Rancher Desktop

### Result

a message saying "Rancher Desktop is damaged and can't be opened" appears.

### Expected Behavior

I'd like the app to open.

### Additional Information

I previously had Rancher Desktop installed and had no issues with it till the update to 1.5.1 (it started complaining about not having lima installed).
Because I couldn't opened it, I removed everything in /Applications/Rancher Desktop and removed the .rd folder in my home.

I tried to re-install Rancher Desktop from scratch but it's not working.

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Monterey 12.5.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by lucacerone** [comment]
Note. After submitting the issues, I also tried to install older versions that worked previously, and none of them can't be installed.

I am not sure if this might be due to the recent security updates from Apple.

**Comment by jason-edstrom** [comment]
Same issues as the OP with same system configuration (12.5.1, M1 Pro, 1.5.1 Rancher Desktop).  Noticed in the inspector that macOS thinks it's an Intel app.  Should it be native instead?

![rancher-desk](https://user-images.githubusercontent.com/2515629/185996749-ed65cba8-ab37-4c4c-83e2-ee166f7c8ee3.png)

**Comment by lucacerone** [comment]
In my case the "limactl" not existing was caused by "Cisco" software recognizing it as a virus and deleting it from the system. Once the IT folks fixed the policy, everything worked as expected.
