### ISSUE TITLE
limactl doesn't exist on M1 chip mac

### ISSUE THREAD

**Issue by mmhealey1** [rancher-sandbox/rancher-desktop#2798]
### Actual Behavior

`File /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl doesn't exist.
`

### Steps to Reproduce

Run Rancher Desktop

### Result

```
2022-08-22T11:04:51.725Z: Error starting lima: se [Fatal Error]: File /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl doesn't exist.
    at Ur.ensureArchitectureMatch (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:17:206482)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:17:228437 {
  fatal: true
}
```

### Expected Behavior

Should boot up and work

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.5.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by mmhealey1** [comment]
This could be due to XProtectPayloads being updated on macOS today
![Screenshot 2022-08-22 at 12 26 42](https://user-images.githubusercontent.com/52454660/185910364-7936e44f-d353-425a-be99-9648e45de66b.png)

**Comment by adamkpickering** [comment]
Thanks for the bug report! Have you tried running `limactl` by itself? I am curious if that will work.

Also, could you please post more logs here? Please enable debug mode in the Troubleshooting tab before reproducing the issue. Then you can access the logs via the Troubleshooting tab as well. Thanks!

**Comment by mmhealey1** [comment]
The issue is definitely with limactl. I tried installing it via homebrew
independent of Rancher-Desktop and the same issue occurred. It looks like
Apple security update deletes limactl because it thinks its malware.

**Comment by AkihiroSuda** [comment]
> The issue is definitely with limactl.

Isn't this an issue of macOS?
Could you send the report to Apple?

**Comment by mmhealey1** [comment]
Yeah, already sent report to apple :)

**Comment by przemekpln92** [comment]
Hi guys, a solution that worked for me and my teammates:
1. Remove rancher from your Applications
2. `brew install --cask rancher`
3. Go to Rancher --> Preferences
           a.In Application section Check Administrative Access
           b. In Container runtime switch to dockerd(moby)

MacOS Monetery 12.5.1 - Intel chip

**Comment by jandubois** [comment]
I understand this issue has been fixed by updating the AV definitions: https://github.com/lima-vm/lima/issues/1028
