### ISSUE TITLE
Dashboard not available when using VPNs

### ISSUE THREAD

**Issue by AlFeersum** [rancher-sandbox/rancher-desktop#2813]
### Actual Behavior

Windows & WSL2

When connected to a corporate VPN , starting the dashboard hangs.

This is due to corporate policy disabling split-tunnel routing.

Implementing `"expertimentalHostResolver": true` does not resolve the issue.
Including `"hostResolver": false` generates a 500 error

Note: replacing "hostResolver" with "experimentalHostResolver" causes `"hostResolver": true` to be recreated.

### Steps to Reproduce

1. Using Windows 11, WSL2 and Cisco AnyConnect with corporate policies implemented,
2. Start Rancher Desktop
3. Connect to corporate VPN (in this case, Cisco AnyConnect)
4. Right-click Rancher Desktop taskbar icon and select 'Dashboard'

### Result

Blank screen using `"expertimentalHostResolver": true, "hostResolver": true` :
![image](https://user-images.githubusercontent.com/20180990/186389055-20aac8bb-bec0-4c96-a257-c3bf9ccacc40.png)

500 error using `"expertimentalHostResolver": true, "hostResolver": false` :
![image](https://user-images.githubusercontent.com/20180990/186385649-7e81abcd-b814-4373-a05d-30e54e1282c6.png)

### Expected Behavior

Rancher Desktop dashboard should display:
![image](https://user-images.githubusercontent.com/20180990/186389372-06210404-082f-4ff3-a7e4-d5302b5669d5.png)

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 21H2 (OS build 22000.856)

### What CPU architecture are you using?

x64

### Windows User Only

VPN Cisco AnyConnect with corporate rules preventing split-tunnel routing.

To get round this using WSL instances (not Rancher Desktop), when the AnyConnect connection event is raised, a task is triggered to update `resolv.conf` with the new DNS entries.

Rancher Desktop does not allow the update of resolv.conf - and to use the triggered script, will require Python3 to be installed.

**Comment by Nino-K** [comment]
@AlFeersum please use our latest release 1.9 which includes a [solution](https://github.com/rancher-sandbox/rancher-desktop/issues/3810) for when using Rancher Desktop behind a VPN. You can enable it using:

```
rdctl set --experimental.virtual-machine.networking-tunnel=true
```
