### ISSUE TITLE
error Command error output: xtables parameter problem: iptables-restore: unable to initialize table 'nat'

### ISSUE THREAD

**Issue by Jmadih** [rancher-sandbox/rancher-desktop#2819]
### Actual Behavior

Hello,
I'm facing a problem with istio in Rancher desktop. Getting an error when i try to deploy the main example "bookinfo.yaml". 
The pod failing with the error "containers with incomplete status: [istio-init]" specially the container "istio-init | docker.io/istio/proxyv2:1.14.3".
The output is : error Command error output: xtables parameter problem: iptables-restore: unable to initialize table 'nat'

Some main informations: 
I'm running the rancher desktop Version: 1.5.1 in mac M1 pro chip - MacOs Montery v12.5 

### Steps to Reproduce

The exact installation steps in : https://istio.io/latest/docs/setup/getting-started/

### Result

COMMIT
--
Wed, Aug 24 2022 10:40:37 pm | 2022-08-24T20:40:37.421097Z info Running command: iptables-restore --noflush /tmp/iptables-rules-1661373637420270143.txt3645179173
Wed, Aug 24 2022 10:40:37 pm | 2022-08-24T20:40:37.445919Z error Command error output: xtables parameter problem: iptables-restore: unable to initialize table 'nat'
Wed, Aug 24 2022 10:40:37 pm |  
Wed, Aug 24 2022 10:40:37 pm | Error occurred at line: 1
Wed, Aug 24 2022 10:40:37 pm | Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Wed, Aug 24 2022 10:40:37 pm | 2022-08-24T20:40:37.446285Z error Failed to execute: iptables-restore --noflush /tmp/iptables-rules-1661373637420270143.txt3645179173, exit status 2

### Expected Behavior

Ready pods

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOs Montery v12.5 

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by Jmadih** [comment]
Hello, thank you for taking this issue.
Well from the networking point, i was disabling Traefik to use nginx-ingress instead. I've enable it back and it doesn't work neither.
Let me know if you want any further informations. Thanks !

**Comment by Nino-K** [comment]
@Jmadih thanks for filing the issue, this is a known issue issue on m1 mac, please take a look [here](https://github.com/istio/istio/issues/36762) for more details.

**Comment by Jmadih** [comment]
@Nino-K thank you. I confirm that this solution https://github.com/istio/istio/issues/26652#issuecomment-1205368297
worked for me. Hopping it will be stable :)
