### ISSUE TITLE
Revisit helm & kubectl e2e tests

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2820]
The `helm` e2e tests frequently flake-fail, usually like so:
```
  1) helm.e2e.spec.ts:83:3 › Helm Deployment Test › should verify if the application is working properly

    Error: expect(received).toBeUndefined()

    Received: {"message": "Error: /Users/ericp/workspace/rancher/desktop/resources/darwin/bin/kubectl exited with code 1", "stderr": "Error from server: error dialing backend: x509: certificate is valid for 127.0.0.1, 192.168.5.15, not 192.168.0.117
    ", "stdout": ""}
```

Maybe this is a straightforward fix. But I'm wondering what exactly are we testing in the Rancher Desktop `k3s`
deployment that we have helm tests. Can they be done in `kubectl` tests instead? Or is the frequent cert error a red
flag that we should act on?

The `kubectl` e2e tests often fail while trying to delete a namespace:

```
    Error: expect(received).toBeUndefined()

    Received: {"message": "Error: /Users/ericp/workspace/rancher/desktop/resources/darwin/bin/kubectl exited with code 1", "stderr": "error: Get \"https://127.0.0.1:6443/api/v1/namespaces?fieldSelector=metadata.name%3Drd-nginx-demo\": dial tcp 127.0.0.1:6443: connect: connection refused - error from a previous attempt: read tcp 127.0.0.1:64182->127.0.0.1:6443: read: connection reset by peer
    ", "stdout": "namespace \"rd-nginx-demo\" deleted
    "}

      57 |   test('should create a sample namespace', async() => {
      58 |     // check if the rd-nginx-demo exists and delete, otherwise it will be ignored
    > 59 |     await kubectl('delete', '--ignore-not-found', 'namespace', 'rd-nginx-demo');
```

We should probably ignore when the deletion times out. I've seen this problem in Kubernetes when
attempting to delete a namespace -- all its components are gone, but there's a termination
problem at the node-level. I think it can be ignored.

**Comment by mook-as** [comment]
The merged PR would _not_ solve the issue in the description — changing timeouts doesn't help with the cert being for the wrong address.

Looking at the error, I suspect that was on Windows (where the WSL address got rotated), in which case the retries wouldn't help either — we don't run CirrusCI on Windows.

**Comment by jandubois** [comment]
I just got these errors on macOS with the latest `main` branch, running `npm run test:e2e` locally:

```
  1) helm.e2e.spec.ts:84:3 › Helm Deployment Test › should verify if the application is working properly

    Error: expect(received).toBeUndefined()

    Received: {"message": "Error: /Volumes/ThunderBlade/suse/rd/resources/darwin/bin/kubectl exited with code 1", "stderr": "Error from server: error dialing backend: x509: certificate is valid for 127.0.0.1, 192.168.5.15, fec0::5055:55ff:fede:ac46, not 192.168.18.119
    ", "stdout": ""}
```

and

```
  2) kubectl.e2e.spec.ts:67:3 › K8s Deployment Test › should deploy sample nginx server ============

    Error: expect(received).toBeUndefined()

    Received: {"message": "Error: /Volumes/ThunderBlade/suse/rd/resources/darwin/bin/kubectl exited with code 1", "stderr": "Unable to use a TTY - input is not a terminal or the right kind of file
    Error from server: error dialing backend: x509: certificate is valid for 127.0.0.1, 192.168.5.15, fec0::5055:55ff:fede:ac46, not 192.168.18.119
    ", "stdout": ""}
```

The `192.168.18.119` address would be an address from my local DHCP server, so would come from the bridged network.

I ran the same tests earlier on the same commit without getting these errors, so they are not deterministic.

**Comment by jandubois** [comment]
> The `192.168.18.119` address would be an address from my local DHCP server, so would come from the bridged network.

I don't understand how this is even possible. The e2e tests always run with `--no-modal-dialogs` to avoid the prompt for the `sudo` password, so they should always run without `sudo`, and therefore shouldn't even have the shared and bridged networks defined. Where does that IP address come from?

And there is another example at https://slack-archive.rancher.com/t/8083664/periodically-having-this-same-problem-restarting-rd-fixes-it, but it shows the IP address from the DHCP range of the shared network.
