### ISSUE TITLE
Epic: Dashboard Plugin

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#2822]
### Problem Description

Rancher Desktop would benefit from tighter integration with select Rancher Manager components, like Dashboard and Marketplace. Right now Dashboard is only accessible in a separate window via a menu entry in a taskbar icon. It should be directly included in the main app window itself.

### Proposed Solution

- [x] #2823
- [x] #2824
- [x] #2825
- [x] #2826
- [x] #2827
  - [x] #3143
  - [x] #3154
  - [ ] Allow `@rancher/shell` to run without backend
  - [ ] Merge and publish Rancher Dashboard modification upstream
- [x] #2828

We will utilize Rancher Dashboard's existing plugin architecture. Rancher Dashboard will act as the shell that will load render Rancher Desktop and Cluster Explorer plugins by default.  

![rancher-desktop-plugin-architecture(1)](https://user-images.githubusercontent.com/835961/186780917-ee950536-6717-436c-ab5b-85d7f3349fc8.png)

#### Plugin Prototype
https://xd.adobe.com/view/7b583c5c-c4d0-4a57-ac7a-78d97c4560a2-2e0b/

### Acceptance Criteria

* Rancher Desktop shows the activity bar with icons for RD and Dashboard
* Dashboard no longer appears in the tray menu
* Dashboard icon is disabled when Kubernetes is disabled or in an error state
* Clicking the RD icon brings up the RD UI
* The RD UI is fully functional
* The preferences dialog is accessible through keyboard shortcuts and gear icon
* Preferences are fully functional
* Clicking on Dashboard icon brings up the cluster dashboard
* All functionality is available without a network connection
* Deploy a sample app and make sure the dashboard displays pods and services, you can see the containers, ssh into the containers, and display their logs
* Check the number of pods and service
* Verify namespaces

### Documentation

* Document activity bar
* Explain when Dashboard is accessible (or not)
* Figure out how to document dashboard functionality itself

**Comment by agracey** [comment]
Would these be the same extensions that be loaded into Rancher Manager 2.7 itself?

**Comment by jandubois** [comment]
> Would these be the same extensions that be loaded into Rancher Manager 2.7 itself?

Eventually, but they will need to be extended for Rancher Desktop. E.g Marketplace will use a different backend to install charts via `helm` and not with CRD and the helm operator.

So at first the extensions will be hard-coded into Rancher Desktop, but eventually things should become configurable by the user.
