### ISSUE TITLE
Administrative Access modal keeps bouncing after expand config network

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#2848]
### Actual Behavior

During a fresh install, the `Administrative Access modal` keeps bouncing up and down for no reason.

### Steps to Reproduce

1. Download latest RD dmg file
2. Install following the app steps
3. Should open the Administrative Access modal

### Result

Modal keeps bouncing up and down after expanding `Configuring Network` element.

### Expected Behavior

The modal should be static without bouncing.

### Additional Information

See video attached:

https://user-images.githubusercontent.com/37411123/187730274-b59de1d0-52fb-4537-a344-d7b1d9cadf98.mov

cc: @rak-phillip  

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.24.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS 12.5.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by rak-phillip** [comment]
@evertonlperes thanks for raising this issue an helping to make Rancher Desktop better 😁

I was able to set up an environment to reproduce and from what I can tell, the second list item is causing a horizontal scrollbar show/hide in perpetuity and this is causing the window to resize in such an erratic fashion.
