### ISSUE TITLE
Include commit id in dev version string

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#285]
Right now all our builds identify as version 0.1.0 because that is the latest released build. But that is confusing if the version is included in bug reports, including screen shots of the installer.

I think for non-release builds we should use some version of `git describe` output, and also display this version prominently in our UI (and log files) in addition to the installer dialog.

**Comment by ericpromislow** [comment]
Merged in https://github.com/rancher-sandbox/rancher-desktop/pull/328#event-4868071971
