### ISSUE TITLE
CPU and RAM does not update since the new UI

### ISSUE THREAD

**Issue by BoKKeR** [rancher-sandbox/rancher-desktop#2855]
### Actual Behavior

On 1.5.0 and 1.5.1 the UI to update the CPU and RAM does not reflect in the cluster anymore. This has happened to many of my colleagues. We all were upgrading from 1.4.8 and are forced to go back to it.

### Steps to Reproduce

- install 1.4.1
- set CPU and RAM
- reset cluster
- reboot rancher
- run `docker stats` to see memory limit
- update to 1.5.1
- check kubernetes settings for CPU and RAM
- compare them to `docker stats` it will say wrong values
- update kubernetes CPU/RAM settings in rancher desktop
- restart cluster
- restart rancher destkop
- check `docker stats` 
- it will say wrong values

### Result

Unable to update CPU/RAM in kubernetes.

### Expected Behavior

To be able to update the settings from the UI

### Additional Information

![image](https://user-images.githubusercontent.com/2664857/188081973-28e219c0-ae86-4973-b560-b1f2bcfdc83c.png)

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.24.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Monterey 12.2.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by MagdyYoussef** [comment]
well, for me CPU is updating normally, but for Memory it's stuck with  Total Memory: 2.909GiB for the lima VM, docker , containers and everything.

i guess it's also related to kubernetes not responding suddenly.

macos M1

**Comment by BoKKeR** [comment]
I actually not sure if CPU did update or not, I have only tested RAM, so it might only be RAM related

**Comment by jandubois** [comment]
The RAM issue is due to [Reduce the memory to <= 3 GiB, when QEMU >= 7.0 && macOS <= 12.3 && CPU == M1 · Issue #795 · lima-vm/lima](https://github.com/lima-vm/lima/issues/795)].

On arm64 machines you will need to upgrade to Monterey 12.4 or later to use more than 3 GiB of memory for the virtual machine.
