### ISSUE TITLE
Docker Private Registry Client.Timeout exceeded while awaiting headers 

### ISSUE THREAD

**Issue by JeopardyBA** [rancher-sandbox/rancher-desktop#2856]
Hi,

We are using Rancher Desktop with version 1.5.1 on Windows 10.
We also upgraded our WSL Kernel Version 5.10.16 (After having kubectl error)

Now we are having problem with https private docker registry (Nexus). Nexus server is behind F5 . When we try to pull docker images with F5 IP or dns adress we are having Client.Timeout errors. But When we want to pull images directly from Nexus repository server there are no errors.  We can see that dns adress can be solved by rancher-desktop wsl machine (we connect desktop machine and test docker pull and curl comands from there also)

We tried to change docker base ip subnet, wsl ip adapter ip adres with hcn module but the problem is still persist. Our networking team adresses that there is no connection outgoing from your local machine (maybe from rancher desktop)

Could you please examine this situation and help us to adress the problem?

**Comment by JeopardyBA** [comment]
After further investigation, we noticed that this problem caused by SEP Firewall module. https://knowledge.broadcom.com/external/article/221329/endpoint-protection-firewall-blocks-netw.html

**Comment by Nino-K** [comment]
@JeopardyBA Thanks for filing the issue. Based on similar user feedback in the past it sounds like the outbound connections to your LB are being blocked. Please ensure that the LB's IP address is white-listed in your local firewall. 

Thanks
