### ISSUE TITLE
I can't access to "k8s.gcr.io", Is there any solution?

### ISSUE THREAD

**Issue by jack-liew** [rancher-sandbox/rancher-desktop#2859]
### Problem Description
**My intranet does not allow access to k8s.gcr.io.**

I use RD 1.5.1, WhenI installed RD and the following error appeared after startup RD.

![image](https://user-images.githubusercontent.com/102201538/188301433-1cab8356-cf85-4867-a5d4-4db64b393d24.png)

FailedCreatePodSandBox (23)32 secs agoFailed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "[k8s.gcr.io/pause:3.6](http://k8s.gcr.io/pause:3.6)": Error response from daemon: Get "https://k8s.gcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Proposed Solution

I dont know how

**Comment by miahwk** [comment]
any solution？I happend to the same issue.

**Comment by jack-liew** [comment]
> 有什么解决方案吗？我碰巧遇到了同样的问题。

i had fixed it, just pull this image from another registry. then docker tag it.
