### ISSUE TITLE
Check if nerdctl-stub needs to be adjusted for simplified `nerdctl --help` output

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2864]
See [cmd/nerdctl: simplify --help by AkihiroSuda · Pull Request #1355 · containerd/nerdctl](https://github.com/containerd/nerdctl/pull/1355#issuecomment-1237075181)

**Comment by ryanfb** [comment]
For what it's worth, from looking at the code, I think it will still work, but I don't have an easy way to run `generate:nerdctl-stub` against `nerdctl` v0.23.0 in my environment in order to verify.

**Comment by jandubois** [comment]
> I think it will still work

Wouldn't we lose support for the global options unless we parse them separately? I haven't actually looked at the code at all yet; I just want to make sure we do before we release this and maybe forget about updating the stub (which is only used on Windows).

**Comment by ryanfb** [comment]
That's what I initially thought, but `nerdctl-stub` by default calls `nerdctl --help` without a subcommand to get the global options, then recursively passes them down to each subcommand (parsed out of the global help output) as its parent command (https://github.com/rancher-sandbox/rancher-desktop/blob/main/src/go/nerdctl-stub/generate/main.go#L92-L121). You can also see in the existing generated output that the global options are only defined once: https://github.com/rancher-sandbox/rancher-desktop/blob/main/src/go/nerdctl-stub/nerdctl_commands_generated.go#L61-L85

**Comment by jandubois** [comment]
@mook-as confirmed in https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/49#pullrequestreview-1104977151 that there is nothing to do here.
