### ISSUE TITLE
Devtools extension not working on main

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2869]
### Actual Behavior

When using `npm run dev`, the Vue devtools extension (the tab showing Vuex states, etc.) no longer shows up.

### Steps to Reproduce

- Checkout Rancher Desktop since 5a80c9d75f0258a51af982c6897cfd7f775dd870
- Run `npm run dev`
- Open dev tools (Ctrl+Shift+I / Cmd+Shift+I)
- Look for the Vue tab

### Result

The Vue tab never shows up.

### Expected Behavior

The Vue tab shows up and is usable.

### Additional Information

This appears to be because we're now loading the UI via `app://` (instead of `http://`), and that doesn't support devtools extensions properly, per https://github.com/electron/electron/issues/34386

### Rancher Desktop Version

'main' (5a80c9d75f0258a51af982c6897cfd7f775dd870)

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina 10.15.7

### What CPU architecture are you using?

x64

**Comment by rak-phillip** [comment]
@jandubois closing because Vue dev tools were removed from the project in #3844
