### ISSUE TITLE
When changing version of RD the blue status bar doesn't show a change is happening

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#287]
The blue bar that shows in the preferences on startup to signify downloading and starting doesn't work when the version is changed and the download/startup process happens for the new version.

This was observed on Windows.

**Comment by ericpromislow** [comment]
Fixed on https://github.com/rancher-sandbox/rancher-desktop/pull/319#event-4826663643 - PR 319

**Comment by ericpromislow** [comment]
Still seeing this problem on windows

**Comment by ericpromislow** [comment]
.. and no longer seeing the problem on windows, both dev and release builds
