### ISSUE TITLE
docker login doesn't work on linux

### ISSUE THREAD

**Issue by thehejik** [rancher-sandbox/rancher-desktop#2893]
### Actual Behavior

Unable login to dockerhub when using moby - nerdctl works - seems the binary `docker-credential-pass` is not available on my system, I have only `pass` bin present in my opensuse 15.3.

I was following docu https://docs.rancherdesktop.io/getting-started/installation/#pass-setup

### Steps to Reproduce

* Install dev rd 1.5.0-471-gda475b63
* delete ~/.docker/config.json
* run rd and select moby/docker as container backend
* docker login

### Result

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: thehejik
Password: 
Error saving credentials: error storing credentials - err: exec: "docker-credential-pass": executable file not found in $PATH, out: ``
```

### Expected Behavior

* docker login command should succeed and valid ~/.docker/config.json will be generated

### Additional Information

works with `nerdctl login`

### Rancher Desktop Version

1.5.0 dev

### Rancher Desktop K8s Version

any

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Other Linux

### Operating System / Build Version

opensuse 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by adamkpickering** [comment]
FWIW, I wasn't able to repro this on Pop OS 20.04. Might be an openSUSE thing?

**Comment by thehejik** [comment]
I installed the binary from snap by `snap install --edge docker-credential-pass` but it failed in next step.

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: thehejik
Password: 
Error saving credentials: error storing credentials - err: exit status 1, out: `pass store is uninitialized`
$ pass list
Password Store
└── docker-credential-helpers
    └── aHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEv
        └── thehejik
```

I guess it is due snap sandbox which doesnt work with my pass database installed and initialized out of snap.

openSUSE itself doesn't offer this helper package. 

I belive it was working some time ago in moby/docker even without the helper installed.

**Comment by adamkpickering** [comment]
We package `docker-credential-pass` with RD - what happens if you uninstall the snap version and retry? The results would depend on what type of `PATH` management you're using - as long as you have `~/.rd/bin/` in your `PATH` it should work fine.

**Comment by thehejik** [comment]
Retested with RD `1.5.0-547-gfbb7c81d` and now it works as expected - I guess I just forgot to source the modified `.bashrc` with the modified `PATH` (so I was using system `kubectl` and `helm` instead the ones from RD). Thanks, closing.

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: thehejik
Password: 
Login Succeeded
```

```
$ cat ~/.docker/config.json 
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "pass"
```
