### ISSUE TITLE
Rancer Desktop Apple Silicon download link downloads Intel version of app

### ISSUE THREAD

**Issue by karthikeyan-mac** [rancher-sandbox/rancher-desktop#2897]
### Actual Behavior

When we download Rancher Desktop (Apple Silicon) from https://rancherdesktop.io/, it downloads Rancher.Desktop-1.5.1.aarch64.dmg but the Rancher Desktop.app inside the DMG is Intel version. Uploaded the screenshot
![Screenshot 2022-09-13 at 6 04 37 PM](https://user-images.githubusercontent.com/7923728/189902562-de528b06-0d95-4a6f-b6bf-3d80d382ee3e.png)

### Steps to Reproduce

Download Rancher Desktop (Apple Silicon) from https://rancherdesktop.io/ 

### Result

It shows the Application Kind is Intel

### Expected Behavior

Application Kind should be Apple Silicon

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

NA

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by jandubois** [comment]
It is only the GUI app that is running via Rosetta right now; the virtualization layer and images will all be executed natively.

We plan to eventually also have a native GUI, but it is not a performance bottleneck, except on the very first start, so this is not a top priority.

There is one other piece that may use Intel binaries: there are no official ARM64 builds of kubectl for older k8s version (I think before 1.20.x, but not sure), so for those we fetch the Intel version as well. That too should not be a performance problem.
