### ISSUE TITLE
Electron fails to launch e2e tests in CI

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#2915]
### Actual Behavior

Electron fails to launch with playwright for e2e tests with an error like `electron.launch: Browser closed`. 

### Steps to Reproduce

1. Install node version 16
2. Install go version 1.18
3. Run `npm ci`
4. Run `npm run postinstall`
5. Run `npm run test:e2e`

### Result

e2e tests are failing because electron fails to launch with the following error:
```
electron.launch: Browser closed.
241
    ==================== Browser output: ====================
242
    <launching> /Users/prvm1mac2/actions-runner/_work/rancher-desktop/rancher-desktop/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --inspect=0 --remote-debugging-port=0 /Users/prvm1mac2/actions-runner/_work/rancher-desktop/rancher-desktop/ --disable-gpu --whitelisted-ips= --disable-dev-shm-usage --no-modal-dialogs
243
    <launched> pid=66411
244
    [pid=66411][err] Debugger listening on ws://127.0.0.1:50840/90c1e2ab-6449-4693-834c-704beb2c76e0
245
    [pid=66411][err] For help, see: https://nodejs.org/en/docs/inspector
246
    [pid=66411][err] Debugger attached.
247
    [pid=66411][err] 
248
    [pid=66411][err] DevTools listening on ws://127.0.0.1:50842/devtools/browser/068abb88-d7f6-49ad-b04a-80e9520c9575
249
    [pid=66411][err] (node:66411) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Users/prvm1mac2/.rd/bin'
250
    [pid=66411][err] (Use `Electron --trace-warnings ...` to show where the warning was created)
251
    [pid=66411][err] (node:66411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### Expected Behavior

Electron should be able to launch with playwright and execute e2e tests.

### Rancher Desktop Version

1.5

### Rancher Desktop K8s Version

24.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

maOs Monterey 

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by ericpromislow** [comment]
Are there stray processes running? I have a script I call `stray` that consists of this:
```
#!/bin/sh

for x in nuxt qemu ; do
echo $x
ps auxww | grep $x
done

ps auxww | grep rancher | grep -vi -e goland
```

And running `stray` should show only the three grep processes. If there are more, I run:

```
stray | awk '{ print $2 }' | xargs kill
```

Use `sudo kill` if some processes are owned by root.

**Comment by jandubois** [comment]
This is not reproducible; please re-open if this still happens!
