### ISSUE TITLE
First-run dialog can be closed and triggers a modal dialog

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2917]
There is still one weird behaviour left; not sure if it is intentional: you can just close the first-run dialog (via the little red dot in the top left corner on macOS), and then the main Window appears with a modal dialog:

<img width="1052" alt="Screen Shot 2022-09-15 at 5 23 06 PM" src="https://user-images.githubusercontent.com/78947/190530990-9f7bf08b-dac5-48df-99bb-c5a6a69d0a92.png">

So I guess it accepted the default settings for Kubernetes, but not for `PATH` configuration. Does this make sense?

_Originally posted by @jandubois in https://github.com/rancher-sandbox/rancher-desktop/issues/2914#issuecomment-1248782344_

**Comment by jandubois** [comment]
Adding to the weirdness is that the first-run dialog does not disable the "Close" button on the top left, but doesn't have a "Cancel" button.

<img width="448" alt="Screen Shot 2022-09-15 at 5 29 31 PM" src="https://user-images.githubusercontent.com/78947/190531517-c1a9be3b-6597-4383-aa63-5446cd0e23c5.png">

I'll create a new issue for sorting this out; I don't think it should affect merging this PR.

**Comment by jandubois** [comment]
Pinging @rak-phillip and @manuelecarlini to provide some feedback

**Comment by ericpromislow** [comment]
The first-run dialog box is populated by the default settings, so closing the box is the same as pressing `Accept` with initial values.

**Comment by ericpromislow** [comment]
A little more background. On startup, if the settings file doesn't exist, RD does the following:
```
* create settings file with default values
* how the first-run dialog box and wait for it to close
* continue as usual
```

The key aspect here is that the settings file is created regardless of what the user does with the first-run dialog box.

**Comment by jandubois** [comment]
> the settings file is created regardless of what the user does with the first-run dialog box

I think that is fine, but the behaviour is still weird. Why does it show the second (modal) dialog about `PATH` settings? When is that dialog ever needed?

Anyways, for the first-run dialog, I think the "close window" functionality should be disabled, and it should have "Quit" and "Accept" buttons, with "Quit" terminating the application without creating a settings file, so the dialog will be displayed again on the next start.

As for the second (modal) dialog, I would like to understand which interactions should lead to it being displayed (I can't think of any). And if there aren't any, then it should be removed.

**Comment by mook-as** [comment]
I feel rather strongly that we should _not_ prevent people from closing the dialog box; some users will not care about it ("just let me use the software"), and in that case we should have reasonable defaults. (I'd even argue that we should aim for good enough defaults that people would be happy with not having a first-run dialog at all.)

(In which case, we should accept the values and _not_ trigger a second dialog, of course…)

**Comment by jandubois** [comment]
We talked about this today, and consensus was to change "Accept" button to "Ok" button, and closing the window will have the same effect as closing the window.
