### ISSUE TITLE
Bumping electron to 18.3.6 triggers typescript errors

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2923]
#2921 depends on this

### Actual Behavior

* Set electron to `^18.3.6` in `package.json`
* rm -fr package-lock.json node_modules
* npm i
* npm run lint:typescript:nofix

```
…/src/store/prefs.js
  223:5   warning  Caution: `Vue` also has a named export `set`. Check if you meant to write `import {set} from 'vue'` instead  import/no-named-as-default
```
(repeated 5 times over 2 files)
```
* npm run test:unit:jest
```
Test suite failed to run

    src/utils/fetch.ts:117:13 - error TS2322: Type 'boolean | Agent | undefined' is not assignable to type 'Agent'.
      Type 'undefined' is not assignable to type 'Agent'.

    117             agent = options.agent(parsedURL);
```

**Comment by ericpromislow** [comment]
Problems raised running `npm run dev`:

* ` WARN  [@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.` (multiple occurrences)

* ```
ERROR in src/components/ImagesFormAdd.vue:45:43                                                              12:08:09
TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.
    43 |       required: true,
    44 |       validator(value) {
  > 45 |         return ['pull', 'build'].includes(value);
       |                                           ^^^^^
    46 |       },
    47 |     },
    48 |   },
```

* 
```
ERROR in src/components/Preferences/Alert.vue:38:16
TS2551: Property 'severities' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'. Did you mean 'severity'?
    36 |     ...mapState('preferences', ['severities', 'preferencesError']),
    37 |     severity(): keyof AlertMap | undefined {
  > 38 |       if (this.severities.error) {
       |                ^^^^^^^^^^
    39 |         return 'error';
    40 |       }
```

and more:
```
ERROR in src/components/Preferences/Alert.vue:42:16
TS2551: Property 'severities' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'. Did you mean 'severity'?
    40 |       }
    41 |
  > 42 |       if (this.severities.reset) {
       |                ^^^^^^^^^^
    43 |         return 'reset';
    44 |       }
    45 |

ERROR in src/components/Preferences/Alert.vue:46:16
TS2551: Property 'severities' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'. Did you mean 'severity'?
    44 |       }
    45 |
  > 46 |       if (this.severities.restart) {
       |                ^^^^^^^^^^
    47 |         return 'restart';
    48 |       }
    49 |

ERROR in src/components/Preferences/Alert.vue:60:16
TS2339: Property 'preferencesError' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
    58 |     },
    59 |     bannerText(): string | null {
  > 60 |       if (this.preferencesError) {
       |                ^^^^^^^^^^^^^^^^
    61 |         return this.preferencesError;
    62 |       }
    63 |

ERROR in src/components/Preferences/Alert.vue:61:21
TS2339: Property 'preferencesError' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
    59 |     bannerText(): string | null {
    60 |       if (this.preferencesError) {
  > 61 |         return this.preferencesError;
       |                     ^^^^^^^^^^^^^^^^
    62 |       }
    63 |
    64 |       if (this.alert) {

ERROR in src/components/Preferences/Alert.vue:71:19
TS2339: Property 'preferencesError' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
    69 |     },
    70 |     errorSplit(): string[] {
  > 71 |       return this.preferencesError.split(/\r?\n/);
       |                   ^^^^^^^^^^^^^^^^
    72 |     },
    73 |     errorTitle(): string {
    74 |       return this.errorSplit[0];

ERROR in src/components/Preferences/ModalActions.vue:10:20
TS2339: Property 'canApply' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
     8 |     ...mapGetters('preferences', ['canApply']),
     9 |     isDisabled(): boolean {
  > 10 |       return !this.canApply;
       |                    ^^^^^^^^
    11 |     },
    12 |   },
    13 |   methods:  {

ERROR in src/pages/Preferences.vue:29:69
TS2339: Property 'credentials' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
    27 |   async fetch() {
    28 |     await this.$store.dispatch('credentials/fetchCredentials');
  > 29 |     await this.$store.dispatch('preferences/fetchPreferences', this.credentials as ServerState);
       |                                                                     ^^^^^^^^^^^
    30 |     this.preferencesLoaded = true;
    31 |
    32 |     ipcRenderer.on('k8s-integrations', (_, integrations: Record<string, string | boolean>) => {

ERROR in src/pages/Preferences.vue:46:14
TS2339: Property 'isPlatformWindows' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
    44 |       return [
    45 |         'Application',
  > 46 |         this.isPlatformWindows ? 'WSL' : 'Virtual Machine',
       |              ^^^^^^^^^^^^^^^^^
    47 |         'Container Engine',
    48 |         'Kubernetes',
    49 |       ];

ERROR in src/pages/Preferences.vue:74:14
TS2339: Property 'credentials' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
    72 |       await this.$store.dispatch(
    73 |         'preferences/commitPreferences',
  > 74 |         this.credentials as ServerState,
       |              ^^^^^^^^^^^
    75 |       );
    76 |       this.closePreferences();
    77 |     },

ERROR in src/pages/Preferences.vue:79:45
TS2339: Property 'credentials' does not exist on type 'CombinedVueInstance<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 7 more ..., OptionTypesType<...>>'.
    77 |     },
    78 |     async proposePreferences() {
  > 79 |       const { port, user, password } = this.credentials as ServerState;
       |                                             ^^^^^^^^^^^
    80 |       const { reset } = await this.$store.dispatch(
    81 |         'preferences/proposePreferences',
    82 |         {
```

And a final fatal error:
```
/Users/ericp/workspace/rancher/desktop/node_modules/typescript/lib/typescript.js:73974
        function getContextualType(node, contextFlags) {
                                  ^
RangeError: Maximum call stack size exceeded
...
```

**Comment by mook-as** [comment]
Eric reports that wiping out `node_modules` fixes this.

**Comment by ericpromislow** [comment]
`src/node_modules`. Just run `git clean -dffx` (`-e .idea/` if using an intellij-based IDE)
