### ISSUE TITLE
cannot set k8s version, on first run

### ISSUE THREAD

**Issue by prabalsharma** [rancher-sandbox/rancher-desktop#2927]
### Actual Behavior

Cannot select k8s version after `factory reset`. k8s version is set to `latest`

### Steps to Reproduce

1. factory reset
2. check to see if settings.json gets deleted 
```
± cat $HOME/Library/Preferences/rancher-desktop/settings.json
cat: /Users/prabal/Library/Preferences/rancher-desktop/settings.json: No such file or directory
```
3. Select k8s version, other than `latest`
<img width="322" alt="Screen Shot 2022-09-16 at 4 30 25 PM" src="https://user-images.githubusercontent.com/3749546/190830362-9c0109fb-774a-4bcf-a67b-8998c37a424f.png">

4. Check k8s version is settings
```
± cat $HOME/Library/Preferences/rancher-desktop/settings.json
{"version":4,"kubernetes":{"version":"1.25.0","memoryInGB":4,"numberCPUs":2,"port":6443,"containerEngine":"containerd","checkForExistingKimBuilder":false,"enabled":true,"WSLIntegrations":{},"options":{"traefik":true,"flannel":true},"suppressSudo":false,"hostResolver":true},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"k8s.io"},"telemetry":true,"updater":true,"debug":false,"pathManagementStrategy":"rcfiles"}
```

### Result

k8s version is set to latest, instead of the selected one

### Expected Behavior

k8s version should be set to 1.22.13

### Additional Information

I can change the k8s version after the initial run

### Rancher Desktop Version

1.5.0-544-g296c105f

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
Happens to me too. I selected 1.19.x but got 1.25.x.

**Comment by IsaSih** [comment]
Also happens to me. Selected 1.18.x got 1.25.x

**Comment by gunamata** [comment]
Happens to me too on Windows 10 Enterprise
