### ISSUE TITLE
Supporting Utilities does not show up in Rancher Desktop on Apple Silicon

### ISSUE THREAD

**Issue by byteknacker** [rancher-sandbox/rancher-desktop#2933]
### Actual Behavior

I cannot see the Supporting Utilities section on the Rancher Desktop app. I installed nerdctl in lima and use lima nerdctl to build and push images. But when I am using the --namespace k8s.io, the images are not available in the Kubernetes cluster spun up by Rancher Desktop. Both are running on the same host.

### Steps to Reproduce

Download the 1.5.1 version release for Apple Silicon and install it. Open the app and there is no Supporting Utilities section. 

### Result

<img width="938" alt="Screenshot 2022-09-19 at 15 43 36" src="https://user-images.githubusercontent.com/10653912/191031571-f6dbf3ab-fefd-46a8-9d2c-175fd1001edf.png">

### Expected Behavior

Supporting Utilities should show up on Rancher Desktop and I can download and install nerdctl with it and connect nerdctl with Rancher Desktop. 

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.22.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

MacBook Pro (13-inch, M1, 2020), Version 12.6 (21G115), macOs Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by jandubois** [comment]
There is no "Supporting Utilities" entry in RD 1.5 anymore; the functionality is controlled by adding `~/.rd/bin` to the `PATH`. You are prompted to enable this automatically during installation, and you can change this in the preferences on the App settings page in the Environment tab.

If you had done this, but still couldn't invoke the RD `nerdctl`, then maybe you didn't start a new shell after enabling `PATH` integration?

Using `nerdctl.lima` will talk to the `default` VM from Lima and not the RD VM, which explains why you didn't see the images in RD.

I hope this clears everything up! I'm going to close this, but feel free to follow up if you continue to have issues!

**Comment by byteknacker** [comment]
Yes you can close this issue. All clear now! I just had to restart my shell.
