### ISSUE TITLE
CI Build Test: Ran into ENOENT: no such file or directory, open '\\wsl$\rancher-desktop\etc\hosts'

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2934]
### Actual Behavior

Ran into ENOENT: no such file or directory, open '\\wsl$\rancher-desktop\etc\hosts' at the first launch post installation.

### Steps to Reproduce

I noticed this behavior with the CI build: 

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3071306322

Steps:

- Have the current release 1.5.1 installed on your machine.
- Close the Rancher Desktop application if it's running
- Install above CI build
- After installation, I ran into the error as shown in the screenshot.

At this stage, no commands (I tried nerdctl, kubectl ) work. I had to perform `Reset Kubernetes` to restore the session to a working state.

### Result

![image](https://user-images.githubusercontent.com/59538726/191037265-df087db6-8ea4-4c6e-a35e-6029cec51330.png)

### Expected Behavior

Rancher Desktop launches with out any error.

### Rancher Desktop Version

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3071306322

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
Happened to me too. I had uninstalled RD 1.5.1 before installing the CI build. There is no `rancher-desktop` distro at the time this error happens:

```console
C:\Users\Jan>wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
openSUSE-Leap-15.2
rancher-desktop-data
```

**Comment by jandubois** [comment]
The distro exists, but seems to get deleted just before the error pops up"

```console
C:\Users\Jan>wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
openSUSE-Leap-15.2
rancher-desktop-data
rancher-desktop

C:\Users\Jan>wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
openSUSE-Leap-15.2
rancher-desktop-data
```

**Comment by jandubois** [comment]
```console
C:\Users\Jan\AppData\Local\rancher-desktop\logs>type wsl-exec.log
Unregistering...
```

**Comment by jandubois** [comment]
This seems to happen every single time I install RD after uninstalling the previous version.

It seems to work after stopping and restarting the app, but the RD directories are not on the PATH; neither in a Windows shell nor in the Ubuntu distro.

Also weird: WSL integration is already checked for Ubuntu, but not for openSUSE (they are both version 2 distros).

**Comment by jandubois** [comment]
@gunamata said that running a "Factory Reset" will restore the failed setup to working conditions, and I can confirm that it worked for me as well.
