### ISSUE TITLE
Diagnostics check for zsh not working correctly

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2951]
Testing using https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3094433305

The diagnostics claim:

```
The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your zsh shell. 
```

But this isn't true:

```console
$ zsh -c 'echo $PATH'
/Users/jan/.rd/bin:/Users/jan/bin:[...]
```

**Comment by gaktive** [comment]
@jandubois to provide corrected command.

**Comment by jandubois** [comment]
I find that `bash -i -c` and `zsh -i -c` work.

I also get correct results from `bash -l -c`, but not from `zsh -l -c`.

Note that you have to drop STDERR and only parse STDOUT.

**Comment by jandubois** [comment]
The fix doesn't seem to be working; I still get the `zsh` diagnostic, even though the directory is in the `PATH`:

```console
$ export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ zsh -i -c 'echo $PATH'
/Users/jan/.rd/bin:/usr/local/Cellar/zplug/2.4.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by ericpromislow** [comment]
Also, running `bash -i ...` or `zsh -i ...` is causing `npm run dev` to suspend.

**Comment by jandubois** [comment]
The problem turns out to be due to iTerm shell integration, which outputs additional information via invisible ANSI escape sequences to the terminal:

```console
$ zsh -i -c 'echo $PATH' | hexdump -C | head -5
00000000  1b 5d 31 33 33 37 3b 52  65 6d 6f 74 65 48 6f 73  |.]1337;RemoteHos|
00000010  74 3d 6a 61 6e 40 6d 61  63 74 6f 70 07 1b 5d 31  |t=jan@mactop..]1|
00000020  33 33 37 3b 43 75 72 72  65 6e 74 44 69 72 3d 2f  |337;CurrentDir=/|
00000030  55 73 65 72 73 2f 6a 61  6e 07 1b 5d 31 33 33 37  |Users/jan..]1337|
00000040  3b 53 68 65 6c 6c 49 6e  74 65 67 72 61 74 69 6f  |;ShellIntegratio|
```

My suggestion is to add a newline and some other prefix to the output, e.g.

```console
$ zsh -i -c 'printf "\nPATH=%s\n" $PATH'

PATH=/Users/jan/.rd/bin:/usr/local/Cellar/zplug/2.4.2/bin:/Users/jan/.rd/bin:/Users/jan/bin:[...]
```

That way we can filter (inside RD, not in zsh) with `/^PATH=(,*)$/` to extract the proper PATH.
