### ISSUE TITLE
Diagnostics should hide muted diagnostics by default

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2953]
Right now muted diagnostics are visible by default.

Hiding them by default has the usability issue that any newly hidden diagnostics vanish immediately once you mute them. For a later release I suggest the "Hide muted diagnostic" should only apply to diagnostics already muted when the page is initially displayed.

Any of the following actions would hide newly muted diagnostics:
* toggling "Hide muted" off and back on
* Re-running diagnostics
* Changing settings via preferences (because that also triggers re-running diagnostics)
* Switching away from the diagnostics tab, and back to it

For the Next milestone I would just like the default to change, and we can live with the fact that hiding a diagnostic will make it disappear right away.

**Comment by mook-as** [comment]
We're going to flip the meaning of the switch around instead so that turning _on_ the button shows muted items.
