### ISSUE TITLE
Diagnostics should catch exceptions for individual checkers

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2954]
It claims that it was run "53 years" ago, which would be impressive uptime, but I actually only started the app half an hour ago:

<img width="163" alt="Screen Shot 2022-09-20 at 8 33 26 PM" src="https://user-images.githubusercontent.com/78947/191408808-24aa5219-1641-455c-ad5f-2110edc2b9e5.png">

**Comment by rak-phillip** [comment]
@jandubois can you provide more details on your environment/how to reproduce? I'm not able to easily get into a state with a last run date of "53 years ago"

![image](https://user-images.githubusercontent.com/835961/191554869-dac4298b-97ff-438e-b22e-306ab29b234e.png)

**Comment by jandubois** [comment]
I just run Rancher Desktop, and it always shows 53 years for me.

I'm using the build from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3094433305 for testing.

I suspect you may still be running `npm run dev`. For release testing we should only use CI builds installed into the default install location.

**Comment by rak-phillip** [comment]
I did another attempt with the build you referenced and still cannot reproduce.

<img width="1052" alt="Screen Shot 2022-09-21 at 9 23 06 AM" src="https://user-images.githubusercontent.com/835961/191558819-6254f84a-bd28-48f8-bed1-54e1afcfd5c0.png">

**Comment by jandubois** [comment]
I don't know what else to say; there must be some code path that doesn't initialize the timestamp (or doesn't fetch the time correctly).

Assuming this is using Unix style time functions, 53 years since the beginning of the epoch (1. Jan 1970) is 1. Jan 2023, which matches today (rounded up to years), so I think it shows that the value is still 0.

**Comment by prabalsharma** [comment]
saw the same on https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3094941803

![image](https://user-images.githubusercontent.com/3749546/191573769-06e2a0ae-77d7-4a2c-acc7-ec9f81eb789e.png)
