### ISSUE TITLE
Diagnostics don't seem to be re-run when setting change

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2956]
I went into Preferences and changed PATH settings to Manual. I verified in a new `bash` session that `~/.rd/bin` was no longer on my PATH.

The Diagnostics tab (and badge count) did not change; only the `zsh` PATH diagnostics was displayed.

Pressing the "Re-run" button also had no effect.

Now, rather surprisingly, restarting RD also did not change anything, so maybe the `bash` test is not working and can never fail?

I now ran `rm ~/.docker/cli-plugins/docker-compose` and pressed the "Re-run" button once more. Again nothing happened, so either the button doesn't do anything, or this test also cannot fail.

So I quit RD once again, and ran `touch ~/.docker/cli-plugins/docker-compose` to prevent RD from creating the symlink on startup. On restart RD now displayed the symlink diagnostic, proving that the diagnostic works, but the button does not.

**Comment by ericpromislow** [comment]
I no longer see any of these problems after applying PR #2969. Please reopen if this isn't the case.
