### ISSUE TITLE
rdctl factory-reset should be implemented in the CLI

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2957]
Right now it is impossible to do a proper cleanup when the machine is in a state where even an uninstall/reinstall doesn't result in a running RD app because `rdctl factory-reset` only works when it can connect to the server.

The functionality should be migrated to the CLI, and the GUI code should invoke the CLI to perform the reset, so that is is always available.

**Comment by jandubois** [comment]
This functionality will also be needed by an uninstaller, so double-check requirements with #3104

**Comment by ericpromislow** [comment]
On macOS we also need to sudo-delete `/etc/sudoers.d/zzzzz-rancher-desktop-lima` , `/opt/rancher-desktop` and probably some other files and directories.
