### ISSUE TITLE
CI Build Test: Cannot install Rancher Desktop on windows

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2961]
I am not able to install Rancher Desktop on my Windows 10 Enterprise version. During the installation process, I see below pop up, and on accepting the dialog, the installation aborts. 

I am trying to install this build - https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3094941803

![PXL_20220921_165657735](https://user-images.githubusercontent.com/59538726/191581168-42f144e5-c1bf-406a-98e6-f6b20eb8c509.jpg)

![PXL_20220921_165704361](https://user-images.githubusercontent.com/59538726/191581139-8fa48476-9b76-4e92-9e83-8cdad9663a09.jpg)

![image](https://user-images.githubusercontent.com/59538726/191581226-3bd3bdd5-7211-4ab9-b029-31b1c0c2e625.png)

**Comment by jandubois** [comment]
Fixed by #2959
