### ISSUE TITLE
Don't include muted diagnostics in failed diagnostics count

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2965]
The diagnostics tab currently reports "1 failed (1 muted)" if there is a single failed diagnostic that is being muted.

Instead it should say "0 failed (and 1 muted)" to make this unambiguous.

I.e. don't include the muted in the failed count, and add the word "and" to show that the second number is not a subset of the first (e.g. when you have "1 failed (1 muted)").

_Originally posted by @jandubois in https://github.com/rancher-sandbox/rancher-desktop/issues/2955#issuecomment-1253953962_

**Comment by ericpromislow** [comment]
This was all done as part of #2955 (Sorry, Mark)
