### ISSUE TITLE
Diagnostics badge count is not correct

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2976]
When I start RD it shows a badge count of `1`. I can let it sit for 10min, and nothing changes.

As soon as I click on the Diagnostics tab, the badge count jumps to `2` and true enough, there are 2 failing diagnostics in there.

**Comment by mook-as** [comment]
Which two diagnostics are failing when this happens? Can you post `diagnostics.log`?

**Comment by mook-as** [comment]
I managed to reproduce this, but in the opposite direction; recording attached.
[diagnostics.log](https://github.com/rancher-sandbox/rancher-desktop/files/9629550/diagnostics.log) — after the 30s break is when I started interacting with the UI.

This was probably where the `connectedToInternet` check was triggered, but the UI had no way to know that an update was needed. Switching to the diagnostics paged caused vuex store to do a fetch, so everything was updated at once.


https://user-images.githubusercontent.com/3977982/191855148-1c0bd881-5fb7-4f39-8493-c348b75a9106.mov

**Comment by jandubois** [comment]
I can't repro this anymore right now, but I also have too many different CI builds now to keep them straight in my head.

I still think the UI needs to be triggered to update the badge any time diagnostics have been updated, so if you know about cases, where it isn't, then please see if you can fix it.

Otherwise I'm also fine with closing this issue for now, and re-opening it when/if we have a repro again.

**Comment by rak-phillip** [comment]
Thanks for the logs, although I still can't repro this one. We could probably disable fetching diagnostics when we navigate to the Diagnostics page if you're able to reliably reproduce, this way we can at lease see what the extra failed check is:

https://github.com/rancher-sandbox/rancher-desktop/blob/ef243b71214b1ddd140904508e32053b13d40e8d/src/pages/Diagnostics.vue#L15

**Comment by jandubois** [comment]
> Otherwise I'm also fine with closing this issue for now, and re-opening it when/if we have a repro again.

Can't repro with RC0 build either, so closing for now.
