### ISSUE TITLE
Change data directories to make more sense

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#298]
We're currently (transitively) using [xdg-portable](https://www.npmjs.com/package/xdg-portable) for managing our paths; this is leading to unusual things like `%LOCALAPPDATA%\xdg.state\rancher-desktop\logs` or `~/Library/State/rancher-desktop`, which looks foreign on both systems.  We may want to consider fixing things to use more native-looking paths. instead.

**Comment by jandubois** [comment]
The canonical log location on macOS is `~/Library/Logs/rancher-desktop`. Using it also makes them browsable with `Console.app`.

**Comment by mook-as** [comment]
Related Apple documentation: [Overview](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html)

**Comment by ericpromislow** [comment]
Note that on my machine the only org using the bundle IDs (e.g. `com.companyname.ProductName` for subdirectories in `~/Library/Caches` and `~/Library/App...Support` is Apple.

**Comment by jandubois** [comment]
<details>
<summary>You must not have any 3rd-party software installed then</summary>

$ ls ~/Library/Caches | perl -nE 'say $1 if /^(\w+\.\w+)\./' | uniq
2BUA8C4S2C.com
86Z3GCJ4MF.com
at.obdev
co.eclecticlight
com.Breakpad
com.DigiDNA
com.adobe
com.agilebits
com.apple
com.aspyr
com.belightsoft
com.bjango
com.blacey
com.blackpixel
com.bluejeans
com.bluejeansnet
com.brettterpstra
com.choosyosx
com.cleverfiles
com.clickontyler
com.cogsciapps
com.crashlytics
com.deltopia
com.docker
com.dropbox
com.etwok
com.expandrive
com.flexibits
com.getdoxie
com.getdropbox
com.google
com.googlecode
com.haystacksoftware
com.helftone
com.houdah
com.ironic
com.kapeli
com.knoxformac
com.latenightsw
com.logmein
com.macility
com.macitbetter
com.macphun
com.manytricks
com.mediaatelier
com.microsoft
com.mizage
com.noodlesoft
com.plausiblelabs
com.readdle
com.runningwithcrayons
com.softraid
com.stairways
com.stclairsoft
com.surteesstudios
com.viscosityvpn
com.vmware
fr.handbrake
info.eurocomp
io.fabric
net.java
net.telestream
org.gnu
org.gpgtools
org.pqrs
org.videolan
us.zoom
</details>

**Comment by ericpromislow** [comment]
Not a whole lot on the relatively new work machine. Probably a different story on my personal laptop.

**Comment by mook-as** [comment]
Planning on where things should go; feel free to edit this comment as we think of more things.

Type | Current Location | Desired (Windows) | Desired (Mac)
--- | --- | --- | ---
Logs | `${XDG.state}/logs` | `LocalAppData\rancher-desktop\logs` | `~/Library/Logs/io.rancherdesktop.app`
Lima VM | `${XDG.state}/lima` | N/A | `~/Library/Application Support/io.rancherdesktop.app/lima`
WSL distro | `${XDG.state}/distro` | `LocalAppData\rancher-desktop\wsl` | N/A
Caches | `${XDG.cache}` | `LocalAppData\rancher-desktop\cache` | `~/Library/Caches/io.rancherdesktop.app`
Settings | `${XDG.config}` | `RoamingAppData\rancher-desktop` | `~/Library/Preferences/io.rancherdesktop.app`
Electron / Chromium Data | `${XDG.data}` | `RoamingAppData\rancher-desktop` | `~/Library/Application Support/io.rancherdesktop.app`

I couldn't find a Windows equvialent of the macOS Library directory stuff; best I found was [known folders](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid).

For Windows, instead of `rancher-desktop` we may also want to consider `SUSE\Rancher Desktop` or `Rancher\Rancher Desktop`; having subdirectories by company seems to happen a few times on my machine (though inconsistently).

**Comment by jandubois** [comment]
I have some concerns that the directory name for `$LIMA_HOME` is getting very long. It now allows a maximum of 13 characters for the username before it will break. I think that is not good enough.

```
/Users/1234567890123/Library/Application Support/io.rancherdesktop.app/lima/rancher-desktop/serial.sock
```

Socket names on macOS must be less than 104 characters long (104 char is the buffer size, which includes a trailing `\0`; the limit on Linux is 108).

One way to get more space for the username would be to change the lima instance name from `rancher-desktop` to a single character...

Also maybe shorten `io.rancher-desktop.app` to `rancher-desktop`? The `.app` suffix is redundant, given that the parent directory is already called `Application Support`. And if we use a URL, we should use `io.rancherdesktop`, which is the domain we actually use and control. But I prefer to keep the dash in the name because that's how I search for related directories:

```console
$ fd rancher-desktop
Caches/rancher-desktop
State/rancher-desktop
State/rancher-desktop/lima/_config/rancher-desktop.yaml
State/rancher-desktop/lima/rancher-desktop
Preferences/rancher-desktop
Preferences/io.rancher.rancher-desktop.plist
Application Support/rancher-desktop
Application Support/CrashReporter/rancher-desktop_BB91A231-8B81-5794-8293-FC46153BEB40.plist
Application Support/KeyCue/Key Counts/rancher-desktop.plist
Saved Application State/io.rancher.rancher-desktop.savedState
Application Support/KeyCue/Application Icons/rancher-desktop.tif
```

**Comment by cpapad** [comment]
> 

Hello everyone!
Trying to get started with rancher-desktop today and unfortunately my user name is 22 characters and i cannot change it because it is a company laptop and the username was preconfigured. Is there any workarounds I can use for the time being? Thank you in advance

**Comment by jandubois** [comment]
@cpapad @luizfernandow

> my user name is 22 characters

There is a workaround in https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877

**Comment by cpapad** [comment]
Worked like a charm thank you!
