### ISSUE TITLE
CI Build Test: Installation shows an additional pop up 

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2999]
When installing on my Windows 10 Enterprise, I see a pop up similar to what's shared in https://github.com/rancher-sandbox/rancher-desktop/issues/2961 

However, after accepting the pop up, the installation proceed further and completed.

The build I used is: https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3114361781 

![image](https://user-images.githubusercontent.com/59538726/192035798-6fb68929-9472-4579-8183-27609451d006.png)

![image](https://user-images.githubusercontent.com/59538726/192035872-6ea4a716-7e3b-4871-b1af-b03dcdc92e92.png)

**Comment by mook-as** [comment]
This is expected (to install the new privileged service component).  Note that you should only see _one_ popup for the whole run; you should _not_ see an additional popup for installing WSL (even if it was not previously installed).

**Comment by gunamata** [comment]
Ok. @jandubois , Do we need to add a note in the release note or elsewhere that this pop up is expected?

**Comment by jandubois** [comment]
> Do we need to add a note in the release note or elsewhere that this pop up is expected?

@gunamata Probably, along with instructions how to run the installer as a non-admin (if that is possible), and which features will be unavailable in that case. Please check with @Nino-K if you need more information about that case.

**Comment by Nino-K** [comment]
So the new behavior as follows:

Our users should still be able to do both non-admin and admin installation. If admin installation is chosen you will have "Rancher Desktop Privileged Service" running as a service in their `windows.msc`. Also, admin install requires a UAC (once only) prompt both during installation and uninstall. The Rancher Desktop Privileged Service will allow our users to see the new behavior with the publish ports, allowing them to bind to `0.0.0.0` and not only `127.0.0.1`(old behavior).
  
If one decides to continue with a non-admin install they will not have the "Privileged Service" running on their machine. Also, the publish ports behavior will be the same as before, meaning that they can only bind to `127.0.0.1`. Furthermore, they will not be getting a UAC prompt during uninstall.

**Comment by gaktive** [comment]
@gunamata to document this behaviour for this release. @mook-as to file an enhancement ticket to clarify what this pop-up means for the installing user.

**Comment by gunamata** [comment]
Added a note to the installation docs in this PR - https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/106

Tested by signing the latest CI build, and the installation shows only one pop up during installation, which is expected.
