### ISSUE TITLE
CI Build Test: Rancher Dashboard doesn't load

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#3012]
With the latest CI build, https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3116291195, the Rancher Dashboard is not working on my Windows 10 Enterprise. I see below error message in the steve.log

`2022-09-26T15:47:00.655Z: stderr: time="2022-09-26T08:47:00-07:00" level=error msg="Failed to read API for groups map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]"
`

![image](https://user-images.githubusercontent.com/59538726/192324383-93a8ff5c-7b4f-4294-84d4-6c4b7cc13ebf.png)

**Comment by adamkpickering** [comment]
I was able to reproduce this once, by doing a factory reset, uninstalling my current version, and installing via "Rancher Desktop Setup.exe". However, after that I ran it via the zip and didn't experience the same issue. And now that I've done that, I can't reproduce it with the installed version of RD.

**Comment by adamkpickering** [comment]
Sorry, nevermind... it seems that the installation process for "Rancher Desktop Setup.exe" ran the right version (that produces the error). But now when I run Rancher Desktop from the dock, it runs an older version of RD that I thought I uninstalled. I need to understand this better.
