### ISSUE TITLE
Diagnostics warnings not displaying error for env PATH of zsh shell

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3019]
### Actual Behavior

When defining in the first-run window to add PATH tools to MANUAL, diagnostics is displaying a warning message advising the user to add the tools in the PATH only for bash shell. And not for zsh shell. 

### Steps to Reproduce

1. Install and run Rancher Desktop
2. Define PATH to manual in the first-run window
3. Check diagnostics messages 

### Result

<img width="953" alt="Screen Shot 2022-09-26 at 3 57 35 PM" src="https://user-images.githubusercontent.com/70187881/192395430-d197c1e6-92c4-4bfc-b5bd-89322d51b3ca.png">

### Expected Behavior

Diagnostics should display warnings to add tools to PATH for both bash and zsh shell

### Rancher Desktop Version

1.5.0-701-g2d00a573

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
This works for me.

<img width="678" alt="Screen Shot 2022-09-27 at 2 01 44 PM" src="https://user-images.githubusercontent.com/78947/192634691-d77a5017-8b04-4991-8317-9531bd932cb3.png">

**Comment by ericpromislow** [comment]
Would be good to have the contents of `~/.bashrc` and `~/.profile` because given those error messages in the terminal window, something isn't correctly configured

**Comment by jandubois** [comment]
Please check if #3060 or #3061 are fixing this issue!

**Comment by adamkpickering** [comment]
FWIW I can't reproduce this on openSUSE Leap 15.3.

**Comment by ericpromislow** [comment]
Can't reproduce this on macOS (intel) with [run 3155414378](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3155414378)
