### ISSUE TITLE
1.6.0 Release: VirusTotal false positives

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#3029]
### Actual Behavior

Various scanners on VirusTotal are flagging our executables.

### Steps to Reproduce

Take a build and post them on VirusTotal.

### Result

- [Setup exe](https://www.virustotal.com/gui/file/f59014881063d0d4f35b9669aa18ede067ef85f4fbf9b64455b258a73a625f2b) (1 hit, BitDefenderTheta)
- [Zip build](https://www.virustotal.com/gui/file/810e879883fbaac8f7a7b9fa3f61f0f04d4851787db05f524cb8495e3ff13fff) (2 hits, BitDefenderTheta, Cylance)
- [Rancher Desktop.exe](https://www.virustotal.com/gui/file/7b70d413a4c7c0d750e89b83cb00158f9b45514dd92a1abdf3ce4a8a2bca71d6) (electron stub) (1 hit, Gridinsoft)
- [wsl-helper](https://www.virustotal.com/gui/file/6B4F0DA285E82285535AC1DE792E91558B0C02A048F0C52E723216323BCD62B0/detection) (1 hit, MaxSecure)
- [docker-credential-ecr-login](https://www.virustotal.com/gui/file/3356e38a20566d688ac6ed22a9999ecca4559ed56eec4d402430b581cae84bb9/detection) (1 hit, MaxSecure)
- [docker-credential-none](https://www.virustotal.com/gui/file/88B6B7F314E2BF3BD40E2361A8F7C6DDAEE32FD76F5DFA250A3E919842E73C68/detection) (2 hits, Cynet, SecureAge)
- [docker-credential-wincred](https://www.virustotal.com/gui/file/A4E7885D3D469B2E3C92AB72C729E35DF94ED1952BC8090272107FEF0652E474/detection) (1 hit, SecureAge):
- [nerdctl-stub](https://www.virustotal.com/gui/file/68874B3E51845641915F4FDE815D73911EF684B078038C037B315F080B2556B4/detection) (5 hits, Cynet, Google, Ikarus, MaxSecure, SecureAge) — see also #2978
- [rdctl](https://www.virustotal.com/gui/file/6680D90B6902B8DD19387EE90667DAF022AB7103E04FA7390ED6AC10ACE02E89/detection) (3 hits, Cylance, Cynet, MaxSecure)
- [host-resolver](https://www.virustotal.com/gui/file/026404A77BD6A2DB1025CC3CE1180820DBBB694ACA955802B0EBD59C62A5B210/detection) (2 hits, Cynet, MaxSecure)
- [privileged-service](https://www.virustotal.com/gui/file/979C479EDC19F8007AB1FFB5518A4517C684BBB2D561797379CE6B6466090039/detection) (2 hits, Cynet, SecureAge)
- [vtunnel](https://www.virustotal.com/gui/file/49237038abfbe3feb97e812b7328efdd71000ddd4a1257623cd16e08b283c8e0/detection) (3 hits, Cynet, MaxSecure, SecureAge)

### Expected Behavior

No false positives in the virus scanners.

### Rancher Desktop Version

1.5.0-701-g2d00a573

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 21H2 (Build 19044.2006)

### What CPU architecture are you using?

x64

### Windows User Only

N/A

**Comment by macedogm** [comment]
@jandubois I got some spare time next week. Let me support you on this.

**Comment by jandubois** [comment]
@macedogm Thank you! Please wait until 1.6.0 is released before reaching out to the vendors!

**Comment by fm-knopfler** [comment]
Can confirm that this is an issue in practice. Palo Alto Cortex on my corporate-managed Windows 10 computer suddenly blocked RD from running.

Details from Cortex XDR:
```
Application Information:
Source process ID: 11384
Source process name: old-uninstaller.exe
Source application location: C:\Users\user042\AppData\Local\Temp\nsy731D.tmp\old-uninstaller.exe
Source process command line: "C:\Users\user042\AppData\Local\Temp\nsy731D.tmp\old-uninstaller.exe" /S /KEEP_APP_DATA /currentuser --keep-shortcuts --updated _?=C:\Users\user042\AppData\Local\Programs\Rancher Desktop
Source application version: 1.5.1.0
Source application publisher: SUSE
Source application signers: Suse LLC
Source process user name: user042

Prevention Information:
Prevention date: Freitag, 26. August 2022
Prevention time: 17:01:11
OS version: 10.0.19044
Component: WildFire
Cortex XDR code: C0400055
Prevention description: Verdächtige Ausführbare Datei entdeckt
Verdict: 2
Quarantined: False
Post-Detected: False
Hash: 469d2c816f2ff0092adbe72746fd3e9713b1c4a008245e6f1a165a18b95bc558
Additional information 1: C:\Users\user042\AppData\Local\Temp\nsy731D.tmp\old-uninstaller.exe
Additional information 2: 469D2C816F2FF0092ADBE72746FD3E9713B1C4A008245E6F1A165A18B95BC558
Additional information 3: 469D2C816F2FF0092ADBE72746FD3E9713B1C4A008245E6F1A165A18B95BC558
Additional information 4: 2
```

**Comment by gaktive** [comment]
I'll sync with @gunamata on the process. This may lead to us signing more executables; @jandubois to file issues for that and then for regular scans for subsequent checks.

**Comment by jandubois** [comment]
For the actual 1.6.0 release I see just the usual suspect:

```
Trapmine: Malicious.high.ml.score
```

I guess they are still struggling with their machine learning system...

**Comment by jandubois** [comment]
> This may lead to us signing more executables; @jandubois to file issues for that and then for regular scans for subsequent checks.

I filed #3146 and #3147 for this.

**Comment by gunamata** [comment]
I submitted false positive reports with the vendors. One of them responded acknowledging the false positive, and mentioning they will update their definitions database to whitelist. I will recheck to see if the number of flags come down sometime next week.

**Comment by gaktive** [comment]
We've submitted and didn't get much feedback. We'll see what happens with our next release.
