### ISSUE TITLE
Wording inconsistent between Container Engine and Container Runtime

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#3037]
### Actual Behavior

Tray menu: 
![image](https://user-images.githubusercontent.com/3977982/192647604-3a7c0159-7ac6-4d7e-b687-956efd391f46.png)

Preferences window:
![image](https://user-images.githubusercontent.com/3977982/192647666-ba8b9c7d-ee70-4794-8aec-942637478c58.png)

### Steps to Reproduce

1. Open preferences window.
2. Open tray menu.

### Result

The name for "the thing that runs containers" is inconsistent between the two places.

### Expected Behavior

Pick one phrase and stick to it throughout the application.

### Rancher Desktop Version

1.5.0-701-g2d00a573

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home 21H2 (Build 22000.1042)

### What CPU architecture are you using?

x64

### Windows User Only

N/A

**Comment by jandubois** [comment]
In #2642 we switched to "Container Engine", but it looks like we missed some instances.

**Comment by rak-phillip** [comment]
See also the discussion for #3039
