### ISSUE TITLE
Diagnostics: run timestamp can be in the future.

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#3041]
### Actual Behavior

Immediately after rerunning diagnostics, the show timestamp indicates that it was last ran in the future.

![image](https://user-images.githubusercontent.com/3977982/192663196-9b86ee98-9a06-458a-801d-5f350d2840ab.png)

### Steps to Reproduce

Click on _Rerun_ in the Diagnostics page.

### Result

See screenshot above.

### Expected Behavior

The text should say "just now" or some other text implying that the diagnostics run did not happen in the future.

### Additional Information

The state lasts a varying amount of time, up to maybe a second — so it's probably only when last run time is exactly the same as current time (down to the second).

### Rancher Desktop Version

1.5.0-701-g2d00a573

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home 21H2 (Build 22000.1042)

### What CPU architecture are you using?

x64

### Windows User Only

N/A

**Comment by ericpromislow** [comment]
The PR has a unit test that shows why this occurs immediately after the `timeLastRun` field is updated.
