### ISSUE TITLE
Diagnostics for ~/.rd/bin not on PATH appear after First-Run

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3044]
The diagnostics seem to run before the RC files for the shells have been updates in response to the First-Run dialog.

The diagnostics are correctly cleared when I Re-run them, but displaying them initially is confusing to the user.

**Comment by mook-as** [comment]
Shouldn't it just always rerun after the settings are applied (whatever they are)?

**Comment by jandubois** [comment]
> Shouldn't it just always rerun after the settings are applied (whatever they are)?

Yes (see #3000), but it is complicated:

* Running diagnostics may take a long time, so re-running them needlessly can delay getting the right results (unless re-running them stops the run that is already in progress). So it would make sense to not run them until First-Run settings changes have been applied.

* Some diagnostics may not be possible until the container runtime, or kubernetes are actually running, so re-running directly after settings changes might not work; we may need to wait until the desired state has been reached. On the other hand, we might never reach the desired state due to an issue a diagnostic might highlight.

I think this will require further investigation to figure out.

**Comment by mook-as** [comment]
Ah, I should clarify: we should run only the affected diagnostics based on the action. (These particular ones are not long-running, and they do not depend on container runtime).

**Comment by jandubois** [comment]
> we should run only the affected diagnostics based on the action.

That would be great; I wasn't aware that we had the support for that.

**Comment by jandubois** [comment]
Confirming that #3061 seems to fix this issue; I can no longer reproduce it; neither on Intel nor on M1.

**Comment by jandubois** [comment]
Confirming that #3060 also seems to fix this issue, on both Intel and M1.

I'll leave it to @mook-as and @rak-phillip to determine which is the better approach.

Neither approach seems to fix #3000, but #3060 does update diagnostics when I switch to the diagnostics tab. If the diagnostics tab was the active tab while applying preference changes, I have to switch away, and back to it before the diagnostics badge (and list) is updated.

**Comment by mook-as** [comment]
Yeah #3060 doesn't force a UI update; we'll likely want something to do that after running diagnostics if take that one.

**Comment by jandubois** [comment]
Fixed by #3060
