### ISSUE TITLE
ENOENT when selecting Dashboard from Rancher Tray Menu

### ISSUE THREAD

**Issue by dpmerrill** [rancher-sandbox/rancher-desktop#3057]
### Actual Behavior

On Ubuntu and OpenSUSE, selecting "Dashboard" from the Rancher Desktop system tray menu, does not show the Dashboard.

### Steps to Reproduce

After Rancher Desktop has started, select "Dashboard" from Rancher Desktop system tray menu.

### Result

`Error: ENOENT, resources/rancher-dashboard/index.html not found in /home/dmerrill/rancher/resources/app.asar
    at createError (node:electron/js2c/asar_bundle:5:1255)
    at Object.e.lstat (node:electron/js2c/asar_bundle:5:4278)
    at node:electron/js2c/asar_bundle:5:4681
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
`

### Expected Behavior

Dashboard should be displayed.

### Additional Information

This is happening on Ubuntu and OpenSUSE, haven't tested Fedora/Rocky.

### Rancher Desktop Version

1.5.0-701-g2d00a573 (RC1)

### Rancher Desktop K8s Version

v1.24.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

22.04.1 LTS

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by mook-as** [comment]
This should be fixed by #3016, which is [3 commits after the build you're testing](https://github.com/rancher-sandbox/rancher-desktop/commits/8bbfcb4e3007e28c7d7278c66f13368c943b183d).
