### ISSUE TITLE
Switching to socket_vmnet does not properly restart the VM

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3067]
I do a Factory Reset, and then start RD with all default settings. When k8s is working, I try to switch from `vde_vmnet` to `socket_vmnet`:

```console
$ rdctl api --method PUT --body '{"kubernetes":{"experimental":{"socketVMNet":true}}}' settings
reconfiguring Rancher Desktop to apply changes (this may take a while)
```

The old VM is stopped, and I'm asked for the admin password (presumably because the sudoers file will change). After entering the password, nothing else happens; the VM is not started.

`lima.log` looks confused: There are attempts to stop `k3s` after already shutting down the VM with `limactl stop 0`.

The output from `limactl sudoers` also looks wrong. The problem seems to be that `_config/networks` contains neither `paths.socketVMNet` nor `paths.vdeVMNet`.

Full log: [lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/9687697/lima.log)

**Comment by jandubois** [comment]
Quitting and restarting fixes the issue; `networks.yaml` gets set to the default content, which configures `socker_vmnet`.

**Comment by mook-as** [comment]
I seem to be able to duplicate this with a local build (but not `npm run dev`).
https://github.com/rancher-sandbox/rancher-desktop/blob/5e65ce0c32679e8cfcd071e7c13367e25d310d41/src/backend/lima.ts#L1192-L1197
Somehow, after that block, `config.paths.socketVMNet` is still missing. The value of `vmnet` is `1`, so it should be entering that block. Still investigating.
