### ISSUE TITLE
Kubernetes error

### ISSUE THREAD

**Issue by prabalsharma** [rancher-sandbox/rancher-desktop#3068]
### Actual Behavior

On first run, I saw the attached Kubernetes error

### Steps to Reproduce

1. First Run
2. Select moby from first run dialog
3. Wait for Admin access dialog
4. Take some time to accept it
5. Wait for password prompt
6. take some time to input password
7. Error will pop up

### Result

K8s error

### Expected Behavior

there should be no error during first run

### Additional Information

<img width="989" alt="Screen Shot 2022-09-30 at 2 36 46 PM" src="https://user-images.githubusercontent.com/3749546/193359562-1c5e8331-ad90-440f-b3c6-0a03c6c06728.png">

**Workaround**: Reset Kubernetes 

### Rancher Desktop Version

1.5.0-739-g5e65ce0c

### Rancher Desktop K8s Version

1.24.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
I cannot reproduce this (also using `1.5.0-739-g5e65ce0c` on Catalina and Intel).

I've just switched the container engine to `moby`, but left kubernetes selected. I've waited for 1 minute before entering the admin password.

Everything started correctly.

**Comment by mook-as** [comment]
Please attach log files. (We should update the bug report template to prompt for those…)

**Comment by prabalsharma** [comment]
it was a first run, so no logs

**Comment by mook-as** [comment]
There would still be logs (just not debug logs) available; logs would be written every time you get the error dialog, at least.

**Comment by ericpromislow** [comment]
I reproduced it. I think this is the key error:
```
 stderr: 'time="2022-10-03T11:50:15-07:00" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2022-10-03T11:50:15-07:00" level=fatal msg="sudoers file \\"/private/etc/sudoers.d/zzzzz-rancher-desktop-lima\\" is out of sync and must be regenerated"\n',
  code: 1,
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl',
    'start',
    '--tty=false',
    '/Users/ericp/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ]
```

There's nothing else of interest in any of the log files.

**Comment by prabalsharma** [comment]
Was able to repro on 1.5.0-754-gc02d8c5b
Waited for 1min to accept Admin Request dialog. 

<img width="764" alt="Screen Shot 2022-10-04 at 10 33 21 AM" src="https://user-images.githubusercontent.com/3749546/193887393-19d78a0b-75d4-4927-a39a-67b732149deb.png">

This time recent logfile lines were different:

```
'time="2022-10-04T10:31:50-07:00" level=fatal msg="sudoers file \\"/private/etc/sudoers.d/zzzzz-rancher-desktop-lima\\" is out of sync and must be regenerated"\n',
  code: 1,
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl',
    'start',
    '--tty=false',
    '/Users/prabal/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ]
}
```

**Comment by ericpromislow** [comment]
This change works for me:
```
diff --git a/src/backend/lima.ts b/src/backend/lima.ts
index 298bd6fc..588802d9 100644
--- a/src/backend/lima.ts
+++ b/src/backend/lima.ts
@@ -1052,16 +1052,6 @@ export default class LimaBackend extends events.EventEmitter implements VMBacken
         }
       }
     }
-    if (haveFiles[LIMA_SUDOERS_LOCATION] && !haveFiles[PREVIOUS_LIMA_SUDOERS_LOCATION]) {
-      // The name of the sudoer file is up-to-date. Return if `sudoers --check` is ok
-      try {
-        await this.limaWithCapture(true, 'sudoers', '--check');
-
-        return;
-      } catch (ex: any) {
-        console.log(`lima sudoers --check returned failure, need to update sudoers file:\n${ ex?.stderr || '(no output)' }`);
-      }
-    }
     // Here we have to run `lima sudoers` as non-root and grab the output, and
     // then copy it to the target sudoers file as root.  Note that `limactl
     // sudoers` checks for the vmnet executables to exist, but they may not be
@@ -1074,6 +1064,20 @@ export default class LimaBackend extends events.EventEmitter implements VMBacken
     const outputPaths: string[] = [LIMA_SUDOERS_LOCATION];
 
     await fs.promises.writeFile(tmpFile, this.replaceVMNetExecutables(data), { mode: 0o644 });
+    if (haveFiles[LIMA_SUDOERS_LOCATION]) {
+      try {
+        const { stdout } = await childProcess.spawnFile('diff',
+          ['-w', tmpFile, LIMA_SUDOERS_LOCATION],
+          { stdio: ['ignore', 'pipe', console] });
+
+        if (!/\S/.test(stdout)) {
+          return;
+        }
+        console.debug(`output from diff of $(lima sudoers) vs ${ LIMA_SUDOERS_LOCATION }: ${ stdout }`);
+      } catch (ex: any) {
+        console.error(`Error running diff ${ tmpFile } ${ LIMA_SUDOERS_LOCATION }: `, ex);
+      }
+    }
     console.log(`need to limactl sudoers, get data from ${ tmpFile }`);
     commands.push(`cp "${ tmpFile }" ${ LIMA_SUDOERS_LOCATION } && rm -f "${ tmpFile }"`);
     if (haveFiles[PREVIOUS_LIMA_SUDOERS_LOCATION]) {
```
