### ISSUE TITLE
Use a supported version of kubectl for the version of Kubernetes in use

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#308]
kubectl only supports so many different versions of Kubernetes. We should look to see if there is a way to match a version of kubectl with a version of k8s. 

This came up in conversation with Flavio about https://github.com/flavio/kuberlr. Note, this project does not work on Windows.

**Comment by mook-as** [comment]
I think there's two significant edge case we should think about:
- What if the targeted cluster is not reachable? (e.g targeting a cluster that's down.)
- What if we're targeting a non-RD cluster? (i.e. the version might be unrelated to what we have in configs)

**Comment by jandubois** [comment]
> This came up in conversation with Flavio about https://github.com/flavio/kuberlr. Note, this project does not work on Windows.

It looks like it is expected to work on Windows: https://github.com/flavio/kuberlr/pull/3 We should test this!

This looks like a reasonable approach to me. We could bundle just kubectl 1.17 to cover 1.16-1.18, and kubectl 1.20 to cover 1.19-1.21 so users don't have to download anything. (Of course this will have to be maintained as newer  k8s release come out).

**Comment by jandubois** [comment]
> I think there's two significant edge case we should think about:

@mook-as Assuming we use `kuberlr`, these are non-issues, right?

**Comment by ericpromislow** [comment]
If the cluster is down, `kuberlr` complains, but still consults `~/.kube/config` to determine states like the current context.

**Comment by ericpromislow** [comment]
Closed in https://github.com/rancher-sandbox/rancher-desktop/pull/357#event-4941940253
