### ISSUE TITLE
LoadBalancers should bind to 0.0.0.0 and not just to 127.0.0.1

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3093]
### Problem Description

On Windows the Rancher Desktop Agent code binds Kubernetes LoadBalancer (and NodePort) services to `127.0.0.1`.

At least the LoadBalancer port should be bound to the external interface as well, so it is reachable on the local network.

### Proposed Solution

Just change the bind address.

### Additional Information

The behavior should be identical between platforms. On macOS the LoadBalancer services already bind to `0.0.0.0`; I have not checked the NodePorts.

On Linux we currently don't have the capability to bind to external interfaces (see #576 and #964).

- [x] Make GuestAgent to bind on `0.0.0.0` https://github.com/rancher-sandbox/rancher-desktop-agent/pull/26
- [x] This should probably be configurable via Preference settings https://github.com/rancher-sandbox/rancher-desktop-agent/pull/27

**Comment by s0nea** [comment]
The issue has been resolved in 1.8.0.
