### ISSUE TITLE
Modify `UnixIntegrationManager` so that it modifies symlinks with a target path containing `/opt/rancher-desktop/resources/resources/linux/bin/`

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3113]
Related to #2456.

@himslm01 is getting the following diagnostic error message:

> The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to /opt/rancher-desktop/resources/resources/linux/bin/docker-buildx.

Currently, `UnixIntegrationManager` only updates a symlink in `~/.docker/cli-plugins` when its target path starts with `~/.rd/bin`. We need to modify it so that it will also update symlinks whose target path starts with `/opt/rancher-desktop/resources/resources/linux/bin/`, which appears to be something that RD created in the past (pre-1.3.0 as far as I can tell).

**Comment by joelsmith3-nhs** [comment]
Also needs to cover the Darwin scenarios

> The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-buildx.

**Comment by dalesit** [comment]
Also needs to cover the Darwin scenario:

> The file ~/.docker/cli-plugins/docker-buildx should be a symlink to ~/.rd/bin/docker-buildx, but points to /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-buildx.
