### ISSUE TITLE
docker credential helper release has filename changes

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3115]
This breaks the `rddepman` update PR #3110

PR fails because `docker-credential-pass-v0.7.0-amd64.tar.gz` is now `docker-credential-pass-v0.7.0.linux-amd64.tar.gz` (added `-linux`).

There may be more changes; check full list at https://github.com/docker/docker-credential-helpers/releases/tag/v0.7.0

**Comment by adamkpickering** [comment]
#3110 is merged, so this should be closed.
