### ISSUE TITLE
Either notify RD team or automate updates of Lima and WSL image repos when new versions of cri-dockerd are available

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3120]
Same thing also for `nerdctl` updates, which are also still baked into the distros.

**Comment by jandubois** [comment]
I want to put this story "on hold" until we have decided what to do about #3286.

As for `nerdctl`, I think I would prefer to move it directly into Rancher Desktop and install it during boot time instead of bundling it in the ISO and distro.

Removing it from the "Next" milestone for now.

**Comment by jandubois** [comment]
We are not going to update cri-dockerd; we are going to drop it when #3286 is implemented.
