### ISSUE TITLE
Kubernetes Error Rancher Desktop 1.6.0 - darwin (x64) Error Starting Kubernetes

### ISSUE THREAD

**Issue by mingdaoy** [rancher-sandbox/rancher-desktop#3137]
### Actual Behavior

<img width="912" alt="image" src="https://user-images.githubusercontent.com/11248998/195401270-8dc92156-8019-4ddb-a9cf-88dda455e796.png">

![image](https://user-images.githubusercontent.com/11248998/195401518-8d8f5c34-d27a-42a1-840b-c64a2dde2933.png)

### Steps to Reproduce

1. Install Rancher Desktop and it runs for a while, then quit by itself.
2. Click the icon in the Dock to relaunch

### Result

Kubernetes Error
Rancher Desktop 1.6.0 - darwin (x64)
Error Starting Kubernetes
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
Last command run:
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl start --tty=false 0

Context:
Starting virtual machine

Some recent logfile lines:

    'time="2022-10-13T00:44:02+08:00" level=fatal msg="errors inspecting instance: [failed to get Info from \\"/Users/<user_name>/Library/Application Support/rancher-desktop/lima/0/ha.sock\\": Get \\"http://lima-hostagent/v1/info\\": context deadline exceeded]"\n',
  code: 1,
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl',
    'start',
    '--tty=false',
    '0'
  ]
}

### Expected Behavior

Start running. 

### Rancher Desktop Version

Rancher Desktop 1.6.0 - darwin (x64)

### Rancher Desktop K8s Version

1.24.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey12.6

### What CPU architecture are you using?

x64

**Comment by mingdaoy** [comment]
Cannot even start again on the first few hours

**Comment by mingdaoy** [comment]
It's in the "Result" section above, which was shown in the popup

**Comment by mingdaoy** [comment]
@jandubois are you referring to 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/11248998/195410440-70578f1a-03b4-4654-a7bb-37bdcb09b37b.png">

**Comment by mattfarina** [comment]
I am experiencing the same error under pop!_os (ubuntu based) with the deb packaged version when I upgraded to 1.6.0. It's the same error message the the original poster but with Linux based system locations.

The specific error I see is...
```
Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:1:7750)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: '',
  stderr: 'time="2022-10-12T13:42:55-04:00" level=info msg="Using the existing instance \\"0\\""\n' +
    'time="2022-10-12T13:42:55-04:00" level=fatal msg="errors inspecting instance: [failed to get Info from \\"/home/mfarina/.local/share/rancher-desktop/lima/0/ha.sock\\": Get \\"http://lima-hostagent/v1/info\\": dial unix /home/mfarina/.local/share/rancher-desktop/lima/0/ha.sock: connect: connection refused]"\n',
  code: 1,
  command: [
    '/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl',
    'start',
    '--tty=false',
    '0'
  ]
}
```

Note, this instance was docker/moby WITHOUT a running Kubernetes.

On Intel Mac the upgrade had no issues. That setup was docker/moby without a running Kubernetes as well.

My log files can be downloaded from https://1drv.ms/u/s!At6-pjJ-bCdxoERe8pHm0RsPPIRS?e=hjaCn7

**Comment by jandubois** [comment]
> Has anyone managed to find a workaround for this problem?

We have not been able to reproduce it, and for Matt the issue was gone once he restarted his machine, so not really clear what can be done about it. Is it more persistent for you?

**Comment by miguelsmuller** [comment]
yes... my first attempt at a solution was to restart...
I updated to Ventura 13.1 but I don't know if it was related.
and kubernetes was always disabled. apparently this error happens on kubernets startup when rancher starts
![Captura de Tela 2022-12-13 às 14 08 59](https://user-images.githubusercontent.com/4589909/207436796-4d84f3c0-df37-473f-be67-7d48e07d1d68.png)
![Captura de Tela 2022-12-13 às 17 27 37](https://user-images.githubusercontent.com/4589909/207436858-0daac519-4162-42d5-8d84-46bcf3fdc3ba.png)

**Comment by miguelsmuller** [comment]
I solved my problem by reinstalling rancher desktop

**Comment by frankcis-sh** [comment]
i solved my problem by enlarge memory allocate

**Comment by jandubois** [comment]
I'm going to close this as not-reproducible. I don't see anything we can do unless we have a repro case.

**Comment by mkarpicki** [comment]
I am facing same problem on Ubuntu, this is "random". 
Starting my machine and sometimes  it happens - only way to work this around is to restart laptop. Restarting Rancher, or using reset Kubernates in Troubleshooting section did not help.
Occurs maybe each second day. Which log file would be best to provide?

**Comment by mkarpicki** [comment]
ok.. I followed mentioned above thread .. 
Factory reset fixed this issue (for now at least)

**Comment by mkarpicki** [comment]
.. only for couple of restarts ... problem came back. Something seems not stable enough. Probably reset to Factory settings is good short term workaround to use.

**Comment by julian-alarcon** [comment]
I had this issue today after turning off and on my laptop. It seems that some files were not deleted after shutting down my Ubuntu OS.

Just deleting manually the `*.sock` and `.pid` files (`qemu.pid`, `serialv.sock`, `ha.sock`, `ga.sock` and similars ) from the `~/.local/share/rancher-desktop/lima/0` directory was enough.

**Comment by xadamxk** [comment]
> I had this issue today after turning off and on my laptop. It seems that some files were not deleted after shutting down my Ubuntu OS.
> 
> Just deleting manually the `*.sock` and `.pid` files (`qemu.pid`, `serialv.sock`, `ha.sock`, `ga.sock` and similars ) from the `~/.local/share/rancher-desktop/lima/0` directory was enough.

Confirming that this fixed the issue for me as well, thank you :raised_hands:

**Comment by benjamin-mogensen** [comment]
I did factory reset in Rancher Desktop, I am on macOS arm64, and it seemed to solve the issue.

**Comment by Elidrake** [comment]
@jandubois Apologies if you're the wrong person to reach after all these years, but I've been able to consistently reproduce the issue.  While running Rancher Desktop, cut the power to the Host.  As mentioned by julian above, this leaves behind sock/pids which are invalid, and rather than cleaning them up on next program start, Rancher attempts to use them, resulting in OP's error.

True at least on Ubuntu 22.04, Rancher Desktop 1.16.0.  Certainly appreciate the argument that this is user error.
