### ISSUE TITLE
Rancher Desktop set with no modal dialogs still running dialogs

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3152]
### Actual Behavior

Even running `npm run dev --no-modal-dialogs`, electron is still launching first-run dialog and sudo access dialog.

### Steps to Reproduce

1. Run npm run dev --no-modal-dialogs
2. Observe how electron launches rancher desktop

### Result

electron is still launching first-run dialog and sudo access dialog.

### Expected Behavior

If defined to run without modal dialogs, electron should launch the main window of rancher desktop and do not display any modals.

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by ericpromislow** [comment]
I'm pretty sure the command was `npm run dev -- --no-modal-dialogs` to pass on the last argument to the electron process, but this was definitely broken by commit e43a0e59c
