### ISSUE TITLE
Calls to the docker cli should always pass the context name

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3156]
When Rancher Desktop calls the `docker` cli, e.g. for the Images page, it should always prepend the args with `--context rancher-desktop`:

https://github.com/rancher-sandbox/rancher-desktop/blob/85ca1c5a42485bdde2b9991d914e7fed846e7686/src/backend/images/mobyImageProcessor.ts#L31-L35

We already do this for `kubectl` (which we access via the client api and not the commandline utility):

https://github.com/rancher-sandbox/rancher-desktop/blob/85ca1c5a42485bdde2b9991d914e7fed846e7686/src/backend/client.ts#L217

## Repro

* Delete `/var/run/docker.sock`
* Run Rancher Desktop with Moby backend without administrative privileges
* Pull any image, e.g. `docker pull busybox`
* Change the docker context: `docker context use default`
* Try to list images and if that still works (because images are cached), try to delete the `busybox` image with the UI

This should now display a failure as Rancher Desktop will run `docker rmi $IMAGEID`, which will attempt to talk to `/var/run/docker.sock` instead of `~/.rd/docker.sock`.

**Comment by cb-lixar** [comment]
If it doesn't already, the updater also should always be passing the context name when running commands, as I believe this led to a recent update semi-failure (I can't prove it since I can't find any relevant logs, though :( The logs in local\rancher-desktop\logs don't seem to have anything relevant post-update.). It said it aborted the update, but RD was updated. 🤷

**Comment by bleggett** [comment]
Yes please - I would prefer if the image builder didn't try to use the global "current" K8S context every time.

If I am doing `kubectl` ops on a remote EC2 K8S cluster in one terminal and doing image builds in the other, I don't want the image builds to be running on the remote cluster just because that's the default current context.

**Comment by jandubois** [comment]
It looks like we don't define the `rancher-desktop` context on Windows; so we would need to pass in `default` there, or (preferably) implement the context mechanism on Windows too.

We most likely haven't done it because we always just use the default `npipe:////./pipe/docker_engine` endpoint location on Windows.

**Comment by gaktive** [comment]
Per @ericpromislow, this is complicated and initial tests indicate that extensions could break so this needs more analysis.

**Comment by ericpromislow** [comment]
After looking at this, I don't understand why we need to do this. When the `rancher-context` is available, there's a `"currentContext": "rancher-desktop"` entry in `~/.docker/config.json`. Isn't this sufficient?

**Comment by cb-lixar** [comment]
No, that's incorrect. The `currentContext` may change outside of Rancher Desktop, such as when the user is making use of other Kubernetes clusters. If the user doesn't reset the context for you, then you may end up executing actions on another cluster when you're trying to operate on RD.

**Comment by ericpromislow** [comment]
ok. The challenge in the code base is that some of the invocations of `docker` actually run directly on the VM, so we don't want to specify any context. 

We do want to specify the context for calls to `docker` run locally.

**Comment by jandubois** [comment]
> some of the invocations of `docker` actually run directly on the VM

That sounds like a source for errors. We should run all of them consistently either on the host or inside the guest, but not use a mix.

Where do we run the `docker` command inside the VM?
