### ISSUE TITLE
Release unused space back to the host

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3158]
Support for `fstrim` has just been merged into Lima: https://github.com/lima-vm/lima/pull/1102.

This makes it possible to run `rdctl shell sudo fstrim /tmp` to release all unused space from the `diffdisk` volume back to the host.

The `diffdisk` is a sparse file, so the filesize itself will not change, but unused blocks are unallocated:

```console
$ ls -lh diffdisk
-rw-r--r--  1 jan  staff   4.1G 13 Oct 20:30 diffdisk

$ du -h diffdisk
 41M	diffdisk
```

We should run `fstrim` automatically every time we stop the VM.

For this feature to work we obviously need to update to the latest Lima version first.

**Comment by CzBiX** [comment]
I believe it is more appropriate to use `fstrim /mnt/data` instead of `fstrim /tmp`.

**Comment by jandubois** [comment]
> I believe it is more appropriate to use `fstrim /mnt/data` instead of `fstrim /tmp`.

Yes, thank you!
