### ISSUE TITLE
host.docker.internal no longer resolves

### ISSUE THREAD

**Issue by benjaminkiefer** [rancher-sandbox/rancher-desktop#3163]
### Actual Behavior

attempts to reach `host.docker.internal` result in an Unknown Host exception

### Steps to Reproduce

from within a container run ping, telnet, etc. and attempt to connect to `host.docker.internal`

### Result

```
[tomadmin@6ab7cb5991c2 tomcat]$ ping host.docker.internal 

ping: host.docker.internal: Name or service not known 

[tomadmin@be015341ff3e tomcat]$ telnet host.docker.internal 1521 

telnet: host.docker.internal: Name or service not known 

host.docker.internal: Unknown host 
```

### Expected Behavior

The hostname should be resolved to the IP of the host machine

### Additional Information

I've reinstalled v1.5.1 and that corrects the issue

### Rancher Desktop Version

v1.6.0

### Rancher Desktop K8s Version

1.24.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 20H2

### What CPU architecture are you using?

x64

**Comment by Nino-K** [comment]
@benjaminkiefer Thanks for reporting this, I actually managed to reproduce this myself. We will set this as a high priority to address.

**Comment by ericpromislow** [comment]
Not seeing this on macOS, reproduced on Windows 10.

**Comment by jandubois** [comment]
> Not seeing this on macOS, reproduced on Windows 10.

Yes, it is only on Windows. @Nino-K has a fix, and we are preparing to get it into the release branch, in case we are doing a patch release.

Fix requires a series of events: first merging a patch into Lima, then updating the reference from rancher-desktop-hostagent, and making a new hostagent release, and finally bumping the dependency of the hostagent in rancher-desktop itself.
