### ISSUE TITLE
Investigate if gvisor-tap-vsock is suitable for Rancher Desktop

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#3164]
Investigate to see if can use [gvisor-tap-vsock](https://github.com/containers/gvisor-tap-vsock) as a network stack in Rancher Desktop for all platforms including Windows, Mac, and linux.

**Comment by gaktive** [comment]
@Nino-K I'll close this since it's also in Done. Let me know if there's anything left here to do; otherwise, it's in the other ticket(s).
