### ISSUE TITLE
The Main Window should remember the active tab (page) when it's closed

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3166]
### Problem Description

Similar to #2634 but for the main window.  Currently when you hit the Tray `Preferences` menu item when the main window is closed, it always comes up with the `General` tab.

### Proposed Solution

The same mechanism being used for the Preferences window should be used for the main window.

There is no requirement to remember the active page across sessions, only during a session.

And actually it's a good idea to always start a session on the General page as this is a good way for us
to notify users of any updates or other info.

**Comment by rak-phillip** [comment]
Resolved in #3010
