### ISSUE TITLE
docker-credential-oskeychain 0.7.0 and 0.8.0 get fails to retrieve records

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3171]
### Actual Behavior

```
$ nerdctl push morspin/alpine:101
INFO[0000] pushing as a reduced-platform image (application/vnd.docker.distribution.manifest.list.v2+json, sha256:594fecb3c21a93affbe9f586504afc2687f3e1db6c9a84f6fe51dc405afe2da3)
WARN[0000] cannot get auth config for authConfigHostname="https://index.docker.io/v1/" (refHostname="docker.io")  error="error getting credentials - err: exit status 22, out: `The user name or passphrase you entered is not correct.`"
$  docker-credential-osxkeychain list | jq .
{...
  "https://index.docker.io": "morspin"
}
$ echo https://index.docker.io | docker-credential-osxkeychain get
The user name or passphrase you entered is not correct.
```

Replacing `resources/darwin/bin/docker-credential-osxkeychain` with the version 0.6.4 one fixes this problem.

### Rancher Desktop Version

dev - we haven't shipped this version of the d-c helpers

### What operating system are you using?

macOS

### Operating System / Build Version

macOS 12.6

### What CPU architecture are you using?

x64

Upstream issue: https://github.com/docker/docker-credential-helpers/issues/246

**Comment by ericpromislow** [comment]
After I upgraded my mac to 12.6.1 (from 12.6.0) the latest docker-credential-osxkeychain (0.7.0) worked for me. And I didn't run into the problem some people reported, where they are repeatedly requested to type in their keychain password with 0.6.4.

We should probably wait for a version that addresses the issues at the upstream issue.

**Comment by ericpromislow** [comment]
Still holds for 0.8.0

**Comment by ericpromislow** [comment]
Upstream issue for 0.8.0: https://github.com/docker/docker-credential-helpers/issues/298

**Comment by ericpromislow** [comment]
Turns out we notarize the binary for release. I was testing with a dev build all this time.

**Comment by jandubois** [comment]
> Turns out we notarize the binary for release. I was testing with a dev build all this time.

This doesn't make sense to me. The `creds.bats` test exercises this credential helper and does pass on macOS with a CI build. And CI builds are not notarized; only the release builds are.
