### ISSUE TITLE
Issues filter input field outline is cropped/clipped by top of pane

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#3175]
### Actual Behavior

The top edge of the filter box outline is clipped

### Steps to Reproduce

1. Open Rancher Desktop
2. Select Images
3. Select an image that when scanned will yield alerts (`python:3.4-alpine` and `python:3.9-slim` appear to fit this requirement at this time
4. Click the `⋮`
5. Click `Scan…`
6. Click the `Filter` input
7. Note that the top edge is clipped

### Result

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/2119212/196022961-f6379550-bd9c-4589-be2f-5f59773f5457.png">

### Expected Behavior

The highlight should run consistently around the entire filter box

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

Off

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.6

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by ericpromislow** [comment]
I'm seeing this for all the images I've tested, on macos and linux.
