### ISSUE TITLE
Store logs on macOS under ~/Library/Logs/rancher-desktop

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#318]
The current location `~/Library/State/rancher-desktop/logs` doesn't make any sense, as `~/Library/State` is a made-up thing that shouldn't exist.

Putting logs into the proper directory also makes them browsable with `Console.app`.

**Comment by mook-as** [comment]
See also #298 which I filed as a more general case (all the other bits too).
