### ISSUE TITLE
Integrate nerdctl with buildkit into the WSL2 environment

### ISSUE THREAD

**Issue by JohnGalt1717** [rancher-sandbox/rancher-desktop#3185]
Right now, getting nerdctl working properly under WSL2 is difficult to say the least. It would be nice if the WSL2 environment generated by Rancher Desktop had nerdctl setup with buildkit so that it just worked from the bash terminal on startup. 

This would make working with containerd WAY easier on Windows.

**Comment by mook-as** [comment]
Hi! It's unclear to me what is being requested here; if you select the containerd backend, `nerdctl` in WSL2 should already be set up (we ship a Linux `nerdctl` executable application directory that does the correct forwarding, and add it to your `PATH`).  I just confirmed that using that executable, a simple `nerdctl build` worked for me.

Please extend the description with specific failing commands, etc. so we can reproduce the problem; I'll mark this issue as closed for now, but we can reopen it once we have enough information.  (Ideally, this would have been created with the issue templates so the back-and-force would have been avoidable…) Thanks!

**Comment by JohnGalt1717** [comment]
@mook-as The hardest part about getting Rancher Desktop working aside from the ingress problem on port 80/443 with external access is Nerdctl. (yes I'm aware that you can just use moby but that has another whole set of problems.)

On Mac, it's relatively straightforward because someone has created a brew for Nerdctl and buildkit.

That isn't true on Linux (I have a 50 line bash script to automate it for my team because it's so fraught with problems and gotchas.  (and there are very few tutorials on it out in the wild and the instructions given on the respective dependencies github are horrifically assumptive and inadequate in most cases. I'm pretty sure that without a 3rd party set of instructions it's not possible to follow their directions and get it installed successfully unless you have institutional knowledge)

On Windows the problem is even worse. There's one instruction guide (in wsl2, not in windows itself) and I've done it and I've gotten 5 other devs to try it and NONE of us have successfully and reliably gotten nerdctl with builds working correctly. (best we've managed is it working immediately then after a restart been unable to make it work again)

Hence, my request is, that since the racncher desktop image shows up in wsl2 and you can easily log into it, it would be ideal to have that wsl2 environment have nerdctl properly configured in it just done right and always working.

More ideal would be to have the windows installer install nerdctl on windows (in available in wsl2) fully working correctly out of the box.

And a deb and/or snap and/or rpm for linux would go a long way too.

And as a general note, nerdctl's arcane installation and myriad of dependencies that have to be perfect and aren't documented (the CNI drivers for instance have 0 documentation that any of us can find at all on how to install them on Linux let alone on windows, we have only inferred what you have to do based on other guides that mention them) is a major obstruction to Rancher Desktop and adoption will be severely harmed until this is fixed.   (The other blocker being ingress on local network)

**Comment by jandubois** [comment]
I have a hard time understand what you write about, as Rancher Desktop includes `nerdctl` and `buildkit` on every platform.

Can you provide examples of how it doesn't work for you? Ideally with a public sample project, so we can reproduce the issue?

> On Mac, it's relatively straightforward because someone has created a brew for Nerdctl and buildkit.

That isn't true, afaict, as `nerdctl` doesn't run on macOS directly; it has to run inside the same machine that runs `containerd`. The brew formula only works on Linux:

```console
$ brew install nerdctl
Running `brew update --auto-update`...
[...]
nerdctl: Linux is required for this software.
Error: nerdctl: An unsatisfied requirement failed this build.
```

**Comment by JohnGalt1717** [comment]
On windows with rancher desktop installed:

1. Nerdctl doesn't work on powershell prompt (not found)
2. Not found at ubuntu wsl2 prompt.
3. Not found at Racher-desktop wsl2 prompt.

Documentation for installing Rancher Desktop says that they pre-requisites are required and not installed and nerdctl is in that list with other things like helm and kubectl both of which are not installed by the rancher-desktop installer.

Linux:

1. Nerdctl not installed on host.
2. May or may not be in rdctl shell, didn't check because the documentation gives no instruction to do so or that that is where it lives and should be used, it just points to the nerdctl page that provides virtually no documentation on how to install nerdctl on a host and each of it's dependencies have similarly horrific help installing.

MacOS:

1. Trivial install on host.
2. Don't know about VM, haven't tried.

If Rancher Desktop is indeed installing nerdctl as part of its own install then the documentation needs to be fixed because it isn't a pre-requisite, it's installed automatically by the installer and just works and should explain how it works and where.

If Rancher Desktop isn't' installing it, then it should be. And it should be available on both the host and anywhere else it's needed with buildkit support embedded because the alternative is a disaster area of non-documentation with archane bash scripts that may or no work on windows or other platforms. Only MacOS has a viable story.
