### ISSUE TITLE
Upgrading to 1.6.0 broke DNS resolution of host.docker.internal

### ISSUE THREAD

**Issue by vitorpmoreira** [rancher-sandbox/rancher-desktop#3217]
### Actual Behavior

Kubernetes' pods are no longer able to resolve **host.docker.internal**.

### Steps to Reproduce

Using the 1.6.0 release, just create a pod and try to make a request to a service running on the host machine by using host.docker.internal or try to ping it.

### Result

Fails to resolve the host **host.docker.internal**.

### Expected Behavior

It should be able to resolve **host.docker.internal** to the same IP that is configured in the **/etc/hosts** file of the rancher-desktop distro.

### Additional Information

Tried a clean install of 1.6.0 (Factory Reset, Uninstall, Install) but it didn't help.
Downgrading to 1.5.1, solved the issue.

I believe this has to be with the DNS changes meant for the 1.5.x versions that ended up only being added to the 1.6.0.

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

1.24.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Enterprise 21H2 22000.1098

### What CPU architecture are you using?

x64

### Windows User Only

Firewall is turned on and has a rule to allow inbound traffic to the WSL.

**Comment by Nino-K** [comment]
@vitorpmoreira thanks for reporting this, it is related to [this](https://github.com/rancher-sandbox/rancher-desktop/issues/3163) issue and has already been addressed. We are doing a patch release, keep your eyes on a new patch release shortly.

**Comment by vitorpmoreira** [comment]
Oh, sorry, don't know how I didn't find that issue. Should I close this one then?

Also, thanks for the fix :)

**Comment by jandubois** [comment]
Yeah, let's close as a duplicate of #3163

**Comment by vitorpmoreira** [comment]
Ok, thank you!
