### ISSUE TITLE
Ability to choose VMs location

### ISSUE THREAD

**Issue by kevinvalleau** [rancher-sandbox/rancher-desktop#3228]
### Problem Description

VMs require some disk space and I would like to move the rancher VMs to another disk.
It would be nice, if there was a possibility to choose the VM location at installation time or a procedure to do it afterwards.

### Proposed Solution

Include a screen in the installer allowing to choose a different location for the VMs.
Show the VM location in the configuration screen and offer the possibility to change the path.
Include a procedure in the documentation to describe the steps necessary to move the VMs to another location.

**Comment by jandubois** [comment]
This is a duplicate of #369.
