### ISSUE TITLE
Add simple formatting to diagnostics

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3238]
I would like to be able to mark parts of a diagnostic as **bold** or as `code`. That way

> The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your bash shell.

could be displayed as

> The `~/.rd/bin` directory has not been added to the `PATH`, so command-line utilities are not configured in your **bash** shell.

It makes it clear which parts are paths or variable names, and it puts emphasis on the **bash** name because people have skipped over that, and thought the diagnostic applied to their **zsh** configuration.

I would propose a simplified form of markdown, using `*` to specify **bold** and `` ` `` to specify `code` (and maybe `_` to specify *italic*, just in case).

We only need to allow non-overlapping markup to keep things simple, and then it can easily be implemented with simple regex replacements, e.g.

```javascript
> p = '*"Bold * text"*. _italic _text_, and `variable_names_with_underscores`'
'*"Bold * text"*. _italic _text_, and `variable_names_with_underscores`'

> x = p.replaceAll(/(^|\s)\*(\S(?:.*?\S)?)\*([\s.,;:!?]|$)/g, '$1<bold>$2</bold>$3')
'<bold>"Bold * text"</bold>. _italic _text_, and `variable_names_with_underscores`'

> y = x.replaceAll(/(^|\s)_(\S(?:.*?\S)?)_([\s.,;:!?]|$)/g, '$1<italic>$2</italic>$3')
'<bold>"Bold * text"</bold>. <italic>italic _text</italic>, and `variable_names_with_underscores`'

> z = y.replaceAll(/(^|\s)`(\S(?:.*?\S)?)`([\s.,;:!?]|$)/g, '$1<code>$2</code>$3')
'<bold>"Bold * text"</bold>. <italic>italic _text</italic>, and <code>variable_names_with_underscores</code>'
```

The regex `(^|\s)\*(\S(?:.*?\S)?)\*([\s.,;:!?]|$)` works as follows:

It matches either at the beginning of the line, or after a space `(^|\s)`, followed by the opening formatting character `\*`.

This is followed by at least one non-space character `\S`, which is optionally followed by any number of characters, as long as the sequence ends with another non-space `(?:.*?\S)?`[^group].

After that we expect the closing formatting character `\*`, followed by a space, punctuation character, or the end of the string `([\s.,;:!?]|$)`.

[^group]: The `(?: ... )` construct is a non-capturing group, so doesn't count as `$3` in the replacement string, and `.*?` is the non-greedy version of `.*`: it captures as few characters as possible.

**Comment by mook-as** [comment]
FWIW, we already have a library to render markdown (for the release notes); it'll be much easier to just use actual markdown for this rather than doing our own.

**Comment by jandubois** [comment]
> FWIW, we already have a library to render markdown (for the release notes); it'll be much easier to just use actual markdown for this rather than doing our own.

Fine with me, as long as it works!  It probably means we would have to use `**` for **bold**, but I guess that's ok...
