### ISSUE TITLE
WSL2 installation fails if the CPU doesn't have hypervisor support enabled in the BIOS

### ISSUE THREAD

**Issue by pgonin** [rancher-sandbox/rancher-desktop#324]
I installed Rancher Desktop on a 'clean' Windows 10 Professional updated system (21H1)
No WSL and no Docker Desktop previously installed.

It fails at first start with error "Error Starting Kubernetes"
![image](https://user-images.githubusercontent.com/6192686/120609825-df70b500-c452-11eb-8df8-580220d1bc08.png)

**Comment by pgonin** [comment]
I have no distribution installed

**Comment by pgonin** [comment]
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 L'ordinateur virtuel n'a pas pu Ûtre dÚmarrÚ car une fonctionnalitÚ requise n'est pas installÚe.

Press any key to continue...
```
maybe my wsl setup is just borken...

**Comment by mattfarina** [comment]
@pgonin Thanks for trying to get this going.

Did your computer restart as part of the installation process? When Rancher Desktop sets up WSL a restart is required.

**Comment by pgonin** [comment]
Yes. It restarted a few times.
Some documentation still mentions wsl2 as a requirement, to be installed before starting the installation of Rancher Desktop.
In my case I did not have it installed before Rancher Desktop installation.

**Comment by mattfarina** [comment]
Do you happen to have a VPN setup on this machine? Looking through the details of people who have similar errors I see a VPN is a common component.

**Comment by pgonin** [comment]
No VPN
Quad9 dns (trying with something 3lse)

**Comment by pgonin** [comment]
Not an issue with DNS

That's what happens when I am trying to update WSL for WSL "2" support
![image](https://user-images.githubusercontent.com/6192686/120758481-312c4480-c512-11eb-8aed-25d3349bfc1e.png)

But I assume I might have already the required WSL update as part of Windows update (or Rancher Desktop installation)

**Comment by pgonin** [comment]
for reference I am using this documentation for installing WSL
https://docs.microsoft.com/en-us/windows/wsl/install-win10

apparently my issue is "RTFM"
```
Installation failed with error 0x80070003 or error 0x80370102
Please make sure that virtualization is enabled inside of your computer's BIOS. The instructions on how to do this will vary from computer to computer, and will most likely be under CPU related options.
```

**Comment by pgonin** [comment]
That was it... I had to enable 'SVM Mode' in BIOS

sorry for the noise...

**Comment by jandubois** [comment]
> sorry for the noise...

It is not noise; it is an issue other users could run into, and we should see if we can't detect this condition before even attempting to install WSL and provide a user-friendly error message instead.

I'm going to re-open, so we have a reminder to research this.

In general, any time you run into a problem and need to spend more than a couple of minutes to figure out what is wrong, please file a ticket, even if it eventually turns out to be user-error. Especially during initial installation we need to provide a great user experience so people don't give up before they can get it to work!
