### ISSUE TITLE
kubectl in Windows 10 not working properly with git-bash when inside VPN (Cisco AnyConnect Client)

### ISSUE THREAD

**Issue by cinnamon-coder-hub** [rancher-sandbox/rancher-desktop#3240]
### Actual Behavior

While being connected to a VPN the command `kubectl get pods`doesn't work when executed in git-bash.
The used OS is Windows 10. 

### Steps to Reproduce

1. Start Rancher Desktop and wait until its loading bar inside the GUI disappears.
2. Connect to VPN via Cisco AnyConnect Mobility Client.
3. Start a git-bash shell and execute the command `kubectl get pods`.

### Result

The Error message: 

_Unable to connect to the server: dial tcp 172.23.211.247:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond._

### Expected Behavior

As a result of the command `kubectl get pods` a list of pods should appear. 

### Additional Information

As a workaround I currently use the wsl command and the wsl distribution ubuntu20.04 to execute the command `kubectl get pods` from inside git-bash when connected to the VPN. Still, it would be quite nice to be able to run the command directly from within git-bash, as in the case of no VPN connection. 

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

1.23.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Windows User Only

Cisco AnyConnect is used for establishing the connection to the VPN.

**Comment by Nino-K** [comment]
@cinnamon-coder-hub thanks for reporting this issue. Are you able to try out [this](https://github.com/rancher-sandbox/rancher-desktop/issues/3091#issuecomment-1268931636) workaround? it will allow us to understand if your issue is related to the routing or not.

**Comment by cinnamon-coder-hub** [comment]
@Nino-K thanks for your fast response. Last week I also tried your workaround. It allowed me to ping the domain from within git-bash, but the command `kubectl get pods` still only works either without connection to the VPN or with the wsl workaround. 
Now I owe you the Route Table information. For both interfaces "vEthernet (WSL)" and "Ethernet 2" I get the following output: 

```
IPv4 Route Table
===========================================================================
Active Routes:
  None
Persistent Routes:
  None

IPv6 Route Table
===========================================================================
Active Routes:
  None
Persistent Routes:
  None
```
.
I'm rather new to network technology, but I guess that that the routing tables for those two interfaces shouldn't be completely empty.

**Comment by Nino-K** [comment]
@cinnamon-coder-hub that looks like a windows glitch, I think disconnecting from the network or even a restart would show the routes.

**Comment by cinnamon-coder-hub** [comment]
Thanks for your response.

It turned out that I just addressed the interfaces the wrong way, as I needed to use their IP4 addresses instead of their IP6 addresses. 
Now there is an active route to the interface itself in both cases.

For the interface "vEthernet (WSL)":

```
PS C:\WINDOWS\system32> route print 172.22.80.1

Interface List
 70...00 15 5d 9c 28 c9 ......Hyper-V Virtual Ethernet Adapter #2
  4...8c 16 45 29 8a 05 ......Intel(R) Ethernet Connection I219-LM
  3...0a 00 27 00 00 03 ......VirtualBox Host-Only Ethernet Adapter
 12...a0 d3 7a c7 a9 c1 ......Microsoft Wi-Fi Direct Virtual Adapter
 25...a2 d3 7a c7 a9 c0 ......Microsoft Wi-Fi Direct Virtual Adapter #2
 23...a0 d3 7a c7 a9 c0 ......Intel(R) Dual Band Wireless-AC 8260
  1...........................Software Loopback Interface 1
 27...00 15 5d ad bd 9e ......Hyper-V Virtual Ethernet Adapter


IPv4 Route Table

Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
      172.22.80.1  255.255.255.255         On-link       172.22.80.1    257

Persistent Routes:
  None

IPv6 Route Table

Active Routes:
  None
Persistent Routes:
  None

```
For the interface "Ethernet 2":
```
`PS C:\WINDOWS\system32> route print 10.42.21.167

Interface List
 18...00 05 9a 3c 7a 00 ......Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
 70...00 15 5d 9c 28 c9 ......Hyper-V Virtual Ethernet Adapter #2
  4...8c 16 45 29 8a 05 ......Intel(R) Ethernet Connection I219-LM
  3...0a 00 27 00 00 03 ......VirtualBox Host-Only Ethernet Adapter
 12...a0 d3 7a c7 a9 c1 ......Microsoft Wi-Fi Direct Virtual Adapter
 25...a2 d3 7a c7 a9 c0 ......Microsoft Wi-Fi Direct Virtual Adapter #2
 23...a0 d3 7a c7 a9 c0 ......Intel(R) Dual Band Wireless-AC 8260
  1...........................Software Loopback Interface 1
 27...00 15 5d ad bd 9e ......Hyper-V Virtual Ethernet Adapter


IPv4 Route Table

Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
     10.42.21.167  255.255.255.255         On-link      10.42.21.167    257

Persistent Routes:
  None

IPv6 Route Table

Active Routes:
  None
Persistent Routes:
  None
  
```
I'll be happy to try out something further or to give more information.

**Comment by Nino-K** [comment]
@cinnamon-coder-hub I'm going to close this issue, if you have any further questions feel free to either re-open this issue or continue your discussion [here](https://github.com/rancher-sandbox/rancher-desktop/issues/3091#issuecomment-1268931636). Thanks
