### ISSUE TITLE
Add preferences for auto-start and window-closing behaviour [5d]

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3262]
We want to have a 3 Preference settings to control application behaviour:

* Automatically start app at login
* App starts in the background without a window
* Closing the app window terminates the app

Using "File | Exit" (Linux, Windows) or "Rancher Desktop | Quit Rancher Desktop" (macOS) or the corresponding tray menu entry will always terminate the app.

Running the app in the background means there is no app window, no entry in the dock or task bar, just a tray icon (where available).

The app window can be opened either via the tray icon, or by starting the app again, in which case it will just open a window for the already running instance.

The configuration could go on the "Application | Behavior"  preference tab.

### Property names

All settings are boolean:

```
application.autoStart
application.startInBackground
application.window.quitOnClose
application.hideNotificationIcon
```

(Note that this introduces a sub-struc to allow future expansion.)

See #3770 if we need the last setting.

# Acceptance Criteria
- After fresh install/factory reset, check if all checkboxes are unselected - set to false. Check if all new properties are included in the settings.json file and set to false.
- Check all properties , click Apply, then verify if all checked settings are set to true in settings.json
- Check if the checkboxes are located under Preferences > Application > Behaviour

**Comment by gaktive** [comment]
@kwwii to update this ticket with the UX flow

**Comment by kwwii** [comment]
Here's my take on the options:

[  ] Automatically start Rancher Desktop at login
        [  ] Start Rancher Desktop in the background

[  ] Keep Rancher Desktop open when closing application window

**Comment by jandubois** [comment]
> ```
> [  ] Keep Rancher Desktop open when closing application window
> ```

Suggestion:

```
 [  ] Keep Rancher Desktop running in the background when closing application window
```

Reasons:

* The word `open` makes no sense when the app doesn't have a window. It is `active` or `running`, but not `open`.
* Re-using the `background` term links it with the second option: it is the same operating mode as if you would have started it `in the background`.

**Comment by torchiaf** [comment]
Below a possible implementation of the UI, what do you think? I think the last 2 options should grouped together:

![image](https://user-images.githubusercontent.com/26394656/211858234-96edb154-b88e-4e02-b4f4-94aecbe54976.png)

**Comment by gaktive** [comment]
Looks good.

Suggestion that arose: moving Startup & Background to the top (above Administrative Access).

**Comment by jandubois** [comment]
I wonder if we should have a hover-tip for "Start RD in the background" that explains how to open the app window (either via the tray icon, or by running the app again while the background service is already running)

**Comment by adamkpickering** [comment]
```
[  ] Start Rancher Desktop in the background
[  ] Keep Rancher Desktop running in the background when closing application window
```

Suggestion:

```
[  ] Start Rancher Desktop without opening application window
[  ] Keep Rancher Desktop running when application window is closed
```

Reasons:

- The term "background" has other meanings. One that comes to mind is "backgrounding" a shell process on Unix systems.
- The "application window" terminology describes what is happening. It is clear to both novices and advanced users.

Another option is to have both the "background" and "application window" terminology, like this:

```
[  ] Start Rancher Desktop in the background without opening application window
[  ] Keep Rancher Desktop running in the background when application window is closed
```

But I think that's needlessly verbose.

**Comment by rak-phillip** [comment]
Perhaps, instead of `background` we can use `System Tray`?

```
[ ] Start Rancher Desktop in the System Tray
[ ] Keep Rancher Desktop running in the System Tray when the window is closed
```

Rancher Desktop technically isn't "running" in the system tray, but this wording can provide context to how we expect to interact with Rancher Desktop while the main window isn't open.

**Comment by gunamata** [comment]
Based on what I have seen with some desktop applications, another design to consider. (Please excuse the text font in the image, I quickly painted something in paint brush)

![image](https://user-images.githubusercontent.com/59538726/212435750-d3184c0e-76e5-40ec-bbb5-c6a0fda3c846.png)

**Comment by jandubois** [comment]
Thanks for all your feedback @adamkpickering ; I've added it all to the agenda for the Wednesday UI/UX sync meeting.

> Perhaps, instead of `background` we can use `System Tray`?

I'm not a fan of that; it feels just wrong to me. Also it would have to be called "notification area" (on Linux and Windows), or "menu bar" (on macOS), to use the correct terminology.

One issue I have with the "without opening the application window" is that we will also run the app without the Task Bar or Dock entry, without an entry in the Application switcher (Alt-⇥), and without an application menu (on macOS).

I'm slowing going back to preferring "in the background". 😄

**Comment by gunamata** [comment]
I synced up with @jandubois to understand the auto-start, backgrounding, window-closing behavior that we are planning to implement. I had a different understanding earlier that prompted my suggestion above. So, please ignore my suggested design above.

**Comment by torchiaf** [comment]
@jandubois I would change the name of the last 2 settings:
```
  autoStart:         false,
  startInBackground: false,
  keepRunning:       false,
  hideTrayIcon:      false,
```

`keepRunning` seems to me more simpler and descriptive and `hideTrayIcon` is much more similar to the Electron APIs and other variable names in the app.
Also, I think we can use the term 'Tray' in place of 'Notification Area' or similar, in the preferences window; the `Tray` term is used for all the 3 platforms to indicate the menu with icons of the running applications.


![image](https://user-images.githubusercontent.com/26394656/212950925-807c41e5-d46c-4a2c-83b8-b71dc5c31fd1.png)

IMO it would be great if we find a way to remove the scrollbar, like grouping the checkboxes to save space or creating a new tab.

**Comment by jandubois** [comment]
> `keepRunning` seems to me more simpler and descriptive and `hideTrayIcon` is much more similar to the Electron APIs and other variable names in the app.

I disagree, `keepRunning` is not descriptive to me at all because it doesn't mention under which condition the app is supposed to "keep running".

I think `windowCloseQuitsApp` is much more descriptive, as it tells you precisely what it does. I agree though that it feels long and clunky, so other suggestions are welcome, but `keepRunning` doesn't work for me.

> and `hideTrayIcon` is much more similar to the Electron APIs and other variable names in the app.

I don't care about the Electron API or our internal variable names here; with out latest changes these names are exposed to the user:

```
rdctl set --application.hide-notification-icon=true
```

If anything, I would change our internal names to match what we call something externally (like how we change `image-allow-list` to `allowed-images`).

> Also, I think we can use the term 'Tray' in place of 'Notification Area' or similar, in the preferences window; the `Tray` term is used for all the 3 platforms to indicate the menu with icons of the running applications.

The term Tray is an anachronism, like the floppy disk icon to mean "Save". There never has been a Tray on OS X / macOS, and it hasn't been called the Tray on Windows in a long time.

I think "notification area" and "notification icon" are terms that we could use for all 3 platforms, even though it is not quite correct for macOS.

**Comment by jandubois** [comment]
> IMO it would be great if we find a way to remove the `scrollbar`, like grouping the checkboxes to save space or creating a new tab.

I would suggest to rename the old tab to "General" and create a new "Behavior" tab for just the 4 new options from this epic.

I'm also in favour of grouping more options together under a single heading. I don't think the headings provide much value, especially if you have a separate heading for each option.

These headings also take up a lot of vertical space, so we really have low "density" in our settings tabs. I wonder if we could lay out labels in a separate column, so save some space (on pages that just have check boxes and dropdown lists). See e.g. (arbitrarily) from Safari:

<img width="880" alt="Screen Shot 2023-01-17 at 11 37 42 AM" src="https://user-images.githubusercontent.com/78947/212995992-d7482624-86a4-4cad-ad36-b8dc9a564c9c.png">

**Comment by torchiaf** [comment]
Thanks @jandubois , I made a few changes considering your suggestions.


- New tab `General` created
- Changed some names
- Added a tooltip for `Background` section

Removing the checkbox headers and adding a a new column like Safari make sense to me, only if our window also had the tab selector on the top, and only a one-level selector.
In current layout, I think there is no space on the left to have a separate column with the checkbox headers so we should think about a complete layout refactoring first.

![image](https://user-images.githubusercontent.com/26394656/213220382-57d3d464-d1b8-45a3-879c-f8cb64f030c2.png)

![image](https://user-images.githubusercontent.com/26394656/213221025-bbcea645-7bd9-494c-8e24-ac09daebeea1.png)

**Comment by ericpromislow** [comment]
Looks fine. Just noting that I don't see any problem merging this into the new v5 work.

**Comment by rak-phillip** [comment]
My understanding is that the `v5` schema would need to reorganize these root-level settings under `application`. So, we would require some refactoring correct?

``` diff
{
  "version": 5,
- "autoStart": false,
- "startInBackground": false,
- "hideNotificationIcon": false,
- "window": { "quitOnClose": false },
  "application": {
+   "autoStart": false,
+   "startInBackground": false,
+   "hideNotificationIcon": false,
+   "window": { "quitOnClose": false },
    "adminAccess": false,
    "telemetry": {
      "enabled": true
    },
    "updater": {
      "enabled": true
    },
    "path": {
      "managementStrategy": "rcfiles"
    }
    "debug": false
  },
```  

@ericpromislow

**Comment by ericpromislow** [comment]
Yes, but it's possible that git will manage to pull this in automatically.

if there are rdctl tests that verify the setting was changed, we'll get test failures as well.
