### ISSUE TITLE
Make it possible to configure system to run Rancher Desktop on startup from within Rancher Desktop UI

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3263]
This came from a discussion around #3144.

**Comment by rak-phillip** [comment]
Closing. This looks to be resolved in #3789

Related Issues:

- https://github.com/rancher-sandbox/rancher-desktop/issues/3769
- https://github.com/rancher-sandbox/rancher-desktop/issues/3771
- https://github.com/rancher-sandbox/rancher-desktop/issues/3772

@jandubois
