### ISSUE TITLE
Improve Kubernetes Error Page

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#3278]
### Problem Description

On the bottom of the error page there is the sentence: "Some recent logfile lines:":

![Screenshot_2022-10-25_08-39-242](https://user-images.githubusercontent.com/8761082/197802468-8f0d1136-731d-44c4-919b-e572840657f9.png)

It would be nice, if the word "logfile" is a link to the logfile directory. If the user clicks the link, the directory opens.

### Proposed Solution

Adapt the word "logfile" to be a link to the logfile directory of the system.

**Comment by gaktive** [comment]
We have a way of accessing that already on the troubleshooting page ("Show Logs") so we can simply use that. We could either do a hyperlink or invoke the OS file manager.
