### ISSUE TITLE
Extend timeout for online diagnostic

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3283]
The code to check if the host is online tries to fetch `http://example.com` with a 2 second timeout. Several people on Slack have reported that this diagnostic shows up incorrectly, most likely because the timeout is too low.

I would suggest increasing the timeout to 5s and also adding an environment variable like `RD_ONLINE_CHECK_TIMEOUT` to allow overriding the default.

**Comment by jsoref** [comment]
I'd suggest it also log something -- whether the timeout fired, or whatever exception it hit.

**Comment by jandubois** [comment]
> I'd suggest it also log something -- whether the timeout fired, or whatever exception it hit.

Absolutely. We already create `diagnostics.log`, at least failing diagnostics should write to it.
