### ISSUE TITLE
Update notification and automation

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#329]
On both mac and windows, users should get a notification when a new version is available and have the opportunity to upgrade.

The upgrade notification box should provide a means to immediately upgrade, silence the notification for now (it can come up again later), or skip updating to the version notified about. If they silence the notification or skip updating to that version a menu item should let them update on their own if they so desire.

**Comment by mattfarina** [comment]
From Jan, let's supply the release notes when we show a notification of an update.

**Comment by mook-as** [comment]
It looks like electron-builder has some [built-in autoupdater](https://www.electron.build/auto-update), which is supposed to be driven from GitHub releases (that is, it wants extra files in releases, `latest.yml` for Windows and `latest-mac.yml` for macOS).  However, it looks like the _generation_ of those files are tied to the integrated publishing support.

Separately, Electron has built-in auto-update, but that's proxied through https://update.electronjs.org.

So, the options I see are (in no particular order):
- Use electron-builder's integration for publishing. 
  This may run into issues if we want to _not_ rebuild the binaries (just the installer) offline.
- Use electron-builder's updater, but generate the update files ourselves.
- Use electron's updater, using their server.
- Use electron's updater, using our own server. (I don't see any value here.)
- Do something else.

I'm leaning towards option 2 currently, but that kind of depends on the release flow — @mattfarina would you be able to describe what we're currently doing, and possibly what we _want_ to be doing, if that's different? If that's going to be long, maybe do it as a [discussion](https://github.com/rancher-sandbox/rancher-desktop/discussions)?  The constraints I'm aware of are:
- Definitely only doing the signing offline (not on public CI systems); among other things, the certificate is on a physical device.
- We need to sign Windows & macOS releases (possibly on their native platforms).

My understanding of the desired things are:
- get CI to build something, and then sign that (/ generate the installer) offline.
- This is triggered on tags.

**Comment by mook-as** [comment]
Current thinking:
- Mostly use electron-builder's [electron-updater](https://www.electron.build/auto-update) client.
- Implement a custom [Provider](https://github.com/electron-userland/electron-builder/blob/v29.30.0/packages/electron-updater/src/providers/Provider.ts#L7) that talks to longhorn's [upgrade-responder](https://github.com/longhorn/upgrade-responder).
- Hopefully get help from the longhorn folks to deploy the server.
- Write a small app running on Kubernetes alongside upgrade-responder to scrape GitHub releases to generate the configmap required.  We can run it once an hour or something and stay well under the GitHub rate limits.
- The client side, upon seeing an update, will need to fetch the release notes from GitHub.
- Using electron-updater means we get download verification (signature checking).  It seems to do some sort of delta download stuff too; not quite sure how that works (and I think it might be based on the installer, which holds a 7z archive, so I'm not sure how well it works…)

**Comment by mook-as** [comment]
Closing this one, and spawning the work related to having a responder server in #404 instead.
