### ISSUE TITLE
Update cri-dockerd version packaged with Rancher Desktop

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3293]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/3279

<div type='discussions-op-text'>

<sup>Originally posted by **fposch** October 25, 2022</sup>
Hi, 

I know it is not strictly Rancher-related and the problem apparently lies in _dockerd(moby)_ (as one of the two container engines) but I'm also getting this when trying to deploy my kubernetes cluster through Rancher Desktop 

In events, I'm getting lots of these (image name obfuscated)

`Failed to pull image "xxxxxx.dkr.ecr.eu-west-1.amazonaws.com/application-image:210630": rpc error: code = Unknown desc = context deadline exceeded `

(I'm using Kubernetes v1.22.12 if that matters).

It seems to be an issue with dockerd/moby where pulling an image (for a pod/container) is aborted after 1 minute, so depending on your connection speed and image sizes you may never get a pod to start unless you pull the image manually so that it is already in cache while deploying.

Somebody has provided a [fix](https://github.com/Mirantis/cri-dockerd/commit/460da8ef84e7d2781ee275907543764b6a77c5ff) for the engine (or presumably the runtime interface/CRI) in version 0.26.0 but it would require an upgrade in Rancher packages make use of that (I tried 1.6.1 and still having the same problem).

I hope that makes sense.

BR,
Florian
</div>

Bumping the packaged version of cri-dockerd to [0.2.6](https://github.com/Mirantis/cri-dockerd/releases) should fix this.

**Comment by jandubois** [comment]
Fixed by #3366 (macOS, Linux) and #3368 (Windows).
