### ISSUE TITLE
nerdctl cp command in MacOS always fail to find GNU tar

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3294]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/3291

<div type='discussions-op-text'>

<sup>Originally posted by **GodDrinkTeJAVA** October 27, 2022</sup>
I'm using MacOS on Apple Silicon and nerdctl cp command always tells me that /bin/tar as GNU tar is not found. The message is written as below.
```WARN[0000] "/bin/tar" does not seem GNU tar```
The problem is, it seems to be in /usr/bin/tar.
Would this be the problem with nerdctl or the virtual machine? If it is the problem from virtual machine, could you tell me if there is any way to fix this? </div>

Looks like we only have busybox `tar` installed in the lima VM, not GNU `tar`. This is a requirement of `nerdctl cp`; see https://github.com/containerd/nerdctl/blob/81a2217dc97dc1cf7473c8659968d35833a4542b/pkg/tarutil/tarutil.go#L37.

**Comment by jandubois** [comment]
> Looks like we only have busybox `tar` installed in the lima VM

I suspect this will be the same in our WSL2 distro, so I have removed the `lima` label.

**Comment by jandubois** [comment]
Fixed by #3366 (macOS, Linux) and #3368 (Windows).
