### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? MacOS

### ISSUE THREAD

**Issue by JulianCabreraS** [rancher-sandbox/rancher-desktop#3296]
### Actual Behavior

I installed Rancher Desktop after uninstalling Docker Desktop. I am not able to Docker Pull and I have errors in the installation. 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/16109083/198453652-e02cc2ca-0313-4faa-b72e-66243d667e00.png">

In the diagnostic section, I see this error: 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/16109083/198453919-3a1ea922-4c5b-4e4c-847e-5fda6c2ebcac.png">

### Steps to Reproduce

* Uninstall Docker Desktop
* Install Docker Ranch using homebrew brew install --cask rancher

### Result

Errors in the installation 

*Unable to Docker pull, terminal gets stuck 
* Kubernetes is using context docker-desktop instead of rancher-desktop.
* Sometime drops this error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? MacOS

### Expected Behavior

Able to Docker Pull 

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

1.25.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS 13

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by adamkpickering** [comment]
Hi @JulianCabreraS, thanks for filing an issue. Can you please confirm the following things:

- You are using the "moby" container engine (go to Preferences > Container Engine and ensure that dockerd (moby) is checked).
- You have configured Rancher Desktop to use the `rancher-desktop` kubectl context. This can be done by clicking on the Rancher Desktop icon in the tray and clicking Kubernetes Contexts > rancher-desktop.
- You have configured Rancher Desktop to use the `rancher-desktop` docker context. This can be done by running `docker context use rancher-desktop`.
- Rancher Desktop starts up correctly.

If you've done all of those things, then I suspect an issue due to running macOS Ventura. Did this problem start after upgrading to Ventura? Does the problem described in #3288 sound familiar?

**Comment by jandubois** [comment]
I'm going to close this as a duplicate of #3288; Kubernetes 1.24.* and 1.25.* simply do not work on Ventura. Downgrading to 1.23.13 might be a workaround until this is fixed.

Simple test to see if this is a duplicate: Does `rdctl shell` work for you? If it just hangs (and I'm 99% sure this will be the case for you), then this is a duplicate of #3288.

**Comment by Kccarr6022** [comment]
context "rancher-desktop": context not found: open /home/system/.docker/contexts/meta/b547d66a5de60e5f0843aba28283a8875c2ad72e99ba076060ef9ec7c09917c8/meta.json: no such file or directory

**Comment by imechemi** [comment]
<img width="764" alt="Screenshot 2024-03-11 at 09 59 56" src="https://github.com/rancher-sandbox/rancher-desktop/assets/3127583/2ce59ffd-936d-4c5a-88e4-c54158839fd0">


I have re-installed and by default my Kubernetes Context is 'loaded-context'.

**Comment by kshitijk20** [comment]
context "rancher-desktop": context not found: open C:\Users\kkai\.docker\contexts\meta\b547d66a5de60e5f0843aba28283a8875c2ad72e99ba076060ef9ec7c09917c8\meta.json: The system cannot find the path specified.

**Comment by rasika** [comment]
We faced the same issue. The only resolution was to uninstall the latest Rancher 1.15.1 and install Rancher 1.14.2. Then restarted the Mac and it worked. Even after autoupdate to 1.15.1 is fine now.

**Comment by RickardCardell** [comment]
Same issue, but hadn't allowed rancher-desktop to use root. I.e had to enable "Administrative Access" under Preferences/Application/General. 
After I'd done that, the symlink was created:
`> ls -al /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  31 13 Dec 11:11 /var/run/docker.sock -> /Users/waldo/.rd/docker.sock`

**Comment by SteveMeckstroth** [comment]
For anyone else ending up here.

rm -rf (whatever path it gives you in the error message)

Try again, if you get an error for a different path
rm -rf (whatever the new path is)

Once you finally get a "command not found" then open rancher, go to troublehsooting, and factory reset it.

**Comment by auroramariatumminello** [comment]
> For anyone else ending up here.
> 
> rm -rf (whatever path it gives you in the error message)
> 
> Try again, if you get an error for a different path rm -rf (whatever the new path is)
> 
> Once you finally get a "command not found" then open rancher, go to troublehsooting, and factory reset it.

Thank you! I've just spent two days trying to correctly setup Rancher, this was the way to go after an incredible amount of commands 😭😭😭
