### ISSUE TITLE
Document Windows user workflows

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#331]
This issue is to write up a series of Windows user workflows (e.g., using RD with PowerShell and a workflow using a Linux distro). This can be written up in the discussions or wiki.

/cc @agracey

**Comment by agracey** [comment]
https://github.com/rancher-sandbox/rancher-desktop/discussions/342

**Comment by agracey** [comment]
Started a discussion about this

**Comment by jtravee** [comment]
Please provide additional details for Windows user workflows.

**Comment by gunamata** [comment]
The current docs have a bunch of tutorial/guide pages describing steps in a typical dev workflow. For example, [Working with Images](https://docs.rancherdesktop.io/tutorials/working-with-images), [Working with Containers](https://docs.rancherdesktop.io/tutorials/working-with-containers), [Helloworld doc](https://docs.rancherdesktop.io/how-to-guides/hello-world-example) etc

@mattfarina , @agracey , I am closing this. Please feel free to reopen if you feel the current docs do not cover what you wanted to.
