### ISSUE TITLE
Add a help button to each page/tab of the Preferences

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3322]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/3273

<div type='discussions-op-text'>

<sup>Originally posted by **jandubois** October 24, 2022</sup>
We want to add a direct link from each Preference page to their documentation. It should be similar to how this is done in macOS System Preferences:

<img width="780" alt="Screen Shot 2022-10-24 at 3 30 36 PM" src="https://user-images.githubusercontent.com/78947/197643895-2c9d47d1-533f-419d-854e-af59a743d53c.png">

Every settings page has a help icon (an inverted question mark inside a filled circle) that directly opens the corresponding help page.

In macOS the icon location jumps around between the lower right and lower left corners. I'm not sure if there is a system behind it; so far it looks it is on the right on the main page, and on the left if this is inside another dialog on top of the page. Some information is in the Apple developer documentation for [help buttons](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/buttons/#help-buttons).

Longer term we want to have this icon everywhere, so also on main app window pages, and maybe even in dialogs:

<img width="568" alt="Screen Shot 2022-10-24 at 11 44 48 AM" src="https://user-images.githubusercontent.com/78947/197644330-edb9d96b-f589-4f0c-9adc-244286109634.png">

This help icon should also be used to link to help topics from diagnostics (instead of the "link to external site" icon we currently use.</div>

**Comment by torchiaf** [comment]
Feature in progress, branch: https://github.com/torchiaf/rancher-desktop/tree/feature/help-buttons

**Comment by torchiaf** [comment]
Example screenshots folder:
[screenshots.tar.gz](https://github.com/rancher-sandbox/rancher-desktop/files/10014908/screenshots.tar.gz)

**Comment by jandubois** [comment]
The screen shots are missing the window title and borders. Maybe this needs an OS-specific solution for each platform.

I've been able to do a full window capture on macOS with:

```console
screencapture -l $(GetWindowID  "Rancher Desktop" "Rancher Desktop - Preferences") prefs.png
```

`screencapture` is bundled with macOS, and `GetWindowID` is from https://github.com/smokris/GetWindowID.

<img width="836" alt="prefs" src="https://user-images.githubusercontent.com/78947/202002471-afe8cf31-1d62-4dce-9bbb-a64175299361.png">

Rancher Desktop needs to be activated before taking the screen shot, so the window controls and title bar are not greyed out/dimmed.
