### ISSUE TITLE
Rancher Desktop installation on Windows not persisting between device restarts

### ISSUE THREAD

**Issue by chr-hen** [rancher-sandbox/rancher-desktop#3332]
### Actual Behavior

Since upgrading to Rancher Desktop 1.6.1, I have an issue where I need to run `Rancher.Desktop.Setup.1.6.1.exe` each time I start my Windows machine. The installation does not persist between sessions and I need to run through the installation wizard each time I would like to run Rancher Desktop.

### Steps to Reproduce

1. Install Rancher Desktop 1.6.1 on Windows 10 Pro, build `19044.2130`
2. Restart your Windows machine
3. Attempt to launch Rancher Desktop

### Result

After restarting the Windows machine, Rancher Desktop will not be launchable and you will need to run `Rancher.Desktop.Setup.1.6.1.exe` to reinstall the software. 

### Expected Behavior

The Rancher Desktop installation should persist between device restarts and be ready to use.

### Additional Information

Factory Reset in Rancher Desktop troubleshooting section does not resolve this issue. I've also noticed that since upgrading to 1.6.1, the installation flow appears to have changed and I now receive prompts from PowerShell.

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

v1.24.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro, build 19044.2130

### What CPU architecture are you using?

x64

**Comment by MrHPotter** [comment]
i am using Rancher-Desktop 1.6.1 and i do not have this Problem. Might be something with your operating System/ Device Setup.

**Comment by chr-hen** [comment]
Thanks for the replies.

I can confirm that `:\Users\<you>\AppData\Local\Programs\Rancher Desktop` persists between sessions, yes. My issue is that Rancher Desktop disappears from my list of programs between restarts.

Given the responses, this does indeed seem to most likely be an issue on my side.
