### ISSUE TITLE
Check for updates automatically not work

### ISSUE THREAD

**Issue by sanxete091** [rancher-sandbox/rancher-desktop#3347]
### Actual Behavior

Hello,

I currently have version 1.6.0 installed. I see that there is a version 1.6.2 but even with the Check for updates automatically not work option checked, the application does not find the update. What can be happening?

### Steps to Reproduce

After opening the application, it does not tell me that there are updates:
![image](https://user-images.githubusercontent.com/36997964/200121669-aa5b25c8-3531-4ae5-924f-e49b4c4fb691.png)

### Result

![image](https://user-images.githubusercontent.com/36997964/200121673-366dae2a-34de-414b-b51c-372df7f6d158.png)

### Expected Behavior

The behavior that I expect is that the application itself tells me that there are updates and gives me the option to download it from the application itself.

### Additional Information

I have MacOsX operating system in version 12.6. Chip Intel
![image](https://user-images.githubusercontent.com/36997964/200121744-90548552-0450-406b-8898-e34e874d4e1e.png)

### Rancher Desktop Version

1.6.0

### Rancher Desktop K8s Version

v1.23.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOs Monterey version 12.6

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
Are you behind a proxy or on a VPN? Maybe the server sending the update information is unreachable? Can you try to run this from the commandline:

```console
$ curl -d '{"appVersion":"1.6.0"}' -X POST https://desktop.version.rancher.io/v1/checkupgrade
{"versions":[{"Name":"v1.2.1","ReleaseDate":"2022-04-24T11:00:00Z","Tags":["v1.2.1"]},{"Name":"v1.2.0","ReleaseDate":"2022-04-23T11:00:00Z","Tags":["v1.2.0"]},{"Name":"v1.1.1","ReleaseDate":"2022-03-04T22:00:00Z","Tags":["v1.1.1"]},{"Name":"v0.7.1","ReleaseDate":"2021-12-20T14:30:00Z","Tags":["v0.7.1"]},{"Name":"v0.6.0","ReleaseDate":"2021-10-15T12:30:00Z","Tags":["v0.6.0"]},{"Name":"v1.6.1","ReleaseDate":"2022-10-24T13:00:00Z","Tags":["v1.6.1"]},{"Name":"v1.6.0","ReleaseDate":"2022-10-06T11:00:00Z","Tags":["v1.6.0"]},{"Name":"v1.5.1","ReleaseDate":"2022-08-11T11:00:00Z","Tags":["v1.5.1"]},{"Name":"v1.0.1","ReleaseDate":"2022-02-02T22:00:00Z","Tags":["v1.0.1"]},{"Name":"v1.0.0","ReleaseDate":"2022-01-26T18:00:00Z","Tags":["v1.0.0"]},{"Name":"v0.7.0","ReleaseDate":"2021-12-16T14:30:00Z","Tags":["v0.7.0"]},{"Name":"v1.6.2","ReleaseDate":"2022-11-03T16:00:00Z","Tags":["v1.6.2","latest"]},{"Name":"v1.5.0","ReleaseDate":"2022-07-28T11:00:00Z","Tags":["v1.5.0"]},{"Name":"v0.6.1","ReleaseDate":"2021-11-02T12:30:00Z","Tags":["v0.6.1"]},{"Name":"v1.4.1","ReleaseDate":"2022-06-08T11:00:00Z","Tags":["v1.4.1"]},{"Name":"v1.3.0","ReleaseDate":"2022-04-28T11:00:00Z","Tags":["v1.3.0"]},{"Name":"v1.1.0","ReleaseDate":"2022-03-02T22:00:00Z","Tags":["v1.1.0"]},{"Name":"v0.5.0","ReleaseDate":"2021-09-27T12:30:00Z","Tags":["v0.5.0"]},{"Name":"v0.4.1","ReleaseDate":"2020-05-18T12:30:00Z","Tags":["v0.4.1"]}]}
```

If this works, check the file attributes:

```console
$ ls -l ~/Library/Caches/rancher-desktop/updater-longhorn.json
-rw-------  1 jan  staff  1561  4 Nov 15:07 /Users/jan/Library/Caches/rancher-desktop/updater-longhorn.json
```

If this file is not owned by the current user, then maybe you once tried to run Rancher Desktop as `root`, which can break future auto-updates. Deleting the whole updater tree might unbreak things:

```console
$ sudo rm -rf ~/Library/Caches/rancher-desktop
```

Or check the contents of the `updater-longhorn.json` file; it should look like this (after reformatting it with `jq`):

```json
{
  "nextUpdateTime": 1667603223228,
  "isInstallable": false,
  "release": {
    "tag": "v1.6.2",
    "name": "Rancher Desktop 1.6.2",
    "notes": "This is the 1.6.2 release of Rancher Desktop, an open source desktop application to bring Kubernetes and container management to Mac, Windows, and Linux.\r\n\r\n## This patch release fixes an incompatibility with macOS Ventura\r\n\r\nRancher Desktop 1.6.0 and 1.6.1 do not work properly with macOS 13 Ventura. When running Kubernetes versions 1.24.* or 1.25.*, the VM would hang right away before becoming ready. With earlier versions, Kubernetes would work initially, but start hanging after restarting Rancher Desktop. This issue has been fixed.\r\n\r\nThere are no other changes in this release compared to 1.6.1.\r\n\r\n## Connect with the developers\r\n\r\n- The [issue queue](https://github.com/rancher-sandbox/rancher-desktop/issues)\r\n\r\n- [Rancher Users Slack](https://slack.rancher.io/) in the #rancher-desktop channel\r\n\r\n## Changelog\r\n\r\nThe [full version changelog, from v1.6.1, can be found using GitHub compare](https://github.com/rancher-sandbox/rancher-desktop/compare/v1.6.1...v1.6.2) and the details of the release can be found in the [v1.6.2 milestone](https://github.com/rancher-sandbox/rancher-desktop/milestone/27?closed=1).\r\n",
    "date": "2022-11-03T23:12:38Z"
  },
  "file": {
    "url": "https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.6.2/Rancher.Desktop-1.6.2-mac.x86_64.zip",
    "size": 524474265,
    "checksum": "kKBXzUh+1UHErHBuVXfQHizHLYf0cW8Ub9FnMTcFOJBhZ7Q+v8W+WAI3UH1ilSg5N48AaKZ8PL5K+LXIzMhMHA=="
  }
}
```

**Comment by sanxete091** [comment]
Hi @jandubois,

When I tried to run:
> ls -l ~/Library/Caches/rancher-desktop/updater-longhorn.json

, it told me that the file did not exist. 
I have created it manually with the content that you have indicated:
> {
  "nextUpdateTime": 1667603223228,
  "isInstallable": false,
  "release": {
    "tag": "v1.6.2",
    "name": "Rancher Desktop 1.6.2",
    "notes": "This is the 1.6.2 release of Rancher Desktop, an open source desktop application to bring Kubernetes and container management to Mac, Windows, and Linux.\r\n\r\n## This patch release fixes an incompatibility with macOS Ventura\r\n\r\nRancher Desktop 1.6.0 and 1.6.1 do not work properly with macOS 13 Ventura. When running Kubernetes versions 1.24.* or 1.25.*, the VM would hang right away before becoming ready. With earlier versions, Kubernetes would work initially, but start hanging after restarting Rancher Desktop. This issue has been fixed.\r\n\r\nThere are no other changes in this release compared to 1.6.1.\r\n\r\n## Connect with the developers\r\n\r\n- The [issue queue](https://github.com/rancher-sandbox/rancher-desktop/issues)\r\n\r\n- [Rancher Users Slack](https://slack.rancher.io/) in the #rancher-desktop channel\r\n\r\n## Changelog\r\n\r\nThe [full version changelog, from v1.6.1, can be found using GitHub compare](https://github.com/rancher-sandbox/rancher-desktop/compare/v1.6.1...v1.6.2) and the details of the release can be found in the [v1.6.2 milestone](https://github.com/rancher-sandbox/rancher-desktop/milestone/27?closed=1).\r\n",
    "date": "2022-11-03T23:12:38Z"
  },
  "file": {
    "url": "https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.6.2/Rancher.Desktop-1.6.2-mac.x86_64.zip",
    "size": 524474265,
    "checksum": "kKBXzUh+1UHErHBuVXfQHizHLYf0cW8Ub9FnMTcFOJBhZ7Q+v8W+WAI3UH1ilSg5N48AaKZ8PL5K+LXIzMhMHA=="
  }
}
When you open the app again, it already detects the update:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/36997964/200181647-62496fd9-5e41-463a-867e-ab0be0762b4f.png">

Problem solved.
Thank you!!

**Comment by jandubois** [comment]
I think this will have "fixed" the problem only for this particular upgrade, but you won't get the next upgrade if Rancher Desktop can't download the version list. Can you run the `curl` command I gave above and post the results? I suspect something (proxy/vpn) is blocking your access to it.

**Comment by sanxete091** [comment]
Hi @jandubois,

The command curl works correctly:
```sh
david@MacBook-Pro-de-David ~ % curl -d '{"appVersion":"1.6.0"}' -X POST https://desktop.version.rancher.io/v1/checkupgrade
{"versions":[{"Name":"v1.0.1","ReleaseDate":"2022-02-02T22:00:00Z","Tags":["v1.0.1"]},{"Name":"v1.5.1","ReleaseDate":"2022-08-11T11:00:00Z","Tags":["v1.5.1"]},{"Name":"v1.5.0","ReleaseDate":"2022-07-28T11:00:00Z","Tags":["v1.5.0"]},{"Name":"v1.2.0","ReleaseDate":"2022-04-23T11:00:00Z","Tags":["v1.2.0"]},{"Name":"v1.0.0","ReleaseDate":"2022-01-26T18:00:00Z","Tags":["v1.0.0"]},{"Name":"v1.6.2","ReleaseDate":"2022-11-03T16:00:00Z","Tags":["v1.6.2","latest"]},{"Name":"v1.6.0","ReleaseDate":"2022-10-06T11:00:00Z","Tags":["v1.6.0"]},{"Name":"v1.4.1","ReleaseDate":"2022-06-08T11:00:00Z","Tags":["v1.4.1"]},{"Name":"v1.3.0","ReleaseDate":"2022-04-28T11:00:00Z","Tags":["v1.3.0"]},{"Name":"v1.2.1","ReleaseDate":"2022-04-24T11:00:00Z","Tags":["v1.2.1"]},{"Name":"v0.7.1","ReleaseDate":"2021-12-20T14:30:00Z","Tags":["v0.7.1"]},{"Name":"v0.7.0","ReleaseDate":"2021-12-16T14:30:00Z","Tags":["v0.7.0"]},{"Name":"v0.6.0","ReleaseDate":"2021-10-15T12:30:00Z","Tags":["v0.6.0"]},{"Name":"v1.6.1","ReleaseDate":"2022-10-24T13:00:00Z","Tags":["v1.6.1"]},{"Name":"v1.1.0","ReleaseDate":"2022-03-02T22:00:00Z","Tags":["v1.1.0"]},{"Name":"v0.6.1","ReleaseDate":"2021-11-02T12:30:00Z","Tags":["v0.6.1"]},{"Name":"v0.5.0","ReleaseDate":"2021-09-27T12:30:00Z","Tags":["v0.5.0"]},{"Name":"v0.4.1","ReleaseDate":"2020-05-18T12:30:00Z","Tags":["v0.4.1"]},{"Name":"v1.1.1","ReleaseDate":"2022-03-04T22:00:00Z","Tags":["v1.1.1"]}]}%     
```

**Comment by jandubois** [comment]
> The command curl works correctly:

Then I don't know why it didn't actually fetch the `longhorn-updater.json` file.

I guess there is nothing left to do, except to watch out when the next update is released, and check if it is installed automatically or not.
