### ISSUE TITLE
Docker command doesn't exist if you open the terminal from the right click menu in a folder

### ISSUE THREAD

**Issue by Luxvao** [rancher-sandbox/rancher-desktop#3354]
### Actual Behavior

When I right click I can select the "Open in Terminal" option:
![slika](https://user-images.githubusercontent.com/95533447/200339816-dafa66d3-0f5d-4cb4-a2e2-eb31b64fc15a.png)
and if I click on it and run docker, it returns:
![slika](https://user-images.githubusercontent.com/95533447/200340016-241cffb2-95fb-4b7b-adf4-80417fb4542e.png)
(I am running powershell 7 and oh my posh if it's important)

### Steps to Reproduce

1. Open any folder
2. Right click
3. "Open in Terminal"
4. Try to run docker

### Result

![slika](https://user-images.githubusercontent.com/95533447/200340284-aa9198c0-ce8a-4007-b7d8-6c110bd4504d.png)

### Expected Behavior

The docker command would run.

### Additional Information

If I navigate to the directory from powershell that was started in the normal way (running the terminal application)
![slika](https://user-images.githubusercontent.com/95533447/200341205-744814be-f00f-417b-9ade-de63f73cb57c.png)
I can access the docker command (when I start the terminal app it starts powershell 7 and oh my posh)

### Rancher Desktop Version

1.6.2

### Rancher Desktop K8s Version

1.24.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home  22000.1098

### What CPU architecture are you using?

x64

**Comment by gunamata** [comment]
@Luxvao , it could be because you have the explorer open before you installed Rancher Desktop. Do you see the problem in a new explorer window that you open as well?

**Comment by Luxvao** [comment]
@gunamata It seems to be that... I'm dumb I guess lol

**Comment by gunamata** [comment]
@Luxvao , We all overlook things at times. Glad it works for you.
