### ISSUE TITLE
kubectl compatibility issues

### ISSUE THREAD

**Issue by jonhutchens** [rancher-sandbox/rancher-desktop#3370]
### Actual Behavior

When connecting to an EKS 1.23.x cluster, the kubectl binary selected by kuberlr (I believe it is selecting 1.24.x, but cannot confirm as the kubectl version command fails due to error below) does not work, but gives the error:
```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

I checked what versions are available via `kuberlr bins` and then manually tested the binaries for 1.22, 1.23, 1.24, and 1.25. The kubernetes skew policy is +-1 minor revision. Results:
* \<kubectl minor version> - success/failure in connecting to an EKS 1.23.x cluster 
* 1.22.x - success
* 1.23.x - success
* 1.24.x - failure (this is the problem - why doesn't this one work?)
* 1.25.x - failure (expected, as +2 minor revisions)

If this is an EKS issue, perhaps an improvement on the kuberlr side would be to expose a setting in rancher desktop allowing the user to configure kuberlr to match version exactly instead of using the latest assumed compatible version?

### Steps to Reproduce

I haven't specifically seen (or tested) this in other environments, but I am having this issue with a target cluster running EKS 1.23.x.

Execute the following:
```
export KUBECONFIG=<eks1.23cluster-config>
kubectl version --short
<fails>
```

### Result

No kubectl commands work

```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

### Expected Behavior

Normal kubectl operation

### Additional Information

More discussion in slack thread:
https://rancher-users.slack.com/archives/C0200L1N1MM/p1668007623874269

### Rancher Desktop Version

1.6.2

### Rancher Desktop K8s Version

1.23.12

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.6

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
> If this is an EKS issue, perhaps an improvement on the kuberlr side would be to expose a setting in rancher desktop allowing the user to configure kuberlr to match version exactly instead of using the latest assumed compatible version?

I believe this is an EKS issue, as the version skew promise for kubectl doesn't seem to hold. If you ever get an answer from AWS about this, please let us know here as well!

Beyond that, I agree that having an (optional) stricter version matching policy for kuberlr seems like a good idea. It would have to be implemented upstream though before it can be exposed by Rancher Desktop.

**Comment by jonhutchens** [comment]
Created an issue against `kuberlr` https://github.com/flavio/kuberlr/issues/30

**Comment by gunamata** [comment]
Closing the issue here as we have https://github.com/flavio/kuberlr/issues/30 for tracking.
