### ISSUE TITLE
Test registry login for the recent credential helper improvements

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#3372]
The idea is to setup some test registries on the cloud platforms such as AWS ECR, GCP, Azure etc and test registry login using `docker` and `nerdctl` CLIs.

**Comment by gaktive** [comment]
Once we have the tests written down, this is a candidate for future BATS (in a new ticket).

**Comment by gunamata** [comment]
Tested configuring credential helpers for AWS Public, Private ECR and GCP registry. Here are the steps that worked for me.

**- Configure `~/.docker/config.json` to use credential helpers for respective container registries. For example, on windows**

```
{
	"credsStore": "wincred",
	"credHelpers": {
		"<account_id>.dkr.ecr.<region>.amazonaws.com: "ecr-login", // AWS Private ECR
		"public.ecr.aws": "ecr-login", // AWS Public ECR
                "us-central1-docker.pkg.dev" : "gcloud"
	}
}
```

**- Authenticate with or Configure profiles  for respective  cloud accounts**

**AWS**:

- Use [aws cli](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to configure aws profile as described [here ](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html)


**GCP**:
- Use [gcloud cli](https://cloud.google.com/cli) to authenticate with your google account using below commands

```
gcloud auth login
gcloud auth activate-service-account  <your-service-account-id>@<your-organization>.iam.gserviceaccount.com  --key-file=your-key-file.json
```


**- Try pull, retag, push using `docker` or `nerdctl` cli, For example,**

**AWS:**
```
docker pull hello-world
aws ecr-public create-repository --repository-name hello-world
docker tag hello-world <your-registry-url>/hello-world
docker push <your-registry-url>/hello-world
```

**GCP:**
```
docker pull hello-world
docker tag hello-world <your-location>-docker.pkg.dev/<your-project-id>/<your-repository-name>/hello-world
docker push <your-location>-docker.pkg.dev/<your-project-id>/<your-repository-name>/hello-world
```
