### ISSUE TITLE
ESLint does not appear to be fixing unchanged lines.

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#3400]
### Actual Behavior

Context: https://github.com/rancher-sandbox/rancher-desktop/blob/bc183f22df27103cbb46a5af3b7789e24f0f7f8a/pkg/rancher-desktop/backend/kube/lima.ts#L429-L436

It looks like eslint isn't fixing the spacing there, causing lines 433 and 434 to not be indented like the surrounding lines.

### Steps to Reproduce

1. Check out bc183f22df27103cbb46a5af3b7789e24f0f7f8a
2. Run `npm run lint` (or equivalently, `eslint --fix pkg/rancher-desktop/backend/kube/lima.ts`).

### Result

No change.

### Expected Behavior

Lines 433 and 434 are changed so the values line up with the surrounding lines.

### Additional Information

I managed to get the linter to fix that chunk locally once, but couldn't reproduce again…

### Rancher Desktop Version

bc183f22df27103cbb46a5af3b7789e24f0f7f8a

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.6

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by rak-phillip** [comment]
eslint rules for key-spacing might shed some light on this behavior

https://eslint.org/docs/latest/rules/key-spacing

With our current config, extra spaces aren't considered incorrect and won't be auto-fixed as a result. In the example provided above, lines 433 and 434 look to be indented properly and the surrounding lines have extra spaces before their values.
