### ISSUE TITLE
since update to >1.5 cant access rancher ui

### ISSUE THREAD

**Issue by PawelSpoon** [rancher-sandbox/rancher-desktop#3407]
### Actual Behavior

i have a working installation of rd with rancher ui (version 1.4 and i think also 1.5)
i did update to 1.6 and rancher.rd.localhost is not accessible: ERR_CONNECTION_REFUSED
i have downdated it to 1.4.1 and again all did work for 1-2 weeks.
today i have again tried an update as 1.6.2 is already out.
again same issue

### Steps to Reproduce

windows 10 
install rancher-desktop 1.6 or higher as per official howto
browse to rancher.rd.localhost
(wsl is enabled)

### Result

can not browser rancher ui

### Expected Behavior

can browse rancher ui

### Rancher Desktop Version

1.6.2

### Rancher Desktop K8s Version

1.20.15

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

windows Windows 10 Enterprise 20H2 build 19042.2130

### What CPU architecture are you using?

x64

### Windows User Only

baracuda vpn

**Comment by PawelSpoon** [comment]
i have to forward port of rancher https-internal and here i reach the dashboard https://localhost:62843/dashboard/auth/login

**Comment by rak-phillip** [comment]
@PawelSpoon thanks for raising the issue and helping to make Rancher Desktop better!

I'd like to confirm a few things as we attempt to reproduce:

1. You are referencing the [Rancher on Rancher Desktop How to Guide in the Rancher Desktop docs](https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop)
2. You are following the instructions for the helm install

**Comment by PawelSpoon** [comment]
@rak-phillip :
from my docs i can see following: 
- the first version i was using was 1.3, i did successfully update either 1.4 or even 1.5. i think to remember the first non-working was 1.6.0
- i was following these instructions : https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop/
- yes, the helm installation
- traefik was enabled
- wsl support (sometimes yes / no)
- my hosts files contains the routes to my app's ingresses that's all

does it makes sense to provide you some logs ?

**Comment by Nino-K** [comment]
I have also managed to repro this, in addition, what I'm noticing is that traefik is not listening on the published ports e.g `80` and `443` but rather on the container ports `30273`, `30571`. 

```
kube-system           traefik                LoadBalancer   10.43.42.59     172.17.236.14   80:30273/TCP,443:30571/TCP   2d23h
```

**Comment by PawelSpoon** [comment]
did test 1.7
works !
