### ISSUE TITLE
Screen shots are missing the borders for Linux and window shadows for Windows

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3431]
> The screen shots are missing the window title and borders. Maybe this needs an OS-specific solution for each platform.

I have some ideas on how to do this on Windows, just need some time to try it out in the next few days.

I won't look for a solution on Linux; somebody else needs to do the research!

_Originally posted by @jandubois in https://github.com/rancher-sandbox/rancher-desktop/issues/2430#issuecomment-1322460938_

**Comment by jandubois** [comment]
I've posted a mechanism to capture full windows on macOS in https://github.com/rancher-sandbox/rancher-desktop/issues/2430#issuecomment-1315749231

**Comment by torchiaf** [comment]
A working example for Linux: [linux/gnome-screenshots](https://github.com/rancher-sandbox/rancher-desktop/commit/6bae5e56eb1fd14384ada286f3af250bef1b440b).
The problem is that gnome-screenshots requires to maintain the focus on testing window, but we could even specify a grab area to take screenshots.
I will try other strategies.

**Comment by jandubois** [comment]
Switching between Light and Dark mode on Windows from the commandline (tested on Windows 10):

```console
# Switch to Dark mode
reg add HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize /v AppsUseLightTheme /t REG_DWORD /f /d 0

# Switch to Light mode
reg add HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize /v AppsUseLightTheme /t REG_DWORD /f /d 0
```

**Comment by jandubois** [comment]
I've been able to create full-window screenshots (including titlebar and menus) on Windows using the FOSS [ShareX](https://getsharex.com) tool.

It is a GUI application, but has some minimal commandline functionality too.

Download the latest "portable" version (meant for USB drives, so you don't need to run the installer) and unzip it: https://github.com/ShareX/ShareX/releases/download/v14.1.0/ShareX-14.1.0-portable.zip

You can capture screenshots of the active window (I didn't find any way to specify an app or window otherwise) using this command:

```console
Z:\jan\Downloads\ShareX>sharex -p -s -ActiveWindow

Z:\jan\Downloads\ShareX>dir ShareX\Screenshots\2022-11
 Volume in drive Z is Shared Folders
 Volume Serial Number is 0000-0064

 Directory of Z:\jan\Downloads\ShareX\ShareX\Screenshots\2022-11

11/29/2022  08:37 PM    <DIR>          .
11/25/2022  03:42 PM    <DIR>          ..
11/29/2022  08:37 PM            54,977 WindowsTerminal_pVORvCxltB.png
               1 File(s)         55,233 bytes
               2 Dir(s)  261,284,085,760 bytes free
```

The `-p` option means "portable" and means the screenshot will be stored under `ShareX\Screenshots\YYYY-MM` directory relative to the location of the `ShareX.exe` executable (it is **not** relative to your current directory).

The `-s` options means "silent", don't show the GUI, and `-ActiveWindow` must be capitalized like this, otherwise it doesn't work correctly.

There is no way to specify the filename it writes to, and the app always appends a random string. So my suggestion would be to always empty out the directory before capturing a window, and then moving the `*.png` file afterwards to the final destination name and directory.

**Comment by gaktive** [comment]
@jandubois to check if Ventura changed behaviour since the shadows look superfluous on macos

**Comment by jandubois** [comment]
> here is a screenshot with shadows

You need to view this issue in Light mode; the shadow is not visible in dark mode.

**Comment by jandubois** [comment]
https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/140 is going to add the shadows via CSS, so I believe the only thing left to do is to disable the shadows from the macOS screenshots, so they don't get double shadows.
