### ISSUE TITLE
Epic: Generate screenshots as part of the CI for docs, #2

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/rancher-desktop#3434]
First part: #2430

* [ ] Create screenshots of additional dialogs (first-run, asking for sudo, ...)
* [ ] Create screenshots of the installer pages

**Comment by jandubois** [comment]
More things to consider in the future:

* screenshot of "General" page that shows a pending update
* screenshot of "General" page that shows the status bar
* include some content on the Port Forwarding page

Once we have the dashboard integrated, we will also want to have at least one dashboard screenshot. We still need to figure out how to integrate Dashboard documentation with Rancher Desktop documentation.

**Comment by jandubois** [comment]
Even more things to do: integrate the additional dependencies for `GetWindowID` on macOS and `ShareX` on Windows to have them automatically installed.

**Comment by jandubois** [comment]
We have to figure out how much documentation we are going to provide for the Cluster Explorer, but we'll probably want at least a few screenshots for it as well.

**Comment by jandubois** [comment]
There are no current plans to implement these additional screenshots; we can always re-open if we change our minds.
