### ISSUE TITLE
Delete pattern should be enabled while editing a pattern

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3456]
If I double-click on a pattern (in the image allow list), I get into edit mode.

At this point the `[-]` box looks enabled (it has the faint blue background instead of grey), but doesn't actually delete the current entry when clicked.

Instead it terminates edit mode and unselects the pattern (and greys out the `[-]` button).

So I have to single click the pattern again to be able to delete it.

I think it should always be possible to delete the current pattern while editing it.

**Comment by torchiaf** [comment]
@jandubois I have just tested the last version (HEAD 64cdaee77820a3b01ca9b3474f1b623f96feade0) and the behavior you described in the issue is not reproducible, at least on my machine.
Could you please test again the latest version and let me know?
Thanks.
