### ISSUE TITLE
Grafana k6 docker image is not working in Rancher Desktop

### ISSUE THREAD

**Issue by kavish-chathuranga** [rancher-sandbox/rancher-desktop#3457]
### Actual Behavior

after running the docker run command k6 logo appears and nothing happened after that

### Steps to Reproduce

create a simple grafana k6 script and try to run it using docker.

docker run -i grafana/k6 run - <script.js

script.js
`import http from 'k6/http';
import { sleep } from 'k6';

export default function () {
  http.get('https://test.k6.io');
  sleep(1);
}
`

### Result

![derr](https://user-images.githubusercontent.com/114043894/203690315-1f8a8d2b-6980-4a19-8468-dd07162e9d6d.PNG)

### Expected Behavior

run the k6 script and display the end-of-test summary in the command line interface

### Rancher Desktop Version

1.6.2

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 19042.2251

### What CPU architecture are you using?

x64

**Comment by adamkpickering** [comment]
Following the steps you gave, I think it worked for me, running on Windows 10 and RD 1.6.2:
```
adam@DESKTOP-PJ3KQUA:/mnt/c/Users/adamk/dev/test/3457$ docker logs e6a5bf7af70e

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: -
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)


running (00m01.0s), 1/1 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 1 VUs  00m01.0s/10m0s  0/1 iters, 1 per VU

running (00m01.4s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [ 100% ] 1 VUs  00m01.4s/10m0s  1/1 iters, 1 per VU

     data_received..................: 17 kB 12 kB/s
     data_sent......................: 438 B 314 B/s
     http_req_blocked...............: avg=326.11ms min=326.11ms med=326.11ms max=326.11ms p(90)=326.11ms p(95)=326.11ms
     http_req_connecting............: avg=61.54ms  min=61.54ms  med=61.54ms  max=61.54ms  p(90)=61.54ms  p(95)=61.54ms
     http_req_duration..............: avg=64ms     min=64ms     med=64ms     max=64ms     p(90)=64ms     p(95)=64ms
       { expected_response:true }...: avg=64ms     min=64ms     med=64ms     max=64ms     p(90)=64ms     p(95)=64ms
     http_req_failed................: 0.00% ✓ 0        ✗ 1
     http_req_receiving.............: avg=478.1µs  min=478.1µs  med=478.1µs  max=478.1µs  p(90)=478.1µs  p(95)=478.1µs
     http_req_sending...............: avg=44.3µs   min=44.3µs   med=44.3µs   max=44.3µs   p(90)=44.3µs   p(95)=44.3µs
     http_req_tls_handshaking.......: avg=233.79ms min=233.79ms med=233.79ms max=233.79ms p(90)=233.79ms p(95)=233.79ms
     http_req_waiting...............: avg=63.48ms  min=63.48ms  med=63.48ms  max=63.48ms  p(90)=63.48ms  p(95)=63.48ms
     http_reqs......................: 1     0.717521/s
     iteration_duration.............: avg=1.39s    min=1.39s    med=1.39s    max=1.39s    p(90)=1.39s    p(95)=1.39s
     iterations.....................: 1     0.717521/s
     vus............................: 1     min=1      max=1
     vus_max........................: 1     min=1      max=1
```

Have you tried a factory reset? Do you have any non-standard network config (VPNs, proxies, special DNS config) on your device?

**Comment by kavish-chathuranga** [comment]
Hi Adam. Yes I tried factory reset and VPN is disabled. Let me check again and get back to you. Thank you trying it out and for the reply.

**Comment by adamkpickering** [comment]
If another try doesn't do the trick, would you mind posting logs for RD (accessible via Troubleshooting > Logs > Show Logs)? And if there are any more logs from K6, please post those too. Thanks!

**Comment by kavish-chathuranga** [comment]
Hi Adam. Please find the attached log files. I tried with a different docker image and it is working fine. But k6 is not working.

[cri-dockerd.log](https://github.com/rancher-sandbox/rancher-desktop/files/10119276/cri-dockerd.log)
[docker.log](https://github.com/rancher-sandbox/rancher-desktop/files/10119277/docker.log)

**Comment by kavish-chathuranga** [comment]
Hi Adam. Were you able to have a look on the log files. Let me know if you find any solution.

**Comment by adamkpickering** [comment]
Hi, not yet. We've got quite the backlog but will get to it when we can. If you are able to find a solution please post it here so others can benefit!

**Comment by kavish-chathuranga** [comment]
Hi Adam. If you find any solution for this please let me know. Thanks for your support.

**Comment by kavish-chathuranga** [comment]
I tried with a different PC and the outcome is the same. Do you have Docker Desktop installed as well? or just RD?

**Comment by kavish-chathuranga** [comment]
I was able to run the script using the following command.
docker run --rm -v $(pwd):/scripts grafana/k6:latest run /scripts/script.js
