### ISSUE TITLE
Ran into a Kubernetes error while performing "Reset Kubernetes (with Images)"

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#3463]
I ran into below error while performing `Reset Kubernetes (with images)` . I am on this [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3544039425) on my Windows 10 Enterprise machine.

Update: Restarting the session worked fine, with Kubernetes reset and images removed.

![image](https://user-images.githubusercontent.com/59538726/203876356-19117011-6b49-4f00-9ff0-20da8926b9a6.png)

**Comment by IsaSih** [comment]
I had the same issue just installing Rancher Desktop (1.6.0-408-gd54f3d63) and running it for the first time. These are the logs for Windows 11: 
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106852/background.log)
[dashboardServer.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106853/dashboardServer.log)
[diagnostics.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106854/diagnostics.log)
[images.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106855/images.log)
[integrations.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106856/integrations.log)
[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106857/k8s.log)
[kube.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106858/kube.log)
[lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106859/lima.log)
[mock.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106860/mock.log)
[networking.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106861/networking.log)
[server.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106862/server.log)
[settings.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106863/settings.log)
[steve.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106864/steve.log)
[update.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106865/update.log)

**Comment by IsaSih** [comment]
Logs for Windows 10
[wsl-helper.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106960/wsl-helper.log)
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106961/background.log)
[dashboardServer.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106962/dashboardServer.log)
[diagnostics.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106963/diagnostics.log)
[images.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106964/images.log)
[integrations.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106965/integrations.log)
[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106967/k8s.log)
[kube.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106968/kube.log)
[lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106969/lima.log)
[mock.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106970/mock.log)
[networking.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106971/networking.log)
[server.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106972/server.log)
[settings.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106973/settings.log)
[steve.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106974/steve.log)
[update.log](https://github.com/rancher-sandbox/rancher-desktop/files/10106975/update.log)
