### ISSUE TITLE
Help button should use white text (and maybe grey background)

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3477]
If the help button is using the blue background, then the text should be white, not black.

It does this correctly in light mode, but not in dark mode:

<img width="880" alt="Screen Shot 2022-11-28 at 2 55 19 PM" src="https://user-images.githubusercontent.com/78947/204398457-22a8214e-d22c-4b8f-b629-9bf9e6ef9cad.png">

However, I would prefer if the help button would not use the primary action styling, but use the platform native style (on macOS), using grey background with a black question mark in light mode, and a white question mark in dark mode.

**Comment by torchiaf** [comment]
Hi @jandubois , changed to:

- light mode: grey background / black question mark
- dark mode: grey background / white question mark

Personally I prefer white question mark also in light mode, anyway below you can see some combinations.

![light_primary](https://user-images.githubusercontent.com/26394656/204525720-f44ec3cf-fbda-4151-9173-9c78f0b975df.png)
![light_implemented](https://user-images.githubusercontent.com/26394656/204525724-0eb59e72-3e92-4428-9eba-dcecae9c4a91.png)
![light_grey](https://user-images.githubusercontent.com/26394656/204525726-1b8cc251-6f12-4d2e-a64f-fe0b667bd5e6.png)
![dark_primary](https://user-images.githubusercontent.com/26394656/204525855-1b12dc93-0c38-432a-84ff-994608d1fa44.png)
![dark_grey](https://user-images.githubusercontent.com/26394656/204525856-bfa054af-bcfa-4b2f-9992-2feda7abe522.png)

**Comment by jandubois** [comment]
> Personally I prefer white question mark also in light mode, anyway below you can see some combinations.

Yeah, I agree. I double checked the macOS Preferences, and they have a grey background for the page (in light mode), so the circle is white, and the question mark is black.

But since we use a darker shade for the button, I think always using white for the question mark looks best.

**Comment by torchiaf** [comment]
Added secondary button examples, see the previous commit.
