### ISSUE TITLE
Docs should default to correct OS automatically

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3482]
Our docs often have blocks that are different based on the host OS.

Unfortunately Docusaurus doesn't seem to have a mechanism to automatically select a view that corresponds to the OS of the browser; it always defaults to "Windows" (because we define it first, I assume).

So when you invoke the URL for "Preferences > Application > Environment" on macOS, you don't get the page you are looking for, because it does not exist on Windows:

https://docs.rancherdesktop.io/next/ui/preferences/application/#environment

I would hope that somebody from the UI team can help out our docs team and write a little bit of Javascript that would select the proper default OS automatically.

It may be slightly more complex because we don't always have 3 choices: "Windows", "macOS", and "Linux", but 2: "Windows", and "macOS & Linux".

**Comment by rak-phillip** [comment]
@jandubois I think that we do this already, can we close this issue?
