### ISSUE TITLE
`rdctl factory-reset`: drop the `--wait=false`option, stop waiting for the app and always kill it -- no need to wait

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3493]
### Actual Behavior

I accidentally tried to repro #3467 on Windows 10 instead of macOS, and the reset failed with an "Access is denied" error.

### Steps to Reproduce

rdctl factory-reset --wait=false

### Result

```console
C:\Users\Jan>rdctl factory-reset --wait=false
time="2022-11-29T15:26:21-08:00" level=error msg="Problem trying to delete C:\\Users\\Jan\\AppData\\Local/rancher-desktop/cache/Rancher Desktop: remove C:\\Users\\Jan\\AppData\\Local/rancher-desktop/cache/Rancher Desktop\\Cache\\Cache_Data\\data_0: Access is denied.\n"
time="2022-11-29T15:26:21-08:00" level=error msg="Problem trying to delete C:\\Users\\Jan\\AppData\\Roaming/rancher-desktop: remove C:\\Users\\Jan\\AppData\\Roaming/rancher-desktop\\lockfile: The process cannot access the file because it is being used by another process.\n"

C:\Users\Jan>wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
openSUSE-Leap-15.2
```

The application is still running, but obviously no longer functional because the distro had been deleted.

### Expected Behavior

The would terminated normally without error and all configuration data is removed.

### Rancher Desktop Version

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3578250286

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Windows User Only

Running in a VM

**Comment by IsaSih** [comment]
Faced similar issue on Windows 10 and Windows 11. However didn't get an output of access denied. 
![image](https://user-images.githubusercontent.com/70187881/204677444-f47b321e-842d-4d40-8c02-285df38b0f10.png)

**Comment by ericpromislow** [comment]
I forgot to mention that this PR is intended only for packaged builds, not dev builds.

**Comment by jandubois** [comment]
> I forgot to mention that this PR is intended only for packaged builds, not dev builds.

I think this is fine for the release, but is there a reason it can't be made to work for the dev setup too? It is not unreasonable to want to do a factory reset to start with a fresh dev setup.

**Comment by ericpromislow** [comment]
I'll have to figure out exactly which processes need to be killed in a dev build to bring down everything. Killing `npm run dev` isn't sufficient to kill all of them.

**Comment by jandubois** [comment]
> I'll have to figure out exactly which processes need to be killed in a dev build to bring down everything.

Create a separate issue for it please, so it doesn't get lost when this one is closed.

**Comment by ericpromislow** [comment]
dev issue: https://github.com/rancher-sandbox/rancher-desktop/issues/3501

**Comment by ericpromislow** [comment]
So we need to *always* wait, because both windows and lima throw fatal exceptions that stop shutdown from happening when certain files they depend on aren't available.

But we should still take away the `--wait` option, just default it to `true` like Mark said.
