### ISSUE TITLE
Windows intaller msi - unexpected error prompt

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3497]
### Actual Behavior

After downloading Rancher Desktop Setup.msi and trying to execute it, an unexpected error dialog appears on screen and installer appears after a while, giving the impression that the installer is corrupted. 

### Steps to Reproduce

1.Download Rancher Desktop Setup.msi
2.Wait for complete download of the installer
3. Execute the installer

### Result

an unexpected error dialog appears on screen and installer appears after a while, giving the impression that the installer is corrupted. 
![error dialog msi installer](https://user-images.githubusercontent.com/70187881/204871223-c8de1b54-bc7b-498f-893c-a40303e0f0d8.png)

### Expected Behavior

Installer should successfully be executed with no error dialogs at any time.

### Rancher Desktop Version

 1.6.0-431-g070c8677

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment]
I always get that error message when I try to install/uninstall a package by running `msiexec OPTIONS file.msi`, so I've been just directly opening the `.msi` file in powershell with the `&` operator. I suspect you're double-clicking on it, right?

**Comment by mook-as** [comment]
Please run the installer with `msiexec /lv* msiexec.log /i rd.msi` and attach the generated log file. (This is new, so we haven't built up how to debug installation issues across the team yet.)

**Comment by ericpromislow** [comment]
[msiexec.log](https://github.com/rancher-sandbox/rancher-desktop/files/10126285/msiexec.log)

This is for a wix build on v1.6.0-450-g519b43cc (output from `git describe --tags`)

The only questionable thing I see is `MainEngineThread is returning 2` but I don't know what `2` means in this context

**Comment by mook-as** [comment]
`msiexec` is weird in that the bulk of the processing is done as a privileged service, so you can't use relative paths for it. Looking at [the reference](https://learn.microsoft.com/en-us/windows/win32/msi/windows-installer-error-messages), your messages are:
> Could not open key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer. System error 2 (The system cannot find the file specified.). 

> The folder path '.' contains an invalid character.

**Comment by ericpromislow** [comment]
Easy fix (for command-line use) thx to https://stackoverflow.com/questions/10108517/what-can-cause-msiexec-error-1619-this-installation-package-could-not-be-opened --  DO NOT USE RELATIVE PATHS to reference the MSI file. Leaving off the leading `.\` (which powershell tab-completion inserts) worked, as did specifying an entire path. But don't use forward slashes because they throw off the msiexec utility.

**Comment by ericpromislow** [comment]
Mark, nice work tying the log file I posted with the error-message reference. I guess the log files are intended for the MSI team, but they could have done better. Also convert relative paths to absolute before spawning a privileged service....

**Comment by gaktive** [comment]
@IsaSih wasn't able to repro this when using a signed installer.
