### ISSUE TITLE
User is able to continue installation without defining a scope - Windows MSI installer

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3498]
### Actual Behavior

Once user is executing Rancher Desktop Setup.msi, it's possible to continue installation without defining an installation scope. It takes a while for the installer to proceed the installation, but once user moves on without selecting a scope, the installer freezes for a long time, and user is not able to click on "Back'" button. By default, the installer proceeds with installation for all users, requesting elevated permissions to continue.

### Steps to Reproduce

1. Download Rancher Desktop Setup.msi
2. Execute the installer
3.Click Next without selecting any installation scope

### Result

![win msi installer-no scope selected](https://user-images.githubusercontent.com/70187881/204874055-b969d622-5a7d-46da-942b-c618f5440e98.gif)

### Expected Behavior

Next button must be blocked unless user selects an installation scope

### Rancher Desktop Version

 1.6.0-431-g070c8677

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
Fixed by #3494.
