### ISSUE TITLE
Replace CD icon with RD icon in MSI installer

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3502]
The default logo in the MSI installer shows a red square with a retro CD icon inside.

We want to use the Rancher Desktop logo instead.

**Comment by mook-as** [comment]
Hmm, according to the [documentation](https://wixtoolset.org/docs/v3/wixui/wixui_customizations/#replacing-the-default-bitmaps), we need bitmaps for:
- Left side of the welcome dialog: 493 × 312 (default asset [here](https://raw.githubusercontent.com/wixtoolset/wix3/develop/src/ext/UIExtension/wixlib/Bitmaps/dlgbmp.bmp).)
- Top of most of the dialogs: 493 × 58 (default asset [here](https://raw.githubusercontent.com/wixtoolset/wix3/develop/src/ext/UIExtension/wixlib/Bitmaps/bannrbmp.bmp).)

The other bitmaps are reminiscent of Windows 95, but that's probably fine.
