### ISSUE TITLE
Privileged Services is not being installed in a signed version - Windows installer MSI

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3504]
### Actual Behavior

After downloading the installer Rancher Desktop Setup.msi and selecting the scope to install Rancher Desktop on the machine, for all users, only one UAC prompt is displayed during installation. UAC prompt to install Privileged Services does not show up, nor the service is installed on the machine.

### Steps to Reproduce

1. Download Rancher Desktop Setup.msi
2. Execute the installer
3. Select installation scope for the whole system -all users
4. Accept the UAC prompt requesting elevation to run the installer
5. Wait for the installer to complete the installation
6. Check if Privileged Services was properly installed

### Result

![no privileged services installed](https://user-images.githubusercontent.com/70187881/204924304-90827270-ebf9-4dbb-b066-037844f552e5.gif)

![image](https://user-images.githubusercontent.com/70187881/204924178-88b917fd-cabc-40a9-83c0-970c9cf13737.png)

### Expected Behavior

UAC prompt should request user to allow the installation of Privileged Services and this service should be installed and available when verifying the services that are installed on the machine.

### Rancher Desktop Version

1.6.0-448-g00891346

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

**Comment by IsaSih** [comment]
Also, focusing on the UAC prompt, I noticed that the installer is not named as Rancher Desktop.msi.

**Comment by mook-as** [comment]
It should be called `Rancher Desktop Privileged Service` (so a bit lower on your screenshot); I'll leave this open so I can examine whether it's installed later.

**Comment by mook-as** [comment]
> Also, focusing on the UAC prompt, I noticed that the installer is not named as Rancher Desktop.msi. 

Yeah, unfortunately Windows Installer internally copies it to a temporary file name, and we can't do anything about it.

**Comment by IsaSih** [comment]
okay, found it! So, the UAC prompt requesting elevation for Privileged Services is no longer expected. Only one UAC prompt is expected for this installing flow?

**Comment by mook-as** [comment]
Yes, we only need one UAC prompt for the whole installation process (with the exception of doing a 1.6.x to 1.7.x upgrade, where we need a separate UAC prompt for the previous uninstaller).

**Comment by mook-as** [comment]
> okay, found it! 

Closing based on my understanding that the reported issue (the privileged service was not being installed) was not reproducible, just that the test case needed to be updated to have a better reference to the service name (i.e. include the "Rancher Desktop" prefix).
