### ISSUE TITLE
Error during application launch

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#3505]
I ran into this error while launching this [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3580187427)

Closing the failed session, and relaunching the app worked fine. 

![image](https://user-images.githubusercontent.com/59538726/204924699-09f0a539-c582-4634-82df-0eda1db8c7fd.png)
 
Logs from this session:

[20221130.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10127851/20221130.zip)

**Comment by mook-as** [comment]
From `wsl-exec.log`:
```
 * Starting openresty ...
 * start-stop-daemon: /usr/local/openresty/bin/openresty is already running

 * Failed to start openresty
                                             [ !! ]
 * ERROR: openresty failed to start
```

**Comment by jandubois** [comment]
@mook-as and I can't repro this with latest CI builds from today. Can you check if you still run into this error?

**Comment by gunamata** [comment]
I could not repro with the latest [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3604713639). Closing the issue for now.
