### ISSUE TITLE
Image list empty after Windows restart

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#351]
After a restart (and windows update) on my desktop, I'm not seeing any images listed. The cluster did come up healthy, so it's just not listing correctly.

![image](https://user-images.githubusercontent.com/442274/121820938-50318180-cc4a-11eb-8a3e-4789e5d2b23a.png)

**Comment by agracey** [comment]
When trying to pull and image to test if it's the list or the link to the cluster, I get this error:
```time="2021-06-13T13:25:54-07:00" level=fatal msg="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.17.21.84:1233: i/o timeout\""
```

![image](https://user-images.githubusercontent.com/442274/121821043-2462cb80-cc4b-11eb-8352-a39e45afd363.png)

**Comment by mook-as** [comment]
This should be fixed (or at least, made better) by #360 (which was merged 3 days after this was filed).  Would it be possible for you to take another look with the top development build from [this list](https://github.com/rancher-sandbox/rancher-desktop/actions/workflows/package.yaml?query=branch%3Amain+is%3Asuccess)? Thanks!

**Comment by agracey** [comment]
I'm now seeing "Waiting for image manager to be ready" and it seems to be indefinite.

![image](https://user-images.githubusercontent.com/442274/123325473-e8eabb80-d4ec-11eb-970f-bfc8ca8c2728.png)

**Comment by agracey** [comment]
The cluster is up:

`agracey@agracey-desktop ~/P/12factor> kubectl get no
NAME              STATUS   ROLES                          AGE    VERSION
agracey-desktop   Ready    builder,control-plane,master   6d1h   v1.21.1+k3s1
agracey@agracey-desktop ~/P/12factor> kubectl get po -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   helm-install-traefik-crd-vvx75            0/1     Completed   0          6d1h
kube-system   helm-install-traefik-fcm5d                0/1     Completed   1          6d1h
kube-system   coredns-7448499f4d-ftbbn                  1/1     Running     2          6d1h
kube-system   local-path-provisioner-5ff76fc89d-6c2hr   1/1     Running     2          6d1h
kube-system   metrics-server-86cbb8457f-gvqsh           1/1     Running     2          6d1h
kube-system   traefik-97b44b794-bpqdd                   1/1     Running     2          6d1h
kube-system   svclb-traefik-tck75                       2/2     Running     4          6d1h
kube-image    builder-hfl7v                             2/2     Running     0          15m`

**Comment by agracey** [comment]
on `Version: 0.3.0-9-gdfcc043`

**Comment by agracey** [comment]
Got `FATA[0020] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.22.250.228:1233: i/o timeout" ` when running `kim images`

**Comment by agracey** [comment]
So it's definitely due to the ip address of WSL being changed after a reboot

**Comment by jandubois** [comment]
I think RD does a `kim builder install --force` on every start to refresh the certs and everything.

Maybe run this manually to see if it makes any difference, or if it fails with a helpful error?

**Comment by agracey** [comment]
That worked and I can see images now. 

Would a previous failure be in a log somewhere?

**Comment by jandubois** [comment]
I don't know; this is something for @mook-as or @ericpromislow to look into.

It seems like the forced refresh is either not happening, or failing.

**Comment by macmiranda** [comment]
Same here. Resetting Kubernetes makes it come back
