### ISSUE TITLE
Factory Reset does not delete anything

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#3519]
While testing the [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3598558497) on my Windows, I noticed the `Factory Reset` did not work as expected.

Steps:

- Install the MSI from the [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3598558497)
- Once the session is up and running, Perform `Factory Reset`.
- On accepting the `Factory Reset` confirmation dialog, the app window gets closed. However, I noticed the window getting closed super quick, almost immediately which is unusual.
- When I relaunch the app from the shortcut, the app directly launches without getting into the initial configuration window

Logs from this session:

[logs-factory-reset-issue.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10143056/logs-factory-reset-issue.zip)

**Comment by jandubois** [comment]
> * On accepting the `Factory Reset` confirmation dialog, the app window gets closed. However, I noticed the window getting closed super quick, almost immediately which is unusual.

This is expected, as we now kill the application instead of performing a proper shutdown: we are going to delete all the data anyways, so we don't care about saving anything.

> * When I relaunch the app from the shortcut, the app directly launches without getting into the initial configuration window

This would be a bug. We should be deleting the `settings.json` file, and it's absence should trigger the first-run dialog.

**Comment by ericpromislow** [comment]
I don't think this is an issue now -- I can't reproduce it. But it could have happened when we had `factory-reset --wait=false`. RD is still running, but it might have hit a fatal error when it was looking for a file or directory during shutdown, but that file had been deleted. The fatal error kills RD immediately, but I can't explain why the settings file is still present, because failures to delete files and directories are reported but don't stop the factory-reset file-deletion step.

**Comment by gunamata** [comment]
I could repro this with the [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3623693560) shared by Jan this morning.

**Comment by mook-as** [comment]
Actually, factory reset isn't resetting anything at all.

We do a factory reset by launching `rdctl` which kills Rancher Desktop and all its children… including `rdctl`. So nothing ever gets deleted.

https://github.com/rancher-sandbox/rancher-desktop/blob/381333d5890f798f6d63a94921cb7eb4cda82b62/src/go/rdctl/pkg/factoryreset/factory_reset_windows.go#L34

**Comment by ericpromislow** [comment]
Does this mean the windows version needs to set `commonShutdownSettings.WaitForShutdown = true` ?

**Comment by jandubois** [comment]
I don't know if this will have any effect, but I would try to pass the `DETACHED_PROCESS` flag to `CreateProcess` when spawning `rdctl factory-reset` from Rancher Desktop.

But I'm not sure if this is just a console handling flag, or if it will put the new process outside the current process tree. But where would it put it, as a sibling to RD?

**Comment by mook-as** [comment]
Looking at the [documentation](https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags), `DETACHED_PROCESS` is just for console handling; it has no relation to the parent/child relationships.

@ericpromislow Do you want to work on a PR to do the wait thing for now? I was hoping to figure out some arguments for `taskkill` that would do the thing we want, but that doesn't seem possible; working on an API-based process killing change now, but that would take longer than waiting (though I'd prefer avoiding waiting for stability reasons).
