### ISSUE TITLE
RD fails to start after upgrade on Windows

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#352]
![Screenshot 2021-06-14 101856](https://user-images.githubusercontent.com/62991/121907847-7282d800-ccfa-11eb-85dd-87528dbec33e.png)

On the latest main build I get a general error and with the build from #346 I get the above error. It's more specific. This only happens after an upgrade. It appears to happen every time it starts up from the installer.

**Comment by mook-as** [comment]
I'm having issues reproducing the error with the tip of #346 now — did manage it once, but it was unhelpfully generic (certificate error, as indicated in the message), I believe from when `start()` fails.

https://github.com/rancher-sandbox/rancher-desktop/blob/2f23e97ae8614e58bfd8a5ba84a7541212ab9d1a/background.ts#L132

The logs indicate that the kubeconfig was already updated, which would mean it's past the new code checking for the certificate.

https://github.com/rancher-sandbox/rancher-desktop/blob/2f23e97ae8614e58bfd8a5ba84a7541212ab9d1a/src/k8s-engine/wsl.ts#L383-L384

I think that means the code I removed in 805cd8a6694fd3ad080ce88fb63c2f5b1fb3612a would have handled it; however, it's unclear to me why that would be needed, as the earlier check should have made it redundant.  I could put that code back, but that's unsatisfying; also, that wouldn't explain why it would happen in `main` (where that code still exists).

**Comment by mattfarina** [comment]
With the latest changes to #346 being merged I can no longer reproduce this.
