### ISSUE TITLE
Image Allow List is not allowing to pull images matching the pattern

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3522]
### Actual Behavior

Once we add pattern to the Image Allow List and click "Apply", by trying to pull an image matching one of the patterns both from UI and CLI, an error of "Manifest unknown" occurs and the images are not pulled.

### Steps to Reproduce

1. Launch Rancher Desktop
2. Go to Preferences > Container Engine > Allowed Images
3. Add patterns to the list
4. Click Apply
5. Go to Images tab of main window
6. Try to pull an image matching one of the patterns
7. Check the output
8. Open a new terminal window
9. Try to pull the same image via CLI
10. Check the output

### Result

<img width="934" alt="Screen Shot 2022-12-02 at 1 00 53 AM" src="https://user-images.githubusercontent.com/70187881/205360639-71c88ad8-08f4-40a8-ad26-8e2b94b89a6c.png">

![failing to pull image matching pattern](https://user-images.githubusercontent.com/70187881/205366604-6859a48c-b6a3-4c6c-a761-290b7153c6d7.gif)

### Expected Behavior

User should successfully pull images that match the pattern.

### Rancher Desktop Version

1.6.0-462-gf1a12006

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
I believe the allow list syntax looks more like:
```
rancher/mirrored-[^/]+
suse/[^/]+
```
(So, don't do the `^` anchoring, don't add the `manifests/` path, don't include `$` matches, don't have the `0` at the end for nginx.)

Additionally, the image you're pulling doesn't have a `latest` tag: [rancher/mirrored-grafana-grafana](https://hub.docker.com/r/rancher/mirrored-grafana-grafana/tags?page=1&name=latest)

**Comment by IsaSih** [comment]
Retested with suggested corrections and tests passed. Created issue #3525 to correct examples of patterns in the documentation. Closing this issue as everything is working as expected.
