### ISSUE TITLE
Image Allow List is pulling images that do NOT match the pattern

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3523]
### Actual Behavior

After adding patterns to Image Allow List and trying to pull an image that does not match the pattern, Rancher Desktop successfully pulls the image.

### Steps to Reproduce

Launch Rancher Desktop
Go to Preferences > Container Engine > Allowed Images
Add patterns to the list
Click Apply
Go to Images tab of main window
Try to pull an image NOT matching any of the patterns
Check the output
Open a new terminal window
Try to another image NOT matching any pattern via CLI
Check the output

### Result

Rancher Desktop is successfully pulling the images.
![ial pulling images out of pattern](https://user-images.git
<img width="1011" alt="Screen Shot 2022-12-02 at 1 02 03 AM" src="https://user-images.githubusercontent.com/70187881/205369331-1f3588d4-0733-4253-835a-d0da6d2bf52d.png">
hubusercontent.com/70187881/205368051-426fbe83-eefe-4ce6-9a2d-5fc22ca4de7e.gif)

### Expected Behavior

Rancher Desktop must not pull the images that do NOT match any of the patterns in Images Allow List

### Rancher Desktop Version

1.6.0-462-gf1a12006

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
Seems to work for me, using the expected allow list syntax:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/3977982/205400612-2f1f7b03-62ff-4a81-bb55-56aa399e01f2.png">
```
$ docker pull alpine
Using default tag: latest
Error response from daemon: unauthorized: image registry-1.docker.io/library/alpine:latest is not covered by Rancher Desktop image-allow-list
```
Running 9040db77 on macOS.

It also doesn't work if I use your allow list:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/3977982/205400815-7057cde0-417c-4ce2-bb6d-4a3edd0cb974.png">
```
$ docker pull alpine
Using default tag: latest
Error response from daemon: unauthorized: image registry-1.docker.io/library/alpine:latest is not covered by Rancher Desktop image-allow-list
```
Note that this gets doubled up as written:
```
$ rdctl shell cat /usr/local/openresty/nginx/conf/image-allow-list.conf
~*^registry.k8s.io(:443)?/pause:[^/]+$ 0;
~*^registry-1.docker.io(:443)?/rancher/mirrored-pause:[^/]+$ 0;
~*^~*^registry-1.docker.io(:443)?/v2/rancher/mirrored-[^/]+/manifests/[^/]+$ 0/manifests/[^/]+$ 0;
~*^~*^registry-1.docker.io(:443)?/v2/suse/[^/]+/manifests/[^/]+$ 0/manifests/[^/]+$ 0;
```

Note that your message says "Downloaded _newer_ image fro alpine:latest", so you already had that image on disk before attempting. It looks like the image allow list isn't blocking that correctly — @jandubois, is this expected?

**Comment by jandubois** [comment]
> Note that your message says "Downloaded _newer_ image for alpine:latest", so you already had that image on disk before attempting. It looks like the image allow list isn't blocking that correctly — @jandubois, is this expected?

No, it should block you from even checking the digest to see if you have the latest or not.

I don't see how you can get the results @IsaSih reported; are you sure you pressed "Apply" before trying to pull? Settings are not updated until you "Apply" them, so the list is still disabled.

**Comment by IsaSih** [comment]
Reproduced this issue only by applying the full regex patterns. Simplified patterns are being applied as expected.
