### ISSUE TITLE
Remove Equivalent Fully Formed RegEx from the table of patterns - Image Allow List

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3525]
### Problem Description

Our current documentation gives examples of patterns to be added to the Image Allow List feature. However, it exposes the Equivalent Fully Formed RegEx, which is an internal implementation detail and should not be exposed to the user, which is an internal implementation detail and should not be exposed to the user.

### Proposed Solution

Remove the Equivalent Fully Formed RegEx from the docs and keep only the simplified patterns.

**Comment by jandubois** [comment]
Simplified documentation in https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/131
