### ISSUE TITLE
Error installing 1.6.0.462 MSI : missing various permissions

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3529]
### Actual Behavior

The dialog boxes are unfortunately not copyable -- see the screen shots

### Rancher Desktop Version

1.6.0.462

### Operating System / Build Version

Windows 10 Home

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment]
![Screen Shot 2022-12-02 at 1 07 40 PM](https://user-images.githubusercontent.com/108392/205386388-9783ec61-1fb5-42c6-add8-fbc822ceeb0b.png)

![Screen Shot 2022-12-02 at 1 08 02 PM](https://user-images.githubusercontent.com/108392/205386437-85960515-4f26-42cc-bf5b-f97c3823d83e.png)

![Screen Shot 2022-12-02 at 1 08 08 PM](https://user-images.githubusercontent.com/108392/205386459-f9b95b5c-2891-4069-a9b6-f009f7f245f3.png)

![Screen Shot 2022-12-02 at 1 08 22 PM](https://user-images.githubusercontent.com/108392/205386498-bcf7ee5c-4f7c-40c7-ab77-76cb29f03b95.png)

![Screen Shot 2022-12-02 at 1 08 32 PM](https://user-images.githubusercontent.com/108392/205386516-fdd90f65-e26a-449f-b662-0bfb944825e5.png)

**Comment by jandubois** [comment]
> The dialog boxes are unfortunately not copyable

You cannot select text, but normally you can click anywhere inside the dialog (except on the buttons, of course), and then press ⌃C, and it will copy the dialog text to the clipboard.

**Comment by mook-as** [comment]
Hi! Some questions:
- Did you choose per-machine or per-user installation? (Or was the scope dialog unavailable?)
- Did the UAC prompt come up?
- Do you have installation logs?

**Comment by ericpromislow** [comment]
I chose per-user.
I didn't get the UAC prompt.
No, I don't have installation logs (yet). I'm working on creating a new Windows VM in case the old one was corrupted (seems unlikely...)

**Comment by mook-as** [comment]
Odd, the second screen shot (the event log stuff) should only be installed for elevated installs. That sounds like the installer was unelevated, but somehow thought it was (and therefore tried to install things that require elevation), leading to the errors.

Investigating.

**Comment by ericpromislow** [comment]
I'll see if I can dig up a log file. Meanwhile I created a new VM and got the "unopenable package error" with a recent CI-build MSI, written up at #3530

**Comment by ericpromislow** [comment]
Not running into this with the MSI from PR 3483, action 3591485540

**Comment by ericpromislow** [comment]
[log.txt](https://github.com/rancher-sandbox/rancher-desktop/files/10145061/log.txt)

Finally reproduced it. The log file is a touch large, and I cancelled out after that first permissions error
