### ISSUE TITLE
Post installation launch error on Windows

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#353]
After installation, the app doesn't startup even if "Launch Rancher Desktop" option is selected.
The app icon shows up inactive in the system tray.

Steps to reproduce:

- Install 0.3.0 version (Ex: https://github.com/rancher-sandbox/rancher-desktop/suites/2990078693/artifacts/67528842 )
- Make sure "Run Rancher Desktop" check box is selected at the end of the installation.

**My laptop configuration**

Device name	DESKTOP-HIQ5D5U
Processor	Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz   2.29 GHz
Installed RAM	8.00 GB (7.88 GB usable)
Device ID	EF38D081-2ECA-4DC6-8700-045346E648B6
Product ID	00330-80000-00000-AA318
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	Dev
Installed on	‎6/‎7/‎2021
OS build	21390.1010
Experience	Windows 10 Feature Experience Pack 321.13302.10.3

**Comment by gaktive** [comment]
@gunamata to try with the latest image and report back.

**Comment by gunamata** [comment]
The reported issue is resolved in the latest version.
So, Closing the issue here.
