### ISSUE TITLE
Unopenable installation package error from a CI-built MSI

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3530]
### Actual Behavior

Double-click on the MSI icon:
```
Windows Installer

This installation package could not be opened.  Contact the application vendor to verify that this is a valid Windows Installer package.
```

Run `msiexec /i C:\Users\User\Downloads\rd-pr3507-2202-12-02a-Setup.msi"`:

Log file:
```
PS C:\Users\User\Downloads> msiexec /l*v log.txt /i "C:\Users\User\Downloads\rd-pr3507-2202-12-02a-Setup.msi"
PS C:\Users\User\Downloads> cat log.txt
=== Verbose logging started: 12/2/2022  14:57:33  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
MSI (c) (3C:DC) [14:57:33:600]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (3C:DC) [14:57:33:600]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (3C:24) [14:57:33:704]: Resetting cached policy values
MSI (c) (3C:24) [14:57:33:704]: Machine policy value 'Debug' is 0
MSI (c) (3C:24) [14:57:33:704]: ******* RunEngine:
           ******* Product: C:\Users\User\Downloads\rd-pr3507-2202-12-02a-Setup.msi
           ******* Action:
           ******* CommandLine: **********
MSI (c) (3C:24) [14:57:33:719]: Note: 1: 2203 2: C:\Users\User\Downloads\rd-pr3507-2202-12-02a-Setup.msi 3: -2147286960
MSI (c) (3C:24) [14:57:33:719]: MainEngineThread is returning 1620
=== Verbose logging stopped: 12/2/2022  14:57:33 ===
```

This MSI is from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3604953898

### Steps to Reproduce

Download the .msi file from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3604953898
into a Windows VM

Try to install it.

### Result

See above

### Expected Behavior

Not that

### Rancher Desktop Version

1.7.0.dev

### What operating system are you using?

Windows

### Operating System / Build Version

Windows [Version 10.0.22000.1219]

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
> MSI (c) (3C:24) [14:57:33:719]: Note: 1: 2203 2: C:\Users\User\Downloads\rd-pr3507-2202-12-02a-Setup.msi 3: -2147286960

Translated via [the error table](https://learn.microsoft.com/en-us/windows/win32/msi/windows-installer-error-messages):
> Database: C:\Users\User\Downloads\rd-pr3507-2202-12-02a-Setup.msi. Cannot open database file. System error 0x80030050.

The error code is `STG_E_FILEALREADYEXISTS`.  I have no idea what that actually means (other than, presumably, some file already existing).

**Comment by ericpromislow** [comment]
Can no longer reproduce (including when the MSI is in `C:\Users\USER\Downloads` -- there doesn't appear to be anything magical about that directory.
