### ISSUE TITLE
Exclude disk images from Time Machine

### ISSUE THREAD

**Issue by vincent99** [rancher-sandbox/rancher-desktop#354]
- Rancher-desktop currently makes up a new generic-sounding ~/Library/State folder that is only used for itself AFAICT.  It should go somewhere more standard like ~/Library/Application Support. ([logs](https://github.com/rancher-sandbox/rancher-desktop/issues/298) too)

- There is no option to exclude this dir from Time Machine, which means it constantly backing up gigs of (mostly) garbage if you use Time Machine, unless you go `ps`-diving to find the above obscure directory.

- The filename has an uncommon extension (`.rawdisk`), which prevents it from being detected by and excluded by default from other backup tools like BackBlaze.  So I'm uploading gigs of (mostly) garbage to the internet too.

- There is no option to choose the location of the state, which I might not want on my home device.  Small, slow, or network-mounted home dirs are A Thing™.

**Comment by jandubois** [comment]
This is additional context for #298

**Comment by jandubois** [comment]
> * Rancher-desktop currently makes up a new generic-sounding ~/Library/State folder that is only used for itself AFAICT.  It should go somewhere more standard like ~/Library/Application Support. ([logs](https://github.com/rancher-sandbox/rancher-desktop/issues/298) too)

We are all in agreement that `~/Library/State` has to go, and that's what #298 is about.

> * There is no option to exclude this dir from Time Machine, which means it constantly backing up gigs of (mostly) garbage if you use Time Machine, unless you go `ps`-diving to find the above obscure directory.

Yes, we should have an option to include/exclude our machine directory from Time Machine. It is just an extended attribute on the directory and can be manipulated like this:

```console
$ tmutil isexcluded ~/Library/State/rancher-desktop/driver/machines
[Included]    /System/Volumes/Data/Users/jan/Library/State/rancher-desktop/driver/machines
$ tmutil addexclusion ~/Library/State/rancher-desktop/driver/machines
$ tmutil isexcluded ~/Library/State/rancher-desktop/driver/machines
[Excluded]    /System/Volumes/Data/Users/jan/Library/State/rancher-desktop/driver/machines
$ xattr -l ~/Library/State/rancher-desktop/driver/machines
com.apple.metadata:com_apple_backup_excludeItem:
00000000  62 70 6C 69 73 74 30 30 5F 10 11 63 6F 6D 2E 61  |bplist00_..com.a|
00000010  70 70 6C 65 2E 62 61 63 6B 75 70 64 08 00 00 00  |pple.backupd....|
00000020  00 00 00 01 01 00 00 00 00 00 00 00 01 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00 00 00 00 00 1C           |.............|
0000003d
$ tmutil removeexclusion ~/Library/State/rancher-desktop/driver/machines
```

This exclusion will **not** show up in the Time Machine preferences. It is possible to add the path to the exclusion database instead of setting an attribute on the object, but it can only be done using `root`, which I would like to avoid.

You can check for all files with this exclusion:

```console
$ mdfind "com_apple_backup_excludeItem = 'com.apple.backupd'" | sort | head
[...]
/Users/jan/Library/Application Support/Google/Chrome/Default/Favicons
/Users/jan/Library/Application Support/Google/Chrome/Default/Favicons-journal
/Users/jan/Library/Application Support/Google/Chrome/Default/History
/Users/jan/Library/Application Support/Google/Chrome/Default/History-journal```
[...]
```

> * The filename has an uncommon extension (`.rawdisk`), which prevents it from being detected by and excluded by default from other backup tools like BackBlaze.  So I'm uploading gigs of (mostly) garbage to the internet too.

We obviously need to show the location of the machine folder in the UI (and make it configurable too), but then you will still have to add the path manually to the [Backblaze exclusion list](https://help.backblaze.com/hc/en-us/articles/217664948).

Even after we switch from [hyperkit](https://github.com/rancher-sandbox/docker-machine-driver-hyperkit) to [lima](https://github.com/rancher-sandbox/lima), the file extension would still at best be `qcow2`, which Backblaze doesn't know either (but right now lima doesn't use any file extention on the disk image files).

> * There is no option to choose the location of the state, which I might not want on my home device.  Small, slow, or network-mounted home dirs are A Thing™.

We do need to provide a UI that both displays the current location (copyable to clipboard), and allows the user to change it.

I'll leave discussion of the default location to #298.

Unfortunately we will  have to limit the user-configurable absolute path part to something like 67 characters because we will need to append `/rancher-desktop/default/serial.sock` to it and still be below 104 bytes, which is the maximum size of a socket name including trailing NUL on macOS (108 bytes on Linux).

We can maybe shorten the machine name from `default` to `0` to get a few extra characters, but I would prefer to always use the `rancher-desktop` subdirectory name underneath the user-specified directory.

**Comment by jandubois** [comment]
> I would prefer to always use the `rancher-desktop` subdirectory name underneath the user-specified directory.

Maybe this is unclear. What I mean is that if I select to move the directory to my SSD array at `/Volumes/ThunderBlade` in the "File Open" dialog, then Rancher Desktop should create `/Volumes/ThunderBlade/rancher-desktop` and move the machine state in there.

The user should not have to manually create the new directory inside the Finder window, which is tedious and error-prone. And we don't want to move the machines into an existing directory that has any other data in it anyways; the whole destination directory should be under RD control.

**Comment by mattfarina** [comment]
This issue only needs to deal with marking the VM file as not being handled by time machine. Moving the VM to a new location is in #369 and should happen after the move to LIMA.
