### ISSUE TITLE
Error downgrading Rancher Desktop

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#3547]
With #3506 closed, I could install the EXE version (1.6.2). However, I run to the below error message while launching the EXE version.

Steps to reproduce:

- Install a MSI version, for example this [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3615524380)
- Uninstall the MSI version
- Install the EXE version ([1.6.2](https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.6.2/Rancher.Desktop.Setup.1.6.2.exe))

![image](https://user-images.githubusercontent.com/59538726/205705774-0b539cd7-d2f9-4f46-bcac-20a79a3a0c0c.png)

**Comment by ericpromislow** [comment]
Were you running a dev version that uses the `.ztar` files earlier?

**Comment by gunamata** [comment]
No, I was a CI build on `main` branch. My understanding is that I need to perform `Factory Reset` before uninstalling the MSI and then need to install the EXE version. I will be trying this with the latest CI build today.

**Comment by jandubois** [comment]
Documented in release notes, with a link to Troubleshooting docs with more info.
