### ISSUE TITLE
"Could not launch hyperkit; exiting with status 1" after clean install of version 0.21 on Macbook Pro with M1

### ISSUE THREAD

**Issue by ppicom** [rancher-sandbox/rancher-desktop#355]
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/6653522/logs.zip)

Hi!

I just installed version 0.21 of Rancher Desktop and I keep running into this error that prevents the kubernetes cluster from starting. I don't know to what extend it might be relevant, but I already have Docker Desktop and minikube installed on my machine.

These are the log files under `~/Library/State/rancher-desktop/logs` folder.

**Comment by jandubois** [comment]
Thanks for reporting!

Apple Silicone is not yet supported: #16 

I'm closing this as a duplicate for now.
