### ISSUE TITLE
Error reloading openresty after factory-reset

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3560]
### Actual Behavior

After performing factory reset via UI, and trying to pull an image with nerdctl, user gets a connection refused error. Logs from the server indicate an error in reloading openresty.

### Steps to Reproduce

1.From docker, switch engine to containerd
2. Add a pattern to IMAGE ALLOW LIST
2. Pull an image with nerdctl  that does not match the pattern
3. Check the output
4. Do factory-reset via UI
5.Relaunch Rancher Desktop, selecting containerd as the engine
6. Try to pull an image via UI
7. Check the output
8. Try to pull the same image via CLI
9. Check the output

### Result

When switching engines, and pulling an image that doesn't match the pattern we observe the Forbidden error as expected. However, after doing a Factory Reset and selecting containerd since the first-run dialog, we get a connection refused error when trying to pull an image, regardless with its name is matching the pattern or not.
After switching engine, before factory-reset:
<img width="932" alt="Screen Shot 2022-12-06 at 10 53 58 AM" src="https://user-images.githubusercontent.com/70187881/206051329-eb6a4cc4-c317-498d-8289-623bf737f18b.png">

After factory-reset:
Full error 
```
time="2022-12-06T19:01:56Z" level=info msg="trying next host" error="failed to do request: Head \"https://registry-1.docker.io/v2/rancher/mirrored-cilium-cilium-etcd-operator/manifests/v2.0.7-amd64\": proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused" host=registry-1.docker.io
time="2022-12-06T19:01:56Z" level=error msg="server \"docker.io\" does not seem to support HTTPS" error="failed to resolve reference \"docker.io/rancher/mirrored-cilium-cilium-etcd-operator:v2.0.7-amd64\": failed to do request: Head \"https://registry-1.docker.io/v2/rancher/mirrored-cilium-cilium-etcd-operator/manifests/v2.0.7-amd64\": proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused"

time="2022-12-06T19:01:56Z" level=info msg="Hint: you may want to try --insecure-registry to allow plain HTTP (if you are in a trusted network)"

time="2022-12-06T19:01:56Z" level=fatal msg="failed to resolve reference \"docker.io/rancher/mirrored-cilium-cilium-etcd-operator:v2.0.7-amd64\": failed to do request: Head \"https://registry-1.docker.io/v2/rancher/mirrored-cilium-cilium-etcd-operator/manifests/v2.0.7-amd64\": proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused"

Error: exit status 1
```

### Expected Behavior

Containerd must have access to the server

### Rancher Desktop Version

1.6.0-477-g44b1d327

### Rancher Desktop K8s Version

1.25.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by IsaSih** [comment]
[server.log](https://github.com/rancher-sandbox/rancher-desktop/files/10171330/server.log)

**Comment by IsaSih** [comment]
Seems to be resolved on CI build 1.6.0-505-g381333d5, after bug fix #3553

**Comment by jandubois** [comment]
> ### Steps to Reproduce
> 1.From docker, switch engine to containerd
> 2. Add a pattern to IMAGE ALLOW LIST
> 2. Pull an image with nerdctl that does not match the pattern
> 3. Check the output
> 4. Do factory-reset via UI
> 5. Relaunch Rancher Desktop, selecting containerd as the engine

I noticed that you do not enable the image allow list again here; is that correct?

> 6. Try to pull an image via UI
> 7. Check the output
> 8. Try to pull the same image via CLI
> 9. Check the output

I successfully pulled the image as expected.

**Comment by jandubois** [comment]
Closing as non-reproducible now, as I have no idea what else to do.
