### ISSUE TITLE
`npm run dev` run: error on factory reset, and `nerdctl run hello-world` fails

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3572]
### Actual Behavior

Upon a fresh start after a factory reset, `nerdctl run` does not work. Also, factory resets throw an error.

### Steps to Reproduce

1. Do a factory reset to ensure you're starting from fresh.
2. Run `npm run dev` on 5feca5c0 after ensuring all dependencies are up to date.
3. Wait for RD to finish starting up.
4. Go to a terminal and run `nerdctl run hello-world`. Note the failure.
5. Do a factory reset. Note that RD prints an error message in the terminal, and the RD icon in the tray turns red.

### Result

Upon running `nerdctl run hello-world`:
```
adam@DESKTOP-PJ3KQUA [~]$ nerdctl run hello-world
INFO[0000] trying next host                              error="failed to do request: Head \"https://registry-1.docker.io/v2/library/hello-world/manifests/latest\": proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused" host=registry-1.docker.io
ERRO[0000] server "docker.io" does not seem to support HTTPS  error="failed to resolve reference \"docker.io/library/hello-world:latest\": failed to do request: Head \"https://registry-1.docker.io/v2/library/hello-world/manifests/latest\": proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused"
INFO[0000] Hint: you may want to try --insecure-registry to allow plain HTTP (if you are in a trusted network)
FATA[0000] failed to resolve reference "docker.io/library/hello-world:latest": failed to do request: Head "https://registry-1.docker.io/v2/library/hello-world/manifests/latest": proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
Error: exit status 1
```
Upon factory reset, this is what is printed in the terminal:
```
(node:24169) UnhandledPromiseRejectionWarning: Error: /home/adam/dev/rancher-desktop/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/home/adam/dev/rancher-desktop/dist/app/background.js:56043:27)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
(node:24169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24169) Warning: Closing file descriptor 134 on garbage collection
(node:24169) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
```

### Expected Behavior

`nerdctl run` and factory reset should work without errors.

### Additional Information

Note that the `nerdctl run` behaviour only shows up on the first run after a factory reset. On subsequent runs, it appears to work fine. It appears that factory resets always fail, unless you do the factory reset before RD is finished starting up.

### Rancher Desktop Version

5feca5c0

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by adamkpickering** [comment]
This seems to imply that we are trying to stop the `k3s` openrc service after the Lima VM is shut down.

**Comment by adamkpickering** [comment]
I would say there is overlap, since doing a factory reset via the UI now calls `rdctl`. I'm going to close this issue as the `nerdctl run` part appears to be fixed by doing a known-good factory reset (on an earlier version).

**Comment by ericpromislow** [comment]
That error happens when `rdctl` thinks RD is no longer running and deletes the files, but RD is still actually running and throws this exception when it tries to access a no-longer-available file.

**Comment by adamkpickering** [comment]
Closing as duplicate of #3501.
