### ISSUE TITLE
Test Case 63: rdctl factory-reset from CLI

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3587]
### Actual Behavior

```
> rdctl factory-reset --wait=false --verbose=true
Error: unknown flag: --wait
Usage:
  rdctl factory-reset [flags]

Flags:
  -h, --help                      help for factory-reset
      --remove-kubernetes-cache   If specified, also removes the cached Kubernetes images.
      --verbose                   Be verbose

Global Flags:
      --config-path string   config file (default C:\Users\prak\AppData\Roaming\rancher-desktop\rd-engine.json)
      --host string          default is localhost; most useful for WSL
      --password string      overrides the password setting in the config file
      --port string          overrides the port setting in the config file
      --user string          overrides the user setting in the config file
```

### Steps to Reproduce

1. By running rdctl factory-reset --wait=false --verbose=true , verify you don't see a prompt every 2 seconds where rdctl reports on progress waiting for key parts of Rancher Desktop to have shut down.

### Result

```
> rdctl factory-reset --wait=false --verbose=true
Error: unknown flag: --wait
Usage:
  rdctl factory-reset [flags]

Flags:
  -h, --help                      help for factory-reset
      --remove-kubernetes-cache   If specified, also removes the cached Kubernetes images.
      --verbose                   Be verbose

Global Flags:
      --config-path string   config file (default C:\Users\prak\AppData\Roaming\rancher-desktop\rd-engine.json)
      --host string          default is localhost; most useful for WSL
      --password string      overrides the password setting in the config file
      --port string          overrides the port setting in the config file
      --user string          overrides the user setting in the config file
```

### Expected Behavior

Verify you don't see a prompt every 2 seconds where rdctl reports on progress waiting for key parts of Rancher Desktop to have shut down.

### Additional Information

Test case 63: rdctl factory-reset from CLI

### Rancher Desktop Version

1.7.0-rc1

### Rancher Desktop K8s Version

NA

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
This is expected, and the test case needs to be updated. We no longer offer the option of `--wait` (since any existing ones are just killed directly, on all platforms).

**Comment by rak-phillip** [comment]
@IsaSih can we update the test template?

**Comment by IsaSih** [comment]
Will update the test case and close this issue
