### ISSUE TITLE
Test Case 67: Image Allow List - component behavior and design

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3588]
### Actual Behavior

> List of patterns must be scrollable to the right/left when pattern is longer than the component

UI does not scroll with a long pattern. It looks like long patterns are truncated with ...

### Steps to Reproduce

1. Navigate to Preferences => Container Engine => Allowed Images
2. Enter a very long expression in the list

### Result

Long rules are truncated with ...

### Expected Behavior

Long rules will cause the pane to scroll horizontally

### Additional Information

![image](https://user-images.githubusercontent.com/835961/206587027-b1d3725a-211b-47e5-a6d7-bf8e209c0fee.png)

### Rancher Desktop Version

1.7.0-rc1

### Rancher Desktop K8s Version

NA

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
If there are spaces in the string, there is wrapping but it's still weird.

**Comment by gaktive** [comment]
The wrapped text in the 2nd line is vertically clipped, so it looks bad but the field shouldn't have spaces or anything there in legit syntax anyways.

**Comment by torchiaf** [comment]
Created an issue to resolve the issue at library level: https://github.com/rancher/dashboard/issues/7675

**Comment by IsaSih** [comment]
On MacOS: 
<img width="761" alt="Screen Shot 2022-12-09 at 3 31 00 PM" src="https://user-images.githubusercontent.com/70187881/206812293-a30ec944-030c-440e-9351-18c42e1e1cff.png">
