### ISSUE TITLE
Test case 71: Verify that only one instance of Rancher Desktop can run, and window behaviour upon second instance

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3589]
### Actual Behavior

Two instances of Rancher Desktop can be opened during first run.

### Steps to Reproduce

1. Factory Reset
2. Launch Rancher Desktop and wait for first run dialog
3. Launch Rancher Desktop

### Result

The main window is rendered along with the first run dialog.

### Expected Behavior

Only the first run dialog is rendered

### Additional Information

![image](https://user-images.githubusercontent.com/835961/206586853-d5448c30-f39d-408a-a25d-30a1360eaad5.png)

### Rancher Desktop Version

1.7.0-rc1

### Rancher Desktop K8s Version

NA

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows 10

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by adamkpickering** [comment]
I was able to reproduce this on Windows 10. That's what you were on right? (It says macOS under the operating system field, but Windows 10 Pro under the build version).

**Comment by adamkpickering** [comment]
I think I know why this is happening. On the `second-instance` event, `window.openMain` is called. So we aren't actually starting two instances. We are just opening the main window prematurely. If this is right, this should occur on other platforms as well. I'll work on this tomorrow morning if nobody gets to it before then.

**Comment by rak-phillip** [comment]
@adamkpickering yes, I'm on Windows 10. I guess I glossed over a few fields while creating my issues 😤
