### ISSUE TITLE
Rancher Desktop is failing to scan images

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3590]
### Actual Behavior

Functionality to scan images is broken. For python, scanning the image brings a JSON formatted output and breaks the UI. For alpine and registry.k8s.io/pause , scanning the image brings an empty table

### Steps to Reproduce

1. Run `docker pull python`
2. Run `docker pull alpine`
3. Go to Images tab, and then click on the 3 dot icon to scan images of python, alpine and registry.k8s.io/pause
4. Check the output

### Result

<img width="934" alt="Screen Shot 2022-12-08 at 5 49 02 PM" src="https://user-images.githubusercontent.com/70187881/206605295-dc1287e3-d36c-4d3d-97b3-90c25134f946.png">
<img width="934" alt="Screen Shot 2022-12-08 at 5 49 16 PM" src="https://user-images.githubusercontent.com/70187881/206605298-35e4b1fb-3ff7-4a3e-a545-7b25422397ea.png">
<img width="934" alt="Screen Shot 2022-12-08 at 5 56 58 PM" src="https://user-images.githubusercontent.com/70187881/206605990-8c7896d6-5bff-49a6-9095-07d6e6f2799d.png">

### Expected Behavior

Scanning an image must bring a report inside a table showing the numbers and levels of vulnerabilities found

### Rancher Desktop Version

1.6.0-525-g675b482e

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Based on similar tests, this works on Windows & Linux so this looks macos specific (at least on Intel).

**Comment by gaktive** [comment]
On M1, the behaviour is different but nothing is still shown.

**Comment by gaktive** [comment]
From what was encountered, if the image has a lot of vulnerabilities to scan, it takes a long time to bring this up.

This is already known existing behaviour so we'll wait to see if this needs to be documented in some fashion.

**Comment by ericpromislow** [comment]
Will be handled in #3595
