### ISSUE TITLE
Failing to deploy a k3s cluster while using Rancher Desktop offline

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3610]
### Actual Behavior

After pulling an image locally while online, user is not being able to deploy a cluster from the same image while offline.

### Steps to Reproduce

1. Launch Rancher Desktop
2. Pull an image from docker hub while online
`docker pull nginx:stable`
3. Disconnect the network to run Rancher Desktop offline
4. Deploy k8s clusters from these cached images
`kubectl create deployment nginx-test --image=nginx:stable`
`kubectl create service clusterip nginx-test --tcp=5000:80`
Check if the pods were deployed with:
`kubectl get pods -A`

### Result

Clusters are being pulled with an error while offline.
![Screen Shot 2022-12-12 at 4 47 44 PM](https://user-images.githubusercontent.com/70187881/207140161-dbe02631-8fd2-49a8-a489-b9bc8109cc05.png)

### Expected Behavior

User should be able to deploy a cluster from an image saved locally while online

### Rancher Desktop Version

1.6.0-525-g675b482e

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
You're using `nginx:latest`; the test steps specify `nginx:stable`. This is because Kubernetes defaults to `imagePullPolicy`: `Always` for `latest`, and `IfNotPresent` for anything else.

**Comment by IsaSih** [comment]
Indeed it was my mistake pulling the image with a different tag
