### ISSUE TITLE
Commit b80b7cc0 breaks dev builds: 

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3625]
### Actual Behavior

On startup, after `git clean -ffdx && npm i && npm run dev`:

```
2022-12-13T21:47:01.347Z: Lima: executing: sudo /sbin/rc-service --ifnotstarted docker start: Error: /home/ericp/workspace/rancher/desktop/resources/linux/lima/bin/limactl exited with code 1
2022-12-13T21:47:01.347Z: Error starting lima: Error: /home/ericp/workspace/rancher/desktop/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/home/ericp/workspace/rancher/desktop/dist/app/background.js:56102:27)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: '',
  stderr: 'nginx: [emerg] open() "/usr/local/openresty/nginx/conf/image-allow-list.conf" failed (2: No such file or directory) in /usr/local/openresty/nginx/conf/nginx.conf:60\n' +
    'nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed\n' +
    ' * ERROR: openresty failed to start\n' +
    ' * ERROR: cannot start docker as openresty would not start\n',
  code: 1,
  command: [
    '/home/ericp/workspace/rancher/desktop/resources/linux/lima/bin/limactl',
    'shell',
    '--workdir=.',
    '0',
    'sudo',
    '/sbin/rc-service',
    '--ifnotstarted',
    'docker',
    'start'
  ]
}
```

### Additional Information

Looks like whatever mangling is supposed to be happening on the startup scripts `/etc/init.d/{containerd,docker}` isn't.

### Rancher Desktop Version

1.7.0dev

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

linux

### Operating System / Build Version

ubuntu/suse/doesn't matter

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by ericpromislow** [comment]
Workaround: needs a factory-reset (ok to keep k8s images)

**Comment by jandubois** [comment]
The only way I can see this error happening is when you started with a VM that had an older `/etc/init.d/docker` script that still included `needs openresty`.

In the latest version openresty is only started "manually" when the corresponding config files have been written, so the situation above cannot occur.

**Comment by ericpromislow** [comment]
Verified this only happens when using VMs built with earlier RCs for 1.7.0 -- not a problem when moving from 1.6.x
