### ISSUE TITLE
Update docs links to new server structure: ranchermanager.docs.rancher.com

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#3626]
### Problem Description

Marketing has made changes to their URL structure for docs so the old `.rancher.io` link has redirects in place to point to the new `docs.rancher.com` setup. However, redirects will only be for existing material so anything else we add will need to the new domain.

### Proposed Solution

Find all links to `docs.ranchermanager.rancher.io` and change them to `ranchermanager.docs.rancher.com`. This likely will be purely in the UI but there may be backend, CLI and other references to look for.

**Comment by jandubois** [comment]
> Find all links to docs.ranchermanager.rancher.io

There aren't any, afaict (and I just searched for `ranchermanager`, not even the full URL). I also checked the `docs.rancherdesktop.io` repo as well as the `dashboard` and `steve` repos.

Closing this for now. Re-open if you know where these elusive links are hiding.

**Comment by gaktive** [comment]
@gunamata FYI. Maybe we need to have a ticket in the docs repo instead to check there.

**Comment by jandubois** [comment]
> Maybe we need to have a ticket in the docs repo instead to check there.

If you are talking about https://github.com/rancher-sandbox/docs.rancherdesktop.io, then I checked that one too, and got not hits.

**Comment by gunamata** [comment]
yes, we don't have any references to docs.ranchermanager.rancher.io on docs either. However, while searching for this I realized we do have some rancher.com/* urls that we need to update. I will file a PR for the same.
