### ISSUE TITLE
Kubernetes fails to launch - mac M1

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3630]
### Actual Behavior

After installing, launching Rancher Desktop and defining a kubernetes version in the first-run dialog, kubernetes encounters an error. From the logs, it seems to fail in reading cached version data and fails to download the tarball for the selected version. 

### Steps to Reproduce

1. Fresh install Rancher Desktop on a mac M1
2. Select a kubernetes version in the first-run dialog (in this case, 1.25.4)
3. Wait for the setup to finish
4. Check the kubernetes status

### Result

[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/10230627/k8s.log)
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/10230635/background.log)
[server.log](https://github.com/rancher-sandbox/rancher-desktop/files/10230656/server.log)
[lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/10230657/lima.log)
[networking.log](https://github.com/rancher-sandbox/rancher-desktop/files/10230658/networking.log)

### Expected Behavior

Kubernetes must start with no errors and must be able to read cached version data. Rancher Desktop must download the selected kubernetes version with no errors.

### Rancher Desktop Version

1.6.0-543-g85e9ec25

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
@ml8mr to try a quick repro on his M1.

**Comment by gaktive** [comment]
We weren't able to reproduce this consistently so this needs some more investigation. It looks like there are cases whereby the download is compressed so this is intermittent.

We may have to release note to clear the .tar file in the cache to force another download, which should then pull the .zst properly.

**Comment by miguelsmuller** [comment]
I'm having the same problem here.
but it's not a fresh install.
it was working and stopped working.
kubernetes is disabled

![image](https://user-images.githubusercontent.com/4589909/207714973-12c6dae7-3fbf-4bcb-b99f-e56bcf52f51a.png)
![image](https://user-images.githubusercontent.com/4589909/207715001-44cb868e-e6a0-440b-a2a0-2694f834e711.png)

**Comment by jandubois** [comment]
> We may have to release note to clear the .tar file in the cache to force another download, which should then pull the .zst properly.

I don't understand this; the code load either the uncompressed or the compressed image, so it shouldn't matter which one already exists in the cache.

**Comment by jandubois** [comment]
@miguelsmuller:

> I'm having the same problem here.
> but it's not a fresh install.
> it was working and stopped working.
> kubernetes is disabled

This sounds like a different problem; please file a separate Github issue for it!

**Comment by jandubois** [comment]
Just for the record: I've not been able to reproduce this on M1 machine with Ventura.

**Comment by miguelsmuller** [comment]
I thought it might be related issues. sorry about that @jandubois.
but I believe it has registered here (https://github.com/rancher-sandbox/rancher-desktop/issues/3137) as well and is the appropriate place.

**Comment by miguelsmuller** [comment]
I solved my problem by reinstalling rancher desktop

**Comment by ulm0** [comment]
It might not be related, but i'm having a similar issue, RD (v1.7.0) is unable to run the VM on M1

```sh
'time="2023-01-23T15:41:26-03:00" level=fatal msg="instance name \\"0\\" too long: \\"/Users/ulm0/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456\\" must be less than UNIX_PATH_MAX=104 characters, but is 106"\n',
  code: 1,
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl',
    'start',
    '--tty=false',
    '/Users/ulm0/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ]
}
```

**Comment by jandubois** [comment]
@ulm0 I assume you edited the error message, as the string length isn't actually 106 characters:

```console
$ echo /Users/ulm0/Library/Application Support/rancher-desktop/lima/0/ssh.sock.1234567890123456 | wc -c
      89
```

So assuming you modified the username, you are probably running into #797, and there is a workaround in https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877

**Comment by gaktive** [comment]
@IsaSih are you still able to repro this? No one else has so we're leaning towards closing this.

**Comment by IsaSih** [comment]
Was not able to reproduce with version 1.7.0
