### ISSUE TITLE
Traefik not coming up upon disable/renable all the time with 1.7.0 RC3

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#3634]
### Actual Behavior

Based on some test results, disabling Traefik and re-enabling doesn't bring up something that listens. "Connection refused"

### Steps to Reproduce

- Navigate to "Preferences then to ''Kubernetes tab".
- Check Enable Traefik
- Run kubectl get pods -A
- (mac/linux) curl http://localhost:80
- (mac/linux) curl -k https://localhost:443

Expected Results
Should see all traefik pods running and healthy
verify that curl commands give '404 page not found' output

### Result

Connection refused.

### Expected Behavior

404

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Everywhere!

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
While I observed once that Traefik was not being started again once it had been disabled once, I have not been able to reproduce this again, so I've lowered the priority and will move it to "Next".

**Comment by gaktive** [comment]
Need to check what happened here since this appears to have come via testing. However, we do have a BATS test now for Traefik so we can detect this going forward.

**Comment by gaktive** [comment]
The related test card was Passed in the test board so closing this for now, especially now that we have https://github.com/rancher-sandbox/rancher-desktop/pull/3896 in place with BATS to test Traefik.
