### ISSUE TITLE
Older intermediate files need to be culled

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#364]
On macos, my `~/Library/Application Support/rancher-desktop` dir is full of files named `.com.github.Electron.RANDOM` that are config files for `net.http_server_properties` (although many are empty). The `.com.github.Electron` comes from the default `CFBundleIdentifier` in the dev Info.plist file.

In our releases, `CFBundleIdentifier` is set to `io.rancherdesktop.app`, but for some reason I only have one of those files, created on May 4, 2021.

**Comment by gaktive** [comment]
Those files no longer appear in the install for macos, but we may have renamed files/folders. We should recheck.

**Comment by jandubois** [comment]
I cannot reproduce this
