### ISSUE TITLE
Address duplication of paths between `rdctl` and typescript `paths` module

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3652]
When factory reset functionality was moved into `rdctl`, this required duplication of the code Rancher Desktop uses to track which directories are used for what, i.e. config, application data and cache data. It isn't good to have more than a single source of truth, so this issue is about correcting this.

If I understood correctly, @jandubois suggested that we move this info into `rdctl`. We can then add a command to `rdctl` that outputs this info. This has two benefits:
1. The main application code can call this command on startup, thus giving it access to this info.
2. This gives the user access to a list of the paths that Rancher Desktop touches, which should more or less address #2710. We should be careful to be specific about this list though - is it a complete list of the paths that RD touches, or is it limited to the directories we need to delete when doing a factory reset (the latter would exclude things like `/var/run/docker.sock`)?

Another possibility is to introduce a static file that is incorporated, separately, in the builds for `rdctl` and the main application. This would be similar to `pkg/rancher-desktop/assets/dependencies.yaml`.

**Comment by mook-as** [comment]
Another possibility is to create another executable in `resources/<platform>/internal` that imports the same (golang) packages that `rdctl` does, and use that (without making it public API in the process).
