### ISSUE TITLE
WSL integration should install docker cli

### ISSUE THREAD

**Issue by OneCyrus** [rancher-sandbox/rancher-desktop#3677]
### Problem Description

when enabling docker integration for a WSL distribution docker cli might not be available.
![image](https://user-images.githubusercontent.com/7747800/209158538-c7438c68-1029-436f-989e-f8e0dc47eb44.png)

```
user@mysystem:~$ docker

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/
```

### Proposed Solution

install the docker cli when not already installed

**Comment by exfizik** [comment]
It's available for me when WSL2 integration is enabled. You just need to use `dockerd`. No separate installation of docker-cli was required.

**Comment by mook-as** [comment]
Note that we "install" the tools by adding the Linux binaries to your Windows `PATH`; so if you have turned off [`appendWindowsPath`](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) in `/etc/wsl.conf` you won't be able to find them. Trying to ensure we catch invocation of every distro to mount the executables in seems to error prone (though if you know of a good hook for us to do that, we'd appreciate the tip).

Additionally, Docker Desktop _does_ do that (or at least did at some point), and your error message sounds like you might have managed to invoke their executable instead; please check that that isn't the case?

**Comment by OneCyrus** [comment]
ok, you were right. both docker versions (Docker Desktop and Rancher Desktop) were in the PATH. The Docker Desktop one was just before the Rancher so it used this. I removed the Docker Desktop from the Path and it's hitting the Rancher Desktop docker now.

```
~$ which docker
/mnt/c/Users/abc/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/bin//docker
```

Unfortunately I get this error now from another WSL distribution were docker cli is installed locally it works and shows the container. (unchecking and rechecking in the Rancher Desktop preferences didn't change anything)

```
~$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by mook-as** [comment]
For that you'll need to do one of two things:
- Run `docker` as `root`
- Create a `docker` group (as in, `groupadd` / `addgroup` or `yast users`, etc.) and make sure your user is in that group.

This is the same as running dockerd on a normal Linux machine (as in, not part of WSL).

**Comment by jandubois** [comment]
> For that you'll need to do one of two things:

I don't think this should be required and have created #3899 to make the socket automatically writable.

I've also create #3898 to show a diagnostic when the Rancher Desktop version of `docker` is shadowed on the `PATH` by another version.

There seems to be nothing else actionable in this issue, so closing it.
