### ISSUE TITLE
Apple Silicon download contains INTEL version.

### ISSUE THREAD

**Issue by matziuul** [rancher-sandbox/rancher-desktop#3695]
### Actual Behavior

The downloaded file should contain the apple silicon version.

### Steps to Reproduce

Download file, install, get info on rancher desktop and it says INTEL.

### Result

<img width="234" alt="image" src="https://user-images.githubusercontent.com/75581438/210378657-44417dbe-6e4e-4e5a-a7f9-854050cc1d0d.png">

### Expected Behavior

It should contain the ARM/Apple Silicon version

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

Kubernets disabled

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Ventura 13.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> Download file, install, get info on rancher desktop and it says INTEL.

This happens because the Electron GUI part of the app is still the Intel version. All the virtual machine code etc are native though, so there should be very little performance impact.

We already have #1416 to track changing the Electron app to ARM code as well, so I'm closing this as a duplicate.
