### ISSUE TITLE
Update to Lima 0.14.X line of Lima

### ISSUE THREAD

**Issue by a1flecke** [rancher-sandbox/rancher-desktop#3702]
### Problem Description

Rancher Desktop is using an old version of Lima that does not support MacOS Ventura's Virtualization Framework.  This has resulted in a significant performance hit when we switched to Rancher Desktop from Docker Desktop.

### Proposed Solution

Update Rancher Desktop to a recent version of Lima (currently 0.14.2)

**Comment by ryancurrah** [comment]
Duplicate of https://github.com/rancher-sandbox/rancher-desktop/issues/3488
