### ISSUE TITLE
Where are the Linux instructions?

### ISSUE THREAD

**Issue by tgeek77** [rancher-sandbox/rancher-desktop#371]
> Rancher can be built from source on macOS or Windows. Cross-compilation is currently not supported.

I would think that since SUSE is a Linux company, SUSE/openSUSE would be the primary platform.

**Comment by jandubois** [comment]
> I would think that since SUSE is a Linux company, SUSE/openSUSE would be the primary platform.

Well, k3s runs natively on openSUSE, so you can install it as easily as

```
curl -sfL https://get.k3s.io | sh -
```

macOS and Windows need to run Linux inside a VM, install k3s inside there, and then forward ports to the local host. So those systems need a lot more work to get started. Think of all the corporate developers stuck on a Windows or Mac laptop; they need our help the most... 😄 

That being said, we are currently investigating demand for a Linux version of Rancher Desktop. This may also become easier to implement once we move from a macOS-specific hypervisor to qemu.

BTW, I think it would be better to think of SUSE as an Open Source company, not just a Linux company. Linux is obviously the core platform, but SUSE tries to meet customers/user needs, wherever they are.
