### ISSUE TITLE
Fail to start rancher desktop. Facing  Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1.

### ISSUE THREAD

**Issue by claraisrael** [rancher-sandbox/rancher-desktop#3716]
### Actual Behavior

I just installed rancher desktop and it is failing to start. Initially, I faced an error due to the limitation of the length of my username (This length must be less than 104 for Rancher Desktop to work correctly). After this, I ran `$ mv ~/Library/Application\ Support/rancher-desktop/lima ~/.rdlima
$ ln -s ~/.rdlima ~/Library/Application\ Support/rancher-desktop/lima` . This seemed to solve the issue, although after restarting RD I got the following error: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1. 
Last command run:
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl start --tty=false /Users/clara_israel_chocron/Library/Application Support/rancher-desktop/lima/_config/0.yaml

Context:
Starting virtual machine

Some recent [logfile](app://./index.html#) lines:
  stderr: 'time="2023-01-05T18:21:58+01:00" level=fatal msg="open /Users/clara_israel_chocron/Library/Application Support/rancher-desktop/lima/_config/0.yaml: no such file or directory"\n',
  code: 1,
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl',
    'start',
    '--tty=false',
    '/Users/clara_israel_chocron/Library/Application Support/rancher-desktop/lima/_config/0.yaml'
  ]
}

Mac information:
<img width="268" alt="Screenshot 2023-01-05 at 19 34 21" src="https://user-images.githubusercontent.com/117909790/211273196-0f1f25ab-b3a7-4d1c-bb71-b0b6d55bd371.png">

### Steps to Reproduce

1. Download Rancher Desktop (RD) [Rancher.Desktop-1.7.0.x86_64.dmg](https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.7.0/Rancher.Desktop-1.7.0.x86_64.dmg) from the release page.
2. Start RD, first face initial issue: ["Starting virtual machine" step fails due to SSH socket path being too long. ](https://github.com/rancher-sandbox/rancher-desktop/issues/797). Which was solved by running: 
$ mv ~/Library/Application\ Support/rancher-desktop/lima ~/.rdlima
$ ln -s ~/.rdlima ~/Library/Application\ Support/rancher-desktop/lima

3. Once that was solved, I restarted RD and faced Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1.

### Result

Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1.

Fail to Start Virtual Machine

### Expected Behavior

Start RD without any issues

### Additional Information

Please for more information find attached a zip with the log files (in ~/Library/Logs/rancher-desktop). 
[rancher-desktop 2.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10371811/rancher-desktop.2.zip)
<img width="273" alt="Screenshot 2023-01-09 at 09 16 29" src="https://user-images.githubusercontent.com/117909790/211274761-e5a70a36-6961-4cbb-b6dd-db7dc45bceb7.png">
<img width="760" alt="Screenshot 2023-01-09 at 09 16 48" src="https://user-images.githubusercontent.com/117909790/211274802-c4bc725e-214c-4571-8965-db2c28b927ec.png">

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

1.25.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by ericpromislow** [comment]
I'm now getting a different error (with a username that's 34-characters long):

I get a permission-denied error while starting up the VM. Pretty sure this error is coming from `lima` itself, because the text it emits isn't in our code.

```
{"level":"debug","msg":"executing script \"ssh\"","time":"2023-01-09T13:37:01-08:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/earlybirdjonathanwaggedornthethird/.rdlima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=earlybirdjonathanwaggedornthethird -o ControlMaster=auto -o ControlPath=\"/Users/earlybirdjonathanwaggedornthethird/.rdlima/0/ssh.sock\" -o ControlPersist=5m -p 59897 127.0.0.1 -- /bin/bash]","time":"2023-01-09T13:37:01-08:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"earlybirdjonathanwaggedornthethird@127.0.0.1: Permission denied (publickey,password,keyboard-interactive).\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"earlybirdjonathanwaggedornthethird@127.0.0.1: Permission denied (publickey,password,keyboard-interactive).\\r\\n\": exit status 255","time":"2023-01-09T13:37:01-08:00"}
```

**Comment by ericpromislow** [comment]
Incidentally, you realize that after every factory reset we need to recreate the symlink to `~/.rdlima`...

**Comment by claraisrael** [comment]
Is there any solution on how I can fix lima?

**Comment by ericpromislow** [comment]
I would retry again... I created an account on a macOS machine with the same username, and had no problems. (There's a separate problem going on with the Earl J. Waggedorn username, but let's ignore that for now).

So I would do the following:
```
* Either in the UI, run `Troubleshooting | Factory Reset` (you can keep the cached images), or from the command-line,
run `~/.rd/bin/rdctl factory-reset`
* Recreate the symlink:
```
mkdir -p ~/.rdlima 
mkdir -p ~/Library/Application\ Support/rancher-desktop/lima
ln -s ~/.rdlima ~/Library/Application\ Support/rancher-desktop/lima
```

Restart Rancher Desktop.

If it fails again, please reattach the log files. We're definitely trying to get you up and running.

**Comment by claraisrael** [comment]
[rancher-desktop 3.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10380759/rancher-desktop.3.zip)
Thanks for answering, unfortunately it hasn't worked out and I'm still running into the same issue. Please find attached the log files

**Comment by jevan68** [comment]
@claraisrael Downgrade to rancher desktop version 1.6.2 , than move the folders and create the symbolic link like you did before again. had the same issue with 1.7.

**Comment by claraisrael** [comment]
Fixed! Thank you!!

**Comment by rhuanlennon** [comment]
> Tentaria novamente... Criei uma conta em uma máquina macOS com o mesmo nome de usuário e não tive problemas. (Há um problema separado com o nome de usuário Earl J. Waggedorn, mas vamos ignorar isso por enquanto).
> 
> Então eu faria o seguinte:
> 
> ```
> * Either in the UI, run `Troubleshooting | Factory Reset` (you can keep the cached images), or from the command-line,
> run `~/.rd/bin/rdctl factory-reset`
> * Recreate the symlink:
> ```
> 
> mkdir -p ~/.rdlima mkdir -p ~/Library/Application\ Support/rancher-desktop/lima ln -s ~/.rdlima ~/Library/Application\ Support/rancher-desktop/lima
> 
> ```
> 
> Restart Rancher Desktop.
> 
> If it fails again, please reattach the log files. We're definitely trying to get you up and running.
> ```

I had the same problem and this solved it thanks
