### ISSUE TITLE
Waiting for Kubernetes API

### ISSUE THREAD

**Issue by lambdakris** [rancher-sandbox/rancher-desktop#3717]
### Actual Behavior

Rancher Desktop hangs with the message "Waiting for Kubernetes API"

### Steps to Reproduce

Launch Rancher Desktop

### Result

Rancher Desktop hangs with the message "Waiting for Kubernetes API"

### Expected Behavior

Rancher Desktop finishes loading

### Additional Information

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10374528/logs.zip)

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

1.25

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2 19044.2364

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

None

**Comment by gunamata** [comment]
@lambdakris, The logs folder you uploaded is empty. If you are still facing the problem, Can you please share the error screenshot and logs files?

**Comment by lambdakris** [comment]
Hey @gunamata , sorry about the logs but thanks for following up. I did a full reset the next day and the problem hasn't re-occurred as of yet. I'll go ahead and close.
