### ISSUE TITLE
Migrate to yarn package manager

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3723]
Rancher Dashboard and Shell both depend on yarn. Areas that will need to be addressed

- [x] Resolve build warnings/error that arise as a result of the change of tooling
- [x] Update developer documentation
- [x] Update CI/CD steps

> Additionally, please file an issue to move to `yarn` (if `@rancher/shell` is already using it) so that we match tools.
> 
> _Originally posted by @mook-as in https://github.com/rancher-sandbox/rancher-desktop/pull/3696#pullrequestreview-1241335752_

**Comment by RihanArfan** [comment]
Out of curiosity, how comes Yarn and not pnpm?

**Comment by rak-phillip** [comment]
A large motivator for moving to yarn is to keep our tooling aligned with Rancher Manager.
