### ISSUE TITLE
Fix E2E timeout failures

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#3724]
### Actual Behavior

It's possible that the work in https://github.com/rancher-sandbox/rancher-desktop/issues/3669 will address this (making this a possible duplicate) but our CI regularly has timeouts when going through E2E. We need to figure out why in most cases, a rerun clears this.

### Steps to Reproduce

Run CI.

### Result

Not sure if this is one of the common errors but https://github.com/rancher-sandbox/rancher-desktop/pull/3670/checks?check_run_id=10533392980 shows the result of an E2E failure on a PR.

### Expected Behavior

More reliable CI 

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

any

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Catalina

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Maybe the most recent Playwright bump will help iron this out somewhat but we need to see what's happening in the actual CI run with additional dialogue boxes popping up.

**Comment by jandubois** [comment]
Seems to be fixed by #3844
