### ISSUE TITLE
The k3s cache is empty and there is no network connection.

### ISSUE THREAD

**Issue by typ431127** [rancher-sandbox/rancher-desktop#3741]
### Actual Behavior

Rancher reports an error during startup

### Steps to Reproduce

Just start and report an error

### Result

![image](https://user-images.githubusercontent.com/20376675/211742579-3dbba233-d22d-45b1-9164-3731cd220931.png)

### Expected Behavior

-

### Additional Information

![image](https://user-images.githubusercontent.com/20376675/211742657-f0de9734-2377-4492-84d5-55a000cf6df7.png)
![image](https://user-images.githubusercontent.com/20376675/211742693-598f00df-69f7-4ac6-a25b-72403fa92eca.png)
![Uploading image.png…]()

### Rancher Desktop Version

20.10.21

### Rancher Desktop K8s Version

1.70

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows Feature Experience Pack 120.2212.4190.0

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
Thank you for the bug report! However, there's nothing we can do beyond the error message you already have, other than may be point you at [the documentation for running offline](https://docs.rancherdesktop.io/how-to-guides/running-air-gapped).

Given your GitHub user profile location, you may be behind the Great Firewall and may not be able to access GitHub directly (where we need to download things on startup); you may need to resolve that first.

**Comment by typ431127** [comment]
> 感谢您的错误报告！但是，除了您已经收到的错误消息之外，我们无能为力，除了可能会向您指出[running offline 的文档](https://docs.rancherdesktop.io/how-to-guides/running-air-gapped)。
> 
> 考虑到你的 GitHub 用户配置文件位置，你可能在防火墙后面，可能无法直接访问 GitHub（我们需要在启动时下载东西）；您可能需要先解决这个问题。

Thank you, I used Clash proxy Rancher to solve this problem and it works fine now
![image](https://user-images.githubusercontent.com/20376675/211993241-93742333-6a28-49be-aa5a-f0608a0aa2e2.png)
