### ISSUE TITLE
Implement `ReadDeploymentProfile` function for Linux [2d]

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3749]
The storage format for deployment profiles on Linux will be just the JSON representation, so can be just a copy of the `settings.json` file.

The location will be:

* System: `/etc/rancher-desktop/profile/defaults.json`
* System: `/etc/rancher-desktop/profile/locked.json`
* User: `~/.config/rancher-desktop/profile/defaults.json`
* User: `~/.config/rancher-desktop/profile/locked.json`

`ReadDeploymentProfile` will first attempt to read the system profile, and if that does not exist, the user profile, and return it as a settings object.

If either the `defaults.json` or `locked.json` file exists in the systems profile, then only the system profile is used, and any user profile settings are ignored.

If the profile is in an invalid format, then we show an error dialog and prevent the app from starting.

`ReadDeploymentProfile` must filter out any fields that are not part of the v5 schema. Otherwise the user/admin could add a rogue `locked` attribute that would cause the `settings.load` function to always overwrite the user value with the profile value.

Note: Allowed Images List is the only lockable property for now.

**Comment by dpmerrill** [comment]
Fixed by #3972
