### ISSUE TITLE
Implement `ReadDeploymentProfile` function for Windows [5d]

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3750]
The storage format for deployment profiles on Windows will be registry settings.

The root of the profile will be at:

* System: `HKEY_LOCAL_MACHINE\SOFTWARE\Rancher Desktop\Profile\Defaults`
* System: `HKEY_LOCAL_MACHINE\SOFTWARE\Rancher Desktop\Profile\Locked`
* User: `HKEY_CURRENT_USER\SOFTWARE\Rancher Desktop\Profile\Defaults`
* User: `HKEY_CURRENT_USER\SOFTWARE\Rancher Desktop\Profile\Locked`

### Mapping value types to registry types

* string → `REG_SZ`
* float → `REG_SZ` (we don't have any right now, and hopefully never will)
* int → `REG_DWORD`
* bool → `REG_DWORD` (`0` is `false` and `1` is `true`)
* list → `REG_MULTI_SZ`
* map → `REG_SZ` or `REG_DWORD` (using keys as `lpValueName`)

Except for maps, all values use the "default value" (`lpValueName` being the empty string). Maps store the various values under their respective key names.

**Comment by dpmerrill** [comment]
Fixed by #3972
