### ISSUE TITLE
Implement `ReadDeploymentProfile` function for macOS [1d]

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3751]
The storage format for deployment profiles on macOS will be the "property list" format (an XML format that can be compressed into a binary version).

You can easily convert our JSON data into a property list:

```console
$ plutil -convert xml1 ~/Library/Preferences/rancher-desktop/settings.json -o -
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>containerEngine</key>
	<dict>
		<key>imageAllowList</key>
		<dict>
			<key>enabled</key>
			<false/>
			<key>locked</key>
			<false/>
			<key>patterns</key>
			<array/>
		</dict>
	</dict>
```

`plutil` can also be used to convert a plist file to JSON (for the subset of plist files whose schema is representable in JSON):

```console
plutil -convert json -r -o profile.json io.rancherdesktop.profile.plist
```

The `-r` option is for pretty-printing, so not needed for `ReadDeploymentProfile`.

The location will be:

* System: `/Library/Preferences/io.rancherdesktop.profile.defaults.plist`
* System: `/Library/Preferences/io.rancherdesktop.profile.locked.plist`
* User: `~/Library/Preferences/io.rancherdesktop.profile.defaults.plist`
* User: `~/Library/Preferences/io.rancherdesktop.profile.locked.plist`

**Comment by dpmerrill** [comment]
Fixed by #3972
