### ISSUE TITLE
Implement new `/v1` API version for version 5 settings format [5d]

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3756]
We need to bump our API version to `/v1` because the `settings` API will be changed in an incompatible way.

All `/v0` endpoints should now return an error. We don't want implement the `GET` method for `/v0/settings` (`PUT` alone is simple because we need migration code for updates anyways).

The PUT method for the `/v1/settings` endpoint will return an error when the call attempts to modify any structure that (directly, or via its parents) has a `locked` attribute that is set to `true` in the current settings.

I.e. you cannot modify `containerEngine.allowedImages.enabled` if `containerEngine.allowedImages.locked` is currently `true`.

We require that every `PUT` request of the `/v1/settings` endpoint includes the `version: 5` field in the request body. That way we could make further changes to the settings layout in the future without having to bump the API version every time.

# Acceptance criteria

* All `/v0` endpoints return an error - run `rdctl api /v0/settings` should bring an error
* The `/v1/settings` endpoint supports the new v5 schema for both `GET` and `PUT`
* The `PUT` method for `/v1/settings` returns an error unless the `version` field exists and has the value `5`.

  ```
  rdctl api -X PUT -b '{"version":5,"containerEngine":{"imageAllowList":{"enabled":true,"patterns":["a","b"]}}}' /v1/settings
  ```

# Release Notes:

**Comment by ericpromislow** [comment]
`locked` field checking will be done as part of issue #3862

**Comment by mook-as** [comment]
> We require that every `PUT` request of the `/v1/settings` endpoint includes the `version: 5` field in the request body. That way we could make further changes to the settings layout in the future without having to bump the API version every time.

That makes posting things from the command line (interactively) very annoying. Could we just drop the requirement and just complain if the schema doesn't match? We don't need to do any migration there (since we _already_ don't support older versions of the API).  If the user cares (in a script or something) they can fetch the current settings version first?

**Comment by jandubois** [comment]
> That makes posting things from the command line (interactively) very annoying.

There should be very little need to change settings via `rdctl api` because we now expose **all** settings via `rdctl set` (yes, map and list settings are not yet implemented).

So I don't think passing the `version` field in `rdctl api` request is such a big deal.
