### ISSUE TITLE
Javascript error on macOS

### ISSUE THREAD

**Issue by lucj** [rancher-sandbox/rancher-desktop#376]
I'm a happy user of Rancher Desktop on MacOS. This is working fine but I suddenly got this error message (cf screenshot). I guess this is only related to the frontend as the cluster still seems to work correctly.

<img width="416" alt="Capture d’écran 2021-06-22 à 11 02 31" src="https://user-images.githubusercontent.com/182406/122993572-c0a57480-d3a7-11eb-88d6-dcc58d2548cb.png">

**Comment by mook-as** [comment]
See docs on [`EMFILE`](https://developer.apple.com/documentation/foundation/posixerror/2293079-emfile) — there's too many open files.  This possibly means we have a file handle leak somewhere, and we haven't noticed because we're not keeping RD running long enough to see it.

**Comment by ericpromislow** [comment]
Superseded by #377
