### ISSUE TITLE
Auto-start option on Windows [2d]

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3769]
Implement the option to automatically start Rancher Desktop during login on Windows.

This may be as easy as running (with the proper path to the executable):

```console
C:\Users\Jan>reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Run /v RancherDesktop /d "C:\Program Files\Rancher Desktop\Rancher Desktop.exe"
The operation completed successfully.
```

Use the `query` command to query the current setting:

```console
C:\Users\Jan>reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Run /v RancherDesktop

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
    RancherDesktop    REG_SZ    C:\Program Files\Rancher Desktop\Rancher Desktop.exe
```

And the `delete` command to remove the setting:

```console
C:\Users\Jan>reg delete HKCU\Software\Microsoft\Windows\CurrentVersion\Run /f /v RancherDesktop
The operation completed successfully.

C:\Users\Jan>reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Run /v RancherDesktop


ERROR: The system was unable to find the specified registry key or value.
```

# Add auto-start configuration subcommand to `rdctl`

`rdctl` needs to be able to disable the autostart setting when it is performing a factory reset. Therefore it makes sense that the configuration of auto-start should also be performed by `rdctl`.

The commands to enable and disable auto-start are:

```shell
rdctl setup --application.auto-start=true
rdctl setup --application.auto-start=false
```

This mirrors the `rdctl set --application.auto-start=true`, which the user should be using for all preference settings. A subset will be implemented via `rdctl setup`, when their functionality is also required by `rdctl factory-reset`. So another candidate for this subcommand is going to be `rdctl setup --application.path-setting=manual`.

# Acceptance Criteria

* Verify that auto-start works
  * Enable auto-start
  * Log out
  * Log back in
  * Wait a minute and verify that Rancher Desktop starts automatically
  * Disable auto-start
  * Log out
  * Log back in
  * Wait a few minutes and check the Task Manager to make sure Rancher Desktop does not start automatically

* Verify that factory-reset removes the auto-start configuration
  * Enable auto-start
  * Run factory reset
  * Use `reg query` to confirm the registry entry has been deleted

**Comment by adamkpickering** [comment]
Just a heads up: I think the location that RD is installed into depends on... something. Maybe the format used to install? My RD appears to be located at `C:\Users\adamk\AppData\Local\Programs\Rancher Desktop`.

**Comment by jandubois** [comment]
> Just a heads up: I think the location that RD is installed into depends on... something. 
> Maybe the format used to install?

It should depend on it being either a system or a user installation.

> My RD appears to be located at `C:\Users\adamk\AppData\Local\Programs\Rancher Desktop`.

That would be the user install location under `%LOCALAPPDATA%\Programs\Rancher Desktop`.

The system install location should be `%ProgramFiles%\Rancher Desktop`.

@mook-as Please confirm!

Not sure why this matters in this story; you should be able to get the app location via `electron.app.getAppPath()`.

**Comment by jandubois** [comment]
> Not sure why this matters in this story; you should be able to get the app location via electron.app.getAppPath().

Or from within `rdctl`, the path to the RD executable relative to the `rdctl` executable should be `..\..\..\..\Rancher Desktop.exe`.

**Comment by jandubois** [comment]
Just to be clear: none of this really works when you run via `npm run dev`, but we are not supporting auto-start for the dev setup, so don't worry about it. Just configure it as if it were a packaged release, and let it fail during login.

**Comment by mook-as** [comment]
> https://github.com/rancher-sandbox/rancher-desktop/issues/3769#issuecomment-1384619506

Yes, that sounds about correct. On Windows, RD is installed in `C:\Program Files\Rancher Desktop` (etc.) when using administrator privileges, or `C:\Users\<name>\AppData\Local\Programs\Rancher Desktop` (or something like that) when _not_ using administrator privileges.
