### ISSUE TITLE
Avoid unnecessarily polling `kim images`

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#377]
Related to #376

**Comment by mook-as** [comment]
Extra fun: Because we run an external binary (`kim.exe`) for this, on Windows by default Windows Defender (the bundled anti-virus system on Windows 20) will happily re-scan the executable every time; on my (physical) machine, this means a spike of about 20% CPU usage every five seconds…

**Comment by jandubois** [comment]
Does this happen because `kim.exe` has no signature? So it cannot cache the checking results?

**Comment by mook-as** [comment]
Possibly? Though even if it did, it'd still need to verify the signature, which is still a read of the executable.
