### ISSUE TITLE
 Error: wsl.exe exited with code 4294967295

### ISSUE THREAD

**Issue by espinoleandroo** [rancher-sandbox/rancher-desktop#3778]
### Actual Behavior

I've tried to install Rancher Desktop in my new laptop, so in my first attempt I downloaded the installer v1.7.0, I run the installer, it finished but never ask me the Kubernetes version and the container type, it was the first stranger thing, after that Rancher started and showed a window with the error 4294967295.

I've tried to install Rancher Desktop in different versions and using the WSL from Microsoft Windows and wsl_update_x64.msi with many combinations, but I always get the same error

### Steps to Reproduce

- Attempt 1
  - Install Rancher Desktop 1.7.0
  - I get the error

- Attempt 2
  - Uninstall Rancher Desktop 1.7.0
  - Reboot Windows
  - install wsl_update_x64.msi
  - Install Rancher Desktop 1.7.0
  - I get the error

- Attempt 3
  - Uninstall Rancher Desktop 1.7.0
  - Reboot Windows
  - install wsl from Microsoft store
  - Install Rancher Desktop 1.7.0
  - I get the error

- Attempt 4
  - Uninstall Rancher Desktop 1.7.0
  - Uninstall WSL from Microsoft store
  - Uninstall WSL from wsl_update_x64.msi
  - Reboot Windows
  - Install Rancher Desktop 1.6.2
  - I get the error

### Result

2023-01-13T22:43:35.809Z: WSL failed to execute wsl.exe --unregister rancher-desktop-data: Error: wsl.exe exited with code 4294967295
2023-01-13T22:43:35.810Z: Error setting up data distribution: Error: wsl.exe exited with code 4294967295
at ChildProcess.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:7721)
at ChildProcess.emit (node:events:390:28)
at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
code: 4294967295,
command: [ 'wsl.exe', '--unregister', 'rancher-desktop-data' ]
}
2023-01-13T22:43:36.106Z: WSL: executing: /bin/sh -c [ -e /etc/os-release ] && . /etc/os-release ; echo ${VERSION_ID:-0.1}: Error: wsl.exe exited with code 4294967295

### Expected Behavior

Run Rancher Desktop correctly with a kubernetes cluster

### Rancher Desktop Version

1.7.0 & 1.6.2

### Rancher Desktop K8s Version

1.21.14

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 21h2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gunamata** [comment]
@espinoleandroo, Is this the first time you are trying to install Rancher Desktop on your machine? Are you installing Rancher Desktop as an Administrator ?

Can you try below steps to clean uninstall existing installations and try again.

- Run `rdctl factory-reset`
- Uninstall Rancher Desktop from Windows `Programs & Features`
- Install Rancher Desktop using the MSI installer. The installation process will check whether WSL2 is available on your machine and if not, will install WSL2.

If you still see problems, Can you please share the application logs? You will find the logs at 
 `%USERPROFILE%\AppData\Local\rancher-desktop\logs`.

**Comment by espinoleandroo** [comment]
Hi! I've gotten other machine, and the installation was successfully, I think that de problem was the machine, but now I can't access to the logs of the first machine to shared you, sorry.
Do I close de issue?

**Comment by jandubois** [comment]
> I can't access to the logs of the first machine to shared you
> Do I close de issue?

Yes, without access to the logs there isn't really anything we can do anymore, so closing it now.
