### ISSUE TITLE
Make kubectl and helm optional

### ISSUE THREAD

**Issue by Boeller666** [rancher-sandbox/rancher-desktop#3787]
### Problem Description

I had problems with kubectl (gcp auth plugin changes) and helm (plugin upgrades), because my shell always uses the Rancher Desktop versions instead the installed ones beside.

### Proposed Solution

Option to disable kubectl and helm in Rancher Desktop to use the already installed versions.

**Comment by jandubois** [comment]
The way to do this is to set the `PATH` management to "Manual" and then edit your shell config file to add `$HOME/.rd/bin` at the end. The "Automatic" mode prepends it at the front, and so takes precedence over all other locations.
