### ISSUE TITLE
Upgrade to electron 22

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3788]
Upgrading to electron 22 works on macOS and Linux, but fails on Windows. We need to find an appropriate solution that that will allow us to continue updating electron. 

> The patch on the bump works on macos and linux, but fails to build on Windows, because of a non-windows option PYTHON=python3 added to the install script in the module's package.json file.
> 
> The @inigolabs/ffi-napi doesn't seem to be in a github repo, but just code stored in npmjs.com, and I don't see bug issues or something similar there. The main contributor of this patch is also basically anonymous.

_Originally posted by @ericpromislow in https://github.com/rancher-sandbox/rancher-desktop/issues/3683#issuecomment-1370348958_

> Given the… opaqueness of this package, we should probably not use it. We may need to reconsider alternative ways to get the certificates (such as have a native executable that generates a tar file directly, instead of doing it from JS). :(

_Originally posted by @mook-as in https://github.com/rancher-sandbox/rancher-desktop/pull/3683#discussion_r1065150733_

**Comment by jandubois** [comment]
We have already updated to Electron 26 in #5620, so I think this issue can be closed @rak-phillip.
