### ISSUE TITLE
docker pull not working on rancher-desktop 1.7.0

### ISSUE THREAD

**Issue by andronachev** [rancher-sandbox/rancher-desktop#3795]
### Actual Behavior

Expected result: docker image for postgres is pulled 
Actual result: error **Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**

### Steps to Reproduce

1) install rancher-desktop 1.7.0 
2) open, configure (kubernetes disabled, container engine: dockered) 
3) rancher-desktop starts, default images visible in the images tab 
4) open CMD 
5) command : docker pull postgres

### Result

Expected result: docker image for postgres is pulled 
Actual result: error **Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**

![image](https://user-images.githubusercontent.com/16139612/213107203-01127100-e1c3-4382-b7f3-33e1b32fd5dd.png)

### Expected Behavior

Expected result: docker image for postgres is pulled 

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

-

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 19042.2364

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gunamata** [comment]
@andronachev , This looks like a issue related to using Rancher Desktop with some VPN environments/clients as reported on https://github.com/rancher-sandbox/rancher-desktop/issues/2477, https://github.com/rancher-sandbox/rancher-desktop/issues/3091

Can you please try the workaround suggested on the thread? https://github.com/rancher-sandbox/rancher-desktop/issues/3091#issuecomment-1268931636

**Comment by andronachev** [comment]
Hi @gunamata  @gaktive  thanks for the reply, however this is happening also when not connected to VPN, I will have a look over those other tickets and workaround

**Comment by jithurjacob** [comment]
@andronachev - Did you try [wsl-vpnkit](https://github.com/sakai135/wsl-vpnkit)?

**Comment by Findaa** [comment]
Same issue here:

- Rancher desktop v: Version: 1.9.0
- Kubernetes v: Tried both 1.23.17 and 1.27.3
- Specs: m2 pro, ventura 13.3

I cant pull with docker-compose, docker, using rancher desktop ui. 

Helm charts work.

@gaktive I see you added Windows platform tag here, should osx be added too or does that require another issue?

**Comment by stevo-knievo** [comment]
Same issue here - I can't pull a docker image.

- macOS:  13.4.1 (22F82)
- chip: M2
- Rancher desktop, v: 1.9.0 (dockerd (moby), Kubernetes disabled)

```shell
docker pull postgres
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.5.3:53: read udp 192.168.5.15:41317->192.168.5.3:53: i/o timeout
```

**Comment by alexshin** [comment]
I fixed this issue by adding "nameserver 8.8.8.8" to resolv.conf of host VM. 

Steps are:

Go to CLI in VM
```bash
rdctl shell bash
```

Add DNS to nameservers:
```bash
sudo vi /etc/resolv.conf
# add nameserver 8.8.8.8 or nameserver 1.1.1.1 or anything else

exit
```

reboot Racherdesktop

This works for me

**Comment by 62mkv** [comment]
I have Rancher Desktop 1.10.0 installed under Windows 10. Same issue here, any attempt to pull image ends up with 

```
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 3.216.34.172:443: i/o timeout.
See 'docker run --help'.
```

I open WSL VM CLI with `wsl --distribution rancher-desktop`

When trying to run `rdctl shell bash`, I get `rdctl not found`. 

So, I just edit the `/etc/resolv.conf` to make it look like this: 

```
/ # cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 172.22.136.144
```

Saving this and exiting VM, I _can pull images_ ! But whenever I "Quit Rancher Desktop" and start it again; all my changes are gone and the issues are there. 

I seems to be the exact same issue there used to exist in Docker for Windows 3-4 years ago; where you had to manually configure some DNS-related configuration on the Windows host to persist it between VM restarts

**Comment by AqlaSolutions** [comment]
Same issue here, version 1.11 for windows. Sometimes it stops working until I restart Windows. I can't turn off VPN because our docker images should be downloaded through VPN.

**Comment by Nino-K** [comment]
This issue is addressed in our latest release. I'm going to close this issue, feel free to re-open it if you encounter anything further.

**Comment by nothing2obvi** [comment]
This is occurring for me on version 1.14.1.

**Comment by bedaberner** [comment]
Same for me

**Comment by gokhantepe** [comment]
@Nino-K Unfortunately, a similar error also occurs in version 1.14.2.

**Comment by learntimes** [comment]
version 1.16 
Error response from daemon: Get "https://registry-1.docker.io/v2/" ...

**Comment by RichardoC** [comment]
We've seen this happen on macOS 15.2 (24C101), Rancher Desktop Version 1.17.0 (1.17.0)

For now we're hacking around this with saving the following as `~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml` and then shutting down/starting up rancher desktop. The equivalent might work for Windows but you'll need to use the different path/etc in <https://docs.rancherdesktop.io/how-to-guides/increasing-open-file-limit>


``` yaml
# `system` is executed with the root privilege
provision:
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
```


Some folks were having issues where https://github.com/rancher-sandbox/rancher-desktop/issues/3795#issuecomment-1733474206 wouldn't stay saved.

**Comment by jamesmoss** [comment]
Ive tried @RichardoC's solution above but my `/etc/resolv.conf` reverts to `nameserver 192.168.5.2` after a period of time; I suspect when swapping between home and work networks.

**Comment by jandubois** [comment]
@jamesmoss There are changes in DNS handling in the upcoming 1.17.1 patch release. Please test with that version, once it is out, and if you still have problems with DNS, please file a new issue for it!

**Comment by mojogitoverhere** [comment]
I just ran into this issue on 1.17.1 and it also occurred when switching between different networks like @jamesmoss. Restarting the cluster fixed the issue.

**Comment by jamesmoss** [comment]
Yeah the problem still persists for me in 1.17.1. Using a VPN on the host also triggers the issue. A restart is the only way to resolve it.
