### ISSUE TITLE
Feature Request - Start/Stop Kubernetes button

### ISSUE THREAD

**Issue by akin-ozer** [rancher-sandbox/rancher-desktop#381]
You can start and quit rancher desktop to Start/Stop the Kubernetes server but I think there can be a button to manage this. Because we might need the resources of the machine itself for a period of time instead of Kubernetes and quitting app totally to achieve this can be counterintuitive.

**Comment by gaktive** [comment]
This could extend to running Rancher Desktop without k8s running so that we don't download a default k8s version until a user selects one and then we could pause k8s too.

**Comment by gaktive** [comment]
Related to #234 & #248

**Comment by SleepyBrett** [comment]
Trying to replace DockerDesktop w/ Rancher desktop I too would like a way to spin down the kube cluster at will to save resources while still having nerdctl/continerd access to build images etc.

**Comment by tanguyantoine** [comment]
There is a `Enable Kubernetes` setting now, sounds like what you are looking for, isn't it?

**Comment by jandubois** [comment]
I agree, this has been implemented
