### ISSUE TITLE
Find more compact layout for preferences tab

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3811]
IMO it would be great if we find a way to remove the `scrollbar`, like grouping the checkboxes to save space or creating a new tab.

I'm also in favour of grouping more options together under a single heading. I don't think the headings provide much value, especially if you have a separate heading for each option.

These headings also take up a lot of vertical space, so we really have low "density" in our settings tabs. I wonder if we could lay out labels in a separate column, so save some space (on pages that just have check boxes and dropdown lists). See e.g. (arbitrarily) from Safari:

<img width="880" alt="Screen Shot 2023-01-17 at 11 37 42 AM" src="https://user-images.githubusercontent.com/78947/212995992-d7482624-86a4-4cad-ad36-b8dc9a564c9c.png">

_Originally posted by @jandubois in https://github.com/rancher-sandbox/rancher-desktop/issues/3262#issuecomment-1385953455_

**Comment by kwwii** [comment]
@manuelecarlini Can you add any screens from the work you started?

**Comment by manuelecarlini** [comment]
<img width="827" alt="Screenshot 2023-02-07 at 11 36 53" src="https://user-images.githubusercontent.com/6459624/217234661-0aed7d3b-2999-42ac-990e-98770dee549c.png">
This is one of the options I've presented,
I'll share soon the prototype @kwwii

**Comment by manuelecarlini** [comment]
Here's the prototype for the proposals
[](https://xd.adobe.com/view/6d2adacd-cc7d-4ce6-819b-2d552d5f605a-3879/)

**Comment by mook-as** [comment]
Note that the icon-bar-at-top style is very macOS, whereas Windows is more likely to have an icon-bar-on-the-left.  Given how sparse our options are at the moment that might be an option.

**Comment by jandubois** [comment]
> more likely to have an icon-bar-on-the-left.

Having primary navigation on the left is already our consensus (for all platforms); we are now wondering if we should have tabs at all, or just a bar on the left. Unfortunately there are both pros and cons to both options, so it is not clear at all yet what might work best. @manuelecarlini is working on prototypes for that now.
