### ISSUE TITLE
Share `TMPDIR` with VM on macOS

### ISSUE THREAD

**Issue by jacobwoffenden** [rancher-sandbox/rancher-desktop#3820]
### Problem Description

I am trying to run a devcontainer feature test but it is failing (https://github.com/devcontainers/cli/issues/380) due to `/var/folders` not being shared on macOS.

### Proposed Solution

Share `TMPDIR` or `DARWIN_USER_TEMP_DIR` with VM

### Additional Information

N/A

**Comment by jandubois** [comment]
It seems like a good feature to just share the `TMPDIR` folder with the VM.

Right now you can configure the additional folder sharing with a Lima override file:

```
$ cat ~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml
mounts:
- location: /var/folders
  writable: true
```

Seems to work fine:

```console
$ echo Yay > $TMPDIR/test
$ rdctl shell cat $TMPDIR/test
Yay
```

**Comment by jacobwoffenden** [comment]
Thanks, @jandubois!
