### ISSUE TITLE
Add "Hide in Menu Bar" option for the notification icon [2d]

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3832]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/3770

<div type='discussions-op-text'>

<sup>Originally posted by **jandubois** January 12, 2023</sup>
It looks like macOS has this options for most of the system-provided menu bar items, and especially on a laptop the menu bar can get rather crowded without using e.g. [Bartender](https://www.macbartender.com).

# Acceptance Criteria
- From Preferences > Application > Behaviour, there has to be a checkbox with the option to "Hide in Menu Bar". Once clicked and after applying the changes, the value has to be set to true in settings.json and the Rancher Desktop icon will no longer be visible in the tray menu.
- Once unchecked, its value need to be set to false in settings.json and Rancher Desktop icon will be visible in the tray menu.</div>

**Comment by torchiaf** [comment]
We can close this issue since it is resolved in #3789. We change the name of new preference 'Hide in Menu Bar' to 'Hide notification Icon'

**Comment by jandubois** [comment]
> We can close this issue since it is resolved in #3789.

Sure. I guess #3789 was only marked to close this issue after it was already merged, so Github didn't close this one automatically.
