### ISSUE TITLE
Github Actions and Cirrus CI work on different source trees

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3845]
The Github Actions checkout perform a merge of the PR into the target branch, and then build and test the software from that merge commit.

The E2E test running on Cirrus-CI is building and testing directly on the PR branch and does not perform a merge.

**Comment by mook-as** [comment]
[Cirrus documentation](https://cirrus-ci.org/guide/tips-and-tricks/) has some clues on customizing clone behaviour; we just need to copy that and use `pull/$CIRRUS_PR/merge` instead of `pull/$CIRRUS_PR/head` to get the thing we want.

**Comment by mook-as** [comment]
This is obsolete — we no longer use Cirrus CI.
