### ISSUE TITLE
Rancher Desktop does not startup (Mac Ventura 13.1)

### ISSUE THREAD

**Issue by christopher-cudennec** [rancher-sandbox/rancher-desktop#3846]
### Actual Behavior

When I start Rancher Desktop I can see that the program is starting up. But I can't see the screen of Rancher Desktop but the startup seems to fail and the program stops.

### Steps to Reproduce

Start Rancher Desktop.

### Result

The application startup failed.

### Expected Behavior

The application starts and I can see Rancher Desktop's UI.

### Additional Information

I'm pretty sure that it works before I upgraded to Ventura 13.1.

I can see the following information in the `background.log`:

```
2023-01-26T07:24:41.857Z: mainEvents settings-update: {"version":4,"kubernetes":{"version":"1.23.6","memoryInGB":6,"numberCPUs":2,"port":6443,"containerEngine":"moby","checkForExistingKimBuilder":false,"enabled":true,"WSLIntegrations":{},"options":{"traefik":true,"flannel":true},"suppressSudo":false,"experimentalHostResolver":false,"hostResolver":true,"experimental":{"socketVMNet":false}},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"k8s.io"},"telemetry":true,"updater":true,"debug":false,"pathManagementStrategy":"rcfiles","diagnostics":{"showMuted":false,"mutedChecks":{}},"containerEngine":{"imageAllowList":{"enabled":false,"locked":false,"patterns":[]}}}
2023-01-26T07:24:41.952Z: Error starting up: [Error: EACCES: permission denied, unlink '/Users/christophercudennec/.docker/cli-plugins/docker-buildx'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/Users/christophercudennec/.docker/cli-plugins/docker-buildx'
}
```

I tried to uninstall using `brew uninstall rancher` and re-installed the latest version from the website. The application still does not start.

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

1.23.6 (?)

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by christopher-cudennec** [comment]
Oh, I managed to fix it by moving the `~/.docker` folder. That seems to fix the file access problem.
Leave the issue here if it helps anyone else.
Do you want to fix some startup routines or would you prefer to close the issue?

**Comment by gaktive** [comment]
Hi @christopher-cudennec 

Just for context, you had Rancher Desktop installed and working prior to upgrading to Ventura 13.1? Was it Ventura 13.0 or an earlier version? And where was the `~/.docker` folder originally and where did you move it to?

**Comment by christopher-cudennec** [comment]
Hi @gaktive !

> you had Rancher Desktop installed and working prior to upgrading to Ventura 13.1? Was it Ventura 13.0 or an earlier version? 

I updated from 13.0.1 to 13.1.

> And where was the ~/.docker folder originally and where did you move it to?

I moved `~/.docker` to `~/.docker_bak` because it was mentioned in the `background.log` (see above). After starting Rancher Desktop again `~/.docker` was recreated and the application could startup.

**Comment by jandubois** [comment]
@christopher-cudennec If you still have the `~/.docker_bak` directory, could you run these 3 commands (replace `.docker` with `.docker_bak`) and show the permission settings on the directories and files:

```console
$ ls -ld ~/.docker
drwx------  22 jan  staff  704 26 Jan 13:56 /Users/jan/.docker

$ ls -ld ~/.docker/cli-plugins
drwxr-xr-x  4 jan  staff  128 26 Jan 13:56 /Users/jan/.docker/cli-plugins

$ ls -l ~/.docker/cli-plugins
total 0
lrwxr-xr-x  1 jan  staff  32 26 Jan 13:56 docker-buildx -> /Users/jan/.rd/bin/docker-buildx
lrwxr-xr-x  1 jan  staff  33 26 Jan 13:56 docker-compose -> /Users/jan/.rd/bin/docker-compose
```

**Comment by christopher-cudennec** [comment]
Sure:
```
➜  ~ ls -ld .docker_bak
drwx------  11 christophercudennec  staff  352 17 Jun  2022 .docker_bak
➜  ~ ls -ld .docker_bak/cli-plugins
drwxr-xr-x  4 root  staff  128 22 Apr  2022 .docker_bak/cli-plugins
➜  ~ ls -l .docker_bak/cli-plugins
total 0
lrwxr-xr-x  1 root  staff  87 22 Apr  2022 docker-buildx -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-buildx
lrwxr-xr-x  1 root  staff  88 22 Apr  2022 docker-compose -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-compose
```

I guess that `root` looks suspicious. 😃

**Comment by jandubois** [comment]
> I guess that `root` looks suspicious. 😃

Indeed, it does. Did you ever run Rancher Desktop as `root`? We made a change in 1.7.0 to disallow this because that can cause various issues (like this one) if you then try to run Rancher Desktop again as a regular user (see #1560).

I guess we should try to trap the error and still continue to start the app, so I will be leaving this issue open.

**Comment by christopher-cudennec** [comment]
I see the following dialog when starting the application and allow admin privileges:

<img width="491" alt="grafik" src="https://user-images.githubusercontent.com/48206222/215026214-4fa79d92-1c4b-410b-ac09-0c552cd84358.png">

Will this setup the `.docker` directory with "root" privileges?

**Comment by jandubois** [comment]
> Will this setup the `.docker` directory with "root" privileges?

No, it will not. This will create a symlink for the Docker socket to the default location at `/var/run/docker.sock`, which allows you to use it without setting the docker context to `rancher-desktop`. It is also potentially needed to configure RD to create a bridged network interface, if you want to VM accessible from other machines on your local network.

But it will not create any files or directories under your `$HOME` directory as `root`. That can only happen (I think) if you run the app itself as `root`.

**Comment by christopher-cudennec** [comment]
I don't recall starting the app as root; I don't do that usually. That's not a guaranty though. 😄

**Comment by jandubois** [comment]
> I don't recall starting the app as root; I don't do that usually

Yeah, it seems unlikely, but it is the only explanation I can come up with to explain why the plugins directory is owned by `root`. If you ever find out that it happened a different way, please let us know.

There used to be a time when Rancher Desktop was installing utilities into `/usr/local/bin`, and by default that directory is owned by `root` (homebrew makes it owned/writable by the user). So some people recommended running Rancher Desktop as `root`, so it could install the supporting utilities in there. This has always been bad advice, and we should have prevented this much earlier; I would think nowadays nobody will do this anymore anyways.

**Comment by christopher-cudennec** [comment]
Thanks for all the support. Closing the issue.
