### ISSUE TITLE
port forward UI does not work

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#390]
The port forwarding UI does not appear to be opening any ports. For example, after using it I can run `nmap localhost` and not see the port displaying. Somewhere along the line this broke.

This should be fixed or pulled out if we have an alternative.

**Comment by jandubois** [comment]
Please specify the platform, in case the code is different between macOS and Windows.

> if we have an alternative.

After switching to lima all ports will automatically be forwarded to localhost (but not to the external interfaces).

**Comment by mook-as** [comment]
> I can run `nmap localhost` and not see the port displaying.

I assume this means it's on macOS.

Also, just tried to test on `main`, and I _can_ use `curl` to contact my forwarded port.

I'll not work on this until after lima, at least.
