### ISSUE TITLE
Enabling WSL integration sometimes doesn't "stick"

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3911]
I've enabled WSL in Preferences, and then switched between other preferences pages. When I went back to the WSL page, the selection sometimes got deselected again.

There was no repeatable sequence of actions to always reproduce this, but it happened several times.

**Comment by rak-phillip** [comment]
I can trace this behavior back to #3232, which is causing us to us to fetch the collection of WSL distributions a second time. Regardless of the behavior, this was intended to be designed in such a way that selections remain as new data comes in.
