### ISSUE TITLE
Traefik is not listening on port 80/443 on linux

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#3916]
Using 1.7.0 release of Rancher Desktop, it looks like that traefik is not listening on port `80` or `443` on the host side while it is enabled under settings. However, it is listening on those ports inside the VM.

**Comment by Nino-K** [comment]
@s0nea can we try to figure out if this is related to the workaround suggested by the user here: https://github.com/rancher-sandbox/rancher-desktop/issues/1668#issuecomment-1064196699 If so, we should close this issue since it would be related.

**Comment by jandubois** [comment]
Isn't this normal on Linux? You have to allow port binding with:

```shell
sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80
```

**Comment by Nino-K** [comment]
Yes, that is normal on Linux, however, I was under the assumption RD should just work outside the box when enabling traefik since that is the behavior on other platforms (MacOs and Windows). If there is an additional step required from the users we should probably document that.

**Comment by jandubois** [comment]
> RD should just work outside the box when enabling traefik since that is the behavior on other platforms

There is no way you can do that without `sudo`. So unless/until we have some kind of privileged helper, we need to tell the user to enable this.

On macOS you can bind to `0.0.0.0:80` as a regular user, but on Linux you cannot.

> we should probably document that.

Yeah, please file a docs bug about this!

**Comment by s0nea** [comment]
Yes, I can confirm the suggestion in https://github.com/rancher-sandbox/rancher-desktop/issues/1668#issuecomment-1064196699 fixes it. I'm closing the issue.

Please find the docs issue here: https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/149

**Comment by s0nea** [comment]
Yes, I can confirm the suggestion in https://github.com/rancher-sandbox/rancher-desktop/issues/1668#issuecomment-1064196699 fixes it. I'm closing the issue.

Please find the docs issue here: https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/149
