### ISSUE TITLE
Upgrade Node.js to version 18.x

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3952]
Node.js 16 will reach [end of life on September 11th, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol/). The new version comes with a breaking change to OpenSSL, which [breaks builds in Rancher Desktop](https://github.com/rancher-sandbox/rancher-desktop/issues/3765#issuecomment-1431729598).

Two common proposed solutions for handling the breaking change in OpenSSL don't appear to work for Rancher Desktop

1. Update the hash function in webpack: `output.hashFunction: "xxhash64 | sha512 | sha256"`. 
   
   This doesn't have any effect on the behavior at all. It seems to me that this error is happening before webpack begins bundling.
 
2. Add `--openssl-legacy-provider` to dev/build scripts. 

   Performing this action raises another error: `electron: --openssl-legacy-provider is not allowed in NODE_OPTIONS`

More research on an upgrade path is needed.

**Comment by gaktive** [comment]
@rak-phillip shall we move to this v.Later or how necessary is this for the current release?

**Comment by rak-phillip** [comment]
Yes, I think later is appropriate.

**Comment by jandubois** [comment]
We are running node 18 now, and I think there are no outstanding problems with the openssl update.
