### ISSUE TITLE
Investigate UI for locked fields in Preferences dialog

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3959]
We currently have the feature to lock the "Allowed Images" settings (both the "Enabled" status, and the list of "Patterns"). When locked we display a lock icon with a tooltip next to the label, and don't allow the user to edit the values.

For the deployment profile work we have generalized the concept of locked settings, and an administrator can provide a locked value for any of the preferences.

This issue is about investigation of how this could be represented in the UI for the different field/value types.

Additional question: are the differences between locked and disabled settings?

**Comment by jandubois** [comment]
In the sync meeting today we talked about distinguishing disabled from locked fields:

* disabled fields will have a gray label
* locked fields have a black label and a lock icon (with tooltip)

In both cases the entry fields would be locked and the current value would be displayed in a disabled state (grayed-out?).

Let's survey other applications to see if there is a common paradigm how to handle these!

**Comment by rak-phillip** [comment]
For reference, this is our existing implementation for Allowed Images

![image](https://user-images.githubusercontent.com/835961/220399333-0c4eaec3-37be-45c6-b75d-300c1f4c72c0.png)

**Comment by jandubois** [comment]
Note that 2 settings are currently also displayed in the General page, and not just the preferences dialog:

```
--application.telemetry.enabled
--application.updater.enabled
```

So if they are locked, they need to be disabled in both places.

**Comment by kwwii** [comment]
After investigating other ideas, simple seems to work best: 
![1](https://user-images.githubusercontent.com/617368/234825805-d1fd8d8a-6fa9-4c12-b28f-c565984afcc9.png)

**Comment by jandubois** [comment]
> After investigating other ideas, simple seems to work best:

Agreed!

I'm curious though why the text for `Enable Kubernetes` and `Enable Traefik` is a lighter grey than the rest of the text. What is that trying to tell me?

Since we are using grey to mean "you can't touch this" now, it is sending me a mixed message when the checkbox itself is actually active.

**Comment by kwwii** [comment]
The text colour itself comes directly from a screenshot so either the text is currently lighter OR it's an artefact from the screenshot/system

**Comment by rak-phillip** [comment]
> I'm curious though why the text for Enable Kubernetes and Enable Traefik is a lighter grey than the rest of the text. What is that trying to tell me?

This is the styling of checkboxes from the core styleshoot. We can see the same styles applied to checkbox labels in Rancher Manager

![image](https://user-images.githubusercontent.com/835961/234970638-13c806b5-de8b-4a49-9907-70868636bd83.png)

**Comment by jandubois** [comment]
> This is the styling of checkboxes from the core stylesheet. We can see the same styles applied to checkbox labels in Rancher Manager

Ok, thanks! I see it is used for the labels in the dropdown list boxes as well. I guess this is fine.

One thing I still don't get though:

In the DISABLED image, the Kubernetes Version text is also greyed out, but the Kubernetes Port text is not. Why are they different when in the ACTIVE image they both are fully black. And why does the disabled port have a darker background than the version?

Actually, given that in the LOCKED image the Version is regular black again, I can kind of understand why it is grey in DISABLED, but does the Port field look different:
<img width="263" alt="CleanShot 2023-04-27 at 17 09 31@2x" src="https://user-images.githubusercontent.com/78947/235016118-4ca52209-6244-4b91-837f-86969e8b8f96.png">

**Comment by kwwii** [comment]
@jandubois I think that is a bug. There should not be a visual difference between the inactive states of text inputs and dropdowns.

**Comment by gaktive** [comment]
#4608 is the epic version of this so I'll move this to Done as a sorta duplicate but with historical reference.

**Comment by IsaSih** [comment]
Tests pass
