### ISSUE TITLE
Screenshots Script: Dark mode in Linux

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3960]
We collect dark mode screenshots for both Windows and macOS. We should be able to do the same in Linux as well. 

It appears to have worked fine, though I don't see anything for dark mode on Linux:
```
rancher-desktop> ls screenshots/output/linux
 #                name                type    size       modified
 0   screenshots/output/linux/light   dir    4.0 KiB   3 minutes ago
```

_Originally posted by @adamkpickering in https://github.com/rancher-sandbox/rancher-desktop/issues/3509#issuecomment-1432067777_

**Comment by adamkpickering** [comment]
Heads up: after a reboot, `git clean -ffdx`, and `npm install`, running `npm run test:e2e:screenshots` still doesn't produce dark mode screenshots for me. Maybe it's a issue that is specific to my system...

**Comment by torchiaf** [comment]
Re-opening this issue since seems to be not resolved for some Linux systems.

**Comment by torchiaf** [comment]
The correct command to produce screenshots, both light&dark mode, is: `npm run screenshots`.
I just filed a new issue to write a README file for screenshots https://github.com/rancher-sandbox/rancher-desktop/issues/4048
