### ISSUE TITLE
Error downgrading Kubernetes - Deleting incompatible Kubernetes state

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3980]
### Actual Behavior

When downgrading Kubernetes from 1.26.1 to 1.24.6, lima fails to remove k3s data in `/var/lib/rancher/k3s/storage`, throwing a fatal error that is not resolved even after a factory-reset as the VM goes to a Broken state

### Steps to Reproduce

1. Start Rancher Desktop with kubernetes version 1.26.1 and moby as the container engine
2. Deploy a kubernetes app. e.g. busybox
3. Start 2 containers rancher and nginx
4. Downgrade Kubernetes to version 1.24.6

### Result

Fatal error message:

```
time="2023-02-16T16:09:31-08:00" level=debug msg="AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com"
time="2023-02-16T16:09:31-08:00" level=debug msg="executing ssh (may take a long)): [/usr/bin/ssh -F /dev/null -o IdentityFile=\"/Users/iguimaraes/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=iguimaraes -o ControlMaster=auto -o ControlPath=\"/Users/iguimaraes/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=5m -q -p 55061 127.0.0.1 -- cd . || exit 1 ; exec \"$SHELL\" --login -c 'sudo rm -rf /var/lib/rancher/k3s/server']"

2023-02-17T00:09:31.595Z: > limactl --debug shell --workdir=. 0 sudo rm -rf /var/lib/kubelet
time="2023-02-16T16:09:31-08:00" level=debug msg="changeDirCmd=\"cd . || exit 1\""
time="2023-02-16T16:09:31-08:00" level=debug msg="OpenSSH version 8.6.1 detected"
time="2023-02-16T16:09:31-08:00" level=debug msg="AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com"
time="2023-02-16T16:09:31-08:00" level=debug msg="executing ssh (may take a long)): [/usr/bin/ssh -F /dev/null -o IdentityFile=\"/Users/iguimaraes/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=iguimaraes -o ControlMaster=auto -o ControlPath=\"/Users/iguimaraes/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=5m -q -p 55061 127.0.0.1 -- cd . || exit 1 ; exec \"$SHELL\" --login -c 'sudo rm -rf /var/lib/kubelet']"
```

From inside the VM: No errors by removing this directory via CLI

```
lima-rancher-desktop:/var/lib/rancher/k3s# ls -l
total 4
drwxr-xr-x    6 root     root          4096 Feb 17 00:07 agent
lima-rancher-desktop:/var/lib/rancher/k3s# rm -rf /var/lib/rancher/k3s/storage
lima-rancher-desktop:/var/lib/rancher/k3s# echo $?
0
lima-rancher-desktop:/var/lib/rancher/k3s# exit
```

[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10770508/Archive.zip)
[lima logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10770513/lima.logs.zip)

### Expected Behavior

Kubernetes must be downgraded to the desired version without occurring any errors

### Rancher Desktop Version

1.7.0-324-gd7df4e7d

### Rancher Desktop K8s Version

1.24.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I believe this failure is due to too many concurrent SSH connections to the VM and should be fixed by #3971.

All recent "package" workflows of merges to `main` have failed, so please use the build from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/4206129233 for testing

**Comment by jandubois** [comment]
@IsaSih Please check if this issue is resolved in the latest CI builds from `main`, and close this issue, if it is.

**Comment by IsaSih** [comment]
Yes, this issue has been fixed.
