### ISSUE TITLE
Auto-update for CI builds is not disabled on macOS

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3989]
#3913 was supposed to implement this, but only seems to work on Windows.

**Comment by jandubois** [comment]
I could not repro this anymore; not sure if this issue was real, or based on running an older build.

**Comment by jandubois** [comment]
I've observed it today again. I think I last ran a failed E2E test locally, which might have left `settings.json` in a non-default state (e.g. "Start in background" was enabled).

Quitting and restarting Rancher Desktop did not change the setting of the auto-updater either:

<img width="1052" alt="Screen Shot 2023-03-07 at 10 58 39 AM" src="https://user-images.githubusercontent.com/78947/223524161-93e4b53c-4925-4238-814a-a60b3b88d8bc.png">

**Comment by jandubois** [comment]
I cannot reproduce this right now; so seems to be fixed.

**Comment by IsaSih** [comment]
Auto-updater is disabled by default on M1.
