### ISSUE TITLE
RancherDesktopPrivilegedService fails to portforward - "cannot run executable found relative to current directory"

### ISSUE THREAD

**Issue by martinothamar** [rancher-sandbox/rancher-desktop#3994]
### Actual Behavior

My docker containers stopped being reachable from Windows host via the portforwarding functionality built into Rancher Desktop. For example an SQL server container with the following port mapping: `0.0.0.0:15672->15672/tcp` is not reachable any more (unclear what I did to provoke this, maybe update + reboot).

### Steps to Reproduce

This is me running on a laptop heavily inflicted with corporate bloatware and "security software", so not sure this will be useful, but this is my setup:

* Install Rancher Desktop 1.7.0
  * Configured with WSL Ubuntu distro, dockerd container engine
* Start a container, with some port mapping to 0.0.0.0 (for example `0.0.0.0:15672->15672/tcp` for RabbitMQ)
* `curl -I http://localhost:15672` - does _not_ work
* `curl -I http://172.28.252.1:15672`  - current WSL IP, does work correctly

### Result

Localhost port forwarding for Windows Rancher Desktop setup does not work on my machine. No portwarding is setup in netsh, eventlog shows error for RancherDesktopPrivilegedService.

### Expected Behavior

Portforwarding configuration to the local WSL instance to be synced correctly based on container deployment. Requests towards localhost to work.

### Additional Information

 `netsh interface portproxy show all` gives empty output, so no rules in place. I reset the config earlier, but before that I could see some portforward configuration pointing to an IP that doesnt exist (probably stale).

In the Windows event log for , I see repeated errors: `port proxy failed: execute command error: exec: "netsh": cannot run executable found relative to current directory: `

I'll probably be able to work around this by manually creating the port forwarding rules.

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 19044.2604, Ubuntu 22.04.1 LTS on WSL

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Corporate laptop with Cisco AnyConnect VPN, some antivirus software, ZScaler MiTM etc. Not sure if it applies, or what can incur the error logged by the privileged service.

**Comment by martinothamar** [comment]
I tried to reinstall Rancher Desktop and selected the radio button to install just for current user this time, and that seems to work. Maybe there is some security setup on this laptop that makes the other mode not work, not sure from the error message in the event log.

**Comment by Nino-K** [comment]
@martinothamar this is already addressed in our latest release. Can you bump the version to 1.11 and give it a try again? Also, I recommend using the experimental network tunnel which will be promoted as the default network in our upcoming 1.12 release. I'm going to close this issue, however, feel free to re-open if you still encounter the issue.
