### ISSUE TITLE
WSL Integrations prompts for Kubernetes restart after reverting changes

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4000]
### Actual Behavior

Making a change to WSL integrations will display the "Kubernetes restart" message after reverting that change. 

## Windows only

1. Navigate to Preferences => WSL Integrations
2. Select an option (the "Kubernetes will restart after applying changes." warning should appear)
3. Deselect the option selected in step 2

### Result

The "Kubernetes will restart after applying changes." warning remains.

### Expected Behavior

The "Kubernetes will restart after applying changes." warning should not render if there is no difference from the initial state.

## Default State

![image](https://user-images.githubusercontent.com/835961/220429415-65048207-0ae7-4fd8-9265-720a5378e4c3.png)

## Change is made, properly prompts for restart
![image](https://user-images.githubusercontent.com/835961/220429469-4a8c23b9-f304-4a8a-a7fd-158e782a5951.png)

## Change is reverted before apply, still prompts for restart

![image](https://user-images.githubusercontent.com/835961/220429534-b729b6f5-042f-40a0-b2ea-c0b38a5165b8.png)

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

NA

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

NA

**Comment by jandubois** [comment]
I also don't understand why Kubernetes needs to be restarted to enable WSL integrations, but I guess that should be a separate issue.
