### ISSUE TITLE
Ability to take application snapshots

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4002]
### Problem Description

It will be useful for users to have functionality to take/save application snapshots in Rancher Desktop and the ability to restore to a saved snapshot. 

**Some use cases where this feature will be useful:**

- To restore to a working state when things go wrong
- To minimize/eliminate repetitive setup steps (ex: starting services, port forwarding, volume mounts etc) when starting a new session. 

### Proposed Solution

TBD

**Comment by jandubois** [comment]
Tracked now in epic #4236
