### ISSUE TITLE
Description for "Quit on Close" is inverted

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4008]
The option currently reads: "Keep running in background when closing application window"

<img width="434" alt="Screen Shot 2023-02-21 at 3 43 05 PM" src="https://user-images.githubusercontent.com/78947/220484041-a78dd40d-ab51-433a-a4f6-7f2811e78e7a.png">

But it does the opposite: It keeps running, when the option isn't selected, but quits the app when it is.

Now we could just invert the logic, and have the option selected by default.

However, I would like to keep the GUI description close to the option names we use for `rdctl set` option names:

```
--application.auto-start
--application.hide-notification-icon
--application.start-in-background
--application.window.quit-on-close
```

Therefore I would rather update the description to "Quit application when closing application window".

I also prefer that all the options are off by default, but agree that that is not very important.

**Comment by kwwii** [comment]
So something like "Quit application when closing window"?
