### ISSUE TITLE
We need to switch update channels when we stop supporting older OS versions

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4010]
Unfortunately #3925 is not enough to prevent users from upgrading to a non-functional release for their OS version:

The auto-update will always attempt to update to the latest available release. So assuming we update 1.8 to know that it is the last version supporting macOS Catalina. That means users updating to 1.8 will not receive another update notification until they update their OS.

However, if somebody has e.g. 1.7 installed on Catalina (say, on a travel laptop), and never updates to 1.8. Once 1.9 is released, the auto-updater will attempt to directly update from 1.7 to 1.9, never running into stopper in 1.8.

The only way I can see to fix this properly would be to introduce a new update channel every time we drop support for an older OS.

That way 1.7 would never see 1.9 on the previous channel, and only 1.8 know to switch to the new channel to see further upgrades.

Well, unless LonghornUpdater has some feature to deal with this, so that should be investigated first.

**Comment by jandubois** [comment]
Screenshot showing how 1.6.0 upgrades directly to 1.7.0, skipping 1.6.1 and 1.6.2:

<img width="1052" alt="Screen Shot 2023-02-21 at 9 57 13 PM" src="https://user-images.githubusercontent.com/78947/220538088-97702e0a-a5b5-4f3b-92aa-d4cdbb108240.png">

**Comment by adamkpickering** [comment]
Closing, since after some discussion we settled on a different way of doing things. Please see #3925 for more info.
