### ISSUE TITLE
Proxy support for Windows with moproxy

### ISSUE THREAD

**Issue by tperale** [rancher-sandbox/rancher-desktop#4013]
### Problem Description

I've been working for the past month on the support of proxies for the Windows version of rancher-desktop. It has been a known issue for a long time that you can't use rancher-desktop with a corporate proxy in Windows because WSL does not takes the proxy settings of the host into account. Here is a list of some issues related to proxy in Windows:  
  * [Issue 767: Create an rancher-desktop-ready script to verify the environment is working](https://github.com/rancher-sandbox/rancher-desktop/issues/767)
    - Verifying the VM connection is not blocked by a proxy connection
  * [Issue 843: kuberlr does not support Windows system proxy](https://github.com/rancher-sandbox/rancher-desktop/issues/843)
    - Getting an error if no `http_proxy` variable set
  * [Issue 866: Custom Environment Variable support for Win/WSL2](https://github.com/rancher-sandbox/rancher-desktop/issues/866)
    - Suggesting to be able to add environment variable to WSL to be able to use a proxy
  * [Issue 905: Kubernetes was unable to start: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"](https://github.com/rancher-sandbox/rancher-desktop/issues/905)
    - Kubernetes not starting with the proxy env var set with `wslenv`.
  * [Issue 995: Rancher doesn't work on VPN / Corporate Proxy](https://github.com/rancher-sandbox/rancher-desktop/issues/995)
  * [Issue 1509: "nerdctl compose up" fails to pull postgres image](https://github.com/rancher-sandbox/rancher-desktop/issues/1509)
    - Probably did the install without a proxy and try to run `nerdctl compose up` behind a proxy
  * [Issue 1568: Error starting Kubernetes -- Updating kubeconfig -- kubectl.exe exited with code 255](https://github.com/rancher-sandbox/rancher-desktop/issues/1568)
    - Kubernetes not starting when running rancher-desktop behind a proxy (installation probably done without a proxy).
  * [Issue 1772: Error starting kubernetes - waiting for services](https://github.com/rancher-sandbox/rancher-desktop/issues/1772)
    - Kubernetes not starting with the proxy env var set.
  * [Issue 2147: RD fails to complete Kubernetes init when Proxy configured](https://github.com/rancher-sandbox/rancher-desktop/issues/2147)
    - Kubernetes not starting with the proxy env var set with `wslenv`.
  * [Issue 2695: Kubernetes fails to start on Windows 10 (corporate envrionment with proxy).](https://github.com/rancher-sandbox/rancher-desktop/issues/2695)
  * [Issue 2759: Add ability to configure proxies in Rancher Desktop preferences](https://github.com/rancher-sandbox/rancher-desktop/issues/2759)
  * [Issue 2815: Kubernetes Error - Rancher Desktop 1.5.1 - win32(x64)](https://github.com/rancher-sandbox/rancher-desktop/issues/2815)
  * [Issue 3545: Stuck at "Waiting for Kubernetes API"](https://github.com/rancher-sandbox/rancher-desktop/issues/3545)
 
If you use rancher-desktop behind a proxy you can't:
  * Install it, because you need to pull docker container during the installation
  * Run it because you get an [error](https://github.com/rancher-sandbox/rancher-desktop/issues/905) from kubernetes.
  * Do a docker pull/push

There has been different proposal in Github issue discussions about how to use a proxy with rancher-desktop:
  * Setting `http_proxy`, `https_proxy` in `WSLENV`. This will create an [error](https://github.com/rancher-sandbox/rancher-desktop/issues/905) from kubernetes.
  * Using `wsl-vpnkit`
  * [Setting](https://github.com/rancher-sandbox/rancher-desktop/issues/995#issuecomment-1022617071) the variable in `rc.conf`

### Proposed Solution

None of the solution proposed really worked. Using `WSLENV` introduce the error with kubernetes and will share the proxy variable with every WSL VM. Based on discussion I had in the rancher-desktop slack I opted for a solution based on the usage of a proxy running inside WSL that could be programmatically enabled/disabled to catch the network traffic and forward it to an http proxy.

My changes to the rancher-desktop-wsl-vm and rancher-desktop code are available here:
   * [rancher-desktop](https://github.com/rancher-sandbox/rancher-desktop/compare/main...tperale:rancher-desktop:wsl-proxy)
   * [rancher-desktop-wsl-distro](https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/compare/main...tperale:rancher-desktop-wsl-distro:main)

My solution is based on a software named `moproxy`, a software installed on WSL as a service that handles the connections and transmissions of packets to an http proxy. The traffic from the network interface is redirected to `moproxy` using `iptables`, so any type of filtering on ports/address is supported.

```mermaid
flowchart  LR;
 subgraph VM["WSL VM"]
   direction LR
   apps{{"Apps"}}
   subgraph vmIptables["iptables"]
   direction LR
     rules{"Rules"}
   end
   moproxy["moproxy"]
   apps -- TCP --> rules
   rules --> moproxy
 end
 proxy((("Proxy")))
 moproxy --> proxy
```

I also made changes to the rancher-desktop graphical interface to make the proxy configurable from the rancher-desktop settings page or during the first run. For now my changes are only available in the `WSL` setting page but in the future it could probably be ported to other platforms.

![settings](https://user-images.githubusercontent.com/4118134/221191149-ab3a514a-eacd-4094-b366-0cc6bd8491d8.png)

![firstrun](https://user-images.githubusercontent.com/4118134/221191160-9ebff318-7466-42a1-b8cb-fc310e2bbb22.png)

Changes on the proxy configuration take effect immediately after clicking on `Apply` without having to restart the backend like the other change in settings.

### Additional Information

Recently there has been some activity on the Github issues to port the network stack to work with `gvisor-tap-vsock` (see [Epic: Incorporate gvisor into Rancher Desktop's networking stack](https://github.com/rancher-sandbox/rancher-desktop/issues/3810)). I'm waiting for the release of this experimental feature in rancher-desktop 1.8 to see how `gvisor-tap-vsock` can work with proxy and if my changes are still required.

```mermaid
flowchart  LR;
 subgraph VM["VM"]
   direction LR
   apps{{"Apps"}}
   subgraph vmIptables["iptables"]
   direction LR
     rules{"Rules"}
   end
   moproxy["moproxy"]
   vmSwitch["VM Daemon Switch"]
   apps -- TCP --> rules
   rules --> moproxy
   moproxy -- TAP --> vmSwitch
 end
 subgraph host["Host"]
   hostSwitch["Host Switch"]
 end
 vmSwitch -- VSOCK --> hostSwitch
 proxy((("Proxy")))
 hostSwitch -- CONNECT --> proxy
```

**Comment by gaktive** [comment]
Work for this is being tracked in #4603 so closing this as a sorta duplicate.
