### ISSUE TITLE
Auto-start feature: slow shutting down process when main window is closed 

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4015]
### Actual Behavior

Once user selects option to shut down application by closing the main window, the shutting down process takes a significant longer time than comparing to shutting it down from the tray menu

### Steps to Reproduce

1. Set quitOnClose to true
2. Close the main application window
3. Observe the shutting down process

### Result

Shut down process is working as expected. However taking a longer time when comparing to shutting down from the tray menu
  

### Expected Behavior

Shutting down process must behave the same way no matter from which way it is trigged.

### Rancher Desktop Version

1.7.0-400-gcad1ad97

### Rancher Desktop K8s Version

1.26.1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by adamkpickering** [comment]
I had a call with @IsaSih and it seems that the amount of time it takes for RD to shut down isn't related to the way it shuts down: sometimes it will be faster when RD is shut down via the tray menu, and other times it will be faster when RD is shut down by closing the main window.

Closing this issue for now; if we see this in the future we can reopen it.
