### ISSUE TITLE
Use "Open" instead of "Show" in the preference menu

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4024]
I've been testing the new behaviours for a bit and have opened the menu on the notification icon many times. Now "Show main window" and "Show preferences dialog" feel wrong to me; they should be "Open" instead of "Show":

"Show" is the the opposite of "Hide"; it brings a window that already exists, but has been hidden/minimized back to normal size and to the front.

"Open" is the opposite of "Close"; it creates a new instance of a window that has either been closed, or has not been created yet.

Our menu options have additional side effects: they also create the dock icon, the entry in the app switcher list, and a top level menu.

I know it is subtle, but I feel "Open" is more appropriate than "Show" here. Also, we have "File | Close Window ⌘W" in our menu, so we should pair that with "Open".

**Comment by jandubois** [comment]
This should also apply to "Show dashboard". It should be "Open dashboard" as long as it opens in an external window.

**Comment by gunamata** [comment]
Just noticed its `File > Exit` on Windows. We should keep this wording consistent across platforms and also between the app File menu and the Notification icon menu. On the Notification icon menu, it is `Quit Rancher Desktop` now.

**Comment by jandubois** [comment]
> Just noticed its `File > Exit` on Windows. We should keep this wording consistent across platforms and also between the app File menu and the Notification icon menu. On the Notification icon menu, it is `Quit Rancher Desktop` now.

This should be a separate issue. I assume "Exit" is a Windows-specific menu entry provided by Electron; not sure if we easily change it to "Quit" (similar to how Electron changes "Rancher Desktop | Preferences" to "Rancher Desktop | Settings" on macOS Ventura).
