### ISSUE TITLE
Hide Notification Icon does not work

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4031]
### Actual Behavior

By selecting to hide the notification icon in Preferences > Application > Behavior, the notification icon is still shown even after quitting and restarting the application.

### Steps to Reproduce

1.Launch Rancher Desktop
2.In Preferences > Application > Behavior, select the option to hide the notification icon
3.Hit Apply
4. Check if the notification icon is hidden from the tray menu

### Result

By selecting to hide the notification icon in Preferences > Application > Behavior, the notification icon is still shown even after quitting and restarting the application.

### Expected Behavior

Notification icon must be hidden right after the new preferences are applied.

### Rancher Desktop Version

1.7.0-412-g64c00763

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by rak-phillip** [comment]
AFAICT this wasn't implemented and and didn't work on all platforms.

**Comment by jandubois** [comment]
Fixed by #4038
