### ISSUE TITLE
Make changes to Rancher Desktop to allow preventing automatic updates on specific OS versions

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4036]
This issue is about modifying Rancher Desktop to enable preventing of automatic updates on specific systems. Please see #3925 for more information.

**Comment by jandubois** [comment]
I think we need to include the WSL2 version in our update request. That way we can tell the user to update WSL2 from the Microsoft store before they can upgrade RD, if we ever require new WSL2 features.

This seems more likely than us requiring an upgrade to Windows itself.

<hr>

Of course this will not help us if a WSL2 release can break an existing RD release, but there is nothing we can do about it.
