### ISSUE TITLE
Make changes to Upgrade Responder to allow preventing automatic updates on specific OS versions

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4037]
This issue is about forking and modifying Upgrade Responder to enable preventing of automatic updates on specific systems. Please see #3925 for more information.

**Comment by jandubois** [comment]
I've put this issue into the 1.9 milestone to prioritize it, but it is ok if it slips into 1.10; we can still ship 1.9 with the Catalina version of QEMU, if we have to.
