### ISSUE TITLE
Set up longhorn upgrade-responder server

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#404]
We landed the auto-upgrade code in #378 but currently it points at a dummy server (that doesn't exist).  This is to track setting  up a real [upgrade-responder](https://github.com/longhorn/upgrade-responder):

- [x] Set up a real server.
- [x] Develop a process to add new versions to the server as they come out.
- [x] Change the [configuration](https://github.com/rancher-sandbox/rancher-desktop/blob/main/electron-builder.yml) to use it.

This is initially waiting on @colstrom (but I can't seem to assign him), since I believe he's working on the server side bits — please let us know when that's ready, thanks!

**Comment by mattfarina** [comment]
> Develop a process to add new versions to the server as they come out.

We have an initial process that is in place. It needs work before closing this issue.
