### ISSUE TITLE
Show Mute is not working in Diagnostics

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4040]
### Actual Behavior

Mute toggle is hiding warnings as expected. However, if we hit the 'Show Muted' toggle, the muted warnings do not show up. 

### Steps to Reproduce

1. Fresh Install Rancher Desktop/ Start Rancher Desktop after a Factory reset
2. Set path management strategy to Manual
3. Go to Diagnostics tab from the main window
4. Mute a warning message
5. Hit 'Show Muted' button

### Result

 Once we hit the 'Show Muted' toggle, the muted warnings do not show up. 
![show muted diagnostics](https://user-images.githubusercontent.com/70187881/221060188-c26a7620-1618-4d5b-9971-40ea0ed8fc95.gif)

### Expected Behavior

Once we select Show Muted toggle, all muted warnings must be visible in the Diagnostics tab.

### Rancher Desktop Version

1.7.0-419-gbf3825e1

### Rancher Desktop K8s Version

1.25.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by rak-phillip** [comment]
Did our settings endpoint change recently? I'm seeing quite a few errors in the logs for the diagnostics page

```
Failed to load resource: the server responded with a status of 400 (Bad Request)

PUT http://localhost:6107/v1/settings 400 (Bad Request)
```

**Comment by rak-phillip** [comment]
Also noting that failed diagnostics are not represented in the primary nav

![image](https://user-images.githubusercontent.com/835961/221062100-b52e1cea-ca9a-43ff-b17f-44dce52b3850.png)

**Comment by IsaSih** [comment]
Yes, the API version was updated to v1.

**Comment by IsaSih** [comment]
> Also noting that failed diagnostics are not represented in the primary nav
> 
> ![image](https://user-images.githubusercontent.com/835961/221062100-b52e1cea-ca9a-43ff-b17f-44dce52b3850.png)

I created another issue for this. #4041

**Comment by IsaSih** [comment]
<img width="659" alt="Screen Shot 2023-02-23 at 5 11 03 PM" src="https://user-images.githubusercontent.com/70187881/221068024-6c14bda4-f4f3-499b-a366-b2bea525939b.png">

**Comment by ericpromislow** [comment]
You need to specify a matching version field for `PUT /settings` -- fix on the way.
