### ISSUE TITLE
Change rdNetworking settings name

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4078]
As discussed in https://github.com/rancher-sandbox/rancher-desktop/pull/4065#issuecomment-1449103298 we want to move the setting under `virtualMachine` and hopefully find a more descriptive name.

Maybe `virtualMachine.networkingTunnel` would work? Please do some bike-shedding if you have better suggestions!

**Comment by Nino-K** [comment]
I'm still not 100% sure if this config belongs under `virtualMachine`. Also, I'm hesitant to use the Tunnel keyword because we have a project called `vtunnel` already and that could cause some confusion. Is there an option where we can have it nested under the networking sibling to the `virtualMachine`? something like this:

```
 "experimental":{
      "virtualMachine":{
         "socketVMNet":false,
         "mount":{
            "type":"reverse-sshfs",
            "9p":{
               "securityModel":"none",
               "protocolVersion":"9p2000.L",
               "msizeInKB":128,
               "cacheMode":"mmap"
            }
         }
      },
      "networking":{
        "switch": true,
      },
 }
```

**Comment by jandubois** [comment]
> I'm still not 100% sure if this config belongs under `virtualMachine`.

Why not? Why does `hostResolver` belong under `virtualMachine`, but `rdNetworking` does not?

> Also, I'm hesitant to use the Tunnel keyword because we have a project called `vtunnel` already and that could cause some confusion.

The `vtunnel` project name is an implementation detail that users neither know nor care about. I'm happy to use a different word as long as it describes what is different about the new networking stack from the user's point of view.

To me it is that the network connections are now "tunneled" to the host, so seem that they originate on the host and not inside the VM. So `host-networking` could be an alternative if `networking-tunnel` doesn't feel right.

> Is there an option where we can have it nested under the networking sibling to the `virtualMachine`?

Not really, unless we create a separate "Networking" page in the Preferences dialog.
