### ISSUE TITLE
Manual Port Forwarding on Rancher Desktop Networking 

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#4096]
During the experimental release of RD Networking, the port forwarding has to be performed manually. This is due to the privileged escalation (firewall prompt) that is required by the `host-switch.exe`. It is important to note that this will improve in the upcoming release and the manual step is no longer expected from our users. 

When port forwarding is needed for e.g:

```
docker run --name mynginx1 -p 8801:80 -d nginx
```

**In order to access the container via the exposed port manual step must be performed.** 

From WSL VM:
```
wsl -d rancher-desktop
```
Expose the desired port:
```
curl http://192.168.127.1:80/services/forwarder/expose -X POST -d '{"local":":8801","remote":"192.168.127.2:8801"}'
```

To Unxpose:
```
curl http://192.168.127.1:80/services/forwarder/unexpose -X POST -d '{"local":":8801","remote":"192.168.127.2:8801"}'
```

Related to: https://github.com/rancher-sandbox/rancher-desktop/issues/3810

**Comment by Nino-K** [comment]
@gunamata @sunilarjun please make sure we include this limitation in the release notes, furthermore, this will change in the upcoming release.

**Comment by gunamata** [comment]
Thanks @Nino-K . Tagging @jandubois as he writes the release notes.

**Comment by jandubois** [comment]
@Nino-K Is `192.168.127.1` a fixed IP address, or the address of the Windows host?

**Comment by Nino-K** [comment]
The `192.168.127.1` is a fixed IP address, it's a gateway address in the virtual network. The gateway is the windows host (host-switch.exe) however, the IP address is not accessible from windows itself, it can only be accessed from within the network namespace (virtual network) for now.

**Comment by jandubois** [comment]
Oh, I see, I missed the `wsl -d rancher-desktop` part.

Maybe it would be better to tell people to use `rdctl shell curl ...` instead.

**Comment by Nino-K** [comment]
> Maybe it would be better to tell people to use `rdctl shell curl ...` instead.

Oh, I didn't think about that, I will test and see if it works. If that works, that would be much better.

**Comment by Nino-K** [comment]
Once the attached PR is merged in, when the new networking is enabled you can use the following commands to expose and unexposed the ports.

expose:
```
.\rdctl.exe shell curl http://192.168.127.1:80/services/forwarder/expose -X POST -d '{\"local\":\":8801\",\"remote\":\"192.168.127.2:8801\"}'
```
unexpose:
```
.\rdctl.exe shell curl http://192.168.127.1:80/services/forwarder/unexpose -X POST -d '{\"local\":\":8801\",\"remote\":\"192.168.127.2:8801\"}'
```
