### ISSUE TITLE
Versions are "blank"

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#412]
I just ran into this:
![image](https://user-images.githubusercontent.com/442274/125856235-e0a07ddb-0823-4a59-99b6-0538135f06f3.png)

Looking in the developer-tools console didn't show anything unexpected and looking at the rendered html makes me think it's a chromium glitch. 

I'm on Version: 0.3.0-9-gdfcc043

**Comment by agracey** [comment]
I'm not sure if I just didn't notice it before or if it's new to the 3.0 release that I'm on.

**Comment by mook-as** [comment]
It looks like the dropdown is being shown white-on-white.  I can reproduce this on _Windows_ if I turn on dark mode there.
