### ISSUE TITLE
`rdctl` command line extension for `rdctl extension install` etc.

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4120]
Add the following new `rdctl` subcommands:

`rdctl extension install [--force] <image-id>`
`--force`: avoid any interactivity.
The `<image-id>` is an image reference, e.g. `splatform/epinio-docker-desktop:latest` (the tag is optional).
The backing API is `POST /v1/extensions/install?id=<image-id>`.

`rdctl extension ls`
List currently installed extensions.
The backing API is `GET /v1/extensions`.

(TDB: if we want `rdctl extension update <image-id>`, and how that would work.)

`rdctl extension uninstall <image-id>`
The backing API is `POST /v1/extensions/uninstall?id=<image-id>`.

**Comment by mook-as** [comment]
For testing, updating the [bats tests](https://github.com/rancher-sandbox/rancher-desktop/blob/main/bats/tests/extensions/install.bats) to use the new command rather than `rdctl api` is probably the easiest way to go.

**Comment by jandubois** [comment]
The BATS test seems to be building its own extension to install. Do we have some sample extension that we can install, list, and uninstall manually? Something that would also be suitable for the docs?

Does the user have to pull the extension manually from the registry, or will `rdctl extension install` do this automatically?

**Comment by jandubois** [comment]
Shouldn't there be an `rdctl extension update` command? Or does this have to be done via uninstall followed by reinstall?

Or is this something to be added later?

**Comment by mook-as** [comment]
> The BATS test seems to be building its own extension to install. Do we have some sample extension (on Dockerhub?) that we can install, list, and uninstall manually? Something that would also be suitable for the docs?

We do not have anything published ourselves.  The BATS tests build locally to ensure we don't have too many dependencies (e.g. Docker Hub has announced plans to essentially sunset public orgs).

> Does the user have to pull the extension manually from the registry, or will `rdctl extension install` do this automatically?

`rdctl extension install` will pull the image automatically.


> Shouldn't there be an `rdctl extension update` command? Or does this have to be done via uninstall followed by reinstall?
> 
> Or is this something to be added later?

That will probably need to be something added later.
