### ISSUE TITLE
k8s service watcher not working in non-privileged env

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#4124]
### Actual Behavior

The guestAgent kubernetes service watcher does no longer work correctly in non-privileged Windows environments.
If I deploy an nginx pod and a NodePort service, nginx is no longer accessible from the Windows host.

### Steps to Reproduce

- Do a non-privileged Rancher Desktop installation on Windows
- Deploy nginx pod + NodePort service
- Check if the NodePort (nginx) service is accessible on Windows

### Result

NodePort service not accessible.

### Expected Behavior

Services should be accessible from the Windows host again.

### Rancher Desktop Version

1.7.0-573-g76857559 Build of https://github.com/rancher-sandbox/rancher-desktop/suites/11430882317/artifacts/589307821

### Rancher Desktop K8s Version

1.25.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by Nino-K** [comment]
This could be the fix for this issue, but needs testing: https://github.com/rancher-sandbox/rancher-desktop-agent/tree/fix-k8s-service-tracker

**Comment by Nino-K** [comment]
Also related to: https://github.com/rancher-sandbox/rancher-desktop/issues/3839
