### ISSUE TITLE
Update screenshots script to check the auto-update checkbox

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4138]
We have modified RD so that dev builds automatically disable auto-updates, so even if `RD_MOCK_VERSION=1.8.0` is set, the option is still disabled because the actual version is a dev version.

**Comment by jandubois** [comment]
To confirm, this story is purely about making sure the checkbox is checked in the screenshot, and nothing else.

**Comment by s0nea** [comment]
> To confirm, this story is purely about making sure the checkbox is checked in the screenshot, and nothing else.

Thank you for the confirmation!
