### ISSUE TITLE
Deployment profile settings need to be validated

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4159]
### Actual Behavior

The deployment profiles aren't validated.

### Steps to Reproduce

Create a default deployment profile like so:
```
{
 application: {
      pathManagementStrategy: 'geese',
    },
    kubernetes: {
      port: {
        zoo: ['possums', 'snakes', 'otters'],
      },
      enabled: 'fish',
    },
    virtualMachine: {
      memoryInGB: 'cows',
    },
}
```

### Result

The new values end up in the settings

### Expected Behavior

Rancher Desktop should complain about the invalid values and refuse to start.

Same with the locked-field thing.

**Comment by IsaSih** [comment]
Regression identified in Mac Intel, build https://github.com/rancher-sandbox/rancher-desktop/actions/runs/5206486035
dep profile with invalid fields used for the test: 
[user-profile-defaults.txt](https://github.com/rancher-sandbox/rancher-desktop/files/11708978/user-profile-defaults.txt)

**Comment by gaktive** [comment]
Working as designed. @IsaSih to retest with different data types.

**Comment by IsaSih** [comment]
Works as expected
