### ISSUE TITLE
Disable "Cluster Tools" in Dashboard

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4168]
The dashboard displays a notice to install the new Cluster Tools:

<img width="846" alt="Screenshot 2023-03-13 at 12 26 37 PM" src="https://user-images.githubusercontent.com/78947/224812481-450b3099-e949-4f82-a2a8-8835bc100230.png">

This is not applicable to Rancher Desktop and should be suppressed.

**Comment by rak-phillip** [comment]
I agree that this should be removed, but there is no regression from 1.7.0.
