### ISSUE TITLE
nerdctl login fails

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4178]
`nerdctl login` failed while testing the rc build (https://github.com/rancher-sandbox/rancher-desktop/actions/runs/4390255742)

Error message: 

```
>nerdctl login
Enter Username: my-dockerhub-id
Enter Password:
FATA[0021] error saving credentials: error storing credentials - err: exit status 22, out: `Error: spawn docker-credential-desktop ENOENT`
```

Logs at this state:

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10962879/logs.zip)

**Comment by jandubois** [comment]
> `Error: spawn docker-credential-desktop ENOENT`

The problem is that the `credStore` value in `~/.docker/config.json` is set to `desktop` instead of `wincred`. RD is supposed to replace the `desktop` value if the corresponding helper isn't actually installed, so that part seems to have failed.

**Comment by gunamata** [comment]
I investigated a bit and it looks like Rancher Desktop is working as expected. RD is replacing the `desktop` value with `wincred` at launch time. When I was testing, by mistake, I edited the `~/.docker/config.json` file after launch which is not correct and also not the order shown in the testcase instructions.  Closing the issue.
