### ISSUE TITLE
Cancel port-forwarding should ask for confirmation

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4180]
Show a confirmation pop up with options `Yes`, `No` on clicking the `Cancel` button for port forwarding. Cancel port forwarding only if user confirms with an `Yes`.

**Comment by jandubois** [comment]
> Show a confirmation pop up with options `Yes`, `No` on clicking the `Cancel` button for port forwarding.

Why do you want that? A confirmation dialog makes sense when you perform a destructive action that cannot easily be undone. But restoring the port forwarding takes only another click, so having a confirmation dialog feels more annoying than helpful to me.

**Comment by gunamata** [comment]
It's just from a regular user experience/expectation point of view where options such as delete, cancel usually present a confirmation dialog. When I think about it a bit more after your comment, I feel the confirmation pop up may not add much value here.  Only scenario I could think of for now is, let's say I cancel a random port assignment **unintentionally** and yes I can forward to a new random port again, but it still involves copying the new port over to wherever I want to. Not a big deal but may be a minor inconvenience.

**Comment by jandubois** [comment]
> may be a minor inconvenience

Exactly. It is a minor inconvenience in the relatively rare case that you click something by accident. Adding the confirmation prompt adds a minor annoyance **every single time** you stop forwarding a port.

We should optimize for the common use case.

**Comment by gunamata** [comment]
Agreed. That's a good point. Closing the issue.
