### ISSUE TITLE
Test case 75 (focusing main window via tray menu) fails

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4185]
### Actual Behavior

Link to Trello card: https://trello.com/c/2wSnzAjx/311-test-case-75-bring-main-window-via-tray-menu

Test case 75 says to "verify that PID number is the same comparing it before and after "Open main window" is clicked". This is not what happens. When the main window is closed and then opened, the PID number is different.

Unless I'm missing something, this isn't actually a problem - it is a problem with the test case.

### Steps to Reproduce

Follow test case 75.

### Result

The PID number is not the same when the window is closed and then opened.

### Expected Behavior

The PID number should be the same when the window is closed and then opened.

### Rancher Desktop Version

9.main.1678731422.7818f12-1031.1c

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by mook-as** [comment]
The test case is not explicit about _which_ PID it's looking for. I assume this is for `…/rancher-desktop` (i.e. the main process), not any per-window processes.

**Comment by adamkpickering** [comment]
I removed the part about checking the PID. The PID of the process that corresponds to the main window doesn't matter. Checking the PID of the background processes would be redundant with other tests, such as test case 71 (which is about testing the single instance behavior), and the E2E tests associated with the `quitOnClose` option.
