### ISSUE TITLE
Deployment profiles need to be created on an unnecessary directory on MacOS

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4186]
### Actual Behavior

Deployment profiles should be saved in 
System: /Library/Preferences/io.rancherdesktop.profile.defaults.plist
System: /Library/Preferences/io.rancherdesktop.profile.locked.plist
User: ~/Library/Preferences/io.rancherdesktop.profile.defaults.plist
User: ~/Library/Preferences/io.rancherdesktop.profile.locked.plist 

However, we need to create /Library/Preferences/rancher-desktop and then save the profiles in this directory.

### Steps to Reproduce

1. Create system and user deployment profiles
2. Start Rancher Desktop
3. Verify that the profiles are not read when created in the expected directory
4. Quit Rancher Desktop
5. Create a directory called rancher-desktop under Library/Preferences and move the profiles to this directory
6. Restart Rancher Desktop

### Result

Profiles are read at /Library/Preferences/rancher-desktop instead of /Library/Preferences

### Expected Behavior

Deployment profiles should be read in 
System: /Library/Preferences/io.rancherdesktop.profile.defaults.plist
System: /Library/Preferences/io.rancherdesktop.profile.locked.plist
User: ~/Library/Preferences/io.rancherdesktop.profile.defaults.plist
User: ~/Library/Preferences/io.rancherdesktop.profile.locked.plist 

### Rancher Desktop Version

1.7.0-636-g1091a64f

### Rancher Desktop K8s Version

1.26.1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
Currently, the user profiles are in `~/Library/Preferences/rancher-desktop/*.plist`. `~/Library/Preferences/rancher-desktop` will be deleted by a factory reset. That does not seem like the correct behaviour.
