### ISSUE TITLE
Rancher Desktop is overriding corrupted deployment profiles

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4187]
### Actual Behavior

Once we create deployment profiles with invalid format on the system's level, and start Rancher Desktop, settings.json is created with the default values and the application starts with no errors, overriding the deployment profiles. 

### Steps to Reproduce

1. Create a SYSTEM's deployment profile with invalid format
2. Start Rancher Desktop

### Result

Application is starting with no errors, overriding settings.json with the default values and ignoring the corrupted deployment profiles.

### Expected Behavior

Rancher Desktop should be prevent from starting if a deployment profile is broken at the system's level.

### Rancher Desktop Version

1.7.0-636-g1091a64f

### Rancher Desktop K8s Version

1.26.1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
#3749 says:

> If the profile is in an invalid format, then we show an error dialog and prevent the app from starting.

@ericpromislow told me that we are using a plist-reading library that simply returns an empty object when an error occurs, which we then treat as if no deployment profile had been specified.

I thought it would be easiest to use the builtin `plutil` program to convert a plist file (both binary and XML) into JSON, and then read the JSON file instead. If the conversion fails, then the plist file is invalid:

```console
$ cat io.rancherdesktop.profile.defaults.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application</key>
	<dict>
		<key>autoStart</key>
		<true/>
	</dict>
	<key>containerEngine</key>
	<dict>
		<key>name</key>
		<string>moby</string>
	</dict>
	<key>kubernetes</key>
	<dict>
		<key>version</key>
		<string>1.24.10</string>
	</dict>
	<key>version</key>
	<integer>6</integer>
</dict>
</plist>

$ plutil -convert json -r -o - -- io.rancherdesktop.profile.defaults.plist
{
  "application" : {
    "autoStart" : true
  },
  "containerEngine" : {
    "name" : "moby"
  },
  "kubernetes" : {
    "version" : "1.24.10"
  },
  "version" : 6
}

$ plutil -convert json -r -o - -- ~/.bashrc
/Users/jan/.bashrc: Property List error: Unexpected character # at line 1 / JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0.

$ echo $?
1
```

**Comment by IsaSih** [comment]
This behaviour also occurs with user deployment profiles

**Comment by IsaSih** [comment]
Tests pass. Rancher Desktop is prevented to start, throwing an error dialog when locked and/or defaults deployment profile at the system's and user's level have
<img width="257" alt="Screen Shot 2023-05-01 at 6 10 30 PM" src="https://user-images.githubusercontent.com/70187881/235564119-c55d80d3-89da-4164-9536-beec8e466986.png">
 invalid formatting
