### ISSUE TITLE
On Ubuntu, trying to hide the notification icon  fails to remove the tray icon

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4205]
### Actual Behavior

On openSUSE (Leap 15.3), if I have the `hide notification icon` preference checked, the tray icon doesn't appear.
But on Ubuntu (20.04.5 LTS) it stays visible regardless of the setting `[Preferences | Application | Behavior | Hide Notification Icon]` 

### Steps to Reproduce

Bring up Prefs.
Check `Application | Behavior | Hide Notification Icon`
Press `Apply`
Notice the toolbar RD icon is gone on openSUSE, as expected, but not Ubuntu

### Expected Behavior

The icon should disappear

### Rancher Desktop Version

1.8rc1

Ubuntu

### Operating System / Build Version

Ubuntu 20.04.5 LTS

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
@ericpromislow can you update this ticket to reflect that this behaviour is correct; it's the Ubuntu scenario that's the actual bug to work on.

**Comment by ericpromislow** [comment]
That was an easy update -- I didn't have to change much of the description

**Comment by rak-phillip** [comment]
I can reproduce on Ubuntu 22.04. Investigating the root cause.

**Comment by rak-phillip** [comment]
I was able to set up a minimal tray example to see if this is perhaps a problem with our tray implementation and I'm still able to reproduce.. I'm beginning to think that this might be an issue in electron/ubuntu.

Some additional reading to support this:

- https://github.com/electron/electron/issues/17622
- https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1395229
- https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1796607

**Comment by gaktive** [comment]
This should be a docs item since there's nothing RD can do here.

**Comment by gaktive** [comment]
Docs has https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/214 to document this.

**Comment by IsaSih** [comment]
The notification icon disappears on Ubuntu after restarting Rancher Desktop, but stays in the tray icon right after enabling it via Preferences.
