### ISSUE TITLE
No error dialog appears upon start with invalid JSON in user locked.json (test case 83)

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4209]
### Actual Behavior

Test case 83 states that RD should produce an error dialog when there is invalid JSON in a "deployment profile". Assuming that "deployment profile" means the user locked.json file, this does not happen.

### Steps to Reproduce

1. Do a factory reset.
2. Ensure you have the following invalid JSON in `~/.config/rancher-desktop/locked.json`: `{"bubbles": "asdf": "containerEngine":{"allowedImages":{"enabled":false}}}`.
3. Start Rancher Desktop.

### Result

No error dialog appears. Rancher Desktop starts up normally.

### Expected Behavior

An error dialog should appear.

### Rancher Desktop Version

9.main.1678731422.7818f12-1031.1

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by mook-as** [comment]
This also happens on mac (predictably).

It should be noted that we _do_ error out if there's an invalid _system_ deployment  profile.

It does get logged:
```
deploymentProfile.log┌2023-04-17T18:38:12.504Z: Error parsing deployment profile ~/Library/Preferences/io.rancherdesktop.profile.defaults.plist                                                                                 │
deploymentProfile.log│Error: plutil exited with code 1                                                                                                         
```
