### ISSUE TITLE
Changing the virtualization framework to VZ breaks Kubernetes

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4213]
### Actual Behavior

When changing the virtualization framework from qemu to vz, kubernetes throws an error

### Steps to Reproduce

1. Run factory-reset
2. Start Rancher Desktop
3. Accept the default values from the first-run dialog
4. Run `rdctl set --experimental.virtual-machine.type=vz`
5. Wait for Rancher Desktop to restart

### Result

kubernetes throws an error
[vz_error.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10995982/vz_error.zip)
[serial.log](https://github.com/rancher-sandbox/rancher-desktop/files/10996028/serial.log)
[ha.stderr.log](https://github.com/rancher-sandbox/rancher-desktop/files/10996029/ha.stderr.log)
[ha.stdout.log](https://github.com/rancher-sandbox/rancher-desktop/files/10996030/ha.stdout.log)

### Expected Behavior

Rancher Desktop and Kubernetes must start with no errors.

### Rancher Desktop Version

1.7.0-638-g8a7c5c76

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
This might be solved by #4857. @jandubois to verify.

**Comment by jandubois** [comment]
This is not reproducible by me. I suspect #4857, or #4891 have fixed this issue. With #4891 the node no longer needs to change IP address when switching between QEMU and VZ.
