### ISSUE TITLE
VZ: shutting down the VM takes an additional 3 minutes

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4259]
Root cause is upstream issue https://github.com/lima-vm/lima/issues/1381

When testing with Lima directly this only happens on the first shutdown; with Rancher Desktop the problem happens on every restart.

**Comment by gaktive** [comment]
@jandubois to verify that the upstream fix addresses this.

**Comment by jandubois** [comment]
This has been fixed by upgrading to Lima 0.16
