### ISSUE TITLE
Spike: Explore Linux

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#426]
Based on questions to @agracey, there is potential demand for Rancher Desktop for Linux.

The goal would be "Linux for non-Linux experts", a lightweight install with a GUI. This would allow for separation from the host machine and the ability to blow away the cluster. 

This is an umbrella item for subsequent spikes on features.

**Comment by kunalsingthakur** [comment]
looks like first, we need Linux as its Linux based.

**Comment by jandubois** [comment]
> looks like first, we need Linux as its Linux based.

@kunalsingthakur Not sure what you mean by that.

Right now Rancher Desktop only supports macOS and Windows, and this spike would be about supporting it on Linux. Of course you could run kubernetes natively on Linux, so this would mostly be about isolation, and ease of switching kubernetes versions.

**Comment by kunalsingthakur** [comment]
Is there way we can control in docker instead of vm . So that don't need to
rely on virtualization layer.

**Comment by jandubois** [comment]
> Is there way we can control in docker instead of vm .

The current plan is to keep the backend as close as possible to the macOS version, which means using Lima and qemu, and whatever we are going to do for further networking support.

So running k3s inside docker is unlikely to happen. While it doesn't have a GUI, [k3d](https://k3d.io) is a specialized tool to run k3s inside Docker and is available now.

**Comment by jandubois** [comment]
Just for reference, I tried running the `example/k3s.yaml` instance on openSUSE Leap, and it worked (after applying https://github.com/lima-vm/lima/pull/180):

```console
jan@localhost:~/git/lima> uname -a
Linux localhost.localdomain 5.3.18-lp152.87-default #1 SMP Sun Aug 8 21:53:57 UTC 2021 (44d702a) x86_64 x86_64 x86_64 GNU/Linux

jan@localhost:~/git/lima> limactl shell k3s uname -a
Linux lima-k3s 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

jan@localhost:~/git/lima> export KUBECONFIG=$PWD/kubeconfig.yaml
jan@localhost:~/git/lima> limactl shell k3s sudo cat /etc/rancher/k3s/k3s.yaml >$KUBECONFIG
jan@localhost:~/git/lima> kubectl get no
NAME       STATUS   ROLES                  AGE     VERSION
lima-k3s   Ready    control-plane,master   3m55s   v1.21.4+k3s1
```

This was using a Ubuntu guest, but it should be no different running the alpine-lima guest.

cc/ @agracey

**Comment by gunamata** [comment]
@gaktive , Since we have linux support in place for the past couple of releases, can we close this?

**Comment by jandubois** [comment]
Yes, this is definitely done now. Any problems with the Linux version should be opened as new issues.
