### ISSUE TITLE
K3s errors and Kubernetes not launching behind proxy and VPN

### ISSUE THREAD

**Issue by Elhefes** [rancher-sandbox/rancher-desktop#4265]
### Actual Behavior

Rancher Desktop is not starting Kubernetes when connected through a proxy

### Steps to Reproduce

Steps to Reproduce
- Download Rancher Desktop 1.7.0
- Had to install k3s manually, because Rancher Desktop could not download it:
  - Go to https://github.com/k3s-io/k3s/releases
  - Select v1.26.0+k3s2
  - Download: k3s-airgap-images-amd64.tar & sha256sum-amd64.txt
  - Copy the tar and the txt file in the folder where Rancher Desktop was installed, for me it is in C:\Users\user\AppData\Local\rancher-desktop\cache\k3s\v1.26.0+k3s2
- Set proxy configs to the WSL distro
- Launch Rancher Desktop with Kubernetes enabled

### Result

- When starting the application, this prompt appears:
    - A JavaScript error occured in the main process. Uncaught Exception: Error: EISDIR: illegal operation on a directory, read
- Rancher Desktop stays forever in the "Checking k3s images" state
- background.log prints this over and over:
```
2023-03-20T12:22:25.763Z: Background process Win32 socket proxy exited with status 1 signal null
2023-03-20T12:22:25.763Z: Background process Win32 socket proxy will restart.
2023-03-20T12:22:26.470Z: Launching background process Vtunnel Host Process.
2023-03-20T12:22:26.938Z: Launching background process Win32 socket proxy.
```
![jserror](https://user-images.githubusercontent.com/33824904/227175520-9385af96-308c-43c3-946b-dc0cebc89a84.PNG)
![rderror](https://user-images.githubusercontent.com/33824904/227175829-d056ba05-3d1f-4be7-ae62-004c9b2315d3.PNG)

### Expected Behavior

Rancher Dekstop & Kubernetes starts without errors

### Additional Information

Related issues, but with slightly different errors
https://github.com/rancher-sandbox/rancher-desktop/issues/3815
https://github.com/rancher-sandbox/rancher-desktop/issues/2181

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

v.1.26.0

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

PulseSecure VPN

**Comment by toddnni** [comment]
Some previous discussion and issue links in #4013

**Comment by Nino-K** [comment]
Can you please try our newer releases (1.13.1) with network tunnel options enabled? I'm going to close this issue, if you encounter anything further feel free to re-open.
