### ISSUE TITLE
Failing `bats` test for uninstalling RDX container

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4299]
### Actual Behavior

#4271 introduced some `bats` tests to test the part of the RDX code that runs extension (backend) containers in the VM. Unfortunately, one of the new tests (`compose - uninstall`) fails each time I run it.

### Steps to Reproduce

1. `git clean -ffdx; npm install; npm run build; npm run package`
2. `cd bats`
3. `bats --show-output-of-passing-tests ./tests/extensions/containers.bats`

### Result

The last test fails:
```
 ✗ compose - uninstall
   (from function `refute_line' in file tests/extensions/../helpers/../../bats-assert/src/refute_line.bash, line 245,
    in test file tests/extensions/containers.bats, line 94)
     `refute_line --partial "$(id vm-compose)"' failed
   Created

   -- no line should contain substring --
   substring : rd/extension/vm-compose
   index     : 1
   output (2 lines):
     CONTAINER ID    IMAGE                                       COMMAND                   CREATED         STATUS    PORTS    NAMES
   > 213454494998    docker.io/rd/extension/vm-compose:latest    "/bin/sh -c sleep inf"    1 second ago    Up                 rd-extension-rd_extension_vm-compose_web_1
   --
```

### Expected Behavior

All tests should pass.

### Rancher Desktop Version

c2a59cd8

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by mook-as** [comment]
I cannot reproduce with main @ 3595358a6665e4063434cf8982855b7a4069b98d — @adamkpickering, would you be able to re-test? I believe this should be fixed by the aforementioned PRs. Thanks! 

(OpenSUSE 15.4 VM, x86_64)

**Comment by mook-as** [comment]
The relevant error from the logs appears to be:

```
extensions.log     │2023-05-01T20:55:32.421Z: Failed to install extension rd/extension/vm-image, cleaning up: c [Error]: /opt/rancher-desktop/resources/resources/linux/bin/nerdctl exited with code 1
extensions.log     │    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:1:8347)
extensions.log     │    at ChildProcess.emit (node:events:527:28)
extensions.log     │    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
extensions.log     │  command: [
extensions.log     │    '/opt/rancher-desktop/resources/resources/linux/bin/nerdctl',
extensions.log     │    '--namespace',
extensions.log     │    'rancher-desktop-extensions',
extensions.log     │    'compose',
extensions.log     │    '--project-directory',
extensions.log     │    '/tmp/rd-nerdctl-copy-in-lkNoim',
extensions.log     │    '--project-name',
extensions.log     │    'rd-extension-rd_extension_vm-image',
extensions.log     │    '--env-file',
extensions.log     │    '/tmp/rd-nerdctl-compose-up-ehKobK',
extensions.log     │    'up',
extensions.log     │    '--quiet-pull',
extensions.log     │    '--detach'
extensions.log     │  ],                                                                                                                                                                                                                                                                                             
extensions.log     │  stdout: '',                                                                                                                                                                                                                                                                                    
extensions.log     │  code: 1,                                                                                                                                                                     
```
The matching stderr is probably:
```
nerdctl.log        ┌time=2023-05-01 20:55:31.000000 level=fatal msg="name Does not match pattern '^[a-z0-9][a-z0-9_-]*$'"
nerdctl.log        └Error: exit status 1
```

I _think_ this means that the `name` field in `compose.yaml` was invalid.

The metadata should have no compose file specified:
https://github.com/rancher-sandbox/rancher-desktop/blob/09b1f0f76641dbed8f925ba3487db4c981a20fff/bats/tests/extensions/testdata/vm-image.json#L1-L7

In that case, we should be generating a name that matches the expression:
https://github.com/rancher-sandbox/rancher-desktop/blob/09b1f0f76641dbed8f925ba3487db4c981a20fff/pkg/rancher-desktop/main/extensions/extensions.ts#L229

We'll need to dig deeper to see why that isn't working correctly…

**Comment by adamkpickering** [comment]
I tested this again with a fresh build from current `main` (7503f5b8). It seems to be fine, so I'm going to close this. We can always reopen it if the problem shows up again.
