### ISSUE TITLE
Kubernetes portmapping reset after an hour

### ISSUE THREAD

**Issue by ThreePinkApples** [rancher-sandbox/rancher-desktop#4305]
### Actual Behavior

After upgrading from Rancher Desktop 1.7.0 to 1.8.1, my port mappings are reset after about 1 hour. This is running Kubernetes 1.24.10.

### Steps to Reproduce

I have not tried to do a clean setup, but I would assume it would produce the same issue
1. Install Rancher Desktop 1.8.1
2. Setup RabbitMQ (my setup was done using `skaffold`) 
```
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: rabbitmq
profiles:
  - name: rabbitmq
    deploy:
      helm:
        releases:
        - name: rabbitmq
          repo: https://charts.bitnami.com/bitnami 
          remoteChart: rabbitmq
          namespace: default
          wait: false
          overrides:
            auth:
              username: guest
              password: guest
            service:
              type: LoadBalancer
            featureFlags: stream_queue
```
3. Wait an hour or so

### Result

During startup, the port mapping for RabbitMQ is configured correctly and I am able to connect to it from outside the cluster:
```
2023/03/29 06:22:30 [DEBUG]   create port mapping for port 25672, protocol TCP
2023/03/29 06:22:30 [DEBUG]   create port mapping for port 15672, protocol TCP
2023/03/29 06:22:30 [DEBUG]   PortTracker Add status: map[4a6dd38a-bcce-4cb6-9f1c-8e025f678d0a:map[30550/TCP:[{HostIP:0.0.0.0 HostPort:30550}]] 54f34ce9-bd49-4707-959f-6b7101e65aef:map[] a8310f60-7db1-4946-980f-6af0ede7fa40:map[15672/TCP:[{HostIP:0.0.0.0 HostPort:15672}] 25672/TCP:[{HostIP:0.0.0.0 HostPort:25672}] 4369/TCP:[{HostIP:0.0.0.0 HostPort:4369}] 5672/TCP:[{HostIP:0.0.0.0 HostPort:5672}]]]
2023/03/29 06:22:30 [DEBUG]   kubernetes service: port mapping added default/rabbitmq:map[4369:TCP 5672:TCP 15672:TCP 25672:TCP]
2023/03/29 06:22:30 [DEBUG]   PortTracker Add status: map[1d8e8774-8a87-4ace-915a-f6a9f9ef7431:map[] 4a6dd38a-bcce-4cb6-9f1c-8e025f678d0a:map[30550/TCP:[{HostIP:0.0.0.0 HostPort:30550}]] 54f34ce9-bd49-4707-959f-6b7101e65aef:map[] a8310f60-7db1-4946-980f-6af0ede7fa40:map[15672/TCP:[{HostIP:0.0.0.0 HostPort:15672}] 25672/TCP:[{HostIP:0.0.0.0 HostPort:25672}] 4369/TCP:[{HostIP:0.0.0.0 HostPort:4369}] 5672/TCP:[{HostIP:0.0.0.0 HostPort:5672}]]]
```

But then, about one hour later, the mapping is deleted and re-added, but this time without any ports
```
2023/03/29 07:22:30 [DEBUG]   kuberentes service: port mapping deleted default/rabbitmq:map[]
2023/03/29 07:22:30 [DEBUG]   PortTracker Add status: map[1d8e8774-8a87-4ace-915a-f6a9f9ef7431:map[] 200bf76f-7945-4774-8dd3-d13ca371fb2e:map[30500/TCP:[{HostIP:0.0.0.0 HostPort:30500}]] 3b93bfd6-db4a-48ac-82a4-f15b8fde11b3:map[] 4a6dd38a-bcce-4cb6-9f1c-8e025f678d0a:map[] 4c9689dd-1bf1-4e8b-a982-0a925191f606:map[6379/TCP:[{HostIP:0.0.0.0 HostPort:6379}]] 54f34ce9-bd49-4707-959f-6b7101e65aef:map[] 94697686-ec67-4181-8bc6-acfcc04da7bd:map[] 9b376571-fc64-4071-9d1f-9f0a42fe3a9d:map[] 9cd7a48d-8b93-4cac-866b-e4904a048cb2:map[443/TCP:[{HostIP:0.0.0.0 HostPort:443}] 80/TCP:[{HostIP:0.0.0.0 HostPort:80}]] a8310f60-7db1-4946-980f-6af0ede7fa40:map[] ce5f375f-cbe1-4cad-8a09-19fde0a072e9:map[] ec73cc0e-f413-470b-84f4-9127a08c56af:map[] f5dcefb0-fcb0-4ed2-8698-30d01f02316a:map[]]
2023/03/29 07:22:30 [DEBUG]   kubernetes service update: default/rabbitmq has -0 +0 service port
2023/03/29 07:22:30 [DEBUG]   kubernetes service: port mapping added default/rabbitmq:map[]
2023/03/29 07:22:30 [DEBUG]   PortTracker Remove status: map[200bf76f-7945-4774-8dd3-d13ca371fb2e:map[30500/TCP:[{HostIP:0.0.0.0 HostPort:30500}]] 3b93bfd6-db4a-48ac-82a4-f15b8fde11b3:map[] 4a6dd38a-bcce-4cb6-9f1c-8e025f678d0a:map[] 4c9689dd-1bf1-4e8b-a982-0a925191f606:map[6379/TCP:[{HostIP:0.0.0.0 HostPort:6379}]] 54f34ce9-bd49-4707-959f-6b7101e65aef:map[] 94697686-ec67-4181-8bc6-acfcc04da7bd:map[] 9b376571-fc64-4071-9d1f-9f0a42fe3a9d:map[] 9cd7a48d-8b93-4cac-866b-e4904a048cb2:map[443/TCP:[{HostIP:0.0.0.0 HostPort:443}] 80/TCP:[{HostIP:0.0.0.0 HostPort:80}]] a8310f60-7db1-4946-980f-6af0ede7fa40:map[] ce5f375f-cbe1-4cad-8a09-19fde0a072e9:map[] ec73cc0e-f413-470b-84f4-9127a08c56af:map[] f5dcefb0-fcb0-4ed2-8698-30d01f02316a:map[]]
```

I can restart Rancher Desktop to restore the port mapping temporarily, but then it fails again after some time.

### Expected Behavior

Portmapping should continue to work "forever"

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.24.10

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 22H2 19045.2728

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by Nino-K** [comment]
@ThreePinkApples thanks for brining this up. This could be potentially related to https://github.com/rancher-sandbox/rancher-desktop-agent/issues/32 and there is a fix for it here: https://github.com/rancher-sandbox/rancher-desktop-agent/pull/33. 

It will be part of `1.9` for sure.

**Comment by jgavahan-widoc** [comment]
Our organization is seeing the same behavior.  This regression has a negative impact on our development teams' productivity and is a blocker for updating to the latest release. Is there an estimated timeline for the `1.9` milestone, or could this be backported into a `1.8` patch release?

**Comment by jgavahan-widoc** [comment]
> @Nino-K Our organization is seeing the same behavior. This regression has a negative impact on our development teams' productivity and is a blocker for updating to the latest release. Is there an estimated timeline for the `1.9` milestone, or could this be backported into a `1.8` patch release?

@Nino-K or @jandubois any thoughts on the timeline for a `1.9` release or a backport to `1.8` for this fix? Thanks!

**Comment by Nino-K** [comment]
@jgavahan-widoc we are aiming to get the release out today. Thanks

**Comment by sherland** [comment]
The 1.9-tech-preview was released 3 weeks ago, but I assume not everyone should update to that version to get the fix?

When is release 1.9 expected? - Optionally, what's the most recent stable release can we run, that is not affected by the bug?

**Comment by jandubois** [comment]
> The 1.9-tech-preview was released 3 weeks ago, but I assume not everyone should update to that version to get the fix?

You should be able to run the tech-preview; but you will have to install it manually. It is not part of the auto-upgrade channel.  I'm not aware of any regressions between 1.8.1 and the tech preview.

> When is release 1.9 expected? - Optionally, what's the most recent stable release can we run, that is not affected by the bug?

I don't expect it for another month.
