### ISSUE TITLE
Port `v-clean-html` directive to Rancher Desktop

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4323]
> NOTE: I wouldn't consider this to be trusted content, so we might need to port over the `v-clean-html` directive from Dashboard.

_Originally posted by @rak-phillip in https://github.com/rancher-sandbox/rancher-desktop/pull/4298#discussion_r1151095439_

**Comment by jandubois** [comment]
This has been done already; not sure which PR, but #6233 is using the `clean-html` directive already.
