### ISSUE TITLE
Tray menu should be disabled at first run.

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/rancher-desktop#4325]
### Actual Behavior

It is possible to run the app for the first time and then open the tray menu and access to preferences dialog or main window.

### Steps to Reproduce

- run Rancher Desktop for the first time (clean all the user settings instead)
- click on the tray icon and open the preferences dialog

### Result

The user can access to app windows

### Expected Behavior

 First run dialog should be completed before the user can interact with the app.

### Rancher Desktop Version

1.8.0

### Rancher Desktop K8s Version

any

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

OpenSUSE

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I'm going to leave this in 1.9, assuming it is a simple fix. Otherwise it should go into 1.10 instead.
