### ISSUE TITLE
Experimental settings: Virtual Machine - Volumes tab

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#4333]
### Problem Description

Add the new experimental setting `experimental.virtual-machine.mount.type` to the Virtual Machine page on Linux and MacOS.

### Proposed Solution

- Add a new "Hardware" tab
- Move the content on the Virtual Machine page into the tab
- Create a new "Volumes" tab
- Add the following setting to the tab on Linux:
  - experimental.virtual-machine.mount.type
    - Type: string
    - Options: [reverse-sshfs, 9p]
    - Default value: reverse-sshfs
    - Location: "Virtual Machine", tab "**Volumes**"
    - Choosing "9p" makes the following settings available:
      - experimental.virtual-machine.mount.9p.cache-mode
        - Type: string
        - Options: [none, loose, fscache, mmap]
        - Default value: mmap
      - experimental.virtual-machine.mount.9p.msize-in-kb
        - Type: integer
        - Min value: 4
        - Default value: 128
      - experimental.virtual-machine.mount.9p.protocol-version
        - Type: string
        - Options: [9p2000, 9p2000.u, 9p2000.L]
        - Default value: 9p200.L
      - experimental.virtual-machine.mount.9p.security-model
        - Type: string
        - Options: [passthrough, mapped-xattr, mapped-file, none]
        - Default value: none
-  Add the following setting to the tab on MacOS:
   - experimental.virtual-machine.mount.type
     - Type: string
     - Options: [reverse-sshfs, 9p, virtiofs] <- **!One option more than Linux!**
     - Default value: reverse-sshfs
     - Location: "Virtual Machine", tab "**Volumes**"
     - Choosing "9p" makes the following settings available:
       - experimental.virtual-machine.mount.9p.cache-mode
         - Type: string
         - Options: [none, loose, fscache, mmap]
         - Default value: mmap
       - experimental.virtual-machine.mount.9p.msize-in-kb
         - Type: integer
         - Min value: 4
         - Default value: 128
       - experimental.virtual-machine.mount.9p.protocol-version
         - Type: string
         - Options: [9p2000, 9p2000.u, 9p2000.L]
         - Default value: 9p200.L
       - experimental.virtual-machine.mount.9p.security-model
         - Type: string
         - Options: [passthrough, mapped-xattr, mapped-file, none]
         - Default value: none
- Make sure the "Experimental" label is shown next to the setting

**Comment by IsaSih** [comment]
Acceptance Criteria is met. All test passed
