### ISSUE TITLE
Experimental settings: Virtual Machine - Network tab

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#4334]
### Problem Description

Add the new experimental setting `experimental.virtual-machine.socket-vmnet` to the Virtual Machine page on MacOS.

### Proposed Solution

- Add a new "Network" tab
- Add the following setting to the tab:
  - experimental.virtual-machine.socket-vmnet
    - Type: boolean
    - Default value: false
    - Location: page "Virtual Machine", tab "**Network**"
 - Make sure the "Experimental" label is shown next to the setting

**Comment by IsaSih** [comment]
Tests pass on MacOS Monterey
