### ISSUE TITLE
RDX: Installing trivy extension with version tag fails

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4349]
Installing trivy extension with version tag fails with below error message. This is on the branch https://github.com/mook-as/rd/tree/extensions/host-apis

```
>rdctl extension install aquasec/trivy-docker-extension:0.4.6
Internal Server Error
{"message":"500 Internal Server Error"}
```

**Comment by jandubois** [comment]
Note that the `latest` tag for the extension is over a year old, `0.4.6` is from 6 months ago. So the issue is not the tag itself, but the actual image.

FWIW, I can pull the image normally, I just can't install it as an extension.

**Comment by gunamata** [comment]
I tried installing an another extension `rdctl extension install prakhar1989/dive-in:0.0.8` and it fails with the same error as well. I see below messages in the extension.log

```
2023-04-03T22:46:57.023Z: Failed to install extension prakhar1989/dive-in:0.0.8, cleaning up: SpawnError: C:\2023\rancher-desktop\resources\win32\bin\docker.exe exited with code 1
    at ChildProcess.<anonymous> (C:\2023\rancher-desktop\dist\app\background.js:46247:20)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    'C:\\2023\\rancher-desktop\\resources\\win32\\bin\\docker.exe',
    'cp',
    '--follow-link',
    'fdf37b80a174aba3cad8e3e22d804c2d8e1669bdca59941e9b25e8eb86759830:/.',
    'C:\\Users\\GUNASE~1\\AppData\\Local\\Temp\\rd-ext-install-tdXVfx'
  ],
  code: 1,
  [Symbol(child-process.command)]: 'C:\\2023\\rancher-desktop\\resources\\win32\\bin\\docker.exe cp --follow-link fdf37b80a174aba3cad8e3e22d804c2d8e1669bdca59941e9b25e8eb86759830:/. C:\\Users\\GUNASE~1\\AppData\\Local\\Temp\\rd-ext-install-tdXVfx'
}
```

**Comment by mook-as** [comment]
(I'm on macOS)

For trivy:
> '/usr/bin/tar: ./etc/ssl1.1/ct_log_list.cnf: File removed before we read it\n'

For dive-in:
That installed fine, though the UI has issues (`TypeError: Cannot read properties of undefined (reading '0')`) — it sounds like our `listImages` implementation is incorrect).

**Comment by mook-as** [comment]
Spawned #4415 on the `listImages` issue.

**Comment by mook-as** [comment]
Assigning to @gunamata to verify
