### ISSUE TITLE
Move to NodeJS 16

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#438]
From comments on Slack I gather that @mook-as and @ericpromislow are using NodeJS 15.* for current development.

NodeJS 15 has been end-of-lifed since June 1st 2021: [NodeJS Releases](https://nodejs.org/en/about/releases/).

RD for Silicon will require NodeJS 16 as well: https://github.com/rancher-sandbox/rancher-desktop/issues/16#issuecomment-881741749

**Comment by mook-as** [comment]
See also #994 where we have a PR for the GitHub Actions parts.
