### ISSUE TITLE
RDX: Replace `BrowserView.webContents.destroy()` with `BrowserView.webContents.close()`

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4394]
We had to implement the undocumented `webContents.destroy()` method in order to resolve #4393.

Later versions of electron provide a `webContents.close()` but we will need to update our electron version before we can consume this method. 

### Reference

https://github.com/electron/electron/pull/35509

**Comment by rak-phillip** [comment]
@gunamata @jandubois Dropping from epic & moving to 1.10

**Comment by gaktive** [comment]
Epic referred to #4580
