### ISSUE TITLE
Docker Daemon unable to start

### ISSUE THREAD

**Issue by rajikulk55** [rancher-sandbox/rancher-desktop#4412]
### Actual Behavior

Hello,
I have recently started using Rancher Desktop v1.8.1. When I use the command docker ps - I get the following error message:
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.

Please help

### Steps to Reproduce

installed  rancher desktop
wsl v2.0 
docker ps

### Result

error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.

### Expected Behavior

should start the docker

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.26.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by s0nea** [comment]
Hi @rajikulk55,

Thank you for creating the issue!

In your bug report you mentioned:

> Which container engine are you using?
> containerd (nerdctl)

Could you please change the container engine to `dockerd (moby)` and check if the issue persists? Please find some more information on how to change the container engine here: https://docs.rancherdesktop.io/ui/preferences/container-engine#general

Thank you :slightly_smiling_face:

**Comment by gunamata** [comment]
@rajikulk55 @Pedro-luis-de-lucena - It looks like you are running into this because you are using docker client when `containerd` is selected as the container engine in Rancher Desktop. With `containerd`, you need to use nerdctl (which comes bundled with Rancher Desktop) to interact with the container engine.

Can you try running docker commands (ex: `docker images`, `docker ps`) with `dockerd(moby)` as the selected container engine and let us know if you see issues?

**Comment by s0nea** [comment]
No further comments have been added, so I assume the issue has been resolved. I'm going to close the issue for now. Please re-open it, if you're experiencing the problem again.

**Comment by espinoleandroo** [comment]
> Hi @rajikulk55,
> 
> Thank you for creating the issue!
> 
> In your bug report you mentioned:
> 
> > Which container engine are you using?
> > containerd (nerdctl)
> 
> Could you please change the container engine to `dockerd (moby)` and check if the issue persists? Please find some more information on how to change the container engine here: https://docs.rancherdesktop.io/ui/preferences/container-engine#general
> 
> Thank you 🙂

It worked for me; I've changed the container engine (nerdctl -> moby), and now I can create my images.

**Comment by castillouparela** [comment]
Hi, I'm currently experiencing the same issue. I'm using Rancher Desktop version 1.20.0 with WSL version 2.6.1.0 and an Ubuntu 22.04.3 LTS image. Additionally, I tried accessing the following link, but it appears to be no longer available: https://docs.rancherdesktop.io/ui/preferences/container-engine#general. I appreciate any support you can provide on this matter.

**System details:**
- WSL version: 2.6.1.0
- Kernel version: 6.6.87.2-1
- WSLg version: 1.0.66
- MSRDC version: 1.2.6353
- Direct3D version: 1.611.1-81528511
- DXCore version: 10.0.26100.1-240331-1435.ge-release
- Windows version: 10.0.26100.6584
