### ISSUE TITLE
Adjust color of extension icons for light/dark schema

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4421]
Some icons are effectively invisible (Epinio in light mode, Tachometer in dark mode).

Maybe the color of the SVG images can be adjusted based on mode, at least for monochrome icons?

**Comment by rak-phillip** [comment]
Is this resolved by #4459?

**Comment by jandubois** [comment]
> Is this resolved by #4459?

I believe it is, thanks!
