### ISSUE TITLE
Extension details page for installed extension shows Install instead of Uninstall button

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4422]
If the extension is already installed, there is no point in installing it again; the button should now Uninstall it:

<img width="1045" alt="CleanShot 2023-04-11 at 11 11 40@2x" src="https://user-images.githubusercontent.com/78947/231252910-84348f2d-729c-4da0-99ff-a92fd14e4c6d.png">

I've seen this work before, so it seems like a regression.

**Comment by rak-phillip** [comment]
Regressed with the inclusion of versioned tags for extensions in #4399
