### ISSUE TITLE
Kim: Image scanning: Handle partial lines correctly

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#443]
I see this in a run:
```
INFO Detecting Alpine vulnerabilities...

2021-07-30T21:06:15.491Z
	[34mINFO[0m
	Number of language-specific files: 0


Target: moby/buildkit:v0.8.3 (alpine 3.12.7)
```

I suspect that's because `addData` got called with half a line somewhere.

_Originally posted by @mook-as in https://github.com/rancher-sandbox/rancher-desktop/pull/409#discussion_r680265983_

**Comment by gaktive** [comment]
Kim was removed from Rancher Desktop prior to 1.x. Closing this as it is no longer necessary.
