### ISSUE TITLE
Kim: Image Scanning: Parse one result at a time

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#444]
Currently, we convert trivy output to one giant JSON blob, and then read it all at once.  It would be better if we emit line-oriented JSON instead (that is, one entry per line), so that we can emit results as soon as we get them.

_Originally posted by @mook-as in https://github.com/rancher-sandbox/rancher-desktop/pull/409#discussion_r680270543_

**Comment by gaktive** [comment]
Kim was removed from Rancher Desktop prior to 1.x. Closing this as it is no longer necessary.
