### ISSUE TITLE
Move RDX Install button to top row

### ISSUE THREAD

**Issue by kwwii** [rancher-sandbox/rancher-desktop#4440]
### Problem Description

The button is too low

### Proposed Solution

Move the install button on a given RDX detail page to the top row, where the RDX title is.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/835961/233469499-f7b5716d-85bf-4a79-b0c7-2e85593e425a.png)

### Acceptance Criteria

- [ ] On the Extensions Details page, the install button should be located inline with the header section of the page, aligned to the right.
- [ ] The location of the install button should be tested on different window sizes and resolutions to ensure that it is always inline with the header.
- [ ] The button behavior should have no regressions.

**Comment by kwwii** [comment]
If we add the logo and version number to the title, we can remove this box.  The links can go to the bottom of the page

**Comment by rak-phillip** [comment]
@gunamata @jandubois Dropping from epic & closing
