### ISSUE TITLE
K8s: Create method to spawn children

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#445]
We have a few places where we want to run some command on the VM and capture the result; the newest is in kim where we run a scan.  We should add a method on `KubernetesBackend` to make it easier to keep the backend specifics in the backend instead.

_Originally posted by @mook-as in https://github.com/rancher-sandbox/rancher-desktop/pull/409#r680249793_

**Comment by gaktive** [comment]
Kim was removed from Rancher Desktop prior to 1.x. Closing this as it is no longer necessary.
