### ISSUE TITLE
Change rancher-desktop-extensions namespace to rdx

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4453]
This is maybe just nit-picking, but the name is rather long when you filter the image list by namespace. If we want to change it, we should do it before we release the first time, so users don't end up with orphaned images.

<img width="366" alt="CleanShot 2023-04-13 at 22 26 58@2x" src="https://user-images.githubusercontent.com/78947/231949415-40a649c6-30d1-40d7-9489-0ec395fc1dab.png">

**Comment by mook-as** [comment]
I'm mildly against this because it's not obvious what "rdx" refers too (it's actually hard to tell it's even related to rancher desktop).  `k8s.io` works only because they own that domain.
