### ISSUE TITLE
After Install, Context not set and unable to connect to docker daemon

### ISSUE THREAD

**Issue by Stargator** [rancher-sandbox/rancher-desktop#4457]
### Actual Behavior

One of my co-workers (on Windows 10) has an issue after installing Rancher Dekstop. They are using version 1.8.1.

Context is set to default instead of set to rancher-desktop and even after manually creating a context for rancher-desktop, they are unable to use docker CLI because the docker daemon cannot be reached.

They updated the Container Engine to dockerd, so that's not an issue.

I'm at the limit of my docker knowledge, so I don't know what this could be.

### Steps to Reproduce

They installed 1.8.1 this week and then updated Container Engine to dockerd. Tried to run a docker command like `docker images` and it says the docker daemon cannot be reached.

This is on Windows. Nothing else was done.

### Result

This is from the user that's on Windows:

Note, Context is set to default and the error in the Server section.

![Rancher-Desktop_Issue](https://user-images.githubusercontent.com/7527155/232090815-793558df-7a86-4474-86ff-663e5b9a4b39.png)

The User is seeing this issue immediately after installing Rancher Desktop:

> `docker images`
> error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/json": open //./pipe/docker_engine: The system cannot find the file specified.
> 
> `docker info`
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.10.4
>     Path:     C:\Users\happer\.docker\cli-plugins\docker-buildx.exe
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.16.0
>     Path:     C:\Users\happer\.docker\cli-plugins\docker-compose.exe
> 
> Server:
>  Containers: 0
>   Running: 0
>   Paused: 0
>   Stopped: 0
>  Images: 0
>  Server Version: 20.10.21
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
>  runc version: 5fd4c4d144137e991c4acebb2146ab1483a97925
>  init version:
>  Security Options:
>   seccomp
>    Profile: default
>   cgroupns
>  Kernel Version: 5.15.90.1-microsoft-standard-WSL2
>  Operating System: Rancher Desktop WSL Distribution
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 8
>  Total Memory: 7.631GiB
>  Name: DESKTOP-A0F18HK
>  ID: UDYI:W2BN:4K63:UBFA:DUR5:6HMM:DDCJ:BGKE:5GJ5:HUS3:MYLH:LRJL
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
> 
> WARNING: No swap limit support

### Expected Behavior

When I installed Rancher Desktop back in Oct/Nov, the Context was set to rancher-desktop and everything worked out of the box. This is their first time installing RD and I don't know if some changes impacted it.

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

N/A, Kubernetes is not enabled.

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Other (specify below)

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

We are using AppGate to VPN into our dev tools (GitLab/Jira). This VPN does not block traffic for us.

ZScalar is also used as a firewall. I have AppGate and ZScalar on my MacOS and I did not have the same issue as this co-worker who works from home. My MacOS ZScalar settings are definitely different from his.

**Comment by Stargator** [comment]
I have started experiencing this issue on my MacOS 12. The issue started when Rancher Desktop starts up there's an error displayed (see attached) related to Kubernetes.

Container Engine is set to `dockerd` and the context has been set to `rancher-desktop`, but this space issue seems to gummed up the works.

My HD has 120 GB free, so I don't understand the "No space left on device" nor the references to `nerdctl`.

> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.10.4
>     Path:     /Users/Stargator/.docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.16.0
>     Path:     /Users/Stargator/.docker/cli-plugins/docker-compose
> 
> Server:
> ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> errors pretty printing info

<img width="763" alt="Screen Shot 2023-04-14 at 4 10 27 PM" src="https://user-images.githubusercontent.com/7527155/232145875-9174cd73-d0ac-4040-ba6b-77bcafcfd812.png">

> stderr: 'scp: /tmp/rd-nerdctl-fEyGZD.nerdctl: No space left on device\n',
>   code: 1,
>   command: [
>      '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl',
>      'copy',
>      '/var/folders/lj/phrmpqfs2ld424jxh8y44w8m0000gn/T/rd-nerdctl-fEyGZD/nerdctl',
>      '0:/tmp/rd-nerdctl-fEyGZD.nerdctl'
>    ]
> }

**Comment by jandubois** [comment]
You may be out of space inside the VM. The data volume has a default maximum size of 100GiB, so if you created/pulled a lot of images, it may be full. You can check with

```console
$ rdctl shell df -h /mnt/data
Filesystem                Size      Used Available Use% Mounted on
/dev/disk/by-label/data-volume
                         97.9G      1.6G     91.2G   2% /mnt/data
```

If you are out of space, check if you can delete some images you no longer need. Also look into `nerdctl image prune` to remove unused images.

**Comment by Stargator** [comment]
I've already removed all the images and containers I had earlier this before this popup from Kubernetes appeared.

Thanks for the `rdctl` suggestion, I'll try that.

**Comment by Stargator** [comment]
This is the output, looks like a lot of space is taken up:

> Filesystem                Size      Used Available Use% Mounted on
> /dev/disk/by-label/data-volume
>                          97.9G     93.1G         0 100% /mnt/data

**Comment by Stargator** [comment]
@jandubois Will a `rdctl factory-reset` clear out the VM data? And are there other options?

I'm not too bummed if I have to do a factory-reset, I'm confident I can get everything back as before.

But I've been using RD for months whereas two co-workers just started using RD and have run into something similar immediately after installation, so I think my issue is not related to theirs.

**Comment by jandubois** [comment]
> Will a `rdctl factory-reset` clear out the VM data?

Yes, it will delete the VM and all data. The VM will be recreated with an empty data volume on the next start.

**Comment by Stargator** [comment]
Ran the factory-reset and RD is running fine, no Kubernetes error. As mentioned, I had already removed all the extra image and containers.

When I got the error I only had one image and one container left.

Not sure how I could clear up the VM outside of `docker rmi` and `docker rm` commands.

**Comment by prlyons** [comment]
I have a similar issue on Windows 11. I installed Rancher Desktop. No errors on starting up, but when I run docker images on a command prompt I see:

> error during connect: Get http://localhost:2375/v1.24/images/json: dial tcp [::1]:2375: connectex: No connection could be made because the target machine actively refused it.

**Comment by prlyons** [comment]
My issue appears fixed after doing running "wsl --shutdown" in powershell and restarting Rancher Desktop.

**Comment by Illutax** [comment]
> Run a "docker context inspect" and delete your old folder (storage/metadataPath) that should be c:\Users\xxxx\.docker\
Didn't work for me.

But uninstalling Docker-Desktop & Rancher-Desktop and installing Rancher-Desktop again fixed it for me.

**Comment by jandubois** [comment]
After reviewing all comments here it seems the issue was always either due to an out-of-space error that was resolved by a factory reset, or a conflict with a Docker Desktop installation that had been resolved by user.

It looks there are no remaining action items for the Rancher Desktop team, so I'm going to close this issue.

**Comment by Illutax** [comment]
> After reviewing all comments here it seems the issue was always either due to an out-of-space error that was resolved by a factory reset, or a conflict with a Docker Desktop installation that had been resolved by user.
> 
> It looks there are no remaining action items for the Rancher Desktop team, so I'm going to close this issue.

In the case of an conflict with docker desktop, it would be nice if the factory reset of Rancher Desktop would also fix the issue in `~/.docker`.

**Comment by JayJay1989** [comment]
On a new device with clean Windows 11, installing Rancher-desktop (without having previously installed docker) having following error after install.

![Image](https://github.com/user-attachments/assets/eb82061d-52ab-4ef7-a0a6-baba271038a5)

After reinstalling Rancher it works fine.
