### ISSUE TITLE
Screenshot of extension displaying incorrect information

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4465]
### Actual Behavior

Screenshot of Logs Explorer is displaying competitor name and personal data (an username).

### Steps to Reproduce

1. Launch Rancher Desktop
2. From the main window, access the Extensions catalog
3. Select Logs Explorer
4. Check information in the blue bar at the top of the Logs Explorer screenshot

### Result

<img width="713" alt="Screen Shot 2023-04-14 at 7 53 53 PM" src="https://user-images.githubusercontent.com/70187881/232179704-f4add53b-200a-4742-992e-d36afec69d78.png">

### Expected Behavior

Screenshot must cut the blue bar at the top of the image. The competitor name and personal data must not be displayed.

### Rancher Desktop Version

1.7.0-1041-g54242d2c

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
The screenshot is provided by the extension author and not by us and is embedded in the extension image (see https://hub.docker.com/extensions/docker/logs-explorer-extension).

Theoretically we could generate our own screenshots, but I'm not sure if this is the right thing to do, and it also becomes a maintenance issue as the catalog will include more extensions.

We will not consider this a bug for the tech preview release.

**Comment by IsaSih** [comment]
I understand. I am just concerned with the use of Docker trademarks the way they are being exposed in our product, even if the image is provided by external source. Here are the trademark guidelines (https://www.docker.com/legal/trademark-guidelines/)
