### ISSUE TITLE
rdx-proxy docker image can be deleted via UI

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4466]
### Actual Behavior

By bulk deleting the docker images via UI, rdx-proxy image can be deleted.

### Steps to Reproduce

1. Pull nginx and python
2. From the main window, go to images and select all images
3. Click delete
4. Check if `ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest` is deleted

### Result
![rdx-proxy-docker-image](https://user-images.githubusercontent.com/70187881/232180683-208aba15-cc80-46df-a409-cd0ee319f818.gif)

### Expected Behavior

`ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest` image should not be deleted.

### Acceptance Criteria
- [x] When the user selects the image `ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest` in the Images Table and attempts to perform a bulk delete action, the delete action should skip this row.
- [x] When the user selects the image `ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest` in the Images Table and attempts to delete the image using the delete button, the delete action should be disabled for this row.
- [x] The user should be able to select and delete other images from the Images Table using the bulk delete option or the delete button without any issues.
- [x] The image `ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest` should continue to be displayed in the Images Table after the user performs bulk delete action.
- [ ] Any attempt to delete the image `ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest` from the Images Table using any other means should result in an error message indicating that the action is not allowed.
- [ ] Each point above should also apply for installed RDX extensions

### Rancher Desktop Version

1.7.0-1041-g54242d2c

### Rancher Desktop K8s Version

1.24.12

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
rdx-proxy should be treated like a system image in the 1.9 release; doesn't have to be fixed in the tech preview.

Is the image automatically reinstalled on next start?

**Comment by IsaSih** [comment]
Moving back to "to do" because the 2 last acceptance criteria are not being accomplished. User can delete the RDX images via CLI, however, the images restart with Rancher Desktop. 
Secondly, user is able to delete RDX installed images via UI, as illustrated in the attached gif.

**Comment by IsaSih** [comment]
@rak-phillip

**Comment by jandubois** [comment]
> the 2 last acceptance criteria are not being accomplished. User can delete the RDX images via CLI,

That is unavoidable, and not covered by the acceptance criteria:

>> Any attempt to delete [...] from the Images Table

We only prevent deletion from the UI, not the CLI.

> however, the images restart with Rancher Desktop.

Not sure what you mean here. The images are being **reinstalled**? That should indeed happen during a restart and is expected.

**Comment by rak-phillip** [comment]
The ability to delete installed images looks to have regressed with the removal of `extensions/list` in #4590. Working on a fix.

Regarding the acceptance criteria `Any attempt to delete the image ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest from the Images Table using any other means should result in an error message indicating that the action is not allowed.`, this sounds like a gap between the acceptance criteria and how Rancher Desktop actually functions. I'm guessing that we need to modify the acceptance criteria so that it correctly describes reality.

**Comment by IsaSih** [comment]
All acceptance criteria is now met. Tests passed
