### ISSUE TITLE
Extension catalog should display all screenshots for an extension

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4479]
`com.docker.extension.screenshots` is a list, not a single screenshot.

You can see how Dockerhub allows you to cycle through all the screenshots:

![CleanShot 2023-04-17 at 16 13 30@2x](https://user-images.githubusercontent.com/78947/232629902-f4314138-5cab-4372-9e60-b5110f307f17.png)

From https://hub.docker.com/extensions/docker/logs-explorer-extension

(note how Dockerhub does not correctly adjust the height of the screenshot area as you resize the width of the window).

### Acceptance Criteria

- [ ] The Extension Details page should display all screenshots for an extension in a carousel.
- [ ] The carousel should cycle screenshots either manually or automatically.
- [ ] The carousel should display each screenshot at a size and resolution that is clear and easy to view.
- [ ] The carousel should include navigation buttons that allow the user to move forward or backward through the screenshots, or jump directly to a specific screenshot.
- [ ] The carousel should include an indicator that displays which screenshot is currently being viewed.
- [ ] The carousel should be responsive and adjust its size and layout to fit the window, regardless of size.

**Comment by rak-phillip** [comment]
@gunamata @jandubois Dropping from epic & closing
