### ISSUE TITLE
If Kubernetes version malformed there is error loading

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#448]
<img width="372" alt="Screen Shot 2021-08-04 at 3 22 17 PM" src="https://user-images.githubusercontent.com/62991/128243940-8fa0ada9-2aed-43b2-9432-5f7c87a2cc66.png">

Somehow the Kubernetes version was saved to setting with the +k3s1 on the version name. This caused an error loading as this is not a known version.

**Comment by mook-as** [comment]
Odd, the `Error in saved settings.json file` string was removed in 7bdbcf075ff21aea61927dff257e4724ce633393; so it shouldn't be possible to get _that_ dialog…

**Comment by mattfarina** [comment]
This should be fixed now.
