### ISSUE TITLE
Catalog entries show "Invalid Date" for "Latest Update"

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4483]
This happens for Logs Explorer and Tachometer, but not Epinio. It seems the date is derived from the `UpdatedAt` metadata field.

There are also separate per-platform "Updated" fields lower in the sidebar. This seems like an excessive amount of information for the end-user. Just the version number and one date should be enough.
![CleanShot 2023-04-17 at 23 28 55@2x](https://user-images.githubusercontent.com/78947/232691645-82ddb979-850b-4fed-b6d0-63efedb93c3f.png)

### Acceptance Criteria

- [ ] The Latest Update field should not be displayed on the page if the `Updated` property contains an invalid date
- [ ] The Platforms field is not included in the metadata for the Extension Details page

**Comment by rak-phillip** [comment]
We should also omit the `Links` header if an extension doesn't have any available.

**Comment by rak-phillip** [comment]
@gunamata @jandubois Dropping from epic & closing
