### ISSUE TITLE
Separator line between menu and extensions should not touch the sides

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4484]
It looks wrong to me that the separator line touches the sides, effectively creating 2 separate boxes. I thing the line should leave a gap on the left and right, similar how horizontal separators are used inside the page client area:

![CleanShot 2023-04-17 at 23 38 26@2x](https://user-images.githubusercontent.com/78947/232693387-86d75020-1f55-4941-8460-0edbbc87e789.png)

There is also a separate issue if "Extensions" should be above or below the line. We used to have it below the line, so it would work as a heading for the individual extension entries below (I believe @gunamata did prefer that arrangement).

The reason to move it above the separator was to keep it with the other regular "menu" entries, as it is also the page to list extensions from the catalog, to install and uninstall them.

**Comment by manuelecarlini** [comment]
Related to this issue
https://github.com/rancher-sandbox/rancher-desktop/issues/4467

**Comment by jandubois** [comment]
This issue is now obsolete with the work being done in #4485.
