### ISSUE TITLE
Scrollbar for extensions

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4485]
If the list of installed extensions does not fit on the screen, then the list is simply cut off and the only way to make them visible is to resize the window. This will run into a limit if the list of extension is longer than the vertical display size.

Should the extension list become scrollable? If yes, should the scroll area be just the extension names, or should the regular menu items scroll out of view as well?

The window should also have some minimum size, e.g. to keep the regular menu plus space for one extension visible at all times.

**Comment by manuelecarlini** [comment]
@jandubois I've discussed with the team, here's a prototype with 3 options
[](https://xd.adobe.com/view/b5658d4d-02f7-4798-88f7-2be19226345b-e036/)

(My favorite is A)

**Comment by jandubois** [comment]
@manuelecarlini You didn't attach (or link to) the prototype.

**Comment by manuelecarlini** [comment]
Sorry @jandubois now it's there

**Comment by jandubois** [comment]
Just to make sure I understand the differences between the 3 options:

(1) has an "Installed Extensions" header in its own little box
(2) has no additional header
(3) shows the header inside the box with the list of extensions

Is is not clear to me if in (3) it would be included in the scrollable region. If it isn't, then it is almost the same as (1), but just missing the horizontal line below the header?

I think I prefer (2), as the header seems redundant when the last menu entry is also "Extensions", but don't really feel strongly about it.

**Comment by manuelecarlini** [comment]
@jandubois Yes, for the scrollbar position we have to consider Epinio as the first element, the scrollbar won't impact the title section. 
Anyway, I've updated the mockup to avoid confusion.

Option number 3 is like the number 1, but the font size for extensions is the same for the regular menu (while the other options are smaller)

**Comment by manuelecarlini** [comment]
@jandubois @kwwii those are the variation discussed yesterday
https://xd.adobe.com/view/659a93d0-1a43-4ba0-a847-612f0ac1b56b-30c9/

**Comment by jandubois** [comment]
Thank you! I assume the difference between open B and C is that B has a grey background for the scrollable region.

I don't think the different background is needed because the scrollable region also has a horizontal border on top. The grey background also conflicts with putting a grey background behind a single extension when that becomes the active page, so I think C is the best choice.
