### ISSUE TITLE
Extensions Screenshots: Automate install of extensions 

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4495]
The portion of the screenshots script that needs to install extensions during setup is unable to complete because default settings are applied to enable the Image Allow List with `rancher/example`. This default setting disallows installing new extensions

* https://github.com/rancher-sandbox/rancher-desktop/blob/82d0544a29065f9dfa2e7ea36027b11509e84f9b/screenshots/screenshots.e2e.spec.ts#L24
* https://github.com/rancher-sandbox/rancher-desktop/blob/82d0544a29065f9dfa2e7ea36027b11509e84f9b/screenshots/screenshots.e2e.spec.ts#L53-L54

**Comment by ericpromislow** [comment]
Got a failure on macos:
```
Running 2 tests using 1 worker


  ✘  1 screenshots.e2e.spec.ts:68:3 › Main App Test › Main Page (2ms)
Skipping packaging logs, not running in Cirrus CI
  -  2 screenshots.e2e.spec.ts:110:3 › Main App Test › Preferences Page


  1) screenshots.e2e.spec.ts:68:3 › Main App Test › Main Page ======================================

    Error: expect(received).toBeVisible()
    Call log:
      - expect.toBeVisible with timeout 30000ms
      - waiting for selector "[data-test="extension-nav-epinio"]"


      56 |     const navExtension = page.locator('[data-test="extension-nav-epinio"]');
      57 |
    > 58 |     await expect(navExtension).toBeVisible({ timeout: 30000 });
         |                                ^
      59 |   });
      60 |
      61 |   test.afterAll(() => {

        at /Users/ericp/workspace/rancher/desktop/screenshots/screenshots.e2e.spec.ts:58:32


  1 failed
    screenshots.e2e.spec.ts:68:3 › Main App Test › Main Page =======================================
  1 skipped

```

**Comment by rak-phillip** [comment]
We can install extensions by adding the following to `test.beforeAll` in `screenshots/screenshots.e2e.spec.ts`

```
    // await tool('rdctl', 'extension', 'install', 'ghcr.io/rancher-sandbox/epinio-desktop-extension:0.0.12');
    // await tool('rdctl', 'extension', 'install', 'docker/logs-explorer-extension:0.2.2');
```

Similarly, we can delete extensions when we are finished collecting screenshots with `test.afterAll`

```
    // await tool('rdctl', 'extension', 'uninstall', 'ghcr.io/rancher-sandbox/epinio-desktop-extension:0.0.12');
    // await tool('rdctl', 'extension', 'uninstall', 'docker/logs-explorer-extension:0.2.2');
```

**Comment by rak-phillip** [comment]
> Got a failure on macos:
> 
> ```
> Running 2 tests using 1 worker
> 
> 
>   ✘  1 screenshots.e2e.spec.ts:68:3 › Main App Test › Main Page (2ms)
> Skipping packaging logs, not running in Cirrus CI
>   -  2 screenshots.e2e.spec.ts:110:3 › Main App Test › Preferences Page
> 
> 
>   1) screenshots.e2e.spec.ts:68:3 › Main App Test › Main Page ======================================
> 
>     Error: expect(received).toBeVisible()
>     Call log:
>       - expect.toBeVisible with timeout 30000ms
>       - waiting for selector "[data-test="extension-nav-epinio"]"
> 
> 
>       56 |     const navExtension = page.locator('[data-test="extension-nav-epinio"]');
>       57 |
>     > 58 |     await expect(navExtension).toBeVisible({ timeout: 30000 });
>          |                                ^
>       59 |   });
>       60 |
>       61 |   test.afterAll(() => {
> 
>         at /Users/ericp/workspace/rancher/desktop/screenshots/screenshots.e2e.spec.ts:58:32
> 
> 
>   1 failed
>     screenshots.e2e.spec.ts:68:3 › Main App Test › Main Page =======================================
>   1 skipped
> ```

Did you install the epinio extension before running?
