### ISSUE TITLE
Epic: Container management dashboard

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4506]
A container management dashboard for Rancher Desktop will simplify the process of overseeing and controlling containers, allowing for quick access to common container details and management activities. 

## View containers
   - Display a comprehensive list of containers
   - Provide information such as container name, state, image, creation date, and ports
   - Quick access for for container management, allowing for start/stop, pause/resume, or delete actions

## Manage Containers
   - Start/Stop containers: Allow users to initiate or terminate container instances
   - Pause/Resume containers: Enable users to temporarily halt or resume container execution
   - Delete containers: Provide the ability to remove containers from the system

## View container details
   - Present detailed information about a specific container
   - Include metadata such as container ID, creation date, labels, environment variables, and networks

### View logs
   - Access and display logs generated by containers
   - Show logs in real-time or allow users to retrieve history

### Resource utilization
   - Provide insights into container resource utilization, such as CPU utilization, memory consumption, and disk usage
   - Display resource usage metrics in a visually appealing and easily understandable format

### Volume mounts
   - Display container volumes and their mount points

### Port mapping
   - Display port mappings for containers

## Backend

- [x] #5096

## Frontend

- [x] #5258
- [ ] #5308
- [ ] #5714
- [x] #5716
- [ ] #5759
- [x] #5761
- [ ] #5775
- [ ] #5841 
## 📖 References

- https://docs.docker.com/desktop/extensions-sdk/dev/api/reference/interfaces/DockerDesktopClient/

**Comment by rak-phillip** [comment]
@gunamata @jandubois Dropping from epic & moving to later

**Comment by jandubois** [comment]
@scures Please create a follow-up epic for the 1.12 milestone and close this issue once all still open issues have been transferred to the new epic!
