### ISSUE TITLE
Most bats tests hang on Linux

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4509]
### Actual Behavior

Various bats tests hang on Linux. They never exit, despite completing successfully when ctrl-C is pressed.

### Steps to Reproduce

1. Install the 7b3dc525 version of the rpm.
2. Check out 7b3dc525 of the repo.
3. Run the below commands, inserting the relevant test file in the place of `testFile`:

```
cd bats
bats <testFile>
```
The test files for which this is an issue are:
- ./tests/containers/host-connectivity.bats
- ./tests/containers/platform.bats
- ./tests/containers/run-rancher.bats
- ./tests/k8s/enable-disable-k8s.bats
- ./tests/k8s/helm-install-rancher.bats
- ./tests/k8s/traefik.bats
- ./tests/k8s/up-downgrade-k8s.bats
- ./tests/k8s/wordpress.bats
- ./tests/registry/creds.bats

### Result

The tests hang on the last step of each bats test file. hangs on the `ping host.rancher-desktop.internal from a container` step.

### Expected Behavior

The test should complete.

### Rancher Desktop Version

7b3dc525

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by jandubois** [comment]
@dpmerrill Please check if you can reproduce this!

**Comment by dpmerrill** [comment]
An explicit call to `rdctl shutdown` was added to helpers/load.bash to fix Linux hangs.
It seems to be working fine now.

**Comment by dpmerrill** [comment]
With the latest changes, the tests are running correctly now on Ubuntu.

**Comment by adamkpickering** [comment]
I ran into some hangs while looking at #4628. Looks like they're still happening for some of the tests I mentioned above. I went through the tests and determined which ones are still problematic:

- ./tests/k8s/helm-install-rancher.bats
- ./tests/k8s/up-downgrade-k8s.bats
- ./tests/k8s/wordpress.bats

I'm going to reopen this issue.
