### ISSUE TITLE
`image - install` bats test fails on Linux

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4510]
### Actual Behavior

The `image - install` bats test fails. Possibly related to #4511.

### Steps to Reproduce

```
cd bats
bats ./tests/extensions/containers.bats
```

### Result

```
rancher-desktop/bats> bats ./tests/extensions/containers.bats
containers.bats
 ✓ factory reset
 ✓ start container engine
 ✓ no extensions installed
 ✓ build extension testing images
 ✗ image - install
   (from function `rdctl' in file tests/extensions/../helpers/commands.bash, line 76,
    in test file tests/extensions/containers.bats, line 57)
     `rdctl api --method=POST "/v1/extensions/install?id=$(id vm-image)"' failed
   Internal Server Error
   {"message":"500 Internal Server Error"}
 ✗ image - check for running container
   (from function `assert_line' in file tests/extensions/../helpers/../../bats-assert/src/assert_line.bash, line 219,
    in test file tests/extensions/containers.bats, line 68)
     `assert_line --regexp "$(id vm-image).*[[:space:]]Up[[:space:]]"' failed

   -- no output line matches regular expression --
   regexp : rd/extension/vm-image.*[[:space:]]Up[[:space:]]
   output : CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES
   --

 ✓ image - uninstall
 ✓ compose - install
 ✓ compose - check for running container
 ✓ compose - uninstall

10 tests, 2 failures
```

### Expected Behavior

The test should pass.

### Additional Information

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11277639/logs.zip)

### Rancher Desktop Version

7b3dc525

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by mook-as** [comment]
Please attach logs (in the normal place when running BATS), thanks!

**Comment by adamkpickering** [comment]
Done!

**Comment by adamkpickering** [comment]
Done!

**Comment by mook-as** [comment]
`/opt/rancher-desktop/resources/resources/linux/bin/nerdctl --namespace rancher-desktop-extensions compose --project-directory /tmp/rd-nerdctl-copy-in-Lohmod --project-name rd-extension-rd_extension_vm-image --env-file /tmp/rd-nerdctl-compose-up-oHljfK up --quiet-pull --detach` exited with code `1`, likely because:

> `time=2023-04-19 21:13:44.000000 level=fatal msg="name Does not match pattern '^[a-z0-9][a-z0-9_-]*$'"`

Which probably means this is similar to #4299.

**Comment by adamkpickering** [comment]
As of e049562b, tests/extensions/containers.bats fails every time. Logs are here: [logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11630329/logs.zip). I get the following output in the console:
```
rancher-desktop/bats> ./bats-core/bin/bats ./tests/extensions/containers.bats
containers.bats
   ===== extensions/containers =====
 ✓ factory reset
 ✓ start container engine
 ✗ no extensions installed
   (from function `assert_success' in file bats-assert/src/assert_success.bash, line 42,
    in test file tests/extensions/containers.bats, line 31)
     `assert_success' failed

   -- command failed --
   status : 1
   output (2 lines):
     Unknown command: GET /v1/extensions
     {"message":"404 Not Found"}
   --

 ✓ build extension testing images
 ✗ image - install
   (from function `rdctl' in file tests/helpers/commands.bash, line 79,
    in test file tests/extensions/containers.bats, line 46)
     `rdctl api --method=POST "/v1/extensions/install?id=$(id vm-image)"' failed
   Unknown command: POST /v1/extensions/install
   {"message":"404 Not Found"}
 ✗ image - check for running container
   (from function `assert_line' in file bats-assert/src/assert_line.bash, line 219,
    in test file tests/extensions/containers.bats, line 57)
     `assert_line --regexp "$(id vm-image).*[[:space:]]Up[[:space:]]"' failed

   -- no output line matches regular expression --
   regexp : rd/extension/vm-image.*[[:space:]]Up[[:space:]]
   output : CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES
   --

 ✗ image - uninstall
   (from function `rdctl' in file tests/helpers/commands.bash, line 79,
    in test file tests/extensions/containers.bats, line 61)
     `rdctl api --method=POST "/v1/extensions/uninstall?id=$(id vm-image)"' failed
   Unknown command: POST /v1/extensions/uninstall
   {"message":"404 Not Found"}
 ✗ compose - install
   (from function `rdctl' in file tests/helpers/commands.bash, line 79,
    in test file tests/extensions/containers.bats, line 69)
     `rdctl api --method=POST "/v1/extensions/install?id=$(id vm-compose)"' failed
   Unknown command: POST /v1/extensions/install
   {"message":"404 Not Found"}
 ✗ compose - check for running container
   (from function `assert_line' in file bats-assert/src/assert_line.bash, line 219,
    in test file tests/extensions/containers.bats, line 80)
     `assert_line --regexp "$(id vm-compose).*[[:space:]]Up[[:space:]]"' failed

   -- no output line matches regular expression --
   regexp : rd/extension/vm-compose.*[[:space:]]Up[[:space:]]
   output : CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES
   --

 ✗ compose - uninstall
   (from function `rdctl' in file tests/helpers/commands.bash, line 79,
    in test file tests/extensions/containers.bats, line 84)
     `rdctl api --method=POST "/v1/extensions/uninstall?id=$(id vm-compose)"' failed
   Unknown command: POST /v1/extensions/uninstall
   {"message":"404 Not Found"}

10 tests, 7 failures
```
Same failure for #4511, since it is the same test.

**Comment by jandubois** [comment]
Note that by default BATS will prefer to test the install in the `system` location (`/opt/rancher-desktop`) if it exist, and fall back to the `user` location in `$PATH_REPO_ROOT/dist/linux-unpacked` only when the `system` location doesn't exist.

You can explicitly request to use the `user` location by setting `RD_LOCATION=user bats ...`

**Comment by adamkpickering** [comment]
> You should always run info.bash as part of your tests, so you can see which installation it is talking to

Why not make this run automatically whenever bats runs? Is this not possible?

> Note that by default BATS will prefer to test the install in the system location (/opt/rancher-desktop) if it exist, and fall back to the user location in $PATH_REPO_ROOT/dist/linux-unpacked only when the system location doesn't exist.

:facepalm: :facepalm: :facepalm: :facepalm: :facepalm: 

I could have sworn that previously, a build present in dist/linux-unpacked was prioritized over any installed version on the system. Has this changed recently? Or am I going crazy?

Either way, specifying `RD_LOCATION=dist` fixes the problem. I guess we can close this?

**Comment by jandubois** [comment]
> > You should always run info.bash as part of your tests, so you can see which installation it is talking to
> 
> Why not make this run automatically whenever bats runs? Is this not possible?

I don't know of any way, except by creating a wrapper script around `bats` that will inject  this argument. Having a wrapper to run common combinations of tests is still in the plan, but not implemented yet. There are some other pieces I would like to do, like preserving the current settings and VM, so running the tests becomes non-destructive.

Oh, wait, I have recently learned about `BATS_SUITE_TEST_NUMBER`, that may be a way to do this automatically; I will check it out. The output would then be displayed as being part of the first test, but maybe that is acceptable.

> I could have sworn that previously, a build present in dist/linux-unpacked was prioritized over any installed version on the system. Has this changed recently? Or am I going crazy?

Is this a trick question? 😄 

But no, the system version was always preferred. Previous change was de61be0 and the change before was 50298e7, in which you added the dist location as a fallback when the system location did not exist.
