### ISSUE TITLE
Running `k8s/helm-install-rancher.bats` bats test file requires user to input sudo password

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4513]
### Actual Behavior

Running the `k8s/helm-install-rancher.bats` bats test file requires the user to input their sudo password to continue execution. This isn't what we want - the bats tests are supposed to be fully automated.

### Steps to Reproduce

```
cd bats
bats ./tests/k8s/helm-install-rancher.bats
```

### Result

```
rancher-desktop/bats> bats ./tests/k8s/helm-install-rancher.bats
helm-install-rancher.bats
 [sudo] password for root:                                                                                                                                                                1/5
 ✓ factory reset
 ✓ start k8s
...
```

### Expected Behavior

The test should require no user input.

### Rancher Desktop Version

7b3dc525

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by IsaSih** [comment]
This also occurs on windows. Just before a factory-reset. 
Will move this to done and track the same issue on windows in #4539
