### ISSUE TITLE
Deployment profiles should be stored under HKLM\Software\Policies\...

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4518]
We currently look in `HKLM\Software\Rancher Desktop` and `HKCU\Software\Rancher Desktop`.

The recommended locations are actually `HKLM\Software\Policies\Rancher Desktop` and `HKCU\Software\Policies\Rancher Desktop`. See also [Policies](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc939918(v=technet.10)?redirectedfrom=MSDN) and [Implementing Registry-based Policy](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/policy/implementing-registry-based-policy).

We should switch to using the new locations, and if no profile is found there, fall back to the current locations for backwards compatibility.

**Comment by ericpromislow** [comment]
Note that this is an update to https://github.com/rancher-sandbox/rancher-desktop/issues/3750

This issue here is also yet one more location for a specification on this feature - all these specs need to be in one document.

**Comment by ericpromislow** [comment]
On read:

If the new location doesn't exist, fall back to the version 1.8 location

So priority order is:

HKLM/.../Profiles

HKLM/old location

HKCU/.../Profiles

HKCU/old location

Note that this means it's possible to have a defaults profile in an old location and locked-fields in the new location,
and read them both in from the separate areas.

**Comment by ericpromislow** [comment]
I think what I said in https://github.com/rancher-sandbox/rancher-desktop/issues/4518#issuecomment-1535247123 is too confusing. We should go with the first partially populated area, and stick with that.

**Comment by jandubois** [comment]
> Note that this means it's possible to have a defaults profile in an old location and locked-fields in the new location,
> and read them both in from the separate areas.

This sounds wrong. Default and Locked profile always need to be read from the same location.

> I think what I said in https://github.com/rancher-sandbox/rancher-desktop/issues/4518#issuecomment-1535247123 is too confusing. We should go with the first partially populated area, and stick with that.

I assume you mean the same thing I just wrote here, right?

We had the same behaviour before: if either default or locked system profile existed, we would not check any user profile.

Now we just have 4 areas instead of 2 (on Windows only):

* new system location
* old system location
* new user location
* old user location

The first location that has either a "default" or "locked" profile is the only location that is being read.
