### ISSUE TITLE
The dot-rcfiles aren't updated on `rdctl start ----application.path-management-strategy=rcfiles`

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4519]
### Actual Behavior

After a factory-reset and then

`rdctl start ... --application.path-management-strategy rcfiles` 

the path-management setting is updated in the settings.json file, but the path-setting lines aren't added to the dotfiles.

### Steps to Reproduce

While running, set path-management to `manual`.

Shutdown

Run something like 
```
./resources/darwin/bin/rdctl start --application.path-management-strategy=rcfiles  --path /Applications/Rancher\ Desktop.app/
```

`jq .application.pathManagementStrategy ~/Library/Preferences/rancher-desktop/settings.json` => `rcfiles`

but the bottom of dotfiles like `~/.bashrc` doesn't contain the managed lines.

**Comment by jandubois** [comment]
I believe this is fixed by #4928.
