### ISSUE TITLE
Breakage when trying to move to a later version

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#452]
This is happening against commit cd56e8b

When I change versions, the lima.log fills up with the line
`Could not read k3s.yaml; retrying...`

**Comment by mook-as** [comment]
I believe this is because of #437 — we generate a new port for the Lima agent, but as the VM wasn't restarted the existing agent (on the old port) is active instead.  Should be fixed via #464.
