### ISSUE TITLE
Ubuntu: Lima exited with code 1 - package omvf missing

### ISSUE THREAD

**Issue by strowi** [rancher-sandbox/rancher-desktop#4524]
### Actual Behavior

Had a working 1.7.0  on ubuntu 22.04, just upgraded to 1.8.1 and get an error "lima exited with code 1".

```bash
   'time="2023-04-21T09:15:12+02:00" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \\"/home/rvg/.local/share/rancher-desktop/lima/0/ha.stderr.log\\")"\n',
  code: 1,
  command: [
    '/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl',
    'start',
    '--tty=false',
    '0'
  ]
}
```

```
~> cat .local/share/rancher-desktop/lima/0/ha.stderr.log
{"level":"debug","msg":"Creating iso file /home/rvg/.local/share/rancher-desktop/lima/0/cidata.iso","time":"2023-04-21T09:15:12+02:00"}
{"level":"debug","msg":"Using /tmp/diskfs_iso1392721507 as workspace","time":"2023-04-21T09:15:12+02:00"}
{"level":"debug","msg":"OpenSSH version 8.9.1 detected","time":"2023-04-21T09:15:12+02:00"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2023-04-21T09:15:12+02:00"}
{"level":"debug","msg":"Start udp server listening on: 127.0.0.1:52262","time":"2023-04-21T09:15:12+02:00"}
{"level":"debug","msg":"Start tcp server listening on: 127.0.0.1:34013","time":"2023-04-21T09:15:12+02:00"}
{"level":"debug","msg":"firmware candidates = [/home/rvg/.local/share/qemu/edk2-x86_64-code.fd /usr/share/qemu/edk2-x86_64-code.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/qemu/ovmf-x86_64-code.bin /usr/share/edk2-ovmf/x64/OVMF_CODE.fd]","time":"2023-04-21T09:15:12+02:00"}
{"level":"fatal","msg":"could not find firmware for \"/usr/bin/qemu-system-x86_64\" (hint: try setting `firmware.legacyBIOS` to `true`)","time":"2023-04-21T09:15:12+02:00"}
```

### Steps to Reproduce

- install v1.8.1 on ubuntu 22.04
- start rancher-desktop
-  see error

### Result

rancher-desktop won't start

### Expected Behavior

Everything working

### Additional Information

After searching for the firmware mentioned in the logs, installing package `ovmf` seems to have done the trick.
That package probably should be installed automatically..

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.24.13

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

22.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by strowi** [comment]
small correction: with the installed omvf, i am getting some errors, e.g. i am unable to run `adminer:4.8.1` on rancher-desktop, which works on normal x86_64-cluster.  It only throws an coredump without any other error.

**Comment by ericpromislow** [comment]
I had no problem upgrading from 1.7.0 to 1.8.1 on Ubuntu 22.04, but I see the host already has a `/usr/share/OVMF` directory. The directory is about 40 minutes old, but all its contents have a datestamp of 2022-09-12 . I don't know how that directory was installed.

Could you give me specific directions for running `adminer` so I can try to repro that?

**Comment by strowi** [comment]
I gave it another shot:

* uninstalled rancher-desktop and ovmf
* installed rancher-desktop=1.7.0*  
Result: no /usr/share/OVMF/* but rancher-desktop works

* upgrade rancher-desktop to 1.8.1
Result: still no /usr/share/OVMF/* and rancher-desktop fails with the mentioned lima-error.

Not sure about ovmf-package, that was my workaround after searching, guess the file must've come from somewhere else or not being used at all with 1.7.0.

As for adminer, this might've been an unrelated side-problem - `kubectl run -ti --image adminer:4.8.1 adminer` seems to run now.

Not sure which logs might be helpful here.. but happy to provide more.

**Comment by julian-alarcon** [comment]
Got a similar error when I upgraded from Ubuntu 23.10 to Ubuntu 24.04 Noble Numbat.

The error was that it was not able to find the firmware.

The package `ovmf` in Ubuntu is the one that provides this files, but it seems that it was looking for `/usr/share/OVMF/OVMF_CODE.fd` but in the recent version of this package I could not find that file but this `OVMF_CODE_4M.fd`.

I ended up creating a symbolic link to that file and now it's working!

```sh
sudo ln -s /usr/share/OVMF/OVMF_CODE_4M.fd /usr/share/OVMF/OVMF_CODE.fd
```

**Comment by julian-alarcon** [comment]
It seems that this has been fixed in Lime in this recent change:
https://github.com/lima-vm/lima/commit/3c4a7f34d1f1506cc56cd7ee1b52b3a6893ae830
https://github.com/lima-vm/lima/pull/2124

Available since version 0.20.0 of Lima

**Comment by DotNetRockStar** [comment]
> Got a similar error when I upgraded from Ubuntu 23.10 to Ubuntu 24.04 Noble Numbat.
> 
> The error was that it was not able to find the firmware.
> 
> The package `ovmf` in Ubuntu is the one that provides this files, but it seems that it was looking for `/usr/share/OVMF/OVMF_CODE.fd` but in the recent version of this package I could not find that file but this `OVMF_CODE_4M.fd`.
> 
> I ended up creating a symbolic link to that file and now it's working!
> 
> ```shell
> sudo ln -s /usr/share/OVMF/OVMF_CODE_4M.fd /usr/share/OVMF/OVMF_CODE.fd
> ```

Wow, this worked for me too.  Thanks for posting this.

**Comment by jandubois** [comment]
#6799 updates Lima to 0.21.0.
