### ISSUE TITLE
Create docker context earlier during VM startup

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4548]
Especially when Kubernetes is enabled too, it appears that the docker context is only created when k3s is already up and running (and responding on the apiserver port).

The context should be created as soon as possible, i.e. when `dockerd` itself is starting.

**Comment by jandubois** [comment]
I guess the reason we are waiting for k3s to be running is to include the Kubernetes endpoint in the docker context.

Right now the Kubernetes endpoint is always `https://127.0.0.1:6443`, so we could either hardcode this, or create the context early, and then update it with the Kubernetes endpoint once Kubernetes is running.

**Comment by mook-as** [comment]
It looks like the docker context stuff may have been removed from the docker CLI already; we should confirm that, and drop the kube context stuff (meaning we can then move setting the docker context earlier).
