### ISSUE TITLE
Add REG output option to `rdctl settings`

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4562]
We need to be able to create deployment profiles from the current settings, and creating `*.reg` files is one way to do this.

There are 4 different files we should be able to create:

* either HKLM or HKCU
* either `defaults` or `locked` profiles

Not sure yet what the best way to specify the options are; starting point:

```
--output=reg,hklm,defaults
--output=reg,hklm,locked
--output=reg,hkcu,defaults
--output=reg,hkcu,locked
```

Defaults should be `hklm` and `defaults`, so

* `--output=reg` would mean `--output=reg,hklm,defaults`
* `--output=reg,locked` would mean `--output=reg,hklm,locked`
* `--output=reg,hkcu` means `--output=reg,hkcu,defaults`

Suggestion for a better option format welcome!

**Comment by ericpromislow** [comment]
The above options look fine

Request to support all the options from `set` to modify current settings.
Also possibly add support for `--body { ... JSON }` or `--input-file PATH-TO-JSON` for more settings.

**Comment by ericpromislow** [comment]
Also a `--output PATH` option, otherwise output goes to `stdout`. Meaning all other output has to go to `stderr`

**Comment by ericpromislow** [comment]
Note that to be useful the reg file output should be encoded as UCS-2 with a BOM of `\uFEFF`

I'm going to add an encoding flag that defaults to `UCS-2` (`UCS2` accepted as an alias), but
an option of `UTF-8` or `UTF8` might help testing.

**Comment by mook-as** [comment]
I believe `reg.exe` can import registry files encoded as ASCII fine (without BOM). For something like non-ASCII, it's probably best to do `"foo"=hex(1):3d,d8,25,dd` (where `1` is `REG_SZ`, and the encoded bytes is little-endian UTF-16 for [fire](https://www.fileformat.info/info/unicode/char/1f525/index.htm)).

**Comment by jandubois** [comment]
> import registry files encoded as ASCII fine (without BOM)

I think technically it assumes ANSI (Windows-1252) character set when there is no BOM, but probably best to only rely on 7-bit ASCII. Using UTF8 with a BOM does **not** work.

We already need to do the `=hex(x)...` encoding for REG_SZ_MULTI strings to get the embedded NUL characters.

**Comment by ericpromislow** [comment]
My mistake... in the tests in PR 4251 the reg files are encoded as 'latin1', and it seems like no BOM is necessary (although I had problems earlier getting `reg` to import the file when there was no BOM, but that probably wasn't the problem.

Thanks for pointing out what the `hex(N)` notation means.

**Comment by mook-as** [comment]
Review comment from #5006 that Eric thinks should be discussed here (and that makes sense):

Currently, the command is specified to take `--output=reg,hklm,defaults` etc.  This ends up complicating the help text a bunch, because it's difficult to explain the multiple sub-flags inside a single flag comment (which is a plain, single-line, string).

I believe this would be a lot easier to understand for the user, and a lot easier to implement, if we made it into multiple flags: `--output=reg --reg-hive=hklm --section=defaults`.  That way we get a help comment per flag, and when we parse it we don't need the custom code (unless we only allow valid values in enums, in which case there would be some code for that).

/cc @jandubois

**Comment by jandubois** [comment]
> I believe this would be a lot easier to understand for the user, and a lot easier to implement, if we made it into multiple flags: `--output=reg --reg-hive=hklm --section=defaults`. That way we get a help comment per flag, and when we parse it we don't need the custom code

I agree, let's do that.
