### ISSUE TITLE
Command-line arguments are ignored when there's an existing settings.json (macOS for sure)

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4569]
### Actual Behavior

Run `npm run dev  -- --container-engine.name=containerd --kubernetes-enabled=false --no-modal-dialogs` 

with current settings `.kubernetes.enabled=false`, `containerEngine.name=moby`.

Reported command-line args
```
[--container-engine.name=containerd, --kubernetes-enabled=false, --no-modal-dialogs]
```

The settings aren't updated

**Comment by mook-as** [comment]
Note that the command line settings there _doesn't_ do the name transformation, so it's `--containerEngine.name=containerd --kubernetes.enabled=false` instead.  That seems to work…

**Comment by ericpromislow** [comment]
Not an issue. The problem was that the command-line arguments need to be in mixedCase, not snake-case
