### ISSUE TITLE
RD gets stuck unable to read `k3s.yaml`

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#457]
Trying to switch from version 1.21.3 to 1.21.1, all that happens is this line repeatedly written to lima.log:

```
Could not read k3s.yaml; retrying...
```

I need to do `menu bar|Quit Rancher Desktop` twice to get it to quit.

On restart, lima.log now says: 
```
time="2021-08-05T11:31:14-07:00" level=info msg="Using the existing instance \"rancher-desktop\""
time="2021-08-05T11:31:14-07:00" level=info msg="The instance \"rancher-desktop\" is already running. Run `limactl shell rancher-desktop` to open the shell."
ssh: connect to host 127.0.0.1 port 55447: Connection refused
lost connection
exit status 1
Error starting lima: Error: /Users/ericp/workspace/rancher/desktop/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Users/ericp/workspace/rancher/desktop/dist/app/background.js:30914:27)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

**Comment by mattfarina** [comment]
> I need to do menu bar|Quit Rancher Desktop twice to get it to quit.

When you do this you're exiting RD while leaving qemu running in the background. That's why you get the lima message about it already running. Killing the qemu process before starting again will clear this up. I filed #456 about qemu still running.
