### ISSUE TITLE
Epic: Update Electron & Node

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4580]
Our version of Electron (20.3.8) is out of support [^1] and Node v16 reaches EOL on [^2]. At the time of writing, Electron v24 is stable and supports Node v18.14. Updating both Node and Electron will require additional maintenance work with removing Nuxt as a dependency from Rancher Desktop; this task has been performed in Rancher Dashboard, so we should have a reference for this work.

Updating Electron and Node is necessary to ensure security and stability for Rancher Desktop, as well as to take advantage of new features and improvements in the latest versions. One enhancement that we will benefit from is in #4394.

## ✔️ Tasks

- [x] #3723
- [x] #5000
  - [x] ~~#5310~~
  - [x] #5568
  - [x] #5298
- [x] #5619
  - see #3683 
- [x] #4394 (would be unblocked post Electron update)
- [x] #5623
  - [x] #5305
  - [x] #5336
- [x] #5630
- [x] #5634
- [x] #5637
- [x] #5659

## 🐛 Known Issues

- [x] https://github.com/node-ffi-napi/node-ffi-napi/issues/238

[^1]: https://www.electronjs.org/docs/latest/tutorial/electron-timelines#:~:text=Beginning%20in%20September%202021%20%28Electron%2015%29%2C%20the%20Electron,will%20continue%20until%20the%20release%20of%20Electron%2019.
[^2]: https://github.com/nodejs/release#release-schedule

**Comment by adamkpickering** [comment]
When this epic is closed, please take #5305 out of draft and review it. It is waiting on node 18+.
