### ISSUE TITLE
Provisioning scripts on windows are not being executed on start

### ISSUE THREAD

**Issue by cherrera2001** [rancher-sandbox/rancher-desktop#4595]
### Actual Behavior

I have placed a provisioning script in `%AppData%\rancher-desktop\provisioning` called `noteportchange.start`. This file contains a simple script that attempts to change the `service-node-port-range` of my local k3s environment. The content of the file is as follows:
```
#!/bin/sh

echo 'K3S_EXEC="--kube-apiserver-arg service-node-port-range=25000-35000"' > /etc/environment
```
I can see in `wsl-exec.log` that rancher desktop is attempting to find the file: 
```
2023-05-03T14:51:24.503Z: Running: wsl.exe --distribution rancher-desktop --exec ln -s -f -T /mnt/c/Users/chris/AppData/Roaming/rancher-desktop/provisioning /etc/local.d
2023-05-03T14:51:24.611Z: Running: wsl.exe --distribution rancher-desktop --exec /usr/bin/find /etc/local.d ( -name *.start -o -name *.stop ) -print -exec chmod a+x {} ;
```
However, no `environment` file is created within `/etc`. 

While debugging, I tried to execute 
```
wsl.exe --distribution rancher-desktop --exec /usr/bin/find /etc/local.d -name *.start -print
``` 
from my PowerShell window, and it printed nothing. However, when I executed 
```
wsl.exe --distribution rancher-desktop --exec /usr/bin/find /etc/local.d/ -name *.start -print
``` 
(Notice the trailing `/` after `/etc/local.d/`) it printed the expected `/etc/local.d/nodeportchange.start`

### Steps to Reproduce

1. Create a provisioning script that attempts to modify a k3s setting with no spaces in the file name and ending with the `.start` extension
2. Place in the  `%AppData%\rancher-desktop\provisioning` folder
3. Ensure that the files are looked for in `wsl-exec.log`
4. Notice that the setting is not set in k3s

### Result

No provisioning script seems to be found or executed.

### Expected Behavior

I expect the provisioning script to be found and executed.

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.26.4 (stable)

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22621.1555

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

No VPN
Windows Defender
No AD

**Comment by gaktive** [comment]
`-L` may help here too.

**Comment by IsaSih** [comment]
Provisioning script is being executed as it's shown in `wsl-exec.log`. If we run `wsl.exe --distribution rancher-desktop --exec /usr/bin/find /etc/local.d/ -name *.start -print`, it returns 
`/etc/local.d/noteportchange.start`. However, `etc/environment` is NOT being created.

**Comment by GetCurious** [comment]
it was indeed wrong line endings.
worked after changing to 'LF'

<img width="1012" height="371" alt="Image" src="https://github.com/user-attachments/assets/fb3a17c8-d86b-49e9-ad6b-d2dcdb0a8d61" />
