### ISSUE TITLE
Define UI behavior pertaining to snapshots while VM is in a down state

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4598]
Snapshots require a running VM in order to operate. It needs to be clearly defined how the snapshots UI will be disabled to prevent users from running into issues when trying to create or restore snapshots while the VM is down. 

## Proposals

- Operate similarly to Images, where the entire UI is replaced with a message
- Lock each action on the page while the VM is not in a running state

## Notes

- When the snapshot is running, the VM might not be available for a long time. Is there a pattern that we can implement to show people that a snapshot is running and prevent them from trying to run Rancher Desktop while a snapshot is being taken?
- How do we show progress?
- Can the process be cancelled? What does this look like?

**Comment by jandubois** [comment]
> Snapshots require a running VM in order to operate. It needs to be clearly defined how the snapshots UI will be disabled to prevent users from running into issues when trying to create or restore snapshots while the VM is down.

This sounds backwards. The VM must be stopped while taking a snapshot. `rdctl snapshot save` will have to make sure the VM is stopped before copying the data volume, to make sure all buffers are flushed and the filesystem is in a consistent state.

**Comment by rak-phillip** [comment]
My notes mention that we require a running VM before we can initiate and restore snapshots from the UI. We will need to update the issue contents to reflect reality if this isn't the case.
