### ISSUE TITLE
BATS traefik.bats test fails to connect to localhost

### ISSUE THREAD

**Issue by dpmerrill** [rancher-sandbox/rancher-desktop#4614]
### Actual Behavior

The test fails with the following error:

`curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused`

### Steps to Reproduce

Run the traefik.bats BATS test:

`./bats-core/bin/bats tests/k8s/traefik.bats`

### Result

"enable traefik" fails with:

`curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused`

while trying:

try --max 30 --delay 10 curl --head "http://$(get_host):80"

### Expected Behavior

Test should run withou failures

### Rancher Desktop Version

1.9

### Rancher Desktop K8s Version

1.22.17

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

22.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I think you forgot to set `net.ipv4.ip_unprivileged_port_start` before running the test.

I've created #4617 to skip the test if Rancher Desktop won't be able to bind to port 80, but please also run the test after making the port available!

**Comment by dpmerrill** [comment]
Thanks Jan. You are correct.  I forgot (or I should say I didn't know) to set the unprivileged port.
For my Trello test scripts, I have the script set the port as part of the test so I never think about it.

The P/R was tested with/without the port start set, and it now works as expected.  approved.
