### ISSUE TITLE
BATS creds.bats test fails with credentials errors

### ISSUE THREAD

**Issue by dpmerrill** [rancher-sandbox/rancher-desktop#4615]
### Actual Behavior

The creds.bats `verify that pushing succeeds after logging in` and `verify credentials in host cred store` tests fail.

### Steps to Reproduce

./bats-core/bin/bats tests/registry/creds.bats

### Result

`verify that pushing succeeds after logging in` fails with:

"error saving credentials: error storing credentials ... out: 'pass not initialized: exec "pass": not found in $PATH"

`verify credentials in host cred store` fails with:

"assert_output --partial "Secret:password" failed"
"output does not contain substring "Secret:password"

### Expected Behavior

Tests should run without failures

### Rancher Desktop Version

1.9

### Rancher Desktop K8s Version

1.22.17

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

22.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
@dpmerrill could you please verify that this is addressed by having the credential helper setup properly?

**Comment by dpmerrill** [comment]
Tests run successfully with credential helper set up.
