### ISSUE TITLE
Enable Browser Dev tools Debug console for the `main` builds

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4626]
### Problem Description

At present, getting into the Electron debug mode (browser dev tools) is possible only in the dev mode (`npm run dev`) and may be PR builds?

As `npm run dev` setup  sometimes doesn't work on some machines, It will be very helpful if we can enable the debug mode behind an environment variable (ex: RD_DEBUG_MODE) for the `main` builds too. 

### Proposed Solution

Enable the debug mode behind an environment variable (ex: RD_DEBUG_MODE) for the `main` builds too.

**Comment by jandubois** [comment]
You can do this by starting Rancher Desktop from the commandline with the `--remote-debugging-port="8315"` option, and then open a browser to `localhost:8315`.

Note that this only gives you access to the dev tools for the main app, and not for extensions.

**Comment by gunamata** [comment]
That's good to know. Unfortunately, at this time I am interested in the dev tools for extensions as `npm run dev` doesn't work as expected on any  of the Windows machines I have access to. 😞

**Comment by jandubois** [comment]
@rak-phillip Is there any way to make the remote debugging work for the extensions as well?

**Comment by mook-as** [comment]
This is just a check in our code:
https://github.com/rancher-sandbox/rancher-desktop/blob/75e4c7ad188d5984ac89236b299b9307aa019a0e/pkg/rancher-desktop/window/index.ts#L375-L376

This is the same for the main devtools:
https://github.com/rancher-sandbox/rancher-desktop/blob/75e4c7ad188d5984ac89236b299b9307aa019a0e/pkg/rancher-desktop/main/mainmenu.ts#L176-L180

**Comment by rak-phillip** [comment]
You should see a list of all available targets when you navigate to an installed extension in Rancher Desktop before opening your browser to `localhost:8315`. For example, I opened Tachometer and this is the list of targets I have available

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/964ade01-0f95-40e2-9c5e-5bf2e366b201)

Selecting `x-rd-extension://6a756c69616e6239302f746163686f6d65746572/ui/dashboard-tab/ui/index.html` will give me the inspector for the extension's browserview

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/5e169842-3e6b-4330-83f3-5a7fd8699e09)

**Comment by jandubois** [comment]
@rak-phillip Please add this information to the project README.md

**Comment by IsaSih** [comment]
Created a PR that fixes the path to rancher-desktop on MacOS. https://github.com/rancher-sandbox/rancher-desktop/pull/4703
