### ISSUE TITLE
containerd/moby fails to access socket when kubernetes is disabled

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4642]
### Actual Behavior

By starting up Rancher Desktop with kubernetes disabled and containerd as the engine, when user tries to start a container, it fails to connect to the containerd socket because it tries to find it inside a k3s directory.

### Steps to Reproduce

1. Start Rancher Desktop
2. Disable Kubernetes
3. Select `containerd` as the engine
4. Quit Rancher Desktop
5. Restart rancher desktop

### Result

```
2023-05-08T20:56:50.139Z: UnhandledRejectionWarning: c [Error]: C:\Program Files\Rancher Desktop\resources\resources\win32\bin\nerdctl.exe exited with code 1
    at ChildProcess.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:8347)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    'C:\\Program Files\\Rancher Desktop\\resources\\resources\\win32\\bin\\nerdctl.exe',
    'namespace',
    'list',
    '--quiet'
  ],
  stdout: '',
  stderr: 'time="2023-05-08T20:56:50Z" level=fatal msg="cannot access containerd socket \\"/run/k3s/containerd/containerd.sock\\": no such file or directory"\n',
  code: 1,
  [Symbol(child-process.command)]: 'C:\\Program Files\\Rancher Desktop\\resources\\resources\\win32\\bin\\nerdctl.exe namespace list --quiet'
}
2023-05-08T20:56:50.141Z: Kubernetes was unable to start: c [Error]: C:\Program Files\Rancher Desktop\resources\resources\win32\bin\nerdctl.exe exited with code 1
    at ChildProcess.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:8347)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    'C:\\Program Files\\Rancher Desktop\\resources\\resources\\win32\\bin\\nerdctl.exe',
    '--namespace',
    'rancher-desktop-extensions',
    'image',
    'load',
    '--input',
    'C:\\Program Files\\Rancher Desktop\\resources\\resources\\rdx-proxy.tgz'
  ],
  code: 1,
  [Symbol(child-process.command)]: 'C:\\Program Files\\Rancher Desktop\\resources\\resources\\win32\\bin\\nerdctl.exe --namespace rancher-desktop-extensions image load --input C:\\Program Files\\Rancher Desktop\\resources\\resources\\rdx-proxy.tgz'
}
```

### Expected Behavior

Containerd should be able to connect to socket regardless of Kubernetes being enabled or not.

### Rancher Desktop Version

1.7.0-1191-g09b1f0f7

### Rancher Desktop K8s Version

1.27.1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Is this a regression since 1.8.1 or was this broken in a released build already?

**Comment by IsaSih** [comment]
In 1.8.1, it fails for a different reason: buildkit status is unsupervised

**Comment by mook-as** [comment]
#4583 may have made a difference here (at least on Windows).

**Comment by ericpromislow** [comment]
I can no longer reproduce this.
