### ISSUE TITLE
RDX: Issue parsing unexpected/incomplete output of nerdctl command

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4661]
With https://github.com/rancher-sandbox/rancher-desktop/pull/4654, I am now able to install and get the Resource Usage extension working with `dockerd`. However, the extension doesn't show containers list with `containerd`.

I see below error message in the extension debugging console.

```
bugsnag.js:2648 Error: Expected ',' or '}' after property value in JSON at position 112
    at stats (useStats.ts:49:45)
    at async Promise.all (index 1)
```

The problem seems to be because of the unexpected/incomplete output that containerd/nerdctl produces for the command `nerdctl stats --all --no-stream --no-trunc --format "{{json .}}"`

Here's the difference in the output of the command with `dockerd` vs `containerd`

**With `dockerd`:**
```
>docker stats --all --no-stream --no-trunc --format "{{json .}}"
{"BlockIO":"0B / 0B","CPUPerc":"0.00%","Container":"b6464d88f0ab","ID":"b6464d88f0ab4e6982e0e9fecb13e0221ba0b547cef10327524a7a127f5a65ba","MemPerc":"0.05%","MemUsage":"12.6MiB / 24.83GiB","Name":"zealous_black","NetIO":"1.18kB / 0B","PIDs":"17"}
```

**With `containerd`:**
```
>nerdctl stats --all --no-stream --no-trunc --format "{{json .}}"
{"Name":"nginx-a509a","ID":"a509ae4d50c90e64fad1f6e6a25fa5558ab7dceac52e7e2e6ed6e85851ae1b01","CPUPerc":"0.00%!"(MISSING),"MemUsage":"12.36MiB / 8EiB","MemPerc":"0.00%!"(MISSING),"NetIO":"1.93kB / 892B","BlockIO":"0B / 0B","PIDs":"17"}
```

**Comment by jandubois** [comment]
This seems to be a bug in `nerdctl` and needs to be reported upstream.

**Comment by mook-as** [comment]
Filed as https://github.com/containerd/nerdctl/issues/2196 and fixed (but I don't believe it's been released yet).

**Comment by jandubois** [comment]
Yes, waiting for [nerdctl 1.4.0](https://github.com/containerd/nerdctl/milestone/30) release.

**Comment by jandubois** [comment]
nerdctl will be updated to 1.4.0 in #4728 and #4729
