### ISSUE TITLE
Design for locked & disabled fields

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4664]
We need to have clear design guidance on how to handle locked fields vs. disabled fields. Styles should be applied consistently against all inputs throughout Rancher Desktop. To begin, we need to focus on the Preferences dialog:

## 🔳 Acceptance Criteria

Improvements identified for our existing implementation includes:

- [x] Clearly stated design guidance for locked & disabled inputs
   Questions surrounding the different styles for selects prompted this discussion ([see comments related to differing disabled styles](https://github.com/rancher-sandbox/rancher-desktop/issues/3959#issuecomment-1526799827))
   We need to answer the question, "Should we have differing styles between disabled & locked fields that go beyond displaying the locked icon?"
   If yes, what are the rules for this design?
- [x] Radio buttons have a design for when they are locked. 
   Checkboxes include the lock icon next to the input itself, this might not make sense for radio buttons
   Does the lock icon belong in the label for the group of radio buttons or somewhere else?
   Can we lock individual options for a radio group?
- [x] Sliders have a design for when they are locked. 
   We have an informal agreement on where the lock icon belongs. 
   Can we explicitly state this in an issue so that all members are aware?
- [x] Allowed Images (string list) has a design for when it is locked. 
   The checkbox for enabling allowed images has a lock icon. 
   Does the allowed images component itself require a lock icon as well?

### Slider

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/33b60458-f0e4-4893-b646-41d448ae445b)

### Radio Group

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/d0e45664-2afc-4293-bd44-46060a53a468)

### Allowed Images
 
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/590b43d2-e973-4757-a666-c8fab2b80889)

### Select Disabled State vs. Input

<img width="263" alt="CleanShot 2023-04-27 at 17 09 31@2x" src="https://user-images.githubusercontent.com/78947/235016118-4ca52209-6244-4b91-837f-86969e8b8f96.png">

**Comment by s0nea** [comment]
Here is a draft for the checkbox in dark mode:

Checked (active, disabled, locked):
![Screenshot_2023-05-15_18-48-08](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/5703ddf2-b62b-44fb-8ea6-5e2cb4d77755)

Unchecked (active, disabled, locked):
![Screenshot_2023-05-15_18-52-00](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/86d3939d-2294-4889-9743-adbaa8baf708)

**Comment by rak-phillip** [comment]
@s0nea thanks for the update. Is the locked checkbox physically smaller than the disabled/enabled states or is this an optical illusion? I haven't taken measurements, it just looks smaller at a glance 😅

**Comment by s0nea** [comment]
> @s0nea thanks for the update. Is the locked checkbox physically smaller than the disabled/enabled states or is this an optical illusion? I haven't taken measurements, it just looks smaller at a glance sweat_smile

Oh... yes, you're right! I updated it:

Checked (active, disabled, locked, disabled + locked):
![Screenshot_2023-05-22_15-16-49](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/acf027b7-b8fd-46b2-ab71-ec48db815994)

Unchecked (active, disabled, locked, disabled + locked):
![Screenshot_2023-05-22_15-17-51](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/f5d2289d-0231-455c-9936-dfa4c65134a2)

**Comment by jandubois** [comment]
The text colour in the locked case should be the same as in the unlocked one; only the background should change to the "disabled" background.

In the screenshots above it looks like the text colour for locked fields is something in the middle between enabled and disabled, which is confusing.

**Comment by s0nea** [comment]
Yes, I agree with you. Although it's not an issue of the color. The color (#ffffff) is the same in both cases. I assume it happens because of the shading of the box.

![Screenshot_2023-05-25_17-59-58](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/05b123c2-470e-428c-ae2e-cb09cdcb0c67)
![Screenshot_2023-05-25_18-00-32](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/d1c55da1-f32d-4d19-b056-17f24eefb074)

**Comment by rak-phillip** [comment]
This should be fixed after merging #4763

**Comment by rak-phillip** [comment]
All of the items in this issue have been addressed, closing
