### ISSUE TITLE
Experimental settings: inconsistency between `virtiofs` and `vz` field

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#4667]
There is an inconsistency between the two fields `virtiofs` and `vs` on macOS. These options can only be enabled if the system version is Ventura or later.
If the requirement is not met, the `virtiofs` option is not shown at all. However the `vz` setting is shown, disabled with a tooltip "The setting requires macOS 13.0 (Ventura) or later". The behavior should be the same in both cases. Because the user can upgrade the system, I think it would be sensible to disable both options with a tooltip (like it is already the case for `vz`).

**Comment by jandubois** [comment]
> Because the user can upgrade the system, I think it would be sensible to disable both options with a tooltip

Agreed
