### ISSUE TITLE
Cant reach pod using service IP

### ISSUE THREAD

**Issue by jnrsilva** [rancher-sandbox/rancher-desktop#4671]
### Actual Behavior

After created two pods they can't communicate through exposed service IP. Only possible to communicate through pod IP.
Same behavior for both contanier engines: containerd and dockerd.

### Steps to Reproduce

`jnsilva@jorge-silva:$ kubectl create deploy test --image=nginx
deployment.apps/test created
jnsilva@jorge-silva:$ kubectl expose deploy test --port=80
service/test exposed
jnsilva@jorge-silva:$ kubectl run tmp-shell --rm -i --tty --image nicolaka/netshoot
jnsilva@jorge-silva:$ kubectl get pod,svc,ep -n default -o wide
NAME                        READY   STATUS    RESTARTS   AGE     IP          NODE          NOMINATED NODE   READINESS GATES
pod/test-865bcfc74c-bkcvm   1/1     Running   0          8m56s   10.42.0.5   jorge-silva   <none>           <none>
pod/tmp-shell               1/1     Running   0          2m39s   10.42.0.8   jorge-silva   <none>           <none>

NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE     SELECTOR
service/kubernetes   ClusterIP   10.43.0.1     <none>        443/TCP   17d     <none>
service/test         ClusterIP   10.43.125.6   <none>        80/TCP    8m38s   app=test

NAME                   ENDPOINTS            AGE
endpoints/kubernetes   172.18.133.32:6443   17d
endpoints/test         10.42.0.5:80         8m38s
jnsilva@jorge-silva:~$ k exec -it tmp-shell -- sh
~ # ping test.default.svc.cluster.local
PING test.default.svc.cluster.local (10.43.125.6) 56(84) bytes of data.
^C
--- test.default.svc.cluster.local ping statistics ---
20 packets transmitted, 0 received, 100% packet loss, time 19735ms

~ # ping 10.42.0.5
PING 10.42.0.5 (10.42.0.5) 56(84) bytes of data.
64 bytes from 10.42.0.5: icmp_seq=1 ttl=64 time=0.359 ms
64 bytes from 10.42.0.5: icmp_seq=2 ttl=64 time=0.070 ms
64 bytes from 10.42.0.5: icmp_seq=3 ttl=64 time=0.095 ms
64 bytes from 10.42.0.5: icmp_seq=4 ttl=64 time=0.062 ms
^C
--- 10.42.0.5 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3133ms
rtt min/avg/max/mdev = 0.062/0.146/0.359/0.123 ms
~ #`

### Result

Executing ping in pod "tmp-shell" to reach "test"

- it doesn't reach "test" if using the Service ( test.default.svc.cluster.local (10.43.125.6) )

- only reaches "test" if using the pod IP ( 10.42.0.5 )

### Expected Behavior

Communication with "test" from "tmp-shell" using address "test.default.svc.cluster.local"

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

1.26.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Wndows 11 Pro 22H2 OS Build 22621.1702

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jnrsilva** [comment]
Hi

There's a fault in the test I did.

'ping test.default.svc.cluster.local (10.43.125.6)' is not working because the exposed port is 80.

Tested successfully with 'wget test.default.svc.cluster.local'.

Will close this issue.

Regards,
Jorge Silva

**Comment by shekarnode** [comment]
I'm also facing the same issue with rancher-desktop .
I have created a pod and service associated with it,  but whenever I try to call the service via a temporary pod it is unable to communicate and when tried to call pod IP it is working perfectly.
Please help here.
