### ISSUE TITLE
Correct unit for 9p option Memory Size

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#4672]
I wrongly used `KiB` as unit (in the legend and tooltip) for the 9p Memory Size option on Preferences -> Virtual Machine -> Volumes while the name of the setting is mSizeInKB.

![Screenshot_2023-05-15_13-36-35](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/af149180-92a6-4043-a3ca-16db438e06f6)

Rename it into `KB`.

**Comment by jandubois** [comment]
You actually picked the right unit; the variable/setting name is wrong. :(

> Please change the name of the variable to msizeInKiB instead.
>
> This will change the --experimental.virtual-machine.mount.9p.msize-in-kb option name, and it doesn't look like the current alias mechanism would us to keep the old name as a hidden alias. But since it is experimental we can simply release-note it.
