### ISSUE TITLE
RDX: `docker/volumes-backup-extension:1.1.2` fails to installed due to dangling symlinks

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4676]
I could install docker/volumes-backup-extension, felipecruz/dockerfile-diff-extension:0.0.5  but when I tried installing after a factory reset, I ran into the below error. 

```
>rdctl extension install docker/volumes-backup-extension:1.1.2
Internal Server Error
{"message":"500 Internal Server Error"}
>rdctl extension install felipecruz/dockerfile-diff-extension:0.0.5
Internal Server Error
{"message":"500 Internal Server Error"}
```

Here are the logs:
[logs-20230515.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11480807/logs-20230515.zip)

**Comment by gunamata** [comment]
This could be because of #4679 . I think I could install the extensions successfully with `dockerd ` but when I `factory reset` and launch with chrome debugger, the app starts with `containerd` and I seem to be running into errors installing extensions.

At present, I am mainly focusing on testing extensions with `dockerd`. Sometime soon, i will test all the extensions i tried with containerd too. I will confirm then if it's a containerd specific issue.

**Comment by mook-as** [comment]
This was a run with `containerd`, correct:
> `Running: wsl.exe --distribution rancher-desktop --exec /usr/local/bin/nerdctl --namespace rancher-desktop-extensions create --entrypoint=/ docker/volumes-backup-extension:1.1.2`

It's unclear why `docker/volumes-backup-extension:1.1.2` failed.

The error in `felipecruz/dockerfile-diff-extension:0.0.5` is clearer:
> `time="2023-05-15T18:19:21Z" level=fatal msg="invalid name \"rd-extension-felipecruz_dockerfile-diff-extension_dockerfile-diff-extension_1\": identifier \"rd-extension-felipecruz_dockerfile-diff-extension_dockerfile-diff-extension_1\" greater than maximum length (76 characters): invalid argument"`

**Comment by gunamata** [comment]
Yes, I unknowingly started RD with `containerd` due to #4679

**Comment by mook-as** [comment]
Re-running the install locally, I see the issue with the first extension:
> `time=2023-05-19 23:10:51.000000 level=fatal msg="unsupported restart policy \"unless-stopped\", supported policies are: [\"always\"]"`

That needs a separate issue (and needs to be tracked upstream).

**Comment by gunamata** [comment]
As per this [comment](https://github.com/containerd/nerdctl/issues/1605#issuecomment-1336927577), It looks like it's resolved and is (probably) released in containerd 1.7.1. We need to upgrade to containerd 1.7.1 in RD. cc: @jandubois

**Comment by jandubois** [comment]
> That needs a separate issue (and needs to be tracked upstream).

We already have #4643 for updating to containerd 1.7

**Comment by gunamata** [comment]
#4643 potentially solves the installation of `docker/volumes-backup-extension:1.1.2`
Created #4724 for `felipecruz/dockerfile-diff-extension:0.0.5` as it seems to be a different problem.

**Comment by jandubois** [comment]
> is (probably) released in containerd 1.7.1

@gunamata Why did you write `1.7.1`? It looks to me like it is included in `1.7.0`, and I don't see any further references to restart policy in `1.7.1`.

This is important because going to Alpine 3.18 will only give us `1.7.0`:

```
lima-std:~# apk add containerd
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libseccomp (2.5.4-r2)
(2/4) Installing runc (1.1.7-r1)
(3/4) Installing containerd (1.7.0-r3)
(4/4) Installing containerd-openrc (1.7.0-r3)
```

**Comment by gunamata** [comment]
@jandubois,  I was not sure which version of `1.7` it was added so I just referenced `1.7.1` with that version being the most recent. I have checked the containerd release notes now and yes the fix was added in `1.7.0`. So, RD upgrading to `1.7.0` is fine.

**Comment by gaktive** [comment]
@gunamata to retest docker/volumes-backup-extension:1.1.2 and if it works, we can close this. The other extension has its own separate ticket.

**Comment by gunamata** [comment]
I still could not install `docker/volumes-backup-extension:1.1.2` with the latest [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/5148656335). I see below error in the extension.log

```
2023-06-01T23:57:47.229Z: Failed to install extension docker/volumes-backup-extension, cleaning up: c [Error]: wsl.exe exited with code 2
    at ChildProcess.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:15385)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    'wsl.exe',
    '--distribution',
    'rancher-desktop',
    '--exec',
    '/usr/bin/tar',
    '--create',
    '--gzip',
    '--file',
    '/tmp/rd-nerdctl-cp-OPPApL/archive.tgz',
    '--directory',
    '/tmp/rd-nerdctl-cp-GaGGHp/',
    '--dereference',
    '--one-file-system',
    '--sparse',
    '--files-from',
    '/tmp/rd-nerdctl-cp-OPPApL/files.txt'
  ],
  code: 2,
  [Symbol(child-process.command)]: 'wsl.exe --distribution rancher-desktop --exec /usr/bin/tar --create --gzip --file /tmp/rd-nerdctl-cp-OPPApL/archive.tgz --directory /tmp/rd-nerdctl-cp-GaGGHp/ --dereference --one-file-system --sparse --files-from /tmp/rd-nerdctl-cp-OPPApL/files.txt'
}
```

When I run the wsl command from a terminal, it seems to be failing while not able to find a folder.

```
>wsl.exe --distribution rancher-desktop --exec /usr/bin/tar --create --gzip --file /tmp/rd-nerdctl-cp-OPPApL/archive.tgz --directory /tmp/rd-nerdctl-cp-GaGGHp/ --dereference --one-file-system --sparse --files-from /tmp/rd-nerdctl-cp-OPPApL/files.txt
/usr/bin/tar: /tmp/rd-nerdctl-cp-GaGGHp/: Cannot open: No such file or directory
/usr/bin/tar: tar (child): Error is not recoverable: exiting now
/tmp/rd-nerdctl-cp-OPPApL/archive.tgz: Cannot open: No such file or directory
tar (child):
```

**Comment by mook-as** [comment]
That's a temporary folder (where we mount the image), so of course it wouldn't be able to find it if you try manually. (There's a `ctr` command line that's relevant.)

The relevant logs:
>    lima.log           |/usr/bin/tar: ./etc/ssl/certs/4304c5e5.0: Cannot stat: No such file or directory
lima.log           |/usr/bin/tar: ./etc/ssl/certs/349f2832.0: Cannot stat: No such file or directory
lima.log           |/usr/bin/tar: ./etc/ssl/certs/03179a64.0: Cannot stat: No such file or directory
lima.log           |/usr/bin/tar: Exiting with failure status due to previous errors

It looks like we need to figure out something better — there's a bunch of dangling symlinks in `/etc/ssl/certs/` in that image (it looks like they just deleted all of `/usr/share` manually, or rather never copied it in in the first place, so `/usr/share/ca-certificates` is missing).

**Comment by mook-as** [comment]
It seems like `docker cp` actually restores symlinks when copying to the host as-is, except on Windows without administrator privileges (that is, without `SeCreateSymbolicLinkPrivilege`), where they're silently skipped.

This means it would be best if we had a custom tar extraction routine :(
