### ISSUE TITLE
Windows host can't access a running container

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4682]
### Actual Behavior

Background:

Running a post 1.8.1 CI build installed from `.exe`, not `.msi`

The installer used a raised-privileges shell and didn't ask for a password

Run `nerdctl | docker` push nginx -d -p 8085:80

From Windows: `curl.exe localhost:8085` fails.

From the rancher-desktop WSL:
```
$ ps auxww | grep agent
[TBD]
```

What we want to see:

### Steps to Reproduce

See ` bats/README.md` for instructions on how to install the code in a Windows machine.

I do this in an Ubuntu WSL with its own git view, so all the files use LF line-endings.

I then `git pull` the `curl-cont-engine-bats` branch and run
```
cd bats
git submodule update --init
git submodule sync
RD_USE_WINDOWS_EXE=true bats/bats-core/bin/bats bats/tests/containers/switch-engines.bats
```

This is a simple test that starts up RD with both containerd and moby, pulls nginx and busybox images, verifies both exists, runs the nginx container, and verifies it can curl it.

`curl localhost:8085` fails from both the Windows side and the rancher-desktop WSL (where the container is hosted).

If I `ctrctl exec` to the container, I can run `curl localhost:80` and see that nginx is running and responding

### Result

The containers can't be seen from the Windows host 

### Expected Behavior

The containers should be visible from the windows host

### Additional Information

```
$ ps auxww | grep agent
rancher-desktop-guestagent -kubernetes=false -iptables=true 
-privilegedService=true
-docker=-false -containerd=true -k8sServiceListenerAddr=0.0.0.0  -debug
```

Problems are:
```
1. -k8sServiceListenerAddr should be `127.0.0.1`
2. -privilegedService should be set to false
```

Also in settings we have `kubernetes.version == ''` (empty string), but I'm not sure that's a problem.

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.26.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 and 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

None

**Comment by ericpromislow** [comment]
Same problem when I install from an MSI from CI, as opposed to installing from a .EXE file.

**Comment by gaktive** [comment]
This may require some priority but we need to rank this amongst other similar work.
