### ISSUE TITLE
The button state doesn't consistently change between "Forward" and "Cancel" in the Port Forwarding tab

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#469]
Steps to reproduce: (This behavior is not consistent though. Sometimes the button state change happens without below issue)

On Windows machine, When I click on `Forward ` button under `Port Forwarding`, the port forwarding generally works.
At this state, If i press on `Cancel` button the button state doesn't change to `Forward` again. I have to switch to a different tab, say `Images` and come back to `Port Forwarding` tab to see the state change.

**Comment by gunamata** [comment]
I take back my earlier comment. The glitch still seems to be there.
@rak-phillip , Can you please add this to your list of things?

**Comment by rak-phillip** [comment]
@gunamata having difficulties reproducing in 0.7.1 and I'm not immediately seeing any issue with the implementation that would cause this to arise.. 

I'm wondering if theres any additional details that we can gather to help us better understand the problem. Are there any specific actions you can remember taking before seeing this behavior?

**Comment by gunamata** [comment]
Agreed, not able to repro this any more. The issue was that when we click on `Cancel` button the button text doesn't change to `Forward`. Anyways, closing the issue for now. I will open a new issue in case this problem appears again.

**Comment by rak-phillip** [comment]
Reopening because we've received reports of this same behavior after enabling for macos/linux

**Comment by rak-phillip** [comment]
Able to reproduce something similar via comment from @adamkpickering on https://github.com/rancher-sandbox/rancher-desktop/pull/1281#pullrequestreview-866783221

>     Start the code on this branch with npm run dev and wait until everything is up.
>     Navigate to "Port Forwarding" tab.
>     Show kubernetes services by enabling the checkbox at the top.
>     Click the Forward button for traefik's web port.
>     Navigate to http://localhost:<port> in a browser.
>     Click the Cancel button on the same row.
>     Note how it does not change back to a Forward button.
> 
> You can get it to go back to being a Forward button by navigating to another tab, and then coming back to the "Port Forwarding" tab.
