### ISSUE TITLE
RDX: Test extensions on macOS

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4698]
Test below extensions before we add to the catalog.

Steps:

- Run below commands to install the extensions
- Navigate to each extension page and check if the page loads
- Try out trivial features of the extensions and check if it works, pages load with out errors etc

```
rdctl extension install aquasec/trivy-docker-extension
rdctl extension install prakhar1989/dive-in
rdctl extension install joycelin79/newman-extension
rdctl extension install docker/resource-usage-extension
rdctl extension install anchore/docker-desktop-extension
rdctl extension install ignatandrei/blockly-automation:0.0.7
rdctl extension install docker/disk-usage-extension:0.2.7
```

**Comment by IsaSih** [comment]
tested the list of extensions in MacOS and found the following issues:
https://github.com/rancher-sandbox/rancher-desktop/issues/4745

**Comment by IsaSih** [comment]
Assigning it to @jandubois to add the list in the release notes.

**Comment by IsaSih** [comment]
Updates:
with CI build https://github.com/rancher-sandbox/rancher-desktop/actions/runs/5127694319, which includes bug fix  , the following changes can be observed on MacOS:

WORK with `containerd`:
-Newman - functionalities work and can be installed via `containerd`
- Resource Usage - functionalities work and can be installed via `containerd`
- Blockly Automation - functionalities work and can be installed via `containerd`


do NOT work with `containerd`:
- Dive-In - can be installed via `containerd`, UI loads but functionalities do NOT work
- Trivy - can be installed via `containerd`, UI loads but functionalities do NOT work
- Disk Usage - can be installed via `containerd`, UI PARTIALLY loads but functionalities do NOT work
- Anchore - can't even be installed via`containerd`
