### ISSUE TITLE
RDX: Test extensions on Linux

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4699]
Test below extensions before we add to the catalog.

Steps:

- Run below commands to install the extensions
- Navigate to each extension page and check if the page loads
- Try out trivial features of the extensions and check if it works, pages load with out errors etc

```
rdctl extension install aquasec/trivy-docker-extension
rdctl extension install prakhar1989/dive-in
rdctl extension install joycelin79/newman-extension
rdctl extension install docker/resource-usage-extension
rdctl extension install anchore/docker-desktop-extension
rdctl extension install ignatandrei/blockly-automation:0.0.7
rdctl extension install docker/disk-usage-extension:0.2.7
```

**Comment by IsaSih** [comment]
All extensions are working expected on Linux using `dockerd` as the container engine.

Extensions that do NOT work with `containerd`:

- Trivy: UI loads but core functionality fails
- Dive-in: UI loads but core functionality fails
- Anchore: UI does not even load and core functionality fails
- Disk Usage: UI partially loads core functionality fails

Extensions that do WORK with `containerd`:

- Newman
- Resource Usage
- Blockly Automation
