### ISSUE TITLE
Display lock for input fields

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4707]
## 🔳 Acceptance Criteria

Given an input element on the preferences page:

- [ ] It can be locked.
- [ ] It displays a lock icon when it is locked.
- [ ] It is disabled when it is locked.
- [ ] It remains interactive (i.e., editable) when it is not locked.
- [ ] It visually indicates an unlocked state (e.g., no lock icon, normal appearance).
- [ ] It retains its current input when locked and unlocked.
- [ ] It provides a clear indication to the user when attempting to interact with the input while it is locked (i.e., tooltip).

**Comment by IsaSih** [comment]
Tests pass
