### ISSUE TITLE
RDX: Installation of felipecruz/dockerfile-diff-extension:0.0.5 fails with `containerd`

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4724]

**Comment by mook-as** [comment]
> time=2023-06-02 23:16:13.000000 level=fatal msg="invalid name \"rd-extension-felipecruz_dockerfile-diff-extension_dockerfile-diff-extension_1\": identifier \"rd-extension-felipecruz_dockerfile-diff-extension_dockerfile-diff-extension_1\" greater than maximum length (76 characters): invalid argument"

This should be fixed by #4789… retesting now that it's merged.

> time=2023-06-02 23:44:56.000000 level=fatal msg="failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/var/run/docker.sock\" to rootfs at \"/var/run/docker.sock\": stat /var/run/docker.s│
ock: no such file or directory: unknown"  

Okay that straight up uses the docker socket directly, this will never work on containerd.  Closing as we can't do anything about it.

**Comment by jandubois** [comment]
When closing issues like this, please make sure that the extension is marked in the catalog as being incompatible with `containerd`, or that there is an issue to do so.

**Comment by gunamata** [comment]
We don't have this extension added to the catalog yet @jandubois

**Comment by jandubois** [comment]
Ok, but it would still be good to have a place to collect this information, so we don't have to re-discover it each time.

**Comment by gunamata** [comment]
Yes. For now, I captured this information on the extensions testing page we setup for Yash.
