### ISSUE TITLE
Rancher-Desktop Compose containers cannot establish connections between each other on network

### ISSUE THREAD

**Issue by kristoff-kiefer** [rancher-sandbox/rancher-desktop#4730]
I have two services in a compose file setup like so: (I reduced the example)

version: "3.8"

services:

  oracle-db:
    container_name: oracle-db-test
    image: gvenzl/oracle-xe
    healthcheck:
      test: [ "CMD", "bash", "-c", "sqlplus / as sysdba" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "1621:1521"
    environment:
      - "ORACLE_PASSWORD=supersafe"
    networks:
      - demo-network

  spike:
    container_name: test-container
    image: wbitt/network-multitool
    networks:
      - demo-network
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

networks:
  demo-network:
    name: demo-network

What we are trying is to have two services, a db and a db-user-service (of course not really a network multitool) running on a private network.

If I log into the multitool and try to ping my db it won't work. (No POINGs returned) in our actual setup connecting with JDBC to the DB fails as well.

I'm running on windows
Rancher-Desktop Version 1.8.1
 --experimental.virtual-machine.networking-tunnel=false

EDIT: Connecting to the db container from the host machine works fine
EDIT2: It appears that you can reach NOTHING from the container. Pinging google.com doesn't work either
           Also the configuration works just fine in docker desktop

EDIT3: Further info was requested: 
Yes I'm behind a firewall. Not in a VPN at the moment though. Although Cisco AnyConnect is installed
I've zipped and added the logs. I wasn't sure which one would help

EDIT4: It's an admin installation

ps aux | grep agent on the rancher-desktop distri gives:

 707 root      0:00 supervise-daemon rancher-desktop-guestagent --start --stdout /mnt/c/Users/kkiefer/AppData/Local/rancher-desktop/logs/rancher-desktop-guestagent.log --stderr /mnt/c/Users/kkiefer/AppData/Local/rancher-desktop/logs/rancher-desktop-guestagent.log --respawn-delay 5 --respawn-max 0 --respawn-period 1800 /usr/local/bin/rancher-desktop-guestagent -- -kubernetes=false -iptables=true -privilegedService=true -docker=true -containerd=false -k8sServiceListenerAddr=127.0.0.1 -debug
  708 root      0:00 /usr/local/bin/rancher-desktop-guestagent -kubernetes=false -iptables=true -privilegedService=true -docker=true -containerd=false -k8sServiceListenerAddr=127.0.0.1 -debug
 1187 root      0:00 grep agent

(My main Distribution under wsl is Ubuntu if this means anything)

[logs_2023-05-23.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11540312/logs_2023-05-23.zip)

FURTHER NOTES:
I also had a look at IPTables in rancher-desktop and I am missing something:

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Am I reading correctly that EVERYTHING goes to DOCKER-USER first? That doesn't matter that table just has a RETURN
but afterwards it seems to go to DOCKER-ISOLATION_STAGE-1

and THAT looks like:

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

DOCKER-ISOLATION-STAGE-2 looks like:

Chain DOCKER-ISOLATION-STAGE-2 (4 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

So doesn't that mean, everything gets dropped?

What am I missing?

**Comment by rak-phillip** [comment]
Hi @kristoff-kiefer, thanks for raising an issue and helping to make Rancher Desktop better!

Can you provide more information about your environment? For example, are you behind a corporate firewall, are you connected to a corporate VPN, or do you require a proxy? It would also be helpful if you could provide us with some logs so that the team can inspect them and get a better idea of what the issue might be.

I performed a test in Windows 11 with a similar Docker Compose setup and didn't encounter any issues. Connecting to running containers, communicating with other containers specified in the compose file, and accessing websites outside of my local network using curl works without fail. I think getting additional details about your environment and logs will assist the team in troubleshooting the problem.

**Comment by kristoff-kiefer** [comment]
Updated original post. Attached logs

**Comment by Nino-K** [comment]
@kristoff-kiefer are you able to share one more thing with us? and that is inside rancher-desktop wsl vm can you share the following output?
`wsl -d rancher-desktop`
and then
`ps aux | grep agent` 

also, is this on an admin installation of non-admin?

**Comment by kristoff-kiefer** [comment]
Updated in original post

**Comment by Nino-K** [comment]
It looks like the guest agent did not start correctly based on the outpout of the `ps` you provided above. Can you confirm if the k8s was disabled or enabled? if it was enabled which version it was set to?

**Comment by kristoff-kiefer** [comment]
It was disabled!
