### ISSUE TITLE
RDX: Add/Remove extensions to/from the catalog

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4786]
Based on the testing in #4698, #4699

**Add below extensions to the catalog:**

joycelin79/newman-extension
docker/resource-usage-extension
anchore/docker-desktop-extension
ignatandrei/blockly-automation:0.0.7
docker/disk-usage-extension:0.2.7

**Remove below extensions from the catalog:**

aquasec/trivy-docker-extension

**Comment by IsaSih** [comment]
So, as identified in issue #4698, beyond Trivy, also are not compatible with `containerd`:
 - Dive-In
- Disk Usage
- Anchore

Could you @rak-phillip  set the `containerd_compatible: false` once they are in the catalog?
