### ISSUE TITLE
Some extensions work with containerd, but need to be installed via dockerd

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4794]
### Actual Behavior

Blockly Automation, Resource Usage and Newman work with containerd, but they fail to be installed via `containerd`. They currently need to be installed using `dockerd` and then will be available when you switch back to `containerd`.

### Steps to Reproduce

1. Start Rancher Desktop with `containerd`
2. Try to Install Resource Usage, Blockly Automation and Newman (it will fail)
3. Switch to `dockerd`
4. Install Resource Usage, Blockly Automation and Newman
5. Switch to `containerd`
6. Wait for the application to restart
7. Verify that the extension's UI and functionality work

### Result

Resource Usage, Blockly Automation and Newman are functional with `containerd`. However, rdctl fails to install the extensions via `containerd`.

Fatal error:
From `extensions.log`:
```
`2023-05-30T05:16:46.222Z: Failed to read metadata for joycelin79/newman-extension: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1`
```
From `lima.log`:
```
2023-05-30T05:23:10.608Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl --debug shell --workdir=. 0 /usr/local/bin/nerdctl --namespace rancher-desktop-extensions rm --force --volumes 027897a48c6c3060afa9bf405f2b3401f08ec5535392122fd1efb1f57f339830
time="2023-05-29T22:23:10-07:00" level=debug msg="changeDirCmd=\"cd . || exit 1\""
time="2023-05-29T22:23:10-07:00" level=debug msg="Failed to detect CPU features. Assuming that AES acceleration is available on this Apple silicon."
time="2023-05-29T22:23:10-07:00" level=debug msg="OpenSSH version 8.6.1 detected"
time="2023-05-29T22:23:10-07:00" level=debug msg="AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com"
time="2023-05-29T22:23:10-07:00" level=debug msg="executing ssh (may take a long)): [/usr/bin/ssh -F /dev/null -o IdentityFile=\"/Users/iguimaraes/Library/Application Support/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=iguimaraes -o ControlMaster=auto -o ControlPath=\"/Users/iguimaraes/Library/Application Support/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=5m -q -p 54076 127.0.0.1 -- cd . || exit 1 ; exec \"$SHELL\" --login -c '/usr/local/bin/nerdctl --namespace rancher-desktop-extensions rm --force --volumes 027897a48c6c3060afa9bf405f2b3401f08ec5535392122fd1efb1f57f339830']"
027897a48c6c3060afa9bf405f2b3401f08ec5535392122fd1efb1f57f339830
```
All logs:
[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11596233/Archive.zip)
[lima-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11596237/lima-logs.zip)

### Expected Behavior

Extensions that offer support to `containerd` must successfully be installed by rdctl via `containerd`.

### Rancher Desktop Version

1.7.0-1432-g567322bd

### Rancher Desktop K8s Version

1.27.2

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
The relevant items are:

- `docker/resource-usage-extension`
- `ignatandrei/blockly-automation`
- `joycelin79/newman-extension`

**Comment by IsaSih** [comment]
Extensions can be successfully installed with `containerd`. Tests pass
