### ISSUE TITLE
Epic: filter extensions that are not compatible with containerd

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4798]
Some extensions are not compatible with `containerd` because

* they don't install with the containerd runtime
* they don't work because of differences between `nerdctl` and `docker`
* they need a docker socket

### Stories

- [x] #4800
- [x] #4801
- [x] #4788

### Related

- [x] #4794
- [x] #4786

### Later

- [ ] Display a warning when removing extensions while switching container engines

**Comment by IsaSih** [comment]
There is already an issue that is meant to update the catalog with the additional extensions. Updated it in the epic
