### ISSUE TITLE
Unable to use kubectl in WSL linux distros

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#480]
If I install Ubuntu under WSL and try to use `kubectl` there is no ability to communicate with the Kubernetes provided by RD. There is no `.kube` directory with configuration in the home directory...

![Capture](https://user-images.githubusercontent.com/62991/129043969-e5d76aeb-b592-48bd-ac0d-39b491b33fae.PNG)

**Comment by mook-as** [comment]
Could you post a screenshot of the bottom of the Kubernetes Settings screen? It should have checkboxes for the WSL distributions. (If it doesn't, a screenshot would still help show that.)

**Comment by mattfarina** [comment]
This is from the tip of main as of this morning. Screenshot below...

![Capture](https://user-images.githubusercontent.com/62991/129079337-f6a503d2-9229-4574-9786-d47a66a99874.PNG)

**Comment by ericpromislow** [comment]
> Could you post a screenshot of the bottom of the Kubernetes Settings screen? It should have checkboxes for the WSL distributions. (If it doesn't, a screenshot would still help show that.)

The checkboxes don't show up on windows because there's not really a /usr/local/bin on that platform.
