### ISSUE TITLE
Add `containerdCompatible` metadata to extension catalog data

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4800]
For each extension we need to know if it is going to be compatible with `containerd` or not.

I suggest to add a `containerd_compatible` boolean field to the `demoMarketplace.summaries` in `src/pkg/rancher-desktop/utils/_demo_marketplace_items.js`.

**Comment by rak-phillip** [comment]
We will start with only setting Trivy to `containerd_compatible: false`. We can follow-up with more extensions as we identify them
