### ISSUE TITLE
Port forwarding not working on Windows

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#482]
Under Windows, I installed WordPress from the Bitnami charts and tried to expose the http service on a local port. It did not work...

![Capture](https://user-images.githubusercontent.com/62991/129051164-daf8ca47-e29a-4250-a114-020442cb4636.PNG)

When trying to connect to localhost on port 1048 you are immediately disconnected. The connection is closed.

**Comment by gunamata** [comment]
I am able to get the port forwarding working for a simple nginx app deployment using `kubectl`. 
However, I don't see my app listed in the Rancher Desktop Port forwarding tab to try the same within UI.

To reproduce, please find the nginx example at `/e2e/assets/nginx-deployment-sample/` on the branch `setup-assets-folder`.

**Comment by gunamata** [comment]
Please ignore the issue i mentioned about missing item in Port forwarding tab.. I was using a wrong .yaml by mistake.. 

For my sample, port forwarding works for me within Rancher Desktop.

**Comment by mattfarina** [comment]
After resetting my environment (i.e. `wslconfig /u rancher-desktop`) and starting up RD again this problem mostly went away. Something seems to have gone wrong with my environment.

Closing issue and will open a separate issue for other things I've noticed.
