### ISSUE TITLE
Improve runtime test reslience to profiles and settings

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4821]
### Problem Description

On LInux two e2e tests failed on the `main` branch due to existing config:

`e2e/containers.e2e.spec.ts` failed at line 128 because of an extensions setting in the defaults profile. Naturally this would trigger a failure after a factory-reset.

`e2e/rdctl-extensions.e2e.spec.ts` failed at line 160 complaining that it couldn't connect to port 6444. Changing `kubernetes.port` to 6443 "fixed" this, which probably indicates another bug.

### Proposed Solution

The e2e and bats test runners should complain if there's an existing profile when they start to run (they can manage profiles of course).

**Comment by jandubois** [comment]
After #4991 BATS will attempt to delete all deployment profiles, and throw an error if it can't. Can be suppressed with `RD_DELETE_PROFILES=false`.

**Comment by ericpromislow** [comment]
This is done for bats at https://github.com/rancher-sandbox/rancher-desktop/blob/e55dc89f10a974731b35c688ef1cede8bfa87b02/bats/tests/helpers/profile.bash#L347
