### ISSUE TITLE
UI of locked field Memory Size In KiB remains interactive 

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4831]
### Actual Behavior

By creating a locked deployment profile, once Rancher Desktop starts, the values in the profiles are applied to the fields. However, one of the UI components under Preferences, which is located in `Preferences > Virtual Machine > Volumes > Mount Type > 9p  > Memory Size in KiB`, preserve this UI fields interactive while all the other locked settings remained locked in the UI. An error message is displayed next to the 'Apply' button, which blocks and prevents the user to change the values. However, this field is expect to also be locked.

### Steps to Reproduce

1. Create a system locked deployment profile, exactly as in this file:
[dep-profile.docx](https://github.com/rancher-sandbox/rancher-desktop/files/11621598/dep-profile.docx)
3. Save it in `/Library/Preferences` as `io.rancherdesktop.profile.locked.plist`
4. Start Rancher Desktop
5. Check the UI components that are present in the locked profiles
6. Try to alter the value of Memory Size in KiB under `Preferences > Virtual Machine > Volumes > Mount Type > 9p  > Memory Size in KiB`
8. Verify that an error message is displayed right next to the "Apply" button which prevents the user to apply any changes

### Result

![ui-interactive](https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/23a81ae9-526d-4136-856c-11554e703d01)

### Expected Behavior

All the respective UI components must be locked if they are listed in a locked deployment profile and should not allow edition by the user.

### Additional Information

This occurs in the latest build from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/5139386231. 

### Rancher Desktop Version

1.7.0-1527-gad348984

### Rancher Desktop K8s Version

1.22.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by s0nea** [comment]
The PR for the (Memory Size in KiB) input field is under review: https://github.com/rancher-sandbox/rancher-desktop/pull/4817

**Comment by rak-phillip** [comment]
PR #4817 merged. Closing and moving to verify
