### ISSUE TITLE
Reduce logo size

### ISSUE THREAD

**Issue by manuelecarlini** [rancher-sandbox/rancher-desktop#4849]
### Problem Description

The logo on the top right part of the UI would look better if it was smaller,
here's the proposal to reduce its size.

### Proposed Solution

<img width="631" alt="Screenshot 2023-06-02 at 15 48 25" src="https://github.com/rancher-sandbox/rancher-desktop/assets/6459624/fdf9ce82-090f-4012-8363-08f711d1fbdf">

**Comment by jandubois** [comment]
I don't know; the logo already looks pretty small to me. Maybe we could get the same effect by increasing the font size of the "Rancher Desktop" string?

**Comment by jandubois** [comment]
Alternate suggestion: get rid of the logo and the "Rancher Desktop" string.

* The logo already exists in the Dock and the App Switcher list.
* The window title is already "Rancher Desktop"

Why do we need to duplicate the visuals inside the client area?

**Comment by jandubois** [comment]
Superseded by #5592
