### ISSUE TITLE
port forwarding choosing the wrong pod

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#485]
While I was trying to use the port forwarding feature on Windows I found it was trying the wrong pod.

I installed the bitnami wordpress chart using the command...

```
helm install wp bitnami/wordpress --set service.type=ClusterIP
```

Once the pods were up, I set a port forward up for it but that did not work. The logs explained by. From the `k8s.log` file...

```
Setting up new port forwarding to default/wp-wordpress:http...
Port forwarding is ready: default/wp-wordpress:http -> localhost:1344.
Attempting to locate wp-wordpress pod...
Attempting to locate wp-wordpress pod...
Got wp-wordpress pod: default:wp-mariadb-0
Got wp-wordpress pod: default:wp-mariadb-0
Failed to create web socket for forwarding to default/wp-wordpress:http: Error: Unexpected server response: 400
Error creating proxy: Error: Unexpected server response: 400
```

Notice it's trying to use the mariadb pod instead of the pod with wordpress on it. But, that's not what I picked for the port forward...

![Capture](https://user-images.githubusercontent.com/62991/129101744-95493270-79f8-4a47-98c4-0ec53acc806d.PNG)

**Comment by mook-as** [comment]
Fetching items from Kubernetes matches on _substring_, so looking for the `wordpress` endpoint found the `wordpress-mariadb` endpoint… sometimes. Fixed in #489.
