### ISSUE TITLE
"Experimental" bubble is sagging

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4861]
The "Experimental" label/tag is using a smaller font than the rest of the text, and the bubble is centered around this string.

Since the text is on the same baseline as the rest of the text, the bubble is off-center relative to the regular text, so looks like a slight subscript:

![CleanShot 2023-06-02 at 14 34 15@2x](https://github.com/rancher-sandbox/rancher-desktop/assets/78947/d6798b22-9cd7-463f-9f80-151ee4691557)

I think the tag should use the same text size as the rest of the text on the line.

@manuelecarlini @kwwii Please let me know what you think!

PS: I also feel that the text inside the bubble has a lot of extra margin. If this is intentional, then I think it needs to have additional margin on the outside as well.

![CleanShot 2023-06-02 at 14 34 15@2x](https://github.com/rancher-sandbox/rancher-desktop/assets/78947/6303efce-5958-49fa-bed3-2e94ae14600f)

**Comment by kwwii** [comment]
Agreed, the whole thing should be moved 2-3(?) pixels higher

**Comment by jandubois** [comment]
> Agreed, the whole thing should be moved 2-3(?) pixels higher

What is the reason not to use the regular text fontsize for the tag? It should solve the alignment issue automatically.

Moving the bubble higher would also lift the text off the baseline, so it would be floating.

Mixing different height text on a single line almost always looks bad, so should be restricted to when there is no other option. In this case the tag already has a bubble to differentiate from the regular text; it doesn't need a different size of font style.

**Comment by kwwii** [comment]
We could use an icon instead, similar to the locked fields feature.

![Artboard 1@4x](https://github.com/rancher-sandbox/rancher-desktop/assets/617368/359db906-f22d-4aa0-bc0e-d6b40ef0ad58)

![miscellaneous](https://github.com/rancher-sandbox/rancher-desktop/assets/617368/d4a2fef2-c229-41de-8063-5fcd48868e92)

**Comment by manuelecarlini** [comment]
I personally would like more if the bubble of "Experimental" would be smaller, 
the reason why I would not use the regular font size is that being a label, a tag, should feel different.

I would agree with Ken anyway, on using an icon, 
also because I don't think it should be very prominent as information.

**Comment by jandubois** [comment]
> We could use an icon instead, similar to the locked fields feature.
> 
> ![Artboard 1@4x](https://user-images.githubusercontent.com/617368/243180536-359db906-f22d-4aa0-bc0e-d6b40ef0ad58.png)

We could, but I have no idea what that icon is supposed to represent. It looks like a bunny face that has been chopped off at the eye level, but that would be rather gruesome, so I guess it has to be something else.

The only image that comes to my mind that says "experimental" is some kind of Erlenmeyer flask with bubbles inside (https://www.vecteezy.com/free-vector/erlenmeyer-flask). Maybe a tilted test tube could work, but is harder to identify without context; the Erlenmeyer flask has a pretty distinctive shape.

**Comment by gaktive** [comment]
This ticket will be replaced once we get the new icon (it's a flask, spoiler alert).

**Comment by jandubois** [comment]
This ticket has been replaced by #5177
