### ISSUE TITLE
WSL UDP bug workaround unavailable in Rancher

### ISSUE THREAD

**Issue by stampycode** [rancher-sandbox/rancher-desktop#4873]
### Problem Description

As per https://github.com/microsoft/WSL/issues/8610 UDP packets of size < 12 bytes can't reach Windows from WSL2

A workaround has been suggested to use `ethtool -K eth0 tx off` to disable eth offloading within the WSL2 env, however Busybox doesn't have ethtool.

### Proposed Solution

Could we have ethtool added, or document an alternative way to perform the same action?

**Comment by Nino-K** [comment]
This issue no longer is relevant, we have added support for UDP to our networking stack and it should be available in our 1.17 release. I'm going to close this issue, feel free to re-open if it requires further discussion.
