### ISSUE TITLE
Error updating Preferences - `Errors in proposed settings: Invalid value for virtualMachine.memoryInGB: <0>`

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4883]
I see below error message when I try updating any of the preferences. The `Apply` button doesn't get enabled in the Preferences dialog. I m on Windows and using a [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/5180483410) from this morning. 

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/59538726/d9bf7c48-068e-4fc4-9fe8-384de200d55c)

Logs: 
[logs-20230605.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11658175/logs-20230605.zip)

**Comment by IsaSih** [comment]
I was also able to reproduce it, but this error is just in the UI. Trying to update the settings is still possible via `rdctl set`.
