### ISSUE TITLE
Tachometer UI never loads

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4887]
### Problem Description

Once the Tachometer extension is installed, the extension UI never loads.

    
![tachometer](https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/56e09544-e9e3-4f08-a080-5267cbd7d805)

### Proposed Solution

Rancher Desktop must load all the extensions UI

### Additional Information

All default configurations in the VM. It occurs on both windows and MacOS.

Here are the attached logs for MacOS, `containerd`:

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11681527/logs.zip)

[lima logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11681573/lima.logs.zip)

Here are the attached logs for MacOS, `dockerd`: It's important to highlight that the UI loads properly after a factory-reset and installing Tachometer directly with dockerd. In fails to load the UI with dockerd if installed via containerd, and then switching to dockerd.
[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11681685/Archive.zip)

**Comment by gaktive** [comment]
Happens on both moby and containerd. Worked for @gunamata

**Comment by gaktive** [comment]
Also on both Mac and Win.

**Comment by rak-phillip** [comment]
I am able to load Tachometer in Windows using `moby`, but it fails with `containerd`
