### ISSUE TITLE
1.9 Screenshots

### ISSUE THREAD

**Issue by sunilarjun** [rancher-sandbox/rancher-desktop#4890]
Creating issue to track the screenshots for 1.9.0. Still need the Windows and macOS screenshots for the UI/Preferences, thanks!

**Comment by torchiaf** [comment]
Linux:
[linux_1.9.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11674223/linux_1.9.zip)

**Comment by s0nea** [comment]
macOS: [darwin_1.9.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11677118/darwin_1.9.zip)

**Comment by rak-phillip** [comment]
Windows: [2023-06-07-screenshots-win32.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11680554/2023-06-07-screenshots-win32.zip)

**Comment by rak-phillip** [comment]
Windows: [2023-06-07-screenshots-win32.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11681389/2023-06-07-screenshots-win32.zip)

**Comment by rak-phillip** [comment]
@sunilarjun I finally got the Windows screenshots uploaded, can you take a look when you get a chance?

**Comment by sunilarjun** [comment]
@rak-phillip They look good! I'll go ahead and move this to closed, thanks!
