### ISSUE TITLE
First-run dialog is overriding the deployment profiles

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4918]
### Actual Behavior

The application is ignoring the default's system deployment profile and displaying a first-run dialog to fill-in all the settings, that already exist in the default deployment profile. It's important to highlight here that the values of the locked fields are being applied. The values set in the first-run dialog are overriding the values in the default deployment profile

### Steps to Reproduce

1. Run a factory reset
2. Create system and user's deployment profiles (the files can be found in the session Additional Information)
3. Start Rancher Desktop

### Result

A first-run dialog is being displayed and the values set in the first-run dialog are overriding the values in the default deployment profile

### Expected Behavior

There should be no first-run dialog displayed at all. If no settings from the first-run dialog are defined in any of the deployment profiles, then Rancher Desktop should start implementing the defaults for this settings with  no first-dialog prompt.

### Additional Information

Here are the files containing each of the deployment profiles used

1. System locked profile - [profile.txt](https://github.com/rancher-sandbox/rancher-desktop/files/11700340/profile.txt)
2. System default profile - [sys-profile-default.txt](https://github.com/rancher-sandbox/rancher-desktop/files/11700564/sys-profile-default.txt)
3. User locked profile - [user-profile-locked.txt](https://github.com/rancher-sandbox/rancher-desktop/files/11701248/user-profile-locked.txt)
4. User default profile -
[user-profile-defaults.txt](https://github.com/rancher-sandbox/rancher-desktop/files/11701428/user-profile-defaults.txt)

### Rancher Desktop Version

1.7.0-1669-g22e4b6c2

### Rancher Desktop K8s Version

1.26.5

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I installed the profiles with these commands:

```shell
sudo cp profile.txt /Library/io.rancherdesktop.profile.locked.plist
sudo cp sys-profile-default.txt /Library/io.rancherdesktop.profile.defaults.plist
cp user-profile-locked.txt ~/Library/io.rancherdesktop.profile.locked.plist
cp user-profile-defaults.txt ~/Library/io.rancherdesktop.profile.defaults.plist
```

I did a factory-reset, and on restart was presented with the first-run dialog. This should not happen when a deployment profile has been loaded.

**Comment by jandubois** [comment]
> I installed the profiles with these commands:

Ok, those were missing the `Preferences` subdirectory:

```
sudo cp profile.txt                 /Library/Preferences/io.rancherdesktop.profile.locked.plist
sudo cp sys-profile-default.txt     /Library/Preferences/io.rancherdesktop.profile.defaults.plist
     cp user-profile-locked.txt    ~/Library/Preferences/io.rancherdesktop.profile.locked.plist
     cp user-profile-defaults.txt  ~/Library/Preferences/io.rancherdesktop.profile.defaults.plist
```

**Comment by mook-as** [comment]
The profiles as given do not set the path management policy.  Currently (per #4854) we force open the first run dialog:
https://github.com/rancher-sandbox/rancher-desktop/blob/97073393715660ed9d34b9ad197779eb2bf115da/background.ts#L273-L281

We should probably change this to have a default value (that's not `notset`) for it, drop `notset` as a choice, and force-migrate people with `notset` to the (new) default value.  I do not know which we should pick as the default.
