### ISSUE TITLE
Main window is shown before the First Run dialog

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/rancher-desktop#4923]
### Actual Behavior

When Rancher Desktop is running for the first time on Linux, it shows the Main window and the progress bar before the First Run dialog.
I noticed that I have some deployment profiles defined in `.config/rancher-desktop.defaults.json`.

### Steps to Reproduce

- Remove the settings directories:
  - `.config/rancher-desktop`
  - `.config/Rancher\ Desktop/`
  - `.local/share/rancher-desktop/`
  - `.rd`

_or_ do a Factory Reset

- Run RD.

### Expected Behavior

The Main window should be open after the user saves the initial settings from First Run dialog.

### Rancher Desktop Version

RC 1.9 (https://github.com/rancher-sandbox/rancher-desktop/actions/runs/5206486035)

### Rancher Desktop K8s Version

1.26.5

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Open SUSE Leap 15

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Possible duplicate with #4159 -- @IsaSih & @jandubois to check.

**Comment by jandubois** [comment]
I cannot reproduce this on macOS and @rak-phillip could not reproduce it on Linux.

We assume that `Clean your environment and remove all RD settings` means factory-reset.

Please include more details steps to reproduce this, including any commands you run from a shell, and any deployment profiles you may have installed.

**Comment by torchiaf** [comment]
> We assume that `Clean your environment and remove all RD settings` means factory-reset.

Sorry, I will add more details to the description; It means I removed the directories in the list below before restarting the application:

- `.config/rancher-desktop`
- `.config/Rancher\ Desktop/`
- `.local/share/rancher-desktop/`
- `.rd`

**Comment by torchiaf** [comment]
Closing because not showing the First Run dialog if there are deployment profiles is an expected behavior.
