### ISSUE TITLE
Error on docker build using rancher desktop

### ISSUE THREAD

**Issue by gchiarapa** [rancher-sandbox/rancher-desktop#4924]
### Actual Behavior

when I try to execute docker build I got the error:

`ERROR: error during connect: Get "http://127.0.0.1:2375/_ping": dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.`

But rancher desktop is up and running.

Could someone help me?

Thanks a lot.

### Steps to Reproduce

Execute the command docker build or docker push

### Result

`ERROR: error during connect: Get "http://127.0.0.1:2375/_ping": dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.`

### Expected Behavior

It should generate a docker image.

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Yes, I use forticlient VPN.

**Comment by mook-as** [comment]
That sounds like you're using a custom docker endpoint (`http://127.0.0.1:2375/`), whereas we use the default `npipe:////./pipe/docker_engine`. Please unset any `DOCKER_HOST` environment variables, and make sure you're not using a non-default Docker context.

**Comment by gchiarapa** [comment]
It works! Tks a lot.
