### ISSUE TITLE
Windows 11 - Test case 78: Deployment profiles with locked fields

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4927]
This test fails on step 11:

> Try to install the extensions that are in the allowed list, with the same tag that is specified in the list. Rancher Desktop must successfully install the extension. Check via rdctl extension ls that the installed tag corresponds to the same that is in the allowed list.

I've added a collection of images into the registry with the following command

```
reg add "HKCU\Software\Policies\Rancher Desktop\Locked\application\extensions\allowed" /v list /t REG_MULTI_SZ /d "disk-usage-extension:0.2.7\0joycelin79/newman-extension\0docker/resource-usage-extension\0prakhar1989/dive-in"
```

I have verified that the images are present in the locked profile in the registry editor. All images fail to install

```
PS C:\Users\phillip> rdctl extension install disk-usage-extension:0.2.7
The image disk-usage-extension:0.2.7 has invalid extension metadata
{"message":"422 Unprocessable Entity"}
PS C:\Users\phillip> rdctl extension install joycelin79/newman-extension
The image joycelin79/newman-extension has invalid extension metadata
{"message":"422 Unprocessable Entity"}
PS C:\Users\phillip> rdctl extension install docker/resource-usage-extension
The image docker/resource-usage-extension has invalid extension metadata
{"message":"422 Unprocessable Entity"}
PS C:\Users\phillip> rdctl extension install prakhar1989/dive-in
The image prakhar1989/dive-in has invalid extension metadata
{"message":"422 Unprocessable Entity"}
```

**Comment by jandubois** [comment]
The test description is incorrect; right now all allowed extensions must also be included in the list of allowed images, if the allowed images feature is enabled (this is going to change in #4926.
