### ISSUE TITLE
The settings API should perform format migration

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4939]
Currently we throw an error unless the current/latest version is specified:

```console
$ rdctl api settings --body '{"version": 7}'
errors in attempt to update settings:
updating settings requires specifying version = 8, but received version 7
Changing field version via the API isn't supported.
{"message":"400 Bad Request"}

$ rdctl api settings --body '{"version": 8}'
no changes necessary
```

We already have the format migration logic when we load an older `settings.json` file. It should be applied to API calls as well.

**Comment by jandubois** [comment]
Migrations also need to be applied to deployment profiles. Right now the application fails to load when a deployment profile specifies an older API version.

**Comment by IsaSih** [comment]
The command fails with all tested versions: 

```
rdctl api --body '{"version": 9}'
Unknown command: PUT /v1/9%7D%27
{"message":"404 Not Found"}

C:\Users\tuctuc>rdctl api --body '{"version": 8}'
Unknown command: PUT /v1/8%7D%27
{"message":"404 Not Found"}

C:\Users\tuctuc>rdctl api --body '{"version": 10}'
Unknown command: PUT /v1/10%7D%27
{"message":"404 Not Found"}
```

From the help menu, it seems that the endpoint `PUT/settings` no longer needs to be specified in the api call. Am I missing something or is this an actual bug?

**Comment by jandubois** [comment]
> From the help menu, it seems that the endpoint `PUT/settings` no longer needs to be specified in the api call. Am I missing something or is this an actual bug?

I don't know; that sounds wrong. You should always have to specify an endpoint. I don't know why that would have changed.

It looks like the code is cooking up some weird endpoint from the the body value: it seems to be the `version` as a string followed by `}` followed by an ESC char, all URL-encoded. That also doesn't make any sense to me, so please file a bug for this!
