### ISSUE TITLE
Deployment profiles are ignoring Kubernetes version wrong data type

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4952]
### Actual Behavior

Once there's a deployment profile with a wrong value for Kubernetes version, Rancher Desktop starts normally, applies the Latest version automatically and does NOT display the Kubernetes version in the UI

### Steps to Reproduce

1. Run a factory-reset
2. Create a defaults deployment profile specifying Kubernetes version to an invalid value. In this test: 
```
<key>kubernetes</key>
    <dict>
        <key>version</key>
        <string>cre</string>
    </dict> 
```
3. Start Rancher Desktop
4. Check what Kubernetes version is displayed in the Preferences dialog

### Result

Rancher Desktop applies the latest Kubernetes version and starts normally instead of throwing an error message. Preferences dialog does not display the corresponding Kubernetes version, and shows and empty field instead
<img width="1209" alt="Screen Shot 2023-06-13 at 1 37 10 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/13bdf260-6d8f-4ce6-835c-71660f8477ea">

### Expected Behavior

Rancher Desktop must throw an error message and prevent the application to start

### Rancher Desktop Version

1.7.0-1684-geb14bb3b

### Rancher Desktop K8s Version

1.27.2

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Possibly connected (or then a duplicate): https://github.com/rancher-sandbox/rancher-desktop/issues/5047

**Comment by ericpromislow** [comment]
I don't think this needs to be a fatal error. Current behavior is to quietly ignore the proposed version and use the most recent stable version instead.

The change I'm going to make is to write a line to `kube.log`of the form

```
Requested kubernetes version X is not a valid version. Falling back to the most recent stable version of Y
```

and recommend the test looks for this line instead.

**Comment by jandubois** [comment]
> I don't think this needs to be a fatal error.

It does if the invalid version is specified in a "locked" profile, but I assume #5205 is going to take care of that.

**Comment by ericpromislow** [comment]
Correct assumption.
