### ISSUE TITLE
Exploration: when to use/not cards

### ISSUE THREAD

**Issue by scures** [rancher-sandbox/rancher-desktop#4955]
### Problem Description

Currently we're making use of `cards` to wrap out content and we might not need to.

### Proposed Solution

Based on the new work for the `Cards redesign` we want to explore where we can remove the use of cards.

**Comment by rak-phillip** [comment]
@scures Yeah, I think it makes sense to raise a PR and fix it 😁

Although, we do also use a card when we delete an image

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/b7a4c21a-4393-43f6-be83-abc5a51b3f82)

I don't know if we want to change this one as well, but it might be better reserved for a more in-depth review of how this feature should function. I think the pattern in place today is sub-optimal as-is.
