### ISSUE TITLE
'BuildKit is enabled but the buildx component is missing or broken'

### ISSUE THREAD

**Issue by anderstogern** [rancher-sandbox/rancher-desktop#4965]
### Actual Behavior

I cannot build Docker images using Docker Buildkit.

### Steps to Reproduce

Install Rancher Desktop 1.9.0 and try to build an image using Docker Buildkit.

### Result

when I try to build a Docker image, I get the error 'BuildKit is enabled but the buildx component is missing or broken'.

I use the command `DOCKER_BUILDKIT=1 docker build --force-rm .` in the Rancher Desktop console (`wsl -d rancher-desktop`).

### Expected Behavior

Docker should begin building the image.

### Additional Information

I have just upgraded from Rancher Desktop 1.8.1 to 1.9.0 on Windows 11. With version 1.8.1 it worked fine. Downgrading to version 1.8.1 also works fine.

Running `docker-buildx --help` returns the help information, so the command exists.

Running `docker --help` does not, however show buildx in the management commands section.

*Update:* I forgot to mention that I have tried with both containerd and dockerd with a factory reset in between, both with the same error.

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

Kubernetes is disabled

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Winows 11 Pro Version 10.0 Build 22621

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

HP IronWolf is installed and running

**Comment by s0nea** [comment]
Hi @anderstogern,

Thank you for reporting the issue!

Could you please select the `dockerd (moby)` container engine on the preferences dialog (https://docs.rancherdesktop.io/ui/preferences/container-engine/general) and try to run the command again?

**Comment by anderstogern** [comment]
Hi S0nea,

I forgot to mention that I have tried with both containerd and dockerd with a factory reset in between, both with the same error, though.

**Comment by anderstogern** [comment]
Hi @s0nea,

Thank you for looking into this. I can confirm that your workaround fixes the issue!

Is this to be expected behaviour for this and future releases of Rancher Desktop? I could not find any mention of it in the change logs (but maybe i missed it) ..

**Comment by s0nea** [comment]
> Is this to be expected behaviour for this and future releases of Rancher Desktop? I could not find any mention of it in the change logs (but maybe i missed it) ..

No, I don't think the behavior is expected. I opened a PR for it.

**Comment by jandubois** [comment]
Temporarily re-opening this issue because I want to cherry-pick the fix for the 1.9.1 patch release.

**Comment by jandubois** [comment]
Cherry-picked into `release-1.9.1` via #5044.
