### ISSUE TITLE
Epic: Deployment Profiles (part 3)

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4968]
# Stories

- [x] #4562
- [x] #4952
- [x] #5047
- [x] #5020 

# Later

- [ ] #4201 

# Previous Epics:

- #3649
- #4608

**Comment by gaktive** [comment]
Removed #4962 from this epic checklist since it's its own epic for @IsaSih. This epic is purely for the development side so it'll be @ericpromislow 's
