### ISSUE TITLE
Diagnostics: Add warning about wsl-vpnkit

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#4990]
### Problem Description

We have a few issues from people complaining about things not working after using wsl-vpnkit.  As (as far as I know) we have no plans to support it, we should add a diagnostic that detects when wsl-vpnkit is in use and warn the user.

### Proposed Solution

Add a new (Windows-only) diagnostic that detects when wsl-vpnkit is in use and warn the user about it.

### Additional Information

We may need to check how our gvisor-based namespaced network thing interacts (it might end up being fine if we end up totally ignoring the network set up in WSL, but that would probably not be the case).

**Comment by jandubois** [comment]
Issue #4966 has been fixed, so I don't think this diagnostic is needed anymore.
