### ISSUE TITLE
Portforwarding not working for new "Networking Tunnel" feature

### ISSUE THREAD

**Issue by mbuchner** [rancher-sandbox/rancher-desktop#4997]
### Actual Behavior

Port from Windows WSL Docker container is not accessible in Windows Browser. 

### Steps to Reproduce

I installed latest version of Rancher 1.9.

Kubernetes is disabled - only dockerd is used.

Enabled under "Preferences -> WSL -> Network" the new "Enable Networking Tunnel" mode.

Rancher Docker Restarted (also OS restart has been tested)

Open cmd shell and start basic docker container:

`docker run --name foo-nginx -d -p 8181:80 nginx`

Docker container is running:
```
docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS         PORTS
  NAMES
38c09d0e1bea   nginx     "/docker-entrypoint.…"   22 minutes ago   Up 3 seconds   0.0.0.0:8181->80/tcp, :::8181->80/tcp   foo-nginx
```

### Result

Open Browser on Windows host and navigate to "http://localhost:8181/"

No service running under 8181 ...

Also curl in cmd shell not working:
```
curl http://localhost:8181/
curl: (56) Recv failure: Connection was reset
```

### Expected Behavior

Default nginx page is displayed

### Additional Information

```
>wsl --version
WSL-Version: 1.2.5.0
Kernelversion: 5.15.90.1
WSLg-Version: 1.0.51
MSRDC-Version: 1.2.3770
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.19045.3086

>rdctl version
rdctl client version: 1.1.0, targeting server version: v1

>docker version
Client:
 Version:           24.0.2-rd
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.4
 Git commit:        e63f5fa
 Built:             Fri May 26 16:43:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Fri May 12 13:54:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Rancher Desktop Version

1.9

### Rancher Desktop K8s Version

none

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Checkpoint Endpoint Security VPN (tunnel disabled as I was on site)

**Comment by Nino-K** [comment]
Thanks for reporting this I have made a [PR](https://github.com/rancher-sandbox/rancher-desktop-agent/pull/49) that should address this issue. As a workaround please run the following commands and that should rectify your issue. 

```
rdctl shell iptables -t nat -D PREROUTING -d 192.168.127.2 -j DNAT --to-destination 127.0.0.1
rdctl shell iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
```

**Comment by mbuchner** [comment]
Thanks for the workarround! I can confirm that it fixes the issue!

**Comment by jandubois** [comment]
Temporarily re-opening this issue for cherry-picking into the 1.9.1 patch release.

**Comment by jandubois** [comment]
Cherry-picked into `release-1.9.1` via #5044.
