### ISSUE TITLE
Rancher Desktop does not start (with new networking) with space in user name

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5001]
### Actual Behavior

Rancher Desktop fails to start the backend, in a way that's not clear to the user.
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/3977982/008ac8d3-9b54-450f-a4b7-21815e4bf1c2)
> Error Starting Kubernetes
Error: Timed out after waiting for /var/run/wsl-init.pid: 30 secs
Context:
Starting WSL environment

### Steps to Reproduce

1. Install Rancher Desktop
2. Start Rancher Desktop with a user name that contains a space.  In this case, the user is named `Adäm Smîth`.
3. See error above.

### Result

The above dialog is displayed.

Relevant lines in the logs:

> background.log
> ```
> 2023-06-20T21:19:01.173Z: Kubernetes was unable to start: Error: Timed out after waiting for /var/run/wsl-init.pid: 30 secs
>     at ei.runInit (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:43:16965)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:43:31369
> ```
> wsl-init.log
> ```
> cat .\wsl-init.log -Encoding UTF8
> + NETWORK_SETUP_LOG='/mnt/c/Users/Adäm Smîth/AppData/Local/rancher-desktop/logs/network-setup.log'
> + VM_SWITCH_LOG='/mnt/c/Users/Adäm Smîth/AppData/Local/rancher-desktop/logs/vm-switch.log'
> + '[' 396 -ne 1 ]
> + exec /usr/local/bin/network-setup --logfile '/mnt/c/Users/Adäm' 'Smîth/AppData/Local/rancher-desktop/logs/network-setup.log' --vm-switch-path /usr/local/bin/vm-switch --vm-switch-logfile '/mnt/c/Users/Adäm' 'Smîth/AppData/Local/rancher-desktop/logs/vm-switch.log' --unshare-arg /usr/local/bin/wsl-init
> time="2023-06-20T21:18:31Z" level=fatal msg="setting logger's output file failed: open /mnt/c/Users/Adäm: permission denied"
> ```

### Expected Behavior

Rancher Desktop starts successfully.

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.1848)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Re-opening temporarily to cherry-pick the fix into 1.9.1

**Comment by jandubois** [comment]
Cherry-picked into `release-1.9.1` via #5023.
