### ISSUE TITLE
Documentation site for Windows deployment profiles is incorrect

### ISSUE THREAD

**Issue by pshutt97** [rancher-sandbox/rancher-desktop#5008]
### Actual Behavior

HKEY_LOCAL_MACHINE\Software\Policies\Rancher Desktop\Profile\Defaults
HKEY_LOCAL_MACHINE\Software\Policies\Rancher Desktop\Profile\Locked
HKEY_CURRENT_USER\Software\Policies\Rancher Desktop\Profile\Defaults
HKEY_CURRENT_USER\Software\Policies\Rancher Desktop\Profile\Locked

### Steps to Reproduce

Go to Rancher Desktop Docs site for deployment profiles, https://docs.rancherdesktop.io/getting-started/deployment

### Result

The documentation shows the following:

HKEY_LOCAL_MACHINE\Software\Policies\Rancher Desktop\Profile\Defaults
HKEY_LOCAL_MACHINE\Software\Policies\Rancher Desktop\Profile\Locked
HKEY_CURRENT_USER\Software\Policies\Rancher Desktop\Profile\Defaults
HKEY_CURRENT_USER\Software\Policies\Rancher Desktop\Profile\Locked

### Expected Behavior

HKEY_LOCAL_MACHINE\Software\Rancher Desktop\Profile\Defaults
HKEY_LOCAL_MACHINE\Software\Rancher Desktop\Profile\Locked
HKEY_CURRENT_USER\Software\Rancher Desktop\Profile\Defaults
HKEY_CURRENT_USER\Software\Rancher Desktop\Profile\Locked

Should be the path as the one that is documented does not change anything.

### Rancher Desktop Version

1.9

### Rancher Desktop K8s Version

1.27.1?

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

ZScaler, Cisco AnyConnect

**Comment by jandubois** [comment]
Should be fixed by https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/232 (once it is merged).
