### ISSUE TITLE
Support generating reg files from arbitrary JSON snippets

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5020]
### Problem Description

This is a follow-up to issue #4562, implemented in PR #5006

We want to create a new command for creating profiles:

```shell
rdctl create-profile --input FILENAME
rdctl create-profile --body JSON
rdctl create-profile --from-settings
```

The options `--input`, `--body`, and `--from-settings` are mutually exclusive; exactly one of them must be provided.

The command will fail when `--from-settings` is specified but the app is not running.

The output format must be specified with `--output reg` or `--output plist`. The command will fail if the `--output` option is not provided.

The output is written to STDOUT.

When the output format is `reg` then the additional options `--type` and `--hive` are supported. `--type` can be either `locked` (default) or `defaults`, and `--hive` can be either `hklm` (default) or `hkcu`.

The `--output` option will be dropped from `rdctl list-settings`. The feature hasn't been shipped, so there's no reason to support it.

---

Old description for reference:

Using `rdctl list-settings --output reg....` is a useful way to convert current settings to registry files, but we need finer tools. It would be useful to be able to run some command to generate a registry file for the values we care about. For example:
```
rdctl CONVERT --body '{"kubernetes": {"enabled": false }}' --output reg --reg-hive hkcu --section defaults > hkcu-defaults.reg

echo '{"containerEngine": {"allowedImages": {"patterns": ["abc", "ghi", "def"] } }, "WSL": { "integrations": { "first": true, "second": false } } }' |
rdctl CONVERT --input - --output reg --reg-hive hkcu --section locked > hkcu-locked.reg
```

It turns out we can easily implement this by piggy-backing on the `list-settings` subcommand. The subcommand `rdctl convert` would be more intuitive, but it might lead to people expecting to use it to convert registry files to JSON, and that's more work than we need to do right now.

Another possible command is `rdctl convert-settings --output reg ...` where `reg` is the default and only possible option (right now).

### Proposed Solution

See above

**Comment by jandubois** [comment]
I think we should create an `rdctl create-profile` command for this.

In addition to the `--input` and `--body` options we should add `--from-setting` and remove the corresponding settings from `rdctl list-settings`. That way all the profile functionality is under one subcommand, and `list-settings` is purely for human consumption.

`--from-settings` can be the default if neither `--body` nor `--input` is specified.

**Comment by ericpromislow** [comment]
Are we going to include an `--output=X` option where X is `reg`|`registry`, `plist`, or `json` (which is a do-nothing)?
If we include `plist`, I would want to implement it as shelling out to `plutil`, which means it would run only on macOS.

I assume the `--reg-hive=X` and  `--profile=Y` options will move here from `list-settings`

By human consumption, do you mean to leave the output of `rdctl list-settings` as JSON? I hope so, because it's non trivial to present hierarchical data in a tabular form.

If the server isn't running and no input is provided should `create-profile` get its input from the settings file, if it exists?

**Comment by jandubois** [comment]
> Are we going to include an `--output=X` option where X is `reg`|`registry`, `plist`, or `json` (which is a do-nothing)?

Yes.

> If we include `plist`, I would want to implement it as shelling out to `plutil`, which means it would run only on macOS.

Why can't you use https://pkg.go.dev/howett.net/plist to make it work everywhere?

> I assume the `--reg-hive=X` and `--profile=Y` options will move here from `list-settings`

Yes. I may want to rename `--profile` to `--type`: `rdctl create-profile --type=locked ...`
 
> By human consumption, do you mean to leave the output of `rdctl list-settings` as JSON? I hope so, because it's non trivial to present hierarchical data in a tabular form.

I don't want it to be JSON. It doesn't have to be tabular, it could in outline format, with multiple blocks. See e.g. `docker info`.

At the very least we need to use the same setting name as we use on the commandline. Right now `rdctl list-settings` shows `virtualMachine.hostResolver` but `rdctl set` expects you to write `virtual-machine.host-resolver`. This doesn't make any sense.

But that is not part of this story; we should discuss it in its own issue. We are not changing the output of `list-settings` right now.
 
> If the server isn't running and no input is provided should `create-profile` get its input from the settings file, if it exists?

No, it should throw an error. Only the backend should load the `settings.json` file (and then apply the locked deployment profile on top). It is confusing if the command returns different settings when the backend isn't running, and we don't want to duplicate the profile processing logic in rdctl.

**Comment by ericpromislow** [comment]
> At the very least we need to use the same setting name as we use on the commandline. Right now rdctl list-settings shows virtualMachine.hostResolver but rdctl set expects you to write virtual-machine.host-resolver. This doesn't make any sense.

This makes sense if you're following the gnu/linux convention that all word-based options have the format `--hyphen-separated-all-lower-case`. But this format is less obvious when you're working with the API.

We should support both forms, and can hide the current set if need be.
