### ISSUE TITLE
Modify or delete scripts/generateReleaseList.js as it is out of date

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5026]
It appears that this script used to be used to generate the Upgrade Responder config. We need to decide whether to continue using this script. If we decide to keep it, it needs to be brought up to date to work with the new Upgrade Responder config.

**Comment by mook-as** [comment]
No, that was used to generate a list of Kubernetes versions (back when we were using minikube); that file is completely obsolete at this point.
(A hint is that it is a `.js` and not a `.ts`.)
