### ISSUE TITLE
Check if switching kubernetes versions leaves unused files around

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#506]
I have a suspicion that we are keeping different copies of the unpacked k3s user-space utilities on `/usr/lib/rancher`. They are unpacked under a UUID name and symlinked to a `current` entry.

**Comment by mook-as** [comment]
For when I look at this next time: they're in `/var/lib/rancher/k3s/data`.

**Comment by gaktive** [comment]
We should check with the k3s team about why they do this this way. @jandubois to ask.

**Comment by jandubois** [comment]
### Summary of #k3s discussion:

The data needs to stick around as long as there are pods running that have been started with that version of k3s.

The containers are re-parented to PID 1, so they keep running even when `k3s-agent` and `containerd` are stopped (so you get no downtime on your workload).

So if you deploy pods, upgrade k3s, deploy pods, and upgrade again, you would need to keep the last 3 versions around.

Therefore the only safe time to drop older data directories would be during a VM restart because then all containers have been stopped. We can simply `rm -rf /var/lib/rancher/k3s/data` in the provisioning script because `k3s server` will extract the current version again, and then all containers will be created with that version.
