### ISSUE TITLE
BATS test containers/allowed-images fails with 1.9.0, 1.9.1

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5066]
This is a problem with the test, not Rancher Desktop:

```shell
@test 'update the list of patterns first time' {
    update_allowed_patterns true "\"$IMAGE_NGINX\", \"$IMAGE_BUSYBOX\", \"$IMAGE_PYTHON\""
    wait_for_container_engine
}
```

The `update_allowed_patterns true ...` call will trigger a restart of the container engine (to configure it to use the proxy). However, by the time `wait_for_container_engine` is called, the engine is still running with the old config, so the following `pull` request is not subjected to the proxy filtering.

Adding a `sleep 10` between the 2 calls fixes the problem, but there should be a more robust way to do this.

Note that for unknown reasons this test worked as-is for the 1.8.1 release.

**Comment by jandubois** [comment]
Idea: check the daemon commandline arguments, e.g.

```console
# PIDFILE=$(RC_SVCNAME=containerd /lib/rc/bin/service_get_value pidfile)
# cat /proc/$(cat "$PIDFILE")/cmdline | tr '\0' '\n' | grep HTTPS
HTTPS_PROXY=http://127.0.0.1:3128
```

**Comment by mook-as** [comment]
Hmm, for me, it's doing the restart, but fails the test because it didn't want for the nginx proxy to restart.

Something like this fixes the issue for me:

```diff
diff --git bats/tests/helpers/load.bash bats/tests/helpers/load.bash
index 37ea92bb..8b7bf1e8 100644
--- bats/tests/helpers/load.bash
+++ bats/tests/helpers/load.bash
@@ -44,7 +44,8 @@ source "$PATH_BATS_HELPERS/paths.bash"
 # and PATH_* variables from paths.bash
 source "$PATH_BATS_HELPERS/commands.bash"
 
-# vm.bash uses various PATH_* variables from paths.bash
+# vm.bash uses various PATH_* variables from paths.bash,
+# rdctl from commands.bash, and jq_output from utils.bash
 source "$PATH_BATS_HELPERS/vm.bash"
 
 # kubernetes.bash has no load-time dependencies
diff --git bats/tests/helpers/vm.bash bats/tests/helpers/vm.bash
index a4b5b977..1214a8fd 100644
--- bats/tests/helpers/vm.bash
+++ bats/tests/helpers/vm.bash
@@ -156,8 +156,9 @@ docker_context_exists() {
     assert_line "$RD_DOCKER_CONTEXT"
 }
 
-buildkitd_is_running() {
-    run rdctl shell rc-service --nocolor buildkitd status
+service_is_running() { # service-name
+    local service_name="$1"
+    run rdctl shell rc-service --nocolor "$service_name" status
     assert_success
     assert_output --partial 'status: started'
 }
@@ -169,7 +170,16 @@ wait_for_container_engine() {
         try --max 30 --delay 5 docker_context_exists
         assert_success
     else
-        try --max 30 --delay 5 buildkitd_is_running
+        try --max 30 --delay 5 service_is_running buildkitd
         assert_success
     fi
+
+    run rdctl list-settings
+    assert_success
+    run jq_output '.containerEngine.allowedImages.enabled'
+    assert_success
+    # shellcheck disable=SC2154 # $output is set by `run`
+    if [ "$output" == "true" ]; then
+        try --max 30 --delay 5 service_is_running openresty
+    fi
 }
```
(Presumably there's a better way to check if we want it.)

**Comment by jandubois** [comment]
> Hmm, for me, it's doing the restart, but fails the test because it didn't want for the nginx proxy to restart.

So maybe we need both. For me the test has already failed while RD is still in the "Waiting for node" phase of the initial startup. Once that is complete it still restarts the VM once more.

I guess it depends on if you run with `containerd` or `moby`. `wait_for_container_engine` returns much earlier for `containerd` because it doesn't need to wait for the docker context to be written (which only happens when k3s is initialized).
