### ISSUE TITLE
Tachometer UI is not loading with containerd

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5072]
### Actual Behavior

Once the Tachometer extension is installed, the extension UI never loads with containerd.

### Steps to Reproduce

1. Run a factory-reset
2. Start Rancher Desktop with containerd and disabled extensions and allowed images list
3. From the catalog, install Tachometer
4. Once installation is complete, open the extension UI

### Result

Extension UI just shows a progress bar, but never loads 

From extensions.log:
```
2023-06-28T01:15:24.536Z: Image julianb90/tachometer:0.0.3 is allowed to install: undefined
2023-06-28T01:15:26.206Z: Extension julianb90/tachometer does not have containers to run.
2023-06-28T01:15:26.209Z: Install julianb90/tachometer: install complete.
2023-06-28T01:15:28.932Z: ipcMain: "extensions/spawn/streaming" triggered with arguments: {"command":["stats","--no-trunc","--format","{{ json . }}"],"execId":"1fdbae4028052b4685d59f22e499c4cf-docker-cli-0","scope":"docker-cli"}
```
Full logs:
[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/11888669/Archive.zip)

### Expected Behavior

Extension UI should load and be fully functional

### Rancher Desktop Version

1.9.0-22-g3a10d579

### Rancher Desktop K8s Version

1.27.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
Note that Tachometer _will_ spin forever if you have no containers (in the default namespace). That's a Tachometer thing.  However, starting a container while it's spinning will make things show up.

**Comment by gaktive** [comment]
@IsaSih to reproduce this with one container at least to confirm behaviour.

However, this may spawn an upstream request with nerdctl to handle this differently.

**Comment by mook-as** [comment]
This behaviour seems to be consistent between `docker` and `nerdctl` (that is, no output when there are no containers, and Tachometer spins).

**Comment by jandubois** [comment]
It doesn't look like there isn't anything for us to do; this is just how the extension works.
