### ISSUE TITLE
nerdctl support on rancher-desktop windows

### ISSUE THREAD

**Issue by claywd** [rancher-sandbox/rancher-desktop#5079]
### Problem Description

Would like to be able to talk to rancher desktop running in windows, using nerdctl within wsl, with the containerd runtime configured such that no docker is being used in the workflow. 

### Proposed Solution

Port over the work done to make rancher-desktop and macos play nicely with containerd/nerdctl minus the lima vm.

**Comment by mook-as** [comment]
Hi! Would you mind elaborating on what is desired here? It sounds like you want to be able to run `nerdctl` from within non-Rancher-Desktop WSL distros, and manage the containers that way?  That _should_ already be supported (though I believe we have issues with mounts and stdio).

If that is not working for you, specific commands involved that are not working would help.

Thanks!

**Comment by mook-as** [comment]
Closing this as we've all seemed to have forgotten about it and there's nothing actionable here.

Feel free to reply if you remember what this was about, and we can reopen it :)
