### ISSUE TITLE
Rancher Destop on Mac fails to start with error

### ISSUE THREAD

**Issue by saurabhguptaDoingCS** [rancher-sandbox/rancher-desktop#5088]
### Actual Behavior

Rancher Desktop used to work since last time I had started it on my macbook. 

Only change brought to system after which it stopped working could be the mac OS upgrade to 13.3.1 (not sure of the cause though)

### Steps to Reproduce

Try to start rancher desktop and it shows error after 15seconds.

### Result

**Rancher Error Screenshot:** 

<img width="908" alt="Screenshot 2023-07-03 at 9 08 23 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/13915911/923b7c3d-b05f-41c7-bc9b-7781cc963ac1">

**Detailed Error log-**

debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 11
/usr/bin/scp: Connection closed
2023-07-03T15:37:36.764Z: + limactl --debug copy /var/folders/z9/0j0ysjtn0_99y9dldckn60gm0000gn/T/rd-k3s-install-FRpFWk/install-k3s 0:bin/install-k3s
2023-07-03T15:37:36.764Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 255
2023-07-03T15:37:36.766Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 255
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:17:141690)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

### Expected Behavior

Rancher should start running with k8 images listed in the "Images tab"

### Additional Information

I have already tried uninstalling and reinstalling `limactl`  and then also did `limactl start` which resulted in following image running-

------
limactl ls
NAME   STATUS   SSH        ARCH   CPUS  MEMORY  DISK   DIR
**docker**  Running  127.0.0.1:54486  x86_64  4    4GiB   100GiB  /Users/saurabh.g/.lima/docker
------

but still startup is failing..

**Versions:** 
lima version- 0.12.0
limactl version- 0.12.0
kubernetes version- 

`kubectl version  
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"d42792181a1c816257050e6f7682475ddbc828af", GitTreeState:"clean", BuildDate:"2023-05-19T00:02:13Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.26) exceeds the supported minor version skew of +/-1`

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

v1.24.2

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

 Ventura 13.3.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Please upgrade to Rancher Desktop 1.9.1 and try again. 1.3.0 is ancient.

Also please don't run `limactl` manually against the Rancher Desktop instance; it won't work. Part of the startup logic is implemented in the Rancher Desktop backend.

**Comment by saurabhguptaDoingCS** [comment]
Hi @jandubois, but it was working earlier with the same version..

**Comment by jandubois** [comment]
> but it was working earlier with the same version..

In that case it is obviously something you changed on your system, and not with Rancher Desktop because Rancher Desktop 1.3 has not changed.

But anyways, even if there is a problem with Rancher Desktop, we can't do anything about it unless it happens with the latest release. Otherwise the fix is to update to the latest version.

I'm going to close this issue, as there is no action we can take on it. Feel free to re-open it if you still have problems with 1.9.1!

**Comment by saurabhguptaDoingCS** [comment]
it worked with latest Rancher Desktop 1.9.1. Thansk @jandubois

**Comment by saurabhguptaDoingCS** [comment]
Hi @jandubois , thanks for the solution, it worked!
