### ISSUE TITLE
Windows installer UAC prompt with random filename

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5089]
When installing 1.9.1 I see this UAC prompt:

<img width="451" alt="CleanShot 2023-07-03 at 12 11 20@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/98861bac-48cb-4edd-aed0-eee884551627">

So the file is signed by SUSE, but the `27aac9.msi` filename makes me worry if the package has been tampered with. Can we use a human-readable name for the internal MSI?

**Comment by mook-as** [comment]
As far as I know, we can't — that's the name of a temporary file Windows creates (I'm not sure if it's because the file you're starting from isn't accessible by the service or something).

**Comment by jandubois** [comment]
I think it is a bug of the signing script because it signs a temporary copy of the original file. See also https://stackoverflow.com/questions/4315840/the-uac-prompt-shows-a-temporary-random-program-name-for-msi-can-the-correct-na

**Comment by jandubois** [comment]
So it looks like passing `/d "Rancher Desktop` to `signtool` might be all that is needed.

At second glance I'm wondering if we can specify the icon in the UAC prompt as well; the current one seems to be generic.

**Comment by jandubois** [comment]
@IsaSih Please ask @ericpromislow for a properly signed build to verify that looks correct when properly packaged and signed like a release!

**Comment by IsaSih** [comment]
@ericpromislow please, provide me the signed build for me to test it. Thanks!
