### ISSUE TITLE
Traefik Ingress Issue - Skipping service: no endpoints found Windows 10 wsl

### ISSUE THREAD

**Issue by amardeep2006** [rancher-sandbox/rancher-desktop#5093]
### Actual Behavior

I have deployed a very simple app via helm chart on local kubernetes. The application is not accessible via Ingress.
The application is accessible if I port forward service directly which means service is created correctly.

I also tried following and it works fine with nginx ingress: 

- Disable Traefik ingress
- Deploy nginx-ingress
- Add ingress class as nginx in ingress.yaml file

### Steps to Reproduce

1. Clone following repo:  https://github.com/jwsy/simplest-k8s/tree/helm
2. Checkout branch named **helm**
3. `helm install jadeshooter .`
4. Tried below URLs in browser : 

https://jade-shooter.rancher.localhost/

http://jade-shooter.rancher.localhost/

### Result

You will see connection refused error in browser.

### Expected Behavior

URL must open and your should see a lovely game called Jadeshooter.

### Additional Information

I see this error in Traefik pod 

`time="2023-07-01T05:04:36Z" level=error msg="Skipping service: no endpoints found" serviceName=jade-shooter-service servicePort="&ServiceBackendPort{Name:,Number:30080,}" providerName=kubernetes ingress=jade-shooter namespace=default`

I also posted this issue on rancher slack channel where @ericpromislow is able to reproduce this issue on Windows machine.

https://rancher-users.slack.com/archives/C0200L1N1MM/p1688382572421829

Please let me know if you need more details.

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

v1.26.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 22H2 (Build 19045.2132)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

I have I have Zscaler VPN on my machine.

**Comment by ericpromislow** [comment]
See the `Steps to Reproduce` section above.

No problem running `helm install js .` and then hitting the endpoint on macOS. On Windows 10/WSL2 I ran into the same problem reported here - the endpoint didn't work, and the traefik logs suggested why.

**Comment by Nino-K** [comment]
@amardeep2006 is this with the experimental network enabled or disabled?

**Comment by Nino-K** [comment]
Unfortunately, I cannot repro this, it works fine for me (using the experimental network). 

Please see the screenshots attached. 

![Screen Shot 2023-07-04 at 9 37 26 AM](https://github.com/rancher-sandbox/rancher-desktop/assets/10409174/1c55ba6e-d44c-4c61-a71e-0c13b66b1af0)
![Screen Shot 2023-07-04 at 9 37 07 AM](https://github.com/rancher-sandbox/rancher-desktop/assets/10409174/ccd0b3f2-e160-4655-b02d-97002dcffdc4)

**Comment by Nino-K** [comment]
@amardeep2006 I'm going to close the issue, please try enabling the experimental network using the following:
```
rdctl set --experimental.virtual-machine.networking-tunnel=false
```
Feel free to reopen if you reencounter the issue.

**Comment by jandubois** [comment]
You can enable this inside the app preferences too: https://docs.rancherdesktop.io/1.9/ui/preferences/wsl/network

**Comment by amardeep2006** [comment]
Thanks a lot @jandubois @ericpromislow @Nino-K 
This is working for me with Traefik ingress as well after enabling the experimental network Tunnel.
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/50517840/a8ee00a9-daac-454d-9f4d-00d41017dbba)
