### ISSUE TITLE
Support for managing hosts in the noproxy list from preferences

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5100]
We want to be able to manage the noproxy list from the preferences dialog, so that hosts that should not be proxied can be specified easily from the UI.

## Proposal

- Display the noproxy list in the WSL Proxy tab alongside other controls
- Manage hosts in the noproxy list via a `textarea`

## Acceptance Criteria

- [ ] Existing hosts in the noproxy list are displayed in a scrollable and easily viewable format
- [ ] Users can add new hosts to the noproxy list
- [ ] Users can delete hosts from the noproxy list
- [ ] Users can edit existing hosts in the noproxy list
- [ ] Users can bulk-add multiple hosts to the noproxy list by providing a comma-delimited string

## Mockup

![Drawing 2023-07-05 06 41 30 excalidraw](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/ed44b564-1cfe-4eff-a1d0-9bd40ba18ca0)

**Comment by rak-phillip** [comment]
I'm working on a rough mockup for how the layout of this tab should look. I'll update the issue description when it is ready.

**Comment by gaktive** [comment]
@rak-phillip to tidy this ticket up for a 1.11 and then for PR #4898, have a ticket to reflect its current state for QA for 1.10.

**Comment by rak-phillip** [comment]
As we discussed, we would like to merge the `textarea` implementation and follow up with some enhancements. Created #5344 to track this work.
