### ISSUE TITLE
Split postinstall.ts into three parts

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5127]
### The Plan

The second part builds the go utils. It doesn't import any node code from `@pkg/`

The third part is the existing `postinstall.ts`

The first part is running any code that generates Go files used by the second part, which so far is 
`scripts/generateCliCode.ts`, and its only dependency on the node code is importing 
`CURRENT_SETTINGS_VERSION` from `pkg/rancher-desktop/config/settings.ts`

Because we can't import `pkg/rancher-desktop/config/settings.ts` until the Go files are built, the new
`postinstall.ts` will need a differrent approach to find the value for `CURRENT_SETTINGS_VERSION`

Try to use dependencies.yaml to keep `CURRENT_SETTINGS_VERSION` in exactly one place.

**Comment by jandubois** [comment]
> Try to use dependencies.yaml to keep `CURRENT_SETTINGS_VERSION` in exactly one place.

Shouldn't the settings version be defined by `pkg/rancher-desktop/assets/specs/command-api.yaml`?

**Comment by ericpromislow** [comment]
Fixed by #5169
