### ISSUE TITLE
Refactor postinstall to remove dependency on RD packages

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5128]
The current `postinstall.ts` code imports various `@pkg/rancher-desktop` like `logging` and `settings`.

#5127 is splitting out the part that builds Go binaries because any code that imports our `paths` package needs a working `rdctl paths` command, leading to a chicken-and-egg situation.

This issue is about refactoring the rest of post-install to not share code with the application, if possible, to avoid having special-case logic in the app that is really only needed for installation at build time.

**Comment by ericpromislow** [comment]
Fixed by #5169
