### ISSUE TITLE
Allow socket_vmnet configuration for VZ emulation

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5179]
Support for `socket_vmnet` was implemented in Lima in https://github.com/lima-vm/lima/pull/1279 but does not include `vde_vmnet` support because that driver is deprecated.

Commit https://github.com/rancher-sandbox/rancher-desktop/commit/18d94918caf920dc74455a194268684ce5700c18 erroneously disabled both `vde_vmnet` and `socket_vmnet` when using `vz`.

`socket_vmnet` needs to be re-enabled, and a diagnostic should be displayed when `vz` is selected, admin mode is enabled, but `socket_vmnet` isn't.

See also #5176

**Comment by gaktive** [comment]
Diagnostic can be done in a separate ticket.
