### ISSUE TITLE
Rancher Desktop auto-update believes v0.7.1 is the newest version

### ISSUE THREAD

**Issue by nhinds** [rancher-sandbox/rancher-desktop#5184]
### Actual Behavior

In Rancher Desktop 1.9.0 on MacOS with auto-updates enabled, an update to version 1.9.1 is not offered.

### Steps to Reproduce

Install Rancher Desktop 1.9.0 (also seen in 1.8.1) and enable auto updates
Check the UI for updates, or check `~/Library/Logs/rancher-desktop/update.log` and `~/Library/Caches/rancher-desktop/updater-longhorn.json`

### Result

No update is offered.

`~/Library/Logs/rancher-desktop/update.log` indicates that it believes version 0.7.1 is the newest available. With debug logging enabled:
```
2023-07-18T16:38:10.030Z: Setting up updater... enabled=true doInstall=true
2023-07-18T16:38:10.038Z: Checking for update
2023-07-18T16:38:10.038Z: update: checking for update
2023-07-18T16:38:10.087Z: Checking https://desktop.version.rancher.io/v1/checkupgrade for updates
2023-07-18T16:38:10.432Z: Upgrade Responder response: {
  versions: [
    {
      Name: 'v0.7.1',
      ReleaseDate: '2021-12-20T14:30:00Z',
      Tags: [ 'v0.7.1', 'latest', [length]: 2 ]
    },
    {
      Name: 'v0.7.0',
      ReleaseDate: '2021-12-16T14:30:00Z',
      Tags: [ 'v0.7.0', [length]: 1 ]
    },
    {
      Name: 'v0.6.1',
      ReleaseDate: '2021-11-02T12:30:00Z',
      Tags: [ 'v0.6.1', [length]: 1 ]
    },
    {
      Name: 'v0.6.0',
      ReleaseDate: '2021-10-15T12:30:00Z',
      Tags: [ 'v0.6.0', [length]: 1 ]
    },
    {
      Name: 'v0.5.0',
      ReleaseDate: '2021-09-27T12:30:00Z',
      Tags: [ 'v0.5.0', [length]: 1 ]
    },
    {
      Name: 'v0.4.1',
      ReleaseDate: '2020-05-18T12:30:00Z',
      Tags: [ 'v0.4.1', [length]: 1 ]
    },
    [length]: 6
  ]
}
2023-07-18T16:38:11.027Z: Update for version 1.9.0 is not available (latest version: v0.7.1, downgrade is disallowed).
2023-07-18T16:38:11.027Z: update: not available: {
  files: [
    {
      url: 'https://github.com/rancher-sandbox/rancher-desktop/releases/download/v0.7.1/Rancher.Desktop-0.7.1-mac.x86_64.zip',
      size: 357272372,
      sha512: 'gedZTW+3gM7JB2XA3usLD0G00GdvzyuWwipH2/OyDZeBasC99tNPx5H5Nwp4qgBzJAUS89rCsRhXnjzjuF7jpA==',
      isAdminRightsRequired: false
    }
  ],
  version: 'v0.7.1',
  path: '',
  sha512: '',
  releaseName: 'Rancher Desktop 0.7.1',
  releaseNotes: 'This is a patch release of Rancher Desktop, an open source desktop application to bring Kubernetes and container management to Mac, Windows, and Linux. This release fixes a networking bug.\r\n' +
    '\r\n' +
    'You can connect with the developers via:\r\n' +
    '\r\n' +
    '- The [issue queue](https://github.com/rancher-sandbox/rd/issues)\r\n' +
    '- [Rancher Users Slack](https://slack.rancher.io/) in the #rancher-desktop channel\r\n' +
    '\r\n' +
    '## Changelog\r\n' +
    '\r\n' +
    'The [full version changelog, from v0.7.0, can be found using GitHub compare](https://github.com/rancher-sandbox/rancher-desktop/compare/v0.7.0...v0.7.1).',
  releaseDate: '2021-12-20T16:55:35Z',
  nextUpdateTime: 1689701890432,
  unsupportedUpdateAvailable: false
}
```

The same information about 0.7.1 is available in `~/Library/Caches/rancher-desktop/updater-longhorn.json`:
```
{"nextUpdateTime":1689701890432,"unsupportedUpdateAvailable":false,"isInstallable":false,"release":{"tag":"v0.7.1","name":"Rancher Desktop 0.7.1","notes":"This is a patch release of Rancher Desktop, an open source desktop application to bring Kubernetes and container management to Mac, Windows, and Linux. This release fixes a networking bug.\r\n\r\nYou can connect with the developers via:\r\n\r\n- The [issue queue](https://github.com/rancher-sandbox/rd/issues)\r\n- [Rancher Users Slack](https://slack.rancher.io/) in the #rancher-desktop channel\r\n\r\n## Changelog\r\n\r\nThe [full version changelog, from v0.7.0, can be found using GitHub compare](https://github.com/rancher-sandbox/rancher-desktop/compare/v0.7.0...v0.7.1).","date":"2021-12-20T16:55:35Z"},"file":{"url":"https://github.com/rancher-sandbox/rancher-desktop/releases/download/v0.7.1/Rancher.Desktop-0.7.1-mac.x86_64.zip","size":357272372,"checksum":"gedZTW+3gM7JB2XA3usLD0G00GdvzyuWwipH2/OyDZeBasC99tNPx5H5Nwp4qgBzJAUS89rCsRhXnjzjuF7jpA=="}}
```

### Expected Behavior

An update to 1.9.1 should be offered

### Additional Information

Deleting `~/Library/Caches/rancher-desktop/updater-longhorn.json` and re-launching Rancher Desktop results in the same behaviour.

It seems that Rancher Desktop is POSTing an object `{"appVersion":"1.9.0","extraInfo":{"platform":"darwin-x64","platformVersion":"13.4.1"}}` to https://desktop.version.rancher.io/v1/checkupgrade. When I do the same via `curl`, I also get a response containing 0.x versions:
```
$ curl -X POST -d '{"appVersion":"1.9.0","extraInfo":{"platform":"darwin-x64","platformVersion":"13.4.1"}}' https://desktop.version.rancher.io/v1/checkupgrade
{"versions":[{"Name":"v0.7.1","ReleaseDate":"2021-12-20T14:30:00Z","Tags":["v0.7.1","latest"]},{"Name":"v0.7.0","ReleaseDate":"2021-12-16T14:30:00Z","Tags":["v0.7.0"]},{"Name":"v0.6.1","ReleaseDate":"2021-11-02T12:30:00Z","Tags":["v0.6.1"]},{"Name":"v0.6.0","ReleaseDate":"2021-10-15T12:30:00Z","Tags":["v0.6.0"]},{"Name":"v0.5.0","ReleaseDate":"2021-09-27T12:30:00Z","Tags":["v0.5.0"]},{"Name":"v0.4.1","ReleaseDate":"2020-05-18T12:30:00Z","Tags":["v0.4.1"]}]}
```

It appears that the upgrade check site is not returning new versions of Rancher Desktop.

Other people I know are experiencing the same on other versions, e.g. 1.8.1 (which logs "Update for version 1.8.1 is not available (latest version: v0.7.1, downgrade is disallowed)").

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

v1.25.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.4.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Hi @nhinds! It's interesting to see that you're getting `0.7.1` as the latest version since I see on our auto-upgrade server that it definitely goes up to the latest `1.9.1`.

Are you running your setup through a proxy at all or VPN? Or what can you tell me about your networking setup? I suspect that you're somehow accessing a stale cached version of version.rancher.io, which should be an updated S3 bucket on AWS. Otherwise, the Epoch time looks expected so there's no local clock skew.

Within the app itself, can you go to the Troubleshooting section and Enable debut mode to then Show Logs? Let me know if there any privacy concerns prior to uploading and we can figure out another way to get the files at hand. 

As for the others you've stated are running into similar issues, do they have an identical setup to you? 

Thanks!

**Comment by jandubois** [comment]
Since you get the same wrong response via `curl` the issue must be a caching proxy along the path. I get the correct response using your `curl` command:

```console
$ curl -s -X POST -d '{"appVersion":"1.9.0","extraInfo":{"platform":"darwin-x64","platformVersion":"13.4.1"}}' https://desktop.version.rancher.io/v1/checkupgrade | jq | head
{
  "versions": [
    {
      "Name": "1.9.1",
      "ReleaseDate": "2023-06-29T16:00:00Z",
      "Supported": true,
      "Tags": [
        "latest"
      ],
      "ExtraInfo": null
```

**Comment by nhinds** [comment]
I now get the correct response via curl, as do the other impacted people I knew, and the upgrade is showing as available in the UI.

I promise there was no caching proxy as I do not have a proxy, and the same `curl` command returned the incorrect 0.7.1 response when run from a random EC2 linux instance in Oregon when I initially raised this issue. To me it seems that something has changed in the https://desktop.version.rancher.io/v1/checkupgrade server in the past 6 hours.

Regardless of how/why this is fixed, it's working now so I'm happy to close this.

**Comment by jandubois** [comment]
I've confirmed that the upgrade server was upgraded earlier today, so it looks like the config map was temporarily set to the canned config from the helm chart, and then updated to the current version a bit later today.

Thanks for letting us know; everything should be good now.
