### ISSUE TITLE
UI for creating symlink gets stuck on error

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#520]
I just tested RD on a fresh install of macOS Monterey Public Beta (well, it was upgrade from a "pristine" VM that was running Big Sur, which in turn may have been created by upgrading a pristine Catalina VM). It did have a `/usr/local` directory owned by `root`, but no `/usr/local/bin`.

Trying to create the symlink shows this error:

<img width="582" alt="Screen Shot 2021-08-18 at 10 48 09 PM" src="https://user-images.githubusercontent.com/78947/130020399-aef208e2-e5b9-4504-8d41-b3f6a3012675.png">

The checkbox is un-clickable afterwards, even once the directory has been created and made writable by the current user.

If you click any of the other checkboxes though, which will then unblock the one with the error message. But the whole behaviour is rather unintuitive.

**Comment by mook-as** [comment]
#542 is touching the same areas heavily; we should not work on this until that's merged.

**Comment by ericpromislow** [comment]
Testing this on top of PR #542, following are needed:

1. Show both errors and warnings
2. Don't disable the checkbox -- when it's clicked, the error shows. The shadowing warnings should always appear.
