### ISSUE TITLE
Tray option to toggle proxy connection configured in the preference

### ISSUE THREAD

**Issue by tperale** [rancher-sandbox/rancher-desktop#5256]
### Problem Description

When using a proxy inside an air gapped environment you often need to enable/disable the wsl proxy connection.
When doing this multiple time it's annoying to always have to open rancher-desktop, click on the preference, open the WSL proxy tab, tick the toggle button, and apply the settings.

### Proposed Solution

Add an option in the tray icon that allows user to toggle the proxy connection in one click.

This option should only appear if the address and port of the proxy are set on the preference window to not add any unused options to the tray menu.

### Additional Information

Check the preference on the `updateMenu()` (triggered by the settingsChanged method) and add the "proxy" tray option if `experimental.virtualMachine.proxy.address` & `experiament.virtualMachine.proxy.port` preferences are defined.
A click on this tray option just toggle the `experimental.virtualMachine.proxy.enabled` preference.

**Comment by jandubois** [comment]
> Add an option in the tray icon that allows user to toggle the proxy connection in one click.

@tperale Thank you for implementing this functionality already in a PR, but we have decided that we want to keep the notification menu pretty minimal for now.

Even if it is only shown when a proxy is configured, it still complicates the documentation etc.

While not quite as nice as an integrated solution, you can still implement this yourself with a small script like this (or the equivalent PowerShell):

```shell
TOGGLE=$(rdctl api settings | jq '.experimental.virtualMachine.proxy.enabled|not')
rdctl set --experimental.virtual-machine.proxy.enabled=$TOGGLE
```

And then invoke it via desktop icon link, hotkey, or from your shell.

We can revisit this issue if a larger number of users ask for it, but for now I'm going to close the issue and PR.
