### ISSUE TITLE
Push button expose a service locally

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#53]
When someone deploys a workload they will often want to access using a port forward. Today you need to know the right kubectl commands to make that happen.

We want to provide a UI that lists workloads and provides a button to create a port forward.

There are numerous details that still need to be worked out such as, is the list just for services or does it include pods?

**Comment by mook-as** [comment]
#46 (the dashboard PR) has stuff for port forwarding.  We could build on that (it takes namespace + endpoint, i.e. ~service) for forwarding.

Alternatively, we could instead go for an internal ingress controller; however that would be significantly more work, and it's unclear for me at the moment how we'd map it to what we can do (we can't allocate arbitrary ports).

**Comment by mattfarina** [comment]
My initial thought was to do the port forwarding in a similar way to the dashboard PR.

The important part of this is the user experience/interface. We want to make the experience be simple.

**Comment by agracey** [comment]
Is this closed? I see it as "Done"

**Comment by mook-as** [comment]
Yep, I think so: we can forward ports in the UI.  Please reopen if there's more work to be done here.
