### ISSUE TITLE
Rancher dashboard does not load

### ISSUE THREAD

**Issue by amardeep2006** [rancher-sandbox/rancher-desktop#5300]
### Actual Behavior

I cannot open rancher dashboard on Windows 11.  It always shows a loading animation

<img width="590" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/50517840/54710d4f-0db8-40ea-be98-83f4b990e7c7">

### Steps to Reproduce

I clicked on following menu to reproduce 

<img width="194" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/50517840/709eed92-67ad-45ea-96fa-7eb85e88cad0">

### Result

There is no error, it always show as loading.

### Expected Behavior

Rancher Dashboard must load to show kubernetes resources.

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.27.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

I have Norton AntiVirus.

**Comment by s0nea** [comment]
Hi @amardeep2006,

Thank you for the bug report!
I tried it on my dev environment and it worked without any issues. Would it be possible to test is with Norton temporarily disabled? Just to make sure it's not related. Also, have you already tried to do a factory reset?

**Comment by amardeep2006** [comment]
Hi @s0nea , I tried both kubernetes reset and factory reset but facing same issue. I also disabled Norton . Also do not see event in Norton logs. Please suggest on troubleshooting it further. @gaktive

**Comment by amardeep2006** [comment]
i enabled debugging and here are logs for dashboard server 
[dashboardServer.log](https://github.com/rancher-sandbox/rancher-desktop/files/12326822/dashboardServer.log)

**Comment by amardeep2006** [comment]
@s0nea @gaktive I found the root cause in steve.log . It was nahimic service blocking port 9080.
I had to use TCPView tool to find out service blocking this port.

this issue was also helpful https://github.com/rancher-sandbox/rancher-desktop/discussions/5326

2023-08-26T10:28:10.073Z: stderr: time="2023-08-26T15:58:10+05:30" level=info msg="Listening on 127.0.0.1:9443"
time="2023-08-26T15:58:10+05:30" level=info msg="Listening on 127.0.0.1:9080"

2023-08-26T10:28:10.074Z: stderr: time="2023-08-26T15:58:10+05:30" level=fatal msg="http server failed: listen tcp 127.0.0.1:9080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."

2023-08-26T10:28:10.079Z: child process exited with code 1

**Comment by mikeseese** [comment]
For people finding via Google, Logitech G Hub also listens on 9080. Uninstalling it got the dashboard working for me.

**Comment by Sh1ken** [comment]
@mikeseese Saved my day. Thanks!

**Comment by UncleMarky** [comment]
Had to disable Logitech G Hub as well. Is it possible to modify the port to avoid future conflicts?
