### ISSUE TITLE
403 on docker push

### ISSUE THREAD

**Issue by wibed** [rancher-sandbox/rancher-desktop#5301]
### Actual Behavior

```shell
export CR_PAT=<**THIS IS A KEY**> 
echo $CR_PAT | docker login ghcr.io -u USER --password-stdin
>Login Successfull
docker tag PACKAGE:latest ghrc.io/USER/PACKAGE:latest 
docker push ghrc.io/USER/PACKAGE:latest
>"<html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n\n"
```

### Steps to Reproduce

- create github token `Settings -> Developer Settings -> Create Token Classic -> Permissions on Package read/write/whatever you find related to the docker registry

```shell
export CR_PAT=<**THIS IS A KEY**> 
echo $CR_PAT | docker login ghcr.io -u USER --password-stdin
>Login Successfull
docker tag PACKAGE:latest ghrc.io/USER/PACKAGE:latest 
docker push ghrc.io/USER/PACKAGE:latest
>"<html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n\n"
```

### Result

unexplicable 403 error

### Expected Behavior

successfull push

### Additional Information

tried different push methods
- docker build . --push -t ghrc.io/USER/PACKAGE
- docker image push ghrc.io/USER/PACKAGE 

related issues:
- https://github.com/moby/moby/issues/15612

same output

### Rancher Desktop Version

1.1.0, 

### Rancher Desktop K8s Version

-

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

sonoma

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Hi @wibed!

Can you confirm what version you're running on? 1.1.0 is a fair bit behind our latest (1.9.1).

Thanks!

**Comment by wibed** [comment]
sorry, i reported the version of the rdctl client.

the actual version is 1.9.1, by the main window of rancher desktop

**Comment by adamkpickering** [comment]
> ghrc.io/USER/PACKAGE:latest

I think it's ghcr.io, not ghrc.io...

**Comment by wibed** [comment]
indeed
