### ISSUE TITLE
Containers page: group containers in application 

### ISSUE THREAD

**Issue by scures** [rancher-sandbox/rancher-desktop#5308]
### Problem Description

#5258 introduces the container page which will list all (running/stopped..) containers & enables some generic actions (start, stop, or delete) (mostly the View containers  & manage containers from EPIC #4506 )

### Proposed Solution

As follow up we should deal with some other improvements:
- Group running containers from `docker-compose` in an app. We could use the `group-row` functionality from Sortable Tables (?). Looking at the functionality that brings the containers list, in the `Labels`, there's some metadata we might be able to use (such as the `config_files` path, using this to understand which containers are part of an application but a better solution might be available)

**Comment by Fladolcetta** [comment]
I see that this issue was marked as "Closed Completed". Did this ever get implemented? If so how does one enable it?
