### ISSUE TITLE
Settings validator: `checkMulti` doesn't always check all validators

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5313]
Re: https://github.com/rancher-sandbox/rancher-desktop/blob/60d7d9439f51aeb9ab023ab1f1b5b8d561907dbe/pkg/rancher-desktop/main/commandServer/settingsValidator.ts#L371

Note that the return value of the validators is whether anything has changed, and _not_ if it succeeded. That means that the current code instead stops when it encounters the first preference that was unchanged.

I believe the correct thing to do would be to split calling sub-validators and computing the result.

_Originally posted by @mook-as in https://github.com/rancher-sandbox/rancher-desktop/issues/5174#issuecomment-1670451363_

**Comment by s0nea** [comment]
Thank you for taking a look and pointing it out.

So... does this mean the `checkMulti` validator was never supposed to be used in the way I made it with the change?

**Comment by mook-as** [comment]
Yes, I think `checkMulti` should always run all sub-validators to get errors (or, alternatively, run all validators in order, and determine if the next one should run based on if `errors` was appended to, instead of the return value).  That is to say, both before and after the change was incorrect.

I believe `checkMulti` should:
- Always run through all sub-validators (to detect any errors) (see above for alternate)
- Return `true` if _any_ of the sub-validators return true.

Alternatively, we can drop `checkMulti` and make `checkMountType` / `checkVMType` call `checkEnum` internally.  That should make the logic clearer.

**Comment by s0nea** [comment]
> Yes, I think `checkMulti` should always run all sub-validators to get errors (or, alternatively, run all validators in order, and determine if the next one should run based on if `errors` was appended to, instead of the return value). That is to say, both before and after the change was incorrect.

Understood!

> 
> I believe `checkMulti` should:
> 
> * Always run through all sub-validators (to detect any errors) (see above for alternate)

I agree!

> * Return `true` if _any_ of the sub-validators return true.

What is the reason behind it? - As far as I understand it `true` stands for "no error occurred". I'm not really sure why `true` should be returned if _one_ of the sub-validators returns `true`. If there is an error, it won't be detected. Or am I wrong here? 

I thought `true` should be returned if _all_ validators succeed. `false` should be returned if _one_ of the validators failed.

> 
> Alternatively, we can drop `checkMulti` and make `checkMountType` / `checkVMType` call `checkEnum` internally. That should make the logic clearer.

**Comment by mook-as** [comment]
The API signature is pretty silly; the return value signifies if a setting had changed, not whether an error occurred.
https://github.com/rancher-sandbox/rancher-desktop/blob/c69dfcb0d4f30c0ca2bedad0ae7f34e66ea81c09/pkg/rancher-desktop/main/commandServer/settingsValidator.ts#L34

It might be useful to change the signature in a follow-up PR to make more sense…

**Comment by s0nea** [comment]
> The API signature is pretty silly; the return value signifies if a setting had changed, not whether an error occurred.
> 
> https://github.com/rancher-sandbox/rancher-desktop/blob/c69dfcb0d4f30c0ca2bedad0ae7f34e66ea81c09/pkg/rancher-desktop/main/commandServer/settingsValidator.ts#L34
> 
> It might be useful to change the signature in a follow-up PR to make more sense…

Okay, got it. Thank you for your explanations! :slightly_smiling_face:
