### ISSUE TITLE
Noproxy list enhancements

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5344]
#5100 focused on getting a functional noproxy list implementation that will display items in an orderly. We would like to enhance this implementation with the string list component.  

## Proposal

- Implement the string list component to manage hosts in the noproxy list

## Acceptance Criteria

- [ ] Existing hosts in the noproxy list are displayed in a scrollable and easily viewable format
- [ ] Users can add new hosts to the noproxy list
- [ ] Users can delete hosts from the noproxy list
- [ ] Users can edit existing hosts in the noproxy list
- [ ] Users can bulk-add multiple hosts to the noproxy list by providing a comma-delimited string https://github.com/rancher/dashboard/issues/9707
- [ ] The noproxy list must be lockable via deployment profile #5468
- [ ] The following PRs that dealt with the text area are reverted
   - [ ] #5445
   - [ ] #5379
   - [ ] #5479 
   - [ ] #5382
   
## Mockup

![Drawing 2023-07-05 06 41 30 excalidraw](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/ed44b564-1cfe-4eff-a1d0-9bd40ba18ca0)

**Comment by IsaSih** [comment]
You might want to add as an enhancement to not allow white spaces on the nopoxy list as users hitting enter /deleting existing hosts leave lots of white space on the list. I suggest this list to behave the same way a the allowed images list
<img width="1026" alt="Screen Shot 2023-08-18 at 10 47 30 AM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/541b07f1-fe41-4d69-ad66-8853ede9e59a">

**Comment by rak-phillip** [comment]
@IsaSih after we implement this enhancement, the no proxy hostname list will function similarly to the image allow list. The current implementation allows for getting the base functionality in place.

**Comment by ericpromislow** [comment]
Please undo PR #5445 when this is implemented.

**Comment by jandubois** [comment]
> Please undo PR #5445 and then #5379 when this is implemented (might need to be done manually).

Also undo #5479 and at least the BATS changes from #5382.

**Comment by s0nea** [comment]
Thank you for the details!

> We did weaken the validation requirements to allow empty lines in the noproxy list because the textbox could easily introduce them.
>

Understood!
 
> When we switch to our own string list control, it will no longer be possible to add empty strings to the list, so the validation can be tightened again (so it also rejects them coming through the API)
> 
> This means we should adjust the BATS test to verify that the API returns an error when the list contains empty strings, or whitespace strings.
> 

But doesn't it mean we should **not** revert the BATS changes in https://github.com/rancher-sandbox/rancher-desktop/pull/5382? As far as I understand it, it will then remove the `complain about duplicate whitespace in string-list properties` test case?

**Comment by jandubois** [comment]
> But doesn't it mean we should **not** revert the BATS changes in #5382? As far as I understand it, it will then remove the `complain about duplicate whitespace in string-list properties` test case?

The test will no longer work because the validator will then reject any empty/whitespace entries in the list, even before it checks for duplicates. That's why I added:

>> This means we should adjust the BATS test to verify that the API returns an error when the list contains empty strings, or whitespace strings.

**Comment by s0nea** [comment]
Okay, so if I now understand it correctly, the changes made to `bats/tests/containers/allowed-images.bats` in https://github.com/rancher-sandbox/rancher-desktop/pull/5579 need to be reverted as well?

**Comment by jandubois** [comment]
Yes, but please keep the changes to `bats/tests/helpers/os.bash`, as they are generic and are now used in other places as well.

**Comment by jandubois** [comment]
It is probably easiest to manually rip out the `@test` blocks that no longer apply instead of trying to revert the git commits.
