### ISSUE TITLE
Addressing New Usage Limits for Cirrus CI in Rancher Desktop

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5345]
We heavily rely on Cirrus CI to execute end-to-end tests for Rancher Desktop. However, recent changes to Cirrus CI's free tier introduce usage limits on compute resources. This could lead to interruptions in our CI tasks.

## Current Usage

Our current e2e testing process appears to exceed the 50 compute credit limit imposed by the new Cirrus CI usage limits [^1]. We need to evaluate how this change will affect our testing pipeline and identify strategies to mitigate disruptions.

## Proposed Solutions

- [ ] Improve CPU utilization of CI tasks.
- [ ] [Bring your own compute](https://cirrus-ci.org/guide/supported-computing-services/).
- [ ] [Use compute credits](https://cirrus-ci.org/pricing/#configuring-compute-credits).
- [ ] Investigate other platforms & solutions for running our e2e tests.

## References

- https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/

[^1]: ![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/4a089ab2-6238-47bb-ba60-4ae7ae5bb375)

**Comment by gaktive** [comment]
@gunamata checking with @ml8mr on options tied to pricing.

**Comment by gaktive** [comment]
We received credits to help out here. Otherwise, we're working on using Github Runners in #5507
