### ISSUE TITLE
Create BATS tests for --option json in rdctl settings

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5356]
### Problem Description

Create BATS tests that cover testing `rdctl list-settings` and the default output format, which is JSON and a test for `rdctl list-settings --option json`, both asserting that the output is generated in JSON format.

### Proposed Solution

Create BATS tests to verify the scenarios illustrated in the problem description

**Comment by ericpromislow** [comment]
This test is obsolete, every since we implemented `rdctl create-profile...` . The result for `rdctl list-settings` is always JSON, and there is no output option anymore.
