### ISSUE TITLE
bats test `containers/factory-reset.bats` fails on linux

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5393]
### Actual Behavior

On macOS, it complains that after running `rdctl factory-reset` we still have `credential-server.json` and `rd-engine.json` in `~/Library/Application\ Support/rancher-desktop/`

On Linux, it complains that `/.local/share/rancher-desktop` still exists (because it contains a `snapshots` subdirectory that should not be deleted.

### Steps to Reproduce

Run `bats bats/tests/containers/factory-reset.bats`

### What operating system are you using?

macOS & linux

**Comment by jandubois** [comment]
> On macOS, it complains that after running `rdctl factory-reset` we still have `credential-server.json` and `rd-engine.json` in `~/Library/Application\ Support/rancher-desktop/`

Is this a recent change in the `rdctl factory-reset` implementation? This test used to pass before.

> On Linux, it complains that `/.local/share/rancher-desktop` still exists (because it contains a `snapshots` subdirectory that should not be deleted.

This is changed behaviour, and we need to adjust the test to account for this.

**Comment by ericpromislow** [comment]
Commit 9856439d0d90c82c4b9f539995f815bdf3f4a49c on July 19 dropped `paths.AppHome` from the list of paths to delete in `src/go/rdctl/pkg/factoryreset/delete_data_darwin.go` but didn't add the specific members of that directory to `pathList`.

**Comment by jandubois** [comment]
> Commit [9856439](https://github.com/rancher-sandbox/rancher-desktop/commit/9856439d0d90c82c4b9f539995f815bdf3f4a49c) on July 19 dropped `paths.AppHome` from the list of paths to delete in `src/go/rdctl/pkg/factoryreset/delete_data_darwin.go` but didn't add the specific members of that directory to `pathList`.

Awesome, so the test detected an actual bug in the change!

I've filed a separate issue for it in #5401.
