### ISSUE TITLE
Experimental Networking Tunnel blocks access via WSL2

### ISSUE THREAD

**Issue by worldofgeese** [rancher-sandbox/rancher-desktop#5406]
### Actual Behavior

Enabling the Networking Tunnel feature blocks access over WSL2. `kubectl` commands continue to function normally from PowerShell on the base Windows system.

### Steps to Reproduce

1. Enable Networking Tunnel
2. Enter `kubectl get no`

### Result

```console
kubectl get no
I0826 20:16:45.527249     764 versioner.go:58] Get "https://127.0.0.1:6443/version?timeout=5s": dial tcp 127.0.0.1:6443: connect: connection refused
E0826 20:16:45.846253     764 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E0826 20:16:45.846694     764 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E0826 20:16:45.848134     764 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E0826 20:16:45.849664     764 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E0826 20:16:45.851128     764 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
```

### Expected Behavior

`kubectl get no` should show available RD node.

### Additional Information

- I've tested both with and without a restart after enabling.

[protocol-handler.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446493/protocol-handler.log)
[rancher-desktop-guestagent.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446494/rancher-desktop-guestagent.log)
[server.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446495/server.log)
[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446488/k8s.log)
[kube.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446489/kube.log)
[moby.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446490/moby.log)
[networking.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446491/networking.log)
[network-setup.log](https://github.com/rancher-sandbox/rancher-desktop/files/12446492/network-setup.log)

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.72.2 / 1.72.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows LTSC

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

No VPN.

**Comment by Nino-K** [comment]
@worldofgeese unfortunately I am unable to repro this, are you able to do a factory reset and try again. Also, are you running  the `kubectl get nodes` from the host or another wsl distro?

**Comment by jandubois** [comment]
> Also, are you running the `kubectl get nodes` from the host or another wsl distro?

@Nino-K I can repro this when running `kubectl get no` from the Ubuntu distro. Isn't that the known issue that WSL integration is simply not yet implemented for the network tunnel?

**Comment by Nino-K** [comment]
> Isn't that the known issue that WSL integration is simply not yet implemented for the network tunnel?

This is why I'm asking for clarification since the issue is not explicitly mentioning that.

**Comment by jandubois** [comment]
> since the issue is not explicitly mentioning that

I understood `blocks access over WSL2` to mean that. Anyways, the reported error message is exactly what you get when you run the command from a WSL2 distro:

```
suse@rd-w11-test-1:~$ kubectl get no
I0828 13:29:11.069986   92594 versioner.go:58] invalid configuration: no configuration has been provided
E0828 13:29:11.381794   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0828 13:29:11.382163   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0828 13:29:11.384111   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0828 13:29:11.385746   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0828 13:29:11.387520   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by worldofgeese** [comment]
> > since the issue is not explicitly mentioning that
> 
> I understood `blocks access over WSL2` to mean that. Anyways, the reported error message is exactly what you get when you run the command from a WSL2 distro:
> 
> ```
> suse@rd-w11-test-1:~$ kubectl get no
> I0828 13:29:11.069986   92594 versioner.go:58] invalid configuration: no configuration has been provided
> E0828 13:29:11.381794   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
> E0828 13:29:11.382163   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
> E0828 13:29:11.384111   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
> E0828 13:29:11.385746   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
> E0828 13:29:11.387520   92594 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> ```

Indeed, that's what I meant. :-)

**Comment by Nino-K** [comment]
I have created https://github.com/rancher-sandbox/rancher-desktop/issues/5415 to tackle this in 1.11.
