### ISSUE TITLE
WSL intergration for the new namespaced network

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#5415]
As part of the new namespaced networking stack, we would like to allow other distros to access the kube API server currently hosted inside the namespace network. This can be achieved by adding a bridge component that allows network flow to the tap (eth0) device inside the namespace. Taking this approach also may require changes to the kube API address for kubectl. 

- [x] [Create a veth pair to enable the network connectivity between default and RD namespace](https://github.com/rancher-sandbox/rancher-desktop-networking/pull/14)
- [x] [Edit the host file to point to the correct IP address belonging to the RD namespace in wsl-integrated distros.](https://github.com/rancher-sandbox/rancher-desktop/pull/5722)
- [ ] https://github.com/rancher-sandbox/rancher-desktop/pull/5771
- [x] https://github.com/rancher-sandbox/rancher-desktop/pull/5835

**Comment by jandubois** [comment]
I believe this issue is done, so closing it to move to Verify.

@Nino-K please re-open if there are remaining tasks!
