### ISSUE TITLE
Sort extension catalog alphabetically by default

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5417]
Now that we have more than one screenful of extensions, they should appear in alphabetical order (ignoring case, accented characters, and leading non-alpha characters, should there be any in the future). This change works for me:
```
diff --git a/pkg/rancher-desktop/utils/_demo_marketplace_items.js b/pkg/rancher-desktop/utils/_demo_marketplace_items.js
index 9ec9396f2..4d2d9dc8c 100644
--- a/pkg/rancher-desktop/utils/_demo_marketplace_items.js
+++ b/pkg/rancher-desktop/utils/_demo_marketplace_items.js
@@ -317,3 +317,15 @@ export const demoMarketplace = {
     },
   ],
 };
+const collator = new Intl.Collator('en', { sensitivity: 'base' });
+
+demoMarketplace.summaries.sort((s1, s2) => {
+  const s1Publisher = s1.publisher.name;
+  const s2Publisher = s2.publisher.name;
+
+  if (s1Publisher.includes('SUSE') !== s2Publisher.includes('SUSE') ) {
+    return s1Publisher.includes('SUSE') ? -1 : 1;
+  }
+
+  return collator.compare(s1.name, s2.name);
+});
```

_Originally posted by @ericpromislow in https://github.com/rancher-sandbox/rancher-desktop/pull/5370#pullrequestreview-1601055538_

**Comment by IsaSih** [comment]
Reopening the issue, as I don't see the list of extensions sorted alphabetically in the catalog. Tested on Windows and MacOS, but this is not a blocker for 1.10 release.

**Comment by jandubois** [comment]
> there's a clause to place SUSE published extensions at the top

I've discussed this internally, and we agreed to remove any special handling of SUSE extensions; they should be sorted normally.
