### ISSUE TITLE
paths_linux.go: `AppHome` should be `filepath.Join(dataHome, appName)`

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5419]
### Actual Behavior

it's too confusing with `AppHome:  filepath.Join(configHome, appName),`

On macOS, we're correct putting `settings.json` in `~/Library/Preferences/rancher-desktop`

On linux, `credential-server.json` and `rd-engine.json` should go in `~/.local/share/rancher-desktop`

and the factory-reset should delete them from the old location (which will happen if `rdctl factory-reset` deletes all of `~/.config/rancher-desktop`

**Comment by jandubois** [comment]
Just to make sure we are in agreement:

1. `settings.json` will remain in `filepath.Join(configHome, appName)`
2. The other 2 files will move to `filepath.Join(dataHome, appName)`

Right?

**Comment by ericpromislow** [comment]
> Just to make sure we are in agreement:
> 
> settings.json will remain in filepath.Join(configHome, appName)
> The other 2 files will move to filepath.Join(dataHome, appName)
> Right?

Yes, exactly. The Windows files will be handled as part of issue #5378
