### ISSUE TITLE
Scroll bar does NOT expose the whole extension UI

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5427]
### Actual Behavior

By installing extension `vklokun/docker-desktop-extension` and accessing its UI, the scroll bar of the main window does not expose all extension's UI components. The main window needs to be resized to expose it all.

### Steps to Reproduce

1. Start Rancher Desktop
2. Install extension `vklokun/docker-desktop-extension`, named as Kubescape
3. Open the extension in the main window
4. Try to verify the UI components at the bottom of the window by scrolling the bar down

### Result

the scroll bar of the main window does not expose all extension's UI components. The main window needs to be resized to expose it all.

![kubescape-scroll-bar](https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/8c18d066-72ac-461f-90a8-09ee0e81bcc9)

### Expected Behavior

Scroll bar must expose all extension's UI components, regardless of the size of the main window.

### Rancher Desktop Version

1.9.1-623-g313754b3

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I suspect that this is the fault of the extension, and there is nothing Rancher Desktop can do about it. We provide the window area, but the HTML to display within is provided by the extension itself. You can see the non-scrolling footer inside the frame; that comes from the extension as well.

**Comment by IsaSih** [comment]
Should I close the issue then?

**Comment by jandubois** [comment]
> Should I close the issue then?

I think so, but would like to see confirmation from @rak-phillip that my understanding that this is an issue with the extension itself and outside our control is correct.

**Comment by rak-phillip** [comment]
I'm able to confirm that this is an issue that will need to be resolved by the extension authors and not something that Rancher Desktop can fix.
