### ISSUE TITLE
Extension UI is not rendering on Windows

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5429]
### Actual Behavior

Excalidraw is not rendering the UI on Windows

### Steps to Reproduce

1. Start Rancher Desktop with `containerd`
2. Install Excalidraw
3. Open the extension in the main window

### Result

Excalidraw is not rendering the UI on Windows
<img width="1118" alt="Screen Shot 2023-08-31 at 12 13 19 AM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/4c90643d-02ee-429f-8451-cf0d4d8badb6">

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12484029/logs.zip)

### Expected Behavior

The extension's UI must be displayed and fully functional

### Rancher Desktop Version

1.9.1-641-gde1efe0a

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by rak-phillip** [comment]
Difficult to say why, but I do see this the error in the chrome developer console when attempting to render the extension 

```
DevTools failed to load source map: Could not load content for x-rd-extension://6976616e6375726b6f7669633034362f657863616c69647261772d646f636b65722d657874656e73696f6e/ui/dashboard-tab/ui/preload.js.map: System error: net::ERR_FILE_NOT_FOUND
```

I don't think that this is related because I also see this error in Linux, where the extension renders without issue. At the moment, I don't think that the error is related.

**Comment by mook-as** [comment]
The `preload.js.map` thing is a red herring; it's trying to load the sourcemap for our preload script and failing. (But that's only used for the dev console; it doesn't affect functionality.)

**Comment by rak-phillip** [comment]
@mook-as sounds about right. What I think is more critical is that on Windows the extension directory for Excalidraw only contains `index.html` and nothing else. 

```
PS C:\Users\phillip\AppData\Local\rancher-desktop\extensions\aXZhbmN1cmtvdmljMDQ2L2V4Y2FsaWRyYXctZG9ja2VyLWV4dGVuc2lvbg\ui\dashboard-tab\ui> ls


    Directory: C:\Users\phillip\AppData\Local\rancher-desktop\extensions\aXZhbmN1cmtvdmljMDQ2L2V4Y2FsaWRyYXctZG9ja2VyLW
    V4dGVuc2lvbg\ui\dashboard-tab\ui


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          3/3/2023   2:30 AM            495 index.html
```

vs on Linux

```
-rw-r--r-- 1 phillip users 2.5K Mar  3 04:51 icon.svg
drwxr-xr-x 1 phillip users   26 Aug 31 13:26 ui/
drwxr-xr-x 1 phillip users    0 Aug 31 13:26 bin/
-rw-r--r-- 1 phillip users  210 Aug 31 14:29 metadata.json
-rw-r--r-- 1 phillip users  974 Aug 31 14:29 labels.json
drwxr-xr-x 1 phillip users  110 Aug 31 14:29 ./
drwxr-xr-x 1 phillip users  162 Aug 31 14:29 compose/
-rw-r--r-- 1 phillip users    5 Aug 31 14:29 version.txt
drwxr-xr-x 1 phillip users  476 Aug 31 14:29 ../
```

**Comment by rak-phillip** [comment]
I do recall encountering this before. The only other error that I've been able to generate comes from `window_browser.log`

```
2023-08-31T22:59:10.089Z: openExtension(6976616e6375726b6f7669633034362f657863616c69647261772d646f636b65722d657874656e73696f6e)
2023-08-31T22:59:28.763Z: Can't load the extension URL x-rd-extension://6976616e6375726b6f7669633034362f657863616c69647261772d646f636b65722d657874656e73696f6e/ui/dashboard-tab/ui/index.html:  Error: ERR_FAILED (-2) loading 'x-rd-extension://6976616e6375726b6f7669633034362f657863616c69647261772d646f636b65722d657874656e73696f6e/ui/dashboard-tab/ui/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:527:28) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'x-rd-extension://6976616e6375726b6f7669633034362f657863616c69647261772d646f636b65722d657874656e73696f6e/ui/dashboard-tab/ui/index.html'
}
```
