### ISSUE TITLE
Can't run bats on opensuse

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5444]
### Problem Description

Run any bats test, and I get this output:
```
./bats/bats-core/bin/bats bats/tests/containers/factory-reset.bats 
factory-reset.bats
 ✗ setup_file failed
   bats warning: Executed 1 instead of expected 35 tests

35 tests, 1 failure, 34 not run
```

bats needs some debugging utilities

**Comment by mook-as** [comment]
FWIW, I run the Windows tests on an OpenSUSE Leap WSL distribution, so it's not something intrinsic to OpenSUSE…

**Comment by ericpromislow** [comment]
@mook-as Are you saying you're seeing the same problem?

**Comment by mook-as** [comment]
No, I'm saying I _don't_ see the problem, even though I'm using OpenSUSE (but running the tests for Windows).

**Comment by ericpromislow** [comment]
Seems to be fixed by following these steps:

1.  getting a release-build bats-tested by installing it into /opt/rancher-desktop and including that directory on the path and then
2. installing `jq`

Then I'm able to run a test, and can then run `RD_LOCATION=dev bats bats/tests/...` 

No changes were needed.

**Comment by ericpromislow** [comment]
I'll wait for the changes on config-file locations to land, but a test failed trying to find `rd-engine.json`

**Comment by ericpromislow** [comment]
It's working well enough now. It's a very slow machine and I found I needed to put a `try --24 --delay 5` before calls to `kubectl run nginx` and `rdctl snapshot create`, but I think that's because I'm running the tests on an old, slow machine.
