### ISSUE TITLE
`Add Image` button is not disabled while Rancher Desktop is starting up

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5457]
When Rancher Desktop is starting up, the `Add Image` button on the `Images` tab is not disabled. You can click on it and try to pull images. I believe it should be disabled, since an image pull won't work until RD has finished starting up.

If it is relevant, this is on Fedora 38 GNOME, Rancher Desktop version `1.9.1-668-gafe9a483` (AppImage).

## Reproduction Steps

1. Launch Rancher Desktop and wait for it to start
2. Navigate to Images (the images button should render)
3. Open Preferences, change the Container Engine, and click Apply
4. The Add Image button will remain visible

## Additional Information

Navigating away from the Images page and back to it still renders the Add Image button.

![Screenshot from 2023-09-05 10-37-50](https://github.com/rancher-sandbox/rancher-desktop/assets/19395776/97db40ac-d9a9-4c63-92cd-70356c5cdb91)

![Screenshot from 2023-09-05 10-38-26](https://github.com/rancher-sandbox/rancher-desktop/assets/19395776/1b7e2914-420a-4170-9a53-825edb7d9d0d)

**Comment by rak-phillip** [comment]
I'm not able to reproduce this in a dev environment on both Linux & Windows could this be a artifact of the AppImage?

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/730d69df-db10-479c-8efb-37c300d88fed)

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/cedcd76c-febe-4c84-94f5-417eac4a3756)

**Comment by rak-phillip** [comment]
I see what the issue is. Added repro steps to the description. 

This isn't an issue when first starting Rancher Desktop, but a problem with changing preferences that require a restart.
