### ISSUE TITLE
Diagnostics is not warning about incorrect docker-compose symlink 

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5460]
### Actual Behavior

When `docker-buildx` and `docker-compose` symlinks point to incorrect locations, Diagnostics is issuing a warning just for `docker-buildx` and is NOT issuing the warning for `docker-compose`

### Steps to Reproduce

1. Shut down Rancher Desktop
2. Record what docker-buildx and docker-compose currently point to by running
3. ls -l ~/.docker/cli-plugins
4. cd ~/.docker/cli-plugins/
5. Relink docker-buildx to ~/.bashrc
6. ln -sf ~/.bashrc docker-buildx
7. Relink docker-compose to ~/.bashrc-doesnt-exist
8. ln -sf ~/.bashrc-doesnt-exist docker-compose
9. Launch Rancher Desktop
10. Check diagnostics warning in the diagnostic tab
11. After finishing the test, don't forget to correct the symlinks, pointing them back to ~/.rd/bin/docker-buildx and ~/.rd/bin/docker-compose.

### Result

Diagnostics is issuing a warning just for `docker-buildx` and is NOT issuing the warning for `docker-compose`
<img width="1147" alt="Screen Shot 2023-09-05 at 12 06 13 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/cf2759d5-e495-4a73-9c24-0d8efbdd0686">
[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12527495/Archive.zip)

### Expected Behavior

Diagnostics must display warning messages for BOTH `docker-buildx` and `docker-compose`

### Rancher Desktop Version

 1.9.1-668-gafe9a483

### Rancher Desktop K8s Version

1.27.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> Diagnostics is issuing a warning just for `docker-buildx` and is NOT issuing the warning for `docker-compose`

This is by design. You are creating a "dangling" symlink from `docker-compose` to a file that does not exist. We will simply overwrite the useless symlink with the updated target.

But we don't replace working symlinks. Which is why you get a warning for `docker-buildx`. You can verify by checking the directory:

```console
$ ls -l
total 0
lrwxr-xr-x  1 jan  staff  18  6 Sep 11:45 docker-buildx -> /Users/jan/.bashrc
lrwxr-xr-x  1 jan  staff  31  6 Sep 11:45 docker-compose -> /Users/jan/.bashrc-doesnt-exist

# Start Rancher Desktop and wait until it has initialized

$ ls -l
total 0
lrwxr-xr-x  1 jan  staff  18  6 Sep 11:45 docker-buildx -> /Users/jan/.bashrc
lrwxr-xr-x  1 jan  staff  33  6 Sep 11:46 docker-compose -> /Users/jan/.rd/bin/docker-compose
```
