### ISSUE TITLE
Test Case RD-163: Proxy on windows

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5464]
## Description

Configuring the proxy and running `rdctl shell curl reddit.com` appears to fail and the proxy does not receive traffic

```
curl: (56) Recv failure: Connection reset by peer
Error: exit status 56
```

## Before starting

Download [goproxy](https://github.com/Nino-K/goproxy/actions/runs/5205713898)

## Steps to reproduce

1. Run the proxy on the host machine:

```
.\goproxy.exe -v
```

2. Use `ipconfig` to determine your host IP address
3. Navigate to Preferences => WSL => Proxy
4. Click "Enable the proxy used by Rancher Desktop"
5. Enter your proxy address gathered in step 2 & set the port to 8080 (default for goproxy) and click apply
6. Open a new powershell window and run `rdctl shell curl reddit.com`

## Expected Result

You should see the following output from the upstream proxy (goproxy.exe)

```
[GOT A REQUEST]: &{Method:CONNECT URL://151.101.65.140:80 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:151.101.65.140:80 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:10.0.0.97:24024 RequestURI:151.101.65.140:80 TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc00005a190}

2023/06/08 10:27:58 [035] INFO: on 0th handler: &{0 <nil> 0x10ba980} 151.101.65.140:80

2023/06/08 10:27:58 [035] INFO: Accepting CONNECT to 151.101.65.140:80
```

## Actual Result

No output from `goproxy.exe`. `rdctl shell curl reddit.com` outputs the following:

```
curl: (56) Recv failure: Connection reset by peer
Error: exit status 56
```

**Comment by mook-as** [comment]
Note that you will need to allow `goproxy.exe` to receive traffic in Windows Firewall.

**Comment by rak-phillip** [comment]
I tried testing again to gather more information, but I'm unable to reproduce. I haven't changed anything in Windows Firewall. I've gone through a series of factory resets and installs in my test environment since then, so it's hard to say what the issue originally might have been. 

@Nino-K I think that I will close this issue since I'm the only one who encountered this issue and now even I can't repro.

**Comment by IsaSih** [comment]
I'll reopen the issue as I found the same error: 

```
rdctl shell curl reddit.com
curl: (56) Recv failure: Connection reset by peer
Error: exit status 56
```
I dont see any outputs in the proxy. Updating the logs:
