### ISSUE TITLE
`rdctl create-profile --output=reg` doesn't handle empty lists

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5466]
### Problem Description

When using `rdctl create-profile --output=reg`, `containerEngine.allowedImages.list` isn't written if that list is empty.

### Steps to reproduce:
1. Factory reset (or otherwise clear the allowed images list)
2. Run `rdctl create-profile --output=reg --from-settings`

### Expected results
The output should contain the allowed images list (currently empty), as that might be a thing that should be locked down (effectively, not allowing any images to be pulled).

### Actual Results
The output does _not_ contain the allowed images list.

### Proposed Solution

Always include it (as a `REG_MULTI_SZ`) even if it's empty.

### Additional Information

Rancher Desktop 1.10-RC1 (0dd5a2563f7bc2a8a4eb47f3d0d1b1703c188037), Windows.

**Comment by ericpromislow** [comment]
Should be same for when generating a macOS plist

**Comment by jandubois** [comment]
I've put this on the 1.10 milestone so we release-note it; the fix can wait for 1.11:

The workaround is to add at least one image to the list, which could be from a URL that doesn't represent a registry.

While I don't expect orgs to lock down an empty image list (they would have to build/load all images locally), this is a bigger issue for the allowed extensions list.

**Comment by ericpromislow** [comment]
I'm not sure we can do this using the standard go marshaler, because it produces a structure with empty arrays or dicts (for `diagnostics.mutedChecks`) whether the field is specified as an empty array or map, or it isn't specified at all.

Which means either supporting an `*EMPTY*` designation:
```
{... "mutedChecks": {"*EMPTY*":true} }
{.... noproxy: ["*EMPTY*"] }
{.... list: ["*EMPTY*"] }
{.... patterns: ["*EMPTY*"] }
```

or we write our own unmarshaler.

**Comment by jandubois** [comment]
> using the standard go marshaler, because it produces a structure with empty arrays or dicts

I don't quite understand. Isn't this controlled by the `omitempty` tag on the field? So you drop that tag on the lists where you want to generate an empty list, but keep it on the others?
