### ISSUE TITLE
No proxy list doesn't respond correctly to locked preferences

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5468]
### Actual Behavior

When the no proxy host name list is locked (via deployment policies), it's not correctly locked in the UI; it's still possible to modify the multi-line text area holding the list (but it's not possible to actually submit the changes).

![screenshot showing the locked no proxy list being edited](https://github.com/rancher-sandbox/rancher-desktop/assets/3977982/05b7351d-67ac-4bea-9bb0-52498fcd7579)

### Steps to Reproduce

1. Factory reset (this creates a default no-proxy list).
2. Start Rancher Desktop.
3. Run `rdctl create-profile --from-settings --output reg --type locked --hive hkcu | Out-File -Encoding utf8 .\settings.reg` to generate a deployment profile.
4. Double click the newly generated `settings.reg` and import it into the registry.
5. Start Rancher Desktop
6. Go to Preferences → WSL → Proxy
7. Try to edit the no proxy list.

### Result

It is possible to edit the list; there is no indication that the preference is locked.

### Expected Behavior

The list should be disabled (as in, the user should not be able to edit it).

### Additional Information

This will probably be obsoleted by #5344

### Rancher Desktop Version

1.10-RC1 (0dd5a2563f7bc2a8a4eb47f3d0d1b1703c188037)

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2134)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

None (fresh VM).

**Comment by s0nea** [comment]
Indeed. There is no way to lock the textarea. Would is be possible to fix it as part of https://github.com/rancher-sandbox/rancher-desktop/issues/5344 or will the fix be needed earlier?

**Comment by jandubois** [comment]
> Would is be possible to fix it as part of #5344 or will the fix be needed earlier?

It should be fixed as part of #5344. This is not a critical issue as validation still prevents you from applying the setting after you changed it from its locked value. This is not good UX, but does not violate the promise of the locked profile.
