### ISSUE TITLE
Deployment profiles E2E tests time out on Fedora 38 VM

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5471]
### Actual Behavior

As specified in manual tests, I am running
```
yarn test:e2e e2e/startup-profiles.e2e.spec.ts
```
These tests output an error about timing out.

I was able to get the tests to pass by increasing the timeout to 500 seconds. So it seems that this is all we need to do.

### Steps to Reproduce

Ensure no system deployment profiles are configured. Then:
```
yarn test:e2e e2e/startup-profiles.e2e.spec.ts
```

### Result

The tests fail with the following output:
```
Running 4 tests using 1 worker

  ✘  1 …p windows based on existing profiles and settings › verify profile/settings conditions and test skips or passes (5.0m)
Standard test 0: settings: deleted, user profile: deleted, system profile: deleted
waiting for main window, iter 100...
waiting for main window, iter 200...
waiting for main window, iter 300...
Skipping packaging logs, not running in Cirrus CI
Manually killing group processes 3378 3379 3381 6055 6223 6277 6278 6282 6283 6286 6287
Did not find processes in process group 3375, ignoring.
Test startup-profiles.e2e.spec.ts-0 took 1 min 43 sec.
Standard test 1: settings: deleted, user profile: deleted, system profile: existing
Skipping test where there's no system profile
Standard test 2: settings: deleted, user profile: existing, system profile: deleted
waiting for main window, iter 100...
waiting for main window, iter 200...
waiting for main window, iter 300...
Skipping packaging logs, not running in Cirrus CI
Manually killing group processes 6338 6339 6341 8825 8932 8967 8968 8971 8972 8975 8976
Did not find processes in process group 6335, ignoring.
Test startup-profiles.e2e.spec.ts-2 took 1 min 41 sec.
Standard test 3: settings: deleted, user profile: existing, system profile: existing
Skipping test where there's no system profile
Standard test 4: settings: existing, user profile: deleted, system profile: deleted
waiting for main window, iter 100...
waiting for main window, iter 200...
waiting for main window, iter 300...
Skipping packaging logs, not running in Cirrus CI
  -  2 …2:9 › track startup windows based on existing profiles and settings › problematic user profiles › nonexistent settings
  -  3 ….ts:136:9 › track startup windows based on existing profiles and settings › problematic user profiles › invalid format
  -  4 … track startup windows based on existing profiles and settings › problematic user profiles › wrong datatype in profile


  1) startup-profiles.e2e.spec.ts:79:7 › track startup windows based on existing profiles and settings › verify profile/settings conditions and test skips or passes 

    Test timeout of 300000ms exceeded.

  Slow test file: startup-profiles.e2e.spec.ts (5.0m)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    startup-profiles.e2e.spec.ts:79:7 › track startup windows based on existing profiles and settings › verify profile/settings conditions and test skips or passes 
  3 skipped
Rancher Desktop: main process exited with status 1
1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

The tests should pass.

### Rancher Desktop Version

80655a23

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Fedora 38

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by jandubois** [comment]
> I was able to get the tests to pass by increasing the timeout to 500 seconds.

@ericpromislow Does it make sense that this single test needs more than 5 minutes to run?

**Comment by ericpromislow** [comment]
Well, we are running on a VM with unknown CPU load, so I'd say maybe just increase the timeout when `process.env.CIRRUS_CI` is truish.

**Comment by jandubois** [comment]
> maybe just increase the timeout when `process.env.CIRRUS_CI` is truish.

I thought this was a problem on a local machine and not on Cirrus CI.

I'm just wondering if it makes sense to tweak individual timeouts like this, or if we should have a global setting like `E2E_TIMEOUT_FACTOR=2` (defaulting to `1`), which will be applied to all timeouts throughout the E2E tests.

**Comment by mook-as** [comment]
We have something like that:
https://github.com/rancher-sandbox/rancher-desktop/blob/d253355083b8f85069999012863e345efa6b61d2/e2e/config/playwright-config.ts#L7

**Comment by jandubois** [comment]
> We have something like that:

Oh, cool. So @adamkpickering could just have done an `export CI=1` and everything should have worked for him? Or do we still need code to adjust the various timeouts?

Maybe this should be mentioned in the docs somewhere?

**Comment by adamkpickering** [comment]
I experienced this in a Fedora 38 VM running on my local machine, so it would be weird to have to specify `CI=1` to get it to work. I would just increase the timeout. It shouldn't make the tests run slower on faster machines.

**Comment by jandubois** [comment]
> I would just increase the timeout.

I understood @mook-as's comment that setting `CI=1` would double all timeouts, which seems to be what you want. But maybe I misunderstand what it does; I haven't looked at the code.

**Comment by adamkpickering** [comment]
Setting `CI=1` would indeed double the timeout. But, I was trying to make the point that it would be confusing to ask people to do this when they aren't running the tests in a CI environment. Also in the future we might tie other behavior to the `CI` environment variable.

Basically, I think we should set the default timeout to a value that will work for all non-CI environments without having to set an environment variable.

**Comment by jandubois** [comment]
My point was that it should not be normal to have a 9min timeout on a test on a "normal" machine. It means the test needs to be broken down into smaller steps, where each step can have a more sensible timeout.

**Comment by adamkpickering** [comment]
IIRC all these tests are doing is modifying/checking deployment profiles and settings.json, and then starting RD and waiting for it to finish starting up. I don't think there is anything that can be done to simplify them.

But that brings to mind another thing: it still seems to take a while for the RD window to appear when started from the AppImage. In my 1.10.0 RC1 testing I'd say it was taking around 30s, but in the past it has taken much longer. [This issue](https://github.com/rancher-sandbox/rancher-desktop/issues/4896) is relevant. Perhaps this is something we could address.
