### ISSUE TITLE
RD 1.10: VirusTotal results

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5475]
### Actual Behavior

There appears to a few false positives in VirusTotal that we will need to handle.  At least none of them this round appear to be the major players?

### Steps to Reproduce

Upload parts of the installer to VirusTotal.  This was originally done with 1.10-RC1 (0dd5a2563f7bc2a8a4eb47f3d0d1b1703c188037).

For a more complete check, I built a special build (in CI) where we deliberately didn't package the WSL distro, and instead uploaded that separately (so that each part is less than the 650MB maximum).

### Result

Uploading files individually finds:
- rdctl.exe was [flagged](https://www.virustotal.com/gui/file/117c9900125a8591ebdffcbd275b7edba711d87496b7ef690c22a27c452f56da) by two vendors:
  - DeepInstinct
  - Jiangmin
- kuberlr.exe was [flagged](https://www.virustotal.com/gui/file/f6057c6ef0e43b70c4d4e58795d7fa15aa50f25f930df1e9d8c18e06b9d52389) by two vendors:
  - Bkav Pro
  - MaxSecure

Building a special installer without the distro tar (so that it fits within VirusTotal's maximum size) finds:
- `distro-0.46.tar`: [`fb81acddfa65`](https://www.virustotal.com/gui/file/fb81acddfa65fa713dd624005a8018322480d65d412b0817f5e87e084d27885a)
  - No hits
  - Microsoft timed out
- Installer `.msi`: [`cd3e4107df5f`](https://www.virustotal.com/gui/file/cd3e4107df5fe5cc3746731ca3b18d4d9cf21058c8adcd23331ce34e898dabc4)
  - One hit from Google (‽) with no data
  - About a dozen vendors just timed out on this one, including some major vendors:
    - Microsoft
    - Kaspersky
    - McAfee
    - BitDefender

### Expected Behavior

There should be no hits on  VirusTotal.

### Rancher Desktop Version

1.10-RC1 (0dd5a2563f7bc2a8a4eb47f3d0d1b1703c188037)

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2134)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

N/A (No installation was used)

**Comment by gunamata** [comment]
VirusTotal scan results for the release bits:

- wsl-helper.exe [flagged](https://www.virustotal.com/gui/file/cb1b1104d26219f097c0110f53386ea961fc9920ec58e009b92a37ba89f3e20f?nocache=1) by 3 vendors
  - MaxSecure
  - Cynet
  - Bkav Pro

- bin\docker-credential-ecr-login.exe [flagged ](https://www.virustotal.com/gui/file/60dd759f6c333ac12b5447470a4e26553d39c9288765771e5e264daa135f46b2)by 3 vendors
  - MaxSecure
  - SecureAge
  - Bkav Pro

- bin\docker-credential-none.exe [flagged ](https://www.virustotal.com/gui/file/0ad1c1756c4c9d377ba52770837d25ada9f05bc51b15799bf30e4847a2898ed0?nocache=1) by 5 vendors
  - MaxSecure
  - SecureAge
  - Bkav Pro
  - McAfee-GW-Edition
  - Cynet

- bin\kubectl.exe [flagged](https://www.virustotal.com/gui/file/f6057c6ef0e43b70c4d4e58795d7fa15aa50f25f930df1e9d8c18e06b9d52389) by 2 vendors
  - MaxSecure
  - Bkav Pro

- bin\kuberlr.exe [flagged](https://www.virustotal.com/gui/file/f6057c6ef0e43b70c4d4e58795d7fa15aa50f25f930df1e9d8c18e06b9d52389) by 2 vendors
  - MaxSecure
  - Bkav Pro

- bin\nerdctl.exe [flagged](https://www.virustotal.com/gui/file/e4250f853a71dc39215b633d3e143dd4cc93fd243b2225b0ca8ef63a4f67d8e2?nocache=1) by 6 vendors
  - MaxSecure
  - Bkav Pro
  - Cynet
  - DeepInstinct
  - SecureAge
  - McAfee-GW-Edition

- bin\rdctl.exe [flagged ](https://www.virustotal.com/gui/file/564211321bde680429bde6e105aa4b03fcfceb99c513489af32bbcc9db089db4/detection) by 3 vendors
  - MaxSecure
  - SecureAge
  - Bkav Pro

- internal\host-switch.exe [flagged](https://www.virustotal.com/gui/file/54c4b3e027f3c31cce70896006bc605192b8add15dbc16e940b40d89960b526a) by 3 vendors
  - MaxSecure
  - McAfee-GW-Edition
  - Bkav Pro


- internal\vtunnel.exe [flagged ](https://www.virustotal.com/gui/file/6bc295544e5b6a42e3622c8bb35565a0120ac2f5b4bd142170032dd6b9c8d29b?nocache=1) by 4 vendors
  - MaxSecure
  - McAfee-GW-Edition
  - Bkav Pro
  - SecureAge

**Comment by gunamata** [comment]
Filed a False positive & Allowlisting report at https://www.mcafee.com/en-us/consumer-support/dispute-detection-allowlisting.html.

**Comment by jonathanklingberg** [comment]
Similar finding reported from VirusTotal on the Rancher.Desktop.Setup.1.12.3.msi, see:
https://www.virustotal.com/gui/file/5d91da8fb15e121a6fbbd286946d20dd839c47d61d53a5b158d5e513ff7bd49c/detection
Should this be filed as a separate issue?

**Comment by mook-as** [comment]
Hi! Yes, we generally use new issues for each release, because the behaviour-based scanners will keep finding random things (because they're guesses).
