### ISSUE TITLE
Add API endpoint that allows for starting/stopping the VM

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5476]
For `rdctl` to create/restore a snapshot, it first needs to ensure the main RD VM is stopped. Once the snapshot is created/restored, it needs to be able to restart the VM. It will do this through the use of a new endpoint on the main process's API.

**Comment by jandubois** [comment]
> it needs to be able to restart the VM. It will do this through the use of a new endpoint on the main process's API.

It should only do that is the app is already running. You should be able to create / restore a snapshot with `rdctl` without spinning up the app at all.
