### ISSUE TITLE
Rancher desktop doesn't start properly

### ISSUE THREAD

**Issue by user799595** [rancher-sandbox/rancher-desktop#5482]
### Actual Behavior

Rancher desktop can't start Lima. It says "Kubernetes error" on startup (even though I have Kubernetes disabled).

Last command run:
```
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false 0
```

### Steps to Reproduce

It just fails on startup. Rebooting can help.

### Result

```
2023-09-07T11:01:33.161Z: > limactl start --tty=false 0
$ c [Error]: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:15549)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
    'start',
    '--tty=false',
    '0'
  ],
  stdout: '',
  stderr: 'time="2023-09-07T13:01:33+02:00" level=info msg="Using the existing instance \\"0\\""\n' +
    'time="2023-09-07T13:01:33+02:00" level=fatal msg="errors inspecting instance: [failed to get Info from \\"/Users/myname/Library/Application Support/rancher-desktop/lima/0/ha.sock\\": Get \\"http://lima-hostagent/v1/info\\": dial unix /Users/myname/Library/Application Support/rancher-desktop/lima/0/ha.sock: connect: connection refused]"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false 0'
}
```

### Expected Behavior

Lima starts

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

13.5

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

Homebrew

**Comment by rumstead** [comment]
https://github.com/rancher-sandbox/rancher-desktop/issues/3137 maybe?

**Comment by mkarpicki** [comment]
Same... 
Factory reset fixed this issue (observe for how long)

**Comment by mkarpicki** [comment]
... after couple of laptop restarts, problem came back and seems that 'Factory Reset' works as short term solution (each time for some time)

**Comment by user799595** [comment]
Yeah, I've actually had the same experience, I closed the issue too early. Thankfully, the frequency of having to do this has become lower and I have a script somewhere to reset my config when it happens.
