### ISSUE TITLE
User experience for frontend form validation

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5485]
We've initiated experiments to identify an appropriate validation library to enhance frontend form validations (#5438 and rancher/dashboard#8605). This issue is focused on improving the user experience related to relaying frontend validation messages in Rancher Desktop.

## Objectives

- Evaluate the current validation patterns used throughout Rancher Desktop
- Identify fields and form sections where frontend validation can enhance the user experience
- Explore opportunities to refine our validation message patterns

## Fields for Frontend Validation

Rancher Desktop might benefit from frontend validation messages in the following areas:

### Main Window

- Port Forwarding
  - Evaluate input validation for port numbers
- Images
   - Add Image
      - Check for valid input in build tab
      - Check for valid input in pull tab 

### Preferences

- Virtual Machine 
   - Hardware
     - Validate inputs for memory and CPU settings
   - Mount Type => 9p
      - Validate memory size in KiB
- WSL (Windows)
   - Proxy
      - Validate proxy address and port inputs 
      - Validate the format of the "No proxy hostname list"
- Container Engine
   - Allowed Images
      - Validation for allowed image patterns
- Kubernetes
   - Validate Kubernetes Port

**Comment by jandubois** [comment]
Should this also be covered by validation:

* cannot use virtiofs unless you are using VZ emulation

I think we have at least one other scenario like this, but I cannot remember right now.
