### ISSUE TITLE
(re)Define accent colour 

### ISSUE THREAD

**Issue by manuelecarlini** [rancher-sandbox/rancher-desktop#5487]
### Problem Description

With the implementation of the new menu and the UI color rework, we need to define a new accent color that would define navigation and other meaning inside the Rancher systemmeanings

### Proposed Solution

A first round of proposals has been created, but we need to rethink the outcome to be more in line with the brand guideline and the feedback received 

### Additional Information

The first proposal
https://xd.adobe.com/view/2fb816d0-fcd3-4e8c-814d-807ed1c9882b-7aeb/

**Comment by gaktive** [comment]
Putting on hold for now.
