### ISSUE TITLE
Define secondary button style

### ISSUE THREAD

**Issue by manuelecarlini** [rancher-sandbox/rancher-desktop#5488]
### Problem Description

With the color rework of the user interface we need to rethink the secondary button style, including color, size, contrast and more

### Proposed Solution

There are already a couple of rounds of proposals to start from, but it all depends by the overall look and feel we want to give to the UI and how this button would match the rest of the interface

### Additional Information

The first proposal
https://xd.adobe.com/view/2fb816d0-fcd3-4e8c-814d-807ed1c9882b-7aeb/

**Comment by gaktive** [comment]
Putting on hold for now.
