### ISSUE TITLE
Nothing happens with the `anchore` extension on windows 10

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5490]
I can install it when running moby, but just see a never-ending beachball-type icon. Works fine on linux and macOS

**Comment by rak-phillip** [comment]
Just gave a quick test in Windows 10 and the Anchore extension renders initial content without issue. Are to able to replicate while attaching the Chrome remote debugger to see if there's any pertinent information that gets printed to the console?

https://github.com/rancher-sandbox/rancher-desktop#remote-debugging-an-extension

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/8d5290c0-4c89-41b5-a90f-522e23f1bcee)

**Comment by ericpromislow** [comment]
And now I can run this extension no problem on the slow windows laptop
