### ISSUE TITLE
Notification icon is not hidden when `application.hideNotificationIcon` is set to `true` via `rdctl`

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5493]
### Actual Behavior

The notification icon is not hidden when `application.hideNotificationIcon` is set to `true` via `rdctl`.

### Steps to Reproduce

1. Factory reset
2. Start rancher desktop
3. Run `rdctl set --application.hide-notification-icon=true`

### Result

The notification icon is not hidden. When it is clicked on, a box appears but it is blank.

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/19395776/7e3a2695-331b-4e71-b267-d6cfb740f588)

### Expected Behavior

Once `rdctl set --application.hide-notification-icon=true` has run, the notification icon should be hidden.

### Additional Information

It appears that it is possible to get two RD notification icons if after doing the steps described above, you open the RD window, go to preferences, and uncheck Application > Behavior > Hide Notification Icon. See screenshot.

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/19395776/63212c67-aa7d-4570-bb52-e2a03ad882fa)

### Rancher Desktop Version

1.9.1-699-gb84729ab

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment]
Isn't this a [known issue](https://docs.rancherdesktop.io/ui/preferences/application/behavior/#known-issues-and-limitations-2):

>For Ubuntu operating systems and specifically versions >= 20.04.5 LTS, there is a known issue with hiding the tray icon in the preferences settings. Please see this [issue comment](https://github.com/rancher-sandbox/rancher-desktop/issues/4205#issuecomment-1533750167) for further information.

**Comment by adamkpickering** [comment]
:+1: thanks, right you are.
