### ISSUE TITLE
Kubernetes 1.18.20 does not work

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5509]
### Actual Behavior

Rancher Desktop fails to start after downgrading Kubernetes: fails to connect to the node

### Steps to Reproduce

1. Start Rancher Desktop with kubernetes version 1.27.5
3. Pull an image:  `docker pull nginx:stable`
4. Downgrade Kubernetes from 1.27.5 to 1.18.20

### Result

Fatal error: 

```
Error starting lima: Error: connect ECONNREFUSED 127.0.0.1:6443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6443
}
```

Logs:

From `kube.log`:

`Configuration /etc/rancher/k3s/k3s.yaml not present in lima vm; will check again...`

From `background.log`:
```
failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache/index0/size: no such file or directory
I0912 17:56:14.114378    3913 log.go:172] http: TLS handshake error from 127.0.0.1:36556: remote error: tls: bad certificate

```
From `k8s.log`:
```
2023-09-12T02:23:03.116Z: Waiting for K3s server to be ready on port 6443...
2023-09-12T02:23:03.117Z: Error: connect ECONNREFUSED 127.0.0.1:6443
2023-09-12T02:23:10.656Z: Updating kubeconfig /Users/iguimaraes/.kube/config...
2023-09-12T02:23:14.629Z: Error priming kuberlr: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 1

2023-09-12T02:23:14.630Z: Output from kuberlr:
ex.stdout: [
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
],
ex.stderr: [I0911 19:23:11.077525   44595 versioner.go:58] Get "https://127.0.0.1:6443/version?timeout=5s": EOF
error: Get "https://127.0.0.1:6443/api/v1/namespaces/kube-system/services?labelSelector=kubernetes.io%2Fcluster-service%3Dtrue": dial tcp 127.0.0.1:6443: connect: connection refused - error from a previous attempt: read tcp 127.0.0.1:59514->127.0.0.1:6443: read: connection reset by peer
]
2023-09-12T02:23:14.632Z: Failed to match a kuberlr network access issue.

```
All logs:
[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12589502/Archive.zip)
[lima-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12589508/lima-logs.zip)

### Expected Behavior

Kubernetes must restart with no errors by downgrading kubernetes.

### Rancher Desktop Version

 1.9.1-699-gb84729ab

### Rancher Desktop K8s Version

1.18.20

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by IsaSih** [comment]
BATS test pass with the defaults version of the test which is 1.22.7, and fails with 1.18.20, so this is an issue most likely specific to version 1.18.20.

**Comment by jandubois** [comment]
This doesn't seem to have anything to do with downgrading; I can do a factory reset, and then select 1.18.20 as the k8s version in the first-run dialog, and I get the error too.

It is also not a regression; I get the same error with 1.9.1.

So it looks like we somehow lost compatibility with old k8s versions. We need to either restore compatibility, or limit the selection to versions actually compatible.

**Comment by IsaSih** [comment]
This version works as expected on windows 11.

**Comment by gunamata** [comment]
I couldn't reproduce the issue described in the issue description, so, I could successfully pull the `nginx:stable` image and then downgrade kubernetes from 1.27.5 to 1.18.20 with out issues.

**Comment by IsaSih** [comment]
The error I see by starting up the application is different from downgrading. 
Fatal error:
```
Error starting lima: Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
} 
```

Logs: 
[Archive.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12591401/Archive.zip)
[lima-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12591410/lima-logs.zip)

**Comment by ericpromislow** [comment]
This problem is generalized in issue #5625

**Comment by jandubois** [comment]
We are dropping support for k8s versions below 1.21.0 in the 1.15 release, so this is no longer a concern.
