### ISSUE TITLE
`host-switch` is not signed

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5511]
### Actual Behavior

The `host-switch.exe` file in the 1.10 release was not signed.

```
Get-AuthenticodeSignature .\resources\resources\win32\internal\host-switch.exe


    Directory: C:\Program Files\Rancher Desktop\resources\resources\win32\internal


SignerCertificate Status    Path
----------------- ------    ----
                  NotSigned host-switch.exe
```

### Steps to Reproduce

1. Install [Rancher Desktop 1.10](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.10.0) on Windows
2. Check the signatures of the shipped files.

### Result

`host-switch.exe` is not signed.  The other files we build are. (There's a bunch in Electron that we don't sign.)

### Expected Behavior

All files we build are signed.

### Additional Information

We have a whitelist:
https://github.com/rancher-sandbox/rancher-desktop/blob/1ae2cdf2773831fd638728be5a756cf215d62f94/scripts/lib/sign-win32.ts#L68

### Rancher Desktop Version

1.10

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2134)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I wonder if we could create a tool for the final smoke testing of signed bits that could check for this automatically?

**Comment by ericpromislow** [comment]
I've added the following step to the Windows build signing process:
- verify all the executables in CPF/Rancher Desktop/resources/resources/win32/internal are signed: 
```
 Get-AuthenticodeSignature *.exe 
```

All the other parts of the signing process are done manually right now, so I don't have a procedure to tack this on to.
