### ISSUE TITLE
MSI Fails on windows 10 Enterprise (version 22H2) (os build 19045.3324)

### ISSUE THREAD

**Issue by georgehoffman** [rancher-sandbox/rancher-desktop#5521]
### Actual Behavior

I am trying to install on windows 10 enterprise using the MSI on my work laptop. I do have admin rights on the machine but my company does like to throw a bunch of other random security on there. Ive tried running the msi directly and from command line with admin privileges. Ive tried 1.10.0 and 1.9.1 versions of the msi with similar results. I can install on my home computer without issue. I do suspect it is an issue with some security policies on the work laptop but have no idea what to look for. 

I turned on msi debugging and will try to attach the log file but its 3mb. **_suspect lines in the log file include:_**
MSI (c) (BC:78) [10:53:01:760]: Error setting paths ProgramFilesFolder: 1: 2727 2: ProgramFilesFolder 
MSI (c) (BC:78) [10:53:01:760]: Error setting paths CommonFilesFolder: 1: 2727 2: CommonFilesFolder 
MSI (s) (C8:34) [10:53:01:813]: The call to SRSetRestorePoint API failed. Returned status: 1260. GetLastError() returned: 1260
WixQuietExec64:      + CategoryInfo          : SecurityError: (:) , ParentContainsErrorRecordException
WixQuietExec64:      + FullyQualifiedErrorId : UnauthorizedAccess
WixQuietExec64:  Error 0x80070001: Command line returned an error.
WixQuietExec64:  Error 0x80070001: QuietExec64 Failed
WixQuietExec64:  Error 0x80070001: Failed in ExecCommon method
CustomAction InstallWSL returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (c) (BC:F8) [10:53:31:234]: Windows Installer installed the product. Product Name: Rancher Desktop. Product Version: 1.10.0. Product Language: 1033. Manufacturer: SUSE. Installation success or error status: 1603.

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/119448656/e5780952-ba46-4325-b954-aabedd5923ee)

### Steps to Reproduce

just run the installer but you have to be on my laptop ;) Wish I could tell you how to reproduce it but to know that I would probably have to know the cause and hence I would know the fix.

### Result

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/119448656/00b89df3-8a11-4cf4-ab7d-d60007d68c78)

### Expected Behavior

it should be installed and I can run the application

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

N/A - not sure till it installs correctly

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

version 22H2 / os build 19045.3324

### What CPU architecture are you using?

x64
[MSIbd27d.LOG](https://github.com/rancher-sandbox/rancher-desktop/files/12599991/MSIbd27d.LOG)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Im installing without being on VPN. Im guessing my company has custom firewall/security/AD features but I have little visibility into what they might be.

**Comment by georgehoffman** [comment]
The MSI installs directly to "C:/Program Files" which is notorious for installation issues because A it has spaces in it and B its a protected windows folder. Would love to try installing it in a separate directory if anyone knows how to change it with the MSI.  Not sure if its the culprit but would like to rule it out somehow.

**Comment by mook-as** [comment]
You may be able to install WSL separately (`wsl --install --inbox --no-distribution` from an elevated command prompt), and then (after a reboot) try installing the Rancher Desktop msi again.  If WSL is installed already, you will have the option to install for the current user (in `C:\Users\<>\AppData\Local\Programs\…`) instead.

Note that (for now, until we fix the installer) you'll need the `--inbox` version to be detected.

**Comment by georgehoffman** [comment]
I could hug you! I had to fully uninstall WSL first and then reinstall it but finally was able to install rancher desktop. THANKYOUTHANKYOUTHANKYOU!
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/119448656/d75faef4-870d-4d33-b463-9b6b37fc9e38)
