### ISSUE TITLE
Incompatible mount type and VZ emulation can be set via rdctl

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5542]
### Actual Behavior

Server api cannot prevent user from setting VZ emulation with an incompatible mount type, resulting in Rancher Desktop restarting in an error state.

### Steps to Reproduce

1. Start Rancher Desktop
2. Set mount type to `9p` via `rdctl set --experimental.virtual-machine.mount.type 9p`
3. Set emulation mode to `VZ` via `rdctl set --experimental.virtual-machine.type vz`

Also, the following happens:
1. Start Rancher Desktop
2. Set emulation mode to `VZ` via `rdctl set --experimental.virtual-machine.type vz`
3. Set mount type to `virtiofs` via `rdctl set --experimental.virtual-machine.mount.type virtiofs`
4. Set emulation mode to `QEMU` via `rdctl set --experimental.virtual-machine.type qemu`

### Result

Server does not throw an error when setting incompatible settings, resulting in the application restarting in an error state.

### Expected Behavior

Rancher Desktop must prevent user from setting incompatible settings. (Mount type/emulation and vice versa)

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.5.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by ericpromislow** [comment]
Looks like a dup of #5478  - please reopen if it isn't.

**Comment by IsaSih** [comment]
No, this seems like a different issue, as these are not windows specific settings

**Comment by ericpromislow** [comment]
Yes, you're right -- the other issue deals with failing to stop setting windows-specific settings on other platforms.

**Comment by ericpromislow** [comment]
Actually, it's being handled in issue #5473

**Comment by ericpromislow** [comment]
Actually, it's a standalone error.
