### ISSUE TITLE
Local ~/Library locked profile not being utilized

### ISSUE THREAD

**Issue by pshutt97** [rancher-sandbox/rancher-desktop#5545]
### Actual Behavior

When a locked profile is created within the ~/Library directory and Rancher Desktop is started, the profile is not used and none of the settings are locked down.

### Steps to Reproduce

Install Rancher Desktop 1.10, create locked profile within the ~/Library directory, launch Rancher Desktop.

### Result

 You will find that the fields that should be locked are not. If you take this same locked profile and place it in the /Library directory, Rancher Desktop locks down the fields.

### Expected Behavior

It is expected that Rancher Desktop honor both locations as per their documentation and that the /Library take precedence over ~/Library as well.

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS Ventura 13.5.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

N/A

**Comment by jandubois** [comment]
I cannot reproduce the problem:

```console
$ rdctl create-profile --from-settings --output plist > ~/Library/Preferences/io.rancherdesktop.profile.locked.plist

$ rdctl api settings | jq -r .containerEngine.name
moby

$ rdctl shutdown
Shutting down.

$ rdctl start
INFO[0000] About to launch /usr/bin/open -a /Applications/Rancher Desktop.app ...

$ rdctl set --container-engine.name containerd
Error: errors in attempt to update settings:
field "containerEngine.name" is locked
```

The only explanations I can come up with are:

1. You misspelled the user profile setting filename
2. Your locked profile is in the wrong format (e.g. JSON instead of PLIST)
3. You still have a system level default or locked profile

Rancher Desktop never mixes profiles; if there is a system profile (either default, or locked, or both), then any user profile is going to be ignored.

**Comment by pshutt97** [comment]
@jandubois That is correct. I was simply using the existing .plist file that was working before on 1.9.1. When I updated Rancher, this locked profile no longer works when in my ~/Library directory (with no locked profile set in /Library) and vice versa. I am aware of the order it takes it in, all I am saying is that with just the locked profile within the ~/Locked directory, nothing is locked down. I didn't use the rdctl to recreate the plist since the settings are still the same and have not moved from 1.9.1 when compared with those outputted when running rdctl list-settings.

**Comment by jandubois** [comment]
> this locked profile no longer works when in my ~/Library directory (with no locked profile set in /Library) 

Note that having just a default profile under `/Library` is enough for Rancher Desktop to ignore both default and locked profiles under `~/Library`.

**Comment by pshutt97** [comment]
Reinstalled and error is no longer appearing
