### ISSUE TITLE
Kubernetes version shows duplicate "latest" and "stable" versions

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5566]
k8s is disabled and the version dropdown looks empty (you cannot expand it, which makes sense, since it is disabled).

I enable k8s and look at the dropdown. It shows 2 "latest" and 1 "stable" version:

<img width="183" alt="CleanShot 2023-09-21 at 17 43 01@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/ad171eef-04a4-46b9-ab0a-3169c90d5194">

I discard the settings changes and restart the app. I now have just one "latest" but 2 "stable" versions:

<img width="185" alt="CleanShot 2023-09-21 at 17 46 05@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/912f1d34-833a-4909-baec-d95872ce9dfc">

Restarting once more finally fixes it:

<img width="207" alt="CleanShot 2023-09-21 at 17 48 11@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/d3eab366-6d98-4212-a334-fc0f93bda9fa">

It looks like the code that merged the cached list with the latest update from the feed is not correctly handling the labels. There should be a unit test for the merge logic.

**Comment by jandubois** [comment]
Probably unrelated, but I'm also wondering why I'm getting a checkmark in front of "Recommended Versions". In a screenshot from @jsoref there isn't one:

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/78947/5ff7c0d0-8e80-4b94-8daf-685338e0b850)

What is the significance of that checkmark?

**Comment by jsoref** [comment]
Here's my current screenshot:
<img width="327" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/2119212/0fc700ba-15ea-4c21-968e-992566a183d6">

From memory, I had a check on a 1.24.x or something, probably because I had previously enabled kubernetes and selected that version.

But, under no circumstances does it make sense to have a ✔️ next to a disabled heading.
