### ISSUE TITLE
Add `--json` flag to `rdctl snapshot list`

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5569]
For the UI, it is important to be able to get a list of snapshots and their details so that this information can be displayed in the UI. Currently, `rdctl snapshot list` only displays this information as a table. This is difficult to parse. In order to make the UI easier to develop, we should introduce a `--json` flag that causes `rdctl snapshot list` to print the snapshots to stdout as a JSON array.

**Comment by adamkpickering** [comment]
Attention @torchiaf

**Comment by torchiaf** [comment]
> Attention @torchiaf

Thanks @adamkpickering , ATM the commands output are parsed using regex https://github.com/rancher-sandbox/rancher-desktop/blob/d561f3e9a7d1246885d632479bf611310ecce57a/pkg/rancher-desktop/main/snapshots/snapshots.ts
