### ISSUE TITLE
Add Epinio to Rancher Desktop test plan

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#558]
We need to make sure that Epinio and Rancher Desktop work well together.

See also: https://github.com/epinio/epinio/issues/740

**Comment by evertonlperes** [comment]
We already have Epinio integration test plan (Confluence) and also a plan to automate the test: https://github.com/rancher-sandbox/rancher-desktop/issues/885
Closing this for now.
