### ISSUE TITLE
Add `Notes` or equivalent field  ("Description"?) to `Snapshot` object

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5580]
We want a field in snapshot metadata that allows a user to enter text that describes the snapshot. I'm not sure that `Notes` is the name we want for this field - `Description` is another name that comes to mind.

**Comment by jandubois** [comment]
> I'm not sure that `Notes` is the name we want for this field - `Description` is another name that comes to mind.

I think either name is fine. If this is a cli option, I prefer `--note` over `--description` because it is shorter. 😄
