### ISSUE TITLE
Snapshots e2e tests

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/rancher-desktop#5594]
According to the acceptance criteria listed in https://github.com/rancher-sandbox/rancher-desktop/issues/4236 , here is the list of scenarios that needs to be included in our e2e tests:

1. Snapshots must not be deleted on factory reset triggered via UI.
2. Progress bar in the UI must show the download progress of the snapshot being saved/restored
3. UI must show an Error message if it fails to create/restore snapshots and message of success when they’re successfully saved/restored
4. When taking a snapshot via UI, user cannot take a snapshot at the same time via CLI and vice-versa
5. UI components must be locked while a snapshot operation is in progress
6. If a snapshot is created/restored when app is not running, when starting the application, UI must be locked and needs to inform that the snapshot operation is in progress and the VM is still to start.
7. UI must show a list of saved snapshots displaying its name and date with 2 action buttons to restore and delete
8. Once a snapshot operation starts, the preferences dialog must be closed
9. By deleting a snapshot, the UI must remove it from the list of snapshots and `rdctl snapshot list` must not show the deleted snapshot anymore
10. By hitting "Create Snapshot", adding a name and description to the snapshot, hitting the cancel button must cancel the operation and the snapshot must not be created
11. If trying to create a snapshot with a name that already exists, UI must throw a warning message that the name already exists and must not save snapshots with duplicate names

Maybe: (not sure if tray menu testing can be automated)
1. Tray menu options must be disabled while snapshot is in progress

**Comment by jandubois** [comment]
Sync with @IsaSih to see which of the manual release tests could be implemented as E2E tasks.
