### ISSUE TITLE
Understand failures when downgrading to/running older k8s versions

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5625]
Replaces issue #5509 

PR #5548 is a band-aid solution that doesn't understand the underlying cause of intermittent k3s server outages
(which might not be the only reason why running on older versions sometimes fails, usually requiring a restart).

**Comment by jandubois** [comment]
> Replaces issue #5509

I'm not sure why we needed to replace that issue, which already includes comments with a new issue without further information.

I've restored #5509 (but removed the milestone) and will close this one instead.
