### ISSUE TITLE
nerdctl support

### ISSUE THREAD

**Issue by abiosoft** [rancher-sandbox/rancher-desktop#563]
Hi, thanks for this awesome project.

I would like to know if would be possible to have nerdctl support for the bundled containerd?

I was able to get nerdctl to communicate with containerd socket with `$CONTAINERD_ADDRESS` but could not get the appropriate value for the `$CNI_PATH`.

Thanks.

**Comment by jandubois** [comment]
I don't know, but I would expect it to work, although it is outside the scope of what Rancher Desktop tries to provide.

What did you try, and how did it fail?

I assume this works:
```
nerdctl --address /run/k3s/containerd/containerd.sock --namespace k8s.io ps
```

You will need to download and install CNI plugins yourself from https://github.com/containernetworking/plugins/releases

**Comment by abiosoft** [comment]
Thanks @jandubois, I have been able to get it to work by downloading the CNI plugins and specifying the plugin directory with the `--cni-path` or `$CNI_PATH` env var.

If you are wondering why I want this, I sometimes need a docker-compose workflow and nerdctl provides that.
