### ISSUE TITLE
`rdctl snapshot` stops the VM even when the command can't be applied

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/rancher-desktop#5643]
### Actual Behavior

`rdctl snapshot` stops&starts the VM even when a snapshot already exists (`create`) or snapshot doesn't exist (`restore`).

### Expected Behavior

We should check whether `snapshot` commands are applicable before handling the VM by checking the snapshots list.

**Comment by adamkpickering** [comment]
The `rdctl snapshot create` part of this was done in #5781.

**Comment by gaktive** [comment]
@jandubois to verify that this is solved already and close if so.

**Comment by jandubois** [comment]
Seems to work as expected by now:

```console
$ rdctl snapshot create foooo
Error: failed to create snapshot: name "foooo" already exists
$ rdctl snapshot restore yo
Error: failed to restore snapshot "yo": can't find snapshot "yo"
```
