### ISSUE TITLE
`yarn install` fails when running Python 3.12 (or later)

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5655]
### Problem Description

The `distutils` module is no longer supported with python 3.12, but it's needed to build the `ffi-api` binary module.

It's possible to install it by running `pypi install setuptools`, so that might need to be done as part of running the
installer, or to make it a prerequisite.

### Proposed Solution

Not sure

**Comment by jandubois** [comment]
I believe we are trying to get rid of `ffi-napi` as part of #5637, so this issue might simply go away.

**Comment by jandubois** [comment]
I'm using Python 3.13.0, and this doesn't seem to be an issue.
