### ISSUE TITLE
Docker-compatible CLI

### ISSUE THREAD

**Issue by awakecoding** [rancher-sandbox/rancher-desktop#566]
I would like to use Rancher Desktop as a replacement of Docker Desktop - it would need a Docker-compatible CLI using containerd, such that it could correctly support both Windows and Linux containers. Microsoft is now using containerd in Azure Kubernetes Services, but Docker for Windows is not yet using it. The closest Docker CLI replacement that leverages containerd is nerdctl, but it would need more work to reach feature parity with Docker Desktop.

With news that Docker Desktop should now be paid for a lot of developers, it only becomes reasonable that we shop for alternatives. I don't necessarily mind if it's Docker Desktop or Rancher Desktop, but I would buy the one with support for containerd on Windows if it were available. There is definitely a business case for this IMO.

**Comment by mattfarina** [comment]
@awakecoding Thank you for filing this issue. I've seen similar requests in a couple other places, too. We will be taking some time this week to look into this and, hopefully, figure out a plan.

**Comment by nejch** [comment]
https://github.com/rancher-sandbox/rancher-desktop/issues/255 seems to also be related to this although smaller in scope.

**Comment by mattfarina** [comment]
I think this will work best as broken into two separate issues to tackle. First, there is getting a generally docker compatible CLI. Second, windows container support. The reason for handling them separately is that we can tackle the docker compatible one more quickly. Some of the underlying tooling isn't ready for Windows containers, yet. It will also require us to do work outside the CLI around Windows versions (not all of them can do windows containers).

**Comment by awakecoding** [comment]
> I think this will work best as broken into two separate issues to tackle. First, there is getting a generally docker compatible CLI. Second, windows container support. The reason for handling them separately is that we can tackle the docker compatible one more quickly. Some of the underlying tooling isn't ready for Windows containers, yet. It will also require us to do work outside the CLI around Windows versions (not all of them can do windows containers).

I think it is fair to break it in two separate milestones, where the first one is to provide a Docker-compatible CLI for Linux containers, and the second one brings support for Windows containers, but the plan should be to support both Linux and Windows containers at the same time on Windows, with proper WSL2 integration. I agree that the Windows integration part adds a lot more work, but it would be necessary to become a proper replacement for Docker Desktop on Windows. I should also clarify that the Windows support is only needed on a Windows host, non-Windows hosts would be a nice-to-have feature.

**Comment by AkihiroSuda** [comment]
Linking a nerdctl PR to support Windows containers. https://github.com/containerd/nerdctl/pull/197

Help wanted to move this forward.

**Comment by mattfarina** [comment]
In the 0.5 release, which will drop soon, we have added [nerdctl](https://github.com/containerd/nerdctl). This is a docker compatible-ish CLI to work with containerd. The "-ish" is because there are some commands and flags that are not supported but are in the Docker CLI. Things like `nerdctl build` and `nerdctl run` mostly work as expected.

This is just a start to our container cli/build/run.

The next step, which I think more suits this issue, is detailed in #673. It is to provide the ability to have docker cli/moby as an alternative to nerdctl/containerd. Note, under the hood moby uses containerd.
