### ISSUE TITLE
Manage all docker containers inside application

### ISSUE THREAD

**Issue by Seidon1984** [rancher-sandbox/rancher-desktop#5664]
### Problem Description

I would like to manage the containers created i.s.o. using terminal. To start, stop, delete, like other programs

### Proposed Solution

Create a new option the rancher to manage the docker containers created

**Comment by jandubois** [comment]
I assume you are looking for something like #4506.

This is currently being worked on; an initial version will be included in the next release:

<img width="1392" alt="CleanShot 2023-10-06 at 09 52 20@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/3b736e88-2a0f-4e9c-803e-51acc60db3bf">

I'm going to close this issue as a duplicate; feel free to re-open if there is any functionality you are looking for that is not covered by the current epic!
