### ISSUE TITLE
Backend-state event should contain details about operation in progress

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/rancher-desktop#5683]
Possible values of `backendIsLocked` are:

- empty string, meaning that the backend is unlocked
- 'Snapshot operation in progress'

The UI needs additional info from back-end state in order to display correct info in the start-up dialog, in case of  running operations in background:

- empty, meaning no operation in progress
- type: restore or creation
- snapshot name
- errors in case of unsuccessful operations

**Comment by gaktive** [comment]
This may likely only happen on Windows, similar to #5674

**Comment by jandubois** [comment]
#6007 describes the latest plan how this should be done, and is mostly implemented.

#6126 writes the lock reason into the lock file.

#6140 uses this lock reason as the lock dialog title.

The remaining suggestions in this issue are no longer relevant and can be reintroduced if we want to refine the algorithm in the future.
