### ISSUE TITLE
The system lets me try to create two snapshots at the same time

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5695]
### Problem Description

Run `rdctl snapshot create NAME`

Now use the UI to create a snapshot named `SOME-OTHER-NAME`. 
Bug 1: The UI should disable snaphost creation
~~Bug 2: When the UI tries to create snapshot `SOME-OTHER-NAME`, it should report the failure (it didn't create the snapshot)~~

### Proposed Solution

I assue the UI needs to be aware of the state of the snapshot lockfile.

**Comment by gaktive** [comment]
Should be addressed by recent PRs by @adamkpickering

**Comment by adamkpickering** [comment]
To clarify, I think this issue is about the UI not being disabled when a snapshot is being created/restored via `rdctl` (i.e. "bug 1"). I don't think bug 2 is a problem anymore - a suitable error dialog and message are displayed.

That means this is more of a UI issue - @torchiaf would you agree?

It would be nice to get this in for 1.11, but it could also be pushed to 1.12... @jandubois?

**Comment by gaktive** [comment]
If we can't anything by Tuesday, we can push this to 1.12.

**Comment by rak-phillip** [comment]
>  Bug 2: When the UI tries to create snapshot SOME-OTHER-NAME, it should report the failure (it didn't create the snapshot)

We do get a failure message, although it's rendered as a banner in the "Create Snapshot" dialog  

![Pasted image 20231117140546](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/effbe6a8-de38-4585-95a0-0ff8a6685877)

I think that the pattern can be improved, but this is no longer an issue given the scope of this bug.

**Comment by rak-phillip** [comment]
>  Bug 1: The UI should disable snaphost creation

My expectation is that the blocking dialog is raised regardless of the snapshot process being initiated from the frontend or the backend 

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/96c5cd91-b4dc-4e8f-abbf-68eb46bca871)

The current behavior only raises the dialog when the creates a snapshot.

**Comment by gaktive** [comment]
Let's look at this again after we change the lock mechanism.
