### ISSUE TITLE
Start eslinting (and fixing) the .js files

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5697]
### Problem Description

Currently nothing in CI is linting the JS files.

For example:
```
$ ./node_modules/eslint/bin/eslint.js  pkg/rancher-desktop/nuxt/store.js
…
✖ 156 problems (1 error, 155 warnings)
  1 error and 153 warnings potentially fixable with the `--fix` option.
```

It's all complaints about missing semi-colons, whitespace nits, and `let` vars that could be `const`. But if our style guide is good enough for the .ts files, it should be good enough for the `.js` files.

### Proposed Solution

Quick fix:
```
find -name '*.js' | xargs ./node_modules/eslint/bin/eslint.js --fix
```

and verify the code is still good.

**Comment by ericpromislow** [comment]
My mistake -- we're ignoring the nuxt/ directory, and this is where all the problems lie. The other `.js` files passed `eslint`.

**Comment by rak-phillip** [comment]
Just to clarify, anything under the nuxt directory is tool-generated and we don't want to apply our linting rules here.
