### ISSUE TITLE
Review bumping ts-loader back to 9.4.4 (or most recent)

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5710]
### Problem Description

See PR
https://github.com/rancher-sandbox/rancher-desktop/pull/5660 (revert bump from 8.4.0 to 9.4.0)
and how I added the ForkTsCheckers to get startup speed back.

Again, 9.4.4 appeared to add another minute or so to startup time and was a partial cause of e2e timeout failures in CI

**Comment by gaktive** [comment]
Closing since we removed the explicit reference to the loader in our prefs.
