### ISSUE TITLE
Namespace Selector for container list with `containerd`

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5714]
The container list lacks a namespace selector when `containerd` is the active container engine. 

This is essential for users who work with multiple namespaces in `containerd`, as it helps in managing and filtering containers efficiently. 

## Expected Behavior

When the container engine is set to `containerd`, there should be a dropdown in the container list that allows users to filter containers by namespace. 

## Acceptance Criteria

- [x] When `containerd` is the active container engine, a namespace selector should be visible in the container list
- [x] The namespace selector should be populated with the available namespaces for containerd
- [x] Users should be able to select a namespace from the namespace selector
- [x] After selecting a namespace, the container list should update to display only containers in the chosen namespace
- [x] The namespace selector should have a default value of "default"
- [ ] Update the documentation with this new feature and how to use the namespace selector

## Additional Context

This behavior already exists in the Images page. We can review this implementation to see if it will apply to the Containers page.

**Comment by IsaSih** [comment]
@sunilarjun is there an issue to track the documentation of this feature?

**Comment by sunilarjun** [comment]
@IsaSih there wasn't but I just created and linked above. Working on the PR for it currently to update the docs, thanks for shouting out!
