### ISSUE TITLE
Blur main window during snapshot operations

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/rancher-desktop#5728]
Blocked by #5747

- apply unfocused style to main window (= opacity: 0.2) when a Snapshot operation is in progress.
- hide menu bar on main window when a Snapshot operation is in progress.
- should be merged once we have a proper progress bar on snapshots dialog.

**Comment by jandubois** [comment]
I assume "blur" means the usual "dimming" the brightness of the window that has no longer the focus, and not actually blurring the contents.

**Comment by torchiaf** [comment]
Yes, this is meant to give the appearance at the main window to be not usable when there is a snapshot operation in progress.

**Comment by torchiaf** [comment]
I moved the Issue to `1.12` but we may move it to `1.11` since it's a very small one in terms of code changed and test area.
