### ISSUE TITLE
Epic: Image Scanning User Experience

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#573]
Scanning images in Rancher Desktop currently produces results that are no different from the cli output. Trivy vulnerability scans can be output in JSON; this output can be used to produce a UX that provides some enhancements:

* table output
* ability to select and take action on multiple vulnerabilities
* sorting by severity

**Comment by mook-as** [comment]
FWIW, we actually do [output in JSON](https://github.com/rancher-sandbox/rancher-desktop/blob/main/resources/templates/trivy.tpl), but we format that as plain text as a MVP.

**Comment by rak-phillip** [comment]
Closing this epic as stale.
