### ISSUE TITLE
Snapshot fails to be created, but UI shows message of success

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5744]
### Actual Behavior

By trying to create a snapshot via UI, the user receives a message of successful action, but the snapshot fails to be created. 

### Steps to Reproduce

1. Start Rancher Desktop
2. Apply a combination of settings (in this case, vz emulation, 16 GB of memory and 5 of CPU)
3. Go to the SNAPSHOTS UI and select `Create Snapshot`
4. Give to the snapshot a name and a description and confirm 
5. Check the output message in the UI

### Result

![snap](https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/9c8ef8b3-4d65-43b6-a76a-f449a3a3a532)

Logs: 
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/12922072/logs.zip)

### Expected Behavior

UI must show an error message when the operation of creating snapshots fails for any reason

### Additional Information

Basically the operation fails to read data from the wrong location

```
rdctl snapshot create vz-16-5
Error: failed to create snapshot: failed to list snapshots: failed to read "/Users/iguimaraes/Library/Application Support/rancher-desktop/snapshots/.DS_Store/metadata.json": open /Users/iguimaraes/Library/Application Support/rancher-desktop/snapshots/.DS_Store/metadata.json: not a directory
```
Same issue reported in #5740 

### Rancher Desktop Version

1.10.0-379-g93632b80

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.5.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Let's ensure all the snapshots PRs are merged and then retest.

**Comment by rak-phillip** [comment]
This has changed since the introduction of snapshots dialogs in #5685. We now get an error banner in the blocking dialog if the snapshot fails to create. Clicking on "Close" will bring the user back to the form. There is no success banner at this point. 

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/b039daa8-529d-4817-9dd0-9bcd0ab9e080)
