### ISSUE TITLE
Cross compiling applications in linux/amd64 container on M1 Macbooks is broken

### ISSUE THREAD

**Issue by TheFriendlyCoder** [rancher-sandbox/rancher-desktop#5755]
### Actual Behavior

In our case, when we build a GOlang based app inside a linux/amd64 Docker container, and compile it for the amd64 architecture, we get regular segfaults. It doesn't happen on every build, and the larger / more complex the build, the more often the segfaults occur.

### Steps to Reproduce

I've reproduced the problem with a simple Dockerfile:

```
FROM golang:1.19 as builder
COPY hello.go .
RUN go build hello.go
```

and a simple hello.go sample script:

```
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
```

And then run the following command:

```
DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build --no-cache .
```

or the equivalent

```
docker build --platform=linux/amd64 --no-cache .
```

NOTE: Sometimes you may have to run the build command several times to see the error, but usually it'll appear at least once every 2-5 times.

### Result

we get errors that look like this:

```
 > [3/3] RUN go build hello.go:
2.355 runtime/internal/sys: /usr/local/go/pkg/tool/linux_amd64/compile: signal: segmentation fault (core dumped)
------
Dockerfile:3
--------------------
   8 |     #RUN go build hello.go
   9 |     #RUN go build hello.go
  10 | >>> RUN go build hello.go
--------------------
ERROR: failed to solve: process "/bin/sh -c go build hello.go" did not complete successfully: exit code: 1
```

### Expected Behavior

Trivial builds like this should succeed without error

### Additional Information

These problems don't exist when we perform the exact same steps using the Docker Desktop application - only Rancher Desktop.

Also, to help expedite the testing and ensure there aren't any cached files interfering with the test builds, I wrote the following bash script that can be run to delete all intermedia files produced by RD or Docker, after which you can reinstall the Rancher Desktop app - with all default settings (except that I have the K8s subsystem disabled - we don't need that).

```
#!/bin/bash
docker context use default
docker buildx use default
rdctl factory-reset --remove-kubernetes-cache
sleep 5
sudo rm -rf /Applications/Rancher\ Desktop.app/
rm -rf ~/.docker
sudo rm -rf ~/Library/Application\ Support/rancher-desktop
sudo rm -rf /var/run/docker.sock
```

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS Sonoma Version 14.0 (23A344)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by TheFriendlyCoder** [comment]
Here's a similar report from last year: https://github.com/rancher-sandbox/rancher-desktop/issues/2109

**Comment by TheFriendlyCoder** [comment]
I should also mention that I tried inverting several different settings in the Rancher desktop app and have the same results. Some of my test cases included:

- with and without admin permissions enabled
- using qemu and vz virtualization
- with and without Rosetta enabled
- with both reverse-sshfs and virtiofs volume file systems
- with both ocket-vmnet and vde-vmnet networking
- with the "experimental" buildkit feature enabled and disabled as described [here](https://github.com/rancher-sandbox/rancher-desktop/discussions/3083)

**Comment by TheFriendlyCoder** [comment]
There's an anecdote on [this redit thread](https://www.reddit.com/r/docker/comments/13z70mk/cross_compilation_fails_on_m1_mac_fails_with/) suggesting that this problem may be fixed in a newer version of Docker Server (v24.0) but I noticed that RD is currently shipping with the latest version of `moby` (v23.x) so maybe the fix isn't available yet.

**Comment by TheFriendlyCoder** [comment]
I also found a similar / the same defect reported in the docker/buildx repository [here](https://github.com/docker/buildx/issues/2028) as well.

**Comment by TheFriendlyCoder** [comment]
Oh, and for good measure I tried installing the x86 build of RD to see if the problem persisted there, but the RD backend service refuses to launch on an M1 Mac, so I was only able to test the aarch64 build.

**Comment by segevfiner** [comment]
Are the qemu binaries used in Rancher Desktop up-to-date? This smells like a qemu bug.

**Comment by TheFriendlyCoder** [comment]
I have the latest Rancher Desktop updates, plus the problem is reproducible using the Apple VZ virtualization as well as QEMU.

**Comment by segevfiner** [comment]
The platform of Docker, flag uses qemu-user binaries inside the VM, it doesn't matter what the virtualization/hypervisor of the VM is. Maybe we can try replacing/upgrading them at runtime using https://github.com/tonistiigi/binfmt or other similar images and see if this helps.

**Comment by billimek** [comment]
Are you having this issue when running Rancher Desktop VM machine type as the Apple Virtualization framework instead of QEMU?

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/6393612/d9a9a78d-620f-4ea9-952f-d4e8fd5c5898)

**Comment by TheFriendlyCoder** [comment]
Yes.

**Comment by v-vostretsov** [comment]
+ having the same issue

**Comment by wills-feng** [comment]
having the same issue

**Comment by mattfarina** [comment]
I just tried setting the VM type to VZ and enabled using Rosetta. That appeared to allow me to cross-compile to amd64. I'm on macOS 14.1.1.

Using skopeo against the docker socket to pull details for the image I see...
```
    "Architecture": "amd64",
    "Os": "linux",
```

**Comment by TheFriendlyCoder** [comment]
VZ / Rosetta had no impact on this behavior for me... and in fact it caused additional problems than running without

**Comment by noethig** [comment]
Also having the same issue, trying to run a docker container linux/amd with wildfly on M1. Is there any progress on this issue?

**Comment by jandubois** [comment]
I cannot reproduce this issue (using Rancher Desktop 1.16.0 on macOS 15.0.1 using M1):

```console
$ uname -m
arm64
$ sw_vers
ProductName:		macOS
ProductVersion:		15.0.1
BuildVersion:		24A348
$ cat Dockerfile
FROM golang:1.19 as builder
COPY hello.go .
RUN go build hello.go
$ cat hello.go
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
$ docker build --platform=linux/amd64 --no-cache .
[+] Building 26.5s (9/9) FINISHED                                                                      docker:rancher-desktop
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 139B                                                                                     0.0s
 => [internal] load metadata for docker.io/library/golang:1.19                                                           5.3s
 => [auth] library/golang:pull token for registry-1.docker.io                                                            0.0s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 2B                                                                                          0.0s
 => [internal] load build context                                                                                        0.0s
 => => transferring context: 143B                                                                                        0.0s
 => [1/3] FROM docker.io/library/golang:1.19@sha256:3025bf670b8363ec9f1b4c4f27348e6d9b7fec607c47e401e40df816853e743a    19.5s
 => => resolve docker.io/library/golang:1.19@sha256:3025bf670b8363ec9f1b4c4f27348e6d9b7fec607c47e401e40df816853e743a     0.0s
 => => sha256:1611d4f97c5ab666d3c123d72b3bb646dd12bbf7577dd1388fdb191d54cdf440 1.58kB / 1.58kB                           0.0s
 => => sha256:80b76a6c918cba6d8e68fb2b80a7afdd7ce3af457d87e413d985434ae7897533 6.87kB / 6.87kB                           0.0s
 => => sha256:9f13f5a53d118643c1f1ff294867c09f224d00edca21f56caa71c2321f8ca004 64.11MB / 64.11MB                         1.6s
 => => sha256:3025bf670b8363ec9f1b4c4f27348e6d9b7fec607c47e401e40df816853e743a 2.36kB / 2.36kB                           0.0s
 => => sha256:012c0b3e998c1a0c0bedcf712eaaafb188580529dd026a04aa1ce13fdb39e42b 49.56MB / 49.56MB                         3.2s
 => => sha256:00046d1e755ea94fa55a700ca9a10597e4fac7c47be19d970a359b0267a51fbf 24.03MB / 24.03MB                         3.3s
 => => sha256:190fa1651026077cee00b53a754acbe0dc734b99255c6b274e798f6cd877ae18 92.27MB / 92.27MB                         6.1s
 => => extracting sha256:012c0b3e998c1a0c0bedcf712eaaafb188580529dd026a04aa1ce13fdb39e42b                                2.6s
 => => sha256:0808c64687902329ac64331848304f6f0bc14b86d6be46bccf79292b564f6587 149.14MB / 149.14MB                       8.4s
 => => sha256:5ec11cb68eac452710eadb46df5e6cf6ead699755303758bf1e262e47b013417 155B / 155B                               3.6s
 => => extracting sha256:00046d1e755ea94fa55a700ca9a10597e4fac7c47be19d970a359b0267a51fbf                                0.7s
 => => extracting sha256:9f13f5a53d118643c1f1ff294867c09f224d00edca21f56caa71c2321f8ca004                                3.0s
 => => extracting sha256:190fa1651026077cee00b53a754acbe0dc734b99255c6b274e798f6cd877ae18                                2.9s
 => => extracting sha256:0808c64687902329ac64331848304f6f0bc14b86d6be46bccf79292b564f6587                                6.4s
 => => extracting sha256:5ec11cb68eac452710eadb46df5e6cf6ead699755303758bf1e262e47b013417                                0.0s
 => [2/3] COPY hello.go .                                                                                                0.1s
 => [3/3] RUN go build hello.go                                                                                          1.5s
 => exporting to image                                                                                                   0.0s
 => => exporting layers                                                                                                  0.0s
 => => writing image sha256:9aa5806b8998180ae4c4d4a37f18946f65bec9fa04a3483c3d15637a6a4bd8fb                             0.0s
$ docker run --rm --platform linux/amd64 sha256:9aa5806b8998180ae4c4d4a37f18946f65bec9fa04a3483c3d15637a6a4bd8fb ./hello
hello world
```

So I would need some updated repro steps that would allow me to reproduce the problem locally.

**Comment by segevfiner** [comment]
Needs some large project so the build takes a while, or trying it multiple times. Maybe try building https://github.com/caddyserver/caddy

**Comment by jandubois** [comment]
> Needs some large project so the build takes a while, or trying it multiple times. Maybe try building https://github.com/caddyserver/caddy

Please provide exact commands that reproduce the error for you.

Please include full information about your setup: macOS version, Intel or M1, using QEMU or VZ, using Rosetta when using VZ, etc.

**Comment by jandubois** [comment]
@segevfiner Please open a new issue, to capture all the information specific to your setup.

As I've shown above, the problem of the original issue author is not (or no longer) reproducible, so this issue should be closed.

It gets too confusing if several different scenarios and repro instructions are mixed up in a single GitHub issue.

**Comment by noethig** [comment]
I did a more thorough testing today and also can't reproduce the problem on Apple M1 Pro :) thank you for the fix!
