### ISSUE TITLE
mac: kim not in path

### ISSUE THREAD

**Issue by disstress** [rancher-sandbox/rancher-desktop#581]
After installing Rancher-Desktop on macOS Big Sur version 11.5.2 and running, kim is not placed in $path.

**Comment by mattfarina** [comment]
@disstress Can you go into the Kubernetes settings and see if kim has been made accessible.

**Comment by suuus** [comment]
@mattfarina solves same issue for me, thanks!

**Comment by gaktive** [comment]
Closing since this is solved. Let us know if there's anything else to do!
