### ISSUE TITLE
I am not able to open rancher desktop on mac. here is the below error. 

### ISSUE THREAD

**Issue by rajibmitra** [rancher-sandbox/rancher-desktop#582]
![image](https://user-images.githubusercontent.com/1690251/132028187-d2dda671-0ce3-4265-af60-55b2dbe16377.png)

**Comment by mook-as** [comment]
Hi there! We might need some more information to track down this issue:
- What version of Rancher Desktop is this? (I assume it's on macOS)
- Could you attach relevant logs? They're in `~/Library/State/rancher-desktop/logs/` (yeah, that's a weird location; we have plans to make it better soon).  I believe `background.log` and `lima.log` will be the most relevant here, but more logs probably wouldn't hurt :)

Thanks!

**Comment by iniinikoski** [comment]
Having the same issue here, Rancher Desktop version 0.4.1 (latest), here's the lima.log:

```
time="2021-09-14T00:15:09+03:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2021-09-14T00:15:09+03:00" level=info msg="Attempting to download the image from \"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/alpline-lima-v0.1.0-std-3.13.5.iso\""
time="2021-09-14T00:15:09+03:00" level=info msg="Downloaded image from \"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/alpline-lima-v0.1.0-std-3.13.5.iso\""
time="2021-09-14T00:15:09+03:00" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/iniinikoski/Library/State/rancher-desktop/lima/rancher-desktop/serial.log\")"
time="2021-09-14T00:15:10+03:00" level=info msg="SSH Local Port: 58260"
time="2021-09-14T00:15:10+03:00" level=error msg="[hostagent] couldn't remove existing localhost host keys"
time="2021-09-14T00:15:10+03:00" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/Users/iniinikoski/Library/State/rancher-desktop/lima/rancher-desktop/ha.stderr.log\")"
Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:3150)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

**Comment by jandubois** [comment]
@iniinikoski I think your problem is due to invalid data in your `~/.ssh/known_hosts` file.

You could try to run this command in a shell:

```
ssh-keygen -R [127.0.0.1]: 58260 -R [localhost]: 58260
```

I suspect you will get one or more errors from the `known_hosts` file. You will need to remove the defective lines for Rancher Desktop 0.4.1 to work. This problem will no longer happen in future Rancher Desktop releases because we will no longer need to modify that file.

**Comment by gaktive** [comment]
Closing based on age and how this problem was solved in later versions. If this is still an issue with Rancher Desktop 1.0 or higher, please file a new ticket and link back here if it helps with context.
