### ISSUE TITLE
Create snapshot using `diffdisk.raw` rather than `diffdisk` when using VZ

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5827]
When Rancher Desktop is using VZ, it converts `diffdisk` into `diffdisk.raw` because VZ only supports RAW disks. When switching back to QEMU, no such conversion is done because QEMU supports both RAW disks and QCOW2 disks. When `diffdisk` is converted to `diffdisk.raw`, `diffdisk` is deleted, so the two should not exist on the system simultaneously.

Currently, only `diffdisk` is taken into account when creating and restoring snapshots. We need to handle `diffdisk.raw` as well.

**Comment by jandubois** [comment]
It turns out that this change is not needed, as `diffdisk.raw` is just a temporary name. The file is renamed back to `diffdisk` at the end of the conversion, so the snapshot code doesn't need to know about this.
