### ISSUE TITLE
Refactor `wrapSnapshotOperation()`

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5831]
While chatting on Slack, @jandubois and I agreed that it would be cleaner if `snapshotErrors` was removed from `src/go/rdctl/cmd/snapshot.go`, and replaced by returning `[]error` from `wrapSnapshotOperation()`, and whatever other functions may return multiple errors.

Additionally, as @jandubois has said a couple of times, we don't want any possibility of doing a factory reset when creating a snapshot. While the code does not currently do this, the inclusion of `wrapSnapshotOperation()` makes it more likely when changing the code in the future. It may make more sense to do away with `wrapSnapshotOperation()` and put the equivalent code in each of `createSnapshot()` and `restoreSnapshot()`.

@jandubois please correct me if I got anything wrong.

**Comment by jandubois** [comment]
> @jandubois please correct me if I got anything wrong.

No, this captures the result of our discussion.

I think that `wrapSnapshotOperation` is trivial enough to just unroll it into the 2 call locations. This also gets rid of having a callback to a closure in the middle, which just obscures the control flow; it can then be simply inlined.
