### ISSUE TITLE
Restore snapshot from the UI fails when the snapshot contains a hash

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5845]
### Actual Behavior

I modified Test Case 173, calling the snapshot "Snapshot #1" instead of the suggested "snap1"

When I try to restore the snapshot in the  UI, I get an error message that Rancher Desktop «can't find snapshot "snapshot"»

### Steps to Reproduce

Create a snapshot in the UI (or with rdctl) called "Snapshot #1". 

### Result

Now try to restore it

### Expected Behavior

It gets restored

### Additional Information

I can restore the snapshot with `rdctl` from the command-line

### Rancher Desktop Version

1.11.rc1

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

n/a

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I can't reproduce this on macOS; I can restore `foo bar` just fine from the GUI:

<img width="1035" alt="CleanShot 2023-10-26 at 17 03 28@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/5988a4a3-09e7-4bcc-bbf4-91f799581bff">

**Comment by jandubois** [comment]
The problem is the hash character, not the space. See:

<img width="631" alt="CleanShot 2023-10-26 at 17 17 36@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/0b9fb06e-c771-436b-bbdd-975611c22cd0">

Is the name send from the renderer thread to the background thread as a URL, so everything after the `#` is stripped as an anchor?

**Comment by jandubois** [comment]
@torchiaf @rak-phillip Can you take a look?

**Comment by ericpromislow** [comment]
So the URL isn't being correctly escaped? 
I can create a snapshot called `99% invisible` (reference to a classic Reply All episode),
and `country & western` so maybe it's only the `#` character
