### ISSUE TITLE
Windows 11: Rancher Desktop Crashes During Create/restore snapshot when app is not running 

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5846]
## Steps to reproduce

1. Shutdown Rancher Desktop
2. After shutdown is complete, via CLI, create a snapshot by running `rdctl snapshot create ABC`
3. AND start the application WHILE THE OPERATION IS STILL IN PROGRESS

## Expected Result

When starting the application, the application's UI must be locked and needs to inform that the snapshot operation is in progress and the VM is still to start.

## Actual Result

Rancher Desktop starts, the UI is locked and informs that the snapshot is in progress, and a Kubernetes Error is raised. 

Closing the Kubernetes Error dialog leaves Rancher Desktop in a locked state with no way to dismiss the "Snapshot operation in progress" dialog.

## Additional Information

Test Case RD-178: Create/restore snapshot when app is not running

### Error Starting Kubernetes
```
Error: wsl.exe exited with code 4294967295
```

### Some recent logfile lines
```
2023-10-26T20:26:33.653Z: Registered distributions: rancher-desktop-data
2023-10-26T20:26:33.796Z: Registered distributions: rancher-desktop-data
2023-10-26T20:26:33.854Z: WSL failed to execute wsl.exe --import rancher-desktop C:\Users\phillip\AppData\Local\rancher-desktop\distro C:\Program Files\Rancher Desktop\resources\resources\win32\distro-0.50.tar --version 2: Error: wsl.exe exited with code 4294967295
```

## Screenshots

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/965d7145-f7cb-48f5-a519-350edf0f9aaa)

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/77188dbc-3b8a-4d72-8862-7d891b5017eb)

**Comment by gaktive** [comment]
Sounds related to #5849 which also requires discussion.

**Comment by gaktive** [comment]
@rak-phillip to try to repro this again.

**Comment by IsaSih** [comment]
While trying to repro this issue, found https://github.com/rancher-sandbox/rancher-desktop/issues/6163. Will move this issue to done but will mention it in #6163 to keep a track of this, as it's a different error
