### ISSUE TITLE
Tray menu not disabled when starting with snapshot lock

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5848]
### Actual Behavior

When Rancher Desktop starts while a snapshot operation is active, it is possible to use the tray menu to open the preferences dialog.

### Steps to Reproduce

1. Quit Rancher Desktop.
2. Run `rdctl snapshot create abcdef`
3. Before the snapshot completes, open Rancher Desktop
4. (There is a modal dialog preventing interaction because a snapshot operation is in progress.)
5. While the snapshot is still ongoing, right click on the tray icon and select the menu entry to open the preferences window.

### Result

The preferences window opens, and the user can interact with it (including applying preference changes).  This can lead to downstream errors.

### Expected Behavior

It should not be possible to open the preferences window (or otherwise interact with the tray menu) while a snapshot operation is in progress.

### Rancher Desktop Version

1.10.0-566-g9034e36d (1.11 RC1)

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2428)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gaktive** [comment]
Sorta related to #5854
