### ISSUE TITLE
Windows 11: Can quit RD while creating/restoring a snapshot

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#5854]
## Steps to reproduce

1. Start Rancher Desktop
2. Go to Snapshots page
3. Create a snapshot

---

1. Do a factory reset
2. Start Rancher Desktop again
3. Try to restore the created snapshot

## Expected Result

According to the RD-173 test case: "Tray menu options must be locked (except Open main window)", the "Quit Rancher Desktop" item should not be active and clickable. 

According to the RD-174 test case: "Tray menu options must be locked (except Open main window)", the "Quit Rancher Desktop" item should not be active and clickable. 

## Actual Result

While the snapshot is being created open the RD tray menu. The menu item "Quit Rancher Desktop" still appears to be active and clickable. Clicking "Quit Rancher Desktop" quits the application

Same applies to the restore operation. While restoring the previous created snapshot, the menu item "Quit Rancher Desktop" still appears to be active and clickable. Clicking "Quit Rancher Desktop" quits the application

## Additional Information

- Test Case RD-173: Create Snapshots via UI
- Test Case RD-174: Restore Snapshots via UI

## Screenshot

![Screenshot_2023-10-27_10-26-47](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/44807d62-6fca-40f1-b6d3-06dfc8c18e00)

![Screenshot_2023-10-27_12-09-03](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/731c1fb7-a6b5-4e59-8e47-c6d9afb42e6b)

**Comment by IsaSih** [comment]
Same behavior occurs in MacOS

**Comment by IsaSih** [comment]
Also, I observed that after snapshot is created/restored, the UI becomes interactive again. However, the backend is still starting. The UI should be locked until full start or just until the snapshot operation is finished?
