### ISSUE TITLE
Windows 11: Containers page staying in "Loading..." status after snapshot restore

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#5855]
## Steps to reproduce

1. Start Rancher Desktop
2. Go to Snapshots page
3. Create a snapshot

---

1. Do a factory reset
2. Start Rancher Desktop again
3. Restore the created snapshot

## Expected Result

RD should be working properly after snapshot restore.

## Actual Result

I created and restored a snapshot as explained in RD-173 and RD-174. After restoring the snapshot I navigated to the Containers page and found it stuck in state "Loading...".

## Additional Information

- Test Case RD-173: Create Snapshots via UI
- Test Case RD-174: Restore Snapshots via UI

## Screenshot

![Screenshot_2023-10-27_13-02-59](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/730cea48-1f80-4a75-855b-a74199c3850d)

**Comment by rak-phillip** [comment]
#5846 could be related

**Comment by jandubois** [comment]
Did you check if the container runtime was actually working, by running `docker ps` or `nerdctl ps`?

**Comment by s0nea** [comment]
> Did you check if the container runtime was actually working, by running `docker ps` or `nerdctl ps`?

No, I didn't. I can check it again on Monday.

**Comment by jandubois** [comment]
I could not reproduce this. I got the "There are no containers to show" message after the snapshot was restored.

I did however wait until the progressbar disappeared before checking the container view; not sure if that would be related.
