### ISSUE TITLE
Windows 11: can't start RD with rdctl-generated locked|deployment profile

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#5857]
## Steps to reproduce

1. Bring up a clean RD environment
2. Create a locked profile via `rdctl create-profile --from-settings --output reg --type locked --hive hkcu`
3. Stop RD
4. Import the profile to the registry
5. Start RD again

## Expected Result

RD should start with all fields being locked.

## Actual Result

RD doesn't start up and shows an error instead (see the attached screenshot).

I also tried it in combination with a deployment profile created via `rdctl create-profile --from-settings --output reg`. I ended up in the same situation.

## Additional Information

- Test Case RD-75: Bring main window via tray menu with locked fields - (all platforms)

## Screenshot

![Screenshot_2023-10-27_18-06-33](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/feb1dfed-32e3-4092-9875-891d3b5c404e)

**Comment by jandubois** [comment]
It looks like the reg format handles empty lists differently. I exported an empty REG_MULTI_SZ value with `regedit.exe`:

```
"zzz"=hex(7):00,00
```

Whereas `rdctl` writes out an empty string followed by the final 0:

```
"patterns"=hex(7):00,00,00,00
```

I guess it makes sense, as an empty string is already the end-of-list marker, so no need for a second `\0`.
 
> A sequence of null-terminated strings, terminated by an empty string (\0). The following is an example: String1\0String2\0String3\0LastString\0\0. The first \0 terminates the first string, the second-from-last \0 terminates the last string, and the final \0 terminates the sequence.
