### ISSUE TITLE
Success toast does not appear on Fedora 38

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5861]
### Actual Behavior

When using the extension testing extension, clicking the "Success" button does not result in a Success toast on Fedora 38 GNOME.

### Steps to Reproduce

Test case 151:
1. Install the testing extension with `rdctl extension install ghcr.io/rancher-sandbox/rancher-desktop/rdx-host-api-test:latest`.
2. Open the testing extension in the UI.
3. Click the "Success" button.

### Result

No success toast shows up.

### Expected Behavior

A success toast should appear.

### Additional Information

Clicking the "Warning" and "Error" buttons both cause toast notifications of the corresponding type to appear.

### Rancher Desktop Version

1.11 RC1

### Rancher Desktop K8s Version

1.27.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Fedora 38 GNOME

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by jandubois** [comment]
Is this a regression? Did it work with Fedora 37?

Could it be something that is configured in system-wide notification settings, like "show only errors and warnings"?

**Comment by adamkpickering** [comment]
> Is this a regression? Did it work with Fedora 37?

I don't think it is a regression, I remember running into it before. I had thought there was an issue for this, but a search turned up nothing. Perhaps I noticed it before but forgot to make an issue?

> Could it be something that is configured in system-wide notification settings, like "show only errors and warnings"?

Let me check this. I wouldn't have made a settings change, and I don't know why that would be the default in GNOME, but stranger things have happened.

**Comment by adamkpickering** [comment]
Closing as this is a duplicate of #5483.

**Comment by ericpromislow** [comment]
The `Success toast` *does* appear on opensuse leap 15.5
