### ISSUE TITLE
Rancher Desktop fails to apply settings when `9p` mount type is selected

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5865]
### Actual Behavior

The backend fails to restart when the `9p` mount type is selected and Apply is clicked.

### Steps to Reproduce

1. Set Preferences > Virtual Machine > Volumes > Mount Type to `9p`
2. Leave the other settings, such as Cache Mode and Protocol Version, set to their defaults.
3. Click apply.

### Result

An error dialog pops up.

### Expected Behavior

Rancher Desktop should restart the backend successfully.

### Additional Information

I first noticed this when testing 1.11 RC1. However, it happens in the exact same way on 1.10.0.

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/13207888/logs.zip)

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

1.27.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Fedora 38 GNOME

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by jandubois** [comment]
> An error dialog pops up.

Could you attach a screenshot of the dialog when this happens?

**Comment by jandubois** [comment]
Also please make sure symlinked files are included properly in the `logs.zip`. They are just stored as symlinks without their targets.

**Comment by adamkpickering** [comment]
Closing as this is a duplicate of #4943.
