### ISSUE TITLE
Remove icons from action buttons - Container Dashboard

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5866]
### Problem Description

For the action buttons in the container dashboard, please, l suggest to leave only the names of the actions, instead of the icons, as the Stop command actually exits the process, but the pause icon in the `Stop` button makes it confusing and user may expect it to run a `Pause`, instead of `Stop`.

<img width="1410" alt="Screenshot 2023-10-30 at 9 46 27 AM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/f68ef471-5c34-45a2-825f-d6dcd65a3844">

### Proposed Solution

Leave only the names of the actions in the action buttons

**Comment by ericpromislow** [comment]
Call for a true stop-button added to issue #5868
