### ISSUE TITLE
Add a stop button to the rancher icon set

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5868]
### Problem Description

See issue #5866 - we were trying to associate the container-stop action with a pause-button icon, but this was just confusing many of the developers.

### Proposed Solution

We're resolving #5866 by removing the icon, but it would be better to add a true stop-icon to this icon set. Seems puzzling that it's not there.

**Comment by gaktive** [comment]
We won't do this.
