### ISSUE TITLE
Container dashboard is not showing kubernetes containers with nerdctl

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5879]
### Actual Behavior

Container dashboard is not showing containers deployed via Kubernetes, even in allowed namespaces

### Steps to Reproduce

1. Start Rancher Desktop
2. Start a container 
`nerdctl run -d -p 5500:80 --restart=always nginx `
3. Deploy a container via Kubernetes:
`kubectl create service clusterip nginx-test --tcp=5000:80 --namespace default`
4. Go to the Containers Dashboard to verify if the deployment is listed in the UI

### Result

<img width="1283" alt="Screenshot 2023-10-30 at 7 36 12 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/86eb7791-f643-40fa-a2f6-d8a4a8be5cfd">

UI does not show the container deployed via Kubernetes
  
```
kubectl get pods -A                                                          
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   svclb-traefik-4a17ecdc-dh27k              2/2     Running     0          5m37s
kube-system   helm-install-traefik-crd-dwfzw            0/1     Completed   0          5m40s
kube-system   traefik-55f65f58b-jbvj5                   1/1     Running     0          5m37s
kube-system   helm-install-traefik-jpmzf                0/1     Completed   1          5m40s
kube-system   coredns-6799fbcd5-ncgq4                   1/1     Running     0          5m40s
kube-system   local-path-provisioner-84db5d44d9-s8pkk   1/1     Running     0          5m40s
kube-system   metrics-server-67c658944b-kttjg           1/1     Running     0          5m40s
**default       nginx-test-566dbd78d4-jwh2m               1/1     Running     0          2m49s**
 ```

 ```
nerdctl ps -a                                                                
CONTAINER ID    IMAGE                             COMMAND                   CREATED          STATUS    PORTS                   NAMES
b9bded6a0d29    docker.io/library/nginx:latest    "/docker-entrypoint.…"    5 minutes ago    Up        0.0.0.0:5500->80/tcp    **nginx-b9bde**
```

### Expected Behavior

Container dashboard must list all containers that are not in the kube system namespace

### Rancher Desktop Version

 1.10.0-579-g3bb3d5b9

### Rancher Desktop K8s Version

1.28.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.5.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
You need to differentiate between `containerd` namespaces and `kubernetes` namespaces.

All images and containers owned by Kubernetes are inside the `k8s.io` containerd namespace.

The dashboard is only showing the containers in the `default` namespace. This has nothing at all to do with `kubernetes` namespaces.

We already have #5714 to add a namespace selector to the container dashboard, so we can consider this issue a duplicate.

**Comment by jandubois** [comment]
To see the different containers from the shell you can run `nerdctl -n k8s.io ps` to see the Kubernetes containers.

You can list all existing containerd namespaces with

```console
$ nerdctl namespace ls
NAME                          CONTAINERS    IMAGES    VOLUMES    LABELS
buildkit                      0             0         0
default                       4             1         0
k8s.io                        13            16        0
rancher-desktop-extensions    0             1         0
```

If you don't specify a namespace with `nerdctl -n NAMESPACE ...` then you get the `default` namespace.
