### ISSUE TITLE
Add --description-from-stdin option to snapshot creation

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5881]
On Windows the commandline has a maximum length of 32KB, which limits the amount of data you can pass to the `--description` option (see #5843).

An easy way around this would be to add an alternative `--description-from-stdin` option, so the app could pipe the description to `rdctl`.

It is arguable that 32KB should be plenty enough for a snapshot description, but it is possible that the description may be autogenerated from manifests of all the workloads installed inside the VM, so it is better to not have an artificial limit.

**Comment by ericpromislow** [comment]
I would add support for `--description-from-file FILE` because stdin on powershell isn't so simple, so some users might not be comfortable with it.

**Comment by jandubois** [comment]
> I would add support for --description-from-file FILE

I'm fine with this as long as `--description-from file -` works as well, to implement `--description-from-stdin`.
