### ISSUE TITLE
containerd ports are not accessible

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#5891]
### Actual Behavior

It appears that accessing the containers from the host is broken.

### Steps to Reproduce

1. Install Rancher Desktop on Windows (with admin)
2. Start Rancher Desktop, with containerd, no Kubernetes, no network tunneling
3. `nerdctl run -d --name hello-world -p 62042:80 strm/helloworld-http`
4. Attempt to connect to the container from Windows:

       curl.exe http://127.0.0.1:62042

### Result

```
> Get-Service RancherDesktopPrivilegedService

Status   Name               DisplayName
------   ----               -----------
Running  RancherDesktopP... Rancher Desktop Privileged Service

> rdctl list-settings | ConvertFrom-Json | % { $_.experimental.virtualMachine.networkingTunnel }

False

> rdctl list-settings | ConvertFrom-Json | % { $_.kubernetes }

version : 1.27.6
port    : 6443
enabled : False
options : @{traefik=True; flannel=True}
ingress : @{localhostOnly=False}

> nerdctl ps -a

CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES

> nerdctl run -d --name hello-world -p 62042:80 strm/helloworld-http

d5ecdb3ad2be46bdb2a8c64811310289975ac8a2522f25cd2a098b84c084f6e5

> netsh interface portproxy show all

Listen on ipv4:             Connect to ipv4:

Address         Port        Address         Port
--------------- ----------  --------------- ----------
0.0.0.0         62042       172.27.135.215  62042

> netstat -ant | findstr '62042'

  TCP    0.0.0.0:62042          0.0.0.0:0              LISTENING       InHost

> Get-NetIPAddress -AddressFamily IPv4 | % { echo $_.IPAddress ; curl.exe "http://$($_.IPAddress):62042" }

172.27.128.1
curl: (56) Recv failure: Connection was reset
192.168.3.159
curl: (56) Recv failure: Connection was reset
127.0.0.1
curl: (56) Recv failure: Connection was reset

> rdctl shell curl http://localhost:62042

<html><head><title>HTTP Hello World</title></head><body><h1>Hello from d5ecdb3ad2be</h1></body></html
```
(I notice that the last byte is missing in the last command… but that's not the issue here.)

### Expected Behavior

It should be possible to reach the container from the host.

### Additional Information

Manual test link: https://app.qase.io/case/RD-54

### Rancher Desktop Version

1.10.0-579-g3bb3d5b9 (1.11 RC2)

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2428)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by Nino-K** [comment]
This is a known issue when using the default network. Switching backends or other operations can cause iptables to enter a state where the associated nat tables rules are clobbered which requires a factory reset or even `wsl --shutdown` to restore the iptables rules.

**Comment by mook-as** [comment]
Yep, confirmed that uninstalling RD, manually doing a `wsl --shutdown`, and re-setup fixed things. (The uninstall was probably unnecessary, I just needed it for other reasons.)
