### ISSUE TITLE
Containers Dashboard Does Not Filter by State

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5893]
The filter on the Containers table is not functioning as expected. The displayed results are inaccurate when attempting to filter containers based on their status or image name.

## Steps to reproduce

1. Start new containers
   1. Start a Docker container: `docker run -d -p 5500:80 --restart=always nginx`
   2. Create a Kubernetes deployment: `kubectl create deployment nginx-test --image=nginx:stable`
   3. Create a Kubernetes service: `kubectl create service clusterip nginx-test --tcp=5000:80`
2. Filter the Containers table
   1. Navigate to Containers
   2. In the filter input, enter "running" to filter by the container's status
   3. In a separate attempt, enter "nginx" to filter by containers with the nginx image

## Expected behavior

- When filtering by "running," the Containers list should only display running containers

## Actual behavior

- When filtering by "running," the Containers list displays "There are no rows which match your search query" instead of showing running containers

**Comment by jandubois** [comment]
> Given the generic nature of the search field (unless we want to go into advanced filters which I'm not sure we support) I think the current behavior is ok.

I agree. At first it was surprising to me that the filter expression is applied to all columns and not just the name, and I can conceive situations where this might show more containers than you want, but I certainly like the simplicity of it.

Let's keep the simple filtering across all columns as the only option for now.

**Comment by rak-phillip** [comment]
> When filtering by "nginx," the Containers list should only display containers with the nginx image

It looks like the existing filter behavior behaves as expected by matching name/image to the provided string. I've removed the criteria related to filtering the image by name.
