### ISSUE TITLE
`kim builder install` references AWS endpoint

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#591]
> kim builder install --force --endpoint-addr=127.0.0.1

Im getting this output. Is trying to connect to AWS even the command is specifying localhost. 

kim builder install --force --endpoint-addr=127.0.0.1
Error: Get "https://***********************.ca-central-1.eks.amazonaws.com/api/v1/nodes": dial tcp ************:443: i/o timeout

> adduser: number 1575537784 is not in 0..256000 range 
> I tried Reset Kubernetes many times, without any success still stuck in the middle of nowhere :(

_Originally posted by @vivanov83 in https://github.com/rancher-sandbox/rancher-desktop/issues/562#issuecomment-913798712_

**Comment by mook-as** [comment]
Pretty sure that just means that `kubectl config set-context` was set to something that wasn't `rancher-desktop` (looks like EKS), so it's trying to install kim on EKS instead.

**Comment by jandubois** [comment]
Yes, that sounds likely. @vivanov83, can you please double-check?

**Comment by vivanov83** [comment]
@jandubois Yep, tried with switching context, now I'm getting the same error as pulberg 

> FATA[0030] Get "https://192.168.64.18:6443/api/v1/nodes": dial tcp 192.168.64.18:6443: i/o timeout

**Comment by jandubois** [comment]
> Yep, tried with switching context, now I'm getting the same error as pulberg

Ok, in that case I'll close this issue as a duplicate of #592
