### ISSUE TITLE
kim builder: connection refused

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#592]
```
kim builder install --force
Error: Get "https://127.0.0.1:6443/api/v1/nodes": dial tcp 127.0.0.1:6443: connect: connection refused
```

_Originally posted by @pulberg in https://github.com/rancher-sandbox/rancher-desktop/issues/562#issuecomment-913194592_

**Comment by gaktive** [comment]
Kim was removed from Rancher Desktop prior to 1.x. Closing this as it is no longer necessary.
