### ISSUE TITLE
SASS Deprecations

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#593]
﻿Investigate SASS deprecation warnings and issues associated with `math.div`.

> Due to the sass deprecation warning, I've attempted to use math.div instead of /, but I just get Undefined function instead (after @use "sass:math"; @debug math.$e worked but @debug math.div(2, 1) failed).

#523

**Comment by mook-as** [comment]
Closed by #597 (I believe).
