### ISSUE TITLE
Rancher Desktop fail to start on macOS Sonoma 14.1

### ISSUE THREAD

**Issue by secsaba** [rancher-sandbox/rancher-desktop#5930]
### Actual Behavior

When I start Rancher Desktop after a few seconds exits without any error dialog. How can I see the log files? Is there any command line options to show more debug messages?

### Steps to Reproduce

Start Rancher Desktop.

### Result

No error displayed. Just exits.

If I start from command line the following warnings are displayed after that the program exits:

2023-11-06 09:54:50.128 Rancher Desktop[4477:41445] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
objc[4479]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5c29fc08) and /Applications/Rancher Desktop.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x11352e250). One of the two will be used. Which one is undefined.

### Expected Behavior

Rancher Desktop should start.

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

1.28.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Sonoma 14.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by alan-copeland-keysight** [comment]
Windows 11 doesn't seem to work either...

**Comment by gaktive** [comment]
@secsaba thanks for bringing this to our attention. Are you running any additional security or application level software on your Sonoma setup? I know there have been some changes to Signal AppKit in newer macos versions, along with restorable states, but I'm curious if you've seen this problem on either earlier macos (pre-Sonoma) or Rancher Desktop versions. 

Do you have any files in /Users/USERNAME/Library/Logs/rancher-desktop/ ? This is where we'd expect logs to be written to.

@alan-copeland-keysight are you seeing the exact same error on Windows 11? This issue brings up some Mac-specific errors so I'm curious on what you're seeing?

**Comment by alan-copeland-keysight** [comment]
I think my issue is related to public DNS blocking that was recently implemented at my company.

**Comment by secsaba** [comment]
Thank you @gaktive. Looking at the logs I found the following error: `Invalid strategy "undefined"` that lead me to the #5618 error. After cleaning the folders Rancher Desktop started.

Looks like I had some old lying configurations that didn't let Rancher Desktop to start.
