### ISSUE TITLE
Docs: Provisioning docs are outdated 

### ISSUE THREAD

**Issue by rumstead** [rancher-sandbox/rancher-desktop#5945]
### Actual Behavior

https://docs.rancherdesktop.io/how-to-guides/provisioning-scripts/#windows

On Windows, `%LOCALAPPDATA%\rancher-desktop\provisioning` is used now per https://github.com/rancher-sandbox/rancher-desktop/pull/5612

### Steps to Reproduce

Use the old path and settings are not picked up.

### Result

Settings are not picked up.

### Expected Behavior

`%AppData%\rancher-desktop\provisioning` is used for configuration.

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

1.27

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by rumstead** [comment]
https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/316

**Comment by jandubois** [comment]
Thank you for pointing this out, and for updating the docs. This was an oversight, and we should have migrated the scripts to the new location automatically, the same way we did for the `settings.json` file. Alas it is too late for that now.

I've also updated the release notes "Known Issues" section to mention this problem.
