### ISSUE TITLE
Create functionality to save and restore the state of Rancher Desktop, much like snapshot functionality.

### ISSUE THREAD

**Issue by Beastie71** [rancher-sandbox/rancher-desktop#5948]
### Problem Description

I've a bunch of scripts that I run to setup K8s after a clean start of Rancher Desktop.  These scripts are great, but they do take some time to run and install all the components they do.  If I am testing one thing, and then I need to drop that to test something else, I essentially have to reset Rancher Desktop, re-run a set of setup tasks and then go through testing that scenario, going back to test the initial scenario I have to go back and reset again.  This can result in a lot of wasted time while I wait for my components to install and everything to become healthy.  

### Proposed Solution

If it were possible to save the state of Rancher Desktop to a "snapshot", and allow you to save that state, reset Rancher Desktop, and start fresh, but then at a future point go back and restore that snapshot, it would allow you to recover that previously existing environment and start from there, rather than duplicating the work you had gotten to to get to that state.  This would be particularly useful in testing some of the more advanced K8s tools that I use within my environment.  Ideally, this functionality would allow for having multiple snapshots and allow you to switch between them with little effort.

### Additional Information

I am guessing there is probably a manual way I could do this myself if I knew all the files that were part of an existing running system, and copying those over and then copying them back.  That might be a preliminary solution that I could use, but I think the functionality would be useful for others if it were part of the desktop experience natively.  This functionality would likely be limited with the amount of disk space available on the computer.

**Comment by jandubois** [comment]
> If it were possible to save the state of Rancher Desktop to a "snapshot"

This has just been released in Rancher Desktop 1.11 as a new experimental feature: https://docs.rancherdesktop.io/ui/snapshots

Is this not exactly what you are asking for?

**Comment by jandubois** [comment]
I'm going to close this issue; if there is something missing from our implementation, please file a new issue and provide additional details.

Note that we are still actively working on improving this feature and have a length list of things to improve/fix already (see #5876).
