### ISSUE TITLE
Add a user scope to the winget manifest

### ISSUE THREAD

**Issue by byjrack** [rancher-sandbox/rancher-desktop#5952]
### Problem Description

_Assuming you maintain the manifests on https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/suse/RancherDesktop_

Currently there is just the "default" run of the MSI which will assume machine and needs UAC.

### Proposed Solution

Add a new Installer scope for user and include the MSI params (WSLKERNELINSTALLED=1 MSIINSTALLPERUSER=1) so that a user who wants to install only as User can use winget install suse.rancherdesktop --scope=user

An example of this is 
https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/Anaconda/Miniconda3/py311_23.5.2-0/Anaconda.Miniconda3.installer.yaml

Note that the users winget settings will dictate which scope is the preferred.  I don't think you can override that by manifest so doc tweaks may be needed to keep folks using machine if they want the easier intergration.

### Additional Information

easy workaround for now is

`winget install suse.rancherdesktop --custom "WSLKERNELINSTALLED=1 MSIINSTALLPERUSER=1"`

note custom is only on somewhat recent versions of winget, but the --override exists as well though then you need to manage visibility and logging manually as well.

**Comment by jandubois** [comment]
> Assuming you maintain the manifests on https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/suse/RancherDesktop

We have no control over 3rd party packagers like `winget` or `brew`, so any changes should be requested in their issue trackers.

**Comment by jandubois** [comment]
I'm going to close this issue, as I don't see any action we could take. Let me know if I misunderstand, and if there is something we can do to help on our side (e.g. making changes to the MSI itself).

**Comment by byjrack** [comment]
Yeah some teams maintain their manifests/formulae versus leaving them to community maintenance.  No worries will try and figure out who is doing that maintenance work and get their thoughts.
