### ISSUE TITLE
On Windows, start keeps looking for /etc/rancher/k3s/k3s.yaml

### ISSUE THREAD

**Issue by dvht** [rancher-sandbox/rancher-desktop#5967]
I just installed RD, so i would think it's me who is doing something wrong.  
When I startup RD it hangs on Updating Kubeconfig.
But it looks like this is the problem:

I get an wsl-exec.log filled with
``2023-11-15T14:16:00.451Z: Running: wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi
2023-11-15T14:16:01.729Z: Running: wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi
2023-11-15T14:16:03.054Z: Running: wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi
2023-11-15T14:16:04.424Z: Running: wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi
2023-11-15T14:16:05.703Z: Running: wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi``

If this is executed on windows, it fails because the /bin/sh command is ended by the semicolumn before "then".
test: line 0: syntax error: unexpected end of file (expecting "then")

[the command](https://github.com/rancher-sandbox/rancher-desktop/blame/031e042a746438c8f49f69a2b5e4ae926a5d09ea/pkg/rancher-desktop/backend/kube/wsl.ts#L208) probably should be quoted.

**Comment by ericpromislow** [comment]
I can't reproduce this.

First, the command is run in a linux WSL partition, and is correctly unquoted -- if it was logged as

```
Running: wsl.exe --distribution rancher-desktop --exec /bin/sh -c "if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi"
```

It would fail, as `/bin/sh` would be looking for a command called `if test -r ...`, and not the builtin `if`.

It looks like `k3s` is having problems starting. This is puzzling on a first-time run, but I would run `factory-reset` just in case, and retry starting.

You should have the UI up, even if kubernetes isn't available, and run `Troubleshooting | Factory Reset`. If that's not available, you should be able to run `rdctl factory-reset` from a command-line that was started after Rancher Desktop was installed.

**Comment by ericpromislow** [comment]
Please reopen this issue if the above advice doesn't help.

**Comment by dvht** [comment]
Hi Eric, I'm adding this for future reference.   `rdctl factory-reset ` did indeed solve my issue, and I couldn't reproduce it neither.

However, your comment about the unquoted command confused me because those quotes seem really necessary:

```
C:\WINDOWS\system32>wsl.exe --distribution rancher-desktop --exec /bin/sh -c "if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi"
yes

C:\WINDOWS\system32>wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi
test: line 0: syntax error: unexpected end of file (expecting "then")

```

I used Sysinternals Process Monitor and found out it is only in the logging that the quotes are missing.  `childProcess.spawnFile` called in WSLBackend.execWSL  seems to quote the command before executing, and that's why it works.

**Comment by ericpromislow** [comment]
Yes, that's my mistake on the quoting.  It's annoying that the quotes are dropped in those logs, but the original code
is passing the complete `if ... then ... else ... fi` statement to `/bin/sh -c`:

```
const command = 'if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi';
...
const result = await this.vm.execCommand({ capture: true }, '/bin/sh', '-c', command);
```

Thanks for reporting that it worked on a restart.
