### ISSUE TITLE
dev build fails to start on Windows: no linux wsl-helper

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#5969]
### Actual Behavior

Starting up, I get this error message:
```
Last command run:
wsl.exe --distribution rancher-desktop --exec /usr/local/bin/wsl-service --ifnotstarted docker start

```

### Steps to Reproduce

clone rancher-desktop on a new Windows box, and run `yarn ; yarn dev`

### Result

See above

### Expected Behavior

See above

### Additional Information

```
PS C:\Users\eric3\rancher-desktop\src\go\wsl-helper> wsl.exe --distribution rancher-desktop --exec /usr/local/bin/wsl-service --ifnotstarted docker start
 * Starting Rancher Desktop Docker Daemon ...
 * supervise-daemon: /usr/local/bin/wsl-helper does not exist
 * failed to start Rancher Desktop Docker Daemon                                                                  [ !! ]
 * ERROR: docker failed to start
```

On the linux partition, there is no `wsl-helper`:

```
PS C:\Users\eric3\rancher-desktop\src\go\wsl-helper> wsl -d rancher-desktop ls /usr/local/bin
buildctl                           nerdctl                            vm-switch
buildkitd                          network-setup                      wsl-exec
cri-dockerd                        rancher-desktop-guestagent         wsl-init
docker-credential-rancher-desktop  trivy                              wsl-service
```

### Rancher Desktop Version

1.11dev

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

WIndows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

n/a

**Comment by gaktive** [comment]
Upon discussion, this looked like a one-off issue. Closing.

**Comment by jandubois** [comment]
@ericpromislow reported the same issue again when testing the upgrade from 1.12.0 to 1.12.1:

> In wsl-exec.log:
> ```
>  * Caching service dependencies ... [ ok ]
> 2024-01-12T01:15:40.126Z: Running: wsl.exe --distribution rancher-desktop --exec /usr/local/bin/wsl-service --ifnotstarted docker start
>  * Starting Rancher Desktop Docker Daemon ...
>  * supervise-daemon: /usr/local/bin/wsl-helper does not exist
> 
>  * failed to start Rancher Desktop Docker Daemon
>                          [ !! ]
>  * ERROR: docker failed to start
> ```
> This is with no factory-reset after running 1.12.0 (and shutting it down first).

The problem went away after a factory-reset. We still think this is due to running a release build after a dev build without doing a factory-reset in-between.
