### ISSUE TITLE
host.docker.internal resolves to undefined on Windows 11

### ISSUE THREAD

**Issue by dbielik** [rancher-sandbox/rancher-desktop#5984]
Microsoft just released new [networking security features for WSL2](https://devblogs.microsoft.com/commandline/new-enterprise-grade-security-controls-for-the-windows-subsystem-for-linux/), which breaks the logic behind the configuration of host.docker.internal and host.rancher-desktop.internal [here](https://github.com/rancher-sandbox/rancher-desktop/blob/45944ddda734a97e24e85526914ec2f8c89a44fa/pkg/rancher-desktop/utils/networks.ts).
It happens because the default WSL interface name is renamed from "vEthernet (WSL)" to "vEthernet (WSL (Hyper-V firewall))".

The current workaround is to turn off the new Hyper-V firewall by creating `.wslconfig` file in `%USERPROFILE%` directory with the following content and restarting the computer:
```ini
[experimental]
firewall=false
```

**Comment by NaldoRay** [comment]
We have this issue too on some of our workstations that're using Win11.
Turning off the new hyper-V firewall doesn't work for us.
Turning on network tunneling, however, works both without or with VPN.

**Comment by Nino-K** [comment]
@dbielik thanks for bringing this up, can you confirm if this happens when the network tunnel is enabled or disabled?

**Comment by brunomsilvaf** [comment]
Having the same issue on Win11.
Enabling Networking Tunnel fixed it.

**Comment by josearmins4ns4n** [comment]
Having the same issue.
Turning off the firewall fixed it.

**Comment by Nino-K** [comment]
This does not impact our new network stack (network tunnel) and should not prevent us from making the new experimental network our default network. I can confirm that switching to the network tunnel will rectify this issue, furthermore,as a fix for the old network we should perhaps use a different approach to match the interface name [here](https://github.com/rancher-sandbox/rancher-desktop/blob/45944ddda734a97e24e85526914ec2f8c89a44fa/pkg/rancher-desktop/utils/networks.ts), that can handle both old name and the new interface name.

**Comment by KoditkarVedant** [comment]
When I enabled the network tunnel, I was able to get the `host.docker.internal` dns working but this introduce new issue as when building the image, I was unable to restore NuGet packages from `api.nuget.org`.

There are two possible solutions. 

1. Disable the experimental network adapter above by @dbielik **(Recommended)**
2. You can also rename the adapter `Rename-NetAdapter -name "vEthernet (WSL (Hyper-V firewall))" -newname "vEthernet (WSL)" -IncludeHidden`

**Comment by KoditkarVedant** [comment]
> This does not impact our new network stack (network tunnel) and should not prevent us from making the new experimental network our default network. I can confirm that switching to the network tunnel will rectify this issue, furthermore,as a fix for the old network we should perhaps use a different approach to match the interface name [here](https://github.com/rancher-sandbox/rancher-desktop/blob/45944ddda734a97e24e85526914ec2f8c89a44fa/pkg/rancher-desktop/utils/networks.ts), that can handle both old name and the new interface name.

@Nino-K We could provide a way to configure the adapter name? we can keep `vEthernet (WSL)` as the default adapter. This would help us keep checks simple and avoid any sort of partial checks.

**Comment by jandubois** [comment]
Need to verify if this is fixed by #6933.

**Comment by jandubois** [comment]
> Need to verify if this is fixed by #6933.

I've confirmed that the issue is fixed in `main`, so should be included in 1.14.0.

I will keep this issue open because I think we need to have a BATS test checking for this, in case Microsoft renames the interface again.

**Comment by jandubois** [comment]
> I will keep this issue open because I think we need to have a BATS test checking for this, in case Microsoft renames the interface again.

This should have been caught by `bats/tests/containers/host-connectivity.bats`. I wonder if that got lost due to other BATS tests failing on Windows at that time. Need to verify before adding a new test.

**Comment by jandubois** [comment]
> This should have been caught by `bats/tests/containers/host-connectivity.bats`. I wonder if that got lost due to other BATS tests failing on Windows at that time. Need to verify before adding a new test.

That test is skipped with the legacy networking; it only runs with the new tunneling network that didn't have the problem.

Since legacy networking is going away in 1.15 there is no point in adding tests for it.
