### ISSUE TITLE
Sign PowerShell scripts in the Windows installer

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5989]
Currently only the binaries are signed.

From Rancher User Slack:

> I am looking for some help to install Rancher Desktop on an enterprise managed Windows client. 
>
> We have set up wsl2 already properly [...]
>
> The problem is that it isn't allowed to execute not signed Powershell scripts at all and the installation wizard aborts and rolls back the installation after it tried to exec that script.
>
> Is there a way to get around this? I already unpacked the script, signed it with my key and was able to execute afterwards, but this doesn't really help, because there is no option to not run the script in the installer?

**Comment by mook-as** [comment]
#5875 would drop the PowerShell script (and use a MSI custom action in a DLL instead), so that might bypass the issue. We'll need to check that we signed that DLL correctly, though.

**Comment by mook-as** [comment]
Resolved by either #5875 (dropped the PowerShell script) or #6047 (Added a check for `*.ps1` to ensure they get signed), depending on how you want to look at it.
