### ISSUE TITLE
GitHub Linux Runner Image Outdated

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#6004]
### Problem Description

Today we noticed that some of the E2E CI was failing to run because we had no active runners.  This appears to be because our CI image is outdated.

Per [documentation](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/autoscaling-with-self-hosted-runners#controlling-runner-software-updates-on-self-hosted-runners), the runners must be updated within 30 days.

We currently have [automation to build runner images](https://github.com/rancher-sandbox/rancher-desktop/actions/workflows/github-runner-build-image.yaml), but they are not applied automatically.

### Proposed Solution

- Run the runner image builder automatically when `actions/runner` has a release (we can probably get away with a per-week schedule the check for a new release)
- We may need to stuff the result into a release or a GitHub package (as a container image?) so we can keep track of versions.
- On the github-runner-monitor side, check for new images (daily? weekly?) and pull it down and use it when there's a new one.

**Comment by jandubois** [comment]
We are not using private runners anymore right now, so closing for now.
