### ISSUE TITLE
Network status in status bar colorization improvement

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#6046]
The topic came up during the review here https://github.com/rancher-sandbox/rancher-desktop/pull/5985#discussion_r1402733458 . The network status bar item has a colored dot as 'online'/'offline' indicator in green or red. We might want to have further discussion if the 'online'/'offline' text and/or the globe icon can be colored instead and the dot removed.

Here are some examples:

![Screenshot_2023-11-24_12-22-20](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/3e7d61a8-dd35-4513-bf8e-af18dad49393) ![Screenshot_2023-11-24_12-15-52](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/e32fc658-fc27-4c72-8a31-2a9293461fd4)

---

![Screenshot_2023-11-24_12-22-34](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/7a357197-2510-4a9c-929c-1ada8cc2bb8f)
![Screenshot_2023-11-24_12-16-08](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/147ee212-0904-4fe2-b119-b4f24cd0c954)

---

![Screenshot_2023-11-24_12-23-05](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/702a17e9-a93a-4a79-9d96-0184d23c1433)
![Screenshot_2023-11-24_12-16-31](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/06c7db9b-1da0-49d2-ae9b-6671d66eda44)

---

![Screenshot_2023-11-24_12-24-10](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/0ef441bd-0c4c-462d-906e-cd4c8029b838)
![Screenshot_2023-11-24_12-16-40](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/da3acd0d-d1ec-4f2b-82f1-b9f015bac14b)

---

![Screenshot_2023-11-24_12-26-07](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/3cf9dd84-9e92-498b-9129-2c2ba753bb71)
![Screenshot_2023-11-24_12-17-29](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/7ea95391-1cb0-4453-a4cd-5d906a58c44c)

---

![Screenshot_2023-11-24_12-26-14](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/584d5e74-a01d-4863-a0aa-442c1864617a)
![Screenshot_2023-11-24_12-17-37](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/338061d7-4eac-43f3-af82-da48eed84e70)

---

![Screenshot_2023-11-24_12-26-35](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/2ae9242f-d6cf-4cd4-94a1-ae1f557bbe6a)
![Screenshot_2023-11-24_12-18-03](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/d23ad25e-76a9-471e-9c56-ef9f01a0b595)

---

![Screenshot_2023-11-24_12-26-42](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/6fc2cd7c-5557-4bb4-9c5b-db1c4c69ca66)
![Screenshot_2023-11-24_12-18-11](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/7d2b0093-7531-4468-8c99-25d933d74cb4)

**Comment by jandubois** [comment]
I think the current network status with the colored dot looks good; no further changes needed.
