### ISSUE TITLE
'Rancher Desktop.exe' hangs after running for hours.

### ISSUE THREAD

**Issue by pelifix** [rancher-sandbox/rancher-desktop#6057]
### Actual Behavior

After running Rancher Desktop successful for hours, the 'Rancher Desktop.exe' process is stuck.
When this happens I'm unable to gracefully stop Rancher Desktop and I'm also unable to kill the process.

1) Here are the verbose log when running `rdctl shutdown --verbose`:
[rdctl-shutdown.log](https://github.com/rancher-sandbox/rancher-desktop/files/13474012/rdctl-shutdown.log)

2) Also trying to kill the process in Windows does not work:
```
> taskkill.exe /IM "Rancher Desktop.exe" /T /F
ERROR: The process with PID 25832 (child process of PID 1472) could not be terminated.
Reason: There is no running instance of the task.
```

3) Using Task Manager or Process Explorer to kill the process gives 'access denied':
<img width="556" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/28622113/d9180657-4ef9-463b-8d2a-c97507c3008d">

So only alternative to get back to work is to reboot the laptop (!).

### Steps to Reproduce

Leave it running...

### Result

'Rancher Desktop' stuck and unable to force kill it.

### Expected Behavior

...it should not get stuck. If it gets stuck, we should be able to force kill it.

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

v1.27.4+k3s1

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

23H2 (22631.2715)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

SentinelOne

**Comment by gunamata** [comment]
@pelifix , This could be because of a known WSL [bug](https://github.com/microsoft/WSL/issues/8696) that makes WSL unresponsive after hibernation on some Windows configurations. Next time when you run into the problem, Can you please try the steps suggested in the below FAQ item and see if it helps?

https://docs.rancherdesktop.io/faq#q-rancher-desktop-becomes-unresponsive-after-my-windows-machine-wakes-up-from-hibernation-how-can-i-get-my-rancher-desktop-session-working-again-with-out-having-to-reboot-my-machine

**Comment by pelifix** [comment]
@gunamata thanks for the suggestion.
This is unfortunately is not the cause of the issue. This laptop never goes to hibernation (or sleep) mode, it stays on 24-7.
Also following the suggested steps will of course not fix anything, as the "Rancher Desktop.exe" process is crashed and can not be killed.

**Comment by gunamata** [comment]
@pelifix , Sorry to hear that the suggested workaround did not help. Would you be able to share the application logs from your machine when you run into the error next time please? It helps if you run Rancher Desktop with debug mode enabled. And, you can open the folder containing application logs by clicking on `Show Logs`  under the Troubleshooting page.

**Comment by pelifix** [comment]
Good news. 
I've updated to the _Rancher Desktop 1.11.1_ release, and been running it the whole week, and it has not yet crashed. Before it typically crashed after a day, maybe two.

A fix in 1.11.1 is how it handles _kube config_ file (symlink vs file), and this can explain both the crashing and the stuck process. If a Windows process crashes when doing IO it can become zombie process that are impossible to kill.
More info here: https://techcommunity.microsoft.com/t5/windows-blog-archive/unkillable-processes/ba-p/723389

Let's keep this open a couple of more days, and then close it if all is good. :-)

**Comment by pelifix** [comment]
Problem do not occur after upgrading to 1.11.1.
Closing this issues as fix.
Thx all!

**Comment by ansumaersk** [comment]
It does occur after upgrading to 1.11.1
