### ISSUE TITLE
kubectl in WSL not working

### ISSUE THREAD

**Issue by ashhSAG93** [rancher-sandbox/rancher-desktop#6096]
### Actual Behavior

Upgraded the Rancher Desktop from 1.11.0 to 1.11.1, in order to resolve the issue related to corruption of kubeconfig. 

When I do kubectl on windows, its perfectly fine. 

When I do kubectl on WSL distro like Ubuntu, I get this error:

E1201 10:42:02.542743    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.543253    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.544791    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.546036    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.547709    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### Steps to Reproduce

Upgrade Rancher Desktop from 1.11.0 to 1.11.1

Run a kubectl command on a WSL distro

### Result

E1201 10:42:02.542743    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.543253    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.544791    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.546036    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E1201 10:42:02.547709    1661 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Looks like in wsl the kube config reference seems to be incorrect

As a workaround, I did this in my WSL distro:

echo 'export KUBECONFIG=/mnt/c/Users/ashh/.kube/config' >> ~/.bashrc
source ~/.bashrc

### Expected Behavior

Post upgrade, user should be able to run kubectl smoothly on Windows and WSL. There should be no need of a workaround. 

### Rancher Desktop Version

1.11.1

### Rancher Desktop K8s Version

1.27.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

N/a

**Comment by yevon** [comment]
Exactly the same here, unable to make it to work again, very frustrating. Not even downgrading to 1.10 and deleting everything.

**Comment by jandubois** [comment]
The problem is that the generated kubeconfig does have the context configured. You can fix it with

```
kubectl config use-context rancher-desktop
```

**Comment by kingaj12** [comment]
This answer looks good https://github.com/rancher-sandbox/rancher-desktop/issues/6096#issuecomment-1848716431

But when I run `kubectl config view` there is no `rancher-desktop` configuration

**Comment by jandubois** [comment]
> there is no `rancher-desktop` configuration.

Which Rancher Desktop version are you using? In the latest release 1.13.1 the kube config inside the WSL should be turned into a symlink to the Windows version, as long as there aren't any other users/contexts defined in there.

If you remove (rename) the file and restart Rancher Desktop then it should create the symlink automatically and you will only have a single file to maintain from then on.

**Comment by aleckscastro** [comment]
> This answer looks good [#6096 (comment)](https://github.com/rancher-sandbox/rancher-desktop/issues/6096#issuecomment-1848716431)
> 
> But when I run `kubectl config view` in my WSL2 Ubuntu command window, there is no `rancher-desktop` configuration.
> 
> The rancher-desktop configuration is in `/mnt/c/User/<username>/.kube/config`. I copied (relevant parts of) that file to `~/.kube/config`, and this fixed my problem. This is documented in https://docs.rancherdesktop.io/ui/preferences/wsl/integrations/

Thanks, this worked for me. I had no kube config file on Ubuntu. Instead of copying (parts) of the config file, I simply created a symlink to `/mnt/c/Users/<username>/.kube/config` in `~./kube`.
