### ISSUE TITLE
Rancher Desktop attempts to install kim on non rancher-desktop cluster when kubectl context is switched

### ISSUE THREAD

**Issue by jrdunne** [rancher-sandbox/rancher-desktop#610]
I had a dns issue causing the kim pods to fail to pull their images (ErrImagePull, ImagePullBackOff), but when I switched to a remote cluster to work on something else, rancher desktop tried to install kim on the remote cluster. My remote cluster is an AKS cluster if that matters. I am happy to provide logs or any other details, but I am not sure which ones are relevant 

Rancher desktop should never try to access non rancher-desktop clusters regardless of current kubectl context.

Steps to recreate:
1. Start rancher desktop 
2. Have a broken kim pod
3. Switch kubectl context before it is finished (kubectl config use-context other-cluster)

rancher-desktop version 0.4.1
k8s version 1.21.4

**Comment by jandubois** [comment]
> Rancher desktop should never try to access non rancher-desktop clusters regardless of current kubectl context.

Agreed!

Both `kubectl` and `kim` support `--kubeconfig` and `--context` options, that should **always** be specified both whenever Rancher Desktop calls out to them.

**Comment by ericpromislow** [comment]
merged in https://github.com/rancher-sandbox/rancher-desktop/pull/619#event-5344859695
