### ISSUE TITLE
Rancher Desktop WSL Instance Has No Internet Connectivity

### ISSUE THREAD

**Issue by wstr-ncrum** [rancher-sandbox/rancher-desktop#6110]
### Actual Behavior

When attempting to build a docker file apt-get is unable to reach any archives. All network requests to the internet timeout. We also connected to the WSL instance directly and attempted to curl out to things and it timed out.

### Steps to Reproduce

- Installed Rancher Desktop 1.11.0
- Opened Rancher Desktop without run as administrator
- Try to build a container

### Result

When attempting to build a docker file apt-get is unable to reach any archives. All network requests to the internet timeout. We also connected to the WSL instance directly and attempted to curl out to things and it timed out.

### Expected Behavior

apt-get is able to update and the build complete

### Additional Information

The user that is having the issue also does not have a virtual ethernet adapter showing on their network connections control panel where as others have a "vEthernet (WSL) 2" adapter showing.

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

1.27.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Ent OS Build 22621.2715

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Happens on or off of Ivanti Secure Access Client.

**Comment by wstr-ncrum** [comment]
[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/13549250/logs.zip)
Here are the logs from Rancher Desktop

**Comment by Nino-K** [comment]
@wstr-ncrum you would need to enable the network tunnel.
