### ISSUE TITLE
QEMU fails when properly signed and notarized

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6117]
When using the new `yarn sign` script from #6019 then QEMU no longer works properly:

```console
$ "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/qemu-system-x86_64" -netdev help
qemu-system-x86_64: allocate 1073741824 bytes for jit buffer: Invalid argument
```

The same command worked just fine before the signing.

It looks like the `finch` team ran into [the same problem](https://www.mail-archive.com/qemu-devel@nongnu.org/msg920949.html); not sure how they dealt with it.

This is a release-blocker, because Rancher Desktop no longer works on macOS with QEMU right now. The fallback solution would be use the old signing mechanism for the 1.12 release.

**Comment by mook-as** [comment]
I can reproduce with `qemu-system-aarch64 -M none -netdev help` (on a notarized build).

- I do not see relevant logs in `Console.app`, other than possibly a:
  > ContextStoreAgent (CoreDuet) Simulating crash. Reason: <private>
- This appears to be coming from qemu, specifically:
  https://gitlab.com/qemu-project/qemu/-/blob/v8.0.0/tcg/region.c?ref_type=tags#L536-541
  which is `mmap()` returning `MAP_FAILED`.
- I can reproduce this with `yarn sign --skip-notarize`; that is, just signing without the notarizing seems to produce the same issue.
- I can reproduce with the _Mac Developer_ certificate (i.e. one that can't be used for notarization)
- `com.apple.developer.kernel.extended-virtual-addressing` is not an allowed entitlement.
- `com.apple.security.files.all` doesn't help (makes sense, we're not using App Sandbox)

**Comment by jandubois** [comment]
I've taken a look at [Finch](https://github.com/runfinch/finch). It ships with a signed copy of `qemu`, and it has the same issue (from `ha.stderr.log`):

```json
{
  "level": "warning",
  "msg": "failed to run [/Applications/Finch/lima/bin/qemu-system-x86_64 -M none -netdev help]: stdout=\"Accelerators supported in QEMU binary:\\ntcg\\nhax\\nhvf\\n\", stderr=\"qemu-system-x86_64: allocate 1073741824 bytes for jit buffer: Invalid argument\\n\"",
  "time": "2023-12-04T23:46:58-08:00"
}
```

Somewhat weirdly it shows output on stdout:

```
Accelerators supported in QEMU binary:
tcg
hax
hvf
```

Whereas when I run it manually it only shows stderr output:

```console
$ /Applications/Finch/lima/bin/qemu-system-x86_64 -M none -netdev help
qemu-system-x86_64: allocate 1073741824 bytes for jit buffer: Invalid argument
```

Either way, the command fails, so Lima cannot detect if the `vde` device is supported by QEMU. But then Finch doesn't care, as it only ships with `socket_vmnet` (and their bundled qemu doesn't include `vde` support either).

So maybe the failure is ignorable, but we would have to disable `vde_vmnet` support and always use `socket_vmnet`. But that is a good idea anyways, given that `vde` support is deprecated and seems to be missing in newer qemu builds from homebrew.

**Comment by mook-as** [comment]
After re-signing files:
If I drop `--options runtime` in the signing command line, this no longer shows up.  But that basically just means that if we opt out of using entitlements at all it works…
