### ISSUE TITLE
`yarn screenshots` is broken

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#6127]
### Problem Description

```
 1) screenshots.e2e.spec.ts:94:9 › Main App Test › Main Page › Containers Page ────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveCount(expected)

    Locator: getByRole('row')
    Expected: 6
    Received: 0
    Call log:
      - expect.toHaveCount with timeout 5000ms
      - waiting for getByRole('row')
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
```

Looks like the sortableTables we use no longer have a `row` role in them.

Also, the UI isn't happy (see screenshot)

### Proposed Solution

I tried a css locator `class="main-row"` but that didn't work

**Comment by ericpromislow** [comment]
![Screen Shot 2023-12-05 at 2 52 07 PM](https://github.com/rancher-sandbox/rancher-desktop/assets/108392/f64a5bb3-c608-41a0-b0cc-25a58fea2a7f)

**Comment by ericpromislow** [comment]
I get a console error associated with the above message, but it doesn't stay up for long, and I just get a lot of minified code most likely related to `vue` or `nuxt`:

![Screen Shot 2023-12-05 at 2 55 36 PM](https://github.com/rancher-sandbox/rancher-desktop/assets/108392/960b01ee-71c7-4d0e-bef4-de469bab8780)

**Comment by gaktive** [comment]
@sunilarjun can help

**Comment by jandubois** [comment]
Workaround in #6162
