### ISSUE TITLE
Rancher Desktop produces bad certificates for WSL hosts

### ISSUE THREAD

**Issue by worldofgeese** [rancher-sandbox/rancher-desktop#6156]
### Actual Behavior

With the new Networking Tunnel enabled, RD produces bad certificates.

### Steps to Reproduce

1. Enable Networking Tunnel
2. Enable WSL distro integration
3. Enter `kubectl get no`

### Result

```
Unable to connect to the server: tls: failed to verify certificate: x509: certificate is valid for jahi, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, not gateway.rancher-desktop.internal
```

### Expected Behavior

```
NAME   STATUS   ROLES                  AGE   VERSION
jahi   Ready    control-plane,master   32m   v1.28.4+k3s2
```

### Rancher Desktop Version

1.11.1

### Rancher Desktop K8s Version

v1.28.4+k3s2

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro  23H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by Zeratoxx** [comment]
Is there a workaround to fix the local instance until a new release gets published?

**Comment by lmihalkovic** [comment]
jeez .... nothing ever works these days ...
