### ISSUE TITLE
Cannot start since upgrade

### ISSUE THREAD

**Issue by michaelandrepearce** [rancher-sandbox/rancher-desktop#617]
I was using 0.2.1 on upgrading to 0.4.1 though i can no longer get it to startup and keep getting 

Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 255

From the UI its not clear what the issue is or what i can do to fix, i have tried fresh re-install.

MacBook Pro 15inch (2018) Intel model. MacOS is Big Sur 11.6

**Comment by mattfarina** [comment]
First, let me say that I'm sorry it has taken this long to catch your issue and respond to it. This shouldn't be the norm and we are going to correct that.

We made a big change between those versions that moved from hyperkit to lima/qemu as the manager for the VM. `limactl` is the internal tool we are using to manage the VM where Kubernetes is running.

Did you upgrade all the way to v0.4.1?

You can find logs at `~\Library\State\rancher-desktop\logs`. In the next release we have both a button go get to logs and they are moved to the standard log location.

**Comment by michaelandrepearce** [comment]
@mattfarina thanks for where to find the logs, it seems the issue is with lima, i see there are lots of issues already raised as such i will presume this is very unstable/experimental still, as such ive reverted to 0.3 version and all good again.

**Comment by mattfarina** [comment]
@michaelandrepearce We just release v0.5 and there were numerous stability improvements. You might want to take a look at that release.

**Comment by jandubois** [comment]
I assume this issue has been resolved by one of the later releases, like 0.6.0, 0.6.1, 0.7.0, or 0.7.1.

Please open a new issue with additional details if there are still problems starting Rancher Desktop!
