### ISSUE TITLE
Containers are not starting via containerd

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#6176]
### Actual Behavior

Containers are not starting via containerd

### Steps to Reproduce

1. Start Rancher Desktop with containerd
2. Start a container via `nerdctl run -d -p 5400:80 nginx --namespace default `
3. From the UI, open the container dashboard
4. Run `nerdctl ps -a --namespace default` 

### Result

The container starts with an exited status (so it actually does NOT start at all)

### Expected Behavior

The container must successfully start, so its status must be `running`

### Rancher Desktop Version

1.11.1-457-g88d859a9

### Rancher Desktop K8s Version

1.28.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.5.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> * Start a container via `nerdctl run -d -p 5400:80 nginx --namespace default `

You are passing the `--namespace` option to `nginx` instead of `nerdctl`. It has to be specified even before the `nerdctl` subcommand, i.e.

```
nerdctl -n default run -d -p 5400:80 nginx
```

Note that `default` is the default namespace, so it doesn't have to be specified here at all.
