### ISSUE TITLE
Rancher Docker fails to run on MacOS M3

### ISSUE THREAD

**Issue by bcdeed** [rancher-sandbox/rancher-desktop#6181]
### Actual Behavior

Have install Ranch Desktop 1.11.1 on Macbook Pro M3 and I have two issues;

1. Whilst the Desktop is initialising, I get a Kubernetes error.   I don't actually need Kubernetes but am still getting the error after disabling Kubernetes?
2. Once the Desktop is running, with an exclamation mark icon, I'm unable to execute the docker at the command line

### Steps to Reproduce

Install Ranch Desktop 1.11.1 for M3 chipset
### Application Settings
- Allow Administrative Access
- Configure PATH Automatically 
### Container Engine
- dockerd (moby)
### Kubernetes 
- Disabled 

Run Desktop

### Result

The Desktop presents a popup message with this error;
```
Kubernetes was unable to start: c [Error]: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 255
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:138016)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura',
    'shell',
    '--workdir=.',
    '0',
    'sudo',
    '/bin/sh',
    '-c',
    'rm -f /usr/local/share/ca-certificates/rd-*.crt'
  ],
  stdout: '',
  stderr: '',
  code: 255,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo /bin/sh -c rm -f /usr/local/share/ca-certificates/rd-*.crt'
}`
```

After closing this error message, the command line then fails with
```
>docker login
...
Login Succeeded
>docker pull ruby:2.7.8
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Expected Behavior

I expect the Desktop to startup without the Kubernetes error because its disabled.   Then be able to pull the image via the command line

### Rancher Desktop Version

1.11.1

### Rancher Desktop K8s Version

1.28.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

14.1.2 (23B2091)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by bcdeed** [comment]
Resolved issue by using the Apple Virtualisation Framework

<img width="769" alt="Screenshot 2023-12-12 at 12 21 39 pm" src="https://github.com/rancher-sandbox/rancher-desktop/assets/68991186/40433dca-87fb-4c64-b6f5-a74b4ddbccb1">

**Comment by bcdeed** [comment]
Closing

**Comment by joehorsnell** [comment]
See also #5943
