### ISSUE TITLE
Checked row in Containers tab unchecks itself after short delay

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#6189]
### Actual Behavior

After checking the checkbox at the far left of a row in the Containers tab, it unchecks itself shortly thereafter.

### Steps to Reproduce

1. Start RD with containerd and go to Containers tab.
2. Run `nerdctl run -d -p 5500:80 --restart=always nginx`
3. Check the checkbox that corresponds to the container you just created
4. Wait ~5s

### Result

The checkbox unchecks itself.

### Expected Behavior

The checkbox should stay checked indefinitely, unless the user unchecks it.

### Additional Information

Found while doing test case RD-185.

### Rancher Desktop Version

1.12 RC1 (4a32089ba)

### Rancher Desktop K8s Version

1.28.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment]
Wasn't this fixed by #6201? Maybe the linking didn't work because it was merged into `release-1.12` and not `main`? (We'll merge `release-1.12` into `main` after the release).
