### ISSUE TITLE
Namespace dropdown and container list get out of sync upon navigating to different tab and back

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#6191]
### Actual Behavior

When navigating to another tab and then back to the Containers tab, the container list is kept the same but the selection in the Namespace dropdown is set back to `default`. The container list is thus out of sync.

### Steps to Reproduce

1. Start RD with containerd
2. Navigate to the Containers tab
3. Select the `k8s.io` namespace
4. Navigate to the Port Forwarding tab
5. Navigate back to the Containers tab

### Result

The value of the Namespace dropdown is set back to `default`, but the containers from the `k8s.io` namespace are still shown.

### Expected Behavior

The Namespace dropdown and the shown containers should always be in sync.

### Rancher Desktop Version

1.12 RC1 (4a32089)

### Rancher Desktop K8s Version

1.28.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by rak-phillip** [comment]
Fixed by #6203
