### ISSUE TITLE
Progress bar is displayed inside snapshot deletion confirmation dialog when backend is starting up

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#6204]
### Actual Behavior

The progress bar appears in the snapshot deletion confirmation dialog when the backend is starting.

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/19395776/e85f786d-ba1e-40a9-8ffb-7c5ec35ee64d)

### Steps to Reproduce

1. Create a snapshot via the UI
2. When the snapshot creation completes, the backend should still be starting up. While it is starting up, click "Delete" on the snapshot you just created.

### Result

The progress bar appears inside the dialog asking for confirmation of snapshot deletion.

### Expected Behavior

There should be no progress bar inside the deletion confirmation dialog.

### Additional Information

Found while testing RD-173.

### Rancher Desktop Version

1.12 RC1 (4a32089)

### Rancher Desktop K8s Version

1.28.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by gaktive** [comment]
PR merged.
