### ISSUE TITLE
No error dialog when snapshot creation via UI fails

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#6206]
### Actual Behavior

When settings.json is deleted and snapshot creation is attempted, no error dialog or error feedback of any kind is produced.

### Steps to Reproduce

1. Factory reset
2. Start RD with default settings and wait for it to fully start up
3. Remove settings.json
4. Create a snapshot via the UI

### Result

No error dialog or feedback is produced.

### Expected Behavior

According to test case RD-180, an error dialog with a button that leads to the RD logs should appear.

### Additional Information

Found while testing RD-180.

### Rancher Desktop Version

1.12 RC1 (4a32089)

### Rancher Desktop K8s Version

1.28.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by rak-phillip** [comment]
This regressed as a result of 4328ab6b0e628c3ae16fb8a66bfd8714e3190dd4, where we allow the presence of of a backend lock to raise a blocking dialog. When we emit `dialog/close` from the main window, the blocking dialogs would close indiscriminately.
