### ISSUE TITLE
Extension windows block out bottom status bar

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#6209]
### Actual Behavior

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/19395776/83db0279-3813-43b0-a49d-fa9883f93a8b)

### Steps to Reproduce

1. Factory reset
2. Start RD with defaults
3. Install the Anchore or Disk Usage extension
4. Navigate to their UI

### Result

The extension UI sits over the bottom status bar, rather than under it.

### Expected Behavior

The bottom status bar should be on top of the extension's UI.

### Additional Information

Found while testing RD-171.

### Rancher Desktop Version

1.12 RC1 (4a32089)

### Rancher Desktop K8s Version

1.28.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by rak-phillip** [comment]
This looks like a duplicate of #6190

**Comment by IsaSih** [comment]
Also, found the same issue on Mac Intel 
<img width="1158" alt="Screen Shot 2023-12-13 at 6 26 34 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/6ba7b86d-db5d-4808-903d-6d8f6e941630">

**Comment by adamkpickering** [comment]
Closing as duplicate of #6190.
