### ISSUE TITLE
Rancher Desktop should not automatically switch context upon starting

### ISSUE THREAD

**Issue by ManiacDC** [rancher-sandbox/rancher-desktop#622]
When launching Rancher Desktop, it switches the current Kubernetes context. I use a namespace within my cluster and have that set up as a separate context, so I have to switch contexts back to my context every time I launch Rancher Desktop.

Alternatively, this could be an option.

**Comment by mattfarina** [comment]
This is a great point and, I think you're right. I've added this to a milestone so we can work on it.

**Comment by gaktive** [comment]
We should make this optional with a toggle, in an obvious way with default of "on".

**Comment by ManiacDC** [comment]
> We should make this optional with a toggle, in an obvious way with default of "on".

You could default to on, though I will point out that I've yet to use another tool to run Kubernetes that automatically switches the context every time it starts up. They typically add it to the configuration and maybe switch it the first time, but that's it.

**Comment by jandubois** [comment]
I believe `minikube start` will switch the context every time you run it unless you use the `--keep-context` option, so this would essentially be the same behaviour.

**Comment by dhruvbaldawa** [comment]
+1 to this issue, this is a little inconvenient if the context changes everytime RD restarts. `colima` preserves the context after restart, I would love if we can have a similar behavior in RD.

**Comment by avodaqstephan** [comment]
+1 
I applied manifests multiple times to the wrong cluster just because I needed to start up RD to build some images or run a container locally.
