### ISSUE TITLE
Snapshot creation dialog escapes snapshot name

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#6220]
### Actual Behavior

The snapshot creation dialog (where we wait for the snapshot to be created) appears to HTML-escape the name of the snapshot

### Steps to Reproduce

1. Create a new snapshot with the UI, with the name `""` (two double quotes)

### Result

![Screenshot of the snapshot creation dialog, where the heading says _Creating &amp;quot;&amp;quot;_](https://github.com/rancher-sandbox/rancher-desktop/assets/3977982/ee39faa9-372a-4bf5-a3c0-542a8201f582)

### Expected Behavior

The heading should say _Creating ""_ instead.

### Additional Information

As shown in the screenshot, the description is correctly.  The snapshot listing afterwards also shows the correct text.

### Rancher Desktop Version

1.11.1-468-g4a32089b (1.12 RC1)

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2861)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

None

**Comment by IsaSih** [comment]
Test passes
