### ISSUE TITLE
Snapshot created banner is vulerable to XSS

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#6221]
### Actual Behavior

If the snapshot name contains HTML, the snapshot created banner evaluates it in a way that is susceptible to cross-site scripting.

### Steps to Reproduce

1. Create a snapshot from the UI, where the snapshot name is
   > `</body><img src="invalid:url" onerror="alert(0)">`

### Result

![screenshot of XSS being executed due to the banner](https://github.com/rancher-sandbox/rancher-desktop/assets/3977982/7e4f2e89-3fe6-480c-8603-54a7afe649d7)

The script is executed and an alert pops up.

### Expected Behavior

The snapshot created banner should display escaped HTML, in the same way that the snapshot listing does.

### Additional Information

Since in order to be able to create a snapshot in the UI you need to be an interactive user (or equivalent using accessibility technologies), this is **not** a security vulnerability.

### Rancher Desktop Version

1.11.1-468-g4a32089b (1.12 RC1)

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2861)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

None

**Comment by rak-phillip** [comment]
Unfortunately, all `v-html` usage is susceptible to xss. There's a `clean-html` directive that we can port over to desktop that will resolve this. #4323

https://github.com/rancher/dashboard/blob/807e2dc96cdeca78c6fd9293f068dd3f4cff9981/shell/plugins/clean-html-directive.js#L2

Alternatively, avoid `v-html` usage.
