### ISSUE TITLE
Restoring snapshot does not update status bar

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#6222]
### Actual Behavior

When a snapshot is restored (and the backend restarts), the status bar is not updated to reflect the settings from the restored snapshot.

### Steps to Reproduce

1. `rdctl factory-reset` as a baseline.
2. In first run dialog, select:
   - Kubernetes enabled
   - (Leave default Kubernetes version)
   - Container engine: containerd
3. Make a snapshot
4. In preferences, change settings to:
   - Container engine: moby
   - Kubernetes disabled
5. Wait for restart
6. Restore the snapshot from step 3
7. Wait for restart.
8. Note that the status bar has the settings from step 4, and does match the actual settings.

### Result

The status bar has outdated information (Kubernetes is disabled, and using moby backend)

### Expected Behavior

The status bar should reflect the actual state (Kubernetes is enabled, using containerd backend)

### Rancher Desktop Version

1.11.1-468-g4a32089b (1.12 RC1)

### Rancher Desktop K8s Version

1.26.11

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 (Build 22621.2861)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

None

**Comment by gaktive** [comment]
Duplicate (seemingly) of #6227

**Comment by jandubois** [comment]
Closing this one because #6227 has a screenshot and (more importantly) an assignee. 😄
