### ISSUE TITLE
Progress messages truncated for no good reason

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6229]
Longer progress messages seems to get truncated with an ellipsis (…) even though there is still plenty of space:

![CleanShot 2023-12-15 at 14 42 38@2x](https://github.com/rancher-sandbox/rancher-desktop/assets/78947/f8e953b7-fd23-45b9-a048-00bc5f4e19fb)

Maybe the width calculations have not been updated when the status bar was extended across the whole window, and didn't stop at the menubar?

**Comment by gaktive** [comment]
PR merged
