### ISSUE TITLE
Trying to switch contexts via notification area icon results in an error

### ISSUE THREAD

**Issue by ManiacDC** [rancher-sandbox/rancher-desktop#623]
If I right click the rancher desktop icon, select Kubernetes Contexts, and try to pick a new context, I am presented with this error:

![image](https://user-images.githubusercontent.com/1823305/133837635-834d7472-8ca8-485f-8a89-c1a201cd50de.png)

I can manually switch the context using "kubectl" on the command line without issue.

Windows 10 20H2 x64, rancher desktop 0.4.1

**Comment by mattfarina** [comment]
Thank you for reporting this issue. I can reproduce it.

**Comment by mattfarina** [comment]
I've checked the latest development version and this issue is fixed. Thank you for reporting it and we will soon (days) have a release with this fixed.

**Comment by ManiacDC** [comment]
Thanks!

**Comment by abonillabeeche** [comment]
@mattfarina I've installed Version: 0.4.1-289-g9c37814 and the issue continues. It looks like it can't find kubectl - where is Rancher Desktop expecting it?

**Comment by jandubois** [comment]
I can repro it as well.
