### ISSUE TITLE
Snapshot failure no longer shows failure reason

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6235]
I start Rancher Desktop, delete `~/Library/Preferences/rancher-desktop/settings.json` and try to create a snapshot.

This fails as expected, but the failure reason is not being displayed. The VM is just restarting and the UI returns to this view:

<img width="1392" alt="Screenshot 2023-12-18 at 3 15 30 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/792a9e88-cd30-4f82-8186-883d24f28a2e">

The status message is "Rancher Desktop will be temporarily unavailable while creating a new Snapshot". The only (very subtle) hint that something is wrong is that the "create" dialog is not dismissed, and replace by the list of snapshots.

RD-180

**Comment by jandubois** [comment]
Duplicate of #6206, fixed by #6225.

**Comment by IsaSih** [comment]
Test passes, however, as @jandubois mentions in #6225, the progress bar is displayed in the error dialog, and is stays open even after the VM finishes to restart.
