### ISSUE TITLE
Make socket_vmnet the default setting

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6247]
socket_vmnet is no longer considered experimental (since 1.12), and has always been the only choice for VZ emulation (even when the option was not selected).

We need to make this mode the default before removing vde_vmnet completely.

**Comment by AkihiroSuda** [comment]
For VZ, vzNAT might be a better choice, as it does not need the root.

**Comment by jandubois** [comment]
> For VZ, vzNAT might be a better choice, as it does not need the root.

We already default to `vzNAT` when using VZ emulation without `root`: https://github.com/rancher-sandbox/rancher-desktop/blob/cbcf55c3bc025f66f1f74736dc1579819245cef4/pkg/rancher-desktop/backend/lima.ts#L719-L724

**Comment by jandubois** [comment]
We have announced in the [1.14.0 release notes](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.14.0) that `vde_vmnet` support will be removed in 1.15.0.

We are not going to keep it as a non-default option for another release.
