### ISSUE TITLE
nit: s/socket-vmnet/socket_vmnet/g

### ISSUE THREAD

**Issue by AkihiroSuda** [rancher-sandbox/rancher-desktop#6250]
[`socket_vmnet`](https://github.com/lima-vm/socket_vmnet) seems referred as "socket-vmnet" in GUI and docs:
- https://github.com/search?q=repo%3Arancher-sandbox%2Francher-desktop%20socket-vmnet&type=code
- https://docs.rancherdesktop.io/ui/preferences/virtual-machine/network/

**Comment by jandubois** [comment]
This option will just be removed once `vde_vmnet` is gone. Users don't know what any of this means anyways; it is just confusing.

**Comment by jandubois** [comment]
The "Network" tab has been removed and `socket_vmnet` is the only option, that is always enabled when "Administrative Access" is enabled (yes, unintuitive UX, but that is a different issue).

The `socket-vmnet` string should not longer exist in the source code / UI, and the "Networks" docs page is no longer referenced from the TOC of the docs.

The page itself still exist and can be found by Google, but will be removed via https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/396.
