### ISSUE TITLE
CLI: map docker to nerdctl

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#627]
Any reference have to docker from the CLI needs to map to nerdctl. Both on windows and mac.

**Comment by jandubois** [comment]
I assume this is **in addition** to having a link to `nerdctl` directly. Because the `docker` CLI may already be installed.

**Comment by ericpromislow** [comment]
A proposal before I dive in: I think we should do this only if there's no docker on the target system.

On macos and every linux subsystem except the rancher-desktop one:

 - if `command -v docker > /dev/null` fails and `/usr/local/bin` exists and is in the path, create sym link `/usr/local/bin/docker` pointing it to `../resources/macos/bin/nerdctl`.

On Windows itself:
- If `command docker` fails, copy `.../resources/win32/bin/nerdctl.exe` to `.../resources/win32/bin/docker.exe`

**Comment by jandubois** [comment]
> On macos and every linux subsystem except the rancher-desktop one:
> 
> * if `command -v docker > /dev/null` fails and `/usr/local/bin` exists and is in the path, create sym link `/usr/local/bin/docker` pointing it to `../resources/macos/bin/nerdctl`.

I would simplify as: if `/usr/local/bin` exists, but `/usr/local/bin/docker` doesn't, then allow to create the symlink. Otherwise don't. Isn't this how it works for all the other tools as well?
