### ISSUE TITLE
The repository  is not signed.  / The following signatures were invalid: EXPKEYSIG 1F833FA1A63FE758

### ISSUE THREAD

**Issue by echo-devnull** [rancher-sandbox/rancher-desktop#6291]
### Actual Behavior

When following the installation manual here: https://docs.rancherdesktop.io/getting-started/installation/#linux

After adding the apt repo and the gpg key, when you update, you get the following results:

```sh
Err:2 https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb ./ InRelease
  The following signatures were invalid: EXPKEYSIG 1F833FA1A63FE758 isv:Rancher OBS Project <isv:Rancher@build.opensuse.org>
W: GPG error: https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb ./ InRelease: The following signatures were invalid: EXPKEYSIG 1F833FA1A63FE758 isv:Rancher OBS Project <isv:Rancher@build.opensuse.org>
E: The repository 'https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

### Steps to Reproduce

Follow the installation document

### Result

Invalid signing key error from apt install / update

### Expected Behavior

No error from apt, smooth sailing ;-)

### Rancher Desktop Version

NA

### Rancher Desktop K8s Version

NA

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

❯ cat /etc/issue Pop!_OS 22.04 LTS

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by mattmattox** [comment]
Repulling the key resolves this error.

```
curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | gpg --dearmor | sudo dd status=none of=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg] https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/ ./' | sudo dd status=none of=/etc/apt/sources.list.d/isv-rancher-stable.list
sudo apt update
```

**Comment by echo-devnull** [comment]
> Repulling the key resolves this error.
> 
> ```
> curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | gpg --dearmor | sudo dd status=none of=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg
> echo 'deb [signed-by=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg] https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/ ./' | sudo dd status=none of=/etc/apt/sources.list.d/isv-rancher-stable.list
> sudo apt update
> ```

I've tried that, but it did not fix the issue for me.

**Comment by TejInaco** [comment]
Same here @echo-devnull . Does anyone have a direction to work on this? No ideia...

**Comment by echo-devnull** [comment]
I have removed the repo and switched to using the appimage in the meantime.

**Comment by gunamata** [comment]
I couldn't reproduce on a machine with Ubuntu 22.04. I ran the exact commands provided in[ this section](https://docs.rancherdesktop.io/getting-started/installation#uninstalling-deb-package) of the docs.

```
curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | gpg --dearmor | sudo dd status=none of=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg] https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/ ./' | sudo dd status=none of=/etc/apt/sources.list.d/isv-rancher-stable.list
sudo apt update
sudo apt install rancher-desktop
```

**Comment by jandubois** [comment]
We had 2 developers try to reproduce this on 2 different Ubuntu machines, and it always worked correctly. Maybe it is a configuration error on the package mirror you are using?

Either way, there isn't really anything else we can do from the Rancher Desktop project, so I'm going to close this issue.

**Comment by roytoo** [comment]
> Repulling the key resolves this error.
> 
> ```
> curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | gpg --dearmor | sudo dd status=none of=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg
> echo 'deb [signed-by=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg] https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/ ./' | sudo dd status=none of=/etc/apt/sources.list.d/isv-rancher-stable.list
> sudo apt update
> ```

This solved the issue for me on my Pixelbook in Terminal
output of 
`lsb_release -a`
```
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

**Comment by shearichard-nec** [comment]
> > Repulling the key resolves this error.
> > ```
> > curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | gpg --dearmor | sudo dd status=none of=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg
> > echo 'deb [signed-by=/usr/share/keyrings/isv-rancher-stable-archive-keyring.gpg] https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/ ./' | sudo dd status=none of=/etc/apt/sources.list.d/isv-rancher-stable.list
> > sudo apt update
> > ```
> 
FWIW this worked for me, on Ubuntu 20.x.

**Comment by scrudge** [comment]
> Had the same issue and it turned out that curl was not part of the default install... Fixed the issue with the command: apt install curl

This worked for me

**Comment by imnasnainaec** [comment]
I'm having this issue on Ubuntu 24.04 and none of the suggestions in this issue have resolved it.

**Comment by ziegelstein** [comment]
Can confirm the issue on Ubuntu 24.04

**Comment by imnasnainaec** [comment]
It's also an issue on Wasta-Linux 22.04.

@jandubois On what versions of Ubuntu did the developers try to reproduce this issue?

Can this please be re-opened?

**Comment by jandubois** [comment]
I can repro. The reason is that the key on OBS is expired:

```console
jan@lima-ubuntu-24-04:/Users/jan$ curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | gpg --show-keys
gpg: directory '/home/jan.guest/.gnupg' created
gpg: keybox '/home/jan.guest/.gnupg/pubring.kbx' created
pub   rsa2048 2021-10-29 [SC] [expired: 2026-03-04]
      322BDD0E231125AF14784FB21F833FA1A63FE758
uid                      isv:Rancher OBS Project <isv:Rancher@build.opensuse.org>
```

Just need to figure out who is able to renew the key...

**Comment by jandubois** [comment]
Should be fixed now:

```console
jan@lima-ubuntu-24-04:/Users/jan$ curl -s https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/Release.key | gpg --show-keys
pub   rsa2048 2021-10-29 [SC] [expires: 2028-04-28]
      322BDD0E231125AF14784FB21F833FA1A63FE758
uid                      isv:Rancher OBS Project <isv:Rancher@build.opensuse.org>
```

**Comment by imnasnainaec** [comment]
Yes, it works for me now, thank you!
