### ISSUE TITLE
Can't change the memory size of a running minikube instance

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#63]
The error message says it needs to be deleted and recreated with the new memory size.

We need a story for supporting this. At the simplest, if this is detected, we can delete it and create and start a new instance.

**Comment by mattfarina** [comment]
We should make the minikube details transparent to the end user. When they want to change the memory size we can prompt them and let them know the consequences. They can accept and we do it or cancel and we revert.

**Comment by mattfarina** [comment]
Closing as this has already been solved with the move away from minikube.
