### ISSUE TITLE
Issue with nerdctl arguments parsing

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#630]
Below command worked fine last week, but it gives a parsing error this morning.

`nerdctl.exe run -p 5000:5000 -it simple-flask-app:v1.0`

Error it throws is: `Error parsing arguments: command "container run" does not support option -it`

I noticed this behavior on windows, with `npm run dev` and latest pull of `main` today.

**Comment by jandubois** [comment]
I think this is a bug in the nerdctl-stub wrapper on Windows. Can you try to run the command from inside one of the Linux distros?

**Comment by mook-as** [comment]
The Linux distros use the same nerdctl-stub wrapper (for volume mounts), so it should do the same.

**Comment by jandubois** [comment]
Should be fixed by #631

**Comment by jandubois** [comment]
#639 confirmed that this issue is gone.
