### ISSUE TITLE
No network traffic between pods

### ISSUE THREAD

**Issue by jackmtpt** [rancher-sandbox/rancher-desktop#6314]
### Actual Behavior

On a fresh install of Rancher Desktop, no pods can connect to anything. CoreDNS can't connect to the WSL VM to resolve anything, no pods can resolve anything via CoreDNS. Ping doesn't work between any pods, nor does any other pod-pod traffic.

What _does_ work is port-forwarding from my Windows host machine to a pod as well as all traffic from the WSL VM to anything. Pods can also ping the WSL VM's IP addresses, both on the cni0 interface (10.42.0.1) and eth0 (172.29.131.171), and send DNS queries to the eth0 address.

When doing a tcpdump in the WSL VM (`tcpdump -ni any "udp port 53"`) I see packets on the vethxxx interface coming from various pods but it never reaches the cni0 interface or the veth of the destination pod.

### Steps to Reproduce

New install of rancher desktop. Open a shell in any pod (e.g. traefik):

nslookup google.com 172.29.131.171 # works
nslookup google.com 10.42.0.6 # (the IP of the coredns pod) fails

ping 10.42.0.6 # fails

Get a shell inside the WSL VM:
`wsl -d rancher-desktop`

ping 10.42.0.6 # works

### Result

No pod-pod traffic works at all.

### Expected Behavior

With no network policies in place (the default), every pod should be able to ping/connect to every other pod on ports that they're listening on.

### Rancher Desktop Version

1.11.1

### Rancher Desktop K8s Version

1.28.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Rancher networking tunnel is DISABLED. I've tried turning it on, but that makes things worse - rancher desktop is unable to start (stuck at the 'updating kubeconfig' step).

**Comment by jackmtpt** [comment]
Doing `echo 0 > /proc/sys/net/bridge/bridge-nf-call-iptables` makes normal pod-pod connections work, although pod --> service IP doesn't of course (since those rely on iptables NAT), so this issue seems to be somewhere in the iptables config...

**Comment by Larswa** [comment]
Yeah. Im seeing the same thing.  Rancher Desktop 1.12.2 and 1.12.3 ... .also tried a few earlier versions back to 1.10  
Running on windows 11 22h2.  Tried with both wsl --update and wsl --update --pre-release. 
Seeing the issue both with moby and containerD 

With moby I was seeing this in the k3s.log 

```
time="2024-02-03T10:57:04Z" level=info msg="Will attempt to re-write config file /var/lib/docker/containers/5105ccf96a758d93d68502b288561b3d248f5b2ae14fbdc3b49db0c2a1549c96/resolv.conf as [nameserver 10.43.0.10 search kube-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5]"
time="2024-02-03T10:57:04Z" level=info msg="Will attempt to re-write config file /var/lib/docker/containers/4cb7e77dc1a405d510805236adc4478db2c121d7b45e14a9abeabae944cd6d34/resolv.conf as [nameserver 10.43.0.10 search kube-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5]"
time="2024-02-03T10:57:04Z" level=error msg="Error adding pod kube-system/metrics-server-67c658944b-xvb7m to network {docker 5105ccf96a758d93d68502b288561b3d248f5b2ae14fbdc3b49db0c2a1549c96}:/proc/2013/ns/net:flannel:cbr0: plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
time="2024-02-03T10:57:04Z" level=error msg="Error adding pod kube-system/traefik-f4564c4f4-vb6v4 to network {docker 4cb7e77dc1a405d510805236adc4478db2c121d7b45e14a9abeabae944cd6d34}:/proc/1998/ns/net:flannel:cbr0: plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
time="2024-02-03T10:57:04Z" level=info msg="Will attempt to re-write config file /var/lib/docker/containers/72ca4a960940fd0313e6c7a2e0e8f99eeaa4ed45fe42427dca9f21a9961af6ba/resolv.conf as [nameserver 172.31.83.131]"
time="2024-02-03T10:57:04Z" level=error msg="Error adding pod kube-system/coredns-6799fbcd5-nf8dz to network {docker 72ca4a960940fd0313e6c7a2e0e8f99eeaa4ed45fe42427dca9f21a9961af6ba}:/proc/2171/ns/net:flannel:cbr0: plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
time="2024-02-03T10:57:04Z" level=info msg="Will attempt to re-write config file /var/lib/docker/containers/7bfffde1521da39d92cf433d94bc32cf6e55b40ae6a2f3fbe5d1fea6ce4a2ba7/resolv.conf as [nameserver 10.43.0.10 search kube-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5]"
time="2024-02-03T10:57:04Z" level=info msg="Will attempt to re-write config file /var/lib/docker/containers/1ffcc411b1b5f2fa0380221f441e4fe36ad79a16974091f431bf56ca4400e280/resolv.conf as [nameserver 10.43.0.10 search flux-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5]"
```

I also had this on my laptop, and figured it might be the wsl stack. Did a refresh install and its working again on laptop.  Then seeing the same thing on my developer tower pc. Did a reset there but still seeing the issue there.

**Comment by 0Styless** [comment]
Can also confirm with wsl version:

```powershell
WSL-Version: 2.0.14.0
Kernelversion: 5.15.133.1-1
WSLg-Version: 1.0.59
MSRDC-Version: 1.2.4677
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-Version: 10.0.22621.819
```

and Rancher-Desktop version 1.12.3

**Comment by Nino-K** [comment]
@jackmtpt I have tried to repro this issue but, unfortunately, I don't seem to be able to. Below are the scenarios I have tested.

On windows 10 use RD 1.15.1 (which has network tunnel enabled by default):
```
> kubectl get pods -A -o wide
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE   IP          NODE              NOMINATED NODE   READINESS GATES
kube-system   coredns-574bcc6c46-zwc88                  1/1     Running     0          11h   10.42.0.4   desktop-nfpkmon   <none>           <none>
kube-system   local-path-provisioner-84bb864455-kbztv   1/1     Running     0          11h   10.42.0.3   desktop-nfpkmon   <none>           <none>
kube-system   helm-install-traefik-crd-rzj6n            0/1     Completed   0          11h   10.42.0.2   desktop-nfpkmon   <none>           <none>
kube-system   helm-install-traefik-pwkhc                0/1     Completed   1          11h   10.42.0.5   desktop-nfpkmon   <none>           <none>
kube-system   svclb-traefik-c7rkx                       2/2     Running     0          11h   10.42.0.8   desktop-nfpkmon   <none>           <none>
kube-system   metrics-server-ff9dbcb6c-bkczt            1/1     Running     0          11h   10.42.0.6   desktop-nfpkmon   <none>           <none>
kube-system   traefik-56c4b88c4b-8b6tw                  1/1     Running     0          11h   10.42.0.7   desktop-nfpkmon   <none>           <none>
> kubectl -n kube-system exec -it traefik-56c4b88c4b-8b6tw -- sh
/ $ nslookup google.com 172.27.176.1
Server:         172.27.176.1
Address:        172.27.176.1:53

Non-authoritative answer:
Name:   google.com
Address: 142.251.211.238

Non-authoritative answer:
Name:   google.com
Address: 2607:f8b0:400a:805::200e

/ $ nslookup google.com 10.42.0.4
Server:         10.42.0.4
Address:        10.42.0.4:53

Non-authoritative answer:
*** Can't find google.com: No answer

Non-authoritative answer:
Name:   google.com
Address: 142.251.211.238

/ $ ping 10.42.0.4
PING 10.42.0.4 (10.42.0.4): 56 data bytes
64 bytes from 10.42.0.4: seq=0 ttl=42 time=0.155 ms
64 bytes from 10.42.0.4: seq=1 ttl=42 time=0.136 ms
64 bytes from 10.42.0.4: seq=2 ttl=42 time=0.111 ms
^C
--- 10.42.0.4 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.111/0.134/0.155 ms
```
I have also tried it on the version you mentioned 1.11.1 (without enabling the network tunnel) I managed to reproduce the results above. Things to note I tried with both k8s version 1.28.5 and 1.30.4.
Also, my WSL version:
```
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.19045.4894
```
Lastly, could please confirm that you are still encountering this issue?

**Comment by Nino-K** [comment]
I'm going to close this, feel free to re-open if necessary.
