### ISSUE TITLE
docker init missing?

### ISSUE THREAD

**Issue by tchiaspko** [rancher-sandbox/rancher-desktop#6321]
### Actual Behavior

```
❯ docker init
docker: 'init' is not a docker command.
See 'docker --help'
```

However I see the documentation here https://docs.docker.com/engine/reference/commandline/init/

### Steps to Reproduce

run "docker init" 

### Result

```
❯ docker init
docker: 'init' is not a docker command.
See 'docker --help'
```

### Expected Behavior

```
 docker init

Welcome to the Docker Init CLI!

This utility will walk you through creating the following files with sensible defaults for your project:
  - .dockerignore
  - Dockerfile
  - compose.yaml
  - README.Docker.md


```

### Rancher Desktop Version

Version 1.11.1 (1.11.1)

### Rancher Desktop K8s Version

1.28

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

ventura

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
The `docker-init` plugin is proprietary closed-source software by Docker Inc and only available when you install their Docker Desktop product.

I'm going to close this issue, as there is nothing we can do about it.

**Comment by tchiaspko** [comment]
Bummer. I thought Rancher Desktop is the replacement for Docker Desktop. But I guess something is not able to be replaced.
