### ISSUE TITLE
Upgrading overwrites ~/.kube/config

### ISSUE THREAD

**Issue by jan-hudec** [rancher-sandbox/rancher-desktop#6357]
### Actual Behavior

After upgrade, `~/.kube/config` only contains the `rancher-desktop` cluster

### Steps to Reproduce

Install older version, add more clusters to `.kube/config`, upgrade to newer version (seen as of 1.12.1, already seen in previous upgrade).

### Result

`~/.kube/config` is overwritten with just the `rancher-destop` cluster, context and users entry (and in somewhat unusual order of elements, with the `apiVersion` and `kind` items at the end, too).

### Expected Behavior

The `rancher-destop` cluster and user entries are updated with appropriate certificates, any other entries are left alone. The other entries are *important*.

### Additional Information

It takes a lot of work to add back the two dozens or so entries I normally have in `~/.kube/config`. The inconvenient structure of the config, where each cluster needs to be added in three places, is partly to blame.

Note that since I picked a specific version of k3s some time ago, it did *not* get upgraded during the rancher-desktop upgrade.

### Rancher Desktop Version

1.12.1

### Rancher Desktop K8s Version

1.25.4 (which means it did *not* upgrade with rancher-desktop)

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Business 22H2 19045.3930

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Bitdefender 7.9.8.350

**Comment by Nino-K** [comment]
@jan-hudec Thanks for reporting this, we did some work as part of https://github.com/rancher-sandbox/rancher-desktop/issues/6245 that should address this issue. This work will be included in our new upcoming release. You can try out our new release that will be coming out soon to see if it works for you. Meanwhile, I will go ahead and close this issue, if you encounter anything further feel free to reopen.
