### ISSUE TITLE
Manually check for update

### ISSUE THREAD

**Issue by giggio** [rancher-sandbox/rancher-desktop#6360]
### Problem Description

I'd like to have a way to manually check for updates.

### Proposed Solution

A button on the general tab next to the version would be enough.
Another option is a right click on the tray icon.

### Additional Information

Right now it sees it only checks for updates when the app is restarted, which takes a long time.
You could also check in an interval, like every x minutes.

**Comment by jandubois** [comment]
> You could also check in an interval, like every x minutes.

I believe it checks every 60 minutes right now. Are you saying this doesn't seem to be working?

Also note that new releases are not immediately available via the update checker; we usually wait a few days after release before upgrading people automatically (in case early users report critical bugs).

**Comment by giggio** [comment]
That's probably it. I haven't seen the 1.12.2 version yet, I thought it was not showing.
Ok, I'll close the issue and I will watch the one hour interval, if I don't see it showing I'll reopen. Thanks!

**Comment by jandubois** [comment]
Auto-updates for 1.12.2 are enabled now

**Comment by giggio** [comment]
And I can confirm the update showed up without needing to restart. Great!
