### ISSUE TITLE
JavaScript Error 

### ISSUE THREAD

**Issue by ontec-xrail** [rancher-sandbox/rancher-desktop#638]
When clicking in task bar "Kubernetes Contexts" -> "rancher-desktop"

![image](https://user-images.githubusercontent.com/68220434/134202096-baa14de9-b964-4162-94a4-ee498e3db603.png)

Windows 10 Pro (21H1)

**Comment by evertonlperes** [comment]
@ontec-xrail  Could you share the version of your rancher-desktop and also windows version?

**Comment by mattfarina** [comment]
It appears this is a duplicate of #623. I can reproduce the issue. Closing it as this is a duplicate issue. We will work it from the other issue.
