### ISSUE TITLE
Add version check for Windows Server

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6390]
We document that Rancher Desktop works on Windows 10 version 1909 or later.

For Windows Server we require Windows Server 2022 plus some KB fixes, as that is the first time Windows Server supports WSL2.

We should determine the minimum requirements, add them to the docs, and maybe to the app.

**Comment by mook-as** [comment]
Given that we currently are not doing any testing on those platforms, we should just say "current, non-Insiders, Windows 10/11, no Server versions" instead?

**Comment by skyhirider** [comment]
As someone who was looking for a way to run Linux containers on a Windows Server, having it mentioned on the [Windows requirements page](https://docs.rancherdesktop.io/getting-started/installation#windows) would have been nice.
