### ISSUE TITLE
Impossible to install Rancher Desktop recent versions on Windows 10 Pro.

### ISSUE THREAD

**Issue by DavidCorral94** [rancher-sandbox/rancher-desktop#6399]
### Actual Behavior

Every time I try to install one of the recent versions of Rancher Desktop in my Windows laptop, I get the following message in the installer:

```
Rancher Desktop Setup Wizard ended prematurely
Rancher Desktop Setup Wizard ended prematurely because of an error. Your system has not been modified.
To install this program at a later time, run Setup Wizard again. Click the Finish button to exit the Setup Wizard.
```

The most recent version that I'm able to install is 1.11.1.

I'm on Windows 10 Pro, version 22H2. Everything has been working fine until last couple of weeks. I don't know if related, but applications that I run locally can't reach containers that I've locally deployed. I needed to reinstall version 1.11.1 to fix it.

### Steps to Reproduce

1. Download any of the installers for Windows
2. Execute the installer

### Result

```
Rancher Desktop Setup Wizard ended prematurely
Rancher Desktop Setup Wizard ended prematurely because of an error. Your system has not been modified.
To install this program at a later time, run Setup Wizard again. Click the Finish button to exit the Setup Wizard.
```

### Expected Behavior

I would expect to get the software properly installed in my computer.

### Rancher Desktop Version

1.12.2

### Rancher Desktop K8s Version

Client Version: v1.26.0 | Kustomize Version: v4.5.7 | Server Version: v1.25.4+k3s1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro, version 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

No.

**Comment by mook-as** [comment]
That sounds like Rancher Desktop hasn't been fully installed. Would you be able to re-run an install with extra logging, and then attach the logs?

You'd need to run this in command prompt (or PowerShell):
```
msiexec /i "C:\Path\to\Rancher Desktop 1.12.2 Setup.msi" /lvx* "C:\Path\To\Setup\Log.txt"
```

> applications that I run locally can't reach containers that I've locally deployed. 

You may want to try enabling the [networking tunnel](https://docs.rancherdesktop.io/ui/preferences/wsl/network) to see if that helps.

**Comment by DavidCorral94** [comment]
@mook-as here you have the logs of the installation try: https://gist.githubusercontent.com/DavidCorral94/6bfac7d8d916a50e8f843c95561d8d0a/raw/4ad6bad645e5b3c1afeeb312ba4c40888b277bcb/log.txt

I'll try about [networking tunnel](https://docs.rancherdesktop.io/ui/preferences/wsl/network) thanks!

**Comment by mook-as** [comment]
I think the relevant bits are:
```
Action 9:19:59: InstallWSL. Installing Windows Subsystem for Linux...
MSI (s) (28!84) [09:19:59:885]: Closing MSIHANDLE (79) of type 790531 for thread 11140
MSI (s) (28!7C) [09:19:59:957]: Creating MSIHANDLE (80) of type 790531 for thread 8572
time="2024-02-01T09:19:59+01:00" level=info msg="--install: unrecognized option: no-distribution"
MSI (s) (28!7C) [09:19:59:958]: Closing MSIHANDLE (80) of type 790531 for thread 8572
MSI (s) (28!84) [09:19:59:980]: Creating MSIHANDLE (81) of type 790531 for thread 11140
time="2024-02-01T09:19:59+01:00" level=error msg="Installing WSL failed" error="exit status 0xffffffff"
```

I think that means you need to:
1. Install WSL manually; either via `wsl --update` (if you have an earlier version installed), or `wsl --install`, or via the Microsoft Store.
2. Try manually uninstalling Rancher Desktop 1.11.1 to see that succeeds.  We do not remove user settings on uninstall yet, so that should be safe.  To get logging for this, do `msiexec /x "{9CB25129-38F0-474A-BAFD-9718DCF6D4F1}" /lvx* C:\path\to\log.txt`
3. Try manually installing the new version again.

You may need to have reboots between some of the steps.

**Comment by DavidCorral94** [comment]
That was it. Thank you very much!
