### ISSUE TITLE
We should separate changing minikube settings from restarting it

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#64]
1. Restarting minikube takes a long time. Better to follow the virtualbox model -- gather the user's settings first, and then act on them after.

**Comment by ericpromislow** [comment]
I'm going to add an "Apply" button that's enabled iff specified settings differ from current settings.

**Comment by ericpromislow** [comment]
See PR #83

**Comment by mook-as** [comment]
I don't think this applies anymore, right? (We _definitely_ don't have minikube settings anymore…)

**Comment by jandubois** [comment]
We don't have minikube anymore, but the principle still applies: you don't want to restart the VM after changing the number of CPUs because you might also want to change the memory allocation, requiring yet another restart.

However, I don't know if this hasn't been implemented already?

**Comment by jandubois** [comment]
> We don't need the MINIKUBE_HOME setting at

No, but you can just change it to `LIMA_HOME` to future-proof the code :) (see #380)

**Comment by gaktive** [comment]
We moved away from Minikube.
