### ISSUE TITLE
@kubernetes/client-node.findHomeDir does not match kubectl logic

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#644]
User on Slack reporting:

```
Error: EPERM: operation not permitted, mkdir 'H:\.kube'
```

Setup seems to be:

* `HOME` is not set
* `HOMEDRIVE=H:` and `HOMEPATH=\`, but `H:\` is a read-only DFS mount
* `USERPROFILE` is set and points to a writable directory

I also believe that `%USERPROFILE%\.kube\config` exists and is automatically used by `kubeconfig`.

The issue seems to be the simplistic logic in the [findHomeDir function in the client-node code](https://github.com/kubernetes-client/javascript/blob/1adb9a7/src/config.ts#L520-L547):

* The first of `%HOME%`, `%HOMEDRIVE%%HOMEPATH%`, `%USERPROFILE%` that exists is returned.

It uses `fs.accessSync(process.env.HOME)`, which implicitly uses `fs.constants.F_OK`, which does not verify that the directory is writable.

The [HomeDir function in the go-client](https://github.com/kubernetes/kubernetes/blob/ea07644/staging/src/k8s.io/client-go/util/homedir/homedir.go) uses these rules:

```
// HomeDir returns the home directory for the current user.
// On Windows:
// 1. the first of %HOME%, %HOMEDRIVE%%HOMEPATH%, %USERPROFILE% containing a `.kube\config` file is returned.
// 2. if none of those locations contain a `.kube\config` file, the first of %HOME%, %USERPROFILE%, %HOMEDRIVE%%HOMEPATH% that exists and is writeable is returned.
// 3. if none of those locations are writeable, the first of %HOME%, %USERPROFILE%, %HOMEDRIVE%%HOMEPATH% that exists is returned.
// 4. if none of those locations exists, the first of %HOME%, %USERPROFILE%, %HOMEDRIVE%%HOMEPATH% that is set is returned.
```

Both rule 1 and rule 2 both would have produced the correct location here.

Let's implement the `kubectl` logic in RD, but also file a PR against the `client-node` upstream.

Note the subtle change of order between rules 1 and 2: for existing `.kube/config` files `%HOMEDRIVE%HOMEPATH%` is preferred, but for creating a new `.kube` directory `%USERPROFILE%` is attempted first.

**Comment by mattfarina** [comment]
I think this is important to upstream, as well.

**Comment by ngauje** [comment]
Same problem here, I share you some information an hope it will help.

here my env on windows :
```
Get-Item -Path Env:HOME*
Name                           Value
----                           -----
HOMEPATH                       \
HOMESHARE                      \\remotefiler\USERNAME
HOMEDRIVE                      U:
```

Note: `U:` is a mounted volume

```
Get-Item -Path Env:USERPROFILE
Name                           Value
----                           -----
USERPROFILE                    C:\Users\username
```

Kubeconfig is here:
U:\.kube\config

Kubectl on windows seems to find it bu oddly, the command execution is slow:
```
PS C:\Users\username\.kuberlr\windows-amd64> .\kubectl1.19.11.exe get node
NAME           STATUS   ROLES            AGE    VERSION
myhost   Ready    builder,master   108d   v1.19.11+k3s1
```

I don't think there is a way for the rancher-desktop distro to fetch this file, since there is no U: mount (no `/mnt/u/`)

Example:
```
./wsl-helper  kubeconfig --show
Error: Could not open Windows kubeconfig: stat : no such file or directory
```
