### ISSUE TITLE
docker engine doesn't start on Windows 10 with with the CI build on the main branch

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#6443]
During launch, the application just stays at `Initializing Rancher Desktop` forever. docker.log has below error messages.

I am using this CI build: https://github.com/rancher-sandbox/rancher-desktop/actions/runs/7808139770 

```
time="2024-02-07T15:36:05.415071300Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
time="2024-02-07T15:36:05.415301500Z" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
time="2024-02-07T15:36:05.415308400Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: Error initializing network controller: error obtaining controller instance: unable to add return rule in DOCKER-ISOLATION-STAGE-1 chain:  (iptables failed: iptables --wait -A DOCKER-ISOLATION-STAGE-1 -j RETURN: iptables v1.8.10 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain DOCKER-ISOLATION-STAGE-1
 (exit status 4))
could not connect to docker: dial unix /mnt/wsl/rancher-desktop/run/docker.sock: connect: connection refused
```

**Comment by mook-as** [comment]
> unable to add return rule in DOCKER-ISOLATION-STAGE-1 chain

Please do a `wsl --shutdown` and see if that helps?
Also, please consider using the network tunnel.

**Comment by gunamata** [comment]
The issue seems to be an old WSL kernel version on my machine.

I had `5.10.102.1-microsoft-standard-WSL2`. After I upgraded to `5.15.133.1-microsoft-standard-WSL2` via `wsl --update`, I could launch Rancher Desktop with out issues.

Per @mook-as 's suggestion, we can potentially add a diagnostic to check whether the user is on a minimum kernel version Rancher Desktop works with. But the challenge is how do we find that minimum version, which should be a version between `5.10.102.1-microsoft-standard-WSL2` and `5.15.133.1-microsoft-standard-WSL2` !

**Comment by mook-as** [comment]
See also #6460

**Comment by gunamata** [comment]
I could test this on a old machine that has the older WSL kernel version `5.10.102.1`. 

When I installed @mook-as 's [PR](https://github.com/rancher-sandbox/rancher-desktop/pull/6524), the installation wizard upgraded my WSL, and I could successfully install and launch the app.
