### ISSUE TITLE
Add option to start Rancher Desktop minimized in notification area

### ISSUE THREAD

**Issue by ManiacDC** [rancher-sandbox/rancher-desktop#645]
I have Rancher Desktop in my Startup folder in Windows. This automatically starts kubernetes for me, which is my ultimate goal.

However, I then have to manually close Rancher Desktop so it minimizes to the notification area. It would be nice for an option where it starts minimized (preferably only in the notification area, and not on the taskbar).

**Comment by slashbeast** [comment]
Was about to file a bug for it, however for MacOS. Starting rancher-desktop at login just to close the window right after that could really be a feature.

**Comment by jandubois** [comment]
Settings to automatically start Rancher Desktop on login, to start it without the window open, and even to hide the notification icon have all been implemented (for all platforms): https://docs.rancherdesktop.io/ui/preferences/application/behavior

If you hide both the main window and the notification icon, you have to "start" the application again: when the app detects that an instance is already running, it will activate (and show the window) of the running instance instead. You cannot run more than one instance of the app.

**Comment by slashbeast** [comment]
> Settings to automatically start Rancher Desktop on login, to start it without the window open, and even to hide the notification icon have all been implemented (for all platforms): https://docs.rancherdesktop.io/ui/preferences/application/behavior
> 
> If you hide both the main window and the notification icon, you have to "start" the application again: when the app detects that an instance is already running, it will activate (and show the window) of the running instance instead. You cannot run more than one instance of the app.

Thanks for the response. I was looking though `rdctl start --help` and was looking for something to start in the background as argument passed to it, didn't crossed my mind it might be a setting of the GUI that I need to change. This solution works for me.

**Comment by jandubois** [comment]
> I was looking though `rdctl start --help` and was looking for something to start in the background as argument passed to it

The command would be

```
rdctl start --application.auto-start --application.start-in-background
```
