### ISSUE TITLE
Kuberenetes won't start with WSL `networkingMode=mirrored`

### ISSUE THREAD

**Issue by evilhamsterman** [rancher-sandbox/rancher-desktop#6517]
### Actual Behavior

WSL is configured to use `networkingMode=mirrored` https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking Kubernetes will never start, Docker works fine but it appears that RD is not communicating with docker because it never pulls any images

### Steps to Reproduce

Stop any WSL distros `wsl --shutdown`
Create a `%USERPROFILE%/.wslconfig` file and add 
```ini
[wsl2]
networkingMode=mirrored
```
Open and enable Kubernetes in RD

### Result

Kubernetes never starts

### Expected Behavior

Kubernetes starts

### Rancher Desktop Version

1.12.3

### Rancher Desktop K8s Version

1.29.1, 1.28.6

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

I have Tailscale on two machines and Cortex XDR on one but the same issue occurs whether they are on or off.

**Comment by ryullulala** [comment]
This has been resolved in Docker version 4.26.0.
You can resolve it by upgrading Docker version.

Ref : https://docs.docker.com/desktop/release-notes/#for-windows-5

**Comment by evilhamsterman** [comment]
@ryullulala The docker version is provided by Rancher Desktop so it's on them to update it.

**Comment by oidualc** [comment]
Also, it doesn't make much sense, 4.26.0 is the _Docker Desktop_ version which is a different product.
It includes _Docker Engine_ version 24.0.7, while Rancher Desktop v1.13.0 includes `Docker version 25.0.4-rd, build c4cd0a9`, so a later version, and still has the bug. I don't think the problem lies there.

**Comment by evilhamsterman** [comment]
This appears to be resolved in 1.13.1
