### ISSUE TITLE
WSL Proxy always using the client admin account to talk to k3s API

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#6553]
As of this PR https://github.com/rancher-sandbox/rancher-desktop-networking/pull/20 we enable the HTTPS connections both from the downstream kubectl client and to the upstream which is K3s API Server. 

However, the cert that is used to establish an upstream HTTPS connection to the k3s API server is always the client admin cert. While this works it raises an issue and that is when a downstream incoming HTTPS connection is established from a less privileged account e.g service account, we are still using the client admin cert to establish the upstream account to the K3s API server. 

The ideal approach would be to use an appropriate cert for the upstream connection depending on what is presented from the downstream incoming HTTPS connection.

**Comment by jandubois** [comment]
> the cert that is used to establish an upstream HTTPS connection

Can't we use a raw TCP proxy (using SOCKS or HTTPS CONNECT), so the connection can use the actual client credentials?
