### ISSUE TITLE
Unable to install version 1.13 of Rancher Desktop on Win11

### ISSUE THREAD

**Issue by feibaihengmo** [rancher-sandbox/rancher-desktop#6560]
### Actual Behavior

Unable to install version 1.13 of Rancher Desktop on Win11.
I am a newcomer who just wanted to try Rancher, but when I tried to install the latest Rancher desktop, it kept failing. I tried it for two days. Until just now, I thought about whether it was the latest version issue and successfully installed it after switching back to version 1.12

### Steps to Reproduce

none

### Result

now it has been installed

### Expected Behavior

none

### Rancher Desktop Version

1.13

### Rancher Desktop K8s Version

i dont know

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

23H2(22631.3155)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Rancher Desktop 1.13 has not been released yet. I assume you built it yourself, or used a CI build from the `main` branch.

Please use the latest release version 1.12.3 and see if that works for you. If it doesn't, then feel free to open another issue, but please include sufficient information for somebody to investigate or reproduce, i.e. include error messages and log files.

**Comment by mook-as** [comment]
Additionally, if you want to be able to troubleshoot the underlying issue, please provide something we can work with.

Please try installing Rancher Desktop (whichever version) with logging enabled:
```powershell
msiexec /lv*x "C:\Path\To\Log\File.txt" /i "C:\Path\To\Rancher Desktop 1.234 Setup.msi"
```
And then upload the log file as an attachment to any new issues you create.
