### ISSUE TITLE
Always wrap calls to wsl in a try/catch block to show errors

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#658]
Often, an error message resulting from a call to `wsl` doesn't give enough information, as in `The system could not find the specified file`. 

If we at least emit the command with arguments when this happens, that will help troubleshoot problems, for both developers and support people.

**Comment by jandubois** [comment]
Same treatment is required for the `kubectl` calls (or really any subprocess created by RD).

**Comment by mook-as** [comment]
Note that we expect _some_ calls to fail, so this will be slightly more complicated than just blanket wrapping all calls.

**Comment by jandubois** [comment]
> Note that we expect _some_ calls to fail, so this will be slightly more complicated than just blanket wrapping all calls.

This ties in at least somewhat with #538, so even when the call is expected to fail, we may still want to see it in the log file, although potentially only in debug mode.
