### ISSUE TITLE
Rancher Desktop messes up config file on WSL

### ISSUE THREAD

**Issue by dozer75** [rancher-sandbox/rancher-desktop#6584]
### Actual Behavior

During startup the Rancher Desktop corrupts the ./kube/config file.

### Steps to Reproduce

- Have a config file with multiple configurations in a Ubuntu WSL
- Enable WSL integration against the Ubuntu WSL

### Result

The .kube/config file is corrupted which causes kubectl commands on the WSL to fail. 

### Expected Behavior

Ideally Rancher Desktop should not touch the config file unless WSL integration is enabled/disabled. If it is required to touch it, use `kubectl config set-XXX` commands instead of trying to edit it raw.

### Rancher Desktop Version

1.12.3

### Rancher Desktop K8s Version

1.28.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Enterprise 21H2 (19044.4046) with Ubuntu 22.04.3 LTS WSL2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by Nino-K** [comment]
@dozer75 we have done some work in https://github.com/rancher-sandbox/rancher-desktop/issues/6245 that should address this issue, the changes will be included in our upcoming release soon.

**Comment by dozer75** [comment]
> @dozer75 we have done some work in #6245 that should rectify this issue, the changes will be included in our upcoming release soon.

Thanks, but that states that you will go back to the symlink variant? It was like this earlier if I remember correctly, but back then it did a reset of the configuration in that config file from time to time as well which made me loose configuration back then as well... I hope that will be handled now then... 

I don't mind have it symlinked as long as it doesn't mess with non Rancher Desktop settings... Rancher Desktop should only affect its own config, not everything else in the config file no matter where it is.

**Comment by Nino-K** [comment]
The new approach does rely on symlink however it should not alter/remove your existing (non rancher-desktop) configuration. I'm going to close this issue, please give our next release a try and see if that addresses your issue. Feel free to reopen if you encounter anything else.
