### ISSUE TITLE
Please lower the needed WSL Kernel Version back to 5.4 because of second most commented WSL Bug

### ISSUE THREAD

**Issue by benzman81** [rancher-sandbox/rancher-desktop#6606]
### Actual Behavior

RD 1.13 now needs WSL Kernel Version >=5.15.

### Steps to Reproduce

None

### Result

Because of the second most commented Bug for WSL https://github.com/microsoft/WSL/issues/6982#issuecomment-1949892016 we are now no langer able to update RD as of its kernel restriction. The last known Kernel version for WSL not having problems with hibernate is 5.4.

### Expected Behavior

Maybe consider reverting the restriction to 5.15 for RD to just not support the features that required this restriction rather than not supporting lower versions at all.

### Rancher Desktop Version

1.13

### Rancher Desktop K8s Version

0.0.0

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by benzman81** [comment]
ah, thats a bummer. I don't think I can help with that. So I am stuck with 1.12.x, I guess.

**Comment by jandubois** [comment]
This has been addressed in the 1.13.1 release, which switches back to `iptables-legacy` when the kernel is too old.
