### ISSUE TITLE
Rancher Desktop will not start Win 11 - Error starting up: Error: Platform "win32" is not supported by RcFilePathManager Error: Platform "win32" is not supported by RcFilePathManager

### ISSUE THREAD

**Issue by aajnh** [rancher-sandbox/rancher-desktop#6656]
### Actual Behavior

Default installation provides an OS invalid configuration option that causes application start to fail fatally.  settings.json $.application.pathMangementStrategy is set to rcfiles which apparently is for Mac or Linux only, not Windows.  Tried "notset", however, this appears to no longer be supported.  Took a punt on a deleted file discussion and altered to "manual"; and the UI then opened.

### Steps to Reproduce

Fresh install of Rancher v 1.13.1 using the downloaded msi
From the start menu selected Rancher Desktop
Nothing opened.
Checked the %APPDATA$\rancher-desktop\logs\background.log and the following is reported (following is total contents of file)
`2024-03-28T01:19:52.607Z: A second instance was started
2024-03-28T01:19:53.699Z: Error starting up: Error: Platform "win32" is not supported by RcFilePathManager Error: Platform "win32" is not supported by RcFilePathManager
    at new Zi (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:41:71876)
    at C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:41:133670
    at Wo (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:41:133729)
    at C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:41:147047
`

Tried rebooting a couple of times too just in case; but that did not solve the issue.

### Result

Rancher Desktop UI will not open

### Expected Behavior

Rancher Desktop UI opens.

### Additional Information

default for Windows should be "manual"

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

Not sure - cannot open

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 23H2 Build 22631.3296

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

Not connected to VPN

**Comment by gunamata** [comment]
Are you running on  a 32 bit machine? if yes, Please note that Rancher Desktop is not built for 32 bit machines. Please try on a 64-bit machine.

**Comment by jandubois** [comment]
> default for Windows should be "manual"

It is already `manual`: https://github.com/rancher-sandbox/rancher-desktop/blob/375ae3fef4539a8881253ce9b579ed9956b4f41a/pkg/rancher-desktop/config/settings.ts#L72

There should be no mechanism on Windows to change the setting to `rcfiles`: it is not settable from the UI nor the CLI:

```console
PS C:\Users\SUSE> rdctl set --application.path-management-strategy rcfiles
Error: option --application.path-management-strategy is not available on Windows
```

The only thing I can think of is if you manually edit `settings.json`, or install a settings file from macOS or Linux.

There isn't really anything we can do unless we get instructions on how to reproduce the issue, so I'm going to close it for now. Feel free to re-open and add additional details if you find a way to reproduce the problem.
