### ISSUE TITLE
network tunnel feature on causes delay with php xdebug client_host = wsl2 IP

### ISSUE THREAD

**Issue by fiburonsk** [rancher-sandbox/rancher-desktop#6689]
### Actual Behavior

I do symfony php development.  In development i use xdebug to step through my application.  When I use the legacy networking (network tunnel = false) I have web page response times of less than 100ms when xdebug is enabled.  When I enable the rancher desktop network tunnel feature the responses take about 4 seconds.

### Steps to Reproduce

In a working php app with xdebug enabled and configured to listen on the wsl2 IP, toggle the rancher desktop network tunnel feature on.

Alternatively with the network tunnel feature already enabled in a php app where xdebug is not enabled.  then enable xdebug and in the xdebug config have it listen on the wsl2 IP for the xdebug.client_host value and redeploy in kubernetes.

### Result

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/10441670/f4986796-3091-4864-9ebd-37caab71df68)

this is a screenshot of the edge network panel in dev tools.  I simply turned on the network tunnel feature and waited for rancher desktop to restart.  xdebug is enabled and listening on the wsl2 IP.

### Expected Behavior

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/10441670/201ba94c-edcb-467b-9466-2c21767668c8)

In this screenshot network tunnel is off.  My expectation would be that the response is close to the same level of performance.

### Additional Information

In testing i've identified this slowness only happens when the following conditions are met
1. xdebug.client_host={wsl2_ip} and xdebug.start_with_request=yes
2. nothing is acitvely listening on the xdebug port
3. rancher desktop network tunnel feature is enabled. 

VS Code runs inside a wsl2 distro via the remote wsl extension.  When I need to debug I enable debugging and VS Code starts listening on my configured xdebug port, the default is 9003.  My pod has xdebug configured to connect to {wsl2ip}:9003 to connect with VS Code.
  
In the scenario that rancher desktop network tunneling is enabled and VS Code is not listening I suspect that the xdebug requests are going into the rancher desktop network tunnel where it takes a few seconds for them to timeout before my response can be finished and returned to my browser.  I've tested this with several different versions of rancher desktop with the same outcome [1.10, 1.11, 1.12, 1.13].  

This is not an issue with `"networkingTunnel": false`

Let me know if I can collect or provide any more detail to help, Thanks!

### Rancher Desktop Version

1.13.0

### Rancher Desktop K8s Version

1.28.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 11 pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by fiburonsk** [comment]
i've learned that this becomes more apparent when developing for Symfony >= 6.4 (current version is 7.0.6) and `networkingTunnel=true`.  I had a legacy Symfony 6.3 app where a delay was less noticeable factoring in the general symfony overhead with `networkingTunnel = true`.  After upgrading the app to symfony 6.4 LTS with `networkingTunnel=true` requests and cli commands started taking ~4 seconds.  Changing `networkingTunnel=false` made my symfony >= 6.4 requests less than 100ms as demonstrated in the initial report.  The initial report testing was using Symfony 7.0.6.

I also tested with a simple index.php script `<?php phpinfo();` running in a deployment on nginx and php 8.3.  This responds quickly but there is still a noticeable difference in timing, with `networkingTunnel=false` i see page load speeds at ~10ms.  When I turn `networkingTunnel=true` this jumps to ~275ms.  When I turn on my VS Code debugger to listen on port 9003 then the ~275ms drops down to about ~25ms.

It appears that Symfony >= 6.4 is exacerbating the issue but there may still be something here for `networkingTunnel=true`.

I also don't know if there is some inherent overhead from the networkingTunnel=true that should be taken into account.

I Hope this can be of some help.  Thanks!

**Comment by Nino-K** [comment]
@fiburonsk, I haven't been able to reproduce the issue you're experiencing with Symfony. Although I didn't have the exact same setup and environment as you do, I conducted various network latency tests along a standard network path and captured the results with a metric emitter in my application. I performed these tests for both legacy and network tunnel configurations, and there were no significant outliers in the results.

I'd also like to clarify whether you're using a VPN. I assume not, as Rancher Desktop wouldn't function properly with the network tunnel option disabled behind a VPN. However, it would be helpful if you could confirm this.

At this point, I suspect that the latency you're observing may be related to your specific setup or other tools that could be interfering with network requests.
