### ISSUE TITLE
Epic: Support the docker-cli to build and run container images

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#673]
This will require the following pieces

* [x] #808
* [x] #809
* [x] #810
* [x] #869
* [x] #900 
* [x] #811
  * [X] Handle volumes & other file paths (@jandubois believes this works automatically, as long as directories are mounted)
* [x] #812
  * [x] Handle volumes & other file paths
* [x] #814
* [x] #901
* [x] #939 - depends on 814
* [x] #950
  * [x] #1011

**Comment by mook-as** [comment]
Note that we'll also need to figure out what to do with volume mounts, because they're on different machines.

It's unclear if this task is supposed to cover Windows — that would include cross-distro volume mounts, which is More Fun.

**Comment by jandubois** [comment]
> It's unclear if this task is supposed to cover Windows — that would include cross-distro volume mounts, which is More Fun.

Yes, it was supposed to cover Windows as well (that's why I didn't put the `macOS` label on it). And yes, we probably need to add a bunch more tasks to the checklist; this issue is supposed to be the umbrella bug to tie them all together.

**Comment by mook-as** [comment]
Adjusted the checklist to make it more explicit that Windows _is_ covered.

**Comment by mook-as** [comment]
Removed #910 from the list because we won't need it for the first go (we'll just clobber the docker socket as appropriate).

**Comment by gaktive** [comment]
At this stage, the main feature work on this is done. 

I'll close this, so bugs discovered around this will exist as new and likely separate tickets.

**Comment by xaocon** [comment]
Sorry to bump a closed issue but I'm just curious what the impetus was for this? Was nerdctl not a good replacement for docker in all cases?

**Comment by jandubois** [comment]
> Was nerdctl not a good replacement for docker in all cases?

Yes, there are various features that are still unimplemented in `nerdctl`. I did a test of using `alias docker=nerdctl` and then trying to build various Github projects that use `docker build` in their `Makefile`. The `nerdctl` alias failed in more than 50% of the cases (very unscientific sampling, but still).

Of course the long term goal is to improve `nerdctl` to get feature-parity as much as possible, but it seemed not achievable in the short term.

Furthermore, some projects only work with the `dockerd` API and not with `containerd`. For us the most important one is [k3d](https://k3d.io). We could only get it to work with Rancher Desktop if we at least optionally support using `dockerd` instead of `containerd`.
