### ISSUE TITLE
The "Restored SNAPSHOT" banner gets updated unexpectedly

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#6733]
### Actual Behavior

I restored snapshot X. With the main window unactivated, I saw that the snapshot was restored at 10:53. But a minute later when I activated the window, the caption was updated to show it was restored at 10:54.

### Steps to Reproduce

Restore a snapshot. Click on another app so the RD main window is lower in the Z-order.

Take note when the snapshot is finally restored. 

Then a few minutes later click on the RD main window -- the restoration time gets updated.

### Result

See above

### Expected Behavior

See above

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

12.6.1

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by ericpromislow** [comment]
And a minute later:

![Screen Shot 2024-04-19 at 10 53 08 AM](https://github.com/rancher-sandbox/rancher-desktop/assets/108392/242fb44c-e3d7-4b89-9ca8-4999e91ead3c)

**Comment by VikalpRusia** [comment]
Even if you don't change screen it gets changed

It is not related to restore event alone it is related to all events
