### ISSUE TITLE
Please update to docker compose 2.25.0 to prevent service "" can't be used with `extends` as it declare `depends_on`

### ISSUE THREAD

**Issue by malylemireflo** [rancher-sandbox/rancher-desktop#6759]
### Actual Behavior

See https://github.com/docker/compose/issues/11544
Should be fixed in 2.25.0

### Steps to Reproduce

See https://github.com/docker/compose/issues/11544

### Result

See https://github.com/docker/compose/issues/11544

### Expected Behavior

See https://github.com/docker/compose/issues/11544

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

1.27.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> Please update to docker compose 2.25.0

We (almost) always update dependencies to their latest version for each "minor" release, i.e. we did update them for `1.13.0`, but not for `1.13.1`.

We have already bumped `docker-compose` to at least `2.26.1` for whenever `1.14.0` is going to be released, so I'm going to close this issue: https://github.com/rancher-sandbox/rancher-desktop/blob/eba9527abbea990030a82ebb7f9835426375c0f6/pkg/rancher-desktop/assets/dependencies.yaml#L11
