### ISSUE TITLE
UDP port forwarding not working on Windows with network tunnel enabled

### ISSUE THREAD

**Issue by segevfiner** [rancher-sandbox/rancher-desktop#6821]
### Actual Behavior

With the network tunnel enabled host-switch listens for TCP even when exposing a UDP port from a container. Without it enabled `wslrelay.exe` doesn't listen at all on UDP ports.

### Steps to Reproduce

Any container with `-p 1234:1234/udp`

### Result

host-switch listens for TCP on the exposed port instead of UDP.

### Expected Behavior

It should listen and forward UDP correctly.

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

1.29.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 10.0.22631

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

N/A

**Comment by Nino-K** [comment]
The UDP is not supported currently, however, this is something that I will look into after our current release since I know that the upstream [library](https://github.com/containers/gvisor-tap-vsock) that we are using may have done some work to support this.

**Comment by segevfiner** [comment]
P.S. I also tried WSL mirrored networking mode, but Rancher Desktop won't start in that mode https://github.com/rancher-sandbox/rancher-desktop/issues/6665

**Comment by AndreKR** [comment]
Is this why `-p 1234:1234/udp` doesn't work when using Rancher Desktop? The port is not reachable. I don't understand what "the network tunnel enabled host-switch" is. Do I have to enable or disable it for UDP ports to work? And where do I enable/disable it?

**Comment by stampycode** [comment]
Since switching to v1.15 the legacy networking mode in Rancher Desktop for Windows (which worked for UDP streams) is no longer available, so we are now unable to upgrade to any version beyond v1.14 until UDP forwarding is fixed.

**Comment by rcastagno** [comment]
+1
Finding that the only feature making this work has been removed before fixing the problem is frustrating.

**Comment by VitaliiTrubchaninovUbisoft** [comment]
This issue makes Rancher Desktop unusable for UDP only applications. Previously we would use internal IP of the WSL instance to communicate with server running in docker container over UDP, but now even that is not available. We had to go back to raw docker installation in WSL. Please consider implementing UDP support sooner than later.
