### ISSUE TITLE
Error starting Kubernetes during CA Certificate installation

### ISSUE THREAD

**Issue by srrich** [rancher-sandbox/rancher-desktop#6839]
### Actual Behavior

On startup of an existing OR fresh installation of Rancher Desktop, there is an error attempting to `rmdir` directories within the path: `C:\Users\srich\AppData\Local\Temp\rd-distro-*`.

This error occurs during the installation of CA Certificates stage. This causes a complete failure of startup of the Kubernetes engine rendering Rancher Desktop completely inoperable. 

Resetting the Kubernetes cluster OR Factory Resetting the application within the `Troubleshooting` section does not change the error behavior rendering Rancher Desktop unusable. 

This seems to stem from a prior issue reported under: https://github.com/rancher-sandbox/rancher-desktop/issues/1919

### Steps to Reproduce

- Fresh install Rancher Desktop
- Select desired Kubernetes version: v1.29.4 (stable, latest)
- Select Container Engine: error occurs with either `containerd` OR `dockerd (moby)`
- Upon download of all K3S resources, "Starting WSL Environment" will show in the bottom-right status log of the `main window`. During this sequence, an error window will appear showing an error during installation, highlighting an error in **Installing CA Certificates**

### Error on initial/fresh installation after uninstalling Rancher Desktop from Windows

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\srich\AppData\Local\Temp\rd-distro-T8lUsM'

2024-05-07T15:36:29.981Z: Registered distributions: 
2024-05-07T15:36:30.091Z: Registered distributions: 
2024-05-07T15:36:37.939Z: Registered distributions: rancher-desktop
2024-05-07T15:36:38.166Z: Registered distributions: rancher-desktop
2024-05-07T15:36:38.166Z: Creating initial data distribution...

### Error after enacting Troubleshooting->Reset Kubernetes

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\srich\AppData\Local\Temp\rd-ca-FV5YRP'

_**Context:
Installing CA certificates**_

2024-05-07T15:46:59.833Z: Running: wsl.exe --distribution rancher-desktop --exec /sbin/rc-update add host-resolver default
2024-05-07T15:46:59.875Z: Running: wsl.exe --distribution rancher-desktop --exec busybox cp /mnt/c/Users/srich/AppData/Local/Temp/rd-moproxy-eWvXCd/moproxy /etc/init.d/moproxy
2024-05-07T15:46:59.926Z: Running: wsl.exe --distribution rancher-desktop --exec touch /var/lib/rancher/k3s/server/manifests/runtimes.yaml.skip
2024-05-07T15:46:59.954Z: Running: wsl.exe --distribution rancher-desktop --exec busybox chmod 644 /etc/containerd/config.toml
2024-05-07T15:46:59.968Z: Running: wsl.exe --distribution rancher-desktop --exec busybox chmod 644 /usr/local/openresty/nginx/conf/resolver.conf
2024-05-07T15:46:59.989Z: Running: wsl.exe --distribution rancher-desktop --exec mkdir -p /etc/cni/net.d
2024-05-07T15:47:00.040Z: Running: wsl.exe --distribution rancher-desktop --exec busybox cp /mnt/c/Users/srich/AppData/Local/Temp/rd-vtunnel-peer-zmvP57/vtunnel-peer /etc/conf.d/vtunnel-peer
2024-05-07T15:47:00.059Z: Running: wsl.exe --distribution rancher-desktop --exec /sbin/rc-update add dnsmasq default
2024-05-07T15:47:00.065Z: Running: wsl.exe --distribution rancher-desktop --exec busybox chmod 755 /etc/init.d/moproxy

### Expected Behavior

Rancher Desktop installs all relevant K8S components, initializes WSL (if applicable) and starts the Kubernetes engine successfully.

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

1.29.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

AntiVirus: CylancePROTECT

**Comment by srrich** [comment]
@mook-as In your investigation of this issue, I'll add anecdotally that I was able to get around this problem by navigating to the directory in question where the failures are occurring: `C:\Users\srich\AppData\Local\Temp\`. I then deleted all directories beginning with the pattern `rd-*`, assuming they were associated with `Rancher Desktop`. 

After deleting all perceived relevant directories within `C:\Users\srich\AppData\Local\Temp\`, I restarted the `Rancher Desktop` application and the CA Cert files "seem" to be installed properly as no errors are thrown and the Kubernetes engine successfully starts. 

This all seems to be a race condition within `AppData/temp` directory cleanup; similar to the earlier reported problem under https://github.com/rancher-sandbox/rancher-desktop/issues/1919. It seems the original fix under https://github.com/rancher-sandbox/rancher-desktop/issues/1919 might need to be revisited.

**Comment by mook-as** [comment]
Thanks for filing the issue! I'm going to tentatively assume the error is because your anti-virus is still checking all the files to see if there are issues, so we failed to delete something. I'll go add a delay/retry to see if that helps.  Since we generate a new directory with a random name every time, any existing ones don't matter.

**Comment by srrich** [comment]
> Thanks for filing the issue! I'm going to tentatively assume the error is because your anti-virus is still checking all the files to see if there are issues, so we failed to delete something. I'll go add a delay/retry to see if that helps. Since we generate a new directory with a random name every time, any existing ones don't matter.

Our CylancePROTECT window is not throwing an AV findings for those files or directories. Previously it would quarantine some of the Rancher Desktop binaries but I have whitelisted those in our AV configuration. As of now, I can confirm any of the remaining AV findings are NOT RancherDesktop related. (Git was flagged, some HotKey32.exe was also flagged but none that are related to Rancher Desktop) 

This truly looks like a race condition of the installer attempting to delete directories while CA Certificate installation is ongoing more than anything. I only included that we have CylancePROTECT as our AV in case it may have been the culprit (and because it's in your ticket template) but I can confirm Cylance is not quarantining files causing the above issue.

**Comment by mook-as** [comment]
Yeah, I wasn't expecting it to be quarantined; but I know that MS Defender, at least, can hold the files open (for reading, to scan them) so files that we create and immediately delete again can have issues on delete.

**Comment by srrich** [comment]
@mook-as With this issue hopefully mitigated in your  #6843 PR that's now incorporated for milestone 1.14....is there any way for us to gain pre-release access to a 1.14-ReleaseCandidate build to verify your fix mitigated the antivirus lock issue on those directories during the `rmdir` execution? I am personally encountering this issue more frequently on my local v1.13.1 installation with it stagnating k8s development while I attempt to circumvent the problem until it magically goes away allowing my k8s cluster to stand up happily

**Comment by jandubois** [comment]
You can download the latest CI build by browsing the GitHub actions for this repo. Filter for branch `main` and workflow `package`: https://github.com/rancher-sandbox/rancher-desktop/actions?query=branch%3Amain&workflow=package

Click on that latest successful[^1] run and download the MSI from the "Summary" part of the page (you need to scroll down the right hand side of the page).

[^1]: The `main` builds should all be successful, but sometimes the "Test Windows Signing" step fails.

You need to be logged into GitHub to be able to download the assets.

Note that the CI builds are **not** signed by SUSE, as GitHub doesn't have access to our signing keys. Only the release builds will be signed by a separate system.
