### ISSUE TITLE
After restart rancher desktop, the local-path-config will be restored

### ISSUE THREAD

**Issue by flyeric0212** [rancher-sandbox/rancher-desktop#6917]
### Actual Behavior

After restart rancher desktop, the local-path-config will be restored

### Steps to Reproduce

<img width="1572" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/9649106/7089bcd0-63dd-482e-8eb5-3c0eb0a09419">

I changed the paths field。

### Result

After restart rancher desktop, the local-path-config will be restored.
<img width="900" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/9649106/8e4954c4-d8cf-4446-a7ad-22742d0a9d3d">
### 

### Expected Behavior

Do not be restored.

### Rancher Desktop Version

1.12.3

### Rancher Desktop K8s Version

1.26.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Sonoma 14.5

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> After restart rancher desktop, the local-path-config will be restored.

This happens because `k3s` will re-apply the `local-storage.yaml` manifest on each restart, removing your settings. And you can't edit the manifest either (I tried), as it gets re-extracted from the bundled manifests each time.

The best workaround is to tell `k3s` to stop applying the manifest:

```console
$ rdctl shell sudo touch /var/lib/rancher/k3s/server/manifests/local-storage.yaml.skip
```
