### ISSUE TITLE
Refresh button on Rancher Desktop Containers view

### ISSUE THREAD

**Issue by mark1566** [rancher-sandbox/rancher-desktop#6939]
### Problem Description

Current Version: 1.13.1

When displaying containers the status changes after actions it would be nice to have a 'refresh' button which would force a change in view of current containers on that display. Accepting that my machine may be a little slow we should not always assume that the device that Rancher Desktop is running on is always as performance as we might like.

### Proposed Solution

Adding a simple 'Refresh' icon on this screen maybe to the left of the filter box would allow users to refresh as and when they wanted.

**Comment by jandubois** [comment]
We already have #5775, about the display not automatically refreshing. It should work the same as the Images tab.

I don't think we want to add an explicit refresh button, so I'm closing this as a duplicate of #5775.
