### ISSUE TITLE
Kubernetes 1.16/1.17 do not start on Windows

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#6962]
### Actual Behavior

If Kubernetes version is 1.16.x or 1.17.x, Kubernetes does not start.  This happens for both moby and containerd.

![Kubernetes Error dialog box screenshot](https://github.com/rancher-sandbox/rancher-desktop/assets/3977982/780a4d47-5382-41ae-8fc5-a14f07faaae9)

(See below for logs, but they're not very useful.)

### Steps to Reproduce

1. Start Rancher Desktop
2. Select either 1.16.x or 1.17.x for Kubernetes version

### Result

[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491214/background.log)
[commandLine.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491215/commandLine.log)
[dashboardServer.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491216/dashboardServer.log)
[deploymentProfile.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491217/deploymentProfile.log)
[diagnostics.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491218/diagnostics.log)
[extensions.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491219/extensions.log)
[host-switch.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491220/host-switch.log)
[images.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491221/images.log)
[integrations.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491222/integrations.log)
[k3s.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491223/k3s.log)
[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491224/k8s.log)
[kube.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491225/kube.log)
[lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491226/lima.log)
[moby.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491227/moby.log)
[mock.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491228/mock.log)
[nerdctl.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491229/nerdctl.log)
[network-setup.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491230/network-setup.log)
[networking-ca.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491231/networking-ca.log)
[networking.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491232/networking.log)
[protocol-handler.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491233/protocol-handler.log)
[rancher-desktop-guestagent.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491234/rancher-desktop-guestagent.log)
[server.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491235/server.log)
[settings.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491236/settings.log)
[shortcuts.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491237/shortcuts.log)
[snapshots.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491238/snapshots.log)
[steve.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491239/steve.log)
[update.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491240/update.log)
[vm-switch.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491241/vm-switch.log)
[window_browser.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491242/window_browser.log)
[wsl-exec.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491243/wsl-exec.log)
[wsl-init.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491244/wsl-init.log)
[wsl-version.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491245/wsl-version.log)
[wsl.log](https://github.com/rancher-sandbox/rancher-desktop/files/15491246/wsl.log)

### Expected Behavior

Kubernetes should start up correctly.

### Additional Information

1.18.x starts fine.

This appears to work on macOS.

### Rancher Desktop Version

1.13.1-521-g9abed793

### Rancher Desktop K8s Version

1.17.17

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 23H2 (Build 22631.3593)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
We will most likely drop support for any Kubernetes version older than 1.21.0 in Rancher Desktop 1.15.0, so we are not going to spend any effort into fixing this.

**Comment by jandubois** [comment]
> We will most likely drop support for any Kubernetes version older than 1.21.0 in Rancher Desktop 1.15.0, so we are not going to spend any effort into fixing this.

This ^^^

Ref #980
