### ISSUE TITLE
Actions performed in Cluster Dashboard's `Workloads > Pods` screen do not immediately reflect

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#6968]
### Actual Behavior

When you perform an action in the Cluster Dashboard's `Workloads > Pods`, the expected outcome of the action doesn't reflect in the dashboard UI immediately. You need to close the cluster dashboard and reopen to see the change.

### Steps to Reproduce

- Create a sample deployment

`kubectl create deployment nginx-test --image=nginx --port=80`

- Go to the Cluster Dashboard's `Workloads > Pods` screen. 
- Delete the the nginx pod 

### Result

You don't see any changes to the pod item in the table. If you close and reopen the dashboard, you will see that a new pod is spun up. This behavior was working as expected in 1.13

### Expected Behavior

You should immediately see the pod terminating and a new pod starting in the table

### Rancher Desktop Version

1.14

### Rancher Desktop K8s Version

1.29.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Fixed by #6983
