### ISSUE TITLE
open-webui container not able to connect to the service running on the host machine

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#6987]
### Actual Behavior

[open-webui](https://docs.openwebui.com/) container not able to connect to the service running on the host machine

### Steps to Reproduce

- [Download and Install ollama](https://ollama.com/download) on the host machine
- After installing ollama, pull a LLM model, for example, `ollama pull moondream`
- Run the open-webui container

```
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui -e WEBUI_AUTH=False --restart always ghcr.io/open-webui/open-webui:main
```

- Browse to http://localhost:3000 . This should bring up the open-webui interface. 
- In web UI, on the top left corner, expand the model selector dropdown. You should see the moondream model that you pulled above

### Result

The open-webui container is not able to access the ollama service (running on port 11434) running on the host machine. I tried host.docker.internal as well but with no luck!

### Expected Behavior

The open-webui container should be able to access the ollama service running on the host machine

### Additional Information

I have Networking tunnel enabled.

### Rancher Desktop Version

1.14

### Rancher Desktop K8s Version

1.29.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by gunamata** [comment]
Removing `--add-host=host.docker.internal:host-gateway` in the command solves the problem. I am not sure if it's the flag `--add-host` or the value passed that's problematic. Any thoughts @Nino-K ?

**Comment by Nino-K** [comment]
I believe the `host-gateway` is specific to the docker desktop, so removing the flag simply works. If you replace the host-gateway with the internal IP address of the host machine, that should solve the problem.

**Comment by jandubois** [comment]
We should see if we can add support for it. There are other open issues referencing `gateway.docker.internal` that I think will have the same root issue.

**Comment by jj-quantumdrones** [comment]
I just ran into this issue myself, I am running ollama and rancher desktop on windows, open web ui was not able to find my models.

I ran `docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main` and this solved the issue.

**Comment by Nino-K** [comment]
Going to close this issue in favor of: https://github.com/rancher-sandbox/rancher-desktop/issues/6987
