### ISSUE TITLE
[Feature Bug] Images does not  load after reset k8s and containers

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#700]
## Summary

What happened/what you expected to happen?

**Issue found**
After reset k8s and container images through `Kubernetes Settings -> Reset Kubernetes -> Reset k8s and containers`, the images does not load properly, keep stuck on: `Waiting for image manager to be ready`

**Expected behaviour**
* Reset k8s and containers be able to reload the image list.

What version of Rancher Desktop are you running?

* `V0.5.0`

What version of Kubernetes are you running?

* `v1.21.5`

Which OS version?

* `macOS 11.6 (20G165) - BigSur / Darwin 20.6.0`

## How to replicate
1. Pull a new image through `Pull image` feature (I've selected `nginx:latest`)
2. Start the new image using `nerdctl run -it --rm nginx`
3. On RD Kubernetes Settings, select `Reset k8s -> Reset k8s and Container images`
4. It should stop `nginx` execution and delete all images/containers
5. Navigate to RD and click on `Images` tab.
6. You should see the msg `Waiting for image manager to be ready`
7. The image list won't shows up :( 

## Diagnostics

During the manual testing process, the test case P0 #10 behaves quite different than expected, not showing the image list after reset k8s and container images.
Even though the  `daemonset.apps/builder` seems to be healthy, the images does not load properly.

`kubectl get all -A`
```bash
NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE
kube-system   pod/metrics-server-86cbb8457f-xdhrh           1/1     Running     0          12m
kube-system   pod/coredns-7448499f4d-cg4sd                  1/1     Running     0          12m
kube-system   pod/local-path-provisioner-5ff76fc89d-wnr66   1/1     Running     0          12m
kube-system   pod/helm-install-traefik-crd-64c5x            0/1     Completed   0          12m
kube-image    pod/builder-dz8hl                             2/2     Running     0          12m
kube-system   pod/helm-install-traefik-pks84                0/1     Completed   1          12m
kube-system   pod/svclb-traefik-vqmcb                       2/2     Running     0          12m
kube-system   pod/traefik-97b44b794-gc76r                   1/1     Running     0          12m

NAMESPACE     NAME                     TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                         AGE
default       service/kubernetes       ClusterIP      10.43.0.1      <none>         443/TCP                         12m
kube-system   service/kube-dns         ClusterIP      10.43.0.10     <none>         53/UDP,53/TCP,9153/TCP          12m
kube-system   service/metrics-server   ClusterIP      10.43.93.54    <none>         443/TCP                         12m
kube-image    service/builder          NodePort       10.43.80.2     <none>         1234:30438/TCP,1233:31601/TCP   12m
kube-system   service/traefik          LoadBalancer   10.43.98.243   192.168.5.15   80:30209/TCP,443:31913/TCP      12m

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                          AGE
kube-image    daemonset.apps/builder         1         1         1       1            1           node-role.kubernetes.io/builder=true   12m
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>                                 12m

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/metrics-server           1/1     1            1           12m
kube-system   deployment.apps/coredns                  1/1     1            1           12m
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           12m
kube-system   deployment.apps/traefik                  1/1     1            1           12m

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/metrics-server-86cbb8457f           1         1         1       12m
kube-system   replicaset.apps/coredns-7448499f4d                  1         1         1       12m
kube-system   replicaset.apps/local-path-provisioner-5ff76fc89d   1         1         1       12m
kube-system   replicaset.apps/traefik-97b44b794                   1         1         1       12m

NAMESPACE     NAME                                 COMPLETIONS   DURATION   AGE
kube-system   job.batch/helm-install-traefik-crd   1/1           25s        12m
kube-system   job.batch/helm-install-traefik       1/1           27s        12m
``` 

*Image and logs after reset k8s+containers*
![Screen Shot 2021-09-28 at 11 52 13 AM](https://user-images.githubusercontent.com/37411123/135142269-ed2e2bb7-d55f-45b1-9974-82a2e7b94f30.png)
[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/7246432/k8s.log)
[kim.log](https://github.com/rancher-sandbox/rancher-desktop/files/7246433/kim.log)

The issue was fixed manually closing the RD app and starting again:
![Screen Shot 2021-09-28 at 12 17 37 PM](https://user-images.githubusercontent.com/37411123/135143282-389b6703-b639-414c-b718-8bb74dc0d64c.png)
[kim_manual.log](https://github.com/rancher-sandbox/rancher-desktop/files/7246483/kim_manual.log)
[k8s_manual.log](https://github.com/rancher-sandbox/rancher-desktop/files/7246486/k8s_manual.log)

**Comment by mattfarina** [comment]
The issues experienced here are due to Kim. In the next release of RD we plan to move away from kim for the generation of this screen. That should fix the issue.

**Comment by gaktive** [comment]
We've moved away from Kim now so this should no longer be a problem. We've not heard any reports since so closing.
