### ISSUE TITLE
Support ~/.docker/config.json#credsHelpers for amazon-ecr-credential-helper

### ISSUE THREAD

**Issue by bestickley** [rancher-sandbox/rancher-desktop#7047]
### Problem Description

I want to use my AWS_PROFILE env var with saved AWS credentials (~/.aws/credentials) to authenticate to ECR for certain repositories and other credential helpers for other repositories. This requires support for `credHelpers` which based on my testing is not implemented for Rancher Desktop. See example:

```json
{
	"credHelpers": {
		"<aws_account_id>.dkr.ecr.<region>.amazonaws.com/repo1": "ecr-login",
		"<aws_account_id>.dkr.ecr.<region>.amazonaws.com/repo2": "osxkeychain"
	}
}
```

### Proposed Solution

Supports `credHelpers`

### Additional Information

https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by jandubois** [comment]
I believe Rancher Desktop supports `credHelpers` and even ships with the `ecr-login` helper:

```console
$ ls ~/.rd/bin/
docker                        docker-credential-ecr-login   helm                          nerdctl
docker-buildx                 docker-credential-none        kubectl                       rdctl
docker-compose                docker-credential-osxkeychain kuberlr                       spin
```

I know I tested it in the past, but only by specifying credentials directly:

```
AWS_ACCESS_KEY_ID=… AWS_SECRET_ACCESS_KEY=… docker push …
```

There should be logs in `~/.ecr/log/ecr-login.log`.

Are you using `docker` or `nerdctl`? In the latter case, you would have to make sure that your `AWS_PROFILE` variable is visible to the Rancher Desktop app, which is started by `launchd` on behalf of `Finder.app`, so doesn't have access to your environment variables.

You could set it globally in your `launchd` configuration with

```
launchctl setenv AWS_PROFILE …
```

Make sure to only use absolute filenames. You can remove it again via

```
launchctl unsetenv AWS_PROFILE
```

Looking at my old notes again (they are from June 2022), I do see that I created a symlink to the credentials inside the VM too, I don't know if this would still be necessary:

```console
lima-rancher-desktop:~# ls -l /root/.aws
total 0
lrwxrwxrwx    1 root     root            27 Jan 25 22:04 credentials -> /Users/jan/.aws/credentials
```

I don't have ECR credentials right now to test again.

But all this should not be necessary if you are using `docker`, so please let us know exactly what your setup is, how things fail, and if you get anything in the `~/.ecr/log/ecr-login.log`.

**Comment by bestickley** [comment]
I'm using docker.

With ~/.docker/config.json like:
```json
{
	"auths": {
		"121668792265.dkr.ecr.us-gov-east-1.amazonaws.com": {}
	},
	"credsStore": "osxkeychain",
	"currentContext": "rancher-desktop"
}
```
I can run `aws ecr get-login-password | docker login --username AWS --password-stdin \"$AWS_ACCOUNT_GLOBAL_DEV.dkr.ecr.$AWS_REGION.amazonaws.com\" && ash --oci-runner docker --no-build` successfully when I have AWS_PROFILE set with valid creds.

But then I change ~/.docker/config.json to:
```json
{
  "auths": {
    "121668792265.dkr.ecr.us-gov-east-1.amazonaws.com": {}
  },
  "credHelpers": {
    "121668792265.dkr.ecr.us-gov-east-1.amazonaws.com": "osxkeychain",
    "121668792265.dkr.ecr.us-gov-east-1.amazonaws.com/ash": "ecr-login"
  },
  "currentContext": "rancher-desktop"
}
```

Note, the "auths" key is added automatically.

~~The above command does not work.~~
UPDATE: this works now... sorry to bother! Thank you :)

**Comment by bestickley** [comment]
FYI, my use case is wanted to authenticate to ECR automatically with AWS_PROFILE for everything EXCEPT when I use AWS CDK because AWS CDK always uses `aws ecr get-login` command (no way to customize)

**Comment by jandubois** [comment]
Thanks for the update! In the `docker` case, everything is really being handled by the upstream CLI, so it doesn't depend on Rancher Desktop. It is different for containerd/nerdctl, where the tool actually runs inside the VM and needs to contact a credential server on the host to get access to the credentials.
