### ISSUE TITLE
Error resetting Kubernetes cluster after kubeconfig was deleted

### ISSUE THREAD

**Issue by bashofmann** [rancher-sandbox/rancher-desktop#705]
* Start Rancher Desktop and wait until the Kubernetes cluster was created
* Delete `~/.kube/config`
* To recreate the config, I'd expect that I can reset the Kubernetes cluster. Click the "Reset Kubernetes" button
* The following error is shown and no new kubeconfig is generated

<img width="937" alt="Bildschirmfoto 2021-09-29 um 17 03 33" src="https://user-images.githubusercontent.com/243056/135296633-31da10dc-1c36-4041-867f-790d2450683c.png">

When you completely stop and the start Rancher Desktop again, a new kubeconfig is generated. This logic should also be executed when you reset the Kubernetes cluster while Rancher Desktop is running.

Tested with 0.5.0 on MacOS Big Sur.

**Comment by mattfarina** [comment]
@bashofmann Thanks for catching this bug.

I've added it to the 0.6 release. We might be able to get it in for that. If not, a fix should come in the 0.7 release.
