### ISSUE TITLE
daemon.json is reset on every start of RancherDesktop

### ISSUE THREAD

**Issue by jhollmannk** [rancher-sandbox/rancher-desktop#7063]
### Actual Behavior

RancherDesktop resets the /etc/docker/daemon.json in the rancher-desktop WSL-VM on every startup.

In previous versions the file was kept unchanged on startup and only got replaced with a new version or with a factory reset. That was not ideal but at least it was manageable.

We need to configure `default-address-pools` and `registry-mirrors` in our company so that the ip-addresses don't clash with our VPN and we do not run into download rate limits.

### Steps to Reproduce

Edit the file with
`wsl -d rancher-desktop vi /etc/docker/daemon.json`
and add a setting like `default-address-pools` or `registry-mirrors`:
```
{
  "features": {
    "containerd-snapshotter": false
  }
  "default-address-pools": [
    {
      "base": "10.189.0.0/16",
      "size": 24
    }
  ]
}
```
Start RancherDesktop

### Result

The file is reset to a standard
```
{
  "features": {
    "containerd-snapshotter": false
  }
}
```

You can check that with
`wsl -d rancher-desktop cat /etc/docker/daemon.json`

### Expected Behavior

The file should at least be unaltered on a normal startup.

There already is the issue #4832 which has been on triage for the next version for a year. Would be nice to have that, which would also solve this problem (even better). But please at least give us back the old behaviour where we only had to correct the daemon.json with every new version.

### Rancher Desktop Version

1.14.1

### Rancher Desktop K8s Version

1.25.9

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> Edit the file with `wsl -d rancher-desktop vi /etc/docker/daemon.json` and add a setting like `default-address-pools` or `registry-mirrors`:

Side-note: You should use `rdctl shell` instead of `wsl -d rancher-desktop` to run commands inside the distro. The latter command does not switch to the correct pid namespace, which doesn't matter for many commands, but will have an effect if you interact with any of the services managed by the init process.

> ```
> {
>   "features": {
>     "containerd-snapshotter": false
>   }
>   "default-address-pools": [
>     {
>       "base": "10.189.0.0/16",
>       "size": 24
>     }
>   ]
> }
> ```

The problem here is that your edit results in invalid JSON format, there must be a comma between all elements:

```diff
--- docker.invalid	2024-06-17 12:31:17.000000000 -0700
+++ docker.json	2024-06-17 12:30:05.000000000 -0700
@@ -1,7 +1,7 @@
 {
   "features": {
     "containerd-snapshotter": false
-  }
+  },
   "default-address-pools": [
     {
       "base": "10.189.0.0/16",```
```

> ### Expected Behavior
> The file should at least be unaltered on a normal startup.

The file is only replaced by the default content because it couldn't be parsed by the JSON parser. I've verified that the file is left intact when it is valid JSON.

I'm closing this issue as we still have #4832 for creating a proper way to configure `daemon.json`.

**Comment by jhollmannk** [comment]
Thanks a lot for the quick reply!
I created the example JSON just by pasting a part of my daemon.json and didn't check whether that was valid.
However, my daemon.json was also invalid! Didn't see that at first. A copy&paste error from the windows clipboard to the vi session in the wsl.
As you said, a valid JSON is not overwritten so I apologize for wasting your time.
