### ISSUE TITLE
Enable ingress

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#71]

**Comment by agracey** [comment]
Could this be done with mDNS so any ingress is discoverable without any setup?

I haven't tried it yet, but something like this looks interesting: https://github.com/blake/external-mdns

**Comment by jandubois** [comment]
> this looks interesting: https://github.com/blake/external-mdns

This looks pretty much like what I was planning to write, so thanks for finding it! I wonder how I missed it when I was looking for mDNS Go libraries last hackweek. Excited to try it out!

**Comment by gaktive** [comment]
To be replaced with a new story from @agracey
