### ISSUE TITLE
Closing the RD Window on macOS with the little red button stops the UI, and cannot be restarted

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#714]
The VM is still running, and the tray icon as well, but the dock entry, task-switcher entry, and the menu bar are all gone, so there is no way to re-open the Window. And since the app is technically still running, you cannot restart it unless you shut down the VM first.

**Comment by jandubois** [comment]
You can actually restart the app using the "Preferences" option from the Rancher Desktop menu.

Running Rancher Desktop should have the same effect.

**Comment by rak-phillip** [comment]
@jandubois I don't think this issue is still relevant. Can you confirm?

**Comment by jandubois** [comment]
> I don't think this issue is still relevant. Can you confirm?

Yes, this is no obsolete; we have the "Run in background" functionality, and the window can be re-opened both by running Rancher Desktop again, and from the notification icon.
