### ISSUE TITLE
Remove WSL Networking preferences

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7209]
The legacy networking stack will be unavailable in 1.15.

- [ ] Remove the "WSL | Networking" page from the preferences dialog, as it doesn't have any other settings on it

- [ ] ~Remove the `--experimental.virtual-machine.networking-tunnel` setting from `rdctl start` and `rdctl set`~
    We are not doing this for 1.15, but the validator will reject any changes to the setting. We'll remove it when we remove the legacy code in 1.16.

- [ ] Add settings migration to force `networking-tunnel` to always be true

- [ ] https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/380

Barring any new-found incompatibilities with the tunneling network, the code for the legacy stack will be removed in 1.16. The code will already be inaccessible in 1.15, but could be re-enabled in an emergency in a patch release.

**Comment by mook-as** [comment]
Docs issue at https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/380 so we can close this one now.  Fixed in #7236.
