### ISSUE TITLE
Port forwarding only listens on IP family that DNS resolves localhost to

### ISSUE THREAD

**Issue by mikeseese** [rancher-sandbox/rancher-desktop#7248]
### Actual Behavior

When using the Port Forwarding tab, I will only see a listen server on the local address that my DNS (I think it's DNS that's what the Windows `hosts` file says) response to `ping localhost` resolves to.

### Steps to Reproduce

1. Forward a port
2. Use TCPView (or netstat) to notice only 1 listener is available on that port instead of 2 (one for both 127:0.0.1 and ::1)

### Result

![image](https://github.com/user-attachments/assets/470ad5c2-29bd-4a5c-9812-b9a2b1902fe6)

``` bash
$ ping localhost

Pinging Einstein [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms 

Ping statistics for ::1:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

### Expected Behavior

I expect to see a bound address for both 127.0.0.1 and ::1 like `kubectl port-forward` does.

### Additional Information

Looking in `pkg/rancher-desktop/backend/kube/client.ts` on line `509`, the server listen is `server.listen({ port: hostPort, host: 'localhost' });`. I believe that changing host to `host: '::'` will resolve this (at least on Windows). I can put together a PR if you're interested in this solution.

### Rancher Desktop Version

1.14.1

### Rancher Desktop K8s Version

1.28.11

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 22H2 Build 22621.3951

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

N/A

**Comment by pelifix** [comment]
I can confirm and replicate this issue on my side:
* When using `kubectl port-forward ` it will listen on both `::1` and `127.0.0.1`
* When using the Rancher Desktop GUI to setup port forwarding it only listen on `::1`

And yes, this breaks a lot for programs.... example SQLPlus.
