### ISSUE TITLE
Host docker plugins not updated on Windows

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#7308]
### Actual Behavior

On Windows, we never overwrite the `docker-*.exe` plugins in `~/.docker/cli-plugins`; this means we never update them after the first time we copy them in (even when the application is updated).

### Steps to Reproduce

1. Install an older version of Rancher Desktop
2. Check the `docker compose` version
3. Install a newer Rancher Desktop that has an updated docker plugin
4. Check the `docker compose` version

### Result

The plugin is never updated.

### Expected Behavior

The plugin should be updated.

### Additional Information

https://github.com/rancher-sandbox/rancher-desktop/blob/0cf389a1540628f4c0e5b4d2b5cca0e75062072a/pkg/rancher-desktop/integrations/windowsIntegrationManager.ts#L436-L444

We always copy with `COPYFILE_EXCL` and swallow `EEXIST` errors.

### Rancher Desktop Version

0cf389a1540628f4c0e5b4d2b5cca0e75062072a

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

N/A

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by pit-hub** [comment]
It is better not to copy files.
In windows we can use symbolic links as we use them in linux.
As I can understand from **buildx** documentation [here](https://github.com/docker/buildx?tab=readme-ov-file#manual-download). In my case I use **buildx** as system wide setup
- **System wide installation** the right location should be %ProgramData%\Docker\cli-plugins
    Example for **buildx**
  ```batch
  mkdir "%ProgramData%\Docker"
  mkdir "%ProgramData%\Docker\cli-plugins"
  mklink "%ProgramData%\Docker\cli-plugins\docker-buildx.exe" "%ProgramFiles%\Rancher Desktop\resources\resources\win32\bin\docker-buildx.exe"
  ```
- **User install** should be: %UserProfile%\.docker\cli-plugins
  ```batch
  mkdir "%UserProfile%\.docker"
  mkdir "%UserProfile%\.docker\cli-plugins"
  mklink "%UserProfile%\.docker\cli-plugins\docker-buildx.exe" "%ProgramFiles%\Rancher Desktop\resources\resources\win32\bin\docker-buildx.exe"
  ```
On installation If the user has already setup a file or symbolic link we should do nothing
On un install any symbolic link can be safely removed.

If the user has already setup somethin on his own it should reflect it intend and it should not have impact ot his/her expectations for plug-in versions.

This way also we a sure we have always the rights version.

**Comment by mook-as** [comment]
As you noted, `mklink` requires either elevation or Developer Mode, so it's not a great solution for us.

**Comment by mook-as** [comment]
We might be able to use https://github.com/docker/cli/blob/2b6d2d98d83ef28826045d25464343839167245b/cli-plugins/manager/manager.go#L58 to add an extra search directory?

**Comment by jandubois** [comment]
> We might be able to use https://github.com/docker/cli/blob/2b6d2d98d83ef28826045d25464343839167245b/cli-plugins/manager/manager.go#L58 to add an extra search directory?

I don't think that is going to work because it looks like it is only searched if the plugin isn't found in `~/.docker/cli-plugins`. So if you have a version already installed there, then `docker` will never look in the extra directory. Or did I misread how it works?

**Comment by jandubois** [comment]
As a workaround, until we have released a fix, users can update the file manually:

Copy
from `"%ProgramFiles%\Rancher Desktop\resources\resources\win32\bin\docker-compose.exe"`
to `"%USERPROFILE%\.docker\cli-plugins\docker-compose.exe"`

Same thing for `docker-buildx.exe`.

**Comment by mook-as** [comment]
We can probably check the plugins to see if they're something we've shipped (or at least no newer the last version we copied) and delete in that case.

(Actually, it looks like on Windows the search path is preferred, but on Linux, including WSL, the version in `~/.docker/cli-plugins` is preferred, per `docker info`. I have no idea why yet.)

**Comment by jandubois** [comment]
Looks like the plugins have no VERSIONINFO resource:

<img width="357" alt="CleanShot 2024-09-05 at 15 22 24@2x" src="https://github.com/user-attachments/assets/f4b4b2ca-1cf9-4f3f-8ff1-3a84c8ea0474">

So the only way I can think of to check the version would be to call `docker compose version`. Or maybe better `"%USERPROFILE%\.docker\cli-plugins\docker-compose" version`.
