### ISSUE TITLE
Configure Path no longer updating .bashrc/.zshrc/.bash_profile when option set to automatic

### ISSUE THREAD

**Issue by luca-ballerini** [rancher-sandbox/rancher-desktop#7315]
### Actual Behavior

Changing the settings under Preferences -> Application -> Environment -> Configure Path no longer add/removes the block below to .bashrc/.zshrc/.bash_profile files

```
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="$HOME/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
```

### Steps to Reproduce

- Open Rancher Desktop main window
- Select Preferences -> Application -> Environment 
- Change the value of the radio button and click Apply
- cat any of the 3 .*rc files

### Result

.bashrc, .zshrc, .bash_profile files are not updated when the radio button value is changed and applied

### Expected Behavior

If the option is set to manual before switching to Automatic and clicking Apply, once the change is applied the .*rc files should be updated to include the path export, and the same block should get removed when switching from Automatic to manual

### Additional Information

This behaviour changed following the update to v 1.15. in 1.14.2 the option worked as expected

### Rancher Desktop Version

1.15.0

### Rancher Desktop K8s Version

1.25.16

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Sonoma 1.14.6

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
Hi! Sorry, we changed the code around there to reduce the chance of files being accidentally clobbered, and it's possible that I made some errors.

Could you [enabled debug logging](https://docs.rancherdesktop.io/1.15/ui/troubleshooting#enable-debug-mode), restart Rancher Desktop (to ensure the relevant code runs), and then upload [your logs](https://docs.rancherdesktop.io/1.15/ui/troubleshooting#show-logs)? The most relevant file is probably `integrations.log` but some of the other ones are possibly useful too.

**Comment by luca-ballerini** [comment]
@mook-as sure - If it can help the background.log file shows an entry about the change that was made to avoid touching files with xattr

```
2024-08-07T16:46:12.828Z: UnhandledRejectionWarning: Error: Refusing to manage /Users/lballerini/.bash_profile which has extended attributes
```
Earlier today I tried to rollback to v1.14.2 and the option works fine

[integrations.log](https://github.com/user-attachments/files/16531924/integrations.log)
[background.log](https://github.com/user-attachments/files/16531940/background.log)

**Comment by mook-as** [comment]
Ah, yeah, that means we're intentionally avoiding to change it (because we now create a new file and rename it in-place, which would have lost your extended attributes).

Can you do a `xattr -lv /Users/lballerini/.bash_profile` to see what extended attributes the file has? I'm not expecting any, but it obviously has something.

**Comment by luca-ballerini** [comment]
Only one, `com.apple.provenance` same also on the .zshrc and .bashrc

**Comment by luca-ballerini** [comment]
Another indirect consequence, is that the Diagnostics section shows an error if the path is exported only on one file. I use zsh so only adding to the .zshrc file, produced this alert
```
The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your bash shell.
```

**Comment by mook-as** [comment]
Yeah, the full set of diagnostics isn't there yet; see #7297 for some of that.

It looks like `com.apple.provenance` (per [this](https://apple.stackexchange.com/questions/450118/)) has to do with quarantine and is probably safe to remove, so we might want to consider just allowing the write if that's the only xattr involved.

**Comment by martintex** [comment]
I just wanted to mention that this indeed does not work.
Just installed latest version with automatic option checked and run into both Failed to determine if /Users/mkx/.zshrc contains extended attributes and the .rd/bin one.
Manipulating the files manually fixes the issue of course.

**Comment by jandubois** [comment]
> It looks like `com.apple.provenance` (per [this](https://apple.stackexchange.com/questions/450118/)) has to do with quarantine and is probably safe to remove, so we might want to consider just allowing the write if that's the only xattr involved.

I think we should also allow updating profile files with the `com.apple.quarantine` attribute, as the shells won't check the attributes before sourcing the files (maybe test this first, but seems extremely unlikely).

More information about `com.apple.provenance` at https://eclecticlight.co/2023/03/13/ventura-has-changed-app-quarantine-with-a-new-xattr/
