### ISSUE TITLE
Spike: rd-open-webui-docker-ext

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#7321]
Look into rd-open-webui-docker-ext and see if we can get it into good enough shape to make it public.

**Comment by mook-as** [comment]
Looking into this, I think we will need to run a process on the host side (as it currently does); while it's easier on Windows, on Linux we'll need to make lima be able to expose devices somehow to get CUDA/ROCm to work. And on macOS, it seems unlike we will be able to expose Metal in a way that makes sense in a Linux VM.

We may wish to extend the extension format to specify a command to start a persistent host-side process in the background (and have RD manage restarting that process as needed).  This would need to be per-platform, so likely under `.host` in `metadata.json`.  Awkwardly, however, there are multiple files for Windows; we may need to figure out a good way to copy that (self-extracting archive and some sort of cleanup? Uninstall hook? Run the Linux version in WSL2 in a glibc-based container?).

**Comment by gunamata** [comment]
Here are my observations from trying out @mook-as 's fork so far:

- Able to build, install (`rdctl extention install ..`)  and use the extension on Windows. We need to confirm if ollama makes use of GPU available on the host machine. 
- On Linux, the extension installation fails. 
However, the extension installation succeeds when tried with Rancher Desktop started via `yarn dev`. 
- On macOS, the extension installation succeeds but ollama is not installed or started so the open-webui app is not able to pull query models.

**Comment by jandubois** [comment]
The spike is done; any additional work will be tracked in separate issues, either here on in the extension repo.
