### ISSUE TITLE
Rancher Desktop incorrectly modifies .bashrc instead of .zshrc

### ISSUE THREAD

**Issue by amingilani** [rancher-sandbox/rancher-desktop#7339]
### Actual Behavior

Rancher Desktop is modifying the .bashrc file, even when Zsh is set as the default shell.

### Steps to Reproduce

1. Use Zsh as your default shell (`echo $SHELL` returns `/bin/zsh`).
2. Install and configure Rancher Desktop.
3. Check the `.bashrc` file: it contains entries managed by Rancher Desktop.
4. Check the `.zshrc` file: it does not contain the necessary configurations from Rancher Desktop.

### Result

Here's the content of my `.bashrc` and `.zshrc` files:

`.bashrc`:
```bash
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/agilani/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
```

`.zshrc`:
```zsh
# Zsh configuration (irrelevant details omitted for brevity)
```

Rancher Desktop should be updating `.zshrc` with the necessary configurations instead of `.bashrc` when Zsh is detected as the active shell.

### Expected Behavior

Rancher Desktop should detect the default shell and update the corresponding shell configuration file (in this case, .zshrc), not .bashrc.

### Additional Information

Rancher Desktop version: Fresh OS and fresh install of Version 1.15.0 (1.15.0)
Shell: Fresh install of ohmyzsh. `zshrc --version` is  `zsh 5.9 (x86_64-apple-darwin23.0)`

### Rancher Desktop Version

Fresh OS and fresh install of Version  (1.15.0)

### Rancher Desktop K8s Version

v1.30.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Sonoma version 14.6.1 (23G93)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by amingilani** [comment]
## Workaround

Kinda obvious. Copy the lines to your `.zshrc`

```
➜  ~ cat ~/.bashrc
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/agilani/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

➜  ~ cat ~/.bashrc >> ~/.zshrc

➜  ~ tail -n 3 ~/.zshrc
### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/agilani/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
```

**Comment by mook-as** [comment]
Hmm, we actually just blindly modify both. Would you be able to [enable debug logging](https://docs.rancherdesktop.io/ui/troubleshooting/#enable-debug-mode), then restart Rancher Desktop (to ensure it tries again with the extra logging enabled), and then check the [logs](https://docs.rancherdesktop.io/ui/troubleshooting/#show-logs) for errors? It's most likely to be in `background.log`.

See also #7315 where some files were not being managed due to having extended attributes; for the initial change we skipped everything with those (since we now write a temporary file and rename in place to reduce chances of dataloss), but it seems like we may need to try to copy those over as well.

**Comment by amingilani** [comment]
Thanks @mook-as it looks like I also had extended attributes. I'm not sure what those are, but:

Log:

```log
2024-08-12T18:14:28.612Z: UnhandledRejectionWarning: Error: Refusing to manage /Users/agilani/.bash_profile which has extended attributes
```

Attributes:

```
➜  ~ xattr -lv $HOME/.bash_profile
/Users/agilani/.bash_profile: com.apple.provenance:
```

It may be safe to mark this as a duplicate?

**Comment by amingilani** [comment]
Removed the attributes

```
➜  ~ xattr -lv $HOME/.bash_profile                    
/Users/agilani/.bash_profile: com.apple.provenance: 
➜  ~ xattr -d com.apple.provenance $HOME/.bash_profile
➜  ~ xattr -lv $HOME/.bash_profile                    
```

Will now if a Factory Reset fixes things.

**Comment by mook-as** [comment]
Yeah, that sounds like it's the same extended attribute, so it would be a duplicate.  Thanks for helping us track things down!

**Comment by amingilani** [comment]
Sounds good. Also added that .zshrc has those attributes too
