### ISSUE TITLE
After upgrading to 1.15.0 on Windows, cannot connect via WSL IP

### ISSUE THREAD

**Issue by MarkRPurdy-Tricentis** [rancher-sandbox/rancher-desktop#7342]
### Actual Behavior

Prior to my upgrade to 1.15.0, along with using localhost to access exposed ports on my K8s services, I was able to use the IP Address assigned to WSL. After upgrading, they are only reachable via localhost. I see the host_switch listening on 0.0.0.0, but connections on any IP Address result in a ERR_CONNECTION_RESET

### Steps to Reproduce

Run a K8s Service exposing a port XYZ
Connect via localhost:XYZ works
Connect via <WSL IP Address>:XYZ receives ERR_CONNECTION_RESET

### Result

ERR_CONNECTION_RESET occurs using any IP Address

### Expected Behavior

Expect the WSL IP Address to work the same as localhost

### Rancher Desktop Version

1.15.0

### Rancher Desktop K8s Version

1.30.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise Version 22H2 Build 19045.4651

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by fengxiao2019** [comment]
hi, MarkRPurdy, have you got the answer, I also have the same issue.

**Comment by MarkRPurdy-Tricentis** [comment]
> hi, MarkRPurdy, have you got the answer, I also have the same issue.

I believe it is due to removing the old networking in this release. I was able to get past it by using the LoadBalancer IP address instead.
