### ISSUE TITLE
DNS resolution no longer work from Rancher Desktop WSL

### ISSUE THREAD

**Issue by jonaslewin** [rancher-sandbox/rancher-desktop#7353]
### Actual Behavior

DNS resolution does not work from Rancher Desktop WSL. Using Windows 11, Rancher Desktop version 1.15.0.

### Steps to Reproduce

1. Set Rancher Desktop as the default WSL instance:
   ```sh
   wsl --set-default rancher-desktop
   ```
2. Open WSL:
   ```sh
   wsl
   ```
3. Attempt to ping a domain:
   ```sh
   ping google.com
   ```

### Result

Domain name is not resolved.

### Expected Behavior

Domain name should be resolved.

### Additional Information

We noticed this because pods in the Kubernetes cluster stopped resolving DNS, resulting in recursive CNAME resolution. This used to work, but after either a Windows or Rancher update (or some other change, we are not sure), the functionality broke.
We previously had this working on multiple workstations with the same configuration, but it stopped working on all workstations at some point.

**Workaround Solution:**
 
We created a `.start` provisioning script for Rancher that sets the DNS in `/etc/resolv.conf` to use `nameserver 1.1.1.1`:
 
```sh
#!/bin/sh
if [ -L /etc/resolv.conf ]; then
    rm -f /etc/resolv.conf
fi
echo "nameserver 1.1.1.1" > /etc/resolv.conf
```

This workaround ensures that DNS resolution works correctly after restarting Rancher Desktop.

### Rancher Desktop Version

1.15.0

### Rancher Desktop K8s Version

1.30.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Win 11 Pro, 23H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by Nino-K** [comment]
@jonaslewin the `/etc/resolv.conf` that you are referring to is the one from the outside of the network namespace and contains an address that will most likely not work (expected). However, if you enter the Rancher Desktop's network namespace by doing the following:
```
rdctl shell
```
and then
```
ping google.com
```
You will notice that it resolves google.com.

I'm going to close this issue, however, feel free if you encounter anything further.

**Comment by jonaslewin** [comment]
Thank you for the comment @Nino-K 
 
The problem for us was not only being unable to resolve DNS from within the WSL instance, but rather from pods in the Rancher Kubernetes cluster (cert-manager specifically) in a fresh Rancher Desktop install.
 
If you were to try to dig CNAME google.com from within any pod, it would result in recursion.
 
The only way for us to fix this was:
 
1. To change the DNS address in the CoreDNS ConfigMap:
 
   ```
   forward ./etc/resolv.conf
   ```
 
   to
 
   ```
   forward . 1.1.1.1
   ```
 
2. Directly in the referenced /etc/resolv.conf.
 
Both of these settings get reset on every restart of Rancher Desktop, hence the need for a custom provisioning script that we would like to avoid. 
 
You might also say that the Kubernetes cluster with Rancher Desktop is broken for us out of the box, and it would appear so to inexperienced people running it on Windows by default.
 
Cheers.
