### ISSUE TITLE
Can't restart Rancher Desktop remotely via CLI

### ISSUE THREAD

**Issue by edwardgalligan** [rancher-sandbox/rancher-desktop#7373]
### Problem Description

I have Rancher Desktop running on a Linux desktop computer (with a Linux DE & monitor attached). If I SSH into this machine & use `rdctl` to interact with Rancher Desktop, it's not possible to modify config & restart, since `rdctl start` always fails with the following error:

```
❯ rdctl start
INFO[0000] About to launch /opt/rancher-desktop/rancher-desktop  ... 
[104006:0821/232823.536391:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[104006:0821/232823.536440:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
```

### Proposed Solution

I can see `CLI/Headless mode` is marked as unsupported on the [feature list](https://github.com/rancher-sandbox/rancher-desktop/blob/main/docs/development/features.md) but it would be nice if it were possible to control the application via CLI on a system that has a display (even if the shell executing the cli does not have a display). The cli seems of limited utility otherwise.

**Comment by mook-as** [comment]
We're not likely to change this in the short term, but we'll keep this open in case we get it some day.  Currently the whole thing is driven using Electron (as in, that starts and then our code runs from that), so a display is required at this point.

**Comment by edwardgalligan** [comment]
@mook-as to clarify, I'm not asking for Rancher Desktop to run without a display (that would be the headless mode mentioned as unsupported in the feature page). I'm asking for a headless login session to a system with a GUI login session running, to be able to restart services without error.

i.e. the full use-case:

- I boot a Linux Desktop Environment on MachineA & run Rancher Desktop via mouse-click - the Electron app minimises to tray & starts k3s & dockerd in the background.
- from MachineB I connect via SSH to MachineA & run `rdctl` - this gives me an error that there is no `$DISPLAY` & crashes Electron (because the SSH login session has no display - there is a display on MachineA)

**Comment by edwardgalligan** [comment]
> FWIW, some rdctl set options will end up doing that because changing some options require restarting the backend

Is this flagged in the CLI output? My intent was to reload config after running `rdctl set` - if this restart happens implicitly in the `set` subcommand it wasn't obvious from the output.

**Comment by mook-as** [comment]
> > FWIW, some rdctl set options will end up doing that because changing some options require restarting the backend
> 
> Is this flagged in the CLI output? My intent was to reload config after running `rdctl set` - if this restart happens implicitly in the `set` subcommand it wasn't obvious from the output.

Yeah, the output of `rdctl` depends on if it's restarting:
```sh
$ rdctl set --diagnostics.show-muted=true
Status: settings updated; no restart required.
$ rdctl set --kubernetes.enabled=true
Status: reconfiguring Rancher Desktop to apply changes (this may take a while).
```
> > `rdctl start` specifically attempts to start a new instance
> 
> Is this deliberate to support some required use-case (running multiple parallel Electron instances)?

No, it's just because it's easier to check from the Electron side if an instance already exists (because we already have to handle it when the user double-clicks on the Rancher Desktop icon when it's already running — that just makes the existing instance pop up).  We do not support multiple parallel Electron instances; `rdctl start` just runs the normal Electron executable and let things happen.

**Comment by edwardgalligan** [comment]
Thanks - I'll try again & re-open if issues persist

**Comment by jandubois** [comment]
> `rdctl start` specifically attempts to start a new instance

Note that `rdctl start` will perform an implicit `rdctl list-settings` command first, to see if the instance is already running. If this succeeds, then it actually just performs an `rdctl set` command instead (`start` and `set` accept the same parameters).
