### ISSUE TITLE
k3s: Switch to fetching versions via channel server

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#740]
From Slack:
> you should use the channel server instead of GH releases

I believe that refers to https://github.com/rancher/channelserver

- [ ] Revert #744

**Comment by jandubois** [comment]
@mattfarina says we should not filter out newer versions, just not make them the default.

Maybe we should have a checkbox "Show unstable versions" and filter them out unless it is checked?
