### ISSUE TITLE
reinstalling rancher fails on macOS M1 sonoma 14.6.1

### ISSUE THREAD

**Issue by ydekel6** [rancher-sandbox/rancher-desktop#7432]
Laptop info: Macbook pro M1 Sonoma 14.6.1
Rancher desktop version 1.15.1

- I've tried to build one of our services and rancher failed with limited space.
- when I tried to raise the memory and CPU in the UI, rancher failed to restart and isn't working anymore.

I've tried to scale down the resources back what what they were and I tried to delete and reinstall (both through the dmg file and through brew). All I get is a bad docker socket and the following error:
```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
```
The full error report:
<img width="734" alt="image" src="https://github.com/user-attachments/assets/86867db3-3185-409e-8d01-b2ccd1cdd567">
the last error in the report:
```
'0:/tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl'
  ],
  stdout: '',
  stderr: '/usr/bin/scp: write remote "/tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl": Failure\r\n' +
    '/usr/bin/scp: failed to upload file /var/folders/jg/m7mgybc91w19rqh_t2_l4x740000gn/T/rd-nerdctl-EpAMhNRjef1B/nerdctl to /tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl\r\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura copy /var/folders/jg/m7mgybc91w19rqh_t2_l4x740000gn/T/rd-nerdctl-EpAMhNRjef1B/nerdctl 0:/tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl'
}
2024-09-09T06:58:45.424Z: > /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura shell --workdir=. 0 sudo rm -f /tmp/rd-nginx.conf-MAC86HUbTP4j.nginx.conf
```

adding all the rancher logs: [rancher-logs.zip](https://github.com/user-attachments/files/16926776/rancher-logs.zip)

----
Is there a way to purge rancher desktop so I can have a clean install? Do I need to delete or reset anything else?

**Comment by ydekel6** [comment]
Now I see that the error is about k8s, but my k8s is set to disabled.

also, when I try any docker command, I get this error:
```
docker run -ti --rm bla:bla sh
docker: error during connect: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": EOF.
```

**Comment by mook-as** [comment]
The dialog title (_Kubernetes Error_) is a red herring, left over from when Rancher Desktop always started Kubernetes.  The actual error is that `limactl.ventura` is crashing.  It seems to start part way though:

```
time="2024-09-09T09:58:44+03:00" level=info msg="[hostagent] The final requirement 1 of 1 is satisfied"
time="2024-09-09T09:58:44+03:00" level=info msg="READY. Run `limactl shell 0` to open the shell."
⋮
2024-09-09T06:58:45.380Z: > limactl copy /var/folders/jg/m7mgybc91w19rqh_t2_l4x740000gn/T/rd-nerdctl-EpAMhNRjef1B/nerdctl 0:/tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl
$ c [Error]: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
⋮
  stderr: '/usr/bin/scp: write remote "/tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl": Failure\r\n' +
    '/usr/bin/scp: failed to upload file /var/folders/jg/m7mgybc91w19rqh_t2_l4x740000gn/T/rd-nerdctl-EpAMhNRjef1B/nerdctl to /tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl\r\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura copy /var/folders/jg/m7mgybc91w19rqh_t2_l4x740000gn/T/rd-nerdctl-EpAMhNRjef1B/nerdctl 0:/tmp/rd-nerdctl-EpAMhNRjef1B.nerdctl'
```
Unfortunately, the error log is missing _why_ the upload failed.

There are a few files in the logs directory that are symbolic links (`lima.ha.stderr.log`, etc.); would you be able to upload those as well?

**Comment by ydekel6** [comment]
Added the lima logs from `~/Library/Application\ Support/rancher-desktop/lima/0` (the symlinks). I checked that folder and I don't have the other 3 files (lima.serial.log, lima.serialp.log, lima.serialv.log)

[lima-logs.zip](https://github.com/user-attachments/files/16936172/lima-logs.zip)

**Comment by mook-as** [comment]
Hi! Would I be correct in thinking that those logs are not matched up to the previous ones (that is, Rancher Desktop was run between the points the logs were collected)?

I'm still trying to figure out what has gone wrong; but I do see that:
- We're using VZ virtualization (which sounds good)
- Administrative privileges are enabled (i.e. we're using socket_vmnet)
- But that might be having issues (possibly as a result of something else having gone wrong):
  > template: :1:21: executing "" at <fd_connect "/private/var/run/socket_vmnet.rancher-desktop-shared">: error calling fd_connect: fd_connect: dial unix /private/var/run/socket_vmnet.rancher-desktop-shared: connect: no such file or directory

**Comment by jandubois** [comment]
> I restarted rancher again and it seems to be fixed.

I assume this means this issue can be closed. Feel free to re-open with additional information if the problem comes back!

**Comment by oualidsr** [comment]
Thanks for documenting this @ydekel6 👍
