### ISSUE TITLE
Support for UDP ports?

### ISSUE THREAD

**Issue by KallynGowdy** [rancher-sandbox/rancher-desktop#7473]
It appears that this agent currently only support setting up forwards for TCP listeners. Would it be possible to detect and support UDP ports as well?

The [iptables lookup entries](https://github.com/lima-vm/lima/blob/d87e89f7ea651cc2e17fc3a913eb62b77c07e8d6/pkg/guestagent/iptables/iptables.go#L14) already include whether the port is TCP/UDP, so hopefully it is as simple as checking the flag and opening the listener in a different mode.

Thoughts?

**Comment by jandubois** [comment]
Comments on #6821 seem to indicate that UDP has been working lately with WSL and the legacy networking stack (which is no longer supported as of Rancher Desktop 1.15).

@Nino-K I think this issue should be considered a duplicate of #6821 and closed.

**Comment by Nino-K** [comment]
I'm going to close this since it's a duplication of https://github.com/rancher-sandbox/rancher-desktop/issues/6821.
