### ISSUE TITLE
Path management diagnostics: No diagnostic for unexpected docker CLI plugin

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#7500]
### Actual Behavior

When a `~/.docker/cli-plugins` symlink points to an unexpected file, we do not get a diagnostic.

### Steps to Reproduce

1. In Rancher Desktop, Preferences → Application → Environment → Configure PATH → Automatic
2. Quit Rancher Desktop
3. `ln -sf ~/.bashrc ~/.docker/cli-plugins/docker-buildx`
4. Start Rancher Desktop
5. Check diagnostics

### Result

There are no diagnostics.

### Expected Behavior

There should be a diagnostic about the incorrect symlink, per Qase test RD-51.

We may decide that there should not be a diagnostic in this case (in which case the test case will be changed).

### Rancher Desktop Version

1.15.1-328-g0ba5528e9

### Rancher Desktop K8s Version

1.30.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.5

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Same issue on macOS
