### ISSUE TITLE
Snapshot banner does not HTML-escape the snapshot name

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7508]
I've created a snapshot with `</body><img src="invalid:url" onerror="alert(0)">` as both the name and description. Once the snapshot is created it shows a banner that doesn't show the snapshot name (but afaict does not execute the script either):

<img width="541" alt="Screenshot 2024-09-18 at 12 55 47 PM" src="https://github.com/user-attachments/assets/2eb6a241-6ec3-43d0-b348-e88eacdeb943">

RD-186

**Comment by mook-as** [comment]
See also comment: https://github.com/rancher-sandbox/rancher-desktop/issues/6221#issuecomment-1857101309

**Comment by jandubois** [comment]
I've edited RD-186 to not expect a name in the banner in this case.

Showing the escaped HTML would be slightly better, but it isn't important.
