### ISSUE TITLE
[Windows] WSL error 255 - Mounting WLS data

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#755]
## Summary

What happened/what you expected to happen?

**Issue found**
Resetting K8s (soft) I got an error on `wsl` after reset kubernetes. Here's the wsl log:
```bash
Creating initial data distribution...
tar: removing leading '/' from member names
agent exited with status 1 signal null
Launching the agent
mount: mounting /mnt/wsl/rancher-desktop/run/data/etc/rancher on /etc/rancher failed: I/O error
WSL: executing: mount -o bind /mnt/wsl/rancher-desktop/run/data/etc/rancher /etc/rancher: Error: wsl.exe exited with code 255
```
It happens during the WSL Mounting process.
Also it seems to crash the entire app: nerdctl, k8s, kim does not work.

**Expected behaviour**
* Reset k8s without crashing wsl.
* Integrated tools should keep working.

What version of Rancher Desktop are you running?
* `0.5.0-148-g36c156d`

What version of Kubernetes are you running?
* `v1.21.5`

Which OS version?
* `Windows 10 PRO - VM Azure Dv3 type`

## How to replicate
* Pull some images using nerdctl
* Navigate to K8s Settings
* Click Reset Kubernetes
* Wait a bit and the error will pop up during the wsl mounting.

## Diagnostics
During the manual testing on Reset k8s feature, after reset k8s, the wsl pops up a error:
![Screen Shot 2021-10-07 at 2 16 50 PM](https://user-images.githubusercontent.com/37411123/136455925-25ecaad3-20e2-45ea-b846-debbd699f740.png)

Closing/Re-opening the app does not fix the issue. There's a workaround to "fix" the error:

* OS Reboot
* `wsl --shutdown` (you don't need to restart Windows)

**Logs**
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/7305004/background.log)
[wsl.log](https://github.com/rancher-sandbox/rancher-desktop/files/7305005/wsl.log)

**Comment by mook-as** [comment]
When this happens, I seem to see a line in `dmesg`:
> EXT4-fs error (device sdd): __ext4_find_entry:1534: inode #2: comm mount: reading directory lblock 0

I believe that came from:

https://github.com/Microsoft/WSL2-Linux-Kernel/blob/a571dc8cedc8e0e56487c0dc93243e0b5db8960a/fs/ext4/namei.c#L1533-L1536

Looking at a relevant commit in the area — https://github.com/microsoft/WSL2-Linux-Kernel/commit/6febe6f253a5bb5c7ac2080d688bd4b75e019d4d (which removed a comment), that (maybe) means there's an read error?

**Comment by mook-as** [comment]
Hmm, don't even need the mount, `ls /mnt/wsl/rancher-desktop/run/data/` (from some other distro is fine) emits:
> EXT4-fs warning (device sdd): htree_dirblock_to_tree:1003: inode #2: lblock 0: comm sh: error -5 reading directory block

I guess it really doesn't like our bind mount (to `/mnt/wsl/…`) magic…
