### ISSUE TITLE
RDX: Shutdown hook

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#7588]
### Problem Description

Currently, extensions can run processes in the background. It would be good to have a hook to run stuff when Rancher Desktop shuts down, so that extensions can clean up (e.g. to terminate processes).

### Proposed Solution

Add a new hook next to `x-rd-{un,}install`, possibly called `x-rd-shutdown`. Run process on quit.

**Comment by mook-as** [comment]
Hmm, I'm assuming for now that the hook runs on application exit, _not_ backend shutdown. (We shutdown the backend to switch container engines or other preferences.)

**Comment by jandubois** [comment]
> Hmm, I'm assuming for now that the hook runs on application exit, _not_ backend shutdown. (We shutdown the backend to switch container engines or other preferences.)

That sounds fine.

We do have some logic to terminate extensions that are not supported by the container engine. I guess this will automatically trigger the uninstall hook, which should take care of shutting down the process, right?
