### ISSUE TITLE
Create a tag for rdx-open-webui

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7671]
Once https://github.com/rancher-sandbox/rancher-desktop-rdx-open-webui/issues/25 is done we need to create a tag for the extension and update the catalog to use the tag instead of `latest`.

**Comment by gunamata** [comment]
[v0.0.1](https://github.com/rancher-sandbox/rancher-desktop-rdx-open-webui/releases/tag/v0.0.1) release of the extension has been created and the catalog updated in the [PR#7834](https://github.com/rancher-sandbox/rancher-desktop/pull/7834) to point to the release.
