### ISSUE TITLE
invalid mount path: 'C:/temp/test' mount path must be absolute

### ISSUE THREAD

**Issue by rrgadeev** [rancher-sandbox/rancher-desktop#7677]
### Actual Behavior

volume is not mounted

### Steps to Reproduce

PS C:\temp> docker run --mount=type=bind,source=${pwd}/test,target=/app/src -it --rm debian:10

### Result

docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'C:/temp/test' mount path must be absolute

### Expected Behavior

volume is being mounted

### Additional Information

this is most likely due to the different case of the disk name
```
PS C:\temp> wsl
/mnt/c/temp # cd ..
/mnt/c # cd ..
/mnt # ls
c     e     wsl   wslg
```

### Rancher Desktop Version

1.15.1

### Rancher Desktop K8s Version

nope

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

win 10 ent N 21H2 19044.4780

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

air grap
wsl_version: "2.2.4" https://github.com/microsoft/WSL/releases/tag/2.2.4
add Media.MediaFeaturePack~~1.0 (It doesn't work without it)
2024-08 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5041580)

**Comment by rrgadeev** [comment]
`docker run -v /c/temp/test:/app/src -it --rm debian:10`
It works

**Comment by rrgadeev** [comment]
in version 1.16.0, the bug is not reproducible

**Comment by jandubois** [comment]
Thank you for confirming that the issue no longer happens in 1.16.0.
