### ISSUE TITLE
Remove "extension" from "Open WebUI Extension"

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7724]
All entries in the catalog are extensions, so this is redundant. Also none of the other extensions have it:

![CleanShot 2024-11-05 at 12 22 15@2x](https://github.com/user-attachments/assets/1e43bbf4-352a-4af4-9985-6dd71cf6814a)

**Comment by gunamata** [comment]
Addressed in the [PR#7834](https://github.com/rancher-sandbox/rancher-desktop/pull/7834)
