### ISSUE TITLE
Does not install in OL/RHEL 8.4 

### ISSUE THREAD

**Issue by Cass67** [rancher-sandbox/rancher-desktop#777]
Hello, 

Seems we cant install this in RHEL 8.4 

[cass@t440 Downloads]$ sudo rpm -ivh rancher-desktop-0.6.0.x86_64.rpm
error: Failed dependencies:
qemu is needed by rancher-desktop-0.6.0-1.x86_64

[cass@t440 Downloads]$ rpm -qa | grep qemu
qemu-kvm-block-curl-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-kvm-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-guest-agent-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-kvm-block-ssh-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-kvm-common-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-kvm-block-iscsi-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
libvirt-daemon-driver-qemu-6.0.0-35.1.module+el8.4.0+11273+64eb94ef.x86_64
qemu-kvm-core-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-kvm-block-rbd-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-img-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
qemu-kvm-block-gluster-4.2.0-48.module+el8.4.0+11909+3300d70f.3.x86_64
ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch

Installs ok with a --nodeps flag, gui works ok and downloads images, but fails to start the vm for lima since i guess it does not find qemu.  Sym linking qemu-kvm to qemu appears not to work in the limited testing i did .. Yet to really have a go at it tbh to check if paths for linking makes a difference..

**Comment by davidcassany** [comment]
Ok I have been digging further on this topic. Apparently CentOS is facing a small lima bug. CentOS makes use of ssh v8.0 and causes lima to create wrong ssh command lines, lima-vm/lima#382 fixes it.

In addition, I managed to get RD working on  CentOS out of the box by using an AppImage (which includes an embedded QEMU, so no `qemu` vs `qemu-kvm` issues) and including a patched lima with lima-vm/lima#382.

**Comment by adamkpickering** [comment]
Closing this issue, since it has been addressed by the AppImage package format. If you are installing Rancher Desktop on distros in the Red Hat family, this is what you should use.
