### ISSUE TITLE
AppImage builds in OBS fail since 2024-10-17

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#7859]
### Actual Behavior

AppImage builds in OBS have been failing since October 2024; the last one available (from `main`) is:
https://download.opensuse.org/repositories/isv:/Rancher:/dev/AppImage/rancher-desktop-9.main.1729099373.23008301-Build2640.1.glibc2.27-x86_64.AppImage.mirrorlist

See https://download.opensuse.org/repositories/isv:/Rancher:/dev/AppImage/ for the current state of things.

### Steps to Reproduce

Check the AppImage build status on the right side of https://build.opensuse.org/project/show/isv:Rancher:dev (or https://build.opensuse.org/project/show/isv:Rancher:stable — both are failing in the same way)

### Result

All AppImage builds are failing; the message from OBS says:

> nothing provides this-is-only-for-build-envs needed by libudev-mini1,
nothing provides this-is-only-for-build-envs needed by systemd-mini,
nothing provides this-is-only-for-build-envs needed by udev-mini,
nothing provides this-is-only-for-build-envs needed by libsystemd0-mini

### Expected Behavior

AppImage builds should succeed.

### Rancher Desktop Version

N/A

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE (Open Build System)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage

**Comment by mook-as** [comment]
We're currently building the AppImage against Leap 15.2, which has long been out of support.  Bumping to the oldest version still in support (15.5) seems to [resolve the build issues](https://build.opensuse.org/package/live_build_log/home:mook_work:branches:isv:Rancher:dev/rancher-desktop-main/AppImage/x86_64).

I'm not familiar with what we want to support for AppImage, but I guess in this case it would make sense? @jandubois thoughts?

**Comment by jandubois** [comment]
> I'm not familiar with what we want to support for AppImage, but I guess in this case it would make sense?

Yes, we want to use the oldest still supported build environment. We are not going to spend effort on maintaining custom build environments. Same reason we are not supporting macOS 10.15 and macOS 11 anymore in the 1.17 release.

It is not clear to me if the generated AppImage wouldn't still work on an older OS release, given that the point of using AppImage is to isolate you as much as possible from the actual system. We should maybe test it, and then mention it in the release notes (and docs) what the minimum required version is.

**Comment by mook-as** [comment]
On trying to test the build AppImage, I realized that it actually built an RPM instead. Will need further investigation to see if I can get it to build an AppImage instead; back to the drawing board…
