### ISSUE TITLE
Add more info to rancherdesktop.io

### ISSUE THREAD

**Issue by catherineluse** [rancher-sandbox/rancher-desktop#786]
In the Hacker News thread about Rancher Desktop, some people had feedback about https://rancherdesktop.io/:

- They said they would like to see a written example of how to build and run a Dockerfile and a docker-compose file using nerdctl - for people who would rather see written example than the video
- The site and README should be updated to mention the technical preview of Rancher Desktop on Linux https://community.suse.com/posts/rancher-desktop-v06-including-linux-tech-preview

Source https://news.ycombinator.com/item?id=28835690

**Comment by mattfarina** [comment]
@catherineluse thanks for capturing those and bringing them over here.

**Comment by gaktive** [comment]
As a start, I'll update https://github.com/rancher-sandbox/rancherdesktop.io/blob/main/content/_index.html with some material from https://github.com/rancher-sandbox/rancher-desktop/blob/main/docs/images.md, then check the video for additional content to transcribe.

**Comment by vovtz** [comment]
I was also unable to find much info about the built-in K3s. Installing with Helm and `kubectl` work fine, but I have no idea how to make my ingress manifests work. I was presuming the defined path suffix should work against `localhost`, but in practice I didn’t succeed. How about using virtual hosts, do I need to define them as `127.0.0.1` equivalents in `/etc/hosts`?

**Comment by gaktive** [comment]
Upon discussion in the lead up to 1.0, we'll leave rancherdesktop.io as a marketing site and move these instructions to the new docs.rancherdesktop.io site. 

@btat how should we track documentation work -- in this repo with a `documentation` label or elsewhere?

**Comment by btat** [comment]
> Upon discussion in the lead up to 1.0, we'll leave rancherdesktop.io as a marketing site and move these instructions to the new docs.rancherdesktop.io site.
> 
> @btat how should we track documentation work -- in this repo with a `documentation` label or elsewhere?

Since there's a dedicated repo for docs now it might make more sense to consolidate things there. 

For ones tied to feature/code updates we can continue with a `documentation` label and use that to create the associated issue on the docs board. For ones like this, that are not tied to code changes, we could have folks create the issue on the docs board directly (and maybe transfer over any existing ones?).

Does that work @gaktive ?

**Comment by gaktive** [comment]
@btat sounds good to me to transfer issues like this over to docs. I'll fill in details as to what's required.

**Comment by gaktive** [comment]
Can't transfer so filed https://github.com/rancher/docs/issues/3806.

Closing this one here and with @gunamata, we'll indicate to the development team what the process is.
