### ISSUE TITLE
pull image failed by proxysetting

### ISSUE THREAD

**Issue by xiaods** [rancher-sandbox/rancher-desktop#787]
**For bugs, describe what you're seeing**
can't nerdctl pull nginx. report proxysettting error

**For feature requests, describe what you'd like to add or change**
fix it.
**To Reproduce**
1. nerdctl pull nginx
2.  show error logs

**Result**
can't run pod by specified image. nerdctl pull nginx not working

**Expected behaviour**
nerdctl pull is work like a charm

**Screenshots**
<img width="994" alt="截屏2021-10-14 上午12 47 47" src="https://user-images.githubusercontent.com/37678/137177683-52354491-1e85-4304-921e-69c2e3c2a240.png">

**Setup (please complete the following information):**
 - OS: macos
 - Rancher Desktop version  upstream version
 - Kubernetes version 1.21

**Additional context**
Add any other context about the problem here. Excerpt or attach logs if appropriate.

**Comment by jandubois** [comment]
There is not enough information in this issue to determine if it has been fixed by the following releases or not.

Please re-open if you still have problems with 1.1.0.
