### ISSUE TITLE
Rancher desktop fails to initialize Kubernetes on Windows 10 fresh installation

### ISSUE THREAD

**Issue by bowl-cat** [rancher-sandbox/rancher-desktop#7886]
### Actual Behavior

Fresh installation on Windows fails to enable Kubernetes with this error. 
Prerequisites are satisfied ( WSL2 is installed)

```
Error handling k8s-versions: Error: Could not fetch releases: Unauthorized
```

Microsoft Windows [Version 10.0.19045.4894]

> 

### Steps to Reproduce

Fresh installation on Windows 10. 

Suspected it was due to conflict with existing Docker Desktop installation and henced removed it. This doesn't seem to be the case though. 

### Result

Versions list shows empty. 

![image](https://github.com/user-attachments/assets/0ed2f69d-6594-46b7-961e-854b42b5bd1e)

### Expected Behavior

User should be able to Enable Kubernetes and pick a Version. 

### Additional Information

[background.log](https://github.com/user-attachments/files/18041441/background.log)
[commandLine.log](https://github.com/user-attachments/files/18041442/commandLine.log)
[dashboardServer.log](https://github.com/user-attachments/files/18041443/dashboardServer.log)
[deploymentProfile.log](https://github.com/user-attachments/files/18041444/deploymentProfile.log)

### Rancher Desktop Version

1.16.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows [Version 10.0.19045.4894]

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

No VPNs. Proxies. It's a Home PC.

**Comment by mook-as** [comment]
The relevant log file is most likely `k8s.log`.  Ideally enable [debug logging](https://docs.rancherdesktop.io/ui/troubleshooting#enable-debug-mode) before quitting Rancher Desktop and restarting it, so that we get extra logging that might be relevant.  But my best guess is that we've run out of unauthenticated GitHub API request limits and we're being rate-limited.

See also #7877

**Comment by mook-as** [comment]
Yeah, unfortunately that doesn't seem to be all that helpful either.

For the next release we should bundle a fixed list of Kubernetes versions on release (via #7877), so at least this shouldn't be an issue; at worst you'd get an outdated list instead (which we will attempt to update on every startup).

**Comment by bowl-cat** [comment]
Closing this as per above comment.
