### ISSUE TITLE
Error starting Kubernetes on the first launch only

### ISSUE THREAD

**Issue by ngauje** [rancher-sandbox/rancher-desktop#789]
**For bugs, describe what you're seeing**
On the first Rancher Desktop launch I get a _Error starting Kubernetes on the first launch_ message
![image](https://user-images.githubusercontent.com/28781255/137207654-eb25a002-66b1-4f4a-9cc6-86be41a91541.png)

In the k8s.log file I got some interesting messages :
```
Right kubectl missing, downloading version 1.19.11+k3s1
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.19.11/bin/windows/amd64/kubectl.exe
kubectl1.19.11+k3s1.exe   1% |                                        | (884/44 MB, 873.891 kB/s) [0s:48s]
[...]
kubectl1.19.11+k3s1.exe 100% |████████████████████████████████████████| (44/44 MB, 969.385 kB/s) [44s:0s] done.
Cross-device error trying to rename a file: rename C:\Users\username\AppData\Local\Temp\1\kuberlr-kubectl-292169627 C:\Users\username\.kuberlr\windows-amd64\kubectl1.19.11.exe: The system cannot move the file to a different disk drive. -- will do a full copy
F1013 22:23:53.323422    4812 main.go:69] rename C:\Users\username\AppData\Local\Temp\1\kuberlr-kubectl-292169627 C:\Users\username\.kuberlr\windows-amd64\kubectl1.19.11.exe: The system cannot move the file to a different disk drive.
```

So I quit Rancher Desktop and launch it again and.... it worked! I got this error message only during the first launch !

I deleted kubectl (C:\Users\username\.kuberlr\windows-amd64\kubectl) and restarted rancher desktop... same error message 1 time. I guess it occurs after the initial download of kubectl.

**Comment by gunamata** [comment]
@ngauje , Do you still see this problem with the recent releases of Rancher Desktop?

**Comment by gaktive** [comment]
@ngauje I'll close this for now based in a lack of response. If you do still see issues, particularly with a newer version (latest as I write: 1.5.1), we can reopen this. Thanks!

**Comment by praveenprem** [comment]
This seems to be still an issue on the latest stable version.
```
I0228 13:35:37.717611   28967 versioner.go:88] Right kubectl missing, downloading version 1.31.6+k3s1
F0228 13:35:37.880001   28967 main.go:70] error while trying to get contents of https://storage.googleapis.com/kubernetes-release/release/v1.31.6/bin/darwin/amd64/kubectl.sha256: GET https://storage.googleapis.com/kubernetes-release/release/v1.31.6/bin/darwin/amd64/kubectl.sha256 returned http status 404 Not Found
```

**Comment by jandubois** [comment]
@praveenprem Do you have a `~/.kuberlr/kuberlr.conf` or `/etc/kuberlr.conf` file on your system?

I think `kuberlr` would download by default from `dl.k8s.io` and not from `storage.googleapis.com`, which has been deprecated for a while.

**Comment by Paragon1970** [comment]
This issue can be solved by faking kuberlr into thinking it already has a local sourced kubectl version.

**Example of error attempting to download a non existing kubectl binary version**
```
➜ kubectl version --client
I0415 21:50:55.814963   20630 versioner.go:119] Right kubectl missing, downloading version 1.20.13
F0415 21:50:56.375588   20630 main.go:81] error while trying to get contents of https://dl.k8s.io/release/v1.20.13/bin/darwin/arm64/kubectl.sha512: GET https://dl.k8s.io/release/v1.20.13/bin/darwin/arm64/kubectl.sha512 returned http status 404 Not Found
```

- Download a version that is as close to the cluster version as possible (one minor version above) 
- Location of Rancher managed and downloaded kubectl versions: `/Users/<USER>/.kuberlr/darwin-arm64`

```
cd /Users/<USER>/.kuberlr/darwin-arm64
curl -LO "https://dl.k8s.io/release/v1.21.0/bin/darwin/arm64/kubectl"
mv kubectl kubectl1.21.0
chmod 755 kubectl1.21.0
cp kubectl1.21.0 kubectl1.20.13  #(fools kuberlr into believing it already has a local kubectl v1.20.13)
```

Kubectl against an older cluster version 1.20.13 will now return without issue.

**Comment by jandubois** [comment]
@Paragon1970 Recent Rancher Desktop releases don't even support Kubernetes 1.20 or earlier anymore (and I think there are no native arm64 versions of `kubectl` published before 1.21 anyways). Is this issue reproducible with recent versions of Kubernetes?

**Comment by Paragon1970** [comment]
Yeah my use case is an outlier @jandubois which likely does not affect that many folks.
It's due mainly to the fact that we employ Arm MacBooks, Rancher-desktop and a number of older versioned k8s clusters.
Rancher automatically references the cluster version and attempts to download the correct version which in some cases may not exist at dl.k8s.io.
In this event I employ the workaround previously stated, this allows continued use of the useful automatic switching of kubectl version as provided by Rancher-Desktop via kuberlr while simultaneously providing access to our older clusters without the need to switch kubectl version manually. (hope this makes sense) 

But I concede, it's highly unlikely the wider community will experience this use case.

**Comment by jandubois** [comment]
> a number of older versioned k8s clusters.

Are these old clusters running with Rancher Desktop or elsewhere? I thought we would force-upgrade clusters to the oldest still supported version (1.21.0?) if you upgrade Rancher Desktop to a recent release.

**Comment by Paragon1970** [comment]
Clusters are running elsewhere, but also employ local pods running under rancher-desktop managed kubernetes for helper apps, local deployments for testing etc. The workaround provided, provides for me at least, the convenience of employing Ranchers kubectl switching, since we manage a large number of cluster spread across multiple cluster versions.

Rancher version 1.18.0 (with automatic updates)

**Comment by praveenprem** [comment]
> [@praveenprem](https://github.com/praveenprem) Do you have a `~/.kuberlr/kuberlr.conf` or `/etc/kuberlr.conf` file on your system?
> 
> I think `kuberlr` would download by default from `dl.k8s.io` and not from `storage.googleapis.com`, which has been deprecated for a while.

@jandubois apologies for the late response, no I don't have those file on my system.

**Comment by jandubois** [comment]
Thanks @praveenprem! Is the issue for you resolved as well, or do you still run into this? If yes, maybe open a new issue with the details for your setup?

**Comment by praveenprem** [comment]
@jandubois I is a still an issue on Rancher `1.12.x` but after upgrading the Rancher to `1.18.2` the error went away so it's working now
