### ISSUE TITLE
nerdctl: build fails to include basic commands such as COPY

### ISSUE THREAD

**Issue by bwdmr** [rancher-sandbox/rancher-desktop#7923]
### Actual Behavior

containerd api does not interpret the dockerfile correctly

### Steps to Reproduce

```Dockerfile
FROM ubuntu:20.04

# Ensure necessary utilities are installed
RUN apt-get update && apt-get install -y coreutils

# Create a non-root user
RUN useradd -m -s /bin/bash dev

COPY ./entrypoint.sh /entrypoint.sh
RUN chown dev /entrypoint.sh

USER dev
WORKDIR /home/dev

# Ensure /dev/null exists
#RUN mknod -m 666 /dev/null c 1 3

# Set entrypoint with explicit path
ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
```

disable kubernetes. 
enable docker: success
disable kubernetes
enable containerd: success
enable kubernetes
enable containerd: fail

### Result

i cant tell what fails. it just stops working if kubernetes runs. and works if not.

### Expected Behavior

the containerd api to interpret the dockerfile correctly.

### Rancher Desktop Version

1.16.0

### Rancher Desktop K8s Version

1.30.6

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by bwdmr** [comment]
if you wondering. entrypoint is just `#/bin/bash echo hello`

**Comment by jandubois** [comment]
I cannot reproduce the issue:

<img width="1260" alt="CleanShot 2024-12-11 at 11 04 47@2x" src="https://github.com/user-attachments/assets/0f937b42-aae1-474f-aaf2-03a9b3a5bb1e" />

**Comment by jandubois** [comment]
@bwdmr We need additional information to do anything further. Please capture both the exact commands you run and the error messages you get from `nerctl build` and/or `nerdctl run`!

Can you also enable debug logging (on the Troubleshooting page) and after you reproduce the failure, collect and attach the logs?

And, are you running the `nerdctl build` command always from the same directory, and is the directory somewhere under your home directory?

**Comment by bwdmr** [comment]
closed.  i rebuilt and can confirm it works as described by you.
thanks for the quick reply.
