### ISSUE TITLE
Multi-Arch Build Support

### ISSUE THREAD

**Issue by madudding** [rancher-sandbox/rancher-desktop#798]
### Enhancement Request

Multi-arch build system equivalent to docker desktop (example docker buildx)  

[Use Case Example](https://www.docker.com/blog/multi-arch-images/ #)

**Comment by buu700** [comment]
I'm very interested in this as well, as it's currently a blocker for switching away from Docker Desktop. At a minimum, a partial implementation of the buildx API with no multi-arch support would be enough for us to get started using Rancher.

**Comment by jandubois** [comment]
I believe this is all implemented already.
