### ISSUE TITLE
Snapshot does not restore on Windows

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#7983]
### Actual Behavior

When attempting to restore a snapshot from UI, Rancher Desktop get stuck and it eventually times out (causing an error).

### Steps to Reproduce

1. Create a snapshot.
2. Restore the snapshot from UI.

### Result

Attempting to create the snapshot fails; it eventually times out.
![image](https://github.com/user-attachments/assets/e5bfcb1e-8445-418c-ac78-57314f6079d1)

### Expected Behavior

The snapshot should be ignored.

### Additional Information

This was from Qase test case RD-174.
[logs](https://github.com/user-attachments/files/18203184/logs.zip) from starting snapshot from UI.

Trying to run the snapshot from UI:
```
> rdctl snapshot restore --verbose Snap1
Error: failed to restore snapshot "Snap1": error waiting for backend to stop: timed out waiting for backend state in [STOPPED]
```

So the issue is probably (from `background.log`):
```
2024-12-19T21:04:08.510Z: UnhandledRejectionWarning: c [Error]: wsl.exe exited with code 1
    at ChildProcess.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:2:185146)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  command: [
    'wsl.exe',
    '--distribution',
    'rancher-desktop',
    '--exec',
    '/usr/bin/killall',
    '-q',
    '/usr/local/bin/network-setup'
  ],
  code: 1,
  [Symbol(child-process.command)]: 'wsl.exe --distribution rancher-desktop --exec /usr/bin/killall -q /usr/local/bin/network-setup'
}
```

It looks like the issue is that while `killall -q` suppresses error messages, it does _not_ affect the exit code; it's still returning non-zero when the process does not exist.
https://github.com/mirror/busybox/blob/1a64f6a20aaf6ea4dbba68bbfa8cc1ab7e5c57c4/procps/kill.c#L293-L295

### Rancher Desktop Version

1.17.0-hackweek-release-261-gbc7bc499b

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 24H2 (Build 26100.2605)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
It looks like this was supposed to be closed by #7985
