### ISSUE TITLE
Nerdctl load not working

### ISSUE THREAD

**Issue by sbaier1** [rancher-sandbox/rancher-desktop#801]
**For bugs, describe what you're seeing**
nerdctl does not lead to images being available in rancher-desktop's k3s cluster.
I'd expect to be able to load tars to the cluster so i can use source2image tools like [jib](https://github.com/GoogleContainerTools/jib), which build images directly instead of using a build-daemon.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a `cat <some-image.tar> | nerdctl load`, which should succeed.
2. `kubectl run --image <the-image-name> nerdctl-test`
3. `kubectl get pods -w`
4. The Pod goes into `ErrImageNeverPull` because the image is not available

FWIW, in my case the original build command was `./gradlew jibDockerBuild -Djib.dockerClient.executable=$(which nerdctl)`, which is pretty much equivalent to building a tar and then piping it to `nerdctl load` though.

**Result**
Images that are created using `nerdctl load` are not usable in the cluster

**Expected behaviour**
I can load a image using `nerdctl load` and then run it as if it were already present in the cluster

**Screenshots**
The behavior above describes it entirely IMO.

**Setup (please complete the following information):**
 - OS: macOS 11.6
 - Rancher Desktop version: 0.5.0 (Getting DNS errors with 0.6.0 so difficult to test anything with it)
 - Kubernetes version: Used the latest version at the time of creating the VM `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by jandubois** [comment]
I think `nerdctl load` will load the image into the `default` namespace. you need to use `nerdctl -n k8s.io load` to load them into the `k8s.io` namespace (these are containerd namespaces, not kubernetes namespaces).

**Comment by sbaier1** [comment]
See my last comment, it is actually working as expected. My bad.
