### ISSUE TITLE
Linux Upgrades

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#806]
On Linux we currently have deb/rpm as install options while we are also working on AppImage. This feature is to provide an upgrade mechanism for each of the Linux install options we provide. For example, for deb/rpm this would likely be appropriate repos.

**Comment by gaktive** [comment]
This should be working now, so we should document the steps involved here.

**Comment by mattfarina** [comment]
To review, we should test the RPM, deb, and appimage for both the dev and stable channels.

**Comment by gaktive** [comment]
#1120 has follow-up work tied to AppImage.
