### ISSUE TITLE
Configure k3s to (optionally) use the dockerd socket, so it can use images built by `docker build`

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#814]

**Comment by jandubois** [comment]
To run `k3s` with the docker runtime, we have to add the `--docker` option to the `k3s server` command in `src/assets/scripts/service-k3s`:

```
command_args="server --docker --https-listen-port 6443 >>/var/log/k3s 2>&1"
```

**Comment by jandubois** [comment]
Another change we need is the list of supporting utilities: for `containerd` we provide `kim` and `nerdctl`. For `dockerd` we provide `docker` (cli). For both we provide `kubectl` (via `kuberlr`).

**Comment by jandubois** [comment]
> * dockerd just by itself

This configuration is out-of-scope for the 0.7.0 release.
