### ISSUE TITLE
[macOs/Linux - UI] K8s Settings slider component glitch

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#817]
**For bugs, describe what you're seeing**
There's a small cosmetic glitch on memory slider component, going outside of the component area.

**To Reproduce**
1. Install latest RD package version: https://github.com/rancher-sandbox/rancher-desktop/actions/runs/1339584460
2. Click on Kubernetes Settings
3. Check the slider component error

**Result**
![Screen Shot 2021-10-15 at 5 00 51 PM](https://user-images.githubusercontent.com/37411123/137562825-f44f6439-d435-493b-a3ab-d03669dce0c0.png)

**Expected behaviour**
Memory slider should be same as CPU slider component:

![Screen Shot 2021-10-15 at 5 04 07 PM](https://user-images.githubusercontent.com/37411123/137562981-d57938b9-3db2-4571-b723-6c4de3fc35d7.png)

**Screenshots**
![Screen Shot 2021-10-15 at 4 57 50 PM](https://user-images.githubusercontent.com/37411123/137562689-28def5a8-2678-46df-8460-39011a2cfa37.png)

**Setup (please complete the following information):**
 - OS: `Linux Ubuntu 20.04.3 LTS`
 - Rancher Desktop: `0.6.0-14-geda4c6e`
 - Kubernetes version: `1.21.5`

**Additional context**
N/A

**Comment by jandubois** [comment]
> Maybe we can set a minimum value for each distro, e.g: Linux/Win/MAC: 4GB

I think it is reasonable to require 8GB, at least on macOS, and probably Windows, as well as at least 4 CPU threads.

While it may be technically possible to squeeze it into a smaller machine, it will not be useful to run any workloads.

**Comment by mattfarina** [comment]
@jandubois I generally agree with you on minimum memory of 8GB. It's difficult to find a system that does not have that these days. Running VMs in less than 8GB is going to run into issues.

I discovered this issue when I was testing on Linux. I'd given a VM 6GB of memory to test RD. Nested VMs! This issue came up visually.
