### ISSUE TITLE
[Suggestion] Windows Terminal profile

### ISSUE THREAD

**Issue by nunix** [rancher-sandbox/rancher-desktop#818]
**For bugs, describe what you're seeing**
By default, both WSL distros (`Rancher Desktop` and `Rancher Desktop Data`) are listed in Windows Terminal due to the automatic scan of WSL distros.
Not sure this is the wanted behavior, however when compared to `Docker Desktop`, their WSL distros are not listed.

**For feature requests, describe what you'd like to add or change**
Depending on what wants to be achieved by the Dev team, there could be two options for a better user experience:
1. Hide/Delete both entries from the Windows Terminal (and Preview) profile (Windows path: %USERPROFILE%\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal*\\LocalState\\settings.json)
2. Only hide/delete the `Rancher Desktop Data` WSL distro entry as the user can't/shouldn't work with it and let the `Rancher Desktop` available (might be helpful for some debugging)

**To Reproduce**
Steps to reproduce the behaviour:
1. Have Windows Terminal installed
2. Have Rancher Desktop installed
3. Open a new instance of Windows Terminal and click on the profile selector icon

**Result**
![image](https://user-images.githubusercontent.com/905874/137628820-bcdcd3f6-dce3-4f3f-a2f1-e8613226c9b4.png)

**Expected behaviour**
As stated above, either both or the `Rancher Desktop Data` should not appear

**Screenshots**
See above

**Setup (please complete the following information):**
 - OS: Windows 11
 - Terminal: Windows Terminal and Windows Terminal Preview
 - Rancher Desktop version: 0.6.0
 - Kubernetes version: n/a (or applicable to all)

Thanks a lot for your support.

**Comment by nunix** [comment]
Thanks a lot for the feedback. It might be a good feature for Windows Terminal then, I will open an issue there.

**Comment by mook-as** [comment]
So if I'm understanding things correctly, the profile GUID for our WSL distributions will be based on the distro name (and therefore effectively constant for us), and we can just drop JSON files in the appropriate places and things will apply automatically for us?

If that's the case, that should be doable on our side (even if it takes a while for us to get to it).  Thanks!

**Comment by zadjii-msft** [comment]
> the profile GUID for our WSL distributions will be based on the distro name (and therefore effectively constant for us)

Yep! That's the contract that some other distros are already reliant on, so we're not about to change that.

**Comment by jandubois** [comment]
The Rancher Desktop distros are no longer listed in Windows Terminal: https://github.com/microsoft/terminal/pull/15166
