### ISSUE TITLE
Cannot build Dockerfile

### ISSUE THREAD

**Issue by yarons** [rancher-sandbox/rancher-desktop#823]
I've written the name next to the `Build Image…` button.
Then clicked the button, selected the relevant `Dockerfile` and I'm getting an error as if it's trying to compile the directory instead of the `Dockerfile` itself (The hint is the stat).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Preferences'
2. Click on 'Images'
3. Scroll down to 'Image Acqusition'
4. Type in the image name
5. Click the 'Build Image…' button

**Result**

```shell
error: could not find /Users/yaron/Documents/mydocker/: stat /Users/yaron/Documents/mydocker/: no such file or directory
time="2021-10-17T08:03:15Z" level=fatal msg="unrecognized image format"
```

**Expected behaviour**
Should have been build

**Setup (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Rancher Desktop 0.6.0
 - Kubernetes 1.21.5

**Additional context**
This is the `Dockerfile`:
```Dockerfile
FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
```

**Comment by tehho** [comment]
Have the same problem on Pop!_OS 21.04.
My repo is on an external drive with NTFS, legacy from windows days.

Pointing to the repo directly: "ash: cd: line 1: can't cd to /media/$usr/$diskid/dev/repo: No such file or directory"
Symlink to ~/repo: "ash: cd: line 1: can't cd to /media/$usr/$diskid/dev/repo: No such file or directory"
cp to ~/repo: Works :tada:

**Comment by rak-phillip** [comment]
@yarons I haven't been able to replicate your issue against my Documents directory, but could produce something very similar to the second example given with a network volume. 

I have a hunch that this is might be permissions issue. Do you recall if you were prompted to provide access to your documents directory before building an image? 

![Screen Shot 2021-12-07 at 1 08 28 PM](https://user-images.githubusercontent.com/835961/145102679-36588c2b-76dc-42e9-8b0a-ed8081a16e3f.png)

Can you also check to see if Rancher Desktop has an entry in System Preferences => Security & Privacy => Files and Folders?

![Screen Shot 2021-12-07 at 1 11 08 PM](https://user-images.githubusercontent.com/835961/145102957-6e075563-44e0-4a7e-9732-a1745d0ddc8e.png)

**Comment by rak-phillip** [comment]
Another possibility is that the home directory mount might be getting dropped after leaving Rancher Desktop running for a prolonged period, as described in #823

**Comment by ericpromislow** [comment]
Is this still an issue with a beta of 1.0.0?

Is a network drive involved?

And our underlying container technologies have changed since version 0.6.0 -- so does this happen when you're using `containerd` (the default), `moby`, or both?

**Comment by ericpromislow** [comment]
I'm closing this issue now because it's against an older version (two), but please feel free to reopen it if it still applies to current versions.
