### ISSUE TITLE
Windows Installer: Work with PowerShell Constrained Language mode

### ISSUE THREAD

**Issue by ngauje** [rancher-sandbox/rancher-desktop#828]
**For bugs, describe what you're seeing**
After a clean install on windows (20H2), the windows PATH is not updated.

Tools are correctly installed here : `C:\Users\username\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\bin`
```
C:\Users\username\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\bin>kubectl.exe get node
NAME           STATUS   ROLES            AGE    VERSION
hostname   Ready    builder,master   113d   v1.19.11+k3s1
```

Note: I use a corporate laptop with a standard user. Not windows popup asking for elevated rights was proposed, maybe it should be needed to update the PATH?
Note2: My terminal was open **after** RD installation

**Comment by mook-as** [comment]
We no longer use PowerShell in the installer (we have a signed DLL instead), see #5875
