### ISSUE TITLE
The cluster loses time while the machine is in a sleep state

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#839]
I have been using several services within k3s deployments including rancher-desktop and kim. Because I am running on a laptop the clock within various containers inside the cluster looses time while the machine is in a sleep state.

If I try to use ntpdate to synchronize things within containers I get issues with privileges and if I try to reset the clocks using hwclock also within containers I only ever see the delayed time that is affected by the host OS sleeping.

Some pods/containers I have benefit from having an ntpd deployment but the system pods etc never seem to recover the lost time.

How are we meant to be getting our clocks back into sync after sleeping etc ?

Question also asked at https://github.com/k3s-io/k3s/discussions/4256.  Given laptops etc are a prime use case for rancher desktop I'm not sure resetting Kubernetes is viable everytime the laptop sleeps.

_Originally posted by @karlmutch in https://github.com/rancher-sandbox/rancher-desktop/discussions/836_

**Comment by jandubois** [comment]
I think this requires running the `qemu-guest-agent` inside the VM to keep the time in sync.

**Comment by gereonvey** [comment]
When building documentation using RD, make complains about clock slew. 
```
$ nerdctl run --rm -it --volume ${PWD}:/usr/src/app --workdir /usr/src/app susedoc/ci:latest /bin/bash -c "daps -d DC-topicXYZ pdf --draft"
make: Warning: File '/usr/src/app/build/.adoc/topicXYZ.xml' has modification time 0.17 s in the future
PDF book built with REMARKS=0, DRAFT=yes and META=0:
/usr/src/app/build/topicXYZ/topicXYZ_color_draft_en.pdf
make: warning:  Clock skew detected.  Your build may be incomplete.
$
```
There is no sleeping involved. When I start RD, build a couple of times (<10) one after the other, it happens once or twice. Not related to the RD (re-)start, just want to point out that it's even happening with a „fresh“ RD.

So the clock inside the VM seems to run out of sync with the OS clock even when not sleeping.
