### ISSUE TITLE
Kubernetes was unable to start: ReferenceError: Electron is not defined

### ISSUE THREAD

**Issue by jachninja** [rancher-sandbox/rancher-desktop#840]
I tried Rancher Desktop V 0.6.0 on Windows today, but I was not able to make it work. It starts properly, downloading Kubernetes, certificates, etc. But then it fails with a windows that says

Kubernetes was unable to start: ReferenceError: Electron is not defined

The background.log file contains basically the same information:
```
k8s-current-port: 6443
Kubernetes was unable to start: ReferenceError: Electron is not defined
    at new yt (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:14:119345)
    at new ClientRequest (_http_client.js:129:13)
    at TunnelingAgent.request (http.js:50:10)
    etc.
```

I'm wondering if I'm missing an env variable or something similar.

**Comment by dirk-olmes** [comment]
I get the same error but only if I have an environment variable "http_proxy" defined. After I removed it rancher desktop started normally.
