### ISSUE TITLE
[AppImage] When exiting the application links in ~/.local/bin are removed even when managed by another app

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#848]
**For bugs, describe what you're seeing**
Let's say I have a symlink to helm in ~/.local/bin that isn't managed by RD via the AppImage. When I exit Rancher Desktop, this symlink is deleted along with kubectl, helm, kim, and nerdctl. It shouldn't be.

Note, we aren't currently shipping an AppImage. This is experimental.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get or build an AppImage for Rancher Desktop
2. For one of the tools that we include linking support for (i.e., kubectl, helm, kim, nerdctl) create a link to something not related to Rancher Desktop.
3. Start and then exit RD.
4. See that the symlink is gone.

**Expected behaviour**
Symlinks should only be deleted if RD created it.

**Setup (please complete the following information):**
 - OS: Linux
 - Rancher Desktop version: main
 - Kubernetes version: N/A

**Comment by adamkpickering** [comment]
I've noticed a related problem with the AppImage. On the first run after a factory reset, all of the binaries (helm, kubectl etc) will be there. But after exiting RD and starting it up again, they are gone. This is solvable by going into the Supporting Utilities tab and checking the boxes of the binaries you want to be present, but the user should not have to worry about this.

**Comment by adamkpickering** [comment]
Also, a related problem: the code David refers to above predates the docker integration, so there is no line to remove the `docker` symlink upon exit. Thus, it is left dangling.
