### ISSUE TITLE
Add app-level end-to-end testing

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#86]
Pulling UI-testing out of issue #54 because it's a completely different animal.

**Comment by ericpromislow** [comment]
See https://raw.githubusercontent.com/KYDronePilot/SpaceEye/master/test/e2e/example.spec.ts for an example of a spectron-based UI test.

On first look, the problem running this test out of the box with this code:
```
import * as electronPath from 'electron';
import { Application } from 'spectron';
…
describe() {...
 beforeEach(() => {
    app = new Application({
      path: electronPath.toString(),
      args: [path.join(__dirname, '..', '..')]
    });
    
 ```
 We don't know what the arguments to `new Application` should be, but the current `electronPath.toString()` doesn't work for `rd`.

This task should be done as a 2-day spike. It could be that solving one problem just opens the next one. Or things will work, and then the tests can become more ambitious.

**Comment by ericpromislow** [comment]
Other references:

https://github.com/TheCowKingmoo/Spectron_Typescript/ (Guna got this to work)

https://github.com/balena-io/etcher - no one got this to work yet

**Comment by ericpromislow** [comment]
Another note: running the following in an interactive shell led to two problems:
```
s = require('spectron')
app = new s.Application({path: 'dist/mac/Rancher\ Desktop.app/Contents/MacOS/Rancher Desktop'})
app.start()
```

The UI did start up, but the permissions box did as well, but it kept erasing my password.
Meanwhile, a large number of other `Rancher Desktop` processes were spawned, and a pile of little Rancher Desktop icons appeared in the lower right of the screen.  So in other words, the app didn't start up in a well-controlled state.
But we might have the start of a useful e2e test here.

Needed to use this command to shut everything down:

```
ps auxww | grep 'Rancher Deskt' | awk '{print $2}' | xargs kill -9
```

**Comment by mook-as** [comment]
We have some tests from #425 that is invoked by `npm run test:e2e`.  This is not yet on CI.

**Comment by gaktive** [comment]
@evertonlperes may have implemented part of this as part of his CI work.

**Comment by evertonlperes** [comment]
> @evertonlperes may have implemented part of this as part of his CI work.

Yep.
The E2E pipeline still running at my forked repository in order to collect data. We still need to enable `cirrus-ci` on upstream repository. Someone with admin access could do this. Let's chat tomorrow during the daily.

All E2E/QA work, could be tracked on this epic https://github.com/rancher-sandbox/rancher-desktop/issues/996

**Comment by prabalsharma** [comment]
I think this is done and can be closed.
