### ISSUE TITLE
Improve the "unknown error starting Kubernetes" dialog

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#871]
This dialog typically does not include any useful information, but just something like "wsl.exe terminated with 12345678".

I think we had an issue to improve the data written to the logs, but this still doesn't really help: Virtually every report of this error, either here on Github or on Slack includes a screenshot of the dialog, but no additional log files.

So I think the dialog body should be extended significantly. Include all of:

* RD version, k3s version
* The actual wsl command RD was trying to run
* The last 10 lines of stderr from the failing command (may need to tweak that later)

This should reduce the number of interactions from the bug being reported until we have enough information to investigate (or determine that it is a duplicate of an already fixed issue).

**Comment by evertonlperes** [comment]
Here's another reference of the error message: https://github.com/rancher-sandbox/rancher-desktop/issues/968
