### ISSUE TITLE
[Linux] Supporting Utilities - symlinks does not work

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#881]
After install RD `0.6.0` on openSUSE Leap, the supporting utilities symlink does not work properly. Executing commands from `konsole` like: `kubectl` , `nerdctl` and/or `helm`, the symlink does not resolve the path.
Even though the tools are correctly installed into the system, you need to pass the entire tool path to get it working:
e.g: `/home/test/.local/bin/kubectl version` - instead just `kubectl version`

**To Reproduce**
--> Fresh openSUSE Leap install (VMBox nested virtualization ON)
1. Download latest development RD rpm package from GitActions
2. Install using sudo zypper install [RD-Dev-Package].rpm
3. Open rancher-desktop
4. Wait until the app being loaded
5. Open the terminal and type: `kubectl version` or `helm version`
6. Should see the following error: see results

**Result**
```bash
localhost:/home/test # kubectl version
If 'kubectl' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf kubectl
localhost:/home/test # helm version
If 'helm' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf helm
localhost:/home/test # nerdctl ps
If 'nerdctl' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf nerdctl
localhost:/home/test # kim version
If 'kim' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf kim
localhost:/home/test # 
```

**Expected behaviour**
Running supporting tools from terminal without passing the entire file path.

**Screenshots**
Without full path:
![Screen Shot 2021-10-28 at 2 23 13 PM](https://user-images.githubusercontent.com/37411123/139329956-1630c4e5-4258-4336-9ae6-54508e29bfb4.png)

With full path:
![Screen Shot 2021-10-28 at 2 34 51 PM](https://user-images.githubusercontent.com/37411123/139331546-9f383657-7f37-456a-bd1d-d5ede55e238a.png)

**Logs**
[symlink_RD_060_logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/7437225/symlink_RD_060_logs.zip)

**Setup (please complete the following information):**
- OS: `openSUSE Leap 15.3`
- KDE Plasma: `5.18.6`
- Rancher Desktop version: `0.6.0`
- Kubernetes version: `1.21.5`

**Additional context**
N/A

**Comment by juliogonzalez** [comment]
> This is because `$HOME/.local/bin` is not part of your default distro `$PATH`. As an example common distro `$PATH` are:
> 
> openSUSE Leap: `$HOME/bin:/usr/local/bin:/usr/bin:/bin` 
> Ubuntu 21.04: `$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin` 

On Debian and Ubuntu `$HOME/bin` is only added to `PATH` if the directory exists.

However, at least on Debian10 and Debian11, I do not have `$HOME/.local/bin` at `PATH` (servers, no GUI). I checked Ubuntu 20.04 and 21.04 using Docker containers and the same happens.

Something tells me that `$HOME/.local/bin` get added to `PATH` by a package that installs files at `/etc/profile.d`.

Did you check with a machine that as GUI?

> Fedora 34: `$HOME/.local/bin:$HOME/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin`
> 
> Note there is not a common path under $HOME for all these three distros. When I coded that part I took the path `~/.local/bin` since this is aligned with [XDG Base Directory specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
> 
> ```
> User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place.
> ```
> 
> and this is already followed, at least, by Fedora and Ubuntu. I have no idea why openSUSE is not including this path...
> 
> In order to facilitate user interaction we could add some logic in RD to discover any path under $HOME as part of $PATH and then use that and treat `~/.local/bin` as the default fallback if none is found.

Since this is a desktop application, I think this should be fixed somewhere at openSUSE.

FMPOV the best approach is fixing the package `aaa_base` to add `~/.local/bin` to `PATH` if the directory exists, as in the end the package already checks a lot of other directories (`/etc/profile`):
```
if test -z "$PROFILEREAD" ; then
    PATH=/usr/local/bin:/usr/bin:/bin
    if test "$HOME" != "/" ; then
        for dir in $HOME/bin/$CPU $HOME/bin ; do
            test -d $dir && PATH=$dir:$PATH
        done
    fi
    if test "$UID" = 0 ; then
        test -d /opt/kde3/sbin  && PATH=/opt/kde3/sbin:$PATH
        PATH=/sbin:/usr/sbin:/usr/local/sbin:$PATH
    fi
    for dir in  /usr/X11/bin \
                /usr/X11R6/bin \
                /var/lib/dosemu \
                /usr/games \
                /opt/bin \
                /opt/kde3/bin \
                /opt/kde2/bin \
                /opt/kde/bin \
                /usr/openwin/bin \
                /opt/cross/bin
    do
        test -d $dir && PATH=$PATH:$dir
    done
    unset dir
    export PATH
fi
```
@davidcassany @evertonlperes  I will try to prepare submit requests for openSUSE Factory (tumbleweed), Leap 15.3, and maybe 15.2

Then users will just need to close their session and open it again to get `~/.local/bin` as part of `PATH`

Rancher Desktop can still merge the PR, of course, but FMPOV this looks like a problem to be fixed on the affected distributions :-)

**Comment by davidcassany** [comment]
> Did you check with a machine that as GUI?

Yes we did all tests with GUI


> @davidcassany @evertonlperes  I will try to prepare submit requests for openSUSE Factory (tumbleweed), Leap 15.3, and maybe 15.2
> 
> Then users will just need to close their session and open it again to get `~/.local/bin` as part of `PATH`

Awesome, I already see the fix you sent is merged. I agree with you that having it fixed within the distro is a better approach.

**Comment by juliogonzalez** [comment]
Hello,

The Maintenance Update for `aaa_base` took longer than expected, as it had to be merged with another fix that required some validation.

But I am happy to announce that `aaa_base` version `84.87+git20180409.04c9dae-3.52.1` and contains:
```
* mié nov 03 2021 jgonzalez@suse.com
- Add git-36-16d1cb895c2742e96a56af98111f8281bedd3188.patch:
  * Add $HOME/.local/bin to PATH, if it exists (bsc#1192248)
```
So the problem should be fixed now. If @evertonlperes can validate, I guess this issue can be closed (warning: you will need to close and start your session again, after you update the package)

**Comment by evertonlperes** [comment]
@juliogonzalez Thanks for the feedback.

The issue was fixed by the OS update.
All RD symlinks are working properly and we don't need to manually add the PATH 🎉 

For Tumbleweed, I'll double-check the PATH fix, but I cannot test RD integration due this issue: https://github.com/rancher-sandbox/rancher-desktop/issues/749

Tagging @adamkpickering on this thread (fyi).

Closing this issue.
