### ISSUE TITLE
WSL: make host.docker.internal work

### ISSUE THREAD

**Issue by ppiotrow** [rancher-sandbox/rancher-desktop#893]
**For feature requests, describe what you'd like to add or change**
host.docker.internal works and behaves like in Docker Desktop
https://docs.docker.com/desktop/windows/networking/

**Comment by mattfarina** [comment]
Ports are mapped to localhost. Have you tried connecting to your containers on localhost?

**Comment by ppiotrow** [comment]
kubectl port-forward -n minio-app service/minio 10101:80
I can open localhost:10101 on my local macOS machine but I'm unable to reach `localhost:10101` from inside running container. With Docker Desktop I could connect to `host.docker.internal:10101` from inside container.

**Comment by jandubois** [comment]
@ppiotrow Please confirm that this is about the Windows version. I assume @mattfarina has set the `platform/windows` label based on you providing a URL to Docker for Windows, but I want to make sure we are all talking about the same platform.

**Comment by ppiotrow** [comment]
I'm on MacOS

**Comment by alsolh** [comment]
i am on windows and the host is not reachable from within a container, any changes I need to do after installing rancher desktop?
![image](https://user-images.githubusercontent.com/22778662/140615352-a223aa16-a02a-4820-91dc-42dad9b0df07.png)

**Comment by djfoxer** [comment]
Any update about how to call host (Windows) from container? If `host.docker.internal` isn't available, maybe there is any workaround for that?

**Comment by jandubois** [comment]
> I'm on MacOS

On macOS you can currently use `host.lima.internal`.

We should implement `host.docker.internal` for compatibility on all platforms.

**Comment by jandubois** [comment]
On Windows it looks like the recommended way to determine the host IP is to extract it from `/etc/resolv.conf` from the `nameserver` field:

```
export HOST_IP=$(cat /etc/resolv.conf | grep nameserver | cut -d ' ' -f 2)
```

**Comment by jandubois** [comment]
From https://rancher-users.slack.com/archives/C0200L1N1MM/p1638473475311400?thread_ts=1634560787.294400&cid=C0200L1N1MM:

>Thanks, but none of those worked for me, but I found that if I used any of the ips from the `wsl -d rancher-desktop ip route`, it works.

**Comment by jandubois** [comment]
See also https://github.com/rancher-sandbox/rancher-desktop/pull/1000#issuecomment-985804525

**Comment by mook-as** [comment]
For WSL, it looks like (assuming it's [generating `/etc/hosts`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#network-settings)) it copies over the system hosts file; this means we "just" need to fix it on the Windows side. However, that's only writable by administrators…

**Comment by dougbreaux** [comment]
Another way to get the IP that works for me:
```
netsh interface IP show addresses "vEthernet (WSL)"
```
Or filter further with
```
netsh interface IP show addresses "vEthernet (WSL)" | findstr "IP"
```

**Comment by mook-as** [comment]
If we only update the hosts file in the rancher-desktop distribution, then we won't need to elevate, but that means you can't connect to it from Windows / other WSL distributions.

If we _do_ update it system-wide, then we'll need administrator privileges (which probably means we want to have a Windows service that the front end can start).  We can [set the service permissions](https://docs.microsoft.com/en-us/windows/win32/services/modifying-the-dacl-for-a-service) if necessary.  However, that would mean we need to install the application as an administrator (so there will be some migration).  This will probably not happen in the short term.

I'll get started on the first (container-only) solution, at least.

**Comment by gaktive** [comment]
This also needs to be investigated for macos in a separate ticket.

**Comment by jandubois** [comment]
> Could that same, or similar, fix be adopted in Rancher Desktop in order to make host.docker.internal work in a similar way?

I believe we have a working solution for `host.docker.internal` in the next release, so I don't think we are looking for an alternate solution, unless there is something wrong with the current (new) approach.

For the release after the next we are likely to switch to a different stub resolver, that is already used on Rancher Desktop for Linux and macOS, which will handle lookup with split-DNS configurations correctly. That one will also have support for `host.docker.internal` built-in.

**Comment by kingrichard2005** [comment]
> > Could that same, or similar, fix be adopted in Rancher Desktop in order to make host.docker.internal work in a similar way?
> 
> I believe we have a working solution for `host.docker.internal` in the next release, so I don't think we are looking for an alternate solution, unless there is something wrong with the current (new) approach.
> 
> For the release after the next we are likely to switch to a different stub resolver, that is already used on Rancher Desktop for Linux and macOS, which will handle lookup with split-DNS configurations correctly. That one will also have support for `host.docker.internal` built-in.

Really appreciate the quick follow-up @jandubois and great to hear this will be resolved in the next release of Rancher Desktop.  I'm helping test Rancher Desktop for my team and DNS issues when pulling from our group's private image repos over our VPN is the main item I'm having issues with and is keeping me coming back to Docker Desktop.  

Also just clarifying, but is "the current (new) approach" referring to having to edit the `/etc/hosts` file?

**Comment by jandubois** [comment]
> Also just clarifying, but is "the current (new) approach" referring to having to edit the `/etc/hosts` file?

No, on Windows we will be running dnsmasq inside the distro, and the name will will be defined in the dnsmasq config file. /etc/resolv.conf inside the distro will point to this dnsmasq instance, so the name will be resolved before we ever need to query the Windows /etc/hosts. We also filter the Windows /etc/host to make sure none the `host.docker.internal` name will not be imported into the `/etc/hosts` inside the distro.

**Comment by dougbreaux** [comment]
I definitely have this resolving under a Rancher Desktop shell, and I _thought_ it resolved under my container running under RD at one point, but it definitely isn't now...

It might be that it resolved when I first ran `nerdctl run...`, but not now when running `nerdctl start` to restart a container I'd stopped earlier.

**Comment by wesleyscholl** [comment]
> > I'm on MacOS
> 
> On macOS you can currently use `host.lima.internal`.
> 
> We should implement `host.docker.internal` for compatibility on all platforms.

Thank you for this, I've been searching for a solution for more than a month. Finally I can talk to localhost!
