### ISSUE TITLE
App doesn't have a restart button

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#895]
When RD installs an update, it just says: "You must restart the app to run the new version".

But how do I do that? Terminate the app and then run it again? Why isn't there button to click that just does this?

**Comment by jsoref** [comment]
For my reference, this is the item in question:
![image](https://user-images.githubusercontent.com/2119212/151262113-202a8361-c4ae-4855-a360-c37aa4dd454e.png)

https://github.com/rancher-sandbox/rancher-desktop/blob/bb7b74cf34f7b23f9b1091e4cb389939b0aad883/src/components/UpdateStatus.vue#L22
