### ISSUE TITLE
Ability to toggle between moby & nerdctl

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#900]
In support of our overall epic story about getting Docker into Rancher Desktop (https://github.com/rancher-sandbox/rancher-desktop/issues/673), we need a way to allow users to select which runtime engine to use: moby or nerdctl.

Upon selection, they'll get the related CLI. Phil to sort out the design and then spawn other tickets for engineers to work on.

If this is changed, this would require a restart of the engine. 

Down the road, we'll need to consider cleanup; for now, abandoning the older images is fine, aside from a factory reset.

**Comment by gaktive** [comment]
Dependent on #814

**Comment by ericpromislow** [comment]
Merged in https://github.com/rancher-sandbox/rancher-desktop/commit/1df436eab3b0e6d15e9bf426ff09f81f43675bc3
