### ISSUE TITLE
Update to latest nerdctl

### ISSUE THREAD

**Issue by markgarrigan** [rancher-sandbox/rancher-desktop#907]
Is there a way to update to the latest nerdctl? Mac OS Catalina v10.15.7

Currently installed via Rancher Desktop 0.12.1
Current nerdctl version 0.13.0

Thanks!

**Comment by jandubois** [comment]
> Is there a way to update to the latest nerdctl? Mac OS Catalina v10.15.7

Let me just cut & paste what I wrote within the last hour on Slack 😄 

<hr>

There is no supported way to do it, but you can, if you are willing to do it manually (if you break something, you get to keep all the pieces). First start a shell inside the VM:

```
LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0
```

Inside the VM install `curl` and then download and overwrite `nerdctl`:

```
sudo apk add curl
curl -sfL https://github.com/containerd/nerdctl/releases/download/v0.13.0/nerdctl-0.13.0-linux-amd64.tar.gz | sudo tar xz -C /usr/local/bin -f -
```

Exit the shell and it should work now:

```console
$ nerdctl --version
nerdctl version 0.13.0
```

**Comment by jandubois** [comment]
I'm going to close this issue, as there isn't really any action left we need to take. `nerdctl` will be updated in the next release.
