### ISSUE TITLE
Nerdctl failed to create LLB definition when using PulseSecure VPN

### ISSUE THREAD

**Issue by wstr-ncrum** [rancher-sandbox/rancher-desktop#912]
**For bugs, describe what you're seeing**

When building a docker image that uses mcr.microsoft.com/dotnet/aspnet:5.0-focal while connected to a Pulse Secure VPN client I receive the following error

![image](https://user-images.githubusercontent.com/81775318/140527171-6101f52a-0aa7-4c89-bcc3-6cd801c8b45c.png)

However building the same dockerfile on the same VPN with Docker Desktop works fine. Our Network team even did a packet capture and the error occurred without any network traffic being blocked on the network side.

If I am not using the Pulse Secure client nerdctl works. If I use one of our other VPN clients like Fortinet Nerdctl works. It is only when used with Pulse Secure that I get the error above.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to VPN using Pulse Secure client (Tunnel Type: VPN; VPN Type: ESP;)
2. attempt to build a docker file with Nerdctl that uses a microsoft image such as mcr.microsoft.com/dotnet/aspnet:5.0-focal
3. build fails with unrecognized image format

**Result**
Show what error or behaviour you're seeing.

![image](https://user-images.githubusercontent.com/81775318/140528127-4b41dd8c-77c8-4a88-a353-3262bedd8f12.png)

**Expected behaviour**

Build should resolve the image pointed to and download it or use the one already cached to my system.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. macos/Windows/Linux with details on versions or distro]
 - Rancher Desktop version
 - Kubernetes version
 
 Windows 10 Enterprise version 1909 build 18363.1854
 Rancher Desktop 0.6.0 and 0.6.1
 Kubernetes version v1.21.4

**Comment by jandubois** [comment]
I'm not sure how we can investigate this, given that we are not able to replicate your setup.

I wonder if there is some network range conflict between what your VPN client uses, and the WSL2 setup. However, I would expect it to affect Docker Desktop the same way.

> However building the same dockerfile on the same VPN with Docker Desktop works fine.

Can you tell if Docker Desktop is using "buildkit" or not, as the error comes from inside buildkit. Maybe share the output of a successful `docker build` run.

Is the problem particular to this specific image, or does it happen for other images as well?

**Comment by junekim3** [comment]
I experience the same issue.  I too use Pulse Secure.  I tried re-installing Rancher-Desktop but it did not resolve the issue.  I also encounter an issue that might be related which is when I start Rancher-Desktop while connected to VPN, it would just wait on "Waiting for Kubernetes...": 
![image](https://user-images.githubusercontent.com/25616801/141008829-1cf88276-5913-4ce1-be81-0753e380850e.png)
If I disconnect from my vpn, then it can continue and eventually start Kubernetes.  I don't have this issue with Docker-Desktop.  Please let me know if there's any additional information I can provide to help troubleshoot the issue.

**Comment by wstr-ncrum** [comment]
It appears to only be these Microsoft images. I have tried building simple dockerfiles that only contain the `FROM image:tag` line for ubuntu and node and both build successfully while using the Pulse Secure VPN

Below is the output of the successful docker build of the same dockerfile. While it doesn't say buildkit specifically there I did fat finger a docker command and the output of that referenced buildkit `failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount800945103/Dockerfile: no such file or directory` :

```powershell
C:\src\CloudArch\CloudArch_DeployDemo [final ≡ +0 ~1 -0 !]> docker build -f .\dotnetWebApp\Dockerfile -t dotnetwebapp:1.0.3-crum .
[+] Building 0.4s (18/18) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 769B
 => [internal] load .dockerignore
 => => transferring context: 35B
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0-alpine
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:6.0-alpine
 => [build 1/7] FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine
 => [internal] load build context
 => => transferring context: 5.31kB
 => [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine
 => CACHED [base 2/2] WORKDIR /app
 => CACHED [final 1/2] WORKDIR /app
 => CACHED [build 2/7] WORKDIR /src
 => CACHED [build 3/7] COPY [dotnetWebApp/dotnetWebApp.csproj, dotnetWebApp/]
 => CACHED [build 4/7] RUN dotnet restore "dotnetWebApp/dotnetWebApp.csproj"
 => CACHED [build 5/7] COPY . .
 => CACHED [build 6/7] WORKDIR /src/dotnetWebApp
 => CACHED [build 7/7] RUN dotnet build "dotnetWebApp.csproj" -c Release -o /app/build
 => CACHED [publish 1/1] RUN dotnet publish "dotnetWebApp.csproj" -c Release -o /app/publish
 => CACHED [final 2/2] COPY --from=publish /app/publish .
 => exporting to image
 => => exporting layers
 => => writing image sha256:6ccc16eac09924408de5be1549d7c837767feabba0f592924aa23f3e2dd9b896
 => => naming to docker.io/library/dotnetwebapp:1.0.3-crum
```

**Comment by gaktive** [comment]
Perhaps the new host-resolver may help with this issue.

**Comment by wstr-ncrum** [comment]
I was able to pull these images on PulseSecure vpn with v1.3.0 of Rancher Desktop today
![image](https://user-images.githubusercontent.com/81775318/172245158-4d2cc876-5bac-45a9-9b6a-839b74ba94d7.png)
