### ISSUE TITLE
portainer support on nerdctl/containerd

### ISSUE THREAD

**Issue by alsolh** [rancher-sandbox/rancher-desktop#918]
can you please do whatever fixes or changes required to support portainer?

![image](https://user-images.githubusercontent.com/22778662/140615572-5e48c0ca-51b6-4181-b150-3a71b576665d.png)

 - OS: windows
 - Rancher Desktop version - 0.6.1

note that nerdctl is aliased to docker

**Comment by AkihiroSuda** [comment]
containerd/nerdctl doesn't support Docker REST API (`/var/run/docker.sock`), so massive change would be needed on Portainer side.

**Comment by jandubois** [comment]
The next version of Rancher Desktop will offer you to choose between running `containerd` (and `nerdctl`), or `dockerd` and the `docker` cli.

Volume support is likely not going to work, at least initially; you may need to map it to a host directory instead.

I'm going to close this issue for now, but please try again once 0.7.0 is released, and open a new issue if you run into problems while using the `dockerd` backend.
