### ISSUE TITLE
Unable to install Rancher Desktop on Windows 10

### ISSUE THREAD

**Issue by pratapagiri** [rancher-sandbox/rancher-desktop#919]
I'm getting below error during installation:

![RancherDesktop-error](https://user-images.githubusercontent.com/16127392/140637389-e325d174-ce9d-48f8-aedb-1f06b639e1cc.PNG)

Windows 10 version: 1909
I have WSL2 installed and enabled.
Can someone suggest me how to resolve this issue?

**Comment by pratapagiri** [comment]
I have found the issue from logs. kubectl was not downloaded correctly. I have downloaded manually and placed in the bin folder. Now everything works fine.

**Comment by jandubois** [comment]
@pratapagiri Could you share the logs with us? It should not be necessary to download `kubectl`, and Rancher Desktop is actually downloading [kuberlr](https://github.com/flavio/kuberlr), which is a wrapper that makes sure you are always using a version of `kubectl` compatible with the version of kubernetes you are currently running.

If there are problems with this setup, we would like to know, so we can fix it also for other users. Thanks!
