### ISSUE TITLE
nerdctl doesn't handle environment variables properly

### ISSUE THREAD

**Issue by ruzickap** [rancher-sandbox/rancher-desktop#921]
**Bug**
It looks like Rancher Desktop + `nerdctl` doesn't handle the environment variables properly.

**To Reproduce:**
See the differences comparing to the standard `docker` command, where `nerdctl` doesn't print the `AAA` variable set by `-e AAA=bbb`:

```bash
$ docker run -it --rm -e AAA=bbb ubuntu sh -c 'echo ${AAA}'
bbb
```

```
$ nerdctl run -it --rm -e AAA=bbb ubuntu sh -c 'echo ${AAA}'
```

**Expected behaviour:**
Rancher Desktop + `nerdctl` should behave the same as "Docker" regarding environment variables.

**Setup (please complete the following information):**
 - OS: MacOS 11.6.1
 - Rancher Desktop version: 0.6.1

**Comment by ruzickap** [comment]
It is still the same for Rancher Desktop version: 0.7.0...

**Comment by jandubois** [comment]
This is related to https://github.com/lima-vm/lima/issues/251. As long as we implement `nerdctl` on top of `limactl shell`, we will have the problem with the double-evaluation of arguments.

**Comment by ruzickap** [comment]
This bug breaking compatibility with "Docker" is still present in Rancher Desktop version `1.0.0`. 
Let's wait for next version (`1.1.0`)...

**Comment by ruzickap** [comment]
I tested this with Rancher Desktop 1.4.1 and this issue was fixed in that version:

```bash
❯ nerdctl run -it --rm -e AAA=bbb ubuntu sh -c 'echo ${AAA}'
bbb
```

Closing...
