### ISSUE TITLE
Feature - Manage kubeconfig files from Rancher

### ISSUE THREAD

**Issue by abonillabeeche** [rancher-sandbox/rancher-desktop#928]
**For bugs, describe what you're seeing**
Currently, Rancher Desktop only allows to switch across contexts of a kubeconfig.

**For feature requests, describe what you'd like to add or change**
I'd like to be able to switch across contexts/clusters from within Rancher Desktop yet be able to utilize local tooling to manage that cluster.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login to Rancher via Rancher Desktop, either via user/pass or token.
2. Feed the Rancher Desktop `Kubernetes Contexts` from Rancher and the Rancher Desktop local cluster.
3. When the user switches contexts, utilize that context/kubeconfig from what is selected, to allow kubectl, helm, etc to work directly with that context without having to fetch specific kubeconfig files.

**Result**
We should be managing kubeconfig files from supported sources and simplifying the access to kubernetes clusters.

**Comment by jandubois** [comment]
> 2\. Feed the Rancher Desktop `Kubernetes Contexts` from Rancher and the Rancher Desktop local cluster.

I don't understand what this means.

> 3\. When the user switches contexts, utilize that context/kubeconfig from what is selected, to allow kubectl, helm, etc to work directly with that context without having to fetch specific kubeconfig files.

Isn't that how it works right now? Can you please elaborate on what the command line tools are doing now that you expect to change?

**Comment by jandubois** [comment]
@abonillabeeche I'm going to close this issue. Managing non-local clusters is outside the scope of the Rancher Desktop project. Even switching local contexts is just a convenience for the user; the primary focus is on providing a local container runtime and k8s cluster for development and testing.
