### ISSUE TITLE
[macOS] Auto update does not find latest releases

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#932]
**For bugs, describe what you're seeing**
Installing an older version, even though the auto-update checkbox is checked, it does not trigger the version updater.

**To Reproduce**
--> First way to reproduce
1. Remove/Uninstall older RD installation (remove folder `~/Library/Caches/rancher-desktop`)
2. Download RD dmg version `0.6.0` from [Releases](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v0.6.0)
3. Install RD `0.6.0` and wait until the app been loaded.
4. You should see on the General page, there is no attempt to update to the latest version `0.6.1`

--> Second way to reproduce
1. Make sure you already have RD `0.6.0` installed.
2. Navigate to Troubleshooting
3. Click on `Factory Reset`
4. Wait App to finish the reset
5. Open App again
6. You should see on the General page, there is no attempt to update the version to `0.6.1`  

**Result**
There's no attempts to update the RD version from `0.6.0` to `0.6.1`.

**Update.log**
```bash
021-11-09T20:25:35.467Z: Checking for update
2021-11-09T20:25:35.563Z: Generated new staging user ID: 310933a9-3d24-524a-b5b3-daafb9c6886b
2021-11-09T20:25:37.186Z: Error: Error: ENOENT: no such file or directory, open '/Users/evertonperes/Library/Caches/rancher-desktop/updater-longhorn.json'
```
**Expected behaviour**
Should trigger the version update and update the RD from `0.6.0` to `0.6.1`

**Screenshots**
![Screen Shot 2021-11-09 at 3 32 31 PM](https://user-images.githubusercontent.com/37411123/141008332-1adebea7-3b8e-4b0d-b7ba-5b53edf125a6.png)

**Setup (please complete the following information):**
 - OS: macOS Monterey `12.0.1`
 - Rancher Desktop version: `0.6.0`
 - Kubernetes version: `1.21.6`

**Additional Info**
Downgrading RD to `0.5.0` the version update feature has detected the latest release (`0.6.1`) properly.
On the second way to reproduce, the file `updater-longhorn.json` can't be recreated after perform `Factory Reset`. 
To recreate the file, you need to uninstall RD app and install it from scratch. This process will "fix" the version updater feature.

On `0.5.0`:
![Screen Shot 2021-11-09 at 3 56 34 PM](https://user-images.githubusercontent.com/37411123/141012137-48d55fd9-b671-4236-a5b8-316abe187395.png)

After restart the application:
![Screen Shot 2021-11-09 at 4 01 31 PM](https://user-images.githubusercontent.com/37411123/141012208-01ca991f-271b-4ee5-ba66-25972be36c53.png)

**Logs**
[0_6_0_RD_Logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/7508186/0_6_0_RD_Logs.zip)
[0_5_0_RD_Logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/7508235/0_5_0_RD_Logs.zip)

**Comment by jandubois** [comment]
@evertonlperes Has this problem been fixed, or can the issue be closed?

**Comment by evertonlperes** [comment]
> @evertonlperes Has this problem been fixed, or can the issue be closed?

This issue was fixed and I've missed to close this.

Thanks for catching.

**Comment by thumperward** [comment]
This still seems to be an issue: `~/Library/Caches/rancher-desktop/updater-longhorn.json` is owned by `root`, and so the updater fails. Changing its owner and restarting Rancher Desktop lets the updater run.

**Comment by jandubois** [comment]
> This still seems to be an issue: `~/Library/Caches/rancher-desktop/updater-longhorn.json` is owned by `root`, and so the updater fails. Changing its owner and restarting Rancher Desktop lets the updater run.

This seems wrong. Did you ever run Rancher Desktop as `root`? I know there has been some misleading advice in some of the comments about not making `/usr/local/bin` writable by the current user. I've been warning about this just yesterday: https://github.com/rancher-sandbox/rancher-desktop/issues/1155#issuecomment-1032851781

So if you've manually run Rancher Desktop as root, you will have to change those file permissions back manually. The only files created as root should be under `/opt/rancher-desktop`, or in `/var/run` and `/etc/sudoers.d`.

**Comment by thumperward** [comment]
> This seems wrong. Did you ever run Rancher Desktop as root? I know there has been some misleading advice in some of the comments about not making /usr/local/bin writable by the current user. I've been warning about this just yesterday: https://github.com/rancher-sandbox/rancher-desktop/issues/1155#issuecomment-1032851781

1155 is indeed the root cause here, but what's interesting is that it's that bug which causes this problem. RD doesn't seem to check for an update on its first run. Therefore, when a user runs it (as non-root) for the first time, they'll encounter the symlink permissions issue described there, and some portion of them (including me) will think of fixing this by re-running as root. And on _second_ start, an update check is performed, which results in that file being written with the wrong permissions. Obviously fixing 1155 so that the required symlinks can be created properly when running as non-root will stop anyone else from encountering this.

**Comment by jandubois** [comment]
> Obviously fixing 1155 so that the required symlinks can be created properly when running as non-root will stop anyone else from encountering this.

Indeed. For the meantime I've shown alternative ways to get the utilities on the `PATH` in https://github.com/rancher-sandbox/rancher-desktop/issues/1155#issuecomment-1032135332. And I've filed #1560, so we don't allow users to run Rancher Desktop as `root` at all.
