### ISSUE TITLE
Cannot pull images from rancher-desktop distro

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#937]
from https://rancher-users.slack.com/archives/C0200L1N1MM/p1636546065188900

>Only the POD named builder-XXXX keeps running into an error. At the end the status in the display is "Init:ImagePullBackOff".
My investigations so far show me that an image download via kim or also nerdctl always fails. My guess is that the DNS service is not set up correctly within the K3S environment.
DNS resolution in the WSL2 environment itself is error free.

>The "resolv.conf" inside the "rancher-desktop" distribution has a problem. It points to a DNS resolver from which no response comes. Also a change of the file does not bring directly the success, it is always reset.
The usual mechanism to control this via wsl.conf does not work for me.
BUT if I change the resolv.conf during operation to my locally available DNS resolver it works.
I can start a container directly via "nerdctl run --rm -it alpine".

**Comment by gaktive** [comment]
We've improved DNS resolution from 0.7.0 and higher. kim is also removed for 1.0.0 beta 1, so please try this again with that version and open a new ticket if you still see any problems.
