### ISSUE TITLE
Ability to disable traefik

### ISSUE THREAD

**Issue by Sebor** [rancher-sandbox/rancher-desktop#951]
**For feature requests, describe what you'd like to add or change**
It would be nice to have ability to install own ingress controller. For example our company uses `nginx` one and all our internal manifests/charts have appropriate definitions.

**Setup (please complete the following information):**
 - OS: MacOS Monterey
 - Rancher Desktop version: 0.6.1
 - Kubernetes version: 1.21.6

**Additional context**
Now I have to uninstall `traefik` and `traefik-crd` helm charts and install `nginx-ingress` one manually every time I switch/reinstall k8s version

**Comment by yuchanns** [comment]
I need to disable traefik too, then I found #926

**Comment by Sebor** [comment]
> I need to disable traefik too, then I found #926

Hmm, where file `lima.yaml` is located?

**Comment by yuchanns** [comment]
> > I need to disable traefik too, then I found #926
> 
> Hmm, where file `lima.yaml` is located?

The location is `~/Library/Application\ Support/rancher-desktop/lima/0/`. But it's not yet work as it is a feature of v0.7.0, though it merged into branch master :information_desk_person:. Just wait.

**Comment by Sebor** [comment]
Ok, thanks.
But anyway it's better to have more obvious way (GUI checkbox, for example)

**Comment by jandubois** [comment]
> But anyway it's better to have more obvious way (GUI checkbox, for example)

Agreed, but that won't make it into the next release, and maybe not into the one after either (there is still so much stuff to be done), so I wanted to have at least a way to configure things "manually" until there is a proper GUI way to do it.

**Comment by cronventis** [comment]
> The location is `~/Library/Application\ Support/rancher-desktop/lima/0/`. 

This is not true for windows.. right? Where can I change the settings for Windows?
