### ISSUE TITLE
Support for DeviceCgroupRules

### ISSUE THREAD

**Issue by kitayis15** [rancher-sandbox/rancher-desktop#953]
Rancher desktop doesn't support `--device-cgroup-rule=` option

https://docs.docker.com/engine/reference/commandline/create/#dealing-with-dynamically-created-devices---device-cgroup-rule

**To Reproduce**
Steps to reproduce the behaviour:
`nerdctl run --rm --cap-add=SYS_ADMIN --cap-add=CAP_MKNOD --device-cgroup-rule="b 7:* rmw"  "image"`

**Comment by AkihiroSuda** [comment]
Please open an issue in nerdctl repo
https://github.com/containerd/nerdctl/issues

**Comment by mattfarina** [comment]
@kitayis15 Thanks for the request. This isn't an issue that Rancher Desktop can address. As Akihiro points out, this is a change that needs to be made to nerdctl itself.
