### ISSUE TITLE
Show explainer dialog before asking for sudo password

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#955]
With #883 we now get a password prompt during startup with the sole explanation: "Rancher Desktop wants to make changes".

I normally decline sudo prompts when I don't expect them, and the application doesn't explain to me why it needs it. That is simply sound security practice.

It looks like there is no mechanism to add more text to the dialog. One pattern I've seen in other apps is that they display a heads-up dialog first: "Rancher Desktop needs your admin password so it can configure network settings. Click OK to get the password prompt!  [OK]" or something like that (will try to take screen shots when I see them again).

Rancher Desktop should add such a dialog to make it more likely that users will understand why RD needs to run an operation as admin and allow it. If they don't allow it, Lima will simply not be working; this is not an optional consent.

**Comment by ericpromislow** [comment]
Closed in #1012
