### ISSUE TITLE
Package M1 build of Rancher Desktop

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#957]
The required steps are shown in the description of #933:

* Start with the `x86_64` build
* Replace ISO and lima directory with `aarch64` versions
* Use arm64 versions of `helm`, `kuberlr`, etc
* Create DMG

For #831 we'll need some mechanism so that RD can tell if the assets are `x86_64` or `aarch64`.

**Comment by jandubois** [comment]
For completeness I want to mention that we _could_ decide to create a "universal" binary that works on both architectures. But that would include about 200MB of data in each release that would be unused on the platform, so I assumed we would reject that approach. Please let me know if you think I'm wrong on this!

**Comment by bdhoine** [comment]
I think it would be a good idea to run Rancher Desktop as a native application and maybe even package it in a universal binary. Seeing there are many binaries and distributions transferred I don't think size is that much of a factor compared to the global disk footprint of the full installation. I think Apple even advices to distribute universal binaries (but can't find an official statement in the docs for now)

**Comment by jandubois** [comment]
> I think it would be a good idea to run Rancher Desktop as a native application

I think so too, but I would also like to see it included in the very next release, and there is very little time left to get it in. So I'm willing to compromise in whatever way is necessary; we can always turn it into a native app later, but at least people can start using it, and providing feedback.

**Comment by jandubois** [comment]
Currently blocked by

* https://github.com/rancher-sandbox/rancher-desktop-docker-cli/issues/2
* https://github.com/flavio/kuberlr/issues/16

**Comment by jsoref** [comment]
https://github.com/flavio/kuberlr/releases/tag/v0.4.2 includes:
* [kuberlr_0.4.2_darwin_amd64.tar.gz](https://github.com/flavio/kuberlr/releases/download/v0.4.2/kuberlr_0.4.2_darwin_amd64.tar.gz)
* [kuberlr_0.4.2_darwin_arm64.tar.gz](https://github.com/flavio/kuberlr/releases/download/v0.4.2/kuberlr_0.4.2_darwin_arm64.tar.gz)

With those, I was able to do:
```sh
% lipo -create kuberlr_0.4.2_darwin_amd64/kuberlr kuberlr_0.4.2_darwin_arm64/kuberlr -output kuberlr
% file kuberlr
kuberlr: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
kuberlr (for architecture x86_64):	Mach-O 64-bit executable x86_64
kuberlr (for architecture arm64):	Mach-O 64-bit executable arm64
% ./kuberlr version
kuberlr version: 0.4.2 (tagged as "v0.4.2") 2022-06-15T12:26:44Z go1.17.11
```
