### ISSUE TITLE
[Feature Request]- Install Rancher Desktop with homebrew

### ISSUE THREAD

**Issue by bdhoine** [rancher-sandbox/rancher-desktop#966]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

At the moment the install is done by using the github release page. It would be nice if in the future we could do

```
brew install rancher-desktop
```

### Proposed Solution

Add Rancher Desktop formula to the homebrew cookbook

### Additional Information

More info can be found on: https://docs.brew.sh/Adding-Software-to-Homebrew
If this sound good for the maintainers I would be happy to contribute this

**Comment by jandubois** [comment]
Due to homebrew cask naming conventions, the `-desktop` suffix is dropped from the cask formula name. You can already install via `brew`:

```console
$ brew info rancher
rancher: 0.6.1 (auto_updates)
https://rancherdesktop.io/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/rancher.rb
==> Name
Rancher Desktop
==> Description
Kubernetes and container management on the desktop
==> Artifacts
Rancher Desktop.app (App)
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/helm (Binary)
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kim (Binary)
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl (Binary)
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/nerdctl (Binary)
==> Analytics
install: 206 (30 days), 327 (90 days), 327 (365 days)
```
