### ISSUE TITLE
System proxy with wpad

### ISSUE THREAD

**Issue by aleksey005** [rancher-sandbox/rancher-desktop#976]
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

--

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Windows User Only

VPN Cisco AnyConnect, Kaspersky, System proxy with wpad https

### Actual Behavior

Not communicate to repo https://desktop.version.rancher.io/v1/checkupgrade

### Steps to Reproduce

Install Rancher Desktop 0.6.1, enter admin password when prompted by the install script.

### Result

All logs clean, update log - https://desktop.version.rancher.io/v1/checkupgrade one record

### Expected Behavior

A working installation.

**Comment by gaktive** [comment]
@aleksey005 are you able to repro this on the latest version of Rancher Desktop? If so, do you have any additional logs and other information regarding your VPN setup? I'm curious what the DNS lookup is looking at.

**Comment by aleksey005** [comment]
Hello.  I don't have any VPN logs or settings.  Now it’s not relevant for me, because.  I use a direct connection to the Internet.

**Comment by jandubois** [comment]
> Now it’s not relevant for me

I assume this is no longer reproducible for you then, so I'm going to close this issue. Please open a new one if you run into problems again!
