### ISSUE TITLE
nerdctl fails with Error unmounting `/mnt/wsl/rancher-desktop/run/nerdctl-tmp.*/input.*`: invalid argument

### ISSUE THREAD

**Issue by cpbotha** [rancher-sandbox/rancher-desktop#984]
### Rancher Desktop Version

0.6.1

### Rancher Desktop K8s Version

1.21.6

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Build 22000.348

### What CPU architecture are you using?

x64

### Windows User Only

N/A

### Actual Behavior

When I invoke `nerdctl build` with a Dockerfile, something I have confirmed to work under Rancher Desktop 0.6.1 on Linux, I see the following errors:

```
2021/11/21 21:28:39 Error unmounting /mnt/wsl/rancher-desktop/run/nerdctl-tmp.1905392857/input.1713537599: invalid argument
2021/11/21 21:28:39 Error parsing arguments: not a directory
```

At that moment, the only sub-directory in `/mnt/wsl/rancher-desktop/run/` is `data`, which seems to contain the rancher-desktop WSL2 image's filesystem.

### Steps to Reproduce

Invoke `nerdctl build` on any Dockerfile.

The rest of my wsl versions are as follows:

```
WSL version: 0.50.2.0
Kernel version: 5.10.74.3
WSLg version: 1.0.29
Windows version: 10.0.22000.348
```

### Result

Error as shown above. `nerdctl build` now blocks until killed.

A few seconds after being killed from a different terminal tab, the tab running nerdtcl displays `read failed 5: I/O error`

if I run `nerdctl` again, it gives the same error, with the same temp directory stems, just different numbers.

After a few more times, `nerdctl build` simply blocks the moment I invoke it, with no error messages. A restart of rancher desktop (during which I can see that the rancher-desktop WSL2 image is terminated) does not change this blocking behaviour.

### Expected Behavior

`nerdctl build` should build the image, like on Linux.

**Comment by ericpromislow** [comment]
I can't reproduce the problem, running `nerdctl build` from both a Windows powershell as well as an Ubuntu WSL prompt.

If you don't need existing workloads, I would consider deleting this subsystem -- `Factory Reset` should do it.
