### ISSUE TITLE
Unmounting missing device error on WSL (dev -> 0.7.0)

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#992]
### Rancher Desktop Version

0.7.0 dev

### Rancher Desktop K8s Version

n/a

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows [Version 10.0.19043.1348] (Home?)

### What CPU architecture are you using?

x64

### Windows User Only

no

### Actual Behavior

This might not be an issue, but I need to write it up.

I was testing a branch, specifically mook-as-docker-api-intercept, commit `eda31ad `.

I had a stale system, and the docker commands weren't working, so I figured I'd clean up the WSLs. But k8s failed to come up. Here's what happened:

From wsl.log:

```021-11-23T19:23:57.642Z: Registered distributions: Ubuntu,rancher-desktop,rancher-desktop-data
2021-11-23T19:23:57.642Z: data distro already registered
2021-11-23T19:24:00.518Z: Unmounting missing device /dev/sdd: 225 224 8:48 / /mnt/wsl/rancher-desktop/run/data rw,relatime shared:2 - ext4 /dev/sdd rw,discard,errors=remount-ro,data=ordered
浵畯瑮›慣❮⁴湵潭湵⁴洯瑮眯汳爯湡档牥搭獥瑫灯爯湵搯瑡㩡删獥畯捲⁥畢祳2021-11-23T19:24:00.626Z: WSL failed to execute wsl.exe --distribution rancher-desktop-data --exec busybox umount /mnt/wsl/rancher-desktop/run/data: Error: wsl.exe exited with code 1
```

Going to unregister the WSL distros, reboot the machine, and see what happens.

### Steps to Reproduce

n/a

### Result

n/a

### Expected Behavior

Working RD

**Comment by jandubois** [comment]
@ericpromislow Is this still something we can investigate, or is it stale and can be closed? There is not really enough information to reproduce the problem.

**Comment by ericpromislow** [comment]
I couldn't repro it. Let's close it.
