### ISSUE TITLE
Epic: Rancher-Desktop Test Automation

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#996]
This is an epic to track down all task related to the Test Automation

###  Working
- [x] #885

### ToDo
- [x] #2809 
- [x] #2367 
- [ ] #2368 
- [ ] #1690
- [x] #1634
- [ ] #1621
- [x] #1593
- [x] #1200
- [x] #1065 
- [x] #1134
- [x] #1135
- [x] #942
- [ ] #1256
- [x] #1319
- [ ] #1545
- [x] #1548

### Done
- [x]  #949 
- [x] #936
- [x] #913
- [x] #1288
- [x] #1025
- [x] #1133
- [x] #1268
- [x] #1482
- [x] #1577
- [x] #1153

**Comment by jandubois** [comment]
Closing the epic; the remaining issues can be found via GitHub labels.
